Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

Changing the CE 1.0 ArmorPenetration to ArmorPenetrationBlunt using as a reference the Gun_Triple_Rocket and Gun_Doomsday_Rocket ArmorPenetration_Blunt values for their respective barrels.
- ArmorPenetrationBlunt value of 3.5 for the Heavy Charge Blaster, Charge Lance, Inferno Cannon and Minigun's melee attack with the barrel. Inspired by Gun_Triple_Rocket and Gun_Doomsday used values for Core Patch.
- MeleeCooldown of 2.44 to match the reference values.
- Same file.
The lack of current armorpenetration syntax make red errors pop up due to incompatibility.
- Implement in Line 74 along with Gun_Minigun and Gun_TripleRocketLauncher patchoperationreplace.

Change ArmorPenetration to ArmorPenetration_Blunt for Heavy Charge Blaster, Charge Lance, Inferno Cannon and Minigun's melee attack with the barrel 

---

Patches/Forsakens/Forsakens_CE_Patch_Ammo_ForsakensArrows.xml
Patches/Forsakens/Forsakens_CE_Patch_Ammo_ProjReskin.xml
Patches/Forsakens/Forsakens_CE_Patch_ApparelDefs.xml
Patches/Forsakens/Forsakens_CE_Patch_BodyDefs_Forsaken_Body.xml
Patches/Forsakens/Forsakens_CE_Patch_Drugs.xml
Patches/Forsakens/Forsakens_CE_Patch_PawnKinds_Forsaken.xml
Patches/Forsakens/Forsakens_CE_Patch_Race_Forsaken.xml
Patches/Forsakens/Forsakens_CE_Patch_Race_Nightling.xml
Patches/Forsakens/Forsakens_CE_Patch_Scenario.xml
Patches/Forsakens/Forsakens_CE_Patch_ThingDefs_Weapons.xml
Patches/Forsakens/Forsakens_CE_Patch_ThingDefs_Weapons_BlackHydra.xml

* Add compatibility patches for Forsakens, as part of the FastTrack merger
* Add conditionally-patched mod-unique ammo and projectiles:
* Forsaken arrow (stats identical to Steel Great Arrows, ammo textures implemented in CE ThirdParty folder, projectile texture directly referenced from original mod)
* Reskinned projectile variants of 8x35mm Charged cartridge, 12 Gauge Charged shotgun cartridge and 5x35mm Charged cartridge ammo, allowing Forsaken weapons to use generic CE Charged ammo while firing their own projectiles
- Contributes towards #10
* Added `HeadAttackTool` to Forsaken race, to address @N7Huntsman's concerns regarding weird AI behaviour if pawns become armless
* Apparel sharp and blunt AP stats balanced to latest CE standards
* Forsaken fabric apparel are only craftable from …

Add Forsakens patches

---

Patches/Core/ThingDefs_Misc/Apparel_Various.xml

Mass of recon armor fixed. Previously there were 2 lines 'replacing' the mass of regular power armor.
- [x ] Compiles without warnings
- [x ] Game runs without errors
- [x ] (For compatibility patches) ...with and without patched mod loaded
- [x ] Playtested a colony (specify how long)

Update to Recon armour mass

---

Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Buildings/TurretGatlingGun.xml

- Removed ` CompProperties_Explosive ` from the Gatling turret

Gatling turret no longer goes boom when destroyed

---

Defs/ThingDefs_Misc/Weapons_Ranged.xml

Currently, the break action grenade launcher fires awfully fast in comparison to the Milkor, given that it's single fire and lacks an ejector.

Increased grenade launcher reload time.

---

Patches/More Practical Traits/TraitDefs/Traits_MPT.xml

Added CE specific stats to new traits from 1.1 version.
Armor stats have been adjusted so that equivalent 100% protection from vanilla is equal to a steel vest.
Traits that previously provided carry capacity added 1/2 of that stat as a flat buff to bulk/weight capacities. This has been reduced to 1/5 of the bonus carry capacity in order to make them less seriously impactful in terms of loadouts.

Mpt1.1 fixes

---

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_BodyPartDensity.cs

`GetBaseValueFor` is inherited from `RimWorld.StatWorker`, and is overridden here.  As this override appears to be intentional, the `new` keyword is supposed to be used (generates a warning if it is not).
Change the name of `GetBaseValueFor`, which leaves access to the base class's version.
Not declare it abstract here, 
- [❌] Compiles without warnings (1 fewer warning though)
- [✔] Game runs without errors
- [✔] Playtested a colony (minutes)

add `new` keyword to GetBaseValueFor, to silence warning

---

Make.py

This script extracts the referenced libraries and sources from the `CombatExtended.csproj` file and automates passing them as arguments to `mcs`.  This ensures that the version of the `System.*.dll` and similar libraries used are the ones used by RimWorld, which is otherwise a challenge on Linux.
Makes compiling on Linux as simple as calling `python3 Make.py` from `$RIMWORLD/Mods/CombatExtended`
There are basically 2 IDEs for C# on Linux.  Neither one is particularly attractive.
JetBrain's Rider is not free, and is incredibly resource hungry.
MonoDevelop is cumbersome, unstable, *and* resource hungry.  
There are other, excellent editors which can supply code completion, navigation, and the usual IDE features for C#, except they don't handle reading `.csproj` files to find the settings …

Add script for compiling on Linux

---

Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs
Source/CombatExtended/CombatExtended/PatchOperationFindMod.cs

Just fixes the remaining unused variable warnings.
In `PatchOperationFindMod`, `modName` was `private`, but doesn't get set within the file, it gets set via reflection elsewhere, but the compiler issues a warning.
Easiest way to silence the warning is to change it to protected.
- [✔] Compiles without warnings (finally, if all the other patches are also applied)
- [✔] Game runs without errors
- [✔] Playtested a colony (minutes)

Fix remaining unused variable warnings.

---

Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedMedieval.xml
Patches/Vanilla Weapons Expanded/Medieval_Ranged.xml
Patches/Vanilla Weapons Expanded/Neolithic_Ranged.xml

Fixes the missing ` thingCategories ` on the throwing rocks / knives from Vanilla Weapons Expanded and the Tomahawak from Settlers, can be stored now.

VWE / VFE-Settlers Fixes

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_CheckReload.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/SightUtility.cs
Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs
Source/CombatExtended/CombatExtended/Things/Smoke.cs
Source/CombatExtended/Harmony/Compatibility/Harmony-GraphicApparelDetour.cs
Source/CombatExtended/Harmony/Harmony-Fire.cs
Source/CombatExtended/Harmony/Harmony-FloatMenuMakerMap.cs
Source/CombatExtended/Harmony/Harmony-JobDriverWait.cs
Source/CombatExtended/Harmony/Harmony-JobGiver_UnloadYourInventory.cs
Source/CombatExtended/Harmony/Harmony-PawnColumnWorkers.cs
Source/CombatExtended/Harmony/Harmony-Pawn_HealthTracker.cs

Managed to miss this commit with the previous cleanup, just removes the rest of the unused variables causing warnings.

Cleanup unused variables

---

Patches/Nihal/PawnKinds_NiHal.xml

Ni'hal Militia pawns spawn with ammo now

Fixes certain Ni'hal pawntypes not spawning with ammo

---

Defs/ThingDefs_Misc/Weapons_RangedNeolithic.xml
Patches/Core/Drugs/Drugs.xml

- Add `NeolithicRangedHeavy` to Pila, since it currently lacks it and so doesn't spawn on tribal Heavy Archers.
- Change GoJuice patchop to account for RW change.

Pilum tags, fix GoJuice patch

---

Patches/Save Our Ship 2/Apparel_SOS2.xml
Patches/Save Our Ship 2/PawnKindsDefs_SOS2.xml

Standardized SOS2 apparel with its CE counterpart.
Added Ammo to SOS2 space crews.

Save Our Ship 2 Patch Update

---

Patches/Core/ThingDefs_Misc/Things_Special.xml

Adjusts some of the fire values, which should hopefully result in fires not spreading as aggressively in the rain, without significantly weakening brush fires in dry weather.

Tweak fire balance

---

Patches/VGP Garden Fabrics/VGP Garden Fabrics.xml
SupportedThirdPartyMods.md

VGP fabrics adds linen Cloth, Hemp and blended wools. Sharp, Blunt and Heat stats are too high and have to be tweaked to fit the new armor models
- just tweaking armor stats for these new fabrics
- heat stat is the same as normal cloth
- linen is supposed to be 30% stronger than cotton fabric, so values were adjusted
- N/A
- I like the VGP fabric mod, but the stats were way too high, close to hyperweave/synthread
- N/A
- [] (For compatibility patches) ...with …

patch for Vegetable Garden new fabrics

---

Patches/Dragon's Descent/Drugs/Draconic_Ambrosia.xml
Patches/Dragon's Descent/Drugs/Dragon_Blood_Potion.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Common_Dragon.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Dragon_Base.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Rare_Dragon.xml
Patches/Insects have chitin/ThingDefs_Items/Chitin.xml

- Made a patch for 'Insects have chitin'.
- Updated the 'Dragon's Descent' patch to the latest version of 'Dragon's Descent'.
- For the 'Insects have chitin' patch, I based it off the 'Alpha Animals' patch's chitin and Core patch's wood log. I used wood log because the chitin is categorized as 'Woody'.
- For updating the 'Dragon's Descent' patch, the latest version of the mod had changes which caused the patch to no longer work. The mod also added more items to the game.

Updated 'Dragon's Descent' patch and added 'Insects have chitin' patch.

---

Source/CombatExtended/Harmony/Harmony-GlobalControls.cs

- Added a null check to `Harmony-GlobalControls.cs`.
- Closes #89.
- Abandoning your last colony means that there is no longer a `CurrentMap` (`CurrentMap` becomes null). Adding a null check fixes the referenced issue.

Added a null check to Harmony-GlobalControls.cs

---

Royalty/Patches/AbilityDefs/Abilities.xml

- Increase the range of all Psycasts by 15%
- Increase from radius of Smokepop from 3.5 to 4.0
Close #125

Increase range of all psycasts 15%, increase smokepop psycast radius.

---

Patches/More Vanilla Turrets/MVT_CE_Patch_Ammo_Shells.xml
Patches/More Vanilla Turrets/MVT_CE_Patch_Buildings_Security.xml

This is a port of the in-progress patch for More Vanilla Turrets.
Changes from that PR:
- Vulcan Turret ammo up to 400 from 100 (10 bursts per reload, maybe needs to be higher)
- Military Grade Turret (auto and manned version) changed to use 7.62 NATO ammoset from previously used .50BMG ammoset. 
- Rocket Complex range up to 58 from 48.
- From https://github.com/CombatExtendedRWMod/CombatExtended/pull/1165

Initial Port of MVT Patch

---

Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml

Quick change to Royality patch file to remove error caused by Glitter Tech.
The original patch added a second version of statBases to the AutoMortar (the first added by Glitter Tech), confusing RimWorld.
This version checks for its existence first, to avoid duplication.
None
Fixed an incompatibility with Glitter Tech.
Removing Console Spam (Error)
I did not test if values make sense, i just made sure that they were correctly added.

Fixing Glitter Tech Compatibility Error

---

Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Weapons.xml

Added a patch for the heavy mace from Vanilla Factions Expanded - Medieval 
Values for the heavy mace were calculated using the vanilla mace on the melee stats sheet, but I increased the mass from 1.25 to 1.75, and range from 60 to 90. 
I also increased the bulk slightly, from 3.5 to 4.5, since this is a larger weapon.

Added VFEM_MeleeWeapon_HeavyMace patch

---

Patches/Genetic Rim/Bodies/GeneticRim_CE_AlphaHybrids_Patch_Bodies.xml
Patches/Genetic Rim/Bodies/GeneticRim_CE_Patch_Bodies.xml
Patches/Genetic Rim/GeneticRim_AA_CE_Items_Resource_Stuff.xml.xml
Patches/Genetic Rim/GeneticRim_CE_Gas.xml
Patches/Genetic Rim/GeneticRim_CE_Hediffs_Local_Implants_Animals.xml
Patches/Genetic Rim/GeneticRim_CE_Hediffs_Local_Implants_Humanoid.xml
Patches/Genetic Rim/GeneticRim_CE_Items_Resource_HybridAnimalProducts_Wools.xml
Patches/Genetic Rim/GeneticRim_CE_Patch_Projectiles.xml
Patches/Genetic Rim/GeneticRim_CE_Patch_Projectiles_AlphaAnimalPatch.xml
Patches/Genetic Rim/GeneticRim_CE_Patch_VerbShootCE.xml
Patches/Genetic Rim/GeneticRim_CE_Patch_VerbShootCE_AlphaAnimalPatch.xml
Patches/Genetic Rim/GeneticRim_Damage_CE/GeneticRim_CE_Patch_DamageDef.xml
Patches/Genetic Rim/GeneticRim_Damage_CE/GeneticRim_CE_Patch_DamageDef_AlphaAnimalPatch.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_AberrationsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_Alpha_HybridCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_ArchoCent_CE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_BearhybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_BoomalopehybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_CathybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_ChickenhybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_InsectoidhybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_MechanoidhybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_MuffalohybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_ParagonCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_ReptilehybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_RodenthybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_ThrumbohybridsCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_WolfhybridsCE.xml

Supports for all vanilla Genetic Rim animals+Alpha Animal Hybrids, including any new weapons, materials and implants. Further tweaks might be added in the immediate future.

Added support for Genetic Rim+Genetic Rim Alpha Animal Patch 

---

Defs/Ammo/Flamethrower.xml
Defs/ThingDefs_Misc/Apparel_Headgear.xml
Defs/ThingDefs_Misc/Apparel_Various.xml

- Update jellied chemfuel recipe to match the item's name
- Composite vest moved into Armor sub-section in outfit/stockpile menus
- Gas mask moved out of Armor sub-section in outfit/stockpile menus

Misc tweaks

---

Patches/Red Horse Faction War Mongrels/RH_WarMongrels_CE_Patch_Apparel_Armor_Headgear.xml
Patches/Red Horse Faction War Mongrels/RH_WarMongrels_CE_Patch_Apparel_Armor_Headgear_Crafting_Rimfeller.xml

Rimfeller Synthamide is probably kevlar as such we can PROBABLY subsitute it for devilstrand in some manafacturing cases, this patch nerfs War Mongrel M89 Helmets to PASGT levels since they were  the essentially the same.

War Mongrel Helmets nerf to PASGT Levels

---

Patches/DefensiveMachineGunTurretPack/DMGT_CE_Patch_ThingDefs_Defensive_Turrets.xml
Patches/DefensiveMachineGunTurretPack/DMGT_CE_Patch_ThingDefs_Sentry_Turrets.xml
Patches/Turret Collection/TurretCollection_CE_Patch_Turrets.xml

Increased mag size & shot count for miniguns and other rotary machine guns from patches for the following mods:
- Defensive Machine Gun Turret Pack
- Turret Collection
- Resolves #174 
- Requires #179 
- New mag sizes based on real-life stats
- Shot counts based directly on CE spreadsheet calculations (and not watered down as a consequence of the original reduced ammo capacity)
- Reduces turret downtime due to more frequent ammo depletion from faster firing rates
Note: all testing conducted using the experimental build for #179

Increase minigun mag size & shot count for various patches

---

Defs/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Vanilla Weapons Expanded - Grenades/Apparel_Packs.xml
Patches/Vanilla Weapons Expanded/Industrial_Grenades.xml
Patches/Vanilla Weapons Expanded/Neolithic_Ranged.xml
SupportedThirdPartyMods.md

Patches the core grenades (frag, emp, and molotovs) for VWE - Grenades. The remaining grenade belts are patched within VWE - Grenades itself.

Patch Vanilla Weapons Expanded - Grenades

---

Patches/Androids Expanded/AlienRace/AlienRace_Droids.xml
Patches/Androids Expanded/AlienRace/AlienRace_Drones.xml
Patches/Androids Expanded/Bodies/Bodies_DroidsExpanded.xml

Race appropriate defs (Bodies, RaceDefs) for Androids Expanded. Androids expanded overrides the drone bodydef from the original with one that has significantly more HP for some reason, which means they get a power increase in general but it works, probably just needs a reduction on their HP (The advanced battledroid, for example, can tank A HEAT rocket to the torso as long as it doesn't hit an internal 'organ', thanks to its 400 hp).

Androids Expanded Patch

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Fix unpatched tool in Gun_ChargeBlasterHeavy, that causes errors when opening the info window for this weapon.

Fix heavy charge blaster info window error

---

Patches/Dragon's Descent/Scenarios/Scenarios_DragonsDescent.xml

Recently Dragon's Decent removed the Pila from their starting scenario and the operation adding the extras failed, this fixes it.

Dragon's Descent Tweak

---

Patches/Vanilla Factions Expanded - Insectoids/Ammo/MadnessShell.xml
Patches/Vanilla Factions Expanded - Insectoids/Hediffs/Hediffs_Berserk.xml

- Removed trade tags from Psychic Shell, should no longer appear on trader's inventory.
- Fixed berserk effect not applying on impact.

VFE - Insectoids

---

Patches/Core/ThingDefs_Misc/Apparel_Various.xml

-Increase parka cost from 80 material to 110
-Increase parka mass from 2kg to 2.5
-Reduce jacket cost from 70 to 60
-Reduce flak jacket stuff cost from 85 to 70
-Increase flak jacket base MPa Armor value from 0.5 to 1.5
-Increase flak pants base MPa Armor value from 0.5 to 1.5
-Reduce T Shirt stuff cost from 40 to 20
-Reduce Button up T shirt stuff cost from 45 to 25
-Reduce pants cost stuff cost from 40 to 20
These were originally Tostov's proposed changes and here's their reasoning for [it.](https://media.discordapp.net/attachments/305582566210273290/747364415023874068/unknown.png)
I support these changes because Parka + Tribalwear is the most cost efficient use of your materials. You pay more for less protection with normal clothes and flak jackets. These reduced costs in theory will …

Clothing Changes

---

Patches/Core/ThingDefs_Misc/Apparel_Various.xml

Addresses a quirk between the Power Armor and Recon Armor, wherein pawns wearing the Power Armor are faster than ones in Recon Armor because they're less affected by the move speed malus associated with weight carried, because the penalty is a function of weight/total capacity.

Balance Power Armor vs Recon Armor weight/speed

---

Patches/Better Infestations/Race_Insect.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Apparel_Footwear.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Apparel_Handwear.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Apparel_Industrial.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Apparel_Medieval.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Apparel_Neolithic.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Headgear_Industrial.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Footwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Handwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Industrial.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Medieval.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Neolithic.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Headgear_Industrial.xml

- Updated Better Infestations patch's mod name check to account for version change;
- Updated Vanilla Armor Expanded and Vanilla Apparel Expanded mod checks to use the one supplied by vanilla RimWorld in case `CombatExtended.PatchOperationFindMod` stops working;
- Modified VArE's heavy marine armor's stats to make it more in line with Royalty DLC's cataphract armor;
- Modified material costs for VAppE's shirts, pants, shoes and gloves and VarE's fabric-based medieval armors to account for the changes of vanilla shirts' and pants' costs;
- Porbably some other things that I forgot to document.

Updates for Better Infestations, Vanilla Armor Expanded and Vanilla Apparel Expanded mod patches.

---

Defs/Ammo/Pistols/50AE.xml

None
Makes .50 AP use the correct bullet.
I had posted about it on discord earlier.
Saw the bug yesterday, might aswell fix it.
None
Before and after

Fixes .50 AE AP being the same as HP

---

Patches/Vanilla Brewing Expanded/Alcohol.xml
Patches/Vanilla Brewing Expanded/ThingDefs_Items.xml

Rewrote the alcohol patches to match the new structure of Brewing Expanded.
For testing purposes, here's my local version of [Vanilla Brewing Expanded](https://github.com/CombatExtended-Continued/CombatExtended/files/5087406/VanillaBrewingExpanded.zip)
**Currently Oskar is on holidays and the mod won't be updated until he comes back**
Cider is added through a patch so we can't normally patch it like other drinks unless CE is loaded after Plants / Brewing Expanded, the case is that this isn't very user friendly and knowing that users will not always load CE after these mods and will cause errors we decided to add a new base drug that inherits from the vanilla drug that includes tools. If Brewing Expanded detects that Plants Expanded is installed and adds the cider to the game this won't …

Vanilla Brewing Expanded

---

Patches/Core/DamageDefs/Damages_LocalInjury.xml

Increases the damage and armor penetration of the base bomb damage def, since this is what orbital strikes inherit their damage from. The damage has gone up to 635 and the penetration to 63.5MPa, based on 20L thermobaric payload.
It is worth noting that this also increases the damage of the 'blast' from falling meteors and ship parts, which I don't see as an issue, but could be individually altered if required (altering the orbital bombardment skyfaller doesn't seem to be possible via pure XML outside of indirectly doing it via altering the bomb damage def)
This fixes the longstanding issue where orbital bombardment targeter strikes have done little to nothing to armored targets
While it may be difficult, it could be possible to make the orbital bombardment skyfaller/verb operate using CE …

Bomb Damage Adjustment

---

Patches/Vanilla Furniture Expanded - Security/ThingDefs_Manned.xml

- Increased the fillPercent of the Ballista to 0.85 because it had a value of 0.4 meaning it couldn't fire over any kind of cover.

Increase ballista fillPercent

---

Defs/Ammo/HighCaliber/20x110mmHispano.xml

Fixed wrong label of 20x110mm Hispano cartridge (Sabot)

Fixed Ammo label

---

Defs/Bodies/BodyParts_Mechanoid_Internal.xml

Swap the capacites on coolant tank and power core so that them being damage matches the capacites for a mechanoid that are being reduced.
Coolant tank reduced the ingame capacity for power generation, and conversely the power core reduced the coolant ability.

Swap power core and coolant tank capacities

---

Patches/Rimsenal Collection/Federation/ThingDefs_Misc/Fed_Apparel.xml

Fixed xpath for unity guard helmet patches.
Reduced unity guard armor blunt armor to equal to steel vest, as even with full frame foerum provides terrible blunt impact resistance.
Removed feet coverage on unity guard armor as it doesn't cover the legs either
Slightly tweaked foerum sharp armor to match plasteel.

Fixes/tweaks to Federation apparel

---

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs

No change in the output assembly, just helps the mono compiler figure out to iterate over worn apparel.
Without this fix, `mcs` (the mono compiler) fails to compile with 
error CS0266: Cannot implicitly convert type `System.Collections.Generic.List<RimWorld.Apparel>.Enumerator?' to `System.Collections.Generic.List<RimWorld.Apparel>.Enumerator'. An explicit conversion exists (are you missing a cast?)
It's probably possible to specify the cast in a single line, but that is likely less readable.

Help mono figure out how to cast with possible null values

---

Patches/Rimefeller/Items_Resource_Stuff.xml

Adds CE specific stuff catergories so armored vests and melee weapons can be made of rimefeller composite

Rimefeller Composite Fix

---

Patches/Rabbie The Moonrabbit/PawnKindDefs/RB_PawnKind.xml
Patches/Rabbie The Moonrabbit/ThingDefs_Items/Items_Resource_Stuff.xml

Added CE stats for Moon Silk material
Added forced backpack to some pawn type defs to ensure they spawn with ammo.
Removed SoftArmor catergory from moonweave, as the armor value is probably too low to be considered for soft armor type apparels.

Rabbie the Moon Rabbit Fixes

---

Defs/Ammo/Grenade/20x42mmGrenade.xml
Defs/Ammo/Grenade/25x40mmGrenade.xml
Defs/Ammo/Grenade/25x59mmGrenade.xml
Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/35x32mmSRGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Grenade/40x47mmGrenade.xml
Defs/Ammo/Grenade/40x53mmGrenade.xml
Defs/Ammo/Grenade/40x53mmVOG25Grenade.xml
Defs/Ammo/Grenade/50mmGS50Grenade.xml
Defs/Ammo/Grenade/83mmPIATGrenade.xml

Changes launcher HE grenades to use the fragmentation calculation for frag ammo type rather than HE, increasing the frag count and removing large fragments from the pool.
Remove/reduce chance of smoke from avaliable options for loadout generation because the AI cannot make effective use of it.
In their current state, grenade launched HE grenades are largely ineffective in their anti-personnel due to low overall damage + penetration and the requirement that they practically need to score direct hits to inflict damage on a target, while a relatavely low velocity projectile and high innate deviation.
Give HE fragmentation grenades a new ammo type on the sheet that applies/uses a different fragmentation amount formula, and possibly uses a different fragmentation projectile.
lperkins2 …

Increase grenade launcher grenade fragmentation effect

---

Patches/Individuality/Traits_Patch_CE.xml

Strong Back from Individuality now 20 CarryWeight and 20 CarryBulk instead of 20 CarryCapacity
CarryCapacity is not used.  FalloutTraits also offers a Strong Back trait, with the same carry capacity boost.  It is replaced with a 20pt bulk and mass boost, so I used the same here.

Patch Strong Back from SYR Individuality like Strong Back from FalloutTraits

---

Patches/Kijin 2.0/ThingDef_Misc/Kijin_Weapons_Melee.xml

Adds patch for Kijin fireblade weapon
* Note: Due to the implementation method on their end, the patch may not always work (i.e. it only works if CE is loaded after the kijin mod, afaik) since the weapon is a patched in def. There's not really much that can be done about that on our end afaik.

Kijin Fireblade Patch

---

Patches/Vanilla Factions Expanded - Insectoids/ThingDefs_Items/Items_Resource_Leathers.xml

Added stuff catergories for chitin so weapons/armor vests can be made of it in CE.
Buffed chitin by reducing weight of stuff made of it, since it in vanilla has a very quick attack rate. Lowed blunt damage for weapons made of it since it already attacks quite quickly.

Tweaks to Vanilla Factions Expanded Chitin

---

Patches/The GiantRace/PawnKindDefs/Giant_PawnKind.xml
Patches/The GiantRace/Scenario/Giant_Scenario.xml
Patches/The GiantRace/ThingDefs_Misc/GiantApparel.xml
Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Melee.xml
Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Ranged.xml
Patches/The GiantRace/ThingDefs_Races/AlienRace_Giantlike.xml
Patches/The GiantRace/ThingDefs_Races/Giant_Mammoth.xml
SupportedThirdPartyMods.md

CE patch stuff for 'The GiantRace', for apparel/weapons/races/pawnkinds/scenario.
Thanks to their generally large size, most of their weapons have significant mass thanks to square cube law, and consequentely, high blunt penetration. This mostly works fine and gears them as a offensively powerful race, but lacking in good ranged or defensive options. The raiders, since they lack consistent armor, are still fairly suppressable despite reduced suppressability, and will still go down to pain from automatic gunfire, even if they can weather some of it, but are a bit like manhunter elephants in that if they get close they can do some significant damage.
The 'base' for the racedef shares a name with another and I wager will change in the near future, but I'd ideally like to get this patch in …

The GiantRace CE patch

---

Patches/Save Our Ship 2/Hediffs_SOS2.xml
Patches/Save Our Ship 2/Weapons_Grenades.xml

Patch armor for archeotech skin implant
Remove CE_AI_Grenade tag from the mechanite cocktail, preventing your first grenadier raider from inflicting a grey goo scenario on your map. The tag wasn't intended to be there, I just missed removing it when first doing the patch.

SoS2 XML patch update

---

Patches/Android Tiers/Hediffs/Hediffs_Android.xml
Patches/Android Tiers/Hediffs/Hediffs_CustomImplants.xml
Patches/Android Tiers/ThingDef_Misc/Weapons_Guns.xml
Patches/Android Tiers/ThingDef_Races/AlienRace_Androids.xml

Add patches for new backstory specific implant weapons.
Fix hydralic parts to provide boosts to bulk/mass. Since their default state made this largely impossible, some of the part efficenciy decreases were instead converted to movespeed penalties.
Tweaked the anti-mech rifle's firing cycle.
Lowered the base T5 arm attack speed.
Increased M7 mech's carry bulk to allow it to carry addtional reloads for the weapon (though still fairly limited, since the ammo is quite high bulk)
While I haven't done it here, I'd like to consider reducing the pellet count on the M7 mech's buckshot weapon, as 200 pellets with the average power of a battle rifle round is not only significantly better than every other mech weapon and hideously effective against everything else in the game due to raw damage values …

Updates to android tiers patch

---

Patches/Rimsenal Collection/Core/Rimsenal_Melee.xml

Updated TE melee to fix errors and match new vanilla weapon specs.
Reduced the cooldown on JI hammer weapon.

Update Rimsenal Melee Stats

---

Patches/Moyo from the depth/Drugs/Belial-V_Effect.xml
Patches/Moyo from the depth/PawnKindDefs/Moyo_PawnKind.xml
Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml

Reduced the armor rating on a few items by a small amount.
Removed the point cost changes, since the pawns have new point costs in the base mod that are almost identical to what I was going to bump them up to anyway.
Added forced backpack on a few more pawndefs
Added Belial V patching

Tweaks to Moyo Patch

---

About/About.xml
Patches/Rabbie The Moonrabbit/ThingDefs_Misc/Weapons_Guns.xml

Add patch stuff to the mortar shell since the mod now alllows them to be throwable or something, as per the base mod's changes.
Added a load requirement to load the mod after the moonrabbit mod to avoid errors.
It seems that adding tools to a ammo item breaks the ammo injector or something, causing the shell to still be able to spawn, but not have its recipe properly show up anywhere. Manually re-adding the recipe to the tables seems to fix the issue without any other problems emerging.
The load requirement was added both to avoid another error (the base mod attempting to patch the minigun's weapon tags) as well as to make the patches here fire properly (otherwise it's possible the patches will break since the mortar shell changes in the base mod are implemented as patches)
It may be …

Rabbie the moonrabbit update

---

Patches/Fell Tribes/PawnkindDefs/PawnKinds_Fell.xml
Patches/Fell Tribes/ThingDefs_Races/Bear.xml
Patches/Fell Tribes/ThingDefs_Races/Fox.xml
Patches/Fell Tribes/ThingDefs_Races/Lynx.xml
Patches/Fell Tribes/ThingDefs_Races/Serval.xml
Patches/Fell Tribes/ThingDefs_Races/Wolf.xml

Adds *very basic* support for [Fell Tribes](https://steamcommunity.com/sharedfiles/filedetails/?id=2243528541) covering pawn types, to enable suppressability/weapon UI functionality/et cetera. Based on the Xenn patch files.

Basic Fell Tribes Patch

---

Patches/Red Horse Faction Coalition/RH_Coaliton_CE_Patch_TraderKinds.xml

- Added new TraderKinds.xml
- Custom RH faction vendors don't seem to carry any ammo for sale. This XML addition simply allows them to sell random ammos as based on the config. 

Added ammo to rh coalition vendors

---

Defs/Misc/TipSetDefs/Tips.xml
Defs/RecipeDefs/Recipes_Production.xml
Patches/Core/ThingDefs_Races/Races_Animal_Rodentlike.xml
Patches/Core/ThingDefs_Races/Races_Animal_Tropical.xml

For balancing discussion.
- Boomalopes/Boomrats now yield some FSX when butchered.
- Using a drug lab, FSX can be made from chemfuel and meat or from boomalope meat.
- Boomalopes and Boomrats are once again milked for chemfuel, rather than FSX.
The current system replaces milking boomalopes/boomrats for chemfuel with milking them for FSX, which is a fairly significnat departure from vanilla and can be disruptive for players who need a steady supply of chemfuel, requiring them to invest in researching a refinery.
This revision restores milking for chemfuel, and introduces two new approaches to obtaining FSX:
1. Butchering a boomalope or boomrat now yields some FSX (10 and 2, respectively). This should mean hunting them would generally be sufficient to keep a tribal colony supplied for …

Revisions to FSX production

---

Patches/Thrumkin/Patch_Bodies_Thrumkin.xml
Patches/Thrumkin/Patch_ImplantsProsthetics_Thrumkin.xml
Patches/Thrumkin/Patch_PawnKinds_Thrumkin.xml
Patches/Thrumkin/Patch_Race_Thrumkin.xml
Patches/Thrumkin/Patch_Things_Thrumkin.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Footwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Handwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Industrial.xml

- Updated SYR Thrumkin patch to patch the industrial tech pawns.
- Attempted to make VAE's advanced armor vest more viable by decreasing its thickness, giving extra mm of sharp armor (when made out of steel), increasing the cost to make, decreasing max health, decreasing worn bulk by a tiny amount and decreasing weight to be 12/13 of the normal armor vest.
- Rebalanced VAE's soft armor vest to be heavier, have 12 mm thickness (up from 10mm), decreased the base worn bulk to 1 from 1.5, increased the cost to 80 materials from 50.
- Modified power armor boots and gloves to be more worth it. Power armor boots have higher carry weight bonus than own mass. Buffed power gloves armor values to be the same as power armor boots. Modified bulks, masses, descriptions of both. They now differ by …

Updates for Vanilla Armor Expanded and SYR Thrumkin patches.

---

.github/workflows/pullrequest.yml

Manually triggering a rebuild for a PR builds correctly, but fails to post the comment or label due to the PR number not being attached to those steps properly.

Use input PR number when manually running

---

Make.py

Makes the PR building workflow fail its check if the PR generates warnings (in the C# layer)
The code base currently doesn't issue warnings.  The `.csproj` already treats warnings as errors.  This makes the Unix build script match.
Try to catch new warnings manually...

Treat warnings as errors

---

Patches/Mincho, The Mint Choco Slime/ThingDefs_Bodies/Mincho_Bodytype.xml

Adds the Shoulders group to the mincho body so they can't wear multiple backpacks
Remove their ability to wear backpacks and just increase their default bulk

Mincho backpack fix

---

Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml
Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml

A handful of changes that generally make the mech turrets and sieges somewhat less lethal.
Changes:
- Add minimum range to several turrets.
- Increase the fuse length on siege objects that explode, so they're not quite so dangerous to destroy with melee.
- Decrease accuracy of a few turrets
- Increase cooldown
- Increase Mass of several turrets (no actual balance effect, they just seemed too light.)

Nerf to Mech Siege Turrets

---

Patches/O21 Mechadroids/Bodies_Mechadroids.xml

Mechanical Leg and Mechanical Foot already have a groups tag. Changed so it is editing that tag instead of making another one.

Minor Fix: O21 Mechadroids

---

Patches/Vanilla Weapons Expanded/Ammo/AntiGrainRocket.xml
Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml

- Tweaked the anti-grain rocket to do a mix of bomb / emp damage, it was doing nothing before.
- **Hand Cannon**
- WorkToMake: 7000 > 4500
- Mass: 1.8 > 0.9
- Bulk: 2.9 > 2.41
- ShotSpread: 0.20 > 0.17
- SwayFactor: 1.15 > 1.10
- RangedCooldown: 0.45 > 0.38
- Warmup: 0.7 > 0.6
- Cost: 35 Steel / 2 Components > 5 Wood / 20 Steel / 2 Components

VWE Tweaks

---

Make.py

Use `csc` instead of `mcs`, and remove experimental lang version flag (under `csc`, the latest C# standard isn't experimental).
csc better supports the latest C# syntax, and is most similar to the compiler used on Windows.
Continue using `mcs`, and limit ourselves to C#6 syntax (no local functions is the common issue)

Use csc instead of mcs as compiler

---

Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml

- Changes the Combat Pistol / Hand Cannon ai aim modes to ` Snapshot `
- Reduced the range of the anti-material rifle to 86 from 126

Vanilla Weapons Expanded Tweaks

---

Source/CombatExtended/Compatibility/EDShields.cs
Source/CombatExtended/Compatibility/VanillaFurnitureExpandedShields.cs

The shield caches for VFE and ED Shields malfunctions when shields are deployed on multiple maps and projectiles are in-flight on those maps at the same time.  This invalidates the cache when the map changes.
It is assumed that maps are processed sequentially.  This is likely to be incompatible with mods that process multiple maps in parallel, but it already will break in that case.
For performance reasons, we cache the list of shields on the map, and update the cache once per tick.  If there are multiple maps with shields, we need to invalidate the cache when switching maps, or shields will either get missed, or provide "ghost" protection.  Or possibly have other strange side effects.
Don't cache the buildings.  This would significantly impact performance on maps with lots of buildings …

Fix ed shields with multiple maps

---

Source/CombatExtended/CombatExtended/Gizmos/Command_ReloadArmor.cs
Source/CombatExtended/Harmony/Harmony_CompReloadable.cs

Allows ordering drafted colonists to reload their reloadable apparel
Doing it this way hooks into the existing reload logic for apparel (when pawns are not drafted).
Manually create the reload job (duplicates code)

Add gizmo to order reloading worn armor (or other CompReloadable apparel)

---

Patches/RimSec-Security/AlienBase.xml
Patches/RimSec-Security/Ammo/SRS Ammo.xml
Patches/RimSec-Security/Bodies.xml
Patches/RimSec-Security/Buildings.xml
Patches/RimSec-Security/PawnKinds.xml
Patches/RimSec-Security/Traits.xml
Patches/RimSec-Security/WeaponDefs.xml

Mod link - https://steamcommunity.com/sharedfiles/filedetails/?id=2323762086
The droids and turrets are strictly better than vanilla counter parts. This is because nothing in this mod is spammable. You need special components to craft each and every item so I've considered that before patching.  The special components are sold by a trader that ONLY visits 3 times a year. They are expensive as well. But still the mod should be reasonably balanced. :) I'm open to balancing suggestions 

Rimsec-Security patch

---

Source/CombatExtended/CombatExtended/Jobs/JobDriver_Hunt.cs

Hunters will keep their distance to dangerous animals and try to shoot them down from a distance. 
Nothing changed when hunter is hunting a safe animal. 
Hunters get close to dangerous animals like Megasloth when they try to hunt them even with sniper rifles like Tac-50. 
The result is if the animal enters manhunting mode, hunter will likely to get badly injured or die.
With this change even if animal enters manhunting mode, hunter can take a few more shots or run away.

Hunter will stay far if they're hunting an animal with revenge chance.

---

Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Footwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Handwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Industrial.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Medieval.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Neolithic.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Headgear_Industrial.xml

- Added trooper armor (uses old light marine armor stats)
- Removed description and name changes to the HMA
- Changed the NVGs apparel layer so they can be used with other hats
- Removed some redundant operations
Prestige version of both the trooper armor and siegebreaker armor are added via a patchOperation that checks for Royalty, so their patches must be handled on VAE's side. Path to this file is ` 1814988282\1.2\Patches\Royalty.xml ` no need to say to replace the orignal file with the one included here [Prestige Armors Patch](https://github.com/CombatExtended-Continued/CombatExtended/files/5897923/Royalty.zip)

Vanilla Armor Expanded Update

---

Source/CombatExtended/Harmony/Harmony_Fire.cs

If clothing is sufficiently non-burnable, shrink the fire
Pawns on fire now can have the fire go out on its own if they are wearing sufficiently flame-retardant material.  Makes fire-arrows against armored opponents not break the AI.
x
- Getting someone sufficiently lit on fire to not just go out, especially when they are not wearing cotton or similar cloth, is actually rather difficult.
Remove fire arrows?

Adjust fire growth rate based on clothing worn by pawn. 

---

Patches/Civilization Beyond Earth Armor Sets/Apparel_T1Armor.xml
Patches/Civilization Beyond Earth Armor Sets/Weapons_T1Guns.xml
SupportedThirdPartyMods.md

Simple patch for Civilization Beyond Earth Armor Sets. Patches one set of armor and one rifle.
- Armor is weaker than recon armor without the loadbearing bonuses.
- Rifle is essentially an assault rifle with a larger mag, shorter range, higher rate of fire, and more recoil. It only needs Gas Operation vs Precision Rifling, but that's from the base mod and I decided to let that stand.

Patch for Civilization Beyond Earth Armor Sets

---

Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs

- Updated the loadout behaviour to treat equipped weapons by the same rules as inventory items (keep item if it's part of the loadout or if forced pick-up), as opposed to checking just loadout.

Fix pawns dropping forced pick-up weapons after equipping them

---

Patches/Vanilla Animals Expanded/IceSheet_Resources.xml
Patches/Vanilla Animals Expanded/RawFish_Resources.xml

Removes a duplicate patch for the raw fish "weapon" by combining the patch for them (and renaming the file).

Minor VAE Duplicate Fix

---

SupportedThirdPartyMods.md

- (Retroactively) add NewRatkinPlus to `SupportedThirdPartyMods.md`
- Ratkin patches already existed as far back as May 2020, but for some reason were never listed in the supported mods list.

Add NewRatkinPlus to modlist (retroactive)

---

.github/workflows/pullrequest.yml

- All PRs will get a downloadable zipfile added in the comments, giving a uniform way to download and test PRs.
Currently XML-only PRs require the tester (or eager players) to navigate to the originating branch and download the branch as a snapshot.  C#-affecting PRs require the tester to either compile the branch locally or use the compiled version provided via download link in the comments.  This was done to test out the CI system without impacting the XML-modding workflow until the kinks were worked out.  The kinks are now worked out, and there have been a few people asking how to get the patches which *don't* have an obvious download link.  Including asking if PRs without download links are not suitable for actual use. …

Build assembly for all PRs

---

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs
Source/CombatExtended/CombatExtended/Loadouts/Utility_Loadouts.cs

- Assigning a loadout to a temporary faction member no longer makes them drop their quest-locked weapons
- Fixed ammo forced pick-up setting wrong item count when a pawn loadout is carrying a weapon loaded with that ammo type

Loadout fixes

---

Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Headgear_Industrial.xml

- Baseball Cap layers reverted to Overhead.
Poking around noticed that VAE was the only mod that moved these hats to the MiddleHead layer causing issues when other apparel mods were loaded (double baseball caps, double helmets, etc) and so on. This change simply aims to fix that.

Vanilla Apparel Expanded Tweaks

---

Patches/Genetic Rim/Bodies/GeneticRim_CE_Patch_Bodies.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_CosmicHorrors_HybridCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_Dino_HybridCE.xml
Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_MechanoidhybridsCE.xml

A few tweaks to Genetic Rim and associated mod patches.
- Comment out the GR_Arachnid bodyType, as it seems unnecessary and causes some errors.
- Fix capitalization error with `Birdlike`.
- Remove mechaspider bite attack, since it doesn't have one in the base mod.
- Fix some formatting.

Genetic Rim Tweaks

---

Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml

IIrc Uzi and MP5K both have 3 round burst modes. At least MP5K does. Uzi can be fired with good discipline with 3 round bursts.
UZI and MP5 burst fire
Added burst fire for said guns
=
Make them more usable to preserve ammo. MP5K totally has burst fire mode irl. 

Burst shots for some smgs, (Uzi and MP5K).

---

Defs/ThingDefs_Buildings/Buildings_Defenses.xml

- Updated embrasure terrain affordance from medium to material-based.
- Makes embrasures have the same placement restrictions as walls, where minimum affordance is light for wood, medium for steel, and heavy for stone. This allows wooden embrasures to be built over bridges.

Update embrasure terrain affordance

---

Patches/JDS EFT Apparel/Apparel_Backpacks.xml
Patches/JDS EFT Apparel/Apparel_ChestRigs.xml

- Pawns no longer equip two backpacks.
- Pawns no longer equip armored chest rigs + load bearing chest rigs.

EFT Apparel Tweaks

---

Patches/Dragon's Descent/AbilityDefs/Dragon.xml
Patches/Dragon's Descent/BodyDefs/Bodies_Animal_Dragon.xml
Patches/Dragon's Descent/DamageDefs/Damage_Dragons.xml
Patches/Dragon's Descent/Drugs/Draconic_Ambrosia.xml
Patches/Dragon's Descent/Drugs/Dragon_Blood_Potion.xml
Patches/Dragon's Descent/HediffDefs/Hediffs.xml
Patches/Dragon's Descent/Projectiles/Projectile_Animal.xml
Patches/Dragon's Descent/Scenarios/Scenarios_DragonsDescent.xml
Patches/Dragon's Descent/ThingDefs_Items/Items_Exotic.xml
Patches/Dragon's Descent/ThingDefs_Items/Items_Resource_Leather.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Common_Dragon.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Dragon_Base.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Rare_Dragon.xml

- Readded Dragon's Descent patch after updating it.
- Dragon's Descent's ranged attacks work now.
- Modified dragon breath attack to act like a better (Combat Extended Guns) flamethrower.
- Modified dragon spit attack to be similar to an incendiary launcher.
- Probably closes #452.
- To me the flamethrower is probably the most similar weapon to the dragon breath attack. Some notable changes are that dragon breath has better range than the flamethrower, fires faster, has worse "recoil" and a "mounted" recoil pattern meant for spreading shots out horizontally, explosion damage is 5, better explosive coverage (3x3 square instead of 3x3 plus) and uses the `Flame` damage type because I didn't want it to apply the "promethium soaked" health status effect.
- I used the incendiary launcher as an …

Readded and updated Dragon's Descent patch.

---

Patches/Japanese Dogs/Dogs.xml

Japanese Dogs Patch.
Patches the Japanese Dogs mod for CE. Assigns CE stats to dogs (small dogs = slightly weaker than Labrador, medium sized dogs = at Labrador's level, Akita Inu = slightly stronger than Husky).
[+] Compiles without warnings
[+] Game runs without errors
[+] (For compatibility patches) ...with and without patched mod loaded

Japanese Dogs Patch

---

Patches/[O21] Outer Rim/Patch_OuterRim_Apparel.xml
Patches/[O21] Outer Rim/Patch_OuterRim_Factions.xml
Patches/[O21] Outer Rim/Patch_OuterRim_Races.xml
Patches/[O21] Outer Rim/Patch_OuterRim_Resources.xml
Patches/[O21] Outer Rim/Patch_OuterRim_SandCrawler.xml
Patches/[O21] Outer Rim/Patch_OuterRim_Weapons.xml

Adds [O21] Outer Rim compatibility Patch.
Patches: [O21] Outer Rim - Core, Outer Rim - Tatooine (Continued), Outer Rim - Faction - Tatooine (Continued) and Outer Rim - Tatooine Sandcrawler (Continued)

[O21] Outer Rim compatibility Patch

---

About/About.xml

Added both proper shotguns mods to < incompatibleWith > in the About.xml
Will help new people and stop some of the bug reports caused by these mods when people use them with CE.

Added both proper shotguns mods to <incompatibleWith>

---

Patches/Ancient Fallout Armory/Apparel_Armor.xml
Patches/Ancient Fallout Armory/Headgears_Fallout.xml
SupportedThirdPartyMods.md

Patches the sets of armor added by the mod.
The metal armor is fairly low quality, well-suited for melee, but not as useful against gunfire.
The medium combat armor is essentially a flak jacket with better coverage.
The heavy and pre-war combat armor is between flak armor and recon armor, which I think is pretty good for its fairly low material cost (doesn't require advanced components). If we're not happy with it, we could potentially increase the protection and perhaps require devilstrand to make it more like power armor.

Patch Ancient Fallout Armory

---

Patches/Core/Bodies/BodyParts_Organs.xml

- Fix permanent scars having a much lower chance than they should
- Set a sensible permanent injury factor for internal organ wounds
- The xpath fix is fairly straightforward: `or "Lung"` is interpreted as `or true` so it needs to be fixed to `or defname="Lung"`, otherwise this patch ends up targeting every single BodyPartDef in the game, which is why things like permanent brain injuries are almost non-existent in CE.
- As for why I changed the factor to 5, some context: In vanilla, body parts have a default permanentInjuryChanceFactor of 1. Some parts, like most bones, have 0 (so they never scar), while others, like eyes (15) and brain (9999999) have higher values to make scars more likely.
But this patch [is way older than that](https://github.com/CombatExtended-Continued/CombatExtended/ …

Fix permanent scar chance patch applying to wrong organs

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/High Caliber/HighCaliber_CE_Patch_Weapons.xml
Patches/JDS The Forge - NCR Armory/Defs_Weapons.xml
Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_UK.xml
Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_Revolvers.xml
Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Modern.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_Revolvers.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_RSGuns_CE.xml
Patches/SYR Naga/Patch_ThingsWeapons_Naga.xml
Patches/Tsar Armory/TsarArmory_Guns.xml
Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_RangedIndustrial.xml
Patches/turk's guns/Patch_Guns.xml

- Increased the reloading time of all revolvers that use speedloaders from 3.5 to 4.6.
- Increased the Revolver's cooldown time from 0.42 to 0.49.
- Changed the Fallout Armory Hunting Revolver and several M1895 Nagant revolvers from using a speedloader to a handload weapons.
Some adjustments to stats to reflect two changes I've made to the Gun Stats spreadsheet to make the revolvers more true to their real-life functionality and more distinct within CE from semi-auto handguns. The two changes I made to the spreadsheet:
- Increase the reloadTime of the "speedloader" from 3.5 to 4.6
- Increase the Cooldown of the "Double" action type from 0.35 to 0.45.
Previously, revolver speed loaders actually reloaded _faster_ than magazines (3.5 vs 4), which is not accurate to real life. Opening a …

Adjustments to Revolver Balance

---

Patches/JDS Exiled Dawn/Ammo/Ammo_ExilePlasma.xml
Patches/JDS Exiled Dawn/Thingdefs_Misc/Weapons_Melee.xml
Patches/JDS Exiled Dawn/Thingdefs_Misc/Weapons_Ranged.xml

Switched the properties of the plasma weapons. Originally they were pure burn weapons in vanilla, but at some point they got changed to bullet. They now function pretty much as charge weapons with slightly improved conc. rounds (that burn instead of blasting) with better sharp penetraiton but much worse blunt.
The big plasma rifle also now consumes 2x rounds per shot and has twice the mag capacity, just to differentiate it a bit more from the standard version.
The melee weapon penetration has been buffed (1.35x sharp penetration, 2x blunt for the mace), both because the faciton heavily relies on the melee weapons to be effective, and because after testing, a lot of the weapons were way more expensive than I had originally thought and as such contribute a lot more to player wealth, and to …

Exiled Dawn Tweaks

---

Source/CombatExtended/CombatExtended/Comps/HediffComp_Prometheum.cs

- Prometheum-soaked hediff is cleared if the pawn comes into contact with firefoam
- Firefoam already has the ability to render prometheum puddles inert, it makes sense to also apply it for prometheum fires on pawns

Firefoam clears prometheum-soaked hediff

---

Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_MutantWeapons.xml

Adds gravity factor to the Feral Shriker's attack so it can aim properly and slightly increases its radius (the spore won't do any damage because of the way it was implemented in the original mod).

Fix Feral Shriker

---

Source/CombatExtended/CombatExtended/Loadouts/HoldRecord.cs
Source/CombatExtended/CombatExtended/Loadouts/Loadout.cs

- Remove log messages when adding items to a loadout, or when saving the game while colonists have inventory hold trackers.
- These were likely added for for debugging purposes at some point, and should have been cleaned up before merging. In large colonies, these can cause the logger to hit its message limit quite easily, which is detrimental for playtesting or bug reports as any errors are suppressed until the log is manually cleared.

Remove unnecessary message logs

---

Source/CombatExtended/CombatExtended/Things/Plant_Blazebulb.cs

- Fix "Got temperature for null map" error that pops up when blazebulb dies from environmental causes (cold snap, etc)

Fix blazebulb error

---

Source/CombatExtended/Harmony/Harmony_JobGiver_OptimizeApparel.cs

- If a pawn is equipped with a two-handed weapon, they won't wear melee/ballistic shields when updating their apparel, even if their outfit restrictions allow it.
- Closes #311

Pawns with two-handed weapons don't automatically wear shields

---

README.md

A permalink to the download of the latest dev snapshot, prominent in the project's README
Keeping the assembly inline in the repository causes problems.  First because git can't well handle regularly-changing binary data.  Second because keeping it in sync with the source code is a challenge.  Third (related to the first), because it causes merge conflicts needlessly.
For the past few months, we've been automatically building dev snapshots out-of-tree, and including links to them automatically in PRs.  When PRs get merged, a new dev snapshot is created as well.  This adds a link to that dev snapshot.
Continue as we have, which requires extra work on merging PRs, and leads to features sometimes getting missed for a release.
Create micro/pre-releases for each merge.  This would work, but is …

Include permalink to dev snapshot download

---

Royalty/Patches/ThingDefs_Misc/Weapons_BladelinkMelee.xml
Royalty/Patches/ThingDefs_Misc/Weapons_Melee.xml

Increased the damage and penetration of monoswords.
Increased the damage and penetration of plasmaswords in general, though some attacks are now slightly slower. It is still overall more powerful however. Increased the chance to use the slash slightly.
Improved the warhammer to make it more comparable in performance to the maul. It's still slightly weaker/faster striking but shouldn't be a practically worse mace that stops from you using shields now.
Improved the handaxe, making it more comparable to a slightly weaker mace against armor, but stronger against unarmored targets where it can use slash damage.
Persona weapons now function as if all their strikes are 10% faster, including the damage and penetration that entails
New weapon data here …

Buffs/Adjustments to Royalty melee wepaons

---

Defs/Bodies/BodyPartGroups.xml
Patches/Core/Bodies/Bodies_Humanlike/Human.xml
Source/CombatExtended/CombatExtended/DefOfs/CE_BodyPartGroupDefOf.cs
Source/CombatExtended/Harmony/Harmony_DamageWorker_AddInjury.cs

Adds a new body part group called `OutsideSquishy` to mark body parts which are outside their sibling (like the eyes, nose, and ears, relative to the skull).
`OutsideSquishy` body parts will propagate overdamage to their sibling.
Currently, high caliber (.50BMG or similar) projectiles regularly hit pawns in the head, destroying a single eye, ear, nose, or jaw, without causing further injury.  This fixes that problem.
Dynamically detect when a body part is outside and damage should continue.  This is not trivial.
Always propagate damage.  This either over-applies damage, or fails on non-humanoid/irregular body definitions.

Fix Eyes soaking high caliber hits

---

Source/CombatExtended/Harmony/Harmony_StunHandler.cs

Duration of mech stun resist scales with damage taken.
If the stun is resisted, the stun resistance duration is slightly decreased.
If a more-stunning hit lands while the target is still stunned, the stun duration increases.
Use a random chance for re-stunning.  As the stun-resist timer gets close to 0, they can get re-stunned early.
Fixes #461
The design goals are:
1. Adding new EMP/ion damage sources should never be a mistake
1. Stun locking mechs should be possible with concentrated fire
1. Such concentrated fire should terminate the mech fast enough to be usually moot
1. Some variability in how long between stuns
1. Mechs, especially more than a single mech, should still be dangerous
Disable mech adaptation - breaks 5
Allow multiple hits before adaptation - breaks 5 and 1
Make stun …

Fix Mech Stun resist

---

Patches/Alpha Animals/BodyDefs/AlphaAnimals_CE_Patch_Bodies.xml
Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MatureFleshbeast.xml

Patches the AA Mature Fleshbeast and its bodyDef, which are currently unpatched. Removes AA's "swallowed whole" mechanic, because it's bugged with CE's knockdown mechanic for animals, usually resulting in an insta-kill by destroying the victim's neck.

Patch AA Mature Fleshbeast + BodyDef

---

Patches/Moyo from the depth/Ammo/Ammo_Moyo.xml

Fixed the nail ammo's bulk/mass/cost, as it's current ones were way too high from what I copied the ammo from previously.

Fix moyo nail ammo

---

Defs/Stats/Stats_Pawns_Inventory.xml

- The CarryWeight and CarryBulk stats added by apparel are now affected by the quality of the piece of apparel.  
This makes higher quality loadbearing gear like packs and tactical rigs (and other apparel that adds these things) more valuable and desirable, whereas there was previously no practical justification for higher quality loadbearing gear having a higher market value.
- Do not add quality affect, leaving it as it currently stands.

Make CarryBulk & CarryWeight on apparel affected by item quality

---

Source/CombatExtended/Harmony/Harmony_JobGiver_OptimizeApparel.cs

- #584 has a bug in it, causing all weapons without tags as well as one-handed weapons to prevent equipping a shield, rather than just two-handed weapons as intended. This change should fix it to work correctly in all cases.

Fix two-handed check on optimize-apparel patch

---

Patches/Rimmu-Nation - Security/Ammo_SSM.xml
Patches/Rimmu-Nation - Security/ThingDefs_Security.xml
Patches/Rimmu-Nation - Security/ThingDefs_Turrets.xml
SupportedThirdPartyMods.md

Patches several automated turrets and mines. Removes the claymore mine, as its shrapnel does not use CE armor penetration properly and is thus very weak.

Patch [CP] Rimmu-Nation Security

---

Defs/Ammo/AmmoCategoryDefs/AmmoCategories_General.xml
Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Grenades.xml
Defs/DamageDefs/Damages_LocalInjury.xml
Defs/HediffDefs/Hediffs_CE.xml
Patches/Core/HediffDefs/Hediffs_Local_Injuries.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Ranged.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml
Patches/Vanilla Weapons Expanded - Frontier/Patch_HighRoller_AddonAmmo.xml
Patches/Vanilla Weapons Expanded - Frontier/Patch_HighRoller_Ammo.xml
Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-HeavyWeapons.xml
Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Quickdraw.xml
Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/40mmLessLethal.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/NonLethal_Grenades.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/NonLethal_Melee.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/NonLethal_Ranged.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/RubberBullet.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/TaserCartridge.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/TranquilizerDart.xml
Patches/Vanilla Weapons Expanded - Quickdraw/Weapons_Quickdraw.xml
Patches/Vanilla Weapons Expanded - Tribal/Melee_Neolithic.xml
Patches/Vanilla Weapons Expanded - Tribal/Ranged_Neolithic.xml
Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml
Patches/Vanilla Weapons Expanded/Medieval_Ranged.xml
SupportedThirdPartyMods.md

- Add High Roller variants of projectiles, with a 10% chance to double damage.
- Patch Vanilla Weapons Expanded - Tribal (Complete).
- Patch Vanilla Weapons Expanded - Non-lethal (Complete).
- Increases the range of some SMGs.
- Swaps VFE - Security sentry gun from 7.62mm NATO to 5.56mm NATO.
- Adds some additional ammo categories that I felt were generic enough to be useful in the base mod, like rubber bullets and tear gas. 
- Adds damageDefs and injury Hediffs for a tasers to the base mod, since it's may be useful.
- Increases heavy crossbow damage slightly by using stats for a slightly faster bolt.
Closes #617

Additional Vanilla Weapons Expanded patch work.

---

Source/CombatExtended/CombatExtended/Lasers/LaserBeamGraphicCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

Toggling damageFalloff property on `ProjectilePropertiesCE` disables damage falloff for lasers and re-enables shots deviating
Coilguns have 0 damage falloff, but shouldn't fire from dead-center for every shot.
Move to a new property to control shot spread vs shot variance. - Can't be done in time for this release, will be needed to support instant-projectile "scatter guns".

Lasers ready

---

Patches/Anty the war Ant/ThingDefs_Misc/Anty_Apparel.xml

-'Anty The war ant' Apparel patch error fix
-Composite Helmet
-Flak Vest
-Flak Plate
-Cloaks
-With the recent update, the xml configuration of the Apparel has been changed.
Some of the existing patches did not work.
- [o] Game runs without errors
- [o] (For compatibility patches) ...with and without patched mod loaded
- [o] Playtested a colony (3 days in game time)

'Anty The war ant' Apparel patch error fix

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Source/CombatExtended/CombatExtended/Comps/CompFragments.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs
Source/CombatExtended/CombatExtended/Things/AmmoThing.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs

- Various long-standing bugs related to sounds from all maps playing on the map the player is looking at
- In essence: Find.CurrentMap -> Map
- No prior issues, I believe?
- Bugs came up during BattleRoyale unit testing all the time:
- - Fragment routines run after Map is destroyed, throwing errors: Tried to spawn thing Fragment_Small80726, but the map provided does not exist.
- - Reload sounds are heard in CurrentMap (rather than in Map, where they should be)
- - Reload text is thrown in CurrentMap (rather than in Map)
- - Ammo explosions can start in destroyed Map
- - Melee parries threw errors after a riposte causing the attacker to die
- Run CombatExtended current build on BattleRoyale and notice that every map has reload sounds
- Run this PR and notice no reload sounds
Check tests …

Prevent Map 'cross-talk'

---

Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Footwear.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml

- Changed the marine armor boots crafting recipe's patch to account for the recent removal of hyperweave from its vanilla recipe;
- Nerfed trooper armor;
- Buffed health of siegebreaker armor.
- Closes #650.
- Fixed an error that was caused by the recipe patch failing;
- Trooper armor is just a cheaper (both recipe and research wise), lighter alternative to the recon armor. It being better or the same in most regards to recon armor is simply wrong.
- Siegebreaker armor is supposed to be a tanker version of normal power armor, but it breaking from the same amount of chip damage as power armor didn't make sense.

Updated/modified the Vanilla Armour Expanded patch

---

Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml

- Made trooper and siegebreaker power armor and helmet inflammable;
- Kept siegebreaker power armor armor values the same, however it now costs a bit less plasteel, doubled the cost of uranium and replaced the industrial components in the recipe with advanced components;
- Siegebreaker power armor carry weight reduced, decreased bulk of the armor;
- Removed siegebreaker power armor's and helmet's pain shock threshold offset;
- Minor tweaks to siegebreaker power armor helmet's armor values;
- Removed siegebreaker power armor helmet's carry bulk and carry weight stat offsets, reduced the helmet's weight, bulk and worn bulk;
- Decreased siegebreaker power armor helmet's plasteel and advanced component recipe cost and increased its devilstrand recipe cost.
- Set flammability of trooper and …

Tweaks to Vanilla Armor Expanded spacer armor.

---

Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Armors.xml
Patches/Spartan Foundry/ThingDefs_Misc/Patch_Apparel_Headgear.xml

Tweaked the values of Spartan foundry armor to better reflect it's place as uncraftable (with one exception), end-game armor that doesn't have prestige variants.
Made a list as follows with vanilla stats:
recon 92% -> 16mm
marine 106% -> 20mm
cataphract 120% -> 28mm
recon 92% -> 12mm
marine 106% -> 16mm
cataphract 120% -> 22mm
and then placed the spartan foundry armor as seemed appropriate by their armor values compared to the above values, with preference for multiples of 2 and exclusively using whole numbers. This then gave me the following list: 
powered assault 118% -> 28mm +
engineer 108% -> 22mm +
explorer 90% -> 18mm ++
grenadier 148% -> 32mm --
commando 108% -> 22mm +
hazard 112% -> 24mm +
diplomat 112% -> 24mm +
defender 108% -> 22mm +
scout 105% -> 20mm +
samurai 85% -> 16mm + …

Tweak Spartan Foundry

---

Patches/Anima Animals/AnimaAnimalsResources_Leathers.xml
Patches/Anima Animals/AnimaWeapons.xml
Patches/Anima Animals/ThingDefs_AnimaCreatures.xml
Patches/Anima Gear/AnimaGear_Apparel.xml
Patches/Anima Gear/AnimaGear_Resources.xml
Patches/Anima Gear/PsychicWeapons.xml
SupportedThirdPartyMods.md

Patches anima gear mod. -
Apparel is patched to match thickness of equivalent, non-anima apparel. Fiber identical to cloth, since it shares the vanilla values. Staff uses psycast staff melee stats.
Patches Anima Animals mod. - Animals are largely similar to the vanilla version, with slightly better stats. Closes #648

Patch Anima Gear mod

---

Patches/Core/ThingDefs_Races/Races_Animal_Arid.xml
Patches/Core/ThingDefs_Races/Races_Animal_Bears.xml
Patches/Core/ThingDefs_Races/Races_Animal_BigCat.xml
Patches/Core/ThingDefs_Races/Races_Animal_Farm.xml
Patches/Core/ThingDefs_Races/Races_Animal_Giant.xml
Patches/Core/ThingDefs_Races/Races_Animal_Insect.xml
Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml
Patches/Core/ThingDefs_Races/Races_Animal_Tropical.xml
Patches/Core/ThingDefs_Races/Races_Animal_WildCanines.xml

Tweaks to make most large predators and herbivores more dangerous, also tweaked the stats of some animals be less nonsensical.
Because a bear would easily lose to a random person with a jacket and knife, because leather jackets apparently makes you impervious to bear attacks somehow. This tweak only buffs animals very slightly, so nonsense like the above could still happen.
Pretty much all animals are so terrible at fighting at a degree that is far beyond my comprehension. Why?
If this PR is merged, I'll take a look at patches for modded animals as well.

Vanilla animal tweak

---

About/About.xml
Patches/Kit's Gunpowder Weapons/Ammo_KitsGunpowder.xml
Patches/Kit's Gunpowder Weapons/KitsGunpowder_Guns.xml
Patches/Vanilla Factions Expanded - Medieval/PawnKindDefs/Patch_Musketman.xml

Tweaked bayonet damage.
Make cannonballs makable at the smithy.
!!!!IMPORTANT!!!!
Added ammo to Medieval Musketman.
This will only work if Combat Extended is loaded after both Vanilla weapons expanded AND Vanilla Faction Expanded: Medieval!!!!!!

Update bayonet and muskets

---

Patches/NewRatkinPlus/Ammo/RKBallistaBolt.xml
Patches/NewRatkinPlus/Ammo/RKCannonShell.xml
Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_Apparel.xml
Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_Buildings_Security.xml
Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_MeleeWeapons.xml
Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_RangedWeapons.xml
Patches/NewRatkinPlus/ThingDefs_Races/Race_Rakinlike.xml

Added appropirate stats for a lot of new content items. Added race stuff for the subject subrace.
Reduced the weight on a few weapons to prevent massive overweight problems for ratkin knights. Gave guardner and order armor back their innate protection since they are specifically combat armors. Moreso for order armor which actually takes up the middle slot, blocking you out of other armor options.
Changed the ballistia patch to not be so intrusive. Also it was broken as well for some reason, so that's fixed.

NewRatkinPlus patch stuff

---

Patches/Colony Leadership/WarriorLeadership.xml
Patches/JPT Open The Windows/Openvindows.xml

Makes Open the windows compatible.
Improvements to Colony leadership, make the stat buffs from warrior type leaders compatible with CE.

Windows of Leadership patch

---

Patches/Alpha Ships/Patch_AlphaShips_DamageDefs.xml
Patches/Save Our Ship 2/Patch_DamageDefs_SOS2.xml

Adds a patch that changes the default AP of Alpha Ships and SOS2's ship mounted weapons to 200 MPa (originally 0.1 MPa)

Fix Armor Penetration for Alpha Ships and SOS2's Ship Weapons

---

Patches/Rimsenal Collection/Feral/ThingDefs_Races/Race_Ogrons.xml

Ogron armor was initially 1.5 sharp and 0.5 blunt, probably a leftover from the old armor system. Since the different ogron classes (hellmaker, gutcher, orgenaut) use the same race_ogron armor, I decided to only up the armor to 8 sharp and 8 blunt, which is what the current feral mail armor is. Hopefully it'll give the ogrons enough survivability while not making it too tanky given its health pool.
- Buffs Ogrons 
- Increased ogron armor to 8 sharp and 8 blunt, the armor level used for feral mail
- Ogrons were easy to down due to lack of armor (1.5 sharp and 0.5 blunt currently)
- increases ogron survivability 
- Easy …

increase ogron armor to feral mail level

---

Source/CombatExtended/Harmony/Harmony_StunHandler.cs

EMP damage stuns turrets.
Check if the stun target is a pawn.  If it is, and it's dead or downed, return early.  Otherwise get it's body size.
If it *isn't* a pawn, use 1.0 as the default, instead of returning early.
- Closes #643 
Turrets, and possibly other EMP-affected things, are not pawns.  So casting them to `Pawn` is `null`.  The previous version jumped out if the stun target was not a pawn, leading to the unstunnable turret bug.

Fix #643 - EMP Stunning turrets

---

Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs

- Fix turret reloading to automatically pick new ammo types only for non-player factions, not the other way around.
- Closes #672

Fix mortar ammo change for sieges

---

Patches/A Rimworld of Magic/Patch_Apparel.xml
Patches/A Rimworld of Magic/Patch_Melee.xml
Patches/A Rimworld of Magic/Patch_Ranged.xml
Patches/A Rimworld of Magic/Patch_Stuff.xml

Added special greatbow ammoset for thrumbo bow
Improved the defensive specs of some of the more expensive gear, gave most the robes decent cloth thickness, adjusted the stats on materials to more closely match CE statting
Many of the apparels had very low stuffable rates for their cost/investment, and the robes in particular take up both middle and outer, so a bit of extra thickness dosen't really  break anything and makes them a bit more usable. A few of the stuffs were either too weak or too strong for the difficulty of aquiring them + their market value.
The thrumbo gear and composite item bade from two pieces of them, as well as some of the more expensive armor, were buffed since thrumbo gear is strictly limited by thrumbo appearances, and by the time you can make them, you can also …

Tweaks to Rim of Magic items/equipment

---

Patches/FF Bushi!/Headgear_Bushi.xml
Patches/FF Bushi!/Melee_Bushi.xml
SupportedThirdPartyMods.md

Mod adds three melee weapons and three masks. The weapons are generally somewhat lighter, shorter version of existing weapons.
- Katana is derived from a longsword. Somewhat shorter and lighter giving it faster attacks, but inferior stabbing damage.
- Wakizashi is a lighter gladius, giving it good stabbing but mediocre cutting. 
- Tanto is a longer, lighter knife.

Patch [FF] Bushi!

---

Patches/Pawnbold Race/Body_Pawnbold.xml
Patches/Pawnbold Race/PawnKinds_Misc.xml
Patches/Pawnbold Race/Race_Pawnbold.xml
Patches/Pawnbold Race/Scenarios_Misc.xml
SupportedThirdPartyMods.md

Patches the Pawnbold race, scenario, pawnkinds, and body.
- Closes #722 
- Pawnbold race is patched using the same stats as the existing O21 Kobold race, as the base versions are already largely identical.

Patch Pawnbold Race

---

Patches/Core/ThingDefs_Misc/Apparel_Hats.xml
Patches/Core/ThingDefs_Misc/Apparel_Various.xml
Patches/JDS Exiled Dawn/Thingdefs_Misc/Apparel.xml
Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml
Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Royal_Apparel.xml
Patches/Neclose Race/ThingDefs_Misc/Neclose_Apparel.xml
Patches/PowerArmour T-45b/T45b_CE_Patch.xml
Patches/PsiTech/ThingDefs/Equipment/PsiTechAdvancedApparel.xml
Patches/Rabbie The Moonrabbit/ThingDefs_Misc/RB_Apparel.xml
Patches/Rim Contractors Arsenal/ThingDefs_Misc/ApparelBodyArmour.xml
Patches/Rim Contractors Arsenal/ThingDefs_Misc/ApparelHeadgear.xml
Patches/Rimsenal Collection/Core/Apparel_RS_CE.xml
Patches/Rimsenal Collection/Federation/ThingDefs_Misc/Fed_Apparel.xml
Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_Apparel.xml
Patches/Save Our Ship 2/Apparel_SOS2.xml
Patches/Xenoorca Race/ThingDefs_Misc/Xenoorca_Apparel.xml
Royalty/Patches/ThingDefs_Misc/Apparel_Armor.xml
Royalty/Patches/ThingDefs_Misc/Apparel_Headgear.xml

Increased power armor tier apparel production costs. Generally increased helmet mass a bit.
Increased the avalibility of money for elite mercs so they can still reasonably get said armor
Tweaked some of the existing patches.
Re-did a lot of the rimsenal armor specifics to more closely match some of the vanilla attributes, as well as fix some instances where the armors had practically vanilla mass/boosting stats.
Reduction in plate and simple helmet costs.
Currently, power armor provides, proportionally for its raw resource cost, significantly more protection, coverage and passive benefits than any other options. While it's reasonable for higher tech items to make more efficent use of your resources and provide higher protection levels to justify the tech investment, power armor apparels …

PA tier cost rebalance

---

Defs/Bodies/BodyShapes.xml

- Adds a wider `Plane` bodyshape for aircraft, which does not change when laying.
- Adds a taller `QuadrupedTall` bodyshape, intended for tripod-like creatures that walk on especially tall, spindly legs.
Per my conversation with @Alicecomma, 'width' is actually a radius rather than straight distance or diameter--this would explain why humans measured 3+ meters wide when laying (they had widthlaying = height, and they are about 1.6m tall). I've adjusted some values accordingly.

Add new bodyshapes.

---

Patches/Rakkle the Rattlesnake/ThingDefs_Misc/Rakkle_Apparel.xml
Patches/Rakkle the Rattlesnake/ThingDefs_Races/AlienRace_Rakklelike.xml

Moved venom bite to the venom gland 'implant' to be consistent with the vanilla implementation. Slightly reduced regular bite damage to account for melee skil scaling. Removed redundant bulk/worn bulk stats from apparel that has been turned into implants.

Rakkle patch update

---

Patches/PsiTech/PawnKindDefs/PawnKinds_PsiTech.xml

1. Patch for Transcendant pawn kind;
2. Removal of most pawn kind combat power patches, only left penitent's;
3. Removal of acolyte pawn kind weapon money nerf patch;
4. Magazine amount changes for most pawn kinds: lower tier pawn kinds have less ammo, higher tier pawn kinds have more;
5. Elite tier pawn kinds always spawn with tactical vests;
6. Doubled sidearm money for commando pawn kind from 30 to 60;
7. Quadrupled sidearm money for warrior pawn kind from 30 to 120.
1. New mod content;
2. Recent combat power changes in the main mod as well as Combat Extended for the most part only changes combat power for tribal pawn kinds;
3. Does not provide much change, that's also one patch operation less;
4. Lower tier pawn magazine amount is the same of mercenary gunners, higher tier - similar …

PsiTech patch update

---

Patches/Vanilla Apparel Expanded - Accessories/Apparel_Utility.xml
SupportedThirdPartyMods.md

- Patches new belts and utility apparel added by VAE - Accessories.
- Backpack matches CE backpack stats.
- Quiver and ammo bag add bulk capacity, but their cooldown tweaks don't appear to work.
- Mini-turret pack currently doesn't work.

Patch VAE - Accessories

---

Source/CombatExtended/Harmony/Harmony_DamageWorker_AddInjury.cs

Only allow damage to propagate to siblings of squishy body parts when the damage type is not surgical or execution cut.
- Fixes #712 
Surgical removal works by inflicting massive damage on the targeted body part.  This damage needs to not propagate.
Calculate the exact damage needed to remove the part.  That is likely to be hard to do, given the possibility of mods which change how much damage the parts take.

Fix surgery on outside-squishy parts causing damage to containing part.

---

Defs/ThingDefs_Misc/Apparel_Headgear.xml
Patches/Core/ThingDefs_Misc/Apparel_Hats.xml
Patches/Core/ThingDefs_Misc/Apparel_Various.xml

Power armour price increase is a good move but I'm not sure why simple helmet and plate armour are getting price reductions? They aren't underpowered and do not need it at all , simple helmet is now OP compared to the composite helmet.
A small quantity of plasteel is very easy to acquire compared to devil strand and plasteel simple helmet is superior in everyway over composite helmet.

Helmet and Plate armour cost tweak

---

Patches/Halo Ammo/5x23mmCaseless.xml
Patches/Halo Ammo/9.5x40mm.xml
Patches/Halo UNSC Weapon Pack/UNSC_CE.xml
Patches/Mass Effect - Playable Geth/Ammo_ME.xml
Patches/Mass Effect - Playable Geth/Geth_Weapons_CE.xml
Patches/Rimeffect Core/Weapons_MEcore.xml
Patches/Rimeffect Extended Cut/Weapons_ME_ExtendedCut.xml

Forgot to balance weapon costs, also fixed a few issues with the weapons.
Not sure why 5x23mm caseless drops casing now, it literally has caseless in the name.
I'm adding drop casing=false to every projectile because they inherit FN 5.7 as base, which drops casing by default. 
Also tweaked the ranges of ME weapons.
Another thing, pls pls pls do not replace the 9.5mmx40mm with 9.5 ammo from patches from some other mods, it is carefully balanced with regards to other ammo that I just uploaded, replacing it from some other mod will ruin the balance. A lot of things are there for a purpose.

Missing Tweaks and fixes for Halo Weapon pack

---

Patches/Combat Enthusiast's Collection/ThingDefs_Weapons.xml
Royalty/Patches/ThingDefs_Misc/Weapons_Melee.xml

Reduced warhammer damage and increased its attack speed.
28 base dmg will result in tons of destroyed head and torso with no chance of being downed. You can still destroy heads with a single blow, but it now requires the user to have high melee skills.
Also slightly decrease axe melee cooldown.

Tweaks to warhammer

---

About/About.xml
Patches/Ancient Fallout Armory/Apparel_Armor.xml
Patches/Ancient Fallout Armory/Headgears_Fallout.xml
Patches/Vanilla Weapons Expanded - Grenades/Apparel_Packs-NonLethal.xml
Patches/Vanilla Weapons Expanded - Non-Lethal/NonLethal_Grenades.xml

Patches the tear gas grenade belt added when VWE - NL and VAE - Grenades are loaded together. Because this def is patched in by Grenades, Grenades must be loaded before CE.
Works as intended in testing. Closes #761 
Also adds stats to the Secret Service armor added in the update to Ancient Fallout Armory. Closes #768.

Patch teargas grenades, update Ancient Fallout Armory patch

---

.github/workflows/main.yml
.github/workflows/pullrequest.yml
.github/workflows/release.yml
Make.py

Add support for generating and using publicized assemblies
It's fast to write.  We want to get a release out tonight.
It's simple to use, as it builds the publicizer on-demand.
Build / download the publicizer as a separate step of the workflow.  Expect the publicizer to exist on the path by the time Make.py is called.  
Use the nuget package TaskPublisher - No good way to do that, as it requires dotnet build, which can allow arbitrary code execution while compiling PRs.
The list of assemblies to publish is contained in the .csproj, and should be dynamically read from there instead of hardcoded in the workflow file.  Also, the .csproj uses some variable expansions to reference the publicized libraries.  This is safely (but noisily) ignored.  

Add support for publicizing assemblies during build.

---

Defs/ThingDefs_Misc/Apparel_Carrying.xml
Ideology/Patches/HeDiffDefs/Hediffs_Casts.xml
Ideology/Patches/PawnKindDefs_Ideology/PawnKinds.xml
Ideology/Patches/ThingDefs_Misc/Apparel_Headgear.xml
Ideology/Patches/ThingDefs_Misc/Apparel_Ideology.xml
Ideology/Patches/ThingDefs_Misc/Items_Misc.xml
LoadFolders.xml

Patches all new content added by Ideology. Most of the content is unremarkable in regards to balance, save for the dryads.
All dryads save the Clawer and based fairly closely upon the labrador retriever stats. The Clawer is based mostly on the Warg, with slightly stronger attacks. These stats are fairly close to how they stack up in vanilla, compared to other vanilla creatures.
- Adds a vanilla apparel base to CE carrying gear. Without it, favorite colors cause problems.

Patch Ideology Content

---

Make.py

Pass `-unsafe` flag to `csc`.
Compiling against a publicized assebly without `-unsafe` flag results in runtime errors.
Don't use a publicized assembly.

Compile with `-unsafe` flag

---

Defs/ThingDefs_Misc/Apparel_Carrying.xml
Ideology/Patches/HeDiffDefs/Hediffs_Casts.xml
Ideology/Patches/PawnKindDefs_Ideology/PawnKinds.xml
Royalty/Patches/TraderKindDefs/TraderKinds_Royalty.xml

- Fixed the tribal pack visual offset.
- Increase the Ideology tribal pawn ammo
- Royalty: Add heavy ammo to traders
- Buff Marksman command reload bonus
- Increase range of combat command mote

More 1.3 tweaks

---

About/About.xml
Patches/Xenohumans - Anthromorphs/Races_Avianmorph.xml
Patches/Xenohumans - Anthromorphs/Races_Bovinemorph.xml
Patches/Xenohumans - Anthromorphs/Races_Caninemorph.xml
Patches/Xenohumans - Anthromorphs/Races_Cervinemorph.xml
Patches/Xenohumans - Anthromorphs/Races_Dragomorph.xml
Patches/Xenohumans - Anthromorphs/Races_Felinemorph.xml
Patches/Xenohumans - Anthromorphs/Races_Gnollmorph.xml
Patches/Xenohumans - Anthromorphs/Races_Lagomorph.xml
SupportedThirdPartyMods.md

Finishes a few missing things from the Xenomorph patch, namely giving added pawnkinds ammo as needed, patching a leather, and setting up required load order stuff (the mod uses "onDemand" defs similar to O21 Forgottten Realms).

Finished Xenohuman Patch

---

Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_Apparel.xml

The newest feral faction update changed the stats of the Scorcher Helmet, removing the blunt and sharp armor rating stats. Combat Extended is trying to replace these attributes with new values, but they no longer exist and thus the error is thrown. As such, the CE blunt and sharp armor stats are added
-replaces the "PatchOperationReplace" with "PathOperationAdd" when referring to the sharp and blunt armor

update the scorcher helmet

---

Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Neolithic/Arrows.xml
Defs/Ammo/Neolithic/GreatArrows.xml
Patches/Arasaka Corporation [1.3]/7mmMiniRailgun.xml
Patches/Arasaka Corporation [1.3]/BigBrainGyrojet.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Patch_Bodies.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/PawnKinds_Misc.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Chitine.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Dwarf.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Gith.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Goblin.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Halfing.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Illlithids.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Kobold.xml
Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Tabaxi.xml

Any newly added projectiles that use basebullet as parent will throw error, replacing it with something else.

Quick Fixes

---

Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_Apparel.xml

Updated the xpaths for the `ArmorRating_Blunt` and `Apparel_ScorcherHelmet` attributes for the Scorcher Helmet defined in the **Rimsenal - Feral Faction Pack** so that the patching operation now succeeds.
The 31.07 update of the **Rimsenal - Feral Faction Pack** changed the stats of the Scorcher Helmet, removing the blunt and sharp armor rating attributes. Commit eb9adaa2888626d132bbaf51b5174580bb10ca34 reintroduces those attributes for Combat Extended, but has an incorrect xpath defined for the attributes which causes the patching operation to fail.

Fixed the xpath for Scorcher Helmet armor attributes

---

Patches/Save Our Ship 2/Apparel_SOS2.xml

- removed the adding of `ToxicSensitivity` equippedStatOffsets for `Apparel_SpaceSuitHelmet` & `Apparel_SpaceSuitHelmetHeavy`
- ToxicSensitivity value is now part of the SOS2 mod and is identical with the patch

SaveOurShip2 - remove ToxicSensitivity from Helmet

---

Patches/Medical System Expansion 2/Defs/HediffDefs/Modules/Hediffs_Modules_Bionics.xml

Compared to unpatched values:
1. Added aiming accuracy buff to the ranged platform module;
2. Added reload speed buff to the ranged platform module;
3. Reduced weapon handling buff of the ranged platform module;
4. Reduced the aiming delay factor buff of the ranged platform module;
5. Added parry chance buff to the melee platform module;
6. Added crit chance buff to the melee platform module;
7. Reduced dodge chance buff of the melee platform module;
8. Reduced hit chance buff of the melee platform module;
1., 2., 3., 4. CE adds aiming accuracy and reload speed, so the ranged platform module now includes those shooting-related stats. Reduction of weapon handling and aiming delay buff just to make it saner for CE. A level 6 shooter with 6 (maximum amount) of those modules and nothing else …

Medical System Expansion 2 - stat offset changes/CE patch for combat modules

---

Source/CombatExtended/Harmony/HarmonyBase.cs
Source/CombatExtended/Harmony/Harmony_ThingOwner.cs

Replaced hundreds of generic ThingOwner<T> patches for several ThingOwner patches.
On heavily modded game CE Controller take a long time (11 seconds) to patch all specific realisations of ThingOwner<T>:
```
11739.3835ms (self: 20.2696 ms) Loading CombatExtended.Controller mod class
- 11719.0974ms (self: 1.1003 ms) Apply Harmony patches
- - 1178.0265ms (self: 1178.0265 ms) instance.PatchAll
- - - 10244.3970ms (self: 4.6578 ms) PatchThingOwner
- - - - 0.0255ms (self: 0.0255 ms) Getting postfix methods
- - - - 94.6166ms (self: 94.6166 ms) Getting patching class collection
- - - - - 23.2577ms (self: 23.2577 ms) Patching Verse.Pawn
- - - - - 16.8603ms (self: 16.8603 ms) Patching Verse.Building
- - - - - 27.9172ms (self: 27.9172 ms) Patching Verse.Corpse
- - - - - 17.9170ms (self: 17.9170 ms) …
```

Reduced amount of ThingOwner patches and total game startup time

---

Patches/Better Infestations/Race_Insect.xml

1. Patch mod name target from `Better Infestations 1.2` to `Better Infestations 1.3`.
1. Better Infestations mod name changed when it updated from RimWorld 1.2 to 1.3.

Better Infestations - updated patch's mod name target.

---

Defs/Ammo/Neolithic/BlowDarts.xml
Defs/Ammo/Neolithic/SlingBullet.xml
Languages/Russian/DefInjected/RecipeDef/SlingBullet.xml
Languages/Spanish/DefInjected/RecipeDef/SlingBullet.xml
Languages/SpanishLatin/DefInjected/RecipeDef/SlingBullet.xml
Patches/Core/ThingDefs_Items/Items_General.xml

None
- Added patch to Core that ensures that `@Name=ChunkBase` (stone and metal chunks) have `<stuffProps>` even if empty.
It allows chunks to be used as ingredients in recipes without throwing "not a stuff" error.
- Updated some incorrect labels/descriptions for some neolithic ammo recipes: invalid count, darts instead of arrows
- Fixes #934
No idea why this is not vanilla (possibly me just being inexperienced). The only problem I can see with this solution is if some other mod will try to patchAdd stuffProps to chunks without checking for existence first causing incompatibility.
Another option is to remove rock chunk from recipe and just create bullets from nothing. This can be justified as gathering good stones around instead of breaking large chunk into them. …

Sling bullets recipe fix #934

---

Defs/Misc/TipSetDefs/Tips.xml
Defs/ThingDefs_Misc/Apparel_Carrying.xml
Defs/ThingDefs_Misc/Apparel_Headgear.xml
Patches/Kobolds of the Rim/Apparel_Kobold.xml
Patches/Kobolds of the Rim/Melee_Kobold.xml
Patches/Kobolds of the Rim/Patch_Body_Kobold.xml
Patches/Kobolds of the Rim/PawnKinds_Kobold.xml
Patches/Kobolds of the Rim/Race_Kobold.xml
Patches/Tribal Warrior Set/TribalWarrior_Apparel.xml
SupportedThirdPartyMods.md

Patches Kobolds of the Rim (which I meant to make its own branch, but I'm an idiot...). Mod adds a kobold race, some pawnkinds, some apparel, and a few weapons. Most all based on existing stats.
A few fixes and adjustments.
- Update the patch for Tribal Warrior Set! mod.
- Packs, , gas masks, and NVGs no longer count as clothing for nudists.
- Fix typo

Patch Kobolds of the Rim, Various Fixes

---

Patches/Kit's Gunpowder Weapons/Ammo_KitsGunpowder.xml
Patches/Kit's Gunpowder Weapons/KitsGunpowder_Security.xml

- Added compatibility for Bombard, 12-Pounder, and Organ
- Buffed Cannon Ball blunt penetration from 18 to 110 (Why was this set to 18 in the first place, did I do that?)
- Because Security/Turrets were patched in the initial merge and were removed in 1.3, I guess. 
- I just happened to see that the CannonBall somehow had a ridiculous 18 blunt penetration.

Kits Gunpowder Weapons Security Update

---

Defs/Ammo/Flare.xml

Flares now have damageDef (smoke) and AP stats (all 0) to allow it used on the Caliber stat and to prevent other errors on displaying its stats.
Previously caused problems like this:
```
What's That Mod: Exception generating def description for [CombatExtended.AmmoDef] Ammo_Flare from mod Combat Extended:
System.NullReferenceException: Object reference not set to an instance of an object
at CombatExtended.AmmoUtility.GetProjectileReadout (Verse.ThingDef projectileDef, Verse.Thing weapon) [0x00192] in <ccb6738ca9da4e0ba4122c09aec10cab>:0 
at CombatExtended.StatWorker_AmmoCaliber.GetExplanationUnfinalized (RimWorld.StatRequest req, Verse.ToStringNumberSense numberSense) [0x00142] in <ccb6738ca9da4e0ba4122c09aec10cab>:0 
at WhatsThatMod.CE_Compat.GetProjectileReadout (Verse.ThingDef …
```

Added damageDef and AP to flaregun to fix caliber and similar bugs

---

Patches/Core/ThingDefs_Misc/Weapons_Melee.xml

I personally find the long sword deeply underwhelming, its stab attack is slow and does low damage. So I buffed it abit to make it less underwhelming.
I'd like to change the quality modifier for melee weapons in the the future, lower its effect on weapon melee damage output and more effect on weapon melee penetration + weapon durability.

Melee weapons tweak

---

Defs/Ammo/Shell/155mmHowitzer.xml
Patches/Vanilla Furniture Expanded - Security/Ammo_Security.xml

- VEF-Security mortar turret bug fix.
Change two mortar ammo def <speed> into 0.
#1005 
Curved shot ammo <speed> just should be 0, If I understand correctly.

[Bug]:Artillery and catapult in VEF-Security just don't run right.

---

Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Medieval/MusketBall.xml
Defs/Ammo/Neolithic/Arrows.xml
Defs/Ammo/Neolithic/BlowDarts.xml
Defs/Ammo/Neolithic/GreatArrows.xml
Defs/Ammo/Neolithic/Javelins.xml
Defs/Ammo/Neolithic/SlingBullet.xml
Defs/ThingDefs_Misc/Weapons_Grenades.xml
Patches/A Rimworld of Magic/Patch_Ranged.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Core/TraderKindDefs/TraderKinds.xml
Patches/Core/TraderKinds.xml
Patches/Forsakens/Forsakens_CE_Patch_Ammo_ForsakensArrows.xml
Patches/Kit's Roman Weapons/Roman_Weapons.xml
Patches/Rimsenal Collection/Core/Weapons_Explosives.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Ammo_EnhancedVanilla.xml
Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedIndustrialGrenades.xml
Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedMedieval.xml
Patches/Vanilla Factions Expanded - Vikings/Weapons_Medieval.xml
Patches/Vanilla Weapons Expanded - Grenades/Apparel_Packs-NonLethal.xml
Patches/Vanilla Weapons Expanded - Grenades/Apparel_Packs.xml
Patches/Vanilla Weapons Expanded/Medieval_Ranged.xml

So I've being patching a few medieval mods and I find weapons like the greatbow functionally useless due to its extremely slow projectile speed, it is actually impossible to hit anything with it.
I've tweaked the speed and damage of various pre-industrial projectiles, as well as adding them to neolithic traders.
Also standardised a few throwing weapons.

Tweaks to Pre-Industrial Ammo and grenades

---

Patches/Eltex Bodysuit/Apparel_Various.xml
SupportedThirdPartyMods.md

A very small patch for the Eltex Bodysuit mod, which adds a single piece of apparel. The mod is currently still for RW 1.2, but it loads and works in 1.3 without errors.

Patch Eltex Bodysuit Mod

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Source/CombatExtended/CombatExtended/CE_Utility.cs
Source/CombatExtended/CombatExtended/Defs/ApparelBodyPartStatModifier.cs
Source/CombatExtended/CombatExtended/Defs/ApparelStatExtension.cs
Source/CombatExtended/CombatExtended/Defs/BodyPartModifier.cs
Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

- Added mass ratios to projectiles. (A passive system)
- Added the ability to apply modifiers on each stat of an apparel to a single body part. Example
```xml
<li Class="CombatExtended.ApparelStatExtension">
<modifiers>
<ArmorRating_Sharp>
<Brain>0.2</Brain>
<Neck>0.8</Neck>
</ArmorRating_Sharp>
<ArmorRating_Blunt>
<Brain>0.1</Brain>
<Neck>0.5</Neck>
</ArmorRating_Blunt>
</modifiers>
</li>
```
In this example brain will have a body 10% of the parent apparel armor. Note:  this is a  mod def extension and should be added to each apparel on a case by case basis. 
- If a projectile is moving at less then it max speed then its damage will be lowered. 
- If a projectile has a missing percentage of mass its damage will be reduced.
Note that both changes of mass and speed won't affect CE without …

Projectile mass and Apparel stats

---

Source/CombatExtended/CombatExtended.csproj

Makes explicit the language version used by the C# source of the mod. Should not change anything, this simply prevents different contributors possibly using differing language versions.

Explicitly use C# 8

---

Defs/Ammo/Shell/155mmHowitzer.xml
Defs/Ammo/Shell/50mmType89Mortar.xml
Defs/Ammo/Shell/60mmMortar.xml
Defs/Ammo/Shell/81mmMortar.xml

Some tweaks to bad balance(extremely overpowered shells) that's being bugging me immensely.
How is that Incendiary shell has huge radius and do guaranteed stunlock + continuous damage against all target, whereas HE shells are next to useless and probably won't do damage even on direct hits because fragments are a joke and Area explosions are even worse.
I'll probably tweak the HE armour pen in later PR.

Tweaks to shell balance

---

Source/CombatExtended/Harmony/Harmony_ShieldBelt.cs

In #767, the old shield belt patch was disabled due to breakage, which
now allows for ranged weapons to be used even if their wielder is
wearing a shield belt. Fix the shield belt patch to correctly consider
both vanilla and CE ranged verbs when determining if they can be used
while wearing a shield, maintaining the existing exception for CE
binoculars.
Also remove various dead code from the shield belt patch. Vanilla shield
belts no longer run a reachability check in 1.3 and the relevant part of
the patch got commented out in #767, so let's get rid of it. Likewise,
the turret-related parts also seem to be dead code, as the
TurretsBreakShields settings only controls whether a pawn's shield belt
should be disabled while they're manning a turret, not whether they can
fire the turret - which …

Prevent using ranged weapons with shield belts

---

Source/CombatExtended/Harmony/Harmony_JobGiver_AIBreaching.cs

This is an alternative solution to fixing mechanoid breach raids. As
outlined in more detail on #1080, mech breach raids are currently broken
because they cannot utilize breaching weapons that have a nonzero
friendly fire avoidance radius. #1080 sidesteps that by removing the
friendly fire avoidance radius from mechanoid breach weapons (the thump
cannon and the inferno cannon), while this patch instead transpiles the
breaching jobgiver to add an exemption for mechs and let them utilize
these weapons.
- Closes #1015 

Alternative fix for mechanoid breach raids (I)

---

Defs/Ammo/Rocket/RPG7.xml

I dunno why all RPG-7 ammo is about 0.2kg heavier than they are on the internet, so I've changed it.
I also changed the thermobaric ammo to do abit more damage, require advanced ammunition tech to craft and need Prometheum to make.
Who knew that thermobaric warhead require incendiary agent to craft? Crazy.

RPG-7 tweaks

---

Source/CombatExtended/CombatExtended/Jobs/JobGiver_DefenderReloadTurret.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_ManTurretsNearPointCE.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_ManTurretsNearSelfCE.cs
Source/CombatExtended/CombatExtended/TurretTracker.cs

Change `JobGiver`s which use `Building_Turret`s to use the turret cache map component. Improves performance for larger bases significantly by not searching every artificial building on the map.
Should not introduce any new behaviors. 
_Technically_ the old method searched all `Building`s on the map, and would sometimes omit a check to ensure the building was infact a subclass of `Building_Turret`, this however seemed to be rejected in other methods, as they assume that the thing passed was in fact a turret, and would early out in the case it wasn't.
If there are in fact examples of things CE considers turrets which do not subclass `Building_Turret`, the `Turret_Tracker` class should be updated.

Improve performance of job searching relating to turrets

---

.github/workflows/main.yml
.github/workflows/pullrequest.yml
.github/workflows/release.yml
Building.md
Make.py

Uses a proper argument parser, which keeps the usage string in sync with the underlying options, handles short-form options, handles `--option=value` properly.
Uses a modular approach, with different steps broken into different functions, and without everything in the global namespace.
Reads the files to publicize from the `.csproj` directly.
The existing Make.py started as a 15 line script barely smart enough to extract the list of `.cs` files to compile, and never intended for fully-automated use.  As the `.csproj` file complexity grew, more and more dirty hacks piled up, and the time to re-read and understand the script got worse.  So it was time to scrap it and do it right.
The new version parses the csproj in pieces, so if a new bit of information needs extracting from the csproj, …

Rewrite make.py

---

Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs
Source/CombatExtended/CombatExtended/Things/AmmoThing.cs

Currently, the jobgiver for reloading turrets may give out a job to
reload a turret with a stack of ammo that's currently cooking off, which
results in a loop as it causes the jobdriver to fail the job. As a fix,
ensure that the jobgiver does not attempt to use ammo which is cooking
off.
For correctness, also make sure that ammo types which can never cook off
(e.g. 12x64mm mechanoid ammo) are never considered to be cooking off.

Avoid potential loop while reloading turrets

---

Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Neolithic/Arrows.xml
Defs/Ammo/Neolithic/GreatArrows.xml
Defs/DamageDefs/Damages_LocalInjury.xml

Make sure that fire arrows don't start a fire on every hit. Flame damage
type effectively guarantees that the target will be set on fire
irrespective of explosionChanceToStartFire, and CE chemfuel puddles also
autoignite, so use Arrow damage type instead with a chance to spawn a
chemfuel puddle (that will then ignite).
The chance to spawn chemfuel is kind of a placeholder value atm. We
could fine-tune it with additional testing.

Reduce fire starting chance of fire arrows

---

Patches/Core/ThingDefs_Misc/Apparel_Hats.xml
Patches/Core/ThingDefs_Misc/Apparel_Various.xml
Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml
Royalty/Patches/ThingDefs_Misc/Apparel_Armor.xml

Currently they feel exactly the same, so I've taken some steps to make them different, Recon armour has less blunt(why do they have almost as much blunt as power armour?), but is more zoomie, Cataphract armour is slower and has difficulty dodging.

Make vanilla power armours more distinct

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Source/CombatExtended/CombatExtended/Jobs/JobDriver_ModifyWeapon.cs
Source/CombatExtended/CombatExtended/Things/WeaponPlatform.cs

- Fixed issues related to the magazine count being larger than the magazine size due to a removed magazine attachment.
- Now pawns will unload all guns before making any changes to them.
- Added new consistency checks on save loading.

Attachments Mag bug fix

---

.github/workflows/pullrequest.yml

Explicitly disabled fast-forward pull when automatically building PRs.
The pull request auto-builder clones Development, then hard pulls the PR.  If the two have diverged, it fails with an error about not knowing how to reconcile the differences.  Passing `--no-ff` to `git pull` explicitly disables fast-forward merge, which allows it to successfully pull the PR's changes.

explicitly disallow fast-forward

---

Languages/English/Keyed/ModMenu.xml
Make.py
Source/CombatExtended/CombatExtended/CE_DebugTooltip.cs
Source/CombatExtended/CombatExtended/CE_DebugTooltipHelper.cs
Source/CombatExtended/CombatExtended/CE_DebugTooltipType.cs
Source/CombatExtended/CombatExtended/CE_DebugUtility.cs
Source/CombatExtended/CombatExtended/Settings.cs

Added a simple system that should allow us to implement tool tips for debugging purposes both in maps and on the world view. This system works by:
1. Finds all functions that have the `CE_DebugTooltip` attribute.
2. If debugging is enabled in CE settings, these functions will be called when the input requirements are met. (by default holding shift, it can be changed)
3. If it's a map, the map and the cell directly under the cursor is passed. If it's a planet (world view), the world and the tile index are passed.
4. The resulting string is used in a new `TipSignal`. 
This system doesn't change anything in CE. The new code can only run if debugging is enabled, so no risk is involved in this
A simple example:
```cs
[CE_DebugTooltip(CE_DebugTooltipType.Map)]
public static string …
```

Debug tooltip helper

---

Defs/ThingDefs_Buildings/Buildings_Production.xml

No new changes
Removed BenchBase overwrition, which isn't clear why it's here at all. No mods should overwrite vanilla bases.
Here is the screenshot of xml bases comparison. Left is CE, right is Vanilla.
No mod should overwrite vanilla bases, for changes use xml patches, so they inject the changes in the right place, not overwriting the whole thing.

Remove BenchBase overwrition 

---

About/About.xml

RimPy's autosorting would not place CE after More Utility Packs, which resulted in patch errors on Royalty-dependent apparel. That was due to MUP being referenced in loadAfter by name, not PackageID. That was fixed.

Changed More Utility Packs' name to PackageID in loadAfter

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/Utilities/GenClosest.cs
Source/CombatExtended/Utilities/Tracking/ThingsTracker.cs
Source/CombatExtended/Utilities/Tracking/ThingsTrackingModel.cs

- Don't stop raycasting early if above the height of walls; some targets are taller than walls.
- Let lasers apply suppression along their path
(Edit by N7)
Closes #805

let lasers hit things taller than walls

---

Patches/Xenohumans Expanded/Races_Radman_XH.xml
Patches/Xenohumans Expanded/Races_Vatgrown_XH.xml

- Fixed incorrect defName for VatgrownHumanRace;
- Switched operation from Replace to Add for RadWorlderRace's armor ratings - it doesn't have them prior to the patch.
Initial implementation was throwing XML patch operation errors on load, and upon inspection issues became visible.
Cutting out the armor values for radworlders? I didn't find the reason they have them - the mod in question only references their resistance to disease and toxic hazards.

Xenohumans Expanded patch fixes

---

Make.py

Implicitly exclude the original libraries when they are publicized
The new publicizer format in the `.csproj` doesn't expliticly exclude the un-published assemblies.  If the compiler finds the un-published version before the published version, it causes the build to fail.  This is why PRs have failed building sometimes, but the same branch in a new PR builds successfully.
Explicitly exclude the pre-publicized libraries.

implicitly exclude libraries which have publicized alternatives

---

Patches/NewRatkinPlus/ThingDefs_Races/Race_Rakinlike.xml

- Changed Ratkin fist damage capacity type to `Blunt`
- Rebalanced power, cooldown time and blunt armor penetration to baseline human levels
Aside from having rat ears and tails, Ratkins are functionally identical to 140~150 cm tall teenage human girls, and do not have rodent claws on their fingers. The proposed rebalance brings them more in line with baseline humans.
Retaining the current patches would give Ratkins an unfair advantage over humans and most other humanoid races.

Rebalance Ratkin race melee tools

---

Defs/Ammo/Advanced/12x70mmCharged.xml

A very minor fix for 12x70 charge recipe label being incorrect.

Fix recipe labels

---

Patches/Expanded Woodworking/Items_Resources.xml

Patched woodlogs and lumbers from Expanded Woodworking (Forked) mod to have the same stats as vanilla woodlog. All the stats were taken from woodlog patch, feel free to tweak if anything. 

Expanded Woodworking (Forked) Patch

---

Source/CombatExtended/CombatExtended/AmmoUtility.cs
Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs
Source/CombatExtended/CombatExtended/GenExplosionCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/Things/AmmoThing.cs

Bump the armor penetration factor of explosion damage to 0.25, up from
0.1. This aims to make direct damage from explosions more dangerous.
Also factor out duplicated armor penetration calculations into helpers
in AmmoUtility so that it's easier to adjust the armor penetration
factor in the future.

Increase explosion armor penetration

---

Patches/Rimeffect Drell/Apparel_Drell.xml
Patches/Rimeffect Drell/Drell_Race.xml
Patches/Rimeffect Drell/PawnKinds_Drell.xml
Patches/Rimeffect Drell/Projectiles_Drell.xml
Patches/Rimeffect Drell/Scenarios_Drell.xml
Patches/Rimeffect Drell/Weapons_Drell.xml
SupportedThirdPartyMods.md

- Adds a patch for Rim-Effect: Drell. Viper is based off the Mantis, with higher rate of fire and lower damage. Locust is based off the tempest, with slightly higher rate of fire and longer range, and slightly less damage. 

Patch Rim-Effect Drell

---

Patches/Bulgarian Imperial Uniforms/Apparel_Industrial.xml
Patches/Bulgarian Imperial Uniforms/RangedIndustrial.xml
SupportedThirdPartyMods.md

Patches the Bulgarian Imperial Uniforms mod.
The mod adds two weapons (both the same rifle, one with a bayonet), a hat, a uniform, and a webbing/backpack combo. The webbing combo has a base value of 45 carry bulk (versus 30 apiece for the backpack and tac vest), since it occupies both slots but the webbing itself is inferior to a tac vest in terms to actual capacity.

Patch Bulgarian Imperial Uniforms

---

Patches/FROG Suit Set/Armor_Spacer.xml
Patches/FROG Suit Set/Industrial_Ranged.xml
SupportedThirdPartyMods.md

Patches the FROG Suit Set mod, which adds a G3 rifle and two pieces of apparel, an armored bodysuit and accompanying helmet.
Closes #1187

Patch FROG Suit Set

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Vanilla Factions Expanded - Ancients/CustomGenDefs_Vaults.xml
Patches/Vanilla Factions Expanded - Ancients/ThingDefs_Sentry.xml

- Add a bit more 5.56mm NATO ammo to most vaults, to supply turrets.
- Add ammo to new vaults added by VFE:A
- Made the Minigun non-destroy on drop, so the one the spawns in one of the vaults is usable (the minigun is already patched within the files)
- Give the Ancient Sentry turret slightly more health, since it's not the makeshift piece of junk the miniturret explicitly is said to be. 

Update VFE: Ancients Patch

---

Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/80x256mmFuelCell.xml
Patches/Rim-Effect Asari and Reapers/Ammo_Projectile_Reapers.xml
Patches/Rim-Effect Asari and Reapers/Asari_Trader.xml
Patches/Rim-Effect Asari and Reapers/Buildings_Reapers.xml
Patches/Rim-Effect Asari and Reapers/Races_Reapers.xml
Patches/Rim-Effect Asari and Reapers/Weapons_Reapers.xml

A handful of final content patches I forgot to add with the previous PR.
- Patches for Reaper turrets.
- Patches for Asari traders.
- Gave Reaper Husks appropriate stats such that they don't feel pain or fear of incoming fire.
- Gave Names to some Mechanoid ammo, so it can be used as a Parent for some reaper ammo.

Rim-Effect: Asari & Reapers Final Patches

---

Source/CombatExtended/Compatibility/Trenches.cs

Move the mod-specific height-adjust check into a private method so it doesn't try to resolve types in unused code paths.
Otherwise Mono barfs on the missing types if VFE-security is not loaded.
- [] (For compatibility patches) ...with patched mod loaded

Fix trenches missing VFE class when VFE-sec not loaded

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

Fixed a bug where missing bodyparts would cause First() instruction to fail

Fix missing bodyparts bug

---

Patches/Android Tiers - TX Series/PawnkindDefs/PawnKinds_Android.xml
Patches/Android Tiers - TX Series/ThingDef_Races/AlienRace_Androids.xml
SupportedThirdPartyMods.md

- Restores the Android Tiers TX Series patch from prior to version 1.3.4.4.
Closes #1236 
This patch folder was originally labeled as "Android Tiers++," a 1.0 mod whose content was integrated into Androids, and so these files were deleted as obsolete in the 1.3.4.4 release. This PR restores those files and the correct mod name.

Restore Androids Tiers - TX Series Patch

---

Patches/Feles - Felines of the Rim [1.3]/Bodies_Feles.xml
Patches/Feles - Felines of the Rim [1.3]/Feles_Leather.xml
Patches/Feles - Felines of the Rim [1.3]/Races_Feles.xml
Patches/Feles - Felines of the Rim [1.3]/Scenarios_Feles.xml
Patches/Warhammer - Dryad/Race_Dryad.xml
Patches/Xenohumans - Anthromorphs/Races_Vulpinemorph.xml
SupportedThirdPartyMods.md

- Patch the Feles Race mod. They're smaller than humans, with less carry weight and bulk, lower crit chance, higher dodge, and some night vision.
- Updated Warhammer Dryads race. The defName was changed without any other changes.
- Patch Xenohumans Vulpinemorphs. As with the other races, they're completely statistically identical to normal humans.
Close #1233 
- Additional use for animals
- Anachronistic
- Breaks realism theme

Patch Feles Race Mod + Small Patch Updates

---

Defs/Stats/Stats_Weapons_Ranged.xml

- Hide the `Sight Efficiency` stat if the value is zero. Realistically, only melee weapons have 0 SE, so there should be no harm in hiding it.
-  Hide `Recoil` if the value is zero. Since recoil only applies to weapons capable of automatic fire, it's meaningless in other cases. This could theoretically hide the info from the player in the case of an automatic weapon whose defined recoil is zero, but I don't know that this is meaningful information in that case any way.
- Hide `Reload Time` if it doesn't have a defined value. This way, it will no longer appear for melee weapons or ranged weapons that don't reload (like single-use rockets).
- Hide the `Muzzle Flash` stat if the value is undefined. This should hide that stat on weapons where it's not useful info (like melee weapons) without …

Hide Unnecessary Weapon Stats

---

Patches/Save Our Ship 2/Hediffs_SOS2.xml

- Added patched armor values for the archotech hologram hediff (`SoSHologramArchotech`) in the Save Our Ship 2 patch.
The default SOS2 version of this wasn't patched and gave 0.75 sharp armor and 0.5 blunt armor, which is extremely low by CE standards. This patch should change it to be more in-line with SOS2 values and survivability. Since archotech holograms don't really have an IRL equivalent to refer to w.r.t material and penetration properties, I just chose the values to be comparable to a flak vest, which is approximately in-line with where the vanilla values fall.
I could have not patched it and just dealt with it I guess
- [ x ] (For compatibility patches) ...with and without patched …

SOS2: Added archotech hologram armor values

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

- Added backpacks to required apparel for men in black
- Increased the amount of ammo men in black can spawn with
- Men in black spawn with the default carry bulk which is low for the apparel they wear and usually don't spawn with additional ammo for their weapon.
- The amount of ammo they spawn with is quite low for a pawn who is supposed to arrive and save the colony from danger.

Allow men in black to spawn with backpacks

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml

- Changed the research project required for autocannon and uranium slug turrets to the proper one.
- Changed the ammo type the uranium slug turret uses to 30mmNATO for consistency's sake and more usefulness.
- Autocannon and uranium slug turrets are heavy auto-turrets and should be coupled with the heavy auto turret added by CE, not manned turrets
- Uranium slug turrets currently use the 90mm shell which is a bit silly considering their name and use-case. Also there is a manned 90mm flak turret which is enough for 90mm shell usage. Also the switch from 90mm shells to 30mm rounds is more consistent with other weapons patched for CE.
- Leave the research projects be as is
- Leave the uranium slug turret untouched

Turrets Tweaks

---

Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml

Closes https://github.com/CombatExtended-Continued/CombatExtended/issues/1238
- Fixed the auto tesla turret from VFE - Mechanoids. Since it uses a custom thingClass, changing it to the CE's turret thingClass wouldn't let it fire its special chain projectile. Changed range values, warmup and cooldown times to match CE values better along with its damage type from Burn to Electrical.
- Tweaked Raider mech's weapon sway and SightsEfficiency to reflect its new caliber better since it's not using 20x110mm cartridges anymore and the values seem to have been unchanged when switched from 20x110mm to 7.62NATO.
- Change its weapon's projectile from 7.62NATO to .338 Norma Magnum to make it less useless for the cost of the mech itself.
- Tweaked and fixed some of the warmup and cooldown times on the …

VFE - Mechanoids Auto Tesla Turret fix

---

Patches/Pulsefire Turret/PulsefireTurret_CombatExtendedPatch.xml

Adds proper ammunition to pulsefire turrets.
Increased magazine size for twinfire turrets now using Charge SMG ammo
Single shot pulsefire now using 8x50mm
nil
- Pulsefire turrets were considered spacer tech and speaking with the original mod author, the original CE patch was a quick fix and not meant to be anything permanent 
- I am considering different ammo types 

Pulsefire Turret Balance

---

Patches/Apex - Rimworld Legends/ApexRimworldLegends_Weapons_AssaultRifles.xml

Tweaked to ad
nil
Adjusted RoF to mimic gun performance in Apex Legends, 
Increased magazine size to make the guns more feasible, using their extended mag variants from Apex Legends
nil
nil

Apex rimworld legends AR tweaks

---

Patches/More Psycasts/AbilitiesPatch.xml

- Added a patch for More Psycasts mod (https://steamcommunity.com/sharedfiles/filedetails/?id=2460833332)
- Increase the range on psycasts added by More Psycasts
- Ranged psycasts are patched to have more range in CE so patched psycasts added by More Psycasts to have more range

Add patch for More Psycasts mod

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Made Miniguns craftable with a balanced crafting recipe and removed the move speed offset
- Other mods have craftable versions of Miniguns so why not?
- Leave the miniguns uncraftable and buyable or quest reward only

Craftable Miniguns

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Vanilla Weapons Expanded - Heavy Weapons/RangedIndustrialHeavy.xml

- Changed the ammo type the Autocannon uses to 20mmn NATO
- Consistency
- Leave the ammo type be as is

Autocannon ammo type switch

---

Patches/Windows/Openvindows.xml

Applying the same patch CE already does to the original mod to the Windows fork mod
Applies the same patch CE already does for the original "[JPT] Open The Windows" to the "Windows" fork  by Owlchemist.
Changing the fillPercent to 0.6
Allow pawns to use windows to shoot. I actually thought the temperature would equalize when messing with the fillpercent, but it doesn't, respecting the mods own windows gizmo that controls wether air should pass or not.

Patching WindowBase

---

Languages/English/Keyed/Misc_Gameplay.xml
Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs

Increased base height hit chances and improved automatic targetting

Caulaflower melee targetting tweaks

---

Patches/Vanilla Ideology Expanded - Dryads/DamageDefs/Animal_Projectile_Shoot.xml
Patches/Vanilla Ideology Expanded - Dryads/DamageDefs/Animal_Projectiles.xml
Patches/Vanilla Ideology Expanded - Dryads/ThingDefs_Items/Items_Resource_Stuff.xml
Patches/Vanilla Ideology Expanded - Dryads/ThingDefs_Races/Races_Animal_AwakenedDryads.xml
Patches/Vanilla Ideology Expanded - Dryads/ThingDefs_Races/Races_Spitter_RangedAttack.xml

- Made the Awakened Dryads functional in CE 
- Added range and accuracy to both ranged 'spitter' Dryads
- Changed the acid projectile to CE Projectile
- Altered the stats of Gaubric (Fur/Leather) to bring it more in line with other materials in CE
- Brought the mod in line with other similar mods and made it so that the new features and creatures added worked in CE

Vanilla Ideology Expanded - Dryads Patch

---

Patches/Cursed Guns/CursedAmmo.xml
Patches/Cursed Guns/CursedGuns.xml
Patches/Cursed Guns/Fedora.xml

Compatability for all guns of the Cursed Guns mod as well as the fedora hat from it.
- I tried to make the guns based on stats of similar guns that already have integrated patches.
- I felt that having a separate 40mm launcher to launch only rubber bullets was unnecessary, so I removed it in favor of adding a 40mm rubber slug that all 40mm grenade launchers should be able to use.
- The fedora hat was patched in exactly the same way as the cowboy hat because I think they're similar enough.
- The 40mm rubber slugs use the 40mm Grenade HE sprites for ammo, because making an ammo sprite that would fit the existing aesthetic is too hard for me.
- The Ballistic Knife Blades ammuthing for the kniper use the dart sprites for ammo, because making an ammo sprite that would fit the existing …

Cursed guns patch

---

Patches/uselessclothes/uselessclothespatch.xml

Adds compatibility with Useless Clothes which adds a bunch of useless clothes to the game, by pulling up their armor stuff value up to VE apparel standards. 
Only adjusted stuff effect value. No other changes. 
- I just like useless clothes. 
Full in game year have passed with everyone using useless clothes. No errors associated with useless clothes.

Useless Clothes compatibility

---

Patches/Vanilla Ideology Expanded - Hats and Rags/Apparel_Headgear.xml

From Aquiles#4265 on discord:
> After many hours of testing, I found the error in the patch for Vanilla Ideology Expanded - Hats and Rags. The CE patch seems OK at first glance, but to make the error disappear a small change is needed: in the Apparel_Headgear file, the PatchOperation for the HorseMask should be Replace, not Add. Just in case you want to merge it to the github version.

Small fix for Horse Mask

---

About/About.xml
About/Manifest.xml
Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Projectiles.xml
Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Races.xml
Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Resources.xml
Patches/RimWorld - Witcher Monster Hunt/Races_CyclopsCE.xml
Patches/RimWorld - Witcher Monster Hunt/Races_EkimmaraCE.xml
Patches/RimWorld - Witcher Monster Hunt/Races_FlederCE.xml
Patches/RimWorld - Witcher Monster Hunt/Races_FogletCE.xml
Patches/RimWorld - Witcher Monster Hunt/Races_KikimoreCE.xml
Patches/RimWorld - Witcher Monster Hunt/Races_WyvernCE.xml
Patches/RimWorld - Witcher Monster Hunt/WH_ProjectileShoot.xml
Patches/Vanilla Animals Expanded/Caves_Animals.xml

- Misc. formatting and housekeeping to improve readability.
- Change Wyverns from QuadrupedLow to Birdlike bodyshape.
- Fix damage type for Acid Spit projectile.
Closes #1257 
Wyverns separate front legs, ambling around on two back legs and the "elbows" of their wings when on the ground, but are still generally laid-out similar to other dragons.
Could leave it all as-is, I suppose.

Magical Menagerie & Witcher Monster Hunter Patch Tweaks

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs

- Should fix NaN damage caused by partial penetrations not being accounted by the fractional damage changes;
- Makes fractional damage semi-randomly (influenced by the fraction of the damage) round to highest/lowest number at any damage value.
- Should close #1235;
- Closes #1231.
- Why was the fractional damage semi-randomly rounding to lowest/highest integer limited to under 1 damage, anyways?
- Code looks much simpler now.

Fixed fractional damage

---

Patches/Dubs Rimatomics/Apparel_Atomic.xml
Patches/Dubs Rimatomics/Atomics_Trader.xml
Patches/Dubs Rimatomics/Turrets_Rimatomics.xml

Patches apparel and traders of Rimatomics,
The turrets use special code to function which isn't supported by CE so, they behave like vanilla turrets but with tweaked damage values to mimic CE turrets.

RimAtomics Patch

---

Defs/Ammo/Pistols/45Colt.xml
Defs/Ammo/Pistols/9x18mmMakarov.xml
Defs/Ammo/Rifle/303British.xml
Defs/Ammo/Rifle/556x45mmNATO.xml
Defs/Ammo/Rifle/7.92x57mmMauser.xml
Defs/Ammo/Shotgun/410Bore.xml
Languages/English/Keyed/ModMenu.xml

- Makes .410 bore garbage as it should be from a short barrel of stuff like Taurus judge. 
- Fixes one setting
- .410 works like a shotgun in a pisol package in CE considering how next to no mods add .410 guns other than the Taurus Judge, while in real life it is just a bad pistol, working best with standard .45 Colt
Putting up with killing bears with a taurus judge

.410 realism and other projectile changes

---

Defs/ThingDefs_Misc/Apparel_Various.xml
Patches/Core/Storyteller/RaidStrategies.xml
Patches/Core/ThingDefs_Misc/Apparel_Various.xml
Patches/Core/ThingDefs_Races/Races_Animal_Arid.xml
Patches/Core/ThingDefs_Races/Races_Animal_Farm.xml
Patches/Vanilla Apparel Expanded - Accessories/Apparel_Utility.xml

- Patched the ranged shield belts from VAE-Accessories that were somehow left out in the process, based on the patched vanilla shield belts
- Rebalanced weight and worn bulk of flak pants, worn bulk of flak jackets and weight of composite and armor vests
- Adjusted the move speed of horses to make em more useful
- Removed the raid strategy tweaks made by CE, since 2 years ago there have been significant changes in raid strategy balance made in vanilla game which our patches screw with that.
- Balance reasons.
- None.

Apparel rebalanced and various tweaks

---

Patches/Archotech Expanded/AE_Hediffs_BodyParts_Prosthetics.xml
Patches/Archotech Expanded/AE_Items_Resource_Stuff.xml
Patches/Archotech+/ArchotechPlus_Hediffs_BodyParts_Archotech.xml

- Compatibility for Archotech+(Continued)
- Compatibility for Archotech Expanded
- Archotech Membrane from Archotech Expanded provides comparatively less armor than in vanilla, in order to not make pawns immortal.
- Archotech Obliterator and Deathclaw arms from Archotech expanded have relatively high armor penetration in order to be viable in combat and I feel like they should be, considering their tech level.
- Make the membrane as OP as vanilla.
- Make materials from Archotech Expanded unfit for making melee weapons and armor.

Compatibility for Archotech+(Continued) and Archotech Expanded

---

Defs/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml

- Fixed and gave melee tools to all grenade types to stop them from throwing red errors when used as a melee weapons in melee combat 
- Made Pyro Mech from VFE-Mechanoids use normal flamethrower projectile

Fix missing melee tools for grenades

---

Patches/Cursed Guns/CursedGuns.xml

- The weapons that have bipods in the texture now have a functioning bipod
- It is present in the sprite, so it probably should be present mechanically

Added bipods to Kniper and Scoped Pistol from Cursed Guns mod

---

Defs/Misc/TipSetDefs/Tips.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml

- Increased the inherent projectile spread of Warcasket and Pyro mechanoid flamethrowers
- Flamethrowers shoot a stream of fire currently which said stream can easily miss the intended target, increasing the spread of the fire that is shot enables flamethrowers to be more useful in area suppression and target immolation

Flamethrower spread broadening

---

Patches/Warhammer - Dryad/Race_Dryad.xml

- Add a gizmo comp patch that directly targets the dryad alien races.
- The alien races didn't previously have gizmos for weapon reload, fire and aim mode.
- Warhammer - Dryad Steam Workshop page: https://steamcommunity.com/sharedfiles/filedetails/?id=1694750191

Warhammer - Dryad patch fix

---

Patches/Heyra the Horned/Bodydef/Heyra_Bodytype.xml
Patches/Paniel the Automata/Ammo/Ammo_Paniel.xml
Patches/Paniel the Automata/Bodies/Paniel_Bodytype.xml
Patches/Paniel the Automata/HediffDef/Hediff.xml
Patches/Paniel the Automata/ThingDefs_Buildings/Buildings_Turrets.xml
Patches/Paniel the Automata/ThingDefs_Items/Items_Resources.xml
Patches/Paniel the Automata/ThingDefs_Misc/Paniel_Apparel.xml
Patches/Paniel the Automata/ThingDefs_Misc/Weapons.xml
Patches/Paniel the Automata/ThingDefs_Races/AlienRace_Paniel.xml

Stuff for Paniel the Automata.
Also a bodypatch for Heyra since I'm not sure whether it's needed any more, but the patch in the mod itself is missing bodydef stuff.
For simplicity's sake, the paniel advanced weapons still use charge ammo despite having kinetic rounds in vanilla. Armor is stuffable but metallic. Originally the paniel clothing is all metallic options, but will probably switch to steelable to reduce the number of insanely heavy caravans from CE's alteration of stuff weight of gold/silver etc.
Have considered either giving them very good ballistic weapon profiles instead, or making a custom ammodef but there's already quite a bit there for the shells, so it seems a little excessive, but I'm open to any suggestions.
Running out of ammo in the …

Paniel the Automata Patch

---

Patches/Censored Armory/Weapons_Turrets.xml

Changed ammo set name to projectile name in \<defaultProjectile\>.
Nothing new added
Replaced "AmmoSet_..." reference with "Bullet_..." reference in \<defaultProjectile\>.
No relevant open issues found
Wrong place for "AmmoSet_..". Also gives reference resolution error in log.
N/A

Fixed Censored Armory patch def reference typo

---

Defs/ThingDefs_Misc/Weapons_Grenades.xml
Defs/ThingDefs_Misc/Weapons_Ranged.xml
Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_RangedMechanoid.xml
Patches/Core/FactionDefs/Factions_Misc.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Artillery.xml

- Tweaked various flamethrower weapons' values
- Commented out raid point curves patch, it was messing with all the faction's raid curves be it mechanoid or modded factions
- Added "ai_AvoidFriendlyFireRadius" in a radius of 5 tiles to grenades that can cause friendly-fire and tweaked some of their minimum fire ranges to better suit their application
- Changes to the grenades and flamethrowers were made to hopefully fix the dumb AI behavior of suicidal grenadiers and friendly-fire caused by improper use of said weapons

Various flamethrower and grenades tweaks

---

Make.py

Apparently, nuget can host zip files whose contents are flagged unreadable, which prevents linking against them.
This marks all extracted files readable before trying to use the extracted files.
Needed for #1380 
Good idea to workaround the issue on our side as it may come up with future libraries too.  Sokyran has reported the issue to the Multiplayer devs, but this is more future proof, and cheap.
Insist all referenced zip files are sane.

Handle zipfiles from nuget with 777 umask

---

Source/CombatExtended/CombatExtended/AmmoInjector.cs
Source/CombatExtended/CombatExtended/BoundsInjector.cs
Source/CombatExtended/CombatExtended/CE_Utility.cs
Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs
Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/Compatibility/VanillaFurnitureExpandedShields.cs
Source/CombatExtended/Harmony/Harmony_GenRadial.cs
Source/CombatExtended/Harmony/Harmony_ThingDef.cs
Source/CombatExtended/Harmony/Harmony_TurretGunUtility.cs

- Wherever possible, use direct reference to fields
- If not possible, use `FieldRef`/`FieldRefAccess` from Harmony
- In one of the cases, used Harmony's functionality of accessing class fields in pre/postfixes
- Used `FastInvokeHandler`/`MethodInvoker` to replace `MethodInfo.Invoke()` call
- Direct access with publicized assemblies should be much faster
- `FieldRef`/`FieldRefAccess` is much faster than reflection
- `FastInvokeHandler`/`MethodInvoker` is slightly faster than using reflection
- Using slow reflection

Replace reflection with direct calls or Harmony

---

SupportedThirdPartyMods.md

- Add T's Samurai Faction to the list of Supported Third-Party Mods.
- Support for T's Samurai Faction was added in #1067.
- Unsure about Placement due to the `'` in the name. Could be placed at the start of Mods that start with a `T`.

Add T's Samurai Faction to SupportedThirdPartyMods

---

Defs/Ammo/Advanced/10x18mmCharged.xml
Defs/Ammo/Advanced/12GaugeCharged.xml
Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/12x72mmCharged.xml
Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml
Defs/Ammo/Advanced/5x35mmCharged.xml
Defs/Ammo/Advanced/6x18mmCharged.xml
Defs/Ammo/Advanced/6x22mmCharged.xml
Defs/Ammo/Advanced/6x24mmCharged.xml
Defs/Ammo/Advanced/8x35mmCharged.xml
Defs/Ammo/Advanced/8x50mmCharged.xml
Defs/Ammo/GENERIC/Charged.xml
Defs/Ammo/GENERIC/Generics_Misc.xml
Defs/Ammo/GENERIC/PistolMagnum.xml
Defs/Ammo/GENERIC/Rifle.xml
Defs/Ammo/GENERIC/RifleMagnum.xml
Defs/Ammo/HighCaliber/408CheyenneTactical.xml
Defs/Ammo/Pistols/10mmAuto.xml
Defs/Ammo/Pistols/357SIG.xml
Defs/Ammo/Pistols/45Colt.xml
Defs/Ammo/Pistols/46x30mm.xml
Defs/Ammo/Rifle/6.5x52mm Carcano.xml
Defs/Ammo/Rifle/77x58mmArisaka.xml

- Added generic charged ammosets to all current charge calibers
- Added the generic ammoset to the .45Colt + .410 bore ammoset
- New generic file to store all unique ammosets
- Added a generic ammoset to 4.6x30mm
- Changed 10mm Auto generic: PistolMagnum => Pistol
- Changed .45 Colt generic: Pistol => PistolMagnum
- Changed .357 SIG generic: PistolMagnum => Pistol
- Changed .408 Cheyenne generic: AntiMateriel => RifleMagnum
- Changed 6.5x55mm Carcano generic: RifleIntermediate => Rifle
- Changed 7.7x58mm Arisaka generic: RifleIntermediate => Rifle
- Fixed some typos in generic descriptions
- 10mm and .357SIG are too small for the Magnum category
- .45 Colt is too big for the Pistol category
- 6.5x55mm and 7.7x58mm are full power cartridges
- .408 is not quite Anti-Materiel

Generic ammo for Taurus Judge and general generics cleanup

---

Defs/Ammo/Advanced/12GaugeCharged.xml
Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml
Defs/Ammo/Advanced/5x35mmCharged.xml
Defs/Ammo/Advanced/6x22mmCharged.xml
Defs/Ammo/GENERIC/Charged.xml
Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Turrets.xml

- Added missing generic charged ammo recipes
- Fixed the Artillery Foundry from VFE-Mechs bug caused by removal of the tar shells from Alpha Biomes
- Fixed the crashed ship gauntlet turret and tesla turret warmup time from VE mechs and pirates mods
- **GOD DAMN IT SAM YOU'RE SUPPOSED TO TEST STUFF BEFORE APPROVING IT**
- PSA: load up the game with the changes in your PRs to make sure stuff's working as intended :D

Charged recipes and misc fixes

---

Patches/Orassans/ThingDefs_Weapons/Weapons.xml

- Increased magazine capacity of Orassan pistol from 10 to 20
As requested by @DianaWinters.
The Orassan pistol is chambered in a custom 6mm OE railgun cartridge, which is similar in size to the real-life FN 5.7×28mm cartridge used in the FN Five-seven pistol, which in turn typically uses 20-round magazines as standard.

Increase mag capacity of Orassan pistol

---

Patches/Cosplay Equipment - Blue Archive/Apparel.xml
Patches/Cosplay Equipment - Blue Archive/Weapons.xml

Request by Patosav#9192
- Outfits are given power armor stats and costs. Due to Blue Archive's story that the girls are absurdly durable to the point that an entire mag of an M4 is enough to knock them out for an hour.

Blue Archive Compatibility Patch

---

Patches/Starship Troopers Arachnids/Bodies_Bugs.xml
Patches/Starship Troopers Arachnids/Races.xml
Patches/Starship Troopers Arachnids/Resources.xml
Patches/Starship Troopers Arachnids/Weapons_Bugs.xml

Patch Request #1241 
- No recoil on Tanker bugs and Firefly to give them a more accurate flame stream
- Warrior caste are made to be fast, deadly in melee but easily taken down.
- Larger Arachnids are heavily armored and can resist small-arms fire.
- Arachnids are fully armored except for outside organs in their head (eyes, mouth,etc)
- The plasma projectiles casts shadows and sadly I don't know how to remove them. So some projectiles are really menacing like the Plasma Bugs'
- Change the flame thrower of the Tanker and Firefly to be flame damage instead of prometheum damage
- Change the Plasma Bug's weapon to follow more of the Plasma Grenadier's plasma instead of an arc like a mortar
- Remove the natural armor on the legs.
- Make the Large Arachnids (or at least the incendiary …

Starship Troopers Arachnids Patch

---

Patches/RimHammer40k -Dreadnought/Apparel_Dreadnought.xml
Patches/WarCasket Expanded/Apparel_Warcaskets.xml

- Compatibility for WarCasket Expanded and RimHammer40k -Dreadnought mods by AOBA
- The EMP ability of the Tyrant Warcasket helmet still reloads with components because it's not a gun, but rather a burst EMP device
- The armor values for WCE were calculated based on comments from the VFE Pirates patch and the relation between armor values
- Dreadnought has 75mm armor because that's what's stated in https://wh40k.lexicanum.com/wiki/Space_Marine_Dreadnought
- Dreadnought is considerably more bulky than other warcaskets because it looks that way
- Rework which warcaskets get nightvision
- Change things in regards to Tyrant's ammunition and projectiles

Compatibility for WarCasket Expanded and RimHammer40k -Dreadnought

---

Patches/Rimsenal Collection/Core/Weapons_GD_CE.xml
Patches/Rimsenal Collection/Core/Weapons_JI_CE.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Ammo_EnhancedVanilla.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_RSGuns_CE.xml
Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_RangedWeapons.xml

Added bipod tags where appropriate. Added stats for the vanilla enhanced thumper gun, uses 30x64 thermobaric and does half regular damage, but dealt as thump with 8 round mag.
For bipod tags
Added DMR tag to the GD and JI sniper rifles. Added LMG tag to the GD LMG. Added DMR tag to the AM rifle from vanilla enhanced. Added DMR tag to Feral AM rifle.

Rimsenal tag updates

---

Patches/Alpha Animals/PawnKindDefs_Mechanoids/AlphaAnimals_CE_Patch_PawnKind_Mechanoids.xml
Patches/Alpha Animals/VFE_Mechs/AdvGoliath.xml
Patches/Alpha Animals/VFE_Mechs/AdvSiegebreaker.xml
Patches/Alpha Animals/VFE_Mechs/VFEGoliath.xml
Patches/Alpha Animals/VFE_Mechs/VFESiegebreaker.xml
Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Junkers.xml
Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Mercenaries.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml

- Removed the patch that adds cover usage behavior to Lancers
- Tweaked the combatPower of Warcasket pawns from VFE-Pirates
- Tweaked the combatPower of certain mechanoid pawns from Alpha Animals
- Removed the VFEP_Captain weapon tag from the Charge Lance which made it usable by Pirate Captains
- Advanced mechs from VFE-Mechanoids have the cover usage behavior, adding a undocumented change to vanilla Lancers only causes confusions.
- Tweaked the combatPower of Warcasket pawns from VFE-Pirates to represent their strength a bit better
- No Human usable charge lances around here...
- Leave stuff as is

Pawns' combatPower rebalanced

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

But jokes aside, the Lancer cover change is not a good decision, Lancers are long range support mechs with very low stopping power and largely incredibly weak on their own. 
They are also lightly armored, are humanoid and have humanlike health scale, which doesn't allow for tanking shots like heavier mechs.
Removing the cover seeking behavior would also make static defenses the most effective strategy against them, which is exactly the strategy that mech raids discourage
And if you want to say that "it's an undocumented change", you do know that you can just document it, right?

Reverted the Lancer cover change

---

Ideology/Patches/AbilityDefs/Abilities.xml
Ideology/Patches/Misc/Hediffs_Casts.xml
Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Patches/Vanilla Factions Expanded - Ancients/PawnKinds_Spacer.xml
Patches/Vanilla Factions Expanded - Pirates/AbilityDefs/Abilities.xml
Patches/Vanilla Factions Expanded - Pirates/Misc/Hediffs_Casts.xml
Patches/Vanilla Factions Expanded - Pirates/Misc/Precepts_Role.xml
Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Mercenaries.xml

- Added and tweaked skill range values for vanilla and modded pawnKinds
- Fixed the Pirate Captain role bonuses from VFE-Pirates
- Some housekeeping for the combat oriented ideology abilities
- Vanilla mercenary gunners and snipers had a shooting skill range of 4~20. Imperial pawns had various combat skill ranges as well which sparked the thought of tweaking and adding the melee and shooting skill range to certain high tier faction pawns to make them more reliable in their combat role.

pawnKind combat skill range tweaks

---

Patches/More Utility Packs/Apparel_Mechanoids.xml
Patches/More Utility Packs/Apparel_Packs.xml
Patches/More Utility Packs/Apparel_Royalty.xml

- Gave the CompQuality to the utility items from the More Utility Packs mod
- The utility items added by the More Utility Packs have a ParentName which causes them to not have quality. Since in CE, those items add bulk and weight capacity and occupy the backpack layer and forbid wearing backpacks simultaneously with them, them not having quality means that the capacity increases don't scale.
- Items not having quality breaks the apparel restrictions. If you limit the quality of allowed apparel in any way, pawns stop auto-equipping the utility packs added by the mod and should be forced to equip them.
- Leave them be as broken as they are

More Utility Packs qualitified

---

Patches/Rabbie The Moonrabbit/ThingDefs_Races/AlienRace_Rabbielike.xml

Add comps, remove redundant Inventory (Rabbie inherits from BasePawn)

Fix Rabbie race patch failing

---

Patches/Revia Race/ThingDefs_Races/Race_Revia.xml

Revia apparently doesn't need suppression and gizmo as they inherit it from somewhere. Adding gizmo the second time causes part selection to be toggled twice per click.

Fix Revia called shot gizmo

---

Defs/BipodCategoryDefs/BipodCategories.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_BullpupAR.xml
Patches/Vanilla Weapons Expanded - Quickdraw/Weapons_Quickdraw.xml

- Added a bipod tag to be used for appropriate assault and battle rifles with integrated bipods.
- Certain rifles like the Galil and Famas have integrated bipods which don't fit in any of the existing bipod tag categories so, added a new rifle bipod tag to accommodate for that.

Rifle bipod tag

---

Patches/Vanilla Weapons Expanded - Laser/RangedSpacer.xml
Patches/Vanilla Weapons Expanded - Quickdraw/Weapons_Quickdraw.xml
Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml
Patches/Vanilla Weapons Expanded/Spacer_Ranged.xml

- Added bipods to base VWE, lasers and the quickdraw modules
- Tweaked the stats on the charge sniper to balance out the change to triplet shot (could arguably be changed even further)
- Sway increased to simulate the shifted balance of having triple the barrel to deal with
- Compared to 8x50, triple 8x35 has significantly higher stopping power, and so the weapon stats should reflect that
- Charge LMG was given a SAW bipod as it uses 6x24
- Only the snipers from the modules got bipods, as both lack a proper LMG/SAW
- Leave them naked and bipodless =)

Tweak VWE patch

---

Source/CombatExtended/CombatExtended.csproj

- What it says on the tin
- The dependency package versions were outdated and VS forced an update on manual build each time a new unbuilt CE dev snapshot was downloaded for build

Update Dependency Package versions

---

Defs/Ammo/Shell/105mmHowitzer.xml
Defs/Ammo/Shell/155mmHowitzer.xml
Patches/Fortifications - Industrial/FT_Artillery.xml

- Added Direct-fire AmmoSet for 155mm
- Compatibility for 155mm Howitzer and Field cannon
- None
- Contributes towards #1324 
- 155mm Howitzer stats are based on VFE:S Heavy artillery but with a bit faster reload (12s vs 10s)
- 155mm Field cannon stats are similar to the 90mm Flak, with tweaks to make it similar to the 155mm Howitzer

Fortifications industrial update

---

Patches/Vanilla Storytellers Expanded - Winston Waves/Modifiers/Modifiers.xml

- Fixed Winston Waves' "Charge weapons for everyone!" raid modifier that forced pawns to spawn with charge lances and replaced the lances with CE guns' charge weapons

Fix Winston Waves' raid modifier

---

Patches/Core/TraitDefs/Traits_Spectrum.xml

- Replaced the Careful shooter trait weapon handling stat modifier from 1.5 to 1.33 and the Trigger-happy trait from 0.5 to 0.75
- Gave the careful shooter trait a 1.25 aiming accuracy bonus and lowered the trigger-happy trait's aim time bonus from -0.5 to -0.75
- https://discord.com/channels/278818534069501953/322827713335394304/954837956793876621
- Balance reasons considering the called shots system and the reference above

Shooting trait modifier tweaks

---

Patches/Fantasy Metals Reforged/Fantasy Metals Reforged.xml
Patches/Vanilla Furniture Expanded - Security/Ammo_Security.xml

Had to return the missing projectile and ammo set due to the file's deletion #1398 
- Returned the EMP Cannon Projectile
- Returned the Raider Heavy Artillery AmmoSet
- Orichalcum already has 1.1 MeleeWeapon_CooldownMultiplier and is causing duplicate XML node errors, removed

Minor Fixes

---

Patches/Revia Race/ThingDefs_Misc/Weapons_Guns.xml

I am not sure how to balance this one. I used upscaled Harvester stats as it's also a scythe of sorts and added Royalty's Warhammer stats for blunt attack and upscaled it too. Offsets are also from Harvester and -8 MeleeHitChance offset is preserved from vanilla variant of Shatterer. 
In other words, it works for me but can probably use some balancing work.

Add Shatterer weapon

---

Defs/ThingDefs_Misc/Apparel_Headgear.xml

Someone on discord raised a valid point - why can you use uranium (and silver and gold and modded Metallic stuff like Rimefeller's composite) for plate armour and not for bascinet?
1. Leave it as is
2. Or add Woody category too - haven't seen any historical bascinet-like helmets made out of wood but I also don't know why rimworlders wouldn't try it anyway. 

Change bascinet stuff category from Steeled to Metallic

---

Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Junkers.xml
Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Mercenaries.xml

- Reverted and readjusted combat power of warcasket pawns according to the recent update to the original mod

VFE-Pirates CP retweaks

---

Defs/Ammo/Shell/105mmHowitzer.xml
Defs/Ammo/Shell/155mmHowitzer.xml

- Fixed the texPath for the 105mm and 155mm smoke howitzer shells

Smoke howitzer shell texture fix

---

Defs/Ammo/Medieval/CannonBall.xml
Defs/Ammo/Medieval/Catapult.xml
Defs/Ammo/Medieval/MortarGrenade.xml

- Added proper medieval tech level nodes to certain medieval ammo types missing them causing issues with tech removing mods.
- Fixes https://discord.com/channels/278818534069501953/324222101550661663/959848538328694785

Medieval ammo tech level fix

---

Defs/ResearchProjectDefs/ResearchProjects_Tier4_Misc.xml

- Changed the Advanced Ammo research from spacer to industrial tech level and compensated the change with a research point increase
- Prerequisite for the research is Precision Rifling which is industrial and the Advanced Ammo research is not gated behind multianalyzer, so there is no reason for it being spacer level. The spacer tech level even causes problems with tech block mods which limit access to an actually industrial research because of the tag.
- Increased the research point cost to reflect the difficulty of the research a bit more and prevent easy tech rushing with mods like Tech Advancing.

Advanced Ammo tech level tweak

---

Patches/RimCities/Scenarios/Scenarios.xml

- Patched the starting scenarios of the Rimcities mod in accordance to the vanilla Crashlanded scenario

Rimcities patch

---

Defs/ThingDefs_Misc/Apparel_Shield.xml

Gate ballistic shield behind Machining. Consistent with how CE Shields handles industrial shields. Also prevents tribals from having it if they have a smithy. It feels very imbalanced to have an 8 RHA steel ballistic shield available when most comparable armour at that level is at ~2mm (Melee Shield is 2.5mm).
Melee shield is no longer made at a crafting spot, so it should be unlocked with Smithing, like medieval CE Shields do

Shield tweaks

---

Patches/Vanilla Storytellers Expanded - Winston Waves/Rewards/Rewards.xml

- Added FSX and Prometheum to Winston Waves' resource drop reward pool
- With how Winston works, acquiring FSX and Prometheum is quite difficult and since he rewards the player with resources, then why not FSX and Prometheum?

Winston Waves rewards expanded

---

Source/CombatExtended/CombatExtended/SecondaryDamage.cs

- Decreased the HE round bomb secondary damage blunt armor factor
- The secondary bomb damage of HE rounds was overperforming against armored enemies, made the change to tame it a bit.

HE round bomb damage tweaks

---

Patches/Core/ThingDefs_Misc/Apparel_Various.xml

- Added feet coverage to flak pants with an appropriate partial armor stat to simulate boots included with the pants.
- This change was made to bring the flak pants in line with apparel from CE Armors that have feet coverage/shoes or boots.

Flak pants feet coverage

---

About/About.xml
Patches/CuprosAlloys/ThingDefs/Patch_Materials_Alloy_Utility.xml
Patches/Expanded Materials - Metals/Items_Resource_Stuff.xml
Patches/Vanilla Factions Expanded - Classical/Ammo_Javelin.xml
Patches/Vanilla Factions Expanded - Classical/Ammo_Scorpion.xml
Patches/Vanilla Factions Expanded - Classical/Apparel_Classical.xml
Patches/Vanilla Factions Expanded - Classical/Apparel_Headgear.xml
Patches/Vanilla Factions Expanded - Classical/Items_Resource_Stuff.xml
Patches/Vanilla Factions Expanded - Classical/PawnKinds_Misc.xml
Patches/Vanilla Factions Expanded - Classical/ThingDefs_Manned.xml
Patches/Vanilla Factions Expanded - Classical/ThingDefs_Shields.xml
Patches/Vanilla Factions Expanded - Classical/ThingDefs_WeaponsMelee.xml
Patches/Vanilla Factions Expanded - Classical/ThingDefs_WeaponsRanged.xml
Patches/Vanilla Factions Expanded - Vikings/Weapons_Medieval.xml
SupportedThirdPartyMods.md

- Add a patch for Vanilla Factions Expanded - Classical.
- The Legionnaire and Centurion armor thickness is somewhat less than plate armor, since the latter is later, more advanced medieval armor, but has less bulk and doesn't have the melee aiming penalties, since the helmets are open-faced. Even so, made of steel (I'm frankly not sure why they can be made of wood, but that's vanilla for you...), they provide satisfactory protection from typical sharp melee attacks.
- The Javelins are largely the same as the Pilum, but costs a bit more steel (for a longer shaft), and uses VFE's custom "apparel damage" type as an extra damage. They can also be fired from the VFE: Ballista.
- The Scorpion, while not impossibly heavy, was still too large to practically be used from the hip. In the patch, it …

Patch Vanilla Factions Expanded - Classical

---

Patches/Opossum Friends/OpossumFriend.xml
SupportedThirdPartyMods.md

- Patches the 'Opossum Friends' mod. Opossums have stats identical to raccoons, minus the claw attacks.

Patch Opossum Friends Mod

---

Patches/Core/Drugs/Drugs.xml

- In an attempt to continue with removing old and outdated patches, removed the depreciated patches for Go-Juice.
- https://discord.com/channels/278818534069501953/322827713335394304/961502167129288724
- Vanilla game handles hard drugs like go-juice and wake-up differently since not too long ago, so no tolerance gain, only overdoses and addictions based on a chance. Also severity lose per day for go-juice is at -0.75 for go juice which make the patch pointless as the change is negligible, less patches, better load time.
- Leave the patches be.

Remove Go-Juice patches

---

Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Goliath.xml
Patches/Alpha Animals/VFE_Mechs/AdvGoliath.xml
Patches/Alpha Animals/VFE_Mechs/VFEGoliath.xml

- Removed the MechanoidGunLongRange weapon tag from the Goliath mech variants
- Since the needle gun is changed in CE from its original counterpart and is no longer a long range sniper type weapon, the goliath mechs would be put in a disadvantageous position if they still spawned with explosive bolt projectors. The mech itself is stronger than pikemen which is a good idea but the weapon in their hand is weak in comparison which makes the mech a weak target. It was discussed in the original patch PR for them to not have the weapon tag, so the change was made to make them not spawn with said weapon. 
- Based on the comment here: https://github.com/CombatExtended-Continued/CombatExtended/pull/673#pullrequestreview-676471315

Goliath mech weapon tags tweaks

---

Defs/Ammo/Grenade/35x32mmSRGrenade.xml

- Added HEDP variant for 35x32mmSR Grenades 
- Damage and cost based off of 40mm HEDP variants
- Penetration based off of: https://weaponsystems.net/system/1311-BB01%20-%2035x32mm%20Type%2087
- Building on repository
- Using mods that could function with it (totally not PLA Steel Torrent with GL trucks)
- It actually exists and has a real life counterpart

35x32mmSR HEDP

---

Patches/Vanilla Chemfuel Expanded/Items_Chemfuel.xml
SupportedThirdPartyMods.md

- A very simple patch that gives 'deep chemfuel' a bulk of 0.05 per unit (like regular chemfuel) instead of 1.

Patch Vanilla Chemfuel Expanded Bulk

---

Patches/A Rimworld of Magic/Patch_Ranged.xml
Patches/Anty the war Ant/ThingDefs_Misc/Weapons.xml
Patches/Arrow Please/ArrowPlease_Ranged.xml
Patches/Core/ThingDefs_Misc/Weapons_RangedNeolithic.xml
Patches/Forsakens/Forsakens_CE_Patch_ThingDefs_Weapons.xml
Patches/JDS Castle Walls/ThingDefs_Tower.xml
Patches/Medieval Overhaul/MO_Weapons_Ranged.xml
Patches/MorrowRim - Bloodmoon/Hunter_Weapons.xml
Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_RangedWeapons.xml
Patches/Nyaron/ThingDefs_Misc/Weapons.xml
Patches/O21 Outland - Eastborn/Eastborn_WeaponsRanged.xml
Patches/Revia Race/ThingDefs_Misc/Weapons_Guns.xml
Patches/Rimcraft Collection/Weapons/Patch_WOW_Ranged.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_Ranged_Misc.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_Ranged_CE.xml
Patches/T's Samurai Faction/T_Samurai_Weapons_Ranged.xml
Patches/Tribal Warrior Set/TribalWarrior_Apparel.xml
Patches/VFWE/ThingDefs_Misc/Weapons_RangedNeolithic.xml
Patches/Vanilla Factions Expanded - Vikings/Weapons_Crypto.xml
Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml
Patches/Vanilla Weapons Expanded/Medieval_Ranged.xml
Patches/Vanilla Weapons Expanded/Neolithic_Ranged.xml

- Decrease CE's cost reduction of vanilla bows (from almost 70% to around 40 - 50%).
- Decrease the overall range of many bows.
The current range of bows is, in many cases, more reflective of their _absolute_ maximum range rather than their realistic maximum _effective_ range. Given the low velocity of the arrows they fire, this leads to an issue where they consistently engage well beyond their actual effective range, making them less effective in combat due to long flight times. I recommend the new range brackets be as follows:
Short bow (and other crude, simple bows): 14 tiles = 60 m.
Recurve bow, crossbows (and other more 'advanced' medieval bows): ~20 tiles = ~100 m.
Great bow (and other long bows): 30 tiles = 190 m.
Figure a range of +/- 10% or so on the ranges for a bit of variance …

Tweaks to Bow Ranges

---

Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml

- Removed the problematic grenade from VFE-Pirates that was throwing a red error at startup
- Tweaked the gravity factor patch, vanilla grenades are already set to 12 speed

Problematic VFE-Pirates grenade removal

---

Defs/Ammo/Shell/81mmMortar.xml

- Fixed the thingSetMakerTag of the Antigrain shell which was set to an outdated and obsolete tag and set it to the original vanilla tag.

Antigrain shell thingSetMakerTag fix

---

Patches/FFGermanSheperd/Races_Animal_FFGermanShepherd.xml

- What it says on the tin, fixed a typo that caused the patch to fail.

FFGermanShepherd patch typo fix

---

Defs/Ammo/Medieval/CrossbowBolts.xml
Defs/Ammo/Neolithic/Arrows.xml
Defs/Ammo/Neolithic/BlowDarts.xml
Defs/Ammo/Neolithic/GreatArrows.xml
Defs/Ammo/Neolithic/SlingBullet.xml

- Made projectile speed of Arrows and Bolts consistent with IRL data and other low velocity projectiles in the mod while fixing some overtuning done to crude projectile speeds
- Contributes towards https://discord.com/channels/278818534069501953/322827713335394304/963592426721771560

Crude projectile speed check

---

Defs/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Censored Armory/Weapons_Guns.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Kaiser Armory/KaiserArmory_Guns.xml
Patches/Kijin 2.0/Ammo/Ammo_Kijin_Misc.xml
Patches/LTS Military/Weapons.xml
Patches/Morgante Mafia Weapons Pack/Weapons_Guns.xml
Patches/O21 Outer Rim/Patch_OuterRim_Weapons.xml
Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Grenades.xml
Patches/Red Army/RedArmy_Weapons.xml
Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_Grenades.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_Grenades.xml
Patches/Rimsenal Collection/Core/Weapons_Explosives.xml
Patches/Rimsenal Collection/Marauder/Marauder_Grenades.xml
Patches/Save Our Ship 2/Weapons_Grenades.xml
Patches/Tsar Armory/TsarArmory_Guns.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
Patches/Vanilla Factions Expanded - Vikings/Apparel_Misc.xml
Patches/Vanilla Weapons Expanded - Tribal/Ranged_Neolithic.xml

- Reverted the gravity factor patch for base grenade projectile that was being very problematic with vanilla "grenade" projectiles that are unpatched for CE
- Added the factor to vanilla and CE thrown grenades only.

Gravity factor patch revert

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Vanilla Factions Expanded - Insectoids/ThingDefs_Misc/Weapons_Spacer.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml
Patches/Vanilla Weapons Expanded - Heavy Weapons/RangedIndustrialHeavy.xml
Patches/Vanilla Weapons Expanded - Laser/RangedSpacer.xml
Patches/Vanilla Weapons Expanded/Spacer_Ranged.xml
Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml

- Added NV capability to mech cluster turrets and other advanced buildable turrets
- It doesn't make sense for mechanoids themselves to have NV but their turrets not having the capability, added an appropriate amount to them to stay consistent to that reasoning
- Added NV to certain buildable turrets to recreate them having advanced scopes.

Add night vision to advanced turrets and guns

---

Patches/British Weapons Set/British_weapon_set.xml
Patches/Remote Detonator/Remote_Detonator_CEpatch.xml
SupportedThirdPartyMods.md

Compatibility for British Weapon  Set and Remote Detonator
I Wanted more weapons using British 303 rounds and this mod seemed good for it, but it had no compatibility patch soo i made it. And after realizing i have that power now, i decided to make and add a patch for Remote detonator by tikubonn

Add British Weapon Set and Remote Detonator Compatibility

---

Patches/Advanced Mechanoid Warfare/Patches/Patch_Melee.xml
Patches/Advanced Mechanoid Warfare/Patches/Patch_Races.xml
Patches/Advanced Mechanoid Warfare/Patches/Patch_Ranged.xml
Patches/Advanced Mechanoid Warfare/Patches/Patch_Turret.xml
Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Demolisher.xml
Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Phalanx.xml
Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Siegebreaker.xml
Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Slurrypede.xml
Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_WaywardAssembler.xml
Patches/Alpha Animals/VFE_Mechs/AdvPhalanx.xml
Patches/Alpha Animals/VFE_Mechs/AdvSiegebreaker.xml
Patches/Alpha Animals/VFE_Mechs/VFEPhalanx.xml
Patches/Alpha Animals/VFE_Mechs/VFESiegebreaker.xml
Patches/Alpha Animals/VFE_Mechs/VFESlurrymaster.xml
Patches/MechanoidsExtraordinaire/PawnKindDefs/PawnKinds_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml
Patches/MoreMechanoids/PawnKinds/PawnKinds.xml
Patches/MoreMechanoids/ThingDefs_Misc/Weapons_Mechanoid.xml
Patches/MoreMechanoids/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Ancients/ThingDefs_Sentry.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- Tweaked the PD turret added by VFE-Ancients to have a larger burst shot count and ammo capacity
- Tweaked the military turrets from VFE-Security to have appropriate burst shot counts
- Readjusted certain values in some old mechanoid mods' patches to bring them up to par to some newly patched mechs and fix some OP or wonkiness issues. 
- The Ancient PD turret is a 2x2 building with twin miniguns mounted on top, considering that the VFE-Security sentry gun is a 1x1 building with only one mounted minigun and shoots 50 rounds in each burst with a 500 round capacity, it was only appropriate to tweak the PD turret to resemble its design. Also the vanilla minigun has a 50/100 burst shot count.
- The military turrets have two mini-turrets mounted on top so made the change to differentiate them …

Modded turret patch tweaks and modded mech armor adjustments

---

BuildCompat.py

Automates building compat libraries
- When new compat libraries are added, they'll be listed in the CombatExtended.sln, 
- We don't want to have to manually keep the CI and the .sln in sync
- Statically set the list, either in the workflow or in another file.

Add BuildCompat.py to automate building compat libraries from .sln

---

Patches/Rimsenal Collection/Core/Apparel_RS_CE.xml
Patches/Rimsenal Collection/Federation/ThingDefs_Misc/Fed_Apparel.xml
Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_Apparel.xml

- Readjusted certain Rimsenal collection armor pieces' partial armor value
- Certain base armor values were changed without consideration for the partial armor system being optional and toggleable, readjusted the partial armor values and reverted some base armor values to adjust for that

Readjust Rimsenal's partial armor

---

Patches/Alpha Animals/ThingDefs_Misc/AA_Resource_CEStuff.xml
Patches/Alpha Biomes/Items_Resource_Stuff.xml
Patches/Rimefeller/Items_Resource_Stuff.xml

- Added toughnessMultiplier to modded woody materials in preparation for the Toughness stat PR to replicate the same toughness as wood to some extent.

Add toughnessMultiplier to modded woody materials

---

Patches/Fort's Firefighter Gadget/Apparel_Industrial.xml
Patches/Fort's Firefighter Gadget/Industrial_Melee.xml
SupportedThirdPartyMods.md

Patches apparel and melee "weapons" from Fort's Firefighter gadget mod.
**Apparel:**
A helmet and bunker jacket (with identical copies in different colors) are based on the actual material thickness (which aren't tremendous) of the real-world equivalents (though real helmets aren't made of metal) plus some additional blunt protection for additional padding both incorporate to protect the wearer from falling debris. Their actual sharp/blunt protective value is unimpressive; the heat protection is the key. I got the thickness info from manufacturers online.
The helmets incorporate a SCBA mask and so protect from smoke. After some consideration, I opted not to have them give the gasmask hediff (and their associated debuffs) since, in real life, these SCBAs have broad visors and supply air, …

Patch Fort's Firefighter gadget 

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Source/CombatExtended/Compatibility/WeaponToughnessAutoPatcher.cs

- Reintroduced the flat multiplier to parry damage;
- Autopatcher calculates bigger base weapon thickness.
- Melee damage variation exists, so a flat value is I believe better. The value is higher to compensate for weapon toughness;
- Aids in reducing chip damage;
- All in all, it should better reward larger penetrating attacks than chip damage.
- Keeping the current random values:
- Attacks that have more AP than the weapon has toughness rarely deal more damage;
- Melee damage (both armed and unarmed) is already varied based on the attacker's skill.
- Remove the parry damage multiplier:
- Weapons and shields are quite fragile;
- There was a flat multiplier of 0.1 before the toughness changes.
- Keeping the current way of getting the base weapon thickness:
- Extremely likely chip damage; …

Reintroduced flat parry damage multiplier, edited toughness autopatcher results

---

Patches/Vanilla Animals Expanded/Caves_Animals.xml
Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
Source/CombatExtended/Harmony/Harmony_Verb.cs

Resolve various exceptions that plagued melee combat:
* Make Verb_MeleeAttackCE check that the defender and attacker are
still spawned; a successful riposte may kill the attacker, and
certain melee attacks such as cocoon bites from VAE: Caves' giant
spiders may despawn the defender.
* Make the vanilla Verb class correctly handle the situation where
the attacker missed their melee attack and was killed in the process
(i.e. got riposted and killed). The vanilla logic was already checking
the state of the attacker in the case their attack connected, but not
when it missed.
* Remove mandibles from VAE: Caves' giant spiders - they no longer have them,
only the ancient giant spider does. This was causing errors every time
the giant spider attempted to use them for an attack.
* Tweak error …

Fix observed errors during melee combat

---

Defs/ThingDefs_Misc/Weapons_Ranged.xml
Patches/LF Red Dawn/RD_Launchers.xml
Patches/LF Red Dawn/RPG123456789_Projectiles.xml
Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_GER.xml
Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_UK.xml
Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_US.xml
Patches/Red Horse Faction Allegiance/RH_Allegiance_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Coalition/RH_Coalition_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Militaires Sans Frontieres/RH_MSF_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction Umbra Company/RH_Umbra_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Red Horse Faction War Mongrels/RH_WarMongrels_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Rimfire/ThingDefs_Misc/RF_Ranged_Modern.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_BigGuns.xml
Patches/Soviet Armory/SovietArmory_CE_Patch_Weapons.xml

- Rebalanced the M72 LAWs crafting cost and market value
- M72 LAWs are currently dirt cheap to buy and craft for 5 whole weapons which is kinda against the output given by the spreadsheet. The Crafting Mats. tab in the spreadsheet seem to state the materials needed for only 1 LAW which is still higher than the in-game costs. If we scale the costs to 5 crafted weapons, it'd result the current values in this PR. The result makes much more sense for a recipe that outputs 5 M72 LAWs. The current market value is very low at 35.72 and the material costs are 26 steel and 2 components which is also unreasonable for 5 rocket launchers.
- Before scaling the values
- After scaling the values

M72 LAW Rebalanced and RPG consistency check

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml

- Buffed the Flak Cannon slightly by lowering the warmup and cooldown time.
- Given that flak cannons shoot very slowly, 9.8+4.55+2.71 seconds between each shot which makes them a bit less viable as a useful tool. Since the reload and cooldown times are set by the gun spreadsheet at 9.8 and 2.5 seconds respectively, I opted for decreasing the cooldown time down to 2.5 seconds and lowered the warmup time from 4.55s to 3.5s because it's not limited by the spreadsheet just to make the cannon more viable.

Flak Cannon buffed

---

Source/CombatExtended/Harmony/Harmony_VerbProperties.cs

123cc55e898a17c3baedb56868586c3f9eb8fe3f added caching to our Harmony
patch that uses reflection to determine whether a given verb is melee
or not, but the cache only varied on the type of the VerbProperties class,
which is always VerbPropertiesCE. This could result in e.g. melee verbs
getting classified as ranged ones. Let's fix it by varying the cache
per property instance.

Make VerbProperties.LaunchesProjectile cache vary per property

---

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets.xml

- Patched the Warcasket armors' steel and component cost to be 2x of the vanilla value
- Warcaskets same as vanilla Power Armors are cheap and their material costs have remained untouched making them too accessible and powerful for the cost. The PR aims to balance things out by doubling their steel and component cost to bring them more in line with how Power Armors are patched to be more expensive while not introduce other materials into their recipe because Spacer Warcaskets are coming in the near future which require steel instead of plasteel to craft.
- Also on another note since Warcasket armor pieces lack market value, the material increase will not affect how the armor pieces are spawned on pawns so there will be no need for further PawnKind Apparel budget patching. In-game testing …

Warcasket material costs adjustments

---

Defs/ThingDefs_Misc/Weapons_Ranged.xml
Patches/LF Red Dawn/RPG123456789_Projectiles.xml

- Added a 1x crafting recipe for the M72 LAW
- Following the much needed change to LAWs, the crafting work cost for 5x LAWs got a bit too high in comparison to 6200 work (which was still too low and incorrect) which was the previous cost. Added the 1x recipe (with appropriate costs to keep the incentive for batch crafting) with the goal of giving the player a quicker access to the rocket launcher in an emergency situation.
- Go against the spreadsheet and decrease the work cost for crafting 5 LAWs

1x Recipe for M72 LAW

---

Patches/Medieval Overhaul/MO_Apparel_Helmets.xml
Patches/Medieval Overhaul/MO_Apparel_Various.xml

MO_Apparel_Helmets.xml and MO_Apparel_Various.xml had a lot of unused Defs, which led to failed Patch Operations.
Removed extra Defs and added new ones, while also adjusting Armour Values to adhere to the Vanilla Plate Armour's Values.
Also one thing that caused issues, was that Gambesons and Sur Coats had cost changes, which somehow broke the patch. These were removed
- Removed old/unused Defs
- Added new Defs that weren't present (all Apparel Defs as of 03.05.2022 are present)
- Removed cost change for Gambesons and Sur Coats
- Removed renaming of sur coats to arming doublets.
- Adjusted Plate Armours' values to be closer to the Vanilla Plate Armour's values.
- Fixed Patch Operation Failures
- New Apparel is now patched
- Cost change and renaming of gambesons/sur coats was unnecessary …

Fixed Medieval Overhaul Patches

---

Patches/Starship Troopers Arachnids/Races.xml
Patches/Starship Troopers Arachnids/Resources.xml
Patches/Starship Troopers Arachnids/Weapons_Bugs.xml

- Updated the Starship Troopers Arachnids' patch with appropriate values
- Some of the bugs needed an armor value adjustments to make them consistent with other insectoids in vanilla and mods. Some of them are supposed to be unarmored which the change reflects that to some extent as best as possible.
- The flamethrower weapons that the bugs use got the same treatment as other flamethrower weapons in regards to spread.
- The leathery and metallic materials added by the mod needed a proper value adjustment to make them consistent with other built-in patches while making the Arachnid Carapace a bit less OP since is abundantly available.

Starship Troopers Arachnids' patch updated

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml

If the player is not using the 'classic mortars' difficulty option, the steel cost of the Flak Gun is reduced by 150, but it now requires a reinforced barrel to construct.
Same as #1551, but with correct formatting.

Add reinforced barrel to Flak gun.

---

Ideology/Patches/Misc/Hediffs_Casts.xml
Ideology/Patches/Misc/Precepts_Role.xml
Patches/Core/InspirationDefs/Inspirations.xml
Royalty/Patches/ThingDefs_Misc/Apparel_RoyaltyHeadgear.xml

- Patched the shooting inspiration to give +2 shooting accuracy instead of +8 (the vanilla value) and +0.2 aiming accuracy
- Adjusted the Gunlink's bonus from +3 shooting accuracy to +1.5 shooting accuracy and +0.6 aiming accuracy
- Readjusted the Ideology combat related precepts and abilities with the same logic as the Gunlink and combat inspirations.
- The shooting inspiration being a flat bonus gives a 0 shooting skill pawn with 100% weapon handling, 368.8 weapon handling. this bonus enables the pawn not only to shoot very well but enables ranged targeting for the duration of the inspiration which is 8 days. Gunlinks give a +3 accuracy bonus, a +2 bonus for the inspiration should be enough. It's not like one day the pawn wakes up and goes, "i can shoot a fly on the moon today"...
- …

Adjust shooting inspiration and Gunlink's bonus

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_ArmorCoverage.cs

- Explosions and explosive projectiles use a different formula for giving suppression; they also ignore sharp armor;
- Explosions deal more suppression than the explosive projectile itself.
- Explosion suppression was broken due to the fact that it always checked against average sharp armor with its sharp penetration, which is 0. This should fix the issue of explosives not doing enough suppression, while raising the T in the lerp to the power of two should help reduce suppression the further a pawn is from the projectile or explosion;
- Projectiles can suppress the same pawn multiple times if it is in the suppression radius of the projectile for multiple ticks, therefore to me it didn't make sense how explosive projectiles can suppress more than the explosion itself.
- Did battlefield …

Added different suppression calculation for explosives and explosions

---

Defs/Ammo/Neolithic/Javelins.xml

- Changed the `unfinishedThingDef` of javelins from `UnfinishedWeapon` to `UnfinishedAmmo` to fix the stuffed unfinished item.
- Closes #1456 

Fix for #1456

---

Source/BetterTurretsCompat/BetterTurretsCompat/BetterTurrets_CE_TurretWeaponBase.cs
Source/MiscTurretsCompat/MiscTurretsCompat/MiscTurrets_CE_TurretWeaponBase.cs

When asking for the ammo of a Turret Base with a `null`, clear the cached ammo.
Invalidate the cache when spawning the turret - does the turret spawn get called when the turret is converted from minimized to installed?  
Invalidate the cache when uninstalling the gun - Requires a harmony patch as the un/install gun methods are not virtual.

clear cached CompAmmoUser _ammo when gun is null

---

Defs/Stats/Stats_Pawns_Combat.xml
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs

- Landing a critical hit forces the damage variation to return the max damage. Does not affect ripostes.
- A critical is a critical - a debilitating, often fatal blow. It would not make sense for the damage to be anything but the max possible on such a hit.

Force max damage on a critical hit

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs
Source/CombatExtended/CombatExtended/Jobs/JobGiver_DefenderReloadTurret.cs
Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs

* Make the reload jobgiver check first if a given turret's magazine fullness
is below the threshold of 50% before additional checks. This avoids triggering
a potentially expensive search for ammo for the case where the turret doesn't
even need reloading.
* Introduce a maximum search radius for ammo for non-player pawns. This avoids
a situation where sieging raiders or mech cluster defenders run halfway across
the map to reload using dropped ammunition - they should now prefer ammunition
supplied to them via siege drop pods or mech ammo beacons and not venture far
from their designated area.
* Fix mech ammo beacons, as they seem to have been accidentally broken by a change
back in 2020 - the check on whether a turret needed reloading had inverted polarity.
As part of this, I also cleaned …

Improve turret reloading behavior for non-player pawns

---

Patches/Combat Enthusiast's Collection/ThingDefs_Weapons.xml
Patches/High Caliber/HighCaliber_CE_Patch_Weapons.xml
Patches/Midworld Weaponry Expanded/Industrial_Ranged.xml
Patches/Rambo Weapons Pack/RamboWeaponsPack_assaultrifles.xml
Patches/Red Horse Faction Cordis Die/RH_CordisDie_CE_Patch_RangedIndustrial_SMG.xml
Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_RangedIndustrial_SMG.xml
Patches/Red Horse Faction Task Force 141/RH_TF141_CE_Patch_RangedIndustrial_HRT_Pack.xml
Patches/Red Horse Faction The Ghosts/RH_Ghosts_CE_Patch_RangedIndustrial_SMG.xml
Patches/Red Horse Faction War Mongrels/RH_WarMongrels_CE_Patch_RangedIndustrial_SMG.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_HRT_Pack.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_R_Others.xml
Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_SMG.xml
Patches/Rimsenal Collection/Marauder/Marauder_Guns.xml
Patches/Soviet Armory/SovietArmory_CE_Patch_Weapons.xml
Patches/Vanilla Weapons Expanded - Quickdraw/Weapons_Quickdraw.xml

- Changed the patched sub-carbines to have the new warmup time for the sub-carbines category, being 0.85 seconds
- The conversation for the implementation started here but the actual change was never made.
https://discord.com/channels/278818534069501953/322827713335394304/959749582835814460
- Sub-carbines are guns with lower than 12 inch barrels, categorizing them with SMGs in the warmup aspect of things makes them very good with very few downsides. Giving them a separate warmup time balances things out fairly well, keeping SMGs and pistols as the fast firing cqc weapons and rifles for longer range engagements. Sub-carbines will be somewhere in the middle without stepping on the other categories' toes.

Implementing the sub-carbine warmup time category

---

Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml

- Buffed Siegebreaker armor's energy shield similar to shield belts by a factor of x1.5.
- Vanilla and modded shield belts have x1.5 the capacity of their vanilla version in CE, patched the siegebreaker armor variants to make them consistent to that design.

Siegebreaker energy shield buff

---

Patches/Core/ThingDefs_Races/Races_Humanlike.xml
Patches/EPOE Forked/Bionics_Patch.xml
Patches/RBSE/Bionics.xml
Patches/Vanilla Bionics Expansion/HediffDefs/FSFAdvancedBionics_AddedParts.xml
Patches/Vanilla Bionics Expansion/HediffDefs/FSFBionics_AddedParts.xml

- Added the human bite attack tool back tot he melee attack pool of humans.
- Patched modded jaw bionics that have bite attack tools.
- Increased human punches' blunt armor penetration from 0.25 to 0.5
- Human bite attack tools were left out because of an arbitrary reason (they were thought as stupid). Added the base bite tool and patched modded bionic jaw bite tools because it only made sense. A human bite has the force of 150 PSI which translates to 1MPa, hence the AP of the bite attack.
- Punches IRL can range from 150 PSI for average unskilled humans to 800 PSI for skilled boxers which translates to 1MPa to 5.5MPa, hence the increase in AP of punches.

Human and bionic melee attack tools adjustments

---

Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml
Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Dragonian_Apparel.xml
Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Royal_Apparel.xml

New royal apparel.
Fixed one we've missed for a while.
New suppession/soothe helmet.
Add partials onto the power armor. Most of the moyo helmets aren't significantly thinner looking for the faceplate outside of the light diving helmet, so they all retain 100%. Helmet is glass, but probalby still pressure resistant, just not actually good at stopping penetrating things like bullets, so only reduces the sharp armor, though it is more significant that most other helmets.
Suppression/Soothe helmets don't have a modification to the suppression in terms of getting shot at helmets since conceptually it'd be the soothe that would have that if nothing else, but I'm not really against adding a suppression offset if it seems reasonable to someone else.
Could give either the suppression or soothe (or …

Moyo apparel updates

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs

Go back to the hard armor damage formula that properly handles near-pen deflected damage properly.
- Partially reverts #1437's revert from #1193.
- Related to #1437 and #1504
- Hard armor needs to take damage from attacks that *almost* pen.
- Clamping 0/1 should avoid the ZL issue
Square or sqrt the relative AP values to tweak damage taken.
Don't cap the top end damage - probably break ZL again, but maybe use a higher cap?

Fix hard armor damage without breaking ZL

---

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/Ammo_Laser.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/Ammo_Vikings.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VFEIMeleeSpacer.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VFEVRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWECRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWELRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWENLRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWEQRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets_Spacer.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Melee_Warcaskets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Weapons_Mech.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Races/Races_Mechanoid.xml

- Patches for new spacer Warcaskets.
- Plasteel cost increased by 50%.
- Increased spacer component count by 2 - 4.
- Patches mech drones for "controller' armor. They work, but the turret drone may have a seemingly harmless error associated with it.
TO DO:
- Patched-in weapons.
- Removed patched-out CarryCapacity changes.
Closes #1586 

Update Vanilla Factions Expanded - Pirates

---

Patches/Save Our Ship 2/HologramRace_SOS2.xml

None
Enables SOS2 holograms to fight in melee mode without breaking the game in interesting ways.
None
The weapon's properties are set such that the CE Hologram Sword is to the CE Plasmasword what the SOS2 Hologram Sword is to the vanilla Plasmasword.
Never set SOS2 holograms to melee mode, never hunt animals with said holograms, and mod out social fights.
- [✓] Compiles without warnings
- [✓] Game runs without errors
- [✓] With and without patched mod loaded
- [✓] Playtested a colony (30 in-game days with the hologram pawn in play)

Fix SOS2 Hologram Sword

---

Patches/Erin's Viera/PawnKinds.xml
Patches/Erin's Viera/Race_Viera.xml

Per MasterXdoof's request:
Patch created using previous patch for Erin's Au Ra as a base
-No new additions
Using patch for Erin's Au Ra as a base, no changes needed beyond @name and defName changes to Viera
* No changes to stats for any melee attacks as default Viera has the same combat stats as an Au Ra without the extra body parts
* [✓] Compiles without warnings
* [✓] Playtested a colony (10 minutes using Character Editor and Dev Tools to spawn raids, cause injuries, and give weapons and ammo)
In testing, race spawns within raids as normal within factions they should spawn in. They have correct gear and ammo for their gear.

Patch Erin's Viera

---

Patches/Mechanite Plague/Patch_AddAmmo.xml
Patches/Mechanite Plague/PawnKinds_MechanitePlague.xml
Patches/Mechanite Plague/ThingDef_Misc.xml
Patches/Mechanite Plague/ThingDef_Races.xml
Patches/Mechanite Plague/ThingDefs_Melee.xml
Patches/Mechanite Plague/ThingDefs_Ranged.xml
Patches/Mechanite Plague/ThingDefs_Weapons.xml

From the author of Mechanite Plague, who lacks a GH account.
- Added support for two new mechanoids, the Drider and the Incubator.
- Added support for three new weapons, the Mechanite Slugger, the Chaos Launcher, and the Incubator Cannon.
- Added ammo / projectiles for each new weapon. (Only the Mechanite Slugger's is craftable.)

Update mechanite plague

---

Patches/YetAnotherProsthetics - Core/Patches/Bionics_Patch.xml

Contains patched bionics supporting hands/arms and jaw for CE damage mechanics, balanced around vanilla CE bionics using part efficiency values as the baseline.  Currently has non-functional lung enhancements for smoke resistance commented out until working.
Patch folder - "YetAnotherProsethetics - Core" containing Bionics patch xml
No changes, just addition of patchset for YAP - Core.
Based off of EPOE-Forked and RAH, along with additional bionics review.  Baseline for mod is 125/150/175/200% part efficiency progression, replacement/augments only with only two implants (skin in the uncraftable category).  Skins are based off SOS2 Archo from mod maker's work so used CE:SOS patch values for Arch skin and reduced appropriately for ultra tier skin.
All other parts use bionic/arch values from …

First run patch - YetAnotherProsthetics - Core

---

Patches/Miho Race/Ammo/Ammo_Miho.xml
Patches/Miho Race/DamageDefs/AbilityDamage.xml
Patches/Miho Race/PawnKindDefs/Miho_PawnKind.xml
Patches/Miho Race/Scenario/Miho_Scenario.xml
Patches/Miho Race/ThingDefs_Items/Items_Resources.xml
Patches/Miho Race/ThingDefs_Misc/Miho_Apparel.xml
Patches/Miho Race/ThingDefs_Misc/Miho_Apparel_Special.xml
Patches/Miho Race/ThingDefs_Misc/Weapons.xml
Patches/Miho Race/ThingDefs_Misc/Weapons_Mechanoid.xml
Patches/Miho Race/ThingDefs_Races/AlienRace_Miho.xml
Patches/Miho Race/ThingDefs_Races/Race_MihoMech.xml
Patches/Miho Race/ThingDefs_Races/Race_MihoSummon.xml
SupportedThirdPartyMods.md

Patch for Miho the Celestial fox.
Caliber selections for the conventional guns is based on the descriptions. (8mm for pistol, 6.5 for rifle, 13.2 for the sniper).  Added in the addtional AP-I variant that deals the mod specific ammo for those calibers, including for the pistol. 
Ability damage has been moved to electric since getting it working nicely with heat armor type was not really clear what it was using to determine the penetration. Addtionally, sharp (which is what the base magic damage was initially) suffered even worse from the same problem.
Could set up a specific ammoset for each of the weapons related, but it is honestly kind of easier to manage/control by just adding the ammo.

Miho Patch

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs

No new additions, just a null check
A null check in GetDeflectDamageInfo to make this code executes in case if the game deals damage without instigator.
Mods were broken due to a Null Reference Exception so I decided to PR a fix it directly instead of patching CE manually

Nullcheck in GetDeflectDamageInfo

---

Patches/Core/Stats/Stats.xml

- Closes #1609 
We rename the ShootingAccuracy stat to WeaponHandling, but in its description it still uses "shooting accuracy" in the description of the formula.  This changes that to "weapon handling".

Fix #1609: relabel to "weapon handling" in description.

---

Languages/English/Keyed/Keys.xml
Source/CombatExtended/CombatExtended/Comps/BipodComp.cs

- Closes #1549 
Embedding English strings for gizmo descriptions prevents translating CE to other languages.

Add translation keys for bipod gizmos.

---

About/About.xml

- Due to the negligence of the BL author and the myriad of issues that the mod is causing for CE, it's best that the mod is added to the "incompatible mods list" in an attempt to save the players' games and avoid more future troubles.
- No Alternatives. RIP and TEAR, until it is done.

State Better Loading as CE-Incompatible

---

Patches/Dragon's Descent/BodyDefs/Bodies_Animal_Dragon.xml
Patches/Dragon's Descent/DamageDefs/Damage_Dragons.xml
Patches/Dragon's Descent/Drugs/Draconic_Ambrosia.xml
Patches/Dragon's Descent/Drugs/Dragon_Blood_Potion.xml
Patches/Dragon's Descent/HediffDefs/Hediffs.xml
Patches/Dragon's Descent/Projectiles/Projectile_Animal.xml
Patches/Dragon's Descent/Scenarios/Scenarios_DragonsDescent.xml
Patches/Dragon's Descent/ThingDefs_Items/Items_Exotic.xml
Patches/Dragon's Descent/ThingDefs_Items/Items_Resource_Leather.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Common_Dragon.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Dragon_Base.xml
Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Rare_Dragon.xml

OHH why did you change mod name... Also, this one is just "fixing pre-existing patch" rather than making one from scratch. However, this one will still make your dragons not fall from very angry sheep kicking sand in the eyes and will instead properly bite their heads clean off.
nothing
Changed mod name in all patch targets (OHH why), leather name and i think that's it.
- Contributes towards #452 i guess?
It dun work
I wanted to make it work
I made it work
I've just fixed what was broken without implementing anything new.
- [yes] Compiles without warnings
- [yes] Game runs without errors
- [maybe] (For compatibility patches) ...with and without patched mod loaded - "Draftable animals" or …

Fixing them dragons descending

---

Defs/ApparelModBlacklist.xml
Source/CombatExtended/CombatExtended/Defs/ApparelModBlacklist.cs
Source/CombatExtended/CombatExtended/Settings.cs
Source/CombatExtended/Compatibility/ApparelAutoPatcher.cs

The autopatcher hits nearly *everything*, limited only by what templates match.
This means the patched values of anything that falls in the range of a template get replaced again.  
There are two problems with the first approach.  
First is that things like hats do not have a bulk added, they get a default assigned, but since it isn't in their statBases, they get targeted, despite already being patched.
Second is anything inheriting values from patched defs get targeted.  This is what happens with the corset, the parent def is patched to 2.0 for the value, which matches the armor vest range and gets changed to 16.
Push back the release till a solution is found.
Add a `<patched>` tag to things manually patched which should be skipped. -- significant work, including in downstream mods which …

Add blacklist to Autopatcher

---

Defs/GunPatcherDefs/SniperRifle.xml
Source/CombatExtended/CombatExtended/GunPatcherUtil.cs
Source/CombatExtended/Compatibility/GunAutoPatcher.cs

* consider autopatching guns with null weaponTags
* Use verbClass instead of typeof verb to get the verb class
* don't try to patch guns with null `defaultProjectile`

Gun autopatcher fixes

---

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets_Spacer.xml

- Patched the remaining warcasket variants' energy shields
- https://github.com/AndroidQuazar/VanillaFactionsExpanded-Pirates/commit/7cbc8a5748c78cf26be528ee01b5f5d077a18921
- The energy shield recharge rates were set to 10 by mistake which is fixed in the original mod. Other warcasket variants besides the Siegebreaker one did not have their energy shield characteristics patched for CE which is done in this PR

Warcasket energy shield readjustments

---

Ideology/Patches/ThingDefs_Buildings/Buildings_Ancient_Outdoors.xml

- Patched the untouched outdoor ancient junk buildings from ideology, they can serve as semi-decent cover now.
- Said buildings had the vanilla fillPercent value of 0.5 which is too short for their texture in CE standards, the change aims to make them consistent to their appearance. 

Ideology ancient junk heights adjusted

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

[As illustrated here](https://github.com/CombatExtended-Continued/CombatExtended/issues/1575), projectiles converted to CE didn't use effecters when spawning explosions, unlike vanilla does.
- Added a check to trigger explosionEffect for ProjectileCE comp if there is an effecter set in XML
- I took [these lines of vanilla code](https://github.com/josh-m/RW-Decompile/blob/d5bbfd741a46452bbfbec3a38b11a122f766f057/Verse/Projectile_Explosive.cs#L44) and added them to the CE comp.
- Changed the variable names from vanilla code to fit the ones existing in CE method.
- Contributes towards #1575
- [In this …

Add trigger for explosionEffect tag of projectiles

---

Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_BoltAction.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_DMR.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Launchers.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Rifle2_Style.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_SMG.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Shotguns.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_SmolKnifes_CE.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_Swords_CE.xml
Patches/RH2 Rimmu-Nation² - Weapons/Rm2_CE_AirSupport.xml

- Patch weapons using existing patch stats: SKS DMR, NLAW, Javelin, Intervention, OVU DMR, Mk14 EBR, M4A1, F2000, KRISS Vector, Desert Tech SRS, ACR, G3A2, Tar-21
- Patch weapons with new stats from Guns sheet: Pancor Jackhammer
- Add bulk to SOFLAM so it doesn't get autopatched.
- Some whitespace changes for housekeeping.
Closes #1602 
Many of these weapons (or variants with only nominal differences) were already patched in various CP / RH integrated patches. Using these patches is both efficient and good for keeping things consistent. Stats for the Pancor Jackhammer were made using the Gun Sheet, generated using stats from the gun's wiki page.

Patch New RH2 - Weapons Guns

---

Patches/Vanilla Base Generation Expanded/SettlementDefs.xml

- Removed the EMP and smoke launcher which are removed in CE from settlement loot tables.
- Removed elephant tusks and thrumbo horns from tribal settlement defense structure loot table since they are not weapons anymore.

Vanilla Base Generation Expanded patch

---

Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml

- Changed the blaster turret to use the proper mech 6x22mm charge ammo instead of the human-built 6x24mm
- Changed the burst shot count of the turret from 10 to 5
- Changed the mech turret ranges to avoid in-game confusion caused by the weapon range display of the turret.
- The vanilla counterpart of the blaster turret is a long range turret with single-shot bursts, the CE one is changed in this PR to better reflect that.
- Vanilla weapon ranges are set to values with a 0.9 on top to avoid the guns being able to hit targets at the edge of their allowed range, the mech turrets currently can shoot targets outside their displayed range because their range is set to 5 instead of 4.9 for example. This change helps the player to understand the actual range of the turrets and prevent their pawns …

Mech mini charge blaster turret tweaked

---

Defs/Ammo/HighCaliber/20x102mmNATO.xml
Defs/Ammo/HighCaliber/20x110mmHispano.xml
Defs/Ammo/HighCaliber/20x82mmMauser.xml
Defs/Ammo/HighCaliber/20x99mmShVAK.xml

- Adjusted the armor penetration values of the 20mm rounds.
- Looking at the armor penetration values of the 20mm NATO round, it seems that the current values are back-ported from the AP-HE penetration values which are sources from Wikipedia and the current 26/13 AP values are absurdly low in comparison to even 14.5mm or other smaller 20mm cartridges which are slower in some cases in comparison to the NATO one. The stated value is for a high explosive round which is not designed for penetration so it is not a good basis for the AP rounds.
With that in mind and considering the armor penetration values of the other 20mm round, I've gone with the guesstimate of 30/15/53mm of armor penetration which keeps the 20mm NATO round is line with other rounds of its family while keeping it from …

Readjusted 20mm rounds' armor penetration values

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml

- Added proper terrain affordance nodes to the turrets added by CE.
- Just like other vanilla structures having a specific terrain affordance based on their mass and other things, turrets added by CE have to have the proper terrain affordance properties.

CE turret terrain affordance fix

---

Defs/Ammo/Advanced/5x35mmCharged.xml
Defs/Ammo/Advanced/6x22mmCharged.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Ammo_Mechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Artillery.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Manned.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- Removed certain modded turret structures' explosive comp.
- Fixed the fire modes of the charge, sentry and EMP turret from VFE-Security.
- Fixed the 155mm from VFE-Security to preventing it from spawning in raids by accident.
- Adjusted the 155mm artillery's mass to 5500kg based on the 155mm howitzer.
- Fixed the field gun and cannon from VFE-Pirates not being able to be built under a roof.
- Tweaked VFE-Mechanoids ship and buildable turrets.
- Adjusted the ship charge railgun turret from VFE-Mechanoids to a more sane level of strong.
- Vanilla and DLC turrets have their explosive comp removed so that they don't explode when damaged, some modded still had the comp which is removed via this PR.
- The Charge, sentry and EMP turret did not have a proper fire mode set same as other unmanned …

Modded turret tweaks

---

Patches/Rimsenal Collection/Core/Ammo_YP.xml
Patches/Rimsenal Collection/Core/Rimsenal_Melee.xml
Patches/Rimsenal Collection/Core/Weapons_YP_CE.xml

Changes to the YP dual wield Dagger which were reverted to single one handers.
Shard pistols got a tag, mostly because they switched to and fro from dual to single, and back to dual again unless _Dual Wield_ mod is installled, and since that isn't supported anyway, yeah...
Doesn't make a lot of sense for them to have some of the doubled stats/characteristics after the adjustment. Now also one handed

Yp updates

---

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Resources_Leathers.xml

- Tweaked a couple AA leathers that had incorrect heat armor values
- The added wools by AA already have proper heat armor value inherited from WoolBase, the silks did not have proper heat armor values in proportion to their vanilla counterpart.

Alpha Animals leather heat armor tweaked

---

Defs/ThingDefs_Misc/Apparel_Shield.xml

- What it says on the tin, nudists don't care about "wearing" shields anymore.
- Cuz duh! Shields are worn in CE but are not actual clothing.

Allow shields to be comfortably used by nudists

---

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_ArmorPartial.cs

The description of apparel now only shows a range if partial armor is enabled.

Only display armor ranges when partial armor enabled

---

Patches/Alpha Animals/ThingDefs_Misc/Alpha_Hediffs.xml

Added Bulk and CarryWeight based on gigantelope's hediff quality.
I think gigantelopes should be a better muffalo for caravans. Currently there should be no reason to choose gigantelopes when you have muffalo in the map for caravans. Their only use is milk and meat for butcher. I could have changed the body size to match muffalo's but I thought this was better.
I could have changed the body size to match muffalo's but I thought this was better.
The carry weight and bulk can be changed for balance. Carry weight I just doubled the carrying capacity on the hediff. Carry bulk... I did it without any formula consideration...

Aa gigantelope hediff

---

Defs/ThingDefs_Misc/Weapons_Spotting.xml

- Using binocs in melee combat freaks the melee targeting system out just like other weapons that used to not have a melee tool, this PR fixes the error by giving them an appropriate melee tool.

Give binocs a melee tool

---

Patches/Rimsenal Collection/Core/Weapons_YP_CE.xml

- Fixed a small typo in the YP weapons' patch causing the whole patch sequence to fail.

Fix Rimsenal's YP weapons patch

---

Patches/Dubs Rimatomics/Apparel_Atomic.xml

- What it says on the tin, RA's masks now occupy the strapped layer as well
- Gas masks can't be worn on top of radiation masks

Tweak Rimatomics' Radiation mask's occupying layers

---

Patches/Moyo Cartel/Ammo/Ammo_Moyo.xml
Patches/Moyo Cartel/PawnKindDefs/Moyo_PawnKind.xml
Patches/Moyo Cartel/ThingDefs_Misc/Moyo_Apparel.xml
Patches/Moyo Cartel/ThingDefs_Misc/Moyo_Royal_Apparel.xml
Patches/Moyo Cartel/ThingDefs_Misc/Weapons.xml

Moyo Cartel PR
Note that there is a lot of content looking stuff in the mod that is not implemented yet, so realistically we ought to expect updates
Mostly simmialr to the existing Moyo equipment, the executioner armor is high spec but unbuildable for a skin/middle apparel.
Not really an alternative, but unless there's a intent to change how they function might be worth taking the dive and converting over all the moyo charge weapons to be more unified with CE charge gun costs.

Moyo Cartel Patch

---

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml

- Tweaked some of the Warcasket guns for better balance.
- Similar to how the slug rifle fires 25mm rounds instead of the 30mm or the handheld slug rifles from VWE-Heavy Weapons, it only makes sense to lower the autorifle's caliber from 20mm to .50 BMG since it's a smaller rifle in comparison to the autocannon turret's gun.
- Lowered the minimum range of the slug rifle since it's a smaller version of the slug turret wielded by a tall pawn in a Warcasket so it makes sense fro mthe pawn to be able to shoot closer to itself.
- The handheld cannon similar to the slug rifle is not a mortar to have such high minimum range, the current stats and nodes in its patch are copied from the handheld mortar in VWE-HW which is not the same as a handheld cannon.

Readjust a couple Warcasket guns

---

Defs/Ammo/Shotgun/20Gauge.xml

20 Gauge shells were previously outdated and used the old armor penetration data. I've added them to the main projectile sheet. Stats are based off of **Remington Express Ammunition 20 Gauge 2-3/4" #3 Buckshot 20 Pellets** for the shot shells and **Remington Slugger Ammunition 20 Gauge 2-3/4" 5/8 oz Rifled Slug** for the slug.
Stats were outdated. Updated them based upon widely available commerical ammo.
Find other stats, I guess?

Update 20 Gauge Shotgun Shells

---

Source/CombatExtended/CombatExtended/CE_Utility.cs
Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs
Source/CombatExtended/CombatExtended/DangerTracker.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Explosive.cs
Source/CombatExtended/CombatExtended/Settings.cs
Source/CombatExtended/CombatExtended/SuppressionUtility.cs

1. Function to return a 3D vector which if used to trace a shape with vectors of the same length would trace a square instead of a circle;
2. Pawns change remembered suppression location if the local suppression exceeds their suppression threshold;
3. A function to add danger to cells in a radius around a center cell;
4. Debug toggle for displaying cell danger rating;
5. Debug toggle for displaying cell cover ratings for a pawn;
6. Danger multipliers for projectiles and explosions;
7. Fused explosives apply danger to cells after landing and apply suppression to pawns before exploding, with more suppression being applied depending on how close they are to exploding;
8. Overhauled how cell cover rating is calculated and how pawns pick cells for running to cover.
9. Projectiles that do no …

Suppression tweaks

---

Patches/Advanced Mechanoid Warfare/Patches/Patch_Ranged.xml
Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_RangedMechanoid.xml
Patches/Anty the war Ant/ThingDefs_Misc/Weapons.xml
Patches/Bori Race/ThingDefs_Misc/Weapons.xml
Patches/Bulgarian Imperial Uniforms/RangedIndustrial.xml
Patches/Censored Armory/Weapons_Guns.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Kaiser Armory/KaiserArmory_Guns.xml
Patches/Kit's Gunpowder Weapons/KitsGunpowder_Guns.xml
Patches/Kit's Industrial Weapons/KitsIndustrial_Guns.xml
Patches/Logann/Wolv_Weapons.xml
Patches/Mechanized Armor Set/Ammo_&_Apparel_Defs.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Grenades_MechanoidsExtraordinaire.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Guns_MechanoidsExtraordinaire.xml
Patches/MoreMechanoids/ThingDefs_Misc/Weapons_Mechanoid.xml
Patches/Moyo from the depth/ThingDefs_Misc/Weapons_Mechanoid.xml
Patches/Moyo light in the abyss/ThingDefs_Misc/Weapons.xml
Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_RangedWeapons.xml
Patches/Nihal/ThingDefs_Weapons/Weapons.xml
Patches/Red Army/RedArmy_Weapons.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_MechWeapons_Mech.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_SpacerWeapons_Mech.xml
Patches/Rim-Effect Asari and Reapers/Weapons_Reapers.xml
Patches/Rim-Effect Core/Mech_Weapons.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_Charge_CE.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_RSGuns_CE.xml
Patches/Thog's Guns - More Brukka Pack/Ranged_Industrial.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
Patches/WWII Soviet Faction/WWIISovietFaction_CE_Patch_RangedIndustrial.xml

- Added the NoSwitch tag to Mechanoids weapons.
- Mechs be it colony built, hostile or hacked are not smart enough to reequip their guns o their own and can't be forced to do so either, the NoSwitch tag makes sure that their guns are not stowed away when out of ammo so that after the implementation of #1690 the player can give them more ammo.

NoSwitch tag XML implementation

---

Patches/NewRatkinPlus/ThingDefs_Races/Race_Rotti.xml

Reduced blunt armor penetration of claws in Rotti pet rodents from the Ratkins mod.
Rottis (0.5) are smaller than their Ratkin (0.8) masters, and should be proportionally weaker in their scratch attacks, while being marginally better than ordinary rats.

Reduce fist blunt armor penetration for Rotti pets from Ratkins

---

Patches/Orassans/Ammo/MissileAmmo.xml
Patches/Orassans/ThingDefs_Weapons/Weapons.xml

- Fix incorrect ammo class for Orassan AP sabot missile
- Fix missing CE melee tools for Orassan weapons
- Fixes outstanding issues from #1671 
- Orassan telescoping warhammer has high blunt damage, as the original mod author (DianaWinters) intended for it to be capable of overcoming the blunt armor resistance of most space marine / cataphract armor, despite the weapon's small size.

Fix incorrect ammo class and missing melee tools for Orassans mod

---

Patches/Rimworld-Style Pilas And Bows Strapped With Grenades and Shells Extended/Arrows.xml
Patches/Rimworld-Style Pilas And Bows Strapped With Grenades and Shells Extended/Javelin.xml

Compatibility for Rimworld-Style Pilas And Bows Strapped With Grenades and Shells Extended
Arrows:
- The weapon names were turned into ammo category/type names while keeping its description
- The arrows are added to the bow, recurve bow and great bow ammosets
- For now, the arrows are basically just stone arrows with throw weapons' (grenade, etc.) damage
- Recipes are stone arrow's cost + the thrown weapon
- Explosion radius for the bowlotov and bowttery  follows the same as its base mod
- Turned bowttery into a Stickbomb of sorts. Its recipe uses the Stone arrow's cost + 20 steel and 1 component (from the base mod, which uses a recurve bow + 20 steel and component)
- Due to a lack of graphics for the arrows, the graphics used is the bow graphics.
Pila:
- The weapon's thingdefs are …

Rimworld-Style Pilas And Bows Strapped With Grenades and Shells Extended CE Patch

---

Defs/Misc/TipSetDefs/Tips.xml
Defs/Tutor/Concepts_NotedOpportunistic.xml
Patches/Core/ThingDefs_Races/Races_Humanlike.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Races/RM_Races_Machines.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml

- Implement the Give Ammo system in XML
- Rechamber the Autocannon wielded by the Raider mech from .338 Norma to .50 BMG now that the gun is not infinite-ammo anymore.
- Adjusted the CarryBulk of the buildable mechs and their guns' bulk to improve their ammo carrying capabilities.
- Give AmmoSets to guns wielded by buildable mechs which used to be infinite-ammo

"Give Ammo" XML implementation

---

Languages/English/Keyed/ModMenu.xml
Source/CombatExtended/CombatExtended/Settings.cs

- Changed some of CE's default settings around from false to true and vice versa.
- Changed some of the setting descriptions for the better,
- Both left and right clicking on the reload button brings up the ammo selection settings which enabling the "right-click ammo selection" settings allows for faster reloading by just left-clicking.
- Unrealistic cook-off can cause errors during game save state and switching between the setting during that state spawns broken projectiles that throw constant red errors and the only way to remove the errors is to manually find and remove the projectiles. Also bullets flying off everywhere is stupid and unrealistic.
- Weapon and Apparel autopatcher are both unreliable and not robust enough in their current state, so a default disabled state is a better …

Update/Fix CE's default settings

---

Patches/Fortifications - Industrial/FT_Artillery.xml

- Removed the patch for removing VFE: Security's World Tile bombardment as it is now compatible

Fortifications Industrial Tile Bombardment Update

---

Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_RangedWeapons.xml

Fixed patch operation adding `NoSwitch` to correctly target the `weaponTags` node of Ratkin ranged weapons, rather than the (erroneous) `tools` node.
- Fixes an outstanding issue for #1713
The current patch causes load errors from startup, and prevents Ratkin NPCs from spawning on game maps.

Fix NoSwitch tag for Ratkin ranged weapons

---

Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Races/RM_Races_Machines.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml

- Removed the bodysize patch for the threaded mechs because it was a flat nerf to their carry capacity stats not allowing them to carry ammo.
- Added a reload speed node to the buildable mechs because they start with 0 shooting skill which nerfs their reload speed to 0.75.
- Added proper combat related stats to the mobile turret now that it is functional.

Tweak buildable mechs

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml

- Added proper mass nodes to vanilla and CE-added turret guns.
- Currently the turret guns added by CE only have a mass of 1kg which is not appropriate when all turret guns have a mass value in vanilla game.

Adjust turret gun mass values

---

Royalty/Patches/ThingDefs_Misc/Apparel_RoyaltyHeadgear.xml

- What it says on the tin, fixed Gunlink's stat offsets and recipe materials. 
- Inheritance issues caused by the parent being def `ApparelArmorHelmetReconBase`.

Fix Gunlink's stats

---

Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml

- Gave the Riot mech from VFE-Mechs some melee hit chance stat to help with them spawning with 0 melee skill. 6 melee hit chance is similar to the pawn having 6 skills in melee, roughly the same as 6.7 that scythers have.
- Find a way to give them proper melee skill instead of a workaround, which seems like not an easy task,

Give the Riot mech melee hit chance

---

Defs/Ammo/Advanced/164x284mmDemoShell.xml

- Thump cannon does more damage in a smaller area, allowing it to tunnel through multi-layer walls.
The thump cannon is supposed to be extra damaging to walls and buildings.  Currently, the thump cannon is stopped by a 2-cell thick wall with 1hp left on the outer wall, because of how explosions work in RW.  This does similar total damage to walls, but spread out over 9 individual impacts, allowing it to shread multiple weak layers of walls.

Make Thump Cannon use shaped charge

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs

Mech ammo beacons use the same radius to check for turrets and to check for loose ammo.
- Closes #1689 
Mech ammo beacons could find a turret and drop ammo for it, then fail to find the dropped ammo, resulting in an endless supply of ammo.

Set the scan distance for ammo to the same as the scan distance for turrets

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Set some of the vanilla guns that did not have preset fire mode to Snapshot
- Default fire mode will be set to aimed shot which necessitates guns that should be fired is a rapid fashion to be set to snap shot.

Vanilla guns' fire mode tweaks

---

Defs/Ammo/Advanced/80x256mmFuelCell.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Doom Factions/DoomFactions_Ammo.xml
Patches/Girls Frontline Weapon Pack/ThingsDef_Misc/GFWeapons.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Guns_MechanoidsExtraordinaire.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_MechWeapons_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

- What it says on the tin, reworked 80mm fuel cells from thermobaric to incendiary with a small thermobaric explosion at the epicenter.
- Infernopedes were designed in an era that the Termite mech used to not exist hence the pretty OP shell that they fire. This PR intends to tame their weapon to an extent so that they still remain a threat but they become closer to their vanilla role of incendiary crowd control unit rather than an instant delete button.

Rework 80mm fuel cells from thermobaric to incendiary

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

When a target is downed by burst / full-auto fire, if there is another pawn belonging to the *same* faction, and it is an enemy faction, the shooter will retarget to the next pawn.
Once the target drops, they may break line of sight.  Additionally, if the target *dies*, the shooter stops shooting and can pick the next target.  Which means it is better if the shooter magically knows their target died vs just dropped.  This allows the shooting pawn to retarget if the pawn is downed, and certain conditions are met, which means the minigun and similar full-auto weapons can "walk" a line of targets.  This especially matters with weapons like the Kinetic Lance, which dumps half its mag per burst and full mag per auto, and which often down pawns at medium range without killing them.
Force pawns …

allow retargeting to nearby pawns along same line

---

Source/CombatExtended/CombatExtended/CE_Utility.cs

Downed pawns are now shorter than crouching ones.
Crouching pawns are between 0.25 and 0.5 their base height depending on body type.  Currently, downed pawns are the same height as crouched pawns.  This leads to downed but alive pawns soaking bullets aimed at crouching pawns.  This applies the same percent-reduction in pawn height that standing->crouching gives to go from crouching->prone
Define a prone height for each body type.  Requires xml changes, including in any sub-mods that add their own body types.

make downed pawns even shorter than crouched ones

---

Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs
Source/CombatExtended/CombatExtended/Comps/CompProperties_FireModes.cs
Source/CombatExtended/CombatExtended/Enums/AimMode.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs

Guns remember their fire mode settings
The AI can switch fire mods when it should , no reason to reset it for AI pawns.  Players usually want their pawns' weapons to stay as set.

Don't reset fire mods when dropping guns.

---

Languages/English/Keyed/ModMenu.xml
Source/CombatExtended/CombatExtended/Comps/CompFragments.cs
Source/CombatExtended/CombatExtended/Settings.cs
Source/CombatExtended/Harmony/Harmony_DamageWorker.cs

Explosives (or other large sources) damaging walls can now generate fragments.
Turning a stone wall into a pile of stones *should* send some of them flying with enough force to do damage.
It is gated behind a mod option as it can be a bit expensive to run.

Add setting for wall damage generating fragments

---

Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Apparel_Mechanite.xml

- Rebalanced the mechanite apparel from VFE - Mechanoids.
- In vanilla game, these two items provide almost 20% of the armor that a flak vest provides, which is 20% and 7% sharp and blunt armor respectively. Making the same comparison in CE while being generous and we come up with 2/3 sharp/blunt armor which is still more than 20% of a steel armor vest for a skin layer item that is made out of steel, cloth and advanced components. 2/3 keeps the apparel fairly strong in terms of armor relatively to the other skin layer option in the game.

Mechanite apparel rebalanced

---

Patches/Kobold Factions/Kobold_Kamikaze_Pawnkind.xml
Patches/Kobold Factions/Medieval_Kobold_Pawnkind.xml
Patches/Nakin Race/Nakin_Bionics.xml
Patches/Nakin Race/Nakin_Body.xml
Patches/Nakin Race/Nakin_Items.xml
Patches/Nakin Race/Nakin_Pawnkind.xml
Patches/Nakin Race/Nakin_Race.xml
Patches/Nakin Race/Nakin_Scenario.xml

Patches for Nakin Race and pawnkind patches for kobolds from Kobold Factions
Patch for Nakin is straight foward, the only value I changed was from Nakin goggles, that gave +2 to Aim, increased to +5.
Added a Sticky-bomb pawnkind to Medieval kobolds alongside a *fix* for kobolds as they were not carrying tribal backpack by default
For Nakins, they start with a base -1000% to Weapon Handling, and their goggles are suppose to help them aim, but with just +2 to Weapon Handling, it was not having any significant impact. Increasing to +5 gives Nakin ranged units a fighting chance while not removing the utility of the advanced Nakin goggles. 
For Kobolds, their small size and low tech make them laughable in CE, specially with no sticky bomb pawns. Introducing Kobold Bombers + a new raid kind …

Compatibility patch for 'Nakin Race' and pawnkind patch for 'Kobold Factions' 

---

Source/CombatExtended/CombatExtended/ShiftVecReport.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

Aiming height is capped to wall height to handle tall targets.
Aiming above walls leads to shooting roofs, and very tall targets end up with absurd shot angles when trying for headshots.
Raise the wall / roof height
Handle tall targets in cover differently - more important if we let shooting tall targets *beyond* walls

Fix shooting tall targets

---

Source/CombatExtended/Harmony/Harmony_ShieldBelt.cs

Shield belts no longer stop melee hits.
Fixes bug introduced by previous ion changes.

Prevent shields stopping melee hits

---

Patches/Vanilla Psycasts Expanded/AbilityDefs/AbilityDefs_Patch.xml
Patches/Vanilla Psycasts Expanded/Bodies/Bodies_Patch.xml
Patches/Vanilla Psycasts Expanded/HediffDefs/Hediffs_Patch.xml
Patches/Vanilla Psycasts Expanded/PawnKinds/EmpirePawnKinds_Patch.xml
Patches/Vanilla Psycasts Expanded/ThingDefs/Projectile_Tweaks.xml
Patches/Vanilla Psycasts Expanded/ThingDefs_Misc/Apparel_Patch.xml
Patches/Vanilla Psycasts Expanded/ThingDefs_Misc/Weapons_Patch.xml
Patches/Vanilla Psycasts Expanded/ThingDefs_Races/Races_Patch.xml

- Range adjustment for all psycasts
- because space magic cool
##Issue Notes
- Currently, the Overshield and Guardian Skipbarrier from Protector Psycaster Path, and Shield Animals or even Shrineshield from Wildspeaker Psycast Path are unable to intercept projectiles (in Vanilla they do just fine)
- Warlord's Guideshot Psycast is able to increase ranged weapon's range, but they will remain the same range even if the duration ends unless forced to unequip the weapon to reset their normal range value

Patch for Vanilla Psycasts Expanded

---

Defs/Ammo/HighCaliber/12.7x108mmSoviet.xml
Defs/Ammo/HighCaliber/13.2x92mmSRTuF.xml
Defs/Ammo/HighCaliber/14.5x114mmSoviet.xml
Defs/Ammo/HighCaliber/15.2x169mm.xml
Defs/Ammo/HighCaliber/2-Bore.xml
Defs/Ammo/HighCaliber/20x110mmHispano.xml
Defs/Ammo/HighCaliber/20x128mmOerlikon.xml
Defs/Ammo/HighCaliber/20x138mmB.xml
Defs/Ammo/HighCaliber/20x82mmMauser.xml
Defs/Ammo/HighCaliber/20x99mmShVAK.xml
Defs/Ammo/HighCaliber/300WinchesterMagnum.xml
Defs/Ammo/HighCaliber/338LapuaMagnum.xml
Defs/Ammo/HighCaliber/338NormaMagnum.xml
Defs/Ammo/HighCaliber/408CheyenneTactical.xml
Defs/Ammo/HighCaliber/470NitroExpress.xml
Defs/Ammo/HighCaliber/50BMG.xml
Defs/Ammo/HighCaliber/55Boys.xml
Defs/Ammo/HighCaliber/600NitroExpress.xml
Defs/Ammo/HighCaliber/7.92x94mm Patronen.xml
Defs/Ammo/HighCaliber/950JDJ.xml

- What it says on the tin, added AP ammo types to the high caliber ammo sets that lacked them.
- Some housekeeping.
- Adjusted 12.7x108mm armor penetration based on http://roe.ru/eng/catalog/land-forces/strelkovoe-oruzhie/pistol-cartridges/57-bzt-542m/
- Did the same AP adjustment for the 13.2x92mm TuF round as well since it is a slower, older/obsolete and heavier round.
- Because most of the left-out cartridges already have AP ammo types in real life which they lacked in CE and normal AP rounds are helpful to those that forsake advanced ammunition.
- 12.7x108mm performs mostly the same than the .50BMG, 20mm armor penetration for the FMJ round in the spreadsheet is not based on a source, The BZT-44 round which is an AP-IT round is 15mm with 90% chance of penetration at 100 meters. Setting …

High caliber AP rounds and housekeeping

---

Patches/Rim-Effect Asari and Reapers/Ammo_Projectile_Reapers.xml

- Fixed the ParentName of the ammo used in the patch from thermobaric to the correct incendiary.

RE Asari and Reapers 80mm cell hotfix

---

Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Grenades.xml
Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Grenade/40x53mmGrenade.xml
Defs/Ammo/Grenade/40x53mmVOG25Grenade.xml
Defs/Ammo/Shell/90mmCannon.xml
Defs/ResearchProjectDefs/ResearchProjects_Tier4_Misc.xml

- The projectiles are now gated behind Advanced Launchers (and added a note to the research project description).
- Increased crafting costs for some of the grenades.
- Revised ammo category labels.
- Some whitespace changes.
- The projectiles have a marked increase in average effectiveness against targets, especially against those in cover, and any reasonable player would probably choose to use these instead of basic HE if given the option (barring the extra cost). Thus, putting it at a higher tech level seems reasonable.
- Some the grenades had an extra 2000 work to build, but some did not. I added the extra work to those that lacked the increase and added it to the 90mm flak shell.
- Revised for a bit of clarity, since both 'time-fuzed' and 'air-burst' are used, and I felt the latter …

Adjustments to Time-Fuzed HE Grenades

---

Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Grenade/40x53mmGrenade.xml
Defs/Ammo/Shell/90mmCannon.xml

- Reduces frag count of time-fuzed rounds to match their normal HE counterparts.
- Increased cost of fuzed rounds by about 30% over normal HE.

Adjust Frag Count and Cost of Time-Fuzed Explosives

---

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml

- Fixed some wrong AA projectile damageDefs.
- Closes #928

Fix Alpha Animals projectile damageDefs

---

Source/CombatExtended/Harmony/Harmony_ShieldBelt.cs

VFE looks like it might make traps try to do damage with a null weapon, so check for that.

add null checking to shield belts

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs

Ordering a pawn to continue shooting at a downed pawn works.
When a target pawn goes down and no valid retargets are available, the shooter stops shooting.  If the player then orders the pawn to continue shooting, the pawn needs to start shooting again.  

Fix shooting at down pawns.

---

Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCEOneUse.cs

If EquipmentSource is null and inventory isn't, SelfConsume would NPE, now it just switches to the next available weapon.

Add null check to SelfConsume

---

Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml

- What is says on the tin, added the 6x22mm and the Thump cannon demo shell recipes to the ammo foundry from VFE - Mechs.
- Now that we can give ammo to mechs, being able to manufacture these ammo types and giving them to colony mechs as kind of a necessity.

Add more mechanoid ammo recipes to the ammo foundry

---

Defs/Ammo/HighCaliber/338NormaMagnum.xml

- What it says on the tin, the cartridge had wrong bullet speed in XML which is fixed based on the spreadsheet.

Fix .338 Norma Mag's bullet speed

---

Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Races.xml

- Animals are not guns to have `SightsEfficiency` nodes in their statBases, instead added a `ShootingAccuracyPawn` node to them.

Magical Menagerie patch fixes

---

About/About.xml

- since the current Rimthreaded state is questionable with their performance stability, it's better to stay on the safe side for now.

Axe Rimthreaded from Compatibility List

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Royalty/Patches/ThingDefs_Misc/Weapons_Melee.xml

- Decreased the Royalty warhammer's mass from 5kg to 2.5kg based on the spreadsheet with the base mass increased to 2.5 and speed increase to 30 to replicate the current stats in the patch and also to avoid nerfing the weapon.
- Removed "Woody" materials from the Royalty axes' stuffCategories.
- The closest thing to a warhammer weighs no more than 2.5kg.
- Axe heads are not commonly made from wood.

Royalty medieval melee weapons adjusted and housekeeping

---

Patches/Vanilla Genetics Expanded/ThingDefs_Races/Races_Animal_ArchoCentipede.xml

- Buffed the Archotech Centipede from VGE as it is a ultimate weapon and the end-game win condition.
- A nigh unkillable pawn should resemble as such.

VGE Archotech Centipede buffed

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Readjusted the minigun based on the findings linked below and the newly inserted mass value into the spreadsheet.
- http://www.navweaps.com/Weapons/WNUS_30-cal_GAU17.php
- Pawn can't properly spawn with 30kg miniguns and carry enough ammo for it.
- Assuming that the minigun itself weighs around 16kg based on the M134D Gatling gun, a battery pack that weighs around 4kg makes sense resulting in a package that weighs 20kg. The result is still a fully loaded minigun not being a viable weapon for an unaugmented pawn or a pawn that is wearing some armor which also wants to carry extra ammo for the gun, armored pawns still won't be able to carry a minigun around.

Minigun readjusted

---

Patches/Core/Bodies/BodyParts_Animal.xml

- Increased the "Body" and "SnakeBody" bodyparts' HP by 10 respectively.
- Same as humanoid and mechanoid torso's and thoraxes that have had their HPs increased, animal bodies need the increase to prevent the "Body destroyed" situation happening to them to some extent.

Increase animal bodies' HP

---

Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Apparel.xml

- What it says on the tin, the `equippedStatOffsets` were unpatched...

Fix VFE - Medieval plate helmets' stat offsets

---

Defs/Ammo/HighCaliber/12.7x108mmSoviet.xml
Defs/Ammo/HighCaliber/14.5x114mmSoviet.xml
Defs/Ammo/HighCaliber/15.2x169mm.xml
Defs/Ammo/HighCaliber/50BMG.xml

- Made adjustments to certain high caliber ammo based on some sources.
- The new values with the sources used are all entered here:
* The new AP values for 20mm rounds are included here as well
- We use uniform bullet mass values for different ammo types, made this the case for .50 BMG and .50 Soviet withc adjustments to bullet velocity and mass.
- 14.5mm rounds penetrate 40mm RHA based on the sources on the internet, 38mm at 100 meters is a good estimation for in-game values of an AP round.
- 15.2x169mm is a APFSDS round and the cartridge does not have any other ammo types.

Higher caliber ammo readjusted

---

Patches/O21 Mechadroids/Bodies_Mechadroids.xml

Add missing body part groups for Mechadroids
Fixes a bug where mechadroids would wear an infinite number of backpacks.
XML Only
Just checked if the backpack bug is gone

Added missing bodyparts groups for Mechadroids

---

Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- What it says on the tin, added back the autocannnon research prerequisite to the double autocannon which was missing due to it being replaced by mistake.

VFE Security double autocannon research prereq. fix

---

Patches/Vanilla Skills Expanded/Expertise.xml
SupportedThirdPartyMods.md

- Added the patch for Vanilla Skills Expanded's combat-related expertise
- Adjusted the aiming time expertise for better balance in CE's ecosystem.
- Changed the Reloading expertise t actually impact reload speed in CE.
- The melee weapon armor penetration expertise looks to not be working in CE with the original VSE modifier, the `MeleePenetrationFactor` does not impact melee weapons either when given to pawns. So instead I opted to go for a crit chance bonus to resemble the armor penetration aspect of the expertise since crits with sharp weapons have double armor penetration.

Vanilla Skills Expanded patch

---

Patches/Vanilla Factions Expanded - Pirates/AbilityDefs/Abilities.xml
Patches/Vanilla Factions Expanded - Pirates/Misc/Hediffs_Casts.xml
Patches/Vanilla Factions Expanded - Pirates/Misc/Precepts_Role.xml

- Added the MayRequire condition to Ideology-related stuff from the mod's patches since they were throwing errors if Ideology was not enabled in the modlist.

VFE Pirates' patch fix

---

Defs/Ammo/Projectiles_Fragments.xml

- Rebalanced the large fragments.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1198674278
- Closes https://github.com/CombatExtended-Continued/CombatExtended/issues/1811
- According to the holy spreadsheet, large fragments are apparently 11 cubic millimeters of material, which even when made out of Tungsten, that'd amount to 25 grams per fragment and 10 grams for steel fragments. This PR fixes the wrong math by giving large frags less mass resulting in them being not so overkill...
- Leave large frags as is and add medium frags which would require much more work and rebalancing, large frags are just wrong value-wise.

Large fragments adjusted

---

Patches/Core/ThingDefs_Misc/Apparel_Various.xml

- Removed a redundant Marine Armor name and description patch which was only confusing and created inconsistencies.

Remove the name and description patch of the Marine Armor

---

Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/12x72mmCharged.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml

- What it says on the tin, tweaked and fixed some values based on the spreadsheet. 12mm charged ammo is 40 grams because it is loosely based on .50 BMG.
- 12x72mm as mentioned in the name has a longer "case" than 12x64mm charged ammo, so made it a bit faster to resemble that.
- Tweaked the HCB based on the spreadsheet.
- https://docs.google.com/spreadsheets/d/11ZcgItLsGnegNDy08xCMxbO3jHv2YNwmmbwabRKzkwg/edit#gid=1573763037

Tweaked the 12mm charge ammo

---

Defs/Ammo/Advanced/12x72mmCharged.xml
Defs/Ammo/Advanced/6x22mmCharged.xml

- Redid the #1829 PR while keeping the 12x72mm ammo intact and as the 12x64mm equivalent as it's supposed to be the carbon-copy of the aforementioned ammo.

Redo of #1829

---

Defs/Ammo/Advanced/12GaugeCharged.xml
Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml
Defs/Ammo/Shotgun/12Gauge.xml
Defs/Ammo/Shotgun/20Gauge.xml
Defs/Ammo/Shotgun/23x75mmR.xml
Defs/Ammo/Shotgun/410Bore.xml

- Fixed the shot ammo mass value formula which was incorrectly calculated in the spreadsheet due to it not taking pellet counts into account when calculating cartridge mass. The new formula is included in the linked spreadsheet which correctly calculates cartridge mass based on pellet counts.
- Changed the 23x75mm shot shells from firing # 1 shots to 00 buck.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1198674278

Shot ammo mass value fix

---

Defs/Ammo/Rifle/303British.xml

- Tweaked the .303 ammo based on the Mark VIIIz rounds.
- The data used for the ammo was based on the old designs of the cartridge which were not so good, used the latest version as the base in the spreadsheet which resulted in a slight buff to the ammo.

.303 British tweaks

---

Patches/Vanilla Weapons Expanded - Coilguns/RangedSpacer.xml
Patches/Vanilla Weapons Expanded - Laser/RangedSpacer.xml

- Lowered the shot spread of the laser and coilgun weapons from aforementioned mods.
- The guns in question are supposed to be very accurate but in-game the very opposite is true, made some tweaks to make them a bit more accurate.

VWE Laser and Coilgun adjustments

---

Defs/ThingDefs_Misc/Apparel_Carrying.xml

- What it says on the tin, the item was inheriting wrong recipe stuff from its parent def causing stuff like stuffed unfinished Exoframes.

Fix the Exoframe's unfinished item

---

Defs/Ammo/Shotgun/20Gauge.xml

- What it says on the tin, based on sources on the net and number comparisons, the 20ga shells had too much sharp penetration which this PR fixes.
- https://www.youtube.com/watch?v=-VeeqLX0CZA

Adjuested 20 Gauge ammo

---

Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_Ammo_Mech.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_SpacerWeapons_Mech.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VFEVRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWECRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWELRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWENLRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWEQRangedWarcasket.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
Patches/Vanilla Weapons Expanded - Heavy Weapons/RangedIndustrialHeavy.xml

- Tweaked some heavy weapons from VWE Heavy to be consistent with their counterparts.
- .50 BMG out of even a short barrel goes farther than .338, made it so for the Pirate autorifle and consistent among other guns.
- Some housekeeping and duplicate/redundant values removal, the mass node removed were because the items themselves already had the same mass value making the replaced value redundant.
- Tweaked the Folding Gun from Pirates to be more accurate to its description.
- Changed the charge lance rifle from Reinforced Mechanoids to fire 5x35mm High-Velocity instead of 8x35mm.

Heavy weapon tweaks and housekeeping

---

Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Aura.xml
Patches/Alpha Animals/VFE_Mechs/AdvAura.xml
Patches/Alpha Animals/VFE_Mechs/VFEAura.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml

- Rebalanced the Aura mechs from Alpha Animals based on the spreadsheet.
- Scythers had a faster left hook for some reason, fixed that as well.
- https://docs.google.com/spreadsheets/d/1gJreRqm--zvrJlpSd1Jq6G3v4b7aHwhwtDotXcFB9mQ/edit#gid=647442519
- Absurd and unrealistic values were used for the Aura mechs which made them even more OP than they are intended to be.

Aura mechs rebalanced and housekeeping

---

Patches/Vanilla Weapons Expanded - Coilguns/RangedSpacer.xml
Patches/Vanilla Weapons Expanded - Laser/RangedSpacer.xml

Reverts CombatExtended-Continued/CombatExtended#1839
Apparently the spread value for the laser guns decides the damage falloff which was unbeknownst to me.

Revert "VWE Laser and Coilgun adjustments"

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml

- Added a patch that increase the Pikeman mech and its variants' combat power from 110 to 180.
- Increased their health scale to 1.0 to make them more durable than their current paper-weak status.
- Pikeman mechs in CE are tougher than Lancers and Scythers with more dangerous guns, 110 Combat Power for them is too low which results in them being spammed in raids which is not appropriate for a relatively tougher pawn.
- Pikeman mechs are easier to hit than other walker mechs which their 0.85 health scale is a disadvantage on top of that.

Pikeman mech combat power increase

---

Defs/Stats/Stats_Pawns_Combat.xml

- Added a `postProcessCurve` to the stat to increase the higher end of the cap.
- Closes #1583 
- So that apparel that might give a bonus damage in the future are not pegged by the cap.

Unarmed damage bonus stat uncapped

---

Patches/Alpha Animals/AA_VPE/AbilityDefs/AbilityDefs_Patch.xml
Patches/Alpha Animals/AA_VPE/HediffDefs/Hediffs_Patch.xml
Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_BlackHive_Psycasts.xml
Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_BlackLarva.xml
Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_BlackQueen.xml
Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_OcularOriginator.xml
Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_Summoned_Eyeling.xml

- Added the patch files for the new additions to the Alpha Animals mod, including the new animals and Psycasts.
- The new temporary pawns that are spawned via psycasts are the exact same as the already existing ones in the mod, so the patches are the same as well.

Alpha Animals patch update

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Fixed the base CE and vanilla turrets based on the data from the gun spreadsheet.
- Rechambered the charge blaster turret from 6x24mm to 8x35mm charged.
- By the time that the charge blaster turret becomes available, it's pretty much obsolete and underpowered, let alone it consuming 950 watts of power as well. I am aware that it pretty much is the human-built version of the mech mini slugger turret tho but it has to have a good purpose to be built. To summarize, the current implementation is expensive for its performance, low firepower for the stage of the game it is unlocked at and high power consumption again for the general lackluster performance of it.  …

Tweaked base CE turrets

---

Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Grenade/40x53mmGrenade.xml

- Introduced a new ammo type in the projectile spreadsheet specifically for the HEDP grenades which balances them out damage-wise.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1198674278
- HEAT projectiles are not the same as HEDP nades...

40mm grenade hotfix

---

Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_Ammo_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Ammo_Mechanoid.xml

- Fixed the custom mech ammo's parent name added to patched mods causing duplicate secondary damage values inherited from the parent.

Custom modded mech ammo hotfix

---

Defs/Ammo/Advanced/10x18mmCharged.xml
Defs/Ammo/Advanced/12GaugeCharged.xml
Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/12x72mmCharged.xml
Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml
Defs/Ammo/Advanced/5x35mmCharged.xml
Defs/Ammo/Advanced/6x18mmCharged.xml
Defs/Ammo/Advanced/6x24mmCharged.xml
Defs/Ammo/Advanced/8x35mmCharged.xml
Defs/Ammo/Advanced/8x50mmCharged.xml

- Adjusted the projectile sizes for charge rounds so that bigger calibers look bigger in-game as well.
- Adjusted the `generateAllowChance` of Ion charge rounds so that they can spawn on AI pawns.
- Ion rounds are kinda the best charge rounds, in a world filled with mechs, you'd assume the empire pawns would carry them as commonly as other rounds or mercs for that matter. 0.5 chance at least brings the effective round into the mix which is helpful for AI pawns to deal with mechs a bit better.

Charge projectile size adjustments and Ion rounds for AI pawns

---

Defs/Ammo/Pistols/44Magnum.xml

- Added proper speed nodes to the high velocity .44 magnum rounds which were missing due to an oversight.

.44 Magnum high velocity ammo set bullet speed fix

---

Defs/Ammo/Advanced/12GaugeCharged.xml
Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/12x72mmCharged.xml
Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml
Defs/Ammo/Advanced/6x22mmCharged.xml
Defs/Ammo/HighCaliber/12.7x108mmSoviet.xml
Defs/Ammo/HighCaliber/50BMG.xml
Defs/Ammo/Rifle/4570Gov.xml
Defs/Ammo/Shotgun/12Gauge.xml
Defs/Ammo/Shotgun/20Gauge.xml
Defs/Ammo/Shotgun/23x75mmR.xml
Defs/Ammo/Shotgun/410Bore.xml

- Adjusted the aforementioned round's sharp and blunt armor penetration based on the spreadsheet.
- Corrected some values based on the spreadsheet.
- Adjusted some formulas in the spreadsheet so that it calculates recipes for shot shells correctly based on the number of pellets in the shell.
- The current stats used for the cartridge is based on the slower trapdoor versions of the round and not the standard ones which is adjusted as well.
- A slow and fat round should not have the same RHA penetration of .30-06 which is very fast and has a lot of energy behind it, gel data is not as reliable for pistol rounds and fat rifle rounds that have a lot of inertia. .45-70 has even less blunt …

.45-70 sharp armor penetration adjusted and some ammo housekeeping and corrections

---

Defs/ThingDefs_Misc/Weapons_Ranged.xml

- Decreased the flare gun's warmup time in an attempt to make it more viable since it does not require proper aiming, it's only a point at the sky and shoot type of gun.

Adjust flare gun's warmup time

---

Defs/BipodCategoryDefs/BipodCategories.xml
Patches/Combat Enthusiast's Collection/ThingDefs_Weapons.xml
Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_BoltAction.xml
Patches/Rimsenal Collection/Core/Weapons_JI_CE.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_Charge_CE.xml
Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_RSGuns_CE.xml
Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_RangedWeapons.xml
Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml

- Add the AMR bipods tag
- Made slight balance tweaks to some of the existing bipod tags
- AMRs are not DMRs so they should not receive the same benefits from the DMR bipods tag, they in-between DMRs and ATRs and the new tag resembles that

Add the AMR bipods tag, stat rebalances and housekeeping

---

Patches/Makeshift Melee Weapons/DetVisor_MakeshiftMelee.xml
SupportedThirdPartyMods.md

Patches the three melee weapons from the Makeshift Melee Weapons mod, based on patches for existing weapons.
The makeshift hammer is based on the VWE hammer, makeshift mace based on the mace, and the makeshift gladius based (somewhat) on the gladius, sans stab attack. Similar to base mod, the weapons have multiple iterations of the same attack, with varying damage, pen, and cooldown, to simulate imperfect and inconsistent strikes due to the poor balance and construction of the weapons.

Patch Makeshift Melee Weapons

---

Defs/SoundDefs/Shot_Weapons.xml
Patches/Apex - Rimworld Legends/ApexRimworldLegends_Weapons_Shotguns.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Kit's Gunpowder Weapons/KitsGunpowder_Guns.xml
Patches/Medieval Overhaul/MO_Weapons_Ranged.xml
Patches/More Vanilla Turrets/MVT_CE_Patch_Buildings_Security.xml
Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedIndustrial.xml
Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml

- Added a shotgun fire SoundDef that lacks the cocking clip for non-pump action shotguns. It's the same vanilla sound without the cocking bit.
- Some minor housekeeping
- Changed the auto and semi-auto shotgun fire sounds to the NoRack version
- Only pump-action shotguns should have the cocking sound, immersion stuff

Add the NoRack shotgun fire SoundDef

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml

- What is says on the tin.
- Vanilla turrets don't have a `castEdgeShadows` node.

Remove the shadow from manned turrets

---

Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- Fixed the `ShootingAccuracyTurret` patch of the Triple Rocket turret from VFE-Security
- The turret does not have a `ShootingAccuracyTurret` in the original mod making the replace patch fail, it had gone unnoticed because because of the "or" patches...

VFE-Security hotfix

---

Patches/Paniel the Automata/Ammo/Ammo_Paniel.xml
Patches/Paniel the Automata/ThingDefs_Buildings/Buildings_Turrets.xml
Patches/Paniel the Automata/ThingDefs_Misc/Paniel_Apparel.xml
Patches/Paniel the Automata/ThingDefs_Misc/Weapons.xml

Added patches for new equipment
Redid costs for the conventional weapons.
Charge rifle has been changed to fire 8x50 but higher recoil and smaller magazine with one by one reload, to differentiate more from LMG.
Launcher now, as per description, has a special hybrid launcher setup which allows it to fire both HV grenades and incendiary calibers.
Conventional weapons have had their costs equalized with regular equipment from other mods. Advanced weapons retain their other differences. This is to make up for the disparity with some of the equipment compared to other weapons, and the fact that they lose their alternate fire modes etc. that are present in vanilla

Paniel Equipment Update

---

Defs/ThingDefs_Items/Items_Resource_Ammo.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Expanded Materials - Metals/Ammo/Sabot.xml

- Made slight adjustments to the Molotovs.
- Fixed the error caused by the problematic patch for Expanded Materials - Metals mods.
- Brought Prometheum's cook-off properties more in line with Chemfuel.
- Both 0.5 and 0.9 explosion radius are the same, change the radius to 0.9 for consistency's sake.
- Molotovs having a 1x1 explosion do not need a 2 radius minimum range, a 3x3 box is big enough.
- Prometheum is volatile but a thicker and stickier substance in comparison with Chemfuel, similar to Molotovs which explode in a single tile radius and are a single Prometheum bottle with a rag, made Prometheum explode in a slightly smaller radius.

Adjust Molotov Cocktails and housekeeping

---

Defs/ThingDefs_Misc/Weapons_Ranged.xml
Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Adjusted the recoil value of the Fixed guns according to the new formula in the spreadsheet. The Fixed guns receive a x0.75 recoil multiplier instead of a flat -0.15 reduction.
- Added recoil values back to non-automatic guns for later use.
- https://docs.google.com/spreadsheets/d/1lbT0zzagCRPDJG4GctkeeoTsFCt3lYfM4SRnWt8ql-k/edit#gid=884124215
- The -0.15 recoil value bonus that fixed guns get is too low taking into account the recoil is not mitigated as much as sway via weapon handling stat and high recoil vales in return make turrets very inaccurate, it also makes sense that a properly mounted gun has much lower recoil than a handheld one.

Recoil value Adjustments

---

Source/CombatExtended/CombatExtended/AmmoUtility.cs
Source/CombatExtended/CombatExtended/SecondaryDamage.cs

- Increased secondary bomb damage's blunt AP factor from x2 to x2.5
- Increased normal bomb damage's blunt AP factor from x0.25 to x0.33
- Since blunt damage with lower than 50% armor penetration vs what the target's armor provides does no damage to armor, letting alone natural armor taking no damage from bomb damage sources, normal bomb damage and secondary bomb damage currently fall flat against anything resembling armor. Barring big explosion sources like something with 150 or so bomb damage that has enough blunt pen to do anything meaningful.
- Things relatively have higher blunt armor vs the bomb damage sources' blunt penetration than sharp pen vs sharp armor which results in bomb damage sources underperforming in comparison.

Increase bomb damage sources' blunt AP factor

---

Patches/Core/ThingDefs_Misc/Apparel_Hats.xml

- Removed the marine helmet's name patch which was left out in the previous marine armor PR.

Marine helmet name patch removal

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/More Vanilla Turrets/MVT_CE_Patch_Buildings_Security.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Artillery.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Turrets.xml
Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Buildings/TurretGatlingGun.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Manned.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- The continuation of #1888 for modded turrets.
- Fixed the 90mm Flak cannon's recoil values since it it was using a wrong velocity value for its 90mm shell.

Modded turret recoil adjustments

---

Patches/Erin's Chocobos/Erin_Chocobos.xml
SupportedThirdPartyMods.md

Patch Erin's Chocobos. The mod has only a single animal. Vanilla stats are similar to a slightly stronger, faster emu, and the patch stats reflect that.

Patch Erin's Chocobos

---

Defs/Ammo/Pistols/357Magnum.xml
Defs/Ammo/Shotgun/410Bore.xml

- Adds an ammoset for .410 shotgun shells. The ammo and projectile already exist and could conceivably be used in a .410 shotgun, so there's really no reason not to have it. Also includes a short barrel (lower velocity) version, since there's no reason not to.
- Adds an ammoset for .357/.38 special. Most .357 revolvers are capable of safely loading and firing both (though the opposite is not true). Shooters might use .38 special instead owing to the more manageable recoil and cheaper ammo cost. These aren't _really_ considerations that is a CE player is going to be concerned about, but it's still a nice option to include.
While the latter ammoset is functional in testing, the fact that the .38 spc and .357 mag ammo shares the same ammo types means that the ammo selector can't …

Add .410 bore and .38/.357 Ammo Sets

---

Defs/RecipeDefs/Recipes_Production.xml

- A temporary change to mech ammo recycle recipe to fix the red error created by the 66mm thermal bolts not existing in dev

Mech ammo recycle recipe error fix

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

- Fixed the tribal chiefs not spawning with ammo and shields
- Added one-handed melee weapons to melee chiefs so that they can spawn with melee shields, the one-handed to two-handed weapons they spawn with is generally around 2 to 1.

Properly fix the tribal chief issues

---

Defs/Ammo/Grenade/20x42mmGrenade.xml
Defs/Ammo/Grenade/25x40mmGrenade.xml
Defs/Stats/Stats_Weapons_Ranged.xml
Languages/English/Keyed/Stats.xml
Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_Magazine.cs

20x42mm and 25x40mm airburst grenades.
Re-added single line magazine size / reload time stat display on weapons stats window
- Closes #1843 

Magazine stats display and 20/25mm airburst grenades

---

Defs/Ammo/HighCaliber/20x128mmOerlikon.xml
Defs/Ammo/HighCaliber/20x138mmB.xml
Defs/Ammo/HighCaliber/30x113mmB.xml
Defs/Ammo/HighCaliber/50BMG.xml

- Added two new 30x113mmB autocannon ammo.
- Adjusted armor penetration of the 20x138mmB rounds and fixed the blunt armor penetration of the 20x128mm Oerlikon AP round.
- Fixed the .50 BMG HE round labels.

Add 30x113mmB autocannon ammo and other ammo tweaks

---

Languages/English/Keyed/ModMenu.xml
Languages/English/Keyed/TextMotes.xml
Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Source/CombatExtended/CombatExtended/Settings.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs

- Removes the mod option to limit parry damage
- Pawns will sometimes deflect attacks without damaging their weapon or shield.  Same chance as a riposte.
- Closes #1866 
Skilled pawns in melee should be able to parry attacks without damaging their weapons.
Unskilled pawns who manage to stop an attack are likely to do so by making the attack strike their weapon.
Leave the parry damage limited - makes some junk weapons too tough

Fix parrying

---

Defs/Stats/Stats_Pawns_Combat.xml
Patches/Core/Stats/Stats.xml

- What it says on the tin, aiming time is impacted by skill and health stats and ranges from x1.25 at zero skill with no higher cap to x0.75 (via skills) and x0.5 at the minimum after stacking health stat bonuses. Trigger-happy and Careful shooter pawns are still balanced even at higher and lower end of shooting skill as well.
- Skilled and enhanced pawns should aim faster.

Make aiming time affected by skill and health stats

---

Defs/Drugs/Psychite_Psycho.xml
Defs/PawnKindDefs/PawnKinds_CE.xml
Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

- Added a new crude combat enhancing drug called "Psycho".
- Enable high tier tribal pawns to carry combat enhancing drugs.
- Contributes towards #1526 
- A new combat drug that is readily available, relatively expensive to make but cheap to sell. Good stat bonuses but very bad side-effects. Highly addictive with relatively high chance of overdose, a last resort option for the player colony but a combat boost for high tier tribal pawns.

Add a new combat drug called Psycho

---

About/About.xml
About/Manifest.xml
Defs/Ammo/HighCaliber/14.5x114mmSoviet.xml
Defs/Ammo/Medieval/CannonBall.xml
Defs/Ammo/Shell/155mmHowitzer.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Kurin Deluxe Patch/Ammo/Ammo_Kurin.xml
Patches/Kurin Deluxe Patch/ScenarioDef/Scenarios_DRNTF.xml
Patches/Kurin Deluxe Patch/ThingDefs_Misc/DRNTF_Apparel.xml
Patches/Kurin Deluxe Patch/ThingDefs_Misc/DRNTF_Weapon.xml
Patches/Kurin Deluxe Patch/ThingDefs_Races/Race_DRNTF.xml
SupportedThirdPartyMods.md

Some assorted tweaks and adjustments for the 4.9 release.
- Adjust the mass and bulk of the molotov to be appropriate for a 12 oz glass bottle. Also adjust the radius based on an appropriate amount of filler.
- Add patch for Kurin Deluxe edition. Patch originally from #1820, plus a few adjustments and fixes that PR needed. Since it was on the patch author's fork, it was more expedient to move over to work on here.
- Increment version number from 4.8 to 4.9.
- Increase Cannon Ball bursting shell damage and frag count; I had miscalculated the filler volume on the sheet the first time.
- Adjusted the 155mm HE shells according to the sheet as well.

4.9 adjustments

---

Defs/Ammo/Rifle/127x55mm.xml
Patches/Nearmare Race/ThingDefs_Misc/Weapons.xml
Patches/Rambo Weapons Pack/RamboWeaponsPack_assaultrifles.xml
Patches/Rambo Weapons Pack/RamboWeaponsPack_sniperrifles.xml

- Updated 12.7x55mm's naming convention to prevent confusion, removed the AR bit to make the ammo type uniform

Update 12.7x55mm's naming convention

---

Patches/Rim-Hivers!/New_Hivers.xml

- Add will and resistance stats to Hiver pawnkinds added by CE.

Add will/resistance to Rim=Hivers pawnkinds

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

- Remove changes CE made to the skill requirements of the Stranger in Black and Ancient Soldiers.
- Reduce Ancient Soldier ballistic shield spawn rate from 0.9 to 0.5.

Remove Pawnkind Skill Patches

---

.github/workflows/main.yml
.github/workflows/pullrequest.yml

Run builds for PRs targeting the 1.4 branch & pushes for the 1.4 branch. Also bump some third-party workflow versions while we're at it.

Enable build actions for the 1.4 branch

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

Projectiles are teleported to the center of their target, causing explosions from projectiles hitting things to fail to generate.
Teleportation is bad in general.
Explosives fail if they aren't on the surface of the target.
Break explosives doing direct damage and return them to exploding on the floor no matter what they hit.

Don't magically teleport projectiles to the center of their target

---

Defs/ApparelAutoPatcherPresets/Helmets.xml
Defs/ApparelAutoPatcherPresets/TorsoSets.xml
Defs/ApparelAutoPatcherPresets/Vests.xml

- Added new apparel autopatcher presets for leather jackets, light vests, light helmets, hats, and other items of non-armored clothing.
- Reduced the wornbulk of the preset helmet from 4 to 1. This makes it consistent with the wornBulk of patched modern/industrial helmets.
The apparel autopatcher had a very limited number of templates, and didn't necessarily cover items with lower armor values, such as medieval-tier gear or heavier non-armored items like heavy jackets. Adding a few more improves its consistency and improves the player's experience by applying autopatched stats that are more in-line with their patched equivalents. 

Add a few more Apparel Autopatcher presets.

---

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml

- Adjusted our skill range patches after the changes in 1.4.3520
- Merc pawns received a proper skill range value and the ancient soldiers got a shooting skill range, made the adjustments accordingly.

Adjust skill ranges for 1.4

---

Defs/Ammo/Pistols/22LR.xml
Defs/Ammo/Pistols/357SIG.xml
Defs/Ammo/Pistols/38Special.xml
Defs/Ammo/Pistols/45ACP.xml
Defs/Ammo/Pistols/45Colt.xml
Defs/Ammo/Pistols/762x25mmTokarev.xml
Defs/Ammo/Pistols/762x38mmR.xml
Defs/Ammo/Pistols/763x25mmMauser.xml
Defs/Ammo/Rifle/277Fury.xml
Defs/Ammo/Rifle/300AACBlackout.xml
Defs/Ammo/Rifle/303British.xml
Defs/Ammo/Rifle/44-40Winchester.xml
Defs/Ammo/Rifle/4570Gov.xml
Defs/Ammo/Rifle/762x39mmSoviet.xml

- What it says on the tin, adjusted various pistol cartridge sharp AP values.
- Decreased the sharp armor penetration of .277 Fury by 0.5 for the FMJ rounds and adjusted the rest accordingly since the cartridge was overtuned.
- Did the same as above for 7.62x39, .300 BO and .303 and a couple more cartridges have been rebalanced.
- Adjusted .22LR's sharp AP values since the sheet is using rifle barrel figures instead of pistol barrel data, kept the rest of the values intact to not make te cartridge absolutely garbage.
- Added the .45 ACP/.410 Bore ammo set to be used by the S&W Governor in CE Guns.
- While adjusting the .45 Colt and ACP cartridges, I noticed that there are …

Various ammo adjustments

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- Buffed the autocannon turret in possible areas according to the gun spreadsheet.
- Removed certain redundant nodes that the base game calculates on its own.
https://docs.google.com/spreadsheets/d/1lbT0zzagCRPDJG4GctkeeoTsFCt3lYfM4SRnWt8ql-k/edit#gid=1573763037
- The autocannon being a 2x2 building was not properly superior to the CE's Heavy Turret. make certain adjustments so that it is a viable option to use considering the associated cost that comes with it.

Various turret adjustments

---

Source/CombatExtended/CombatExtended/DefOfs/CE_ThingDefOf.cs
Source/CombatExtended/CombatExtended/LetterTracker.cs

Fix mechanoid "Strange Signals" letter referencing obsolete def
Write function to find mechanoid with the highest armor value, then display that in the letter.
This would handle mods/DLCs that add mechs with more armor than a standard centipede.
(well there's one less than before this patch)

Patch mechanoid warning letter

---

Defs/ThingDefs_Buildings/Buildings_Defenses.xml

- Removed the `constructEffect` and `repairEffect` from the building since it is automatically handled by the game based on the material the building is made out of.
- 

Hotfix for the barbed wire

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Changed the Bren's mag size from 100 to 50 rounds to make it resemble its texture properly.

Tweak the Bren's magazine size

---

Source/CombatExtended/CombatExtended/SuppressionUtility.cs

- Made breaking line of sight be more important for cover;
- Replaced line of sight check for distance multiplication with a direct-path with all stand-able terrain check;
- Made the aforementioned distance multiplier smaller.
- Should (hopefully) fix https://discord.com/channels/278818534069501953/278818534069501953/1029648986757410826
- Makes pawns more likely to run back into cover instead of out;
- Embrasures were able to pass the line of sight check, although a pawn couldn't directly path trough them;
- Makes pawns consider moving around walls more often while under suppression, although pawn may path around large walls more often.

Adjust suppression behavior

---

Defs/Ammo/Grenade/20x42mmGrenade.xml
Defs/Ammo/Grenade/25x40mmGrenade.xml
Defs/Ammo/Grenade/25x59mmGrenade.xml
Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/35x32mmSRGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Grenade/40x47mmGrenade.xml
Defs/Ammo/Grenade/40x53mmGrenade.xml
Defs/Ammo/Grenade/40x53mmVOG25Grenade.xml
Defs/Ammo/Grenade/50mmGS50Grenade.xml
Defs/Ammo/Grenade/83mmPIATGrenade.xml

- What it says on the tin, gave them the proper `LauncherShot` projectile texture.
- Launched grenades are not beeg boolets.

Give proper projectile textures to launched grenades

---

Defs/ThingDefs_Misc/Gas_Various.xml
Source/CombatExtended/CombatExtended/Defs/GasPropertiesCE.cs

Black smoke uses the pre-1.4 object gas system, which is still present in core, but the BaseGas def has been removed along with some fields from GasProperties. Augment the smoke def with missing data that used to be in the base def, and introduce a new CE-specific gas property class to store the fields removed from core GasProperties.
This does not yet fix the interaction of combat with black smoke - we should do that in a followup patch.

Fix black smoke rendering and propagation

---

Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs
Source/CombatExtended/CombatExtended/Comps/CompProperties_ExplosiveCE.cs

Add support for the postExplosionGasType XML tag in CompProperties_ExplosiveCE, which allows our explosive projectiles to spawn a built-in gas type on detonation. We seem to be already using it in XML, the code just was not ready to use it.

Support spawning vanilla gases from explosive projectile detonation

---

Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs

Don't display the melee targeting gizmo for pawns that are not colonists or are otherwise not under the player's control (e.g. are in an aggressive mental state).

Don't show melee targeting gizmo for pawns not controlled by the player

---

Defs/Ammo/Rifle/5x100mmCaseless.xml

- Added the `MayRequire="Ludeon.RimWorld.Biotech"`  to the toxic version of the 5x100mm ammo.

Make 5x100mm Toxic ammo Biotech-only

---

Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

Biotech's new Centurion/Legionary mechs use shields with finite hitpoints that break if they take enough damage. Our custom intercept logic in ProjectileCE must be updated to handle these shields.
Solve this by just applying the appropriate vanilla logic - applying damage from the projectile to the shield and breaking it if it reaches zero hitpoints. For this to work, move the definition of DamageAmount from BulletCE to ProjectileCE so that we can obtain the scaled damage amount in the interception logic.

Fix new Centurion/Legionary shields

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs

ProjectileCE: Fix duplicate DamageAmount property after merge

---

Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- Changed the burst shot count of the Heavy and Autocannon turrets from 10 to 5 rounds.
- Increased the magazine capacity of the Medium turret from 60 to 80 rounds.
- Tweaked the Double Autocannon turret from VFE-Security to bring it more in line with the vanilla turret.

Turret tweaks

---

Source/CombatExtended/CombatExtended/Gizmos/GizmoAmmoStatus.cs
Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs

There are a few warnings in logs about texture-type fields when dev mode is active. To get rid of the noise, switch GizmoAmmoStatus to initialize its textures on startup with [StaticConstructorOnStartup], and use a CachedTexture instead of a raw texture in ITab_Inventory (which is what vanilla ITabs do).

Reduce noise in logs when dev mode is active

---

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/CombatExtended/SecondaryDamage.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
Source/CombatExtended/Harmony/Harmony_StunHandler.cs

Ensure pawns won't be considered guilty when drafted and ordered to
attack a friendly pawn. This prevents an exploit where players
could draft an undesired pawn and have them punch a colonist or colony
animal so that they'd become guilty & be banished with a lesser impact
on the colony.
Both melee and ranged attacks are covered.

Fix drafted pawns becoming guilty when drafted & ordered to attack 

---

About/About.xml
Patches/Vanilla Factions Expanded - Classical/ThingDefs_Shields.xml
Patches/Vanilla Factions Expanded - Classical/ThingDefs_WeaponsRanged.xml

- Add a dummy parent for the javelin, so it doesn't need to be loaded after Combat Extended. Remove the load order requirement.
- Remove the OversizedWeapon comp from the VFE:C melee shield, since CE treats shields as apparel, not weapons.
- A dummy parent is the cleanest way to implement it, short of just creating a duplicate of the actual parent it's using.

Fix VFE - Classical Patch

---

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Changed the market value of the charge lance from 2200 to 1400, same as other mechanoid weapons.
- Tweaked the recipe of the Minigun based on the values from the Gun spreadsheet.

Minigun and Charge Lance consistency check

---

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Heavy.xml
Defs/Ammo/Advanced/66mmThermalBolt.xml

- Tweaked the armor values of the Tunneler mech to a milder value of 24/60 sharp/blunt rating.
- Lowered the gravity factor of the 66mm Bolts to 10, the previous value was for testing purposes and was not changed.

Biotech balance pass

---

Biotech/Patches/PawnKindDefs_Humanlike/PawnKinds_Waster.xml

- Increase the number of grenades the Tox Grenadier can spawn with. Their parent is unpatched and only receives the default magazine count, so they could do with carrying a few more.

Increase Tox Grenadier Ammo Count

---

Defs/Ammo/Advanced/66mmThermalBolt.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml

- Adds the Bolt Projector for the Pikeman when Biotech is disabled to keep the niche of an indirect fire mech for non-DLC users
- Reduced the gravity factor of 6mm thermal bolts as they were too fast to reliably maneuver around and retaliate against, the new values should still keep a visible arc for the player to see
- With the TBP being moved to the Legionary it leaves the vanilla mech roster lacking in an indirect fire option and has both Lancers and Pikemen take up the role of a single shot precision rifle
- TBP's intended use is to be a deterrent of static positions and to force the player to reposition their pawns, having too fast projectiles detracts from this niche by not allowing the player to reliably retaliate and makes it significantly harder to fight up close where the …

Vanilla Pikeman adjustments and 66mm tweaks

---

Source/CombatExtended/Harmony/Compatibility/Harmony_AlienRace.cs
Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs

Fix our HAR compat patch for 1.4 by updating the HAR method that will be called within our pawn rendering compat hook. GetHairMesh() was replaced by GetHumanlikeHeadSetForPawnHelper() on the HAR side.

Update HAR compat patch

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Source/CombatExtended/Harmony/Harmony_CompReloadable.cs

For consistency with other related gizmos.

Hide ammo status and armor reload gizmos for non-colonist pawns

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs

This is the same style used for the pods that drop the cluster itself.

Use mechanoid faction style for mech cluster ammo drop pods

---

Biotech/Patches/Misc/Ammo_Generic.xml
Defs/Ammo/Advanced/12x64mmCharged.xml
Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml
Defs/Ammo/Advanced/164x284mmDemoShell.xml
Defs/Ammo/Advanced/5x35mmCharged.xml
Defs/Ammo/Advanced/66mmThermalBolt.xml
Defs/Ammo/Advanced/6x22mmCharged.xml
Defs/Ammo/Advanced/80x256mmFuelCell.xml
Defs/Ammo/GENERIC/Charged.xml
Defs/Ammo/GENERIC/Mech.xml
Defs/RecipeDefs/Recipes_Production.xml

- Add two new generic ammo sets; Mech Charged and Mech Shells and assign them to appropriate mechanoid ammo. These are non-craftable, but sellable, like normal mech ammo.
- With Biotech, patch the mech ammo to use either an appropriate generic charged ammo or (for shells) not use a generic at all.
- Made the capitalization of the generic charged heavy label consistent.
- Added the new generic mech ammo types to the recycling recipes.
- Changed the `ammoClass` of the mech demo shell to incendiary, so it works with the Mech Shell generic ammo.
With the introduction of player-controlled mechs in Biotech, the player now needs access to mechanoid ammo. As such, it makes sense to plug them into the Generic Ammo system using the existing spacer charged ammo. Rather than creating a full new set …

Add Generic Ammo to Mech Ammo

---

Biotech/Patches/HediffDefs/Hediffs_Mechanitor.xml

- Patch the energy shield capacity of the Remote Shielder Implant ability that had gone unnoticed by 50% like other energy shields in CE.
- As per the uploaded image, the shield capacity will be increased, this patch is made with that in mind.

Remote Shielder Implant patch

---

Biotech/Patches/Bodies/BodyParts_Mechanoid.xml
Biotech/Patches/DamageDefs/Damages_Misc.xml
Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Medium.xml
Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Turret.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Heavy.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Light.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_SuperHeavy.xml
Defs/Ammo/Pistols/9x19mmPara.xml
Defs/Ammo/Rifle/5x100mmCaseless.xml
Patches/Core/Bodies/BodyParts_Mechanoid.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml
Patches/MoreMechanoids/ThingDefs_Races/Races_Mechanoid.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Races/RM_Races_Machines.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Races/RM_Races_Mechanoids.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml

- Removed the HP scaling patches of mechanoid pawns.
- Adjusted Centipedes' bodyring HP.
- Patches the small mechanoid leg and foot HP.
- Rebalanced the mounted HCB turret on super heavy mechs.
- Tweaked the Tunneler's melee tools based on a heavier but slower variant of Power Claws.
- Switched the Minigun to Snapshot default fire mode.
- Tweaked the Graser to fire in 10 burst counts with 10 ticks between each burst to make it hit stuff more reliably, also increased its Beam damageDef to deal 15 damage instead of 10 with 0.25 Heat AP to make it penetrate normal clothing more easily.
- Updated the stats of the Apocriton mech and its toxic needle gun according to the latest RW ver 1.4.3546 build, it has super heavy mech tier armor with higher blunt armor and its gun deals more damage, opted …

Mechanoid HP scaling tweaks, mech related tweaks and housekeeping

---

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Heavy.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Light.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml
Biotech/Patches/ThingDefs_Races/Races_Mechanoids_SuperHeavy.xml
Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml

- Removed the bodySize patches of mechanoid pawns and adjusted their carry bulk and weight capacities accordingly.
- Adjusted the vanilla and DLC mechanoids' melee chance stats based on the updated values of the Animal Spreadsheet, they were outdated in the sheet to begin with.
- Gave the two super heavy mechs that lacked carry bulk and mass patches an increase capacity and also shooting accuracy stats.
- Some minor housekeeping.
- https://docs.google.com/spreadsheets/d/1Q7MXo-3qcZtTslZ3q4PS89jKLArD7k_RHLo_OqSeeHA/edit#gid=1020770989
- Centipedes have a bodySize of 3.0 in vanilla now and since the bodySize node does nothing in CE apart from melee chance stats, I opted for removing the patches and update the melee stats to keep things consistent and cleaner.
- All of the colony mechs can …

Mech melee chance stat and bodySize adjustments

---

Defs/HediffDefs/Hediffs_CE.xml

- Remove the `Prometheum-Soaked` hediff on death. Your enemies will no longer burn for eternity in the afterlife, and resurrected pawns will not burst into flames.

Remove Prometheum-Soaked Hediff on Death

---

Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml
Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-HeavyWeapons.xml
Patches/Vanilla Weapons Expanded - Tribal/Ranged_Neolithic.xml

Resolve some other patch issues.
- Make throwing shards non-smeltable.
- Update a VFE: Mech artillery foundry reference to the update tar shell defName.
- Remove operations from the Frontier + Heavy Weapons patch that are no longer needed.

Vanilla Expanded 1.4 Patch Fixes

---

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml
Defs/Ammo/Advanced/PlasmaCellHeavy.xml
Defs/Ammo/Advanced/PlasmaCellPistol.xml
Defs/Ammo/Advanced/PlasmaCellRifle.xml

- Add some temporary conditional checks for Apoticon armor nodes. The current patch has a `Replace` operation that works in the current unstable build, but throws an error in the stable build. This check safely prevents that error. The added operation can be removed after stable updates, but will not cause any trouble when it does.
- Made sure that plasma projectiles don't shake the screen upon impact.
- Housekeeping.

Add Conditional Checks for Stable Build, Housekeeping

---

Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Apparel_Industrial.xml
Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Headgear_Industrial.xml

- Add the default bulk to a few pieces of headgear so the autopatch doesn't try to apply presents.
- Patch the surgical mask, even though the armor values don't really change.

Fix VAE headgear bulk for the autopatcher

---

Biotech/Patches/ThingDefs_Misc/Apparel_Headgear.xml
Defs/ThingDefs_Misc/Apparel_Headgear.xml

- Adjust Biotech gas mask:
- Set to the same body parts as the CE gas mask.
- Remove node that made it render over top of other apparel.
- Adjust plate helm layers to match other closed, full-head helmets like the recon helmet. Can no longer wear hats/gas masks beneath it. 

Headgear Apparel Layer Fixes

---

Patches/Core/ThingDefs_Misc/Apparel_Hats.xml

- Patch the now base game's Hood headgear's `StuffEffectMultiplierArmor` which was somehow left unpatched.

Patch the Hood headgear

---

Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs

Changed `PickUp` to `PickUpOne` in the FloatMenuOption .cs file, allowing it to connect with the existing `PickUpOne` translation key in base RW. Given the more complete nature of the base game translations, it makes more sense to use those rather than CE's where possible.
With the 1.3 to 1.4 update, in the base game translation keys `<PickUp>Pick up {1_label}</PickUp>` became `<PickUpOne>Pick up {1_labelShort} x1</PickUpOne>`.
Could just use the `CE_PickUp` translation key, but it's preferable to use base RW's translation keys  where possible instead of CE's translations.

Fix 'PickUp' Translation Key Error

---

About/About.xml
Biotech/Patches/ThingDefs_Misc/Apparel_Headgear.xml
Biotech/Patches/ThingDefs_Misc/Apparel_Various.xml
Defs/Ammo/Shotgun/23x75mmR.xml
Defs/HediffDefs/Hediffs_CE.xml
Defs/ThingDefs_Misc/Apparel_Headgear.xml
Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml
Patches/Core/HediffDefs/Hediffs_Local_AddedParts.xml
Patches/EPOE Forked Royalty DLC expansion/Bionics_Patch.xml
Patches/EPOE Forked/Bionics_Patch.xml
Patches/K4G Rimworld War 2/ThingDefs_Misc/WW2_Apparel.xml
Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_Ammo_Mech.xml
Royalty/Patches/HeDiffDefs/Hediffs_Implants.xml

- Removed the load order rule for Alpha Animals and Mythology since they were no longer needed.
- Adjusted some damage values in the Alpha Animals projectile patches.
- Changed the projectile of the 23mm buckshot from 000 to 0000 pellets and adjusted the necessary values accordingly.
- Fixed a typo in the Reinforced Mechanoids patch.
- Sorted out the inheritance issues with Mechanitor gear that was causing wrong stats to be assigned to wrong items.
- Patched the recipes of the Mechlord set.
- Tweaked the Gas Mask hediff to reflect a more realistic effect of the wearer and changed its tag to cover more pawnKinds, closer to what the Biotech gas mask tried to do.
- Removed the `bodyPartGroups` patch of the Biotech gas mask as it was indirectly causing issues.
- Added the missing …

Misc tweaks and housekeeping

---

Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs

Adjust the faction check to be null-safe, which is also consistent with everywhere else the game is checking faction membership.

Fix possible NRE in CompFireModes

---

Biotech/Patches/PawnKindDefs_Humanlike/PawnKinds_Impid.xml
Biotech/Patches/PawnKindDefs_Humanlike/PawnKinds_Waster.xml
Biotech/Patches/Weapons/RangedIndustrial.xml
Defs/Ammo/Neolithic/Arrows.xml
Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Patches/RadWorld/PawnKinds_RadWorld.xml
Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs

- Patches for new Tox and Imp pawnkinds. Statistically the same as the base game pawnkinds, but restricted to an ammo appropriate to their specific faction.
- Increased the magazine count for `Mercenary_Heavy,` as the current count can leave the pawn with only a few rounds for their grenade launcher.
- Remove the flamebow, as it's no longer needed since pawns can spawn with a specific kind of ammo.
- Fix error when pawn kind using forcedAmmoCategory attempted to spawn with weapon that lacked an ammodef.
- Fix ammo generateAllowChance of 0 blocking forcedAmmoCategory. Hopefully.
**Issues:**

Patch Biotech Pawnkinds and Adjust forcedAmmoClass

---

Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_Ranged_CE.xml

Change the xpath targets for the smoke grenade removal, and update the projectile one to thingDef rather than Thingdef, which might be part of it
Texture path is pretty easy to update and unlikely to change given the author's previous history with rimsenal vanilla.
Not likely to overlap with anything more than rimsenal vanilla itself will.

Fix Rimsenal smoke grenade removal

---

Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml

- Added some missing nodes to the base Advanced Mechanoid race patch.
- Tweaked Advanced Mechanoids to have 0.5 heat armor instead of full 2.0.
- Giving the advanced mechs full immunity to heat armor is a hard counter to AP-I ammo which is already nerfed against pawns with high armor (this change was made after the initial patch for VFE-Mechs was made). They are already immune to small caliber AP-I roudns but them being completely immune to any burn damage source no matter the intensity is kinda unbalanced. Giving them 50% heat armor instead of 200% helps with their armor value being currently too overtuned.

VFE Mechanoids tweaks

---

Biotech/Patches/DamageDefs/Damages_Misc.xml

- Changed the `AcidBurn` damage type to be impacted by Heat armor instead of Sharp.
- Made sure that Vaporize damage type has enough damage since pawns in CE have a bit more HP and is properly calculated against Heat armor.
- Since `AcidBurn` is inheriting from Flame damage and has all the associated mod extensions with it and it is also the anti-mechanoid version of the fire spray in vanilla, changed its armorCategory to Heat so that it can deal damage against armor with its 80% Heat AP but be countered by heat armor so that it can damage mechs as well as normal pawns but not be countered by 0.8mm of sharp armor.
- Keep the `AcidBurn` armorCategory as Sharp and increase its sharp AP which in this case it'd be useless against mechs that in return is contrary to its original purpose unless …

Biotech DamageDefs tweak

---

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs

A similar change is probably warranted for reloading turrets.
Pawns use the pickup-count job instead of the pickup job, so up to 10 pawns can target a single stack of ammo (or other loadout things) at a time.
#2040 
Reduces the need to split ammo into smaller stacks.

Allow multiple pawns to reserve and pickup ammo from the same stack.

---

Defs/Ammo/Advanced/12x72mmCharged.xml
Defs/Ammo/Advanced/20x105mmCharged.xml

- We lacked a charged autocannon round which might become useful later down the line after the Vehicle Framework is released.

Add 20x105mm charged autocannon ammo

---

Patches/Censored Armory/30mm Rifle Grenade.xml
Patches/Censored Armory/37x249mmR.xml
Patches/Censored Armory/75cm leIG18.xml
Patches/Censored Armory/75x714mmR.xml
Patches/Censored Armory/80mm Panzerfaust.xml
Patches/Censored Armory/Recipes_Grenades.xml
Patches/Censored Armory/Weapons_Guns.xml
Patches/Censored Armory/Weapons_Melee.xml
Patches/Censored Armory/Weapons_Turrets.xml
Patches/Kaiser Armory/105x155mmR.xml
Patches/Kaiser Armory/77x230mmR.xml
Patches/Kaiser Armory/KaiserArmory_GrenadeRecipe.xml
Patches/Kaiser Armory/KaiserArmory_Guns.xml
Patches/Kaiser Armory/KaiserArmory_Melee.xml
Patches/Kaiser Armory/KaiserArmory_Turrets.xml
Patches/Tsar Armory/TsarArmory_Guns.xml
Patches/Tsar Armory/TsarArmory_Recipes.xml
Patches/Tsar Armory/TsarArmory_Turrets.xml

- Updated the old mod names to their new version. Mod couldn't be patched as it was looking for the wrong mod. Turns out having the game version in the name is a bad idea for a game that is still receiving updates.

Update PatchOperationFindMod - Censored Armory, Kaiser Armory, Tsar Armory

---

Defs/Ammo/Shotgun/23x75mmR.xml

- What it says on the tin, 0000 projectiles were given less mass than what they should have been.

Fix a miscalculation in 23x75mmR buckshot shells

---

Defs/ThingDefs_Buildings/Buildings_Production.xml

- Changed the research prerequisite of the Ammo Bench to Gunsmithing. It does not make sense for pawns to craft ammo before knowing what firearms are.

Ammo bench research prerequisite

---

About/About.xml

Fixes issues where sometimes AA+AM would load after CE causing patching failures for combination of mods. AA+AM add defs via patches which may cause issue with the patching system if it requests finding another mod.
Load After rules for Alpha animals and Alpha mythology
If for whatever reason you had AA, VFE-M, and CE together and AA is after CE, CE will not be able to find the alpha animals slurrymaster and cause a patch failure. Same thing with Alpha mythology and a dog said.

Places load after rules for AA and AM

---

Source/CombatExtended/Harmony/Harmony_VerbProperties.cs

1.4 introduced multi-threaded loading, which means multiple threads can try to check if a VerbProperties instance is one of ours.  When this happens, it can try to write to the cache from 2 threads at once, corrupting the internal state of the dictionary, or throwing an array out of bounds error.  This adds a lock on writing, which will marginally reduce the performance gain from the cache on first access, but should not impact performance beyond first use of each verb.
Disable the cache.
Make the cache smartly multithread aware.
Build the whole cache in a single thread early in game load.

Use lock on verb properties cache when writing to it.

---

Source/ArtilleryCompat/ArtilleryCompat.csproj
Source/BetterTurretsCompat/BetterTurretsCompat.csproj
Source/CombatExtended/CombatExtended.csproj
Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Source/Loader/Loader.csproj
Source/MiscTurretsCompat/MiscTurretsCompat.csproj
Source/MultiplayerCompat/MultiplayerCompat.csproj

This fixes an error with the inventory tab:
```
Exception filling tab CombatExtended.ITab_Inventory: System.MissingMethodException: bool RimWorld.FoodUtility.WillEat(Verse.Pawn,Verse.Thing,Verse.Pawn,bool)
at CombatExtended.ITab_Inventory.FillTab () [0x005ec] in <b180898554564e0aaf06e6075ec6f8a7>:0
at Verse.InspectTabBase+<>c__DisplayClass16_0.<DoTabGUI>b__0 () [0x00039] in <6f2a3e32809145e28b5fe7238305584e>:0
```

Update RimWorld reference assemblies to 1.4.3555

---

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml

- Enabled the Apocriton and Tesseron mech to seek cover.
- Tesseron is in the same class as Lancer and Apocriton is described as intelligent so it fits.

Medium mech Cover-Seeking behavior

---

Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Ammo_Feral.xml
Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_RangedWeapons.xml

Fixed incorrect ammodef for default
Added mod specific tag since at the moment it's not a generic but someone else may want to do the same/may want to implement it as a generic for whatever reason.
Can intergrate it, and potentially other twinned ammosetdefs into the base ammo if so desired.

Feral Twin 9mm Fixes

---

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs

- Add (god mode only) gizmos to instantly empty and refill the magazine of any weapon with CompAmmoUser
- Closes https://github.com/CombatExtended-Continued/CombatExtended/issues/2026
- Expedites testing of weapons without having to separately spawn in ammo, and then waiting for pawns to reload
- Toggling the ammo system on/off in mod settings, which is not recommended for existing savegames

Add god mode gizmos for emptying and refilling CompAmmoUser

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
Defs/ThingDefs_Misc/Weapons_Turrets.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml
Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml
Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml
Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml

- Updated vanilla turret cooldown times based on the CE's 1 second time for autoturrets.
- Adjusted manned turret cooldown times to be the same as the gun that is mounted on them.
- Ran a consistency check on mechanoid turrets.
- https://discord.com/channels/278818534069501953/322827713335394304/1044536333470814278
- https://discord.com/channels/278818534069501953/322827713335394304/1044699966532227082

Turret cooldown time tweaks

---

Patches/Vanilla Weapons Expanded - Tribal/Ranged_Neolithic.xml

- Gave melee tools to the Fire Bomb and Sling from VWE-Tribal.
- Closes #2105 

Fix VWE-Tribal melee tools

---

Defs/Ammo/Shell/81mmMortar.xml

- What it says on the tin, Antigrain shells' `thingSetMakerTags` has been changed to `RewardStandardCore` in vanilla hence the need for an update.

Update the Antigrain shells' reward tag

---

Patches/MiscTurrets/Patch_Ammo.xml
Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Ammo.xml
Patches/SYR Naga/Patch_Ammo_44Magnum_Naga.xml
Patches/Star Wars - Factions/PlasmaGasCartridge.xml

- Fixed some ammo texture directories that were still directing towards the old charge ammo textures.

Fix some ammo texture directories

---

Patches/Core/TraitDefs/Traits_Singular.xml

- Changed the incoming damage factor of the Tough trait from x0.75 to x0.66.
- Since it is intended for the Tough trait to be stronger than the Robust gene, changing the bonus to x0.66 would be a bit more balanced while keeping it not absurd like its original value.

Readjust the Tough trait

---

Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml

- Adjusted the military turret's range,burst shot count from 20 to 12, and its magazine capacity from 200 to 120.
- Adjusted the sentry turret's burst shot count from 50 to 25, and its magazine capacity from 500 to 250.
- The changes are made to make the military turret which is a double mini-turret to be consistent with autocannon vs double autocannon. And the sentry turret is changed to resemble the handheld minigun.

Rebalance the VFE-Security Military and Sentry turret

---

Defs/Ammo/Rifle/277Fury.xml

- What it says on the tin, it should be 135 grains not ~139 grains.

Fix .277 Fury's projectile mass

---

Patches/Vanilla Psycasts Expanded/ThingDefs/Projectile_Tweaks.xml

- Tweaked the damage amount of Bolt ability of the Staticlord tree.
- Since the aforementioned ability is using the default damage values of the damage type used, it is dealing the default 50 damage of EMP damage type which resulted in it being very overpowered in CE.

VE Psycasts Staticlord Bolt ability tweak

---

Patches/RH2 Faction - The Rangers/Rangers_CE_Patch_Apparel.xml

- What it says on the tin. Fixed an error and updated armor values.
- The ranger armor set is based on Marine gear not Recon.

Update and fix RH2 Rangers apparel patch

---

Patches/Alpha Animals/AA_VPE/AbilityDefs/AbilityDefs_Patch.xml

- Made the necessary tweaks to make the projectile launched by the ability to be consistent with the one launched by the Black Hive insectoids.

Tweak the AA's Herald poison bolt ability

---

Defs/ThingDefs_Buildings/Buildings_Defenses.xml

Just fixing the embrasure def not pointing to the different menu icons depending on stuff, the icons were already present on the repo.

change embrasure icon with stuff

---

Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs

Only try to create a new "run for cover" job if the pawn is not currently running for cover. Currently, we create it every time when a pawn is suppressed and is above the threshold, but discard it anyways if they're already running for cover.
When profiling the immediate period of a doomsday explosion in a raid, this reduced the impact of AddSuppression() from ~40% to ~1.3.%.

Optimize running from cover from suppression

---

Patches/RH2 Faction - VOID/Monsters/Races.xml
Patches/RH2 Faction - VOID/Monsters/Races_Evolved.xml
Patches/RH2 Faction - VOID/PawnKindDefs_Humanlike/PawnKinds.xml

- Decreased the armor value of the monsters by 50% and adjusted their CombatPower.
- Patched and tripled the CombatPower of the VOID PawnKinds.
- The mod is supposed to be absurd but not unbeatable, made adjustments to tone stuff down for CE ecosystem as especially the CombatPower of pawns from the mod was very very low.

Nerf/rebalance the VOID bois

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_BunkerBuster.cs

- Added a property to bunker buster projectiles' explosion, so that they can spawn the new GasType added in 1.4

Allow bunker buster projectiles to spawn gas 

---

Defs/PawnKindDefs/PawnKinds_CE.xml
Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Patches/Core/ThingDefs_Misc/Weapons_Guns.xml

- Fix for tribal gunners spawning with cheap adv firearms and in some cases charged guns.
- Changes the tag `Gun` to `SimpleGun` for tribal gunners and tribal ranged chiefs.
- Added the `SimpleGun` to vanilla pump-action shotgun and bolt-action rifle.
- Gunner tribals have the `Gun` weapon tag, any modded gun that inherits from base makeable gun also has the `Gun` tag, when certain advanced guns are cheap to make they have a chance of spawning on tribals.
- Can confirm this happens with the vanilla chain shotgun, my charge KS 23 (charge pump shotgun, sheet makes it cheap) and apparently some advaced industrial guns from other mods.
- Does not happen with all the guns because we usually don't patch crafting costs of other mods and spacer components (for example) make spacer guns too …

Fix for tribal gunners spawning with cheap adv firearms

---

Patches/Dubs Rimatomics/Damages_LocalInjury.xml
Patches/Dubs Rimatomics/Turrets_Rimatomics.xml

- What it says on the tin, patch the left-out DamageDef in Rimatomics and added the necessary mod extensions to it.
- Made some other minor adjustments to the values in the patches.

Patch Rimatomics' DamageDef

---

About/About.xml
Patches/Obsidia Expansion/ThingDefs_Misc/Obsidia_Expansion_CE_Ability.xml
SupportedThirdPartyMods.md

This patch changes various ranges of abilities to be in CE standard and also makes silkshot compatible. 
Be warned that Obsidia Expansion-Mothoids *must* be loaded before CE or else silkshot will miss its targets.

Obsidia Expansion-Mothoids Patch

---

Defs/Ammo/Shotgun/10Gauge.xml
Defs/Ammo/Shotgun/12Gauge.xml
Defs/Ammo/Shotgun/16Gauge.xml
Defs/Ammo/Shotgun/20Gauge.xml
Defs/Ammo/Shotgun/23x75mmR.xml

- Anything EMP is locked behind Microelectronics and beyond.

Make EMP shells require Microelectronics research

---

Defs/Ammo/Grenade/20x42mmGrenade.xml
Defs/Ammo/Grenade/25x40mmGrenade.xml
Defs/Ammo/Grenade/25x59mmGrenade.xml
Defs/Ammo/Grenade/30x29mmGrenade.xml
Defs/Ammo/Grenade/35x32mmSRGrenade.xml
Defs/Ammo/Grenade/40x46mmGrenade.xml
Defs/Ammo/Grenade/40x47mmGrenade.xml
Defs/Ammo/Grenade/40x53mmGrenade.xml
Defs/Ammo/Grenade/40x53mmVOG25Grenade.xml
Defs/Ammo/Grenade/50mmGS50Grenade.xml
Defs/Ammo/Grenade/83mmPIATGrenade.xml
Defs/Ammo/Shotgun/10Gauge.xml
Defs/Ammo/Shotgun/12Gauge.xml
Defs/Ammo/Shotgun/16Gauge.xml
Defs/Ammo/Shotgun/20Gauge.xml
Defs/Ammo/Shotgun/23x75mmR.xml

- Made EMP launched nades require microelectronics same as EMP shotgun shells.
- EMP shells and launched grenades are effective but tests show that they are spawning on pawns twice as common as other shell types which this PR fixes that.

Make EMP ammo less common on pawns

---

Languages/English/Keyed/ModMenu.xml
Source/CombatExtended/CombatExtended/Settings.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs

The primary warmup time for Verb_ShootCE is now reduced based on how close the new target is to the previous target.  
The time reduction is capped at 90%, and does not change the weapon cooldown time.  It is calculated based on the relative angle between the current target and the last real shot angle, so weapons with high recoil or high sway benefit less.  Additionally, burst and full auto fire stack the recoil effect, reducing the speed bonus from shooting in the same direction.
- Closes #1474 

Faster repeat shots

---

Source/CombatExtended/CombatExtended/AmmoInjector.cs

changed from var to string and limit only to VFE-Production Benches so other benches are not touched
Was looking at error logs and wondered why MO was having this issue. This should fix it.  Placed the benchVFE check inside the benchNameVFE check to avoid false errors since I initialized benchVFE as null.
Fixes my edits when other tags are introduced because new benches are available. Also limits to only the VFE-Production benches that matters

VFE-Production fix

---

Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml

- What it says on the tin, there were some parent def and inheritance issues that are fixed. _This PR has to be merged after VFE-Mechs is updated on steam._
- As per this PR, we have to update our patches to accommodate for the changes:
https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Mechanoid/pull/1

Fix/Update the buildable mechs' patch

---

Patches/Medieval Overhaul/MO_Races.xml

Added Deathstinger, and Northern Boar support for MO
Added Missing ModExtension for DireBoar
DeathStinger values were compared to a Megascarab because it looked like it was copy pasted in vanilla.
Northern Boar values were compared to a wild boar because it looked like it was copy pasted in vanilla.
DireBoar is a Quadruped animal.
This is to properly patch the animals so the autopatcher doesn't do it.

Mo missing races

---

Patches/Rimsenal Collection/Core/Apparel_RS_CE.xml
Patches/Rimsenal Collection/Core/Rimsenal_DamageDefs.xml
Patches/Rimsenal Collection/Core/Rimsenal_Melee.xml
Patches/Rimsenal Collection/Core/Weapons_YP_CE.xml

thingDef -> ThingDef
Merged the few weaponTag PatchoperationAdds to the PatchOperationConditional's match/nomatch class.
Removed the starting '/' from Defs
Fixes Defs from Rimsenal Core
Using both functions for the PatchOperationalConditional where it could be used.
'/' is not needed in front of Defs.

Rimsenal Core xpath Update

---

Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml

Changed the Patch Operation from replace to add
Movespeed isn't being modified like the previous animals.
Add a movespeed value to override vanilla

Wild boar patch operation change

---

Patches/Steamworld Uniforms/Apparel_Various.xml
SupportedThirdPartyMods.md

- Patch Steamworld uniforms. Most of the equipment are stuffable caps or jackets, made equivalent to their vanilla counterparts (the tuque/bowler and the jacket, respectively). Also includes a pith helmet and a pickelhaube (spiked helmet), which have been given appropriate armor/material thicknesses.
- The pith helmet is made from a combination of wood and cloth, and the material is fairly thick but light. As such, it's strong enough to protect the head from edged attacks reasonably well and has some ability to absorb the energy of blows.
- The vanilla armor value given to the spiked helmets (slightly higher than that of the simple helmet) show that the mod author clearly intends them to be viable combat helmets. This isn't historically accurate (most real helmets were made of felt or …

Patch Steamworld Uniforms.

---

Patches/Logistics_Mechanoid/Bodies_Mechanoid_Heavy.xml
Patches/Logistics_Mechanoid/MeleeMechanoid.xml
Patches/Logistics_Mechanoid/Races_Mechanoids_Heavy.xml
SupportedThirdPartyMods.md

- Patches the new mech added by the Logistics Mech mod. Patches the new body (which is virtually identical to the Tunneler body) and the logi mech's melee weapon, which was made as a separate weapon for some reason.

Patch Logistic Mech Mod

---

Patches/Medieval Overhaul/MO_Weapons_Melee.xml

- adjusted base damage, sharp and blunt penetration value for Named Melee Weapons
- The original mod author implied that Named is an equivalent of their Legendary quality Plasteel counterpart
- their value is so low that it's _Nameless_ weapon now

Tweaks - Medieval Overhaul

---

Patches/Core/ThingDefs_Buildings/Buildings_Security.xml

- Reduce autocannon & sniper turret power consumption from 1250 to 500 Watts.
- Decrease the autocannon & sniper hitpoints from 750 to 500.
Given their effectiveness, it's not desirable to let the player easily operate a large number of higher quality turrets like the sniper and autocannon turrets. The being said, having each turret consume 1250 Watts is quite excessive. A well-established colony with a reliable source of power should be able to practically support 4 - 6 advanced turrets (which is a reasonable number to spread across a larger perimeter to supplement other defenses) without needing to heavily invest in whole new power grid to support them. Yes, a player can reduce this burden with effective power management (e.g turning turrets of when not in use), but that's besides the …

Reduce Sniper and Autocannon Power Consumption and HP

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
Patches/Core/ThingDefs_Buildings/Buildings_Security.xml

- Decreased the base CE auto turrets' HP to be in line with the changes made in #2208 
- Tweaked the medium turret's cost list to be a M240B with the extra components for the automation purposes.
- Tweaked CE and base game turret flammability.
- Tweaked the Rocketswarm turret's cost list to be more in line with the other 2x2 ones.

Various CE turret adjustments

---

Defs/Ammo/Medieval/CannonBall.xml
Defs/Ammo/Medieval/MortarGrenade.xml
Defs/Ammo/Medieval/MusketBall.xml
Defs/ResearchProjectDefs/ResearchProjects.xml
Patches/Core/ResearchProjectDefs/ResearchProjects.xml

- Similar to https://github.com/CombatExtended-Continued/CombatExtendedGuns/pull/68
- Changed the Gunsmithing's description to reflect allowing for making lever-action rifles and not incendiary launchers.
- Made medieval ammo that would use gunpowder have the appropriate Gunpowder research project as a prerequisite.
- Our submods need the research project and it's good to have on hand to be used when patching other mods.

Port the Gunpowder tech into main CE

---

Source/CombatExtended/Compatibility/RaceAutoPatchers/RaceAutoPatcher.cs

Adds which defs are being patched by autopatcher.
Stops log from showing if no animals are autopatched.
For patch contribs to know which animal(s) they forgot to patch or if a mod added more animals.

Better log for animal autopatcher

---

Source/CombatExtended/Compatibility/Patches.cs

If the active mod list contains mod assemblies incompatible with the game (i.e. they throw a ReflectionTypeLoadException when their types are fetched), vanilla's ModAssemblyHandler logs an error and skips over those assemblies. However, we try to process all loaded assemblies as part of the initialization stage where we're looking for compatibility patches, so if such a broken mod is present in the modlist, it will break CE initialization and lead to various NREs in-game.
As a fix, harden the loading process to catch type load errors from assemblies. Since these errors are likely to be from some unrelated, broken mod, only log a message if development mode is active to reduce user confusion and logspam.
This should help reduce user confusion as people won't be seeing CE-related errors in …

Prevent busted mod assemblies from breaking CE on load

---

Patches/Alpha Genes/HediffDefs/Hediffs_Attacks.xml

- What it says on the tin, it's a new hediff attached to a gene.
- Tweaked the chainsaw hands to attack x2 faster but deal half damage.
- Chainsaw go vroom vroom.

Patch the Alpha Genes' Crab Claw

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/Utilities/Tracking/ThingsTrackingModel.cs

1. Fixed ThingsNearSegment by stopping later, with minor modifications;
2. Made average projectiles use RayCastSuppression;
3. Made non-explosive projectiles apply suppression upon impact.
1. With how currently ThingsNearSegment works, it uses a cache of pawns sorted by their position X axis to quickly find which pawns may be within the area of a segment. It limited itself a bit too much within the X axis when checking pawn positions that it cut its checking area off.
2. Projectiles would apply suppression to pawns in a radius around its current position, therefore slow projectiles could apply more suppression to a single pawn. Now they apply suppression in a range around a segment between the old position and new position.
3. With how I modified which area RayCastSuppression checks, …

Fix ThingsNearSegment, make average projectiles apply suppression around travel path

---

.gitignore

This makes life easier for people like me that install and work on CE using Git but also use png2dds to optimize textures.

Ignore optimized .dds textures from Rimpy / png2dds

---

Source/CombatExtended/CombatExtended/BoundsInjector.cs
Source/CombatExtended/CombatExtended/GenSightCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

theum
GetHighestCoverAndSmokeForTarget() needs to iterate over all cells on the line of sight to the target and also needs the count of cells on the line. It currently does this by converting the cells IEnumerable to an array via ToArray(), which always allocates a new array and can result in considerable memory pressure when many pawns are in combat and looking for targets. Reduce the memory churn by introducing a new helper method for getting a list of cells on a line of sight that uses a preallocated List under the hood to store the cells.
We can further reduce the impact of cover checking in the subsequent iteration by only calculating cover height once we've determined that the cover is not a plant, as the calculation does not consider plants anyways in this particular case.
Check …

Reduce the performance impact of GetHighestCoverAndSmokeForTarget()

---

Patches/Warcasket Persona Weapons/Weapons_Warcaskets.xml
SupportedThirdPartyMods.md

- Patch Warcasket Persona Weapons mod. Weapons are on par with other spacer warcasket melee weapons.

Patch Warcasket Persona Weapons

---

Patches/Killzone Concept Armor Set/Apparel_Armor.xml
Patches/Killzone Concept Armor Set/Ranged_Industrial.xml
SupportedThirdPartyMods.md

- Patch for the Killzone Concept Armor, which includes a set of armor and two weapons. Original patch from Auggie0808, with some adjustments by me.
- Added partial armor.
- Added smoke protection.
- Switched LMG from 5.56 NATO to 7.51 NATO, as this is what's called out on the Killzone wiki.
- Reduced the recoil and increased the bulk of the SMG. It looks to be roughly the size of a bullpup rifle like the FAMAS, but enjoys low recoil due to the larger weapon.
Closes #1431 

Killzone Concept Armor Patch

---

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Source/CombatExtended/Utilities/GenClosest.cs
Source/CombatExtended/Utilities/Tracking/ThingsTracker.cs
Source/CombatExtended/Utilities/Tracking/ThingsTrackingModel.cs

#2201 second attempt.
1. Modified ThingsNearSegment algorithm to a work;
2. Added new `infront` boolean parameter to ThingsNearSegment;
3. Made ThingsNearSegment yield-break (stop completely) if `behind` and `infront` are set to `false`;
4. Made average projectiles use RayCastSuppression;
5. Modified RayCastSuppression for better performance and consistency with average projectiles.
1. ThingsNearSegment algorithm didn't seem to work, thus I decided to recreate it from scratch. Fortunately, many things didn't need much change;
2. Implemented it because I could;
3. May be helpful in some cases, can be changed if required;
4. Fixes slow projectiles applying more suppression to a single tile and fast projectiles skipping over some tiles;
5. Slow projectiles will make RayCastSuppression return …

Second attempt at #2201

---

Defs/SoundDefs/CasingSounds.xml
Defs/SoundDefs/World_Sustainers_RPG.xml

- Made the sustainer rocket propeller sound loop to be more quiet as it was annoyingly loud in-game and does not even stop when the game is paused.
- Increased the bullet casing landing sound to hopefully make it audible in-game, _but I think the bullet casings have never had a landing sound being played ingame, since they never truly land on anything and just fade away, their impact sound never triggers... _

Minor sound tweaks

---

Defs/Effects/Flecks.xml
Defs/SoundDefs/CasingSounds.xml
Source/CombatExtended/CombatExtended/CE_Utility.cs

- Decreased casing air time. They should now fall 1-2 tiles near the pawn.
- Made fleck solid time longer than air time. Allows them to land on the ground before disappearing and stay there for 1.5 seconds.
- Made flying casings spin around themselves purely for aesthetics. 1 line change, shouldn't impact performance.
- Made big shells use a separate, pitched down, brass sound instead of light plastic shotgun shell sound.
- Made all casings flecks render instanced. This is used in vanilla for dust puffs, footprints, various mass-produced flecks that don't need to look unique. 
- Casing impact sounds existed for years in CE, but never actually showed up in game, because …

Casing fall tweaks

---

Patches/Astra Militarum Regimentum - Cadia/Armor_Industrial.xml
Patches/Astra Militarum Regimentum - Cadia/Headgear_Industrial.xml
Patches/Astra Militarum Regimentum - Krieg Officer Helmet/Headgear_Industrial.xml
Patches/Astra Militarum Regimentum - Krieg/Armor_Industrial.xml
Patches/Astra Militarum Regimentum - Krieg/Headgear_Industrial.xml
Patches/Ordo Tempestus - Tempestus Scions/Armor_Industrial.xml
Patches/Ordo Tempestus - Tempestus Scions/Headgear_Industrial.xml
SupportedThirdPartyMods.md

Patches the following mods:
- Ordo Tempestus - Tempestus Scions
- Astra Militarum Regimentum - Krieg
- Astra Militarum Regimentum - Cadia
- Astra Militarum Regimentum - Krieg: Officer Helmet
Closes #2233
Closes #2232
Closes #2231 
Armor levels for the equipment are generally on part with late industrial gear like the advanced/composite helmet. The body armor is a bit lighter than recon armor, offering protection roughly similar to advanced modern armor. The armor is treated as unpowered (providing no weight capacity bonus) as I couldn't find an indication these types of armor were generally powered in the 40k 'verse. I included partial armor, with the shoulders having a somewhat better proportion of armor (85% vs 60%) than comparable modern vests, since 40k typically uses bulky, hard …

Patch Odz's 40k Equipment Mods

---

Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyBladelinkMelee.xml
Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyMelee.xml

- Increased the speed of the head attack tool of the Zeushammer and its persona version by 10% and fixed its mass in the spreadsheet.
- Fixed the mass of the Psyfocus staff in the melee spreadsheet.
- https://docs.google.com/spreadsheets/d/11e6FkTQvZiJpq7DpXUk9JSXBSq9enrx0DQhTTJ2xH7c/edit#gid=647442519
- https://discord.com/channels/278818534069501953/322827713335394304/1058162877426585631

Royalty weapons minor tweaks

---

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs
Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs

- Fix NRE when aiming turret.
- Turrets now benefit from the faster follow-up shot system
- Checks added to RecalculateWarmupTicks() to prevent affecting aiming time (as opposed to warmup time).  Turret code calls beginBurst() which ultimately calls RecalculateWarmupTicks() when starting to fire, and starting to aim.
- Revamp turret code

Warmup nre fix

---

Defs/ThingDefs_Misc/Weapons_Grenades.xml
Patches/Bori Race/ThingDefs_Misc/Bori_Explosives.xml
Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
Patches/K4G Rimworld War 2/ThingDefs_Misc/WW2_Grenades.xml
Patches/Kaiser Armory/KaiserArmory_Guns.xml
Patches/LF Red Dawn/RD_Grenade.xml
Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Grenades.xml
Patches/Red Horse Faction Elite Crew/RH_EliteCrew_CE_Patch_RangedIndustrial_Grenades.xml
Patches/Tsar Armory/TsarArmory_Guns.xml
Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedIndustrialGrenades.xml

- What it says on the tin, the base grenade projectile being patched to include CE specific nodes in #2235 was causing certain projectiles that used the bade projectile as a parent but did not have the CE projectile class to throw errors and not recognize the nodes.

Fix the base grenade projectile inheritance issues

---

Source/CombatExtended/CombatExtended/Settings.cs

- What it says on the tin, also brought the setting next to the option for the casing themselves for better visibility.

Make ammo casing filth option enabled by default

---

Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml
Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyBladelinkMelee.xml

- What is says on the tin. For whatever reason the vanilla draw size node is not working in CE be it patch op added in or inherited from a parent. This PR fixes that by giving them their appropriate size via CE's gun draw size mod extension
- https://discord.com/channels/278818534069501953/322827713335394304/1059729803751719022

Fix the Light Mechanoid gun draw sizes

---

Defs/Ammo/Shotgun/20Gauge.xml

- Decreased the sharp AP of the 20 gauge buck and slug shells after updating the gel test source. the No. 4 pellets we use can effectively penetrate a maximum of 8 inches of gel.
- https://www.youtube.com/watch?v=8GqZaVQW7O4 

20 gauge shells' sharp AP adjusted

---

Defs/Ammo/Pistols/45ACP.xml
Defs/Ammo/Pistols/45Colt.xml
Defs/Ammo/Shotgun/10Gauge.xml
Defs/Ammo/Shotgun/20Gauge.xml
Defs/Ammo/Shotgun/23x75mmR.xml
Defs/Ammo/Shotgun/410Bore.xml

- Added the High Velocity .45 Colt ammoset to be used in rifles.
- Added .410 slug, beanbag and EMP shells in slow and normal variants.
- Made small adjustments to other shotgun shells and ammosets.
- .410 Slugs: https://www.opticsplanet.com/winchester-ammunition-410ga-3-1-4oz-supx-riflehp-slug-5-x413rs5.html

Ammo adjustments and additions

---

Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml

- Rechambered the Militor mini-shotgun in .410.
- For a mini-shotgun, 20 gauge is too big and deals too much raw damage (100) in buckshot form which can lead to the mech being very strong when they are unlocked and very punishing when hostile. .410 shells with the new shell types added in #2265 offers enough strength.
- Leave the shotgun chambered in 20 gauge.

Mini-shotgun rechambered

---

Defs/Ammo/Shotgun/410Bore.xml
Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs

- Sidearm generation now based on money value in SidearmOption, not pawn weapon money.
- Closes #2260

Fix sidearm generation money.

---

Defs/Ammo/Pistols/22LR.xml
Defs/Ammo/Pistols/25ACP.xml
Defs/Ammo/Pistols/32ACP.xml
Defs/Ammo/Pistols/38ACP.xml
Defs/Ammo/Pistols/58x21mmDAP92.xml
Defs/Ammo/Pistols/763x25mmMauser.xml
Defs/Ammo/Pistols/765x20mmLongue.xml

- The nerf in #1937 was not really necessary after some comparisons.
- Adjusted other pistol cartridges' sharp AP values due to them being inconsistent after comparing some blunt AP values with other similar cartridges.
- Does the cartridge deserve that much sharp AP? probably not but it's year 5500 baby and we have the American-180!

Buff .22LR's sharp armor penetration and other adjustments

---

Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml
Defs/Stats/Stats_Apparel.xml

- To simulate higher quality items having a better fit or joints to be less bulky in general.
- Let pawns suffer and suffocate in their bulky apparel.

Make apparel worn bulk affected by item quality

---

Patches/Rimsenal Collection/Core/Weapons_JI_CE.xml

Increased weight, increased bulk, sway increased to match, and now calculated from loaded weight, not empty weight. Reduced range to closer to other AMRs, increased warmup time as well as made recoil match characteristics now that it actually matters. Increased consumption per shot to 30, increased mag size so to 90, but it should have less firing cycles per magazine, mostly now each shot is 50% more expensive, which should add up a lot given that JI ammo isn't exactly cheap.
AMR works a bit too effectively against boss mechs, since it's initial role was to slap around centipedes with 2-3 shots fairly reliably, boss mechs which aren't exactly any more durable than centipedes unfortunately also get slapped around and the pretty hefty cost per shot wasn't enough of a penalty to use the …

JI AMR nerf

---

Defs/Ammo/Medieval/CannonBall.xml
Defs/Ammo/Medieval/MiniCannonBall.xml

- What it says on the tin, to be used for Organ Guns instead of musket balls.
- Fixed some values in the cannon ball ammo file.

Add mini cannon ball ammoset

---

Patches/Android Tiers Reforged/Bodies/Bodies_Android.xml

- Completed the bodypart patches for the androids in ATR that was causing them to be able to "wear" multiple melee shields.

Fix the melee shield issues in ATR's patch

---

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml

- Replaced the Add patch op with an Extension specific one to avoid future patch conflicts
- If another mod adds an extension to the mask, our current patch would create a duplicate node.

Fix gas mask extension patch op

---

Languages/English/Keyed/ModMenu.xml
Source/CombatExtended/CombatExtended/Settings.cs

- Some minor housekeeping in the settings menu. Removed a redundant space and fixed how "PawnKind" should be written.

Settings menu housekeeping

---

Defs/Ammo/Grenade/20x42mmGrenade.xml

- Added AP, AP-I and AP-HE ammo types to the 20x42mm nades' ammoset
- Adjusted the existing ammo types based on the data found on the interwebs.
- Removed the Time-Fuzed ammo type as 20x42mm nades don't have a TF high-explosive ammo type irl.
- 20x42mm is a special case as it has AP, HE-I and SAPHEI ammo types irl (it's just a subsonic 20mm round) which we only had the HE type in CE, hence why the AP, AP-I and AP-HE ammo types were added to the ammoset. 

Expand the 20x42mm ammoset

---

Defs/ThingDefs_Buildings/Buildings_Turrets.xml

- Removed the tech level node override of the medium and heavy auto-turret as the heavy one should be industrial and the medium is already inheriting the tech level from the parent def.

Fix the Heavy Auto-Turret's tech level

---

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs

- Fix aimed and snap shots continuing their burst after target is killed/downed or otherwise invalid.
- suppressive fire mode will continue firing at the target's last position, instead of wildly firing wherever recoil takes them.
-long bursts from weapons like a minigun turret (300 round burst) would continue firing wildly in whatever direction recoil and sway takes them when the target is killed or downed and retargeting fails.  This generally results in the recoil carrying the shooting vector upwards and into a vertical loop.  If the burst is long enough, this can result in a turret's aim rotating through 270 degrees and shooting down at itself.
-have all shot modes continue firing in the same direction that the target was until the burst ends normally
-have all shot modes end when the …

Fix bursts continuing to fire in random directions with null target.

---

About/About.xml
Patches/Anty the war Ant/Ammo/Ammo_Anty.xml
Patches/Anty the war Ant/PawnKindDefs/Anty_PawnKind.xml
Patches/Anty the war Ant/ThingDefs_Misc/Anty_Apparel.xml
Patches/Black Widows/ThingDefs_Weapons/Patch_Weapons.xml
Patches/Kenshi Armory/KenshiArmory_Apparel.xml
Patches/Kenshi Armory/KenshiArmory_Armour.xml
Patches/Kenshi Armory/KenshiArmory_Weapons.xml

**Kenshi Armory:**
- Added the name of the 1.4 temporary update to the FindMod.
- Implemented partial armor in line with the plate helmet and plate armor.
**Anty the War Ant:**
- Made the mod load before CE; if loaded after, it overwrites the scenario ammo patches.
- Fixed a patch that was using the old defNames for the CE apparel.
- Fixed a couple of outdated texture paths for crossbow bolts.
Closes #2127 

Update the Kenshi Armory & Anty the War Ant mod.

---

Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_PlasmaWeaponry.xml

- Two weapons from the mod had a drawSize node that made them bigger which does not work in CE, added a patch to fix their size via CE's own mod extension.

Fix RM2's weapon drawSizes

---

Defs/Ammo/GENERIC/AntiMateriel.xml
Defs/Ammo/GENERIC/Autocannon.xml
Defs/Ammo/GENERIC/LauncherGrenade.xml
Defs/Ammo/GENERIC/Pistol.xml
Defs/Ammo/GENERIC/PistolMagnum.xml
Defs/Ammo/GENERIC/Rifle.xml
Defs/Ammo/GENERIC/RifleIntermediate.xml
Defs/Ammo/GENERIC/RifleMagnum.xml
Defs/Ammo/GENERIC/ShotgunShell.xml
Defs/Ammo/Rifle/556x45mmNATO.xml

- Added the missing AP ammo type to anti-materiel and magnum rifle generic ammosets.
- Tweaked all the ammosets to be based on the most commonly used ammo types in the game in each category for ease of tracking.

Generic Ammosets housekeeping

---

Defs/Ammo/HighCaliber/25x137mmNATO.xml
Defs/Ammo/HighCaliber/30x165mm.xml

- Adds 30x165mm ammo, widely used by Soviet and Soviet-derived autocannons.
https://docs.google.com/spreadsheets/d/1zH9dSvBVxwzF9GDx1234Bxz35Cy7OZQu30SGi7MfblY/edit?usp=sharing
- Very slightly reduce the 25x137mm NATO ammo AP. New AP values based on a better source than we were previously using for AP numbers. Notes and values on the official sheet updated accordingly.
Closes #2289
After reviewing some AP data from several sources (linked below), I went ahead and gave the 30x165mm the same Sharp AP as the 30x173mm NATO. The two rounds are fairly comparable (x165 is a bit heavier, x173mm is a bit faster), and while the types of x165 rounds I could find RHA values for don't fall cleanly into our ammo categories, their AP values are in the neighborhood and are decent guidelines.
E.g: …

Add 30x165mm ammo.

---

Defs/Ammo/Advanced/8mmRailgun.xml
Defs/Ammo/HighCaliber/12.7x108mmSoviet.xml
Defs/Ammo/HighCaliber/13.2x92mmSRTuF.xml
Defs/Ammo/HighCaliber/20x102mmNATO.xml
Defs/Ammo/HighCaliber/40x311mmR.xml
Defs/Ammo/HighCaliber/50BMG.xml
Defs/Ammo/Projectiles_Fragments.xml
Defs/Ammo/Rifle/127x55mm.xml
Defs/Ammo/Rifle/44-40Winchester.xml
Defs/Ammo/Rifle/545x39mmSoviet.xml
Defs/Ammo/Rifle/556x45mmNATO.xml
Defs/Ammo/Rifle/6.5Creedmoor.xml
Defs/Ammo/Rifle/8x50mmRLebel.xml
Defs/Ammo/Shotgun/20Gauge.xml

- Added the medium fragment projectiles.
- Added the slow ammoset for 5.45x39mm.
- Tweaked some ammo sharp AP values based on some comparisons and usage of gray matter. Since the joke went over people's heads I'll explain: 6.5 Creedmoor has the same ballistic behavior, if not better, as 7.62 nato. 8x50mmB is similar to other pre-ww1 era cartridges hence the buff and 12.7x55mm is tweaked to be accurate to the source claiming its armor penetration capabilities which is the same as 7.62 nato (Level III armor).
- Fixed the typo in 6.5 Creedmoor's projectile defNames.
- No.3 pellets used for 20 gauge buckshot shells weight 1.57 grams which was incorrectly set in the projectile sheet.
- Fixed the 8mm railgun ammo that had incorrectly high sharp AP relative to 6mm which is a rifle railgun ammo, …

Add Medium Fragments and various ammo sharp AP tweaks

---

About/About.xml
Defs/Stats/Stats_Weapons_Melee.xml
Patches/Core/Stats/Stats.xml

R&G breaks bipods and some other things and just generally doesn't work and isnt maintained, pls get rid of it already!
Changed armor scaling to values proposed by Sam here https://discord.com/channels/278818534069501953/356498503847116801/1064071382952067092
The scale of armor value change is very annoying at lower values making preindustrial armors hard to relative-balance against eachother. These values are bit higher than I had in mind but still much better than before.

Armor scaling sanity rebalance

---

Patches/Vanilla Races Expanded - Phytokin/GeneDefs/GeneDefs_BarkSkin.xml
Patches/Vanilla Races Expanded - Phytokin/GeneDefs/Races_Animal_Ideology.xml
SupportedThirdPartyMods.md

- What it says on the tin. There was a new gene and dryad that are patched.
- Scaled the Barkskin gene based on the Stoneskin gland that offers x0.85 of the gene's blunt armor, same as how the Scaleskin gene from Saurids was scaled, resulting in 10MPa blunt armor.

Patch VRE - Phytokin

---

Languages/English/Keyed/ModMenu.xml
Languages/Russian/Keyed/ModMenu.xml
Languages/Spanish/Keyed/ModMenu.xml
Languages/SpanishLatin/Keyed/ModMenu.xml
Source/CombatExtended/CombatExtended/AmmoInjector.cs
Source/CombatExtended/CombatExtended/Settings.cs

Remove the simplified ammo toggle.
Simplified ammo is a common trap for people that want to avoid micromanaging many ammo types but end up finding themselves defenseless against threats that could be easily dealt with using advanced ammo types. The generic ammo system is a superior alternative for reducing the number of ammo types to manage, so there's no need for the simplified ammo toggle to exist now.

Remove the simplified ammo system

---

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml
Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml

- Increased the bulk capacity of the Scorcher mech from 20 to 30 and gave it a proper loadout.
- Increased the loadout range of the Inquisitor mech from 1~2 to 2~3.

Tweaks the Scorcher and Inquisitor mechs' loadout and bulk cap
