CombatExtended-Continued/CombatExtended

SupportedThirdPartyMods.md
* Update Supported Third-Party Mods list with the following additions:
* [O21] Gith 
* [O21] Half-Orcs
* [O21] Hobgoblins
* [O21] Illithids
* [O21] Orcs
* [O21] Orcs - Faction Addon
* [O21] Tieflings
* [O21] Tieflings - Faction Addon
* [O21] Warforged
* [O21] Warforged - Faction Addon
* AnimalCollabProj
* Forsakens
* Vanilla Vehicles Expanded
=> Update supported mod list (13 additions)

Patches/Vanilla Factions Expanded - Settlers/Drugs/Alcohol_Chemshine.xml, Patches/Vanilla Factions Expanded - Settlers/PawnKindDefs/PawnKinds_Bandits.xml, Patches/Vanilla Factions Expanded - Settlers/PawnKindDefs/PawnKinds_Settlers.xml, Patches/Vanilla Factions Expanded - Settlers/Scenarios/Scenarios_Classic.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Buildings/TurretGatlingGun.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Apparel_Headgear.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Apparel_Various.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedIndustrial.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedIndustrialGrenades.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Misc/Weapons/RangedMedieval.xml
Patches the Settlers mod from Vanilla Factions Expanded
=> Vanilla Factions Expanded - Settlers

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Comment out sapper mechs for the time being, due to mech sapper behavior issue.
=> Comment out mech sappers.

Source/CombatExtended/CombatExtended/Jobs/JobGiver_DefenderReloadTurret.cs, Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Should be functionally equivalent.
`mcs`, the compiler provided by mono, can't compile local functions.  Those of us on Linux don't have the option of using `.net`'s compiler, so getting it compiled with `mcs` is necessary.
- [❌] Compiles without warnings (no new warnings added though)
- [✔] Game runs without errors
- [✔] Playtested a colony (days)
=> Support compiling with mono, don't use local functions.

Source/CombatExtended/Harmony/Compatibility/Harmony-RunAndGun.cs, Source/CombatExtended/Harmony/Harmony-DamageWorker_AddInjury.cs, Source/CombatExtended/Harmony/Harmony-Fire.cs, Source/CombatExtended/Harmony/Harmony-PawnColumnWorkers.cs, Source/CombatExtended/Harmony/HarmonyBase.cs, Source/CombatExtended/Harmony/Harmony_ApparelGraphicRecordGetter.cs, Source/CombatExtended/Harmony/Harmony_AttackTargetFinder.cs, Source/CombatExtended/Harmony/Harmony_FireUtility.cs, Source/CombatExtended/Harmony/Harmony_Hediff_Injury.cs, Source/CombatExtended/Harmony/Harmony_PawnGraphicSet.cs, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
Adds missing commit from master, since @MadaraUchiha is a moron and branched out without pulling master first in #57.
=> Fix Madara being an idiot. Always pull all your branches first boys and girls!

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
Long bow man now spawns with 20-40 arrows instead of 3-6.
=> Update to neolithic heavy archer

Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_RangedWeapons.xml, Patches/Orassans/ThingDefs_Weapons/Weapons.xml
- Fix Orassan duplicate node.
- Fix Ratkin error causing weapon stats not showing.
Fix #133
=> Minor fixes to compat patches

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Animus_Vox.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Arctic_Lion.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Barb_Slinger.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Blizzarisk.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Daggersnout.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Dunealisk.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Feralisk.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_FireWasp.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Ironhusk_Beetle.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Junglelisk.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Mammoth_Worm.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Metallovore.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MycoidColossus.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Overgrown_Colossus.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Raptor_Shrimp.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_SandLion.xml
These are the balance tweaks to Alpha Animals from #95 since the Witcher parts of that PR need some more work. 
I also patched the Fire Wasp.
=> Alpha Animals Tweaks

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_RangedMechanoid.xml
None
Changing float values to int in order to remove console warnings,
Restoring incorrect (outdated?) sound to default.
Removing Console Spam.
=> Fixing alpha animals warnings

Patches/RimWorld - Witcher Monster Hunt/Bodies_WMH-CE.xml, Patches/RimWorld - Witcher Monster Hunt/Projectile_WH.xml, Patches/RimWorld - Witcher Monster Hunt/Races_BasiliskCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_BearofleetCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_ChortCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_CyclopsCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_DjinCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_EkimmaraCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_FiendCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_FlederCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_FogletCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_GhoulCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_GolemCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_HymCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_KikimoreCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_LeshyCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_NekkerCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_WerewolfCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_WraithCE.xml, Patches/RimWorld - Witcher Monster Hunt/Races_WyvernCE.xml, Patches/RimWorld - Witcher Monster Hunt/WH_ProjectileShoot.xml
Added Compatibility for Rimworld Witcher Hunt
Unchanged from the previous pull request(now closed).
=> Rimworld Witcher Hunt

Patches/RimWorld - Witcher Monster Hunt/Races_KikimoreCE.xml
Kikimorewarriors and queens buffed, queen is unable to pose any threat to pawns in heavy armour.
=> Tweaks to Witcher monsters

Patches/Combat Enthusiast's Collection/ThingDefs_Weapons.xml, SupportedThirdPartyMods.md
Integrates the standalone patch for Combat Enthusiast's Collection, plus a few stat adjustments. A special thanks to TetraGrath for creating the patch.
=> Integrate Combat Enthusiast's Collection Patch

Patches/Red Horse Faction Allegiance/RH_Allegiance_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Coalition/RH_Coalition_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Faction Last Man Contingent/RH_LMC_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction War Mongrels/RH_WarMongrels_CE_Patch_Apparel_Armor.xml, Patches/Red Horse Faction War Mongrels/RH_WarMongrels_CE_Patch_Apparel_Headgear.xml, Patches/Red Horse Universal Patch/RH_CE_Allegiance_WarMongs_Patch_Apparel_Headgear.xml, Patches/Red Horse Universal Patch/RH_CE_Coalition_Allegiance_Patch_Apparel_Headgear.xml, Patches/Red Horse Universal Patch/RH_CE_LMC_WarMongs_Patch_Apparel_Armor.xml
Shared Defs within RH Factions have been made into a universal RH patch folder
=> Fixed Shared Defs within RH 

Patches/Auto-Mortars/Buildings_Security.xml, SupportedThirdPartyMods.md
Add integrated patch for (the unofficial 1.1 update of) Auto-Mortars, by MouseDuck.
=> Auto-Mortars patch

Patches/Vanilla Furniture Expanded - Security/Buildings_AdvancedTraps.xml, Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml
A few minor fixes and changes. Change costs for some structures that used shells for material, tweak cooldown time for unmanned turrets.
=> VFE: Security Tweaks

Patches/Auto-Mortars/Buildings_Security.xml
Name of mod in the automortars changed, fixed name change
=> Automortar About.xml Name change

Patches/Vanilla Weapons Expanded/Neolithic_Ranged.xml
Fixes the failing patch operation with the latest VWE update.
=> VWE Tweaks

Patches/Auto-Mortars/Buildings_Security.xml, SupportedThirdPartyMods.md
- Update supported mod list.
- Update Auto-Mortars patch findMod.
=> Very minor fixes

Defs/Tutor/Concepts_NotedOpportunistic.xml, Patches/Core/Stats/Stats.xml
- Fixes outdated CE learning helper regarding armor penetration mechanics.
- Updated armor formula explanation to be easier to understand.
=> Improve armor formula descriptions, fix outdated learning helper

Patches/Rimworld - The Dark Descent/Patch_Items.xml, Patches/Rimworld - The Dark Descent/Patch_Races.xml, Patches/Rimworld - The Dark Descent/Patch_Scenarios.xml, SupportedThirdPartyMods.md
Patches the creatures and adds the bulk to a few items.
=> Rimworld - The Dark Descent

Patches/JDS The Forge - NCR Armory/Defs_Weapons.xml
=> NCR - Armory Fix

Patches/Kaiser Armory/105x155mmR.xml, Patches/Kaiser Armory/77x230mmR.xml, Patches/Kaiser Armory/KaiserArmory_GrenadeRecipe.xml, Patches/Kaiser Armory/KaiserArmory_Guns.xml, Patches/Kaiser Armory/KaiserArmory_Melee.xml, Patches/Kaiser Armory/KaiserArmory_Turrets.xml, Patches/Reich Armory/15cmNebelwerfer.xml, Patches/Reich Armory/30mm Rifle Grenade.xml, Patches/Reich Armory/37x249mmR.xml, Patches/Reich Armory/75cm leIG18.xml, Patches/Reich Armory/75x714mmR.xml, Patches/Reich Armory/80mm Panzerfaust.xml, Patches/Reich Armory/ReichArmory_GrenadeRecipe.xml, Patches/Reich Armory/ReichArmory_Guns.xml, Patches/Reich Armory/ReichArmory_Melee.xml, Patches/Reich Armory/ReichArmory_Turrets.xml, Patches/Soviet Armory/SovietArmory_CE_Patch_Turrets.xml, Patches/Soviet Armory/SovietArmory_CE_Patch_Weapons.xml, Patches/Tsar Armory/TsarArmory_Guns.xml, Patches/Tsar Armory/TsarArmory_Recipes.xml, Patches/Tsar Armory/TsarArmory_Turrets.xml
Updated the game version that caused the patches to fail.
=> Kaiser / Reich / Soviet / Tsar Armory Updates

Patches/Vanilla Furniture Expanded - Production/ThingDefs_Buildings.xml, SupportedThirdPartyMods.md
Add various recipes to the new, larger production tables added by VFE - Production.
closes #232
=> VFE - Production Patch

Patches/O21 Mechadroids/Bodies_Mechadroids.xml, Patches/O21 Mechadroids/PawnKinds_Misc.xml, Patches/O21 Mechadroids/Race_Mechadroids.xml, Patches/O21 Mechadroids/ThingDefs_Items.xml, SupportedThirdPartyMods.md
Patches the mechadroid body, race, and faction. It also adds appropriate bulk to a few items.
=> Patch O21 Mechadroids

SupportedThirdPartyMods.md
- Added Dragon's Descent to the supported mods list.
=> Update Supported Mods

Patches/Rimworld - Altered Carbon/Scenarios_Meth.xml, Patches/Rimworld - Altered Carbon/ThingDefs_Misc.xml
- Patches the new Altered Carbon scenario current present in the [beta](https://cdn.discordapp.com/attachments/715977697775583352/749300132834443395/Rimworld-AlteredCarbon-1.2-build1.zip).
=> Altered Carbon

SupportedThirdPartyMods.md
- Adds More Consumables And Mutagens Reworked to the supported mods list
=> Add MC&M to supported mods

About/About.xml, About/Manifest.xml, About/ModSync.xml, Languages/Spanish/Keyed/BulkAndWeight.xml, Languages/Spanish/Keyed/Descriptions.xml, Languages/Spanish/Keyed/FloatMenu.xml, Languages/Spanish/Keyed/Keys.xml, Languages/Spanish/Keyed/LoadoutGeneric.xml, Languages/Spanish/Keyed/LongEventHandler.xml, Languages/Spanish/Keyed/Misc_Gameplay.xml, Languages/Spanish/Keyed/ModMenu.xml, Languages/Spanish/Keyed/Wind.xml, Languages/Spanish/LanguageInfo.xml, Languages/SpanishLatin/Keyed/BulkAndWeight.xml, Languages/SpanishLatin/Keyed/Descriptions.xml, Languages/SpanishLatin/Keyed/FloatMenu.xml, Languages/SpanishLatin/Keyed/Keys.xml, Languages/SpanishLatin/Keyed/LoadoutGeneric.xml, Languages/SpanishLatin/Keyed/LongEventHandler.xml, Languages/SpanishLatin/Keyed/Misc_Gameplay.xml, Languages/SpanishLatin/Keyed/ModMenu.xml, Languages/SpanishLatin/Keyed/Wind.xml, Languages/SpanishLatin/LanguageInfo.xml, Patches/Arachne/AlienRace_Arachne.xml, Patches/Erin's Critter Collection/ThingDefs_Races.xml
- Updated Manifest and ModSync to match the current repository and mod version.
- Spanish / Spanish Latin translations keyed update.
- Fix #259 - Duplicated armor rating values for the Armadillo.
- Fix #257 - Arachne claws using the wrong linkedBodyPartsGroup.
=> Misc. Tweaks

Patches/Eisenhans Power Armor/ThingDefs_Various.xml
- Patches the Eisenhans Power Armor from [Pkp 17 Eisenhans Power Armor](https://steamcommunity.com/sharedfiles/filedetails/?id=2211757341)
=> PKP 17 Eisenhans

Patches/Rimworld - Altered Carbon/Scenarios_Meth.xml, Patches/Rimworld - Altered Carbon/ThingDefs_Weapons.xml, Patches/Vanilla Factions Expanded - Insectoids/ThingDefs_Misc/Apparel_Various.xml
- Riot Armor (VFE - Insectoids)
- **Bulk:**  100 > 40
- **WornBulk:** 25 > 15
- **Mass:** 24 > 20
- **Sharp Armor:** 4 > 6
- Fixed Altered Carbon scenario xpath defName typo
- Reduced the MAC Rifle warm up time from **4** to **2.5**
=> Miscellaneous Tweaks

Source/CombatExtended/Compatibility/VanillaFurnitureExpandedShields.cs
Literally only had to change 1 line of code EZPZ
- [ ✓ ] Compiles without warnings
- [ ✓ ] Game runs without errors
=> VFE Security shields fix

Patches/Revia Race/ThingDefs_Bodies/Revia_Bodytype.xml
Just a patch for the arms and shoulders, so shields are picked up correctly. 
=> Add Bodydef patch for Revia Race.

Defs/PawnKindDefs/PawnKinds_CE.xml, Patches/Kaiser Armory/KaiserArmory_GrenadeRecipe.xml, Patches/Reich Armory/ReichArmory_GrenadeRecipe.xml, Patches/Vanilla Furniture Expanded - Security/Ammo_Security.xml, Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml, Royalty/Patches/ThingDefs_Misc/Apparel_Headgear.xml, Royalty/Patches/ThingDefs_Misc/Apparel_Royalty.xml
- Patches the new Royalty apparel.
- Fixes "inherit" capitalization that quietly wasn't working in various places.
- Fix the MercenaryMachineGunner weaponMoney
=> Patch New Royalty Apparel + Tweaks

Defs/Ammo/Shell/100x695mmR.xml, Defs/Ammo/Shell/120mmCannon.xml, Defs/Ammo/Shell/155mmHowitzer.xml
- Reduces 155mm HE damage, radius, value, and cost based upon reduction to explosive filler in the projectile sheet.
- Reduce 155mm, 100x695mmR, and 120mm shell craft quantity so the required material amounts are more practical.
=> Tweaks to a few shell

Patches/Fantasy Metals Reforged/Fantasy Metals Reforged.xml, SupportedThirdPartyMods.md
Patched the Fantasy Metals Reforged mod. I've tried to balance them to be consistent with the lore of the materials, rather than strictly in proportion to the numbers from the patched mod itself, as I felt the materials would not feel sufficiently different from steel and each other.
Closes #291
=> Fantasy metals

Patches/Animal Armor - Vanilla/ThingDefs_Apparel.xml, SupportedThirdPartyMods.md
Patch the Animal Armor - Vanilla mod. Gear should be on par with the equivalent humanoid armor.
=> Patch Animal Armor - Vanilla

Patches/Misc Core/ThingDefs_Misc/Weapons.xml, SupportedThirdPartyMods.md
Patch for the railgun weapon added by Misc 'CORE'
=> Misc Railgun

Patches/Idhale Race/Bodies/Idhale_Bodytype.xml, Patches/Idhale Race/PawnKindDefs/Idhale_PawnKind.xml, Patches/Idhale Race/ThingDefs_Misc/Idhale_Apparel.xml, Patches/Idhale Race/ThingDefs_Races/AlienRace_Idhale.xml, Patches/Nearmare Race/Ammo/Projectiles.xml, Patches/Nearmare Race/Bodies/Bodies_Summon.xml, Patches/Nearmare Race/Bodies/Nearmare_Bodytype.xml, Patches/Nearmare Race/PawnKindDefs/Nearmare_PawnKind.xml, Patches/Nearmare Race/Scenario/Nearmare_Scenario.xml, Patches/Nearmare Race/ThingDefs_Misc/Nearmare_Apparel.xml, Patches/Nearmare Race/ThingDefs_Misc/Weapons.xml, Patches/Nearmare Race/ThingDefs_Races/AlienRace_Nearmare.xml, Patches/Nearmare Race/ThingDefs_Races/Race_Summons.xml, Patches/Silkiera Race/Bodies/Silkiera_Bodytype.xml, Patches/Silkiera Race/PawnKindDefs/Silkiera_PawnKind.xml, Patches/Silkiera Race/Scenario/Silkiera_Scenario.xml, Patches/Silkiera Race/ThingDefs_Misc/Silkiera_Apparel.xml, Patches/Silkiera Race/ThingDefs_Misc/Weapons.xml, Patches/Silkiera Race/ThingDefs_Races/AlienRace_Silkiera.xml, Patches/Xenoorca Race/Ammo/Projectiles.xml, Patches/Xenoorca Race/Bodies/Xenoorca_Bodytype.xml, Patches/Xenoorca Race/Hediffs/XO_Hediffs.xml, Patches/Xenoorca Race/PawnKindDefs/Xenoorca_PawnKind.xml, Patches/Xenoorca Race/Scenario/Xenoorca_Scenario.xml, Patches/Xenoorca Race/ThingDefs_Misc/Weapons.xml, Patches/Xenoorca Race/ThingDefs_Misc/Xenoorca_Apparel.xml, Patches/Xenoorca Race/ThingDefs_Races/AlienRace_Xenoorca.xml, SupportedThirdPartyMods.md
Adds CE patches for the following mods:
Nearmare Race
Idhale Race
Xenoorca Race
Silkiera Race
=> Ayameduki Races patch

Patches/Misc MAI/ThingDefs_Races/Race_AIPawn.xml
Added CE gizmo to the AI pawns.
Added the inventory relevant stuff to the AI pawn's thinktree
- Closes #308
=> Updated Race file

Make.py
The .csproj format changed slightly (include all `.cs` files under Source, except those specifically excluded).
Also, `VFESecurity.dll` is included in `Source/packages`, so add the ability to chase that down.
=> Update unix make script

Patches/Erin's Mountain Animals/ThingDefs_Races.xml, SupportedThirdPartyMods.md
Patch the Snow leopard (based upon the existing ACP snow leopard), pallas cat (based upon the existing domestic cat), the pika (based on the rat), and the aragali (based upon the ibex).
=> Patch Erin's Mountain Animals.

Patches/Zeta Reticulans/Scenarios_Zeta.xml, Patches/Zeta Reticulans/Zeta_Race.xml, SupportedThirdPartyMods.md
Patches the Zeta race. There's no pawnkind or custom weapons to patch, so it's just the race.
=> Patch the Zeta alien race.

Defs/ThingDefs_Misc/Apparel_Shield.xml, Defs/ThingDefs_Misc/Weapons_Spotting.xml, Patches/Vanilla Factions Expanded - Vikings/Scenarios_Vikings.xml, Patches/Vanilla Factions Expanded - Vikings/Weapons_Medieval.xml
A collection of minor changes and tweaks.
- Add arrows to the VFE; Viking faction
- Make shields smeltable
- Reduce the harpoon bulk and mass to be less than the Pila.
=> Various Fixes and Tweaks

Patches/Jernalk's Skeletal Legion/Bodies/Bodies_Skeleton.xml, Patches/Jernalk's Skeletal Legion/PawnKindDefs/Skeleton_PawnKind.xml, Patches/Jernalk's Skeletal Legion/ThingDefs_Races/Skeletons.xml, SupportedThirdPartyMods.md
CE patch for Jernalk's (original author typo'd and it should techincally be Jernfalk's) Skeletal Legion 1.2 continued version.
=> Jernalk's Skeletal Legion (Continued) Patch

Patches/Silkiera Race/Ammo/Ammo_Silkiera.xml, Patches/Silkiera Race/Bodies/Bodies_Mech.xml, Patches/Silkiera Race/PawnKindDefs/Silkiera_PawnKind.xml, Patches/Silkiera Race/ThingDefs_Misc/Silkiera_Apparel.xml, Patches/Silkiera Race/ThingDefs_Misc/Weapons.xml, Patches/Silkiera Race/ThingDefs_Races/Race_Mech.xml
Patches for new apparel/Weapons/Races.
=> Silkiera race update

Patches/EPOE Forked/Bionics_Patch.xml
Patch for EPOE - Forked
Mostly the same as the intergrated mod on their end, but includes a few tweaks (generally reduces aiming/shooting bonuses so they're not excessively large in CE) and adds the commando module to the patched AI module implants.
I checked and the patch already intergrated in there *shouldn't* cause issues.
=> EPOE Forked Patches

Patches/Save Our Ship 2/ArchoCreatures_SOS2.xml, Patches/Save Our Ship 2/Hediffs_SOS2.xml, Patches/Save Our Ship 2/Weapons_Grenades.xml
Added compat for the new 'archotech' animals
Added compat for the mechanite molotov
=> Save our Ship 2 Patch update

Patches/Vanilla Animals Expanded/TemperateForest_AddClass.xml, Patches/Vanilla Animals Expanded/TemperateForest_Animals.xml
Patches the hedgehog, red panda, badger, wild goose, and beaver. All use stats from versions of the animals from other mods.
=> Patch Vanilla Animals Expanded - Temperate Forest

Patches/Dragonian Race/ThingDefs_Misc/DR_Weapon.xml, Patches/Dragonian Race/ThingDefs_Races/Race_Dragonian_Garam.xml
Added patch for the battle blade weapon in Garam Version
Updated the race patches to match changes made in the racedefs.
=> Dragonian Race patch update/fixes

SupportedThirdPartyMods.md
Add the following to the list of supported mods:
* [JDS] Star Wars BlasTech Industries
* Star Wars - Factions
* Star Wars - Factions (Continued)
Related to #354
=> Add Star Wars mods to support mod list

Patches/Carbon/Items_Resource_Stuff.xml, SupportedThirdPartyMods.md
Patches the three materials from Carbon, along similar lines to the Rimefeller materials. 
Closes #355
=> Patch Carbon mod

Patches/Prestige Specialist Armor/Apparel_Armor.xml, SupportedThirdPartyMods.md
Adds CE patching for the 3 armors added by prestige specialist armor.
=> Patch for Prestige Specialist Armor

Patches/O21 Forgotten Realms/PawnKindDefs/PawnKinds_Misc.xml, Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Dwarf.xml, Patches/Vanilla Factions Expanded - Vikings/Weapons_Medieval.xml
Stuff from last version that apparently never got PR'd or merged.
Change to throwing axe graphics class, now that 'flicker' works.
Patch Forgotten Realms, Dwarves.
=> More fixes

Patches/Revia Race/ThingDefs_Races/Race_Revia.xml
Fix a minor issue in the Revia Race patch.
Close #358
=> Minor fix for Revia Race patch

Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Shields.xml
- Kite Shield from VFE - Medieval texPath now points to the right texture
=> Fix VFE - Medieval Kite Shield texPath

Patches/Vanilla Bionics Expansion/HediffDefs/FSFBionics_AddedParts.xml
Added patches for bionic tool arms.
Tweaked findmod operations to work with legacy versions.
=> Updates for Vanilla Bionics Expansion

Patches/Marilyn the Mincho Worshipper Witch/Hediffs/Hediffs_Biofilm.xml, Patches/Marilyn the Mincho Worshipper Witch/Scenario/Minchowitch_Scenario.xml, Patches/Marilyn the Mincho Worshipper Witch/ThingDefs_Bodies/MinchoWitch_Bodytype.xml, Patches/Marilyn the Mincho Worshipper Witch/ThingDefs_Bodies/Mincho_Golem.xml, Patches/Marilyn the Mincho Worshipper Witch/ThingDefs_Misc/Mincho_Apparel.xml, Patches/Marilyn the Mincho Worshipper Witch/ThingDefs_Races/Race_Golem.xml, Patches/Marilyn the Mincho Worshipper Witch/ThingDefs_Races/Race_Witch.xml, Patches/Mincho, The Mint Choco Slime/Scenario/Mincho_Scenario.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Bodies/Mincho_Bodytype.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Items/Items_Resource_Stuff.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Misc/Mincho_Apparel.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Misc/Mincho_Weapon.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Races/Race_Mincho.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Races/Race_Pets.xml, SupportedThirdPartyMods.md
Add CE patches for Mincho, The Mint Choco Slime and Marilyn the Mincho Worshipper Witch
=> Mincho/Minchowitch Patches

.github/workflows/branch-cleanup.yml, .github/workflows/build-pr.yml, .github/workflows/rebuild-development.yml, Make.py
Related to #347, need to see if the buildbot can successfully push to a protected branch.
=> Deploy workflows to testing branch

Patches/Redcoat Apparel/Apparel_Redcoat.xml
Armor value/bulk patches for Redcoat Apparel mod.
=> Redcoat Apparel CE patch

Patches/RimWorld - Witcher Monster Hunt/Projectile_WH.xml
Since Graphic_flicker no longer result in borked shadow, a previous fix to graphic class has been removed.
Check the tests you have performed:
=> Update to Witcher Monster Hunt

Patches/Red Horse Faction Allegiance/RH_Allegiance_CE_Patch_TraderKinds.xml
Give Allegiance traders ammo. Just a copy-paste of the Coalition patch.
=> Patch RH Allegiance trader

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_AmoebaHuge.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Amoebachungus.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Amoebasmol.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_AngelaMorthal.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Animalisk.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Demolisher.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Drainer.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Mimes.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MounriGallatross.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Phalanx.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_PheonixOwlcat.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Rayhound.xml
Added Support for all new animals. Partial support for new mechanoids, will need to be finalised at a later date.
=> Alfa Animal Update

Patches/Star Wars - Factions/Patch_Apparel.xml, Patches/Star Wars - Factions/Patch_Melee.xml, Patches/Star Wars - Factions/PawnKinds.xml
A few minor tweaks and some formatting adjustments. Patch in general seems good, though some of the guns appear massively oversized--but that appears to be the base mod, so isn't really our issue.
=> Review and tweak the Star Wars 

Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
- Cleaned up the transpiler, jumping around with enums was more confusing than just using an iterated integer with a few comments.
Please test that this works with a large modlist prior to merging. I have verified that the facepaint works, but I have not tested with other mods which interact with PawnRenderer outside of VFE-V.
=> Fix for #352

Patches/HLX Rimworld UNSC Armoury/Apparel_Headgear.xml, Patches/HLX Rimworld UNSC Armoury/Weapons_Ranged.xml, SupportedThirdPartyMods.md
Compatibility patch for [Rimworld: UNSC Armoury](https://steamcommunity.com/sharedfiles/filedetails/?id=2287902429)
=> Rimworld: UNSC Armoury

Patches/HLX Rimworld UNSC Armoury/Ammo_UNSC.xml, Patches/HLX Rimworld UNSC Armoury/Weapons_Ranged.xml
- Add custom 9.5x40mm ammo for the battle rifle.
- Make battle rifle capable of full-auto, since it is in Halo lore.
=> Tweak UNSC patch.

Patches/Vanilla Animals Expanded/TemperateForest_AddClass.xml
- Fixed a typo in the hedgehog defName
=> Fix VAE - Temperate Forest defName typo

Patches/Clay Soldier Race/Bodies/Golem_Bodytype.xml, Patches/Clay Soldier Race/ThingDefs_Races/AlienRace_Claygolem.xml, SupportedThirdPartyMods.md
=> Clay Soldier Race patch

Patches/A Rimworld of Magic/Patch_Apparel.xml, Patches/A Rimworld of Magic/Patch_Demon.xml, Patches/A Rimworld of Magic/Patch_Direwolf.xml, Patches/A Rimworld of Magic/Patch_Elemental.xml, Patches/A Rimworld of Magic/Patch_Hediff.xml, Patches/A Rimworld of Magic/Patch_Loadouts.xml, Patches/A Rimworld of Magic/Patch_Melee.xml, Patches/A Rimworld of Magic/Patch_Minion.xml, Patches/A Rimworld of Magic/Patch_Ranged.xml, Patches/A Rimworld of Magic/Patch_Sentinel.xml, Patches/A Rimworld of Magic/Patch_Skeleton.xml, Patches/A Rimworld of Magic/Patch_SpiritAnimal.xml, Patches/A Rimworld of Magic/Patch_Stuff.xml, Patches/A Rimworld of Magic/Patch_Traits.xml, Patches/A Rimworld of Magic/Patch_Turrets.xml
Patches A Rimworld of Magic to work with CE.
=> Rimworld of Magic Compatibility patch

Defs/RecipeDefs/Recipes_Production.xml
- Fix a typo on both recipes indicating the wrong amount to be synthesized
=> FSX Recipe Typo Fix

Patches/HLX Rimworld UNSC Armoury/Weapons_Ranged.xml
- Corrected wrong values on MagazineSize and ReloadTime
=> UNSC Armoury Fix

About/About.xml, Patches/The GiantRace/ThingDefs_Misc/GiantApparel.xml, Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Melee.xml, Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Ranged.xml
Added patches for new armor/weapon. Added load order dependency so the patch can catch the armor verb if it's present.
Redid the thrown weapon patch to allow for loading before CE.
=> Patch Updates for The GiantRace

Patches/Orassans/ThingDefs_Races/Desiri.xml, Patches/Orassans/ThingDefs_Races/Gryphon.xml, Patches/Orassans/ThingDefs_Races/Hybrid_Race.xml, Patches/Orassans/ThingDefs_Races/Ori.xml
Ori given melee stats of Monkey
Hybrid race uses same stats as Orassan
Desiri uses same stats as Fox
Gryphon uses same stats as BigCat
=> Added missing hybrid race and animals:

SupportedThirdPartyMods.md
- Adds Vanilla Furniture Expanded - Security to SupportedThirdPartyMods.md
=> Add VFE - Security to list of supported mods

Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Royal_Apparel.xml, Patches/Moyo from the depth/ThingDefs_Misc/Weapons.xml
Patches for new royalguard weapon varaint and armor
Changed coverage and layer stuff for the diving suits to use the base, since that changed with the update.
=> Moyo patch update

Patches/Vanilla Storytellers Expanded - Perry Persistent/PawnKinds_ManInCoat.xml, SupportedThirdPartyMods.md
=> Storyteller Perry Persistent

Patches/Android Tiers/Hediffs/Hediffs_Android.xml
Fix Xpath to target new defname for mining arm
=> Android Tiers Hediff fix

Patches/SCP/Apparel_SCP.xml, Patches/SCP/Headgear_SCP.xml, Patches/SCP/Race_SCP.xml, Patches/SCP/SCP_PawnKinds.xml, SupportedThirdPartyMods.md
Patches the apparel, factions, and new SCP 939 creature. Nothing fancy--gear is in line with other RN gear, and 939 has stats similar to a bear.
Closes #449
=> Patch SCP mod

Patches/Forsakens/Forsakens_CE_Patch_Ammo_ForsakensArrows.xml, Patches/Forsakens/Forsakens_CE_Patch_ThingDefs_Weapons.xml
Slightly buffs forsaken arrow damage, allow forsaken bows to fire normal arrows as well. Slightly buff forsaken bows.
- [ x] Compiles without warnings
=> Update Forsakens weapons

Patches/Fallout New Vegas - Elite Riot Gear/Apparel_RiotGear.xml, Patches/More Utility Packs/Apparel_Packs.xml, Patches/WWII German Uniforms/Apparel_GermanUniforms.xml, SupportedThirdPartyMods.md
A couple of small patches for some apparel. Patches More Utility Packs, WWII German Uniforms, Fallout New Vegas - Elite Riot Armor.
=> Patch More Utility Packs, German Uniforms, & FNV - Elite Riot Armor mods.

Patches/Mister Meeseeks/Meeseek_Race.xml, SupportedThirdPartyMods.md
Mister Meeseeks from the cartoon rickety and mortimier .
=> Mister Meeseeks

Patches/Vanilla Animals Expanded/Endangered_AddClass.xml, Patches/Vanilla Animals Expanded/Endangered_Animals.xml, Patches/Vanilla Animals Expanded/Endangered_Resources.xml
Patches animals a fish item that can be used as a melee weapon. Stats are mostly based on existing animals, while the bonobu is a slightly buffed human melee tools.
=> Patch VAE - Endangered

Patches/Kit's Industrial Weapons/KitsIndustrial_Guns.xml, Patches/Kit's Industrial Weapons/KitsIndustrial_Melee.xml, Patches/Kit's Roman Weapons/Roman_Security.xml, Patches/Kit's Roman Weapons/Roman_Shields.xml, Patches/Kit's Roman Weapons/Roman_Weapons.xml, SupportedThirdPartyMods.md
- Roman weapons are based upon new stats generated.
- Industrial weapons are based on existing patches.
=> Patch Kit's Roman and Industrial Weapons

Patches/[HLX] ReGrowth - Mutated Animals Pack/Bodies.xml, Patches/[HLX] ReGrowth - Mutated Animals Pack/Deffclaw.xml, Patches/[HLX] ReGrowth - Mutated Animals Pack/Mutant_Beaver.xml, Patches/[HLX] ReGrowth - Mutated Animals Pack/Mutant_Deer.xml, Patches/[HLX] ReGrowth - Mutated Animals Pack/Mutant_Rat.xml
=> [HLX] ReGrowth - Mutated Animals Pack

Defs/Ammo/Shell/81mmMortar.xml, Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml, Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/Scenario/Scenario.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Ammo_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml
All the same patch content, since I screwed up the Git the first time.
=> Patch VFE - Mechs (Again)

Patches/EPOE/Bionics.xml, Patches/RBSE/Bionics.xml
- Fixes the failing patch operations of both RBSE & EPOE
=> Prosthetics

Patches/Genetic Rim/GeneticRim_Cosmic_CE_Items_Resource_Stuff.xml, Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_CosmicHorrors_HybridCE.xml, SupportedThirdPartyMods.md
New animals and materials patched.
=> Genetic Rim: Cosmic Horrors Patch

Defs/ThingDefs_Misc/Apparel_Carrying.xml
- Allows carrying apparel to be burned
=> Burnable carrying apparel

Patches/Apparello/ThingDefs/Apparel_Stuffed.xml, Patches/Apparello/ThingDefs/Apparel_Stuffless_And_Bases.xml, Patches/Dinosauria/Items_Resource_Dinosauria_Stuff_Leather.xml, Patches/Extended Storage/Storage.xml, Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Chimera.xml, Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Goliath.xml, Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Hound.xml, Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Kraken.xml, Patches/MechanoidsExtraordinaire/BodyDefs/Bodies_Mechanoid_Vespa.xml, Patches/MechanoidsExtraordinaire/HediffDefs/Hediffs_Local_AddedParts_MechanoidsExtraordinaire.xml, Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Guns_MechanoidsExtraordinaire.xml, Patches/Zombieland/CE_Tweak.xml
- Fix Dinosauria patch typo. Closes #529
- Fix Apparello 2 patch.
- Fix Zombieland .xml patch.
- Fix Mechanoids Extraordinaire patch.  Closes #522
=> Misc. Patch Fixes

Patches/Race to the Rim/Patch_AnimalProjectiles.xml, Patches/Race to the Rim/Patch_Leathers.xml, Patches/Race to the Rim/Patch_Resources.xml, Patches/Race to the Rim/Races_Flightmare.xml, Patches/Race to the Rim/Races_Fury.xml, Patches/Race to the Rim/Races_Gronckle.xml, Patches/Race to the Rim/Races_Hotburple.xml, Patches/Race to the Rim/Races_Nadder.xml, Patches/Race to the Rim/Races_Nightmare.xml, Patches/Race to the Rim/Races_Razorwhip.xml, Patches/Race to the Rim/Races_Rumblehorn.xml, Patches/Race to the Rim/Races_Scauldron.xml, Patches/Race to the Rim/Races_Stormcutter.xml, Patches/Race to the Rim/Races_TerribleTerror.xml, Patches/Race to the Rim/Races_TripleStryke.xml, Patches/Race to the Rim/Races_Zippleback.xml, SupportedThirdPartyMods.md
Patch for the Race to the Rim mod. Patches dragons, their breathe attacks, and the new materials and items added by the mod.
The breathe attacks for a few of the dragons need worked on.
=> Race to the Rim Patch

Patches/RimWorld - Witcher Monster Hunt/Projectile_WH.xml
Projectile update
- Additional use for animals
- Anachronistic
- Breaks realism …
=> Update Withcer Projectile_WH.xml

Patches/Androids Expanded/AlienRace/AlienRace_Droids.xml, Patches/Androids Expanded/AlienRace/AlienRace_Drones.xml, Patches/Androids Expanded/Bodies/Bodies_DroidsExpanded.xml
- Refactored patch operations.
- Androids Expanded (Continued) support #534.
=> Androids Expanded Tweaks

Patches/Genetic Rim/GeneticRim_Dino_CE_Items_Resource_Stuff.xml, Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_Dino_HybridCE.xml, SupportedThirdPartyMods.md
Note: Armoured animals wouldn't be armoured as they use Dinosauria body types and Dinosauria body types aren't patched ti have armour coverage.
=> Genetic Rim dinosauria patch

Patches/Geth/Ammo_Geth_CE.xml, Patches/Geth/Ammo_ME.xml, Patches/Geth/Firestorm_M77_CE.xml, Patches/Geth/Geth_Bodies_CE.xml, Patches/Geth/Geth_Traits.xml, Patches/Geth/Geth_Weapons_CE.xml, Patches/Geth/PawnKinds_Geth_CE.xml, Patches/Geth/Races_Geth_CE_.xml, SupportedThirdPartyMods.md
Patches for
-M98 Widow
-Head of geth now covered by armour
-Minor Rebalance
=> Playable Geth Update

Patches/Star Wars - Droids/Patch_SWDroids_Astromech.xml, Patches/Star Wars - Droids/Patch_SWDroids_Core.xml, Patches/Star Wars - Droids/Patch_SWDroids_Protocol.xml, Patches/Star Wars - Droids/Patch_SWDroids_Support.xml
Patches: Star Wars - Droids Core (Continued), Star Wars - Astromech Droids (Continued), Star Wars - Protocol Droids (Continued) and Star Wars - Support Droids (Continued)
=> Star Wars - Droids Compatibility Patch

Patches/Alpha Biomes/Items_Resource_Stuff.xml, Patches/Alpha Biomes/RangedIndustrialGrenades.xml, Patches/Alpha Biomes/TarShell.xml, Patches/Alpha Biomes/Tar_IED.xml, SupportedThirdPartyMods.md
- Patch new materials.
- Patch poison dart weapon.
- Patch tar shell for mortar and IED.
=> Patch Alpha Biomes

Patches/Cybernetic Organism and Neural Network/Hediffs/Patch_Cyborg_hediffs.xml
Resolves a duplicate xml node error
Contributes towards #556 
There was an error with Cybernetic Organism and Neural Network on game start.
=> Change to the Cybernetic Organism and Neural Network patch

Patches/Ancient Eastern Armory/AsianArmory_Apparel.xml, Patches/Ancient Eastern Armory/AsianArmory_Armour.xml, Patches/Ancient Eastern Armory/AsianArmory_Weapons.xml, Patches/Erin's Friendly Ferrets/ThingDefs_Races.xml, Patches/Tribal Warrior Set/TribalWarrior_Apparel.xml, SupportedThirdPartyMods.md
- Patches the Tribal Warrior Set, which just adds some tribal apparel.
- Patches Erin's Friendly Ferrets, which adds one animal (a ferret, naturally).
- Patches Ancient Eastern Armory, which adds some weapons, clothing, and armor. Armor and weapons should be reasonably well scaled to vanilla medieval weaponry and armor.
=> Patch Tribal Warrior Set

Defs/ThingDefs_Misc/Weapons_RangedNeolithic.xml
- Allow javelins to be purchased and sold to traders
=> Fix javelin tradeability

Patches/Moyo from the depth/Ammo/Ammo_Moyo.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Royal_Apparel.xml, Patches/Moyo from the depth/ThingDefs_Misc/Weapons.xml
Added patch stuff for new items. Added ammoset for the nailgun, since it now uses lower tech ammo.
Removed verb patches from the glaives since they no longer have a ranged attack in vanilla. Changed the ammoset for pistol.  Reduced the pile driver penetration since it's now avaliable earlier. There's also some changes related to armor that are already in the master branch but not in devtest.
=> Updates to moyo patch

Patches/Epona Race/Ammo/Ammo_Epona.xml, Patches/Epona Race/Bodies/Epona_Bodytype.xml, Patches/Epona Race/Bodies/Epona_Hediff.xml, Patches/Epona Race/PawnKindDefs/Epona_PawnKind.xml, Patches/Epona Race/Scenario/Epona_Scenario.xml, Patches/Epona Race/ThingDefs_Items/Items_Resources.xml, Patches/Epona Race/ThingDefs_Misc/Epona_Apparel.xml, Patches/Epona Race/ThingDefs_Misc/Weapons.xml, Patches/Epona Race/ThingDefs_Misc/Weapons_Spacer.xml, Patches/Epona Race/ThingDefs_Races/AlienRace_Epona.xml, Patches/Epona Race/ThingDefs_Races/Race_Sheep.xml, SupportedThirdPartyMods.md
CE patch stuff for Epona the centaur race. 
=> Epona race patch

Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs
- Update to https://github.com/CombatExtended-Continued/CombatExtended/commit/334ea654c592504a3b93ec7b00ae170b7d2e449b (GetMagazineAwareStackCount was counting ammo inside weapon magazines in a pawn's inventory, but not in the pawn's equipped weapon)
=> Set hold tracker to count ammo inside equipped weapon magazine

Patches/Kenshi Armory/KenshiArmory_Apparel.xml, Patches/Kenshi Armory/KenshiArmory_Armour.xml, Patches/Kenshi Armory/KenshiArmory_Weapons.xml, SupportedThirdPartyMods.md
Adds stats for Kenshi Armory weapons and apparel.
=> Kenshi armory patch

Defs/Ammo/Neolithic/Arrows.xml, Defs/Ammo/Neolithic/GreatArrows.xml, Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/AmmoUtility.cs, Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs, Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/SecondaryDamage.cs, Source/CombatExtended/Harmony/Harmony_DamageWorker_AddInjury.cs
- Add \<chance\> property to secondaryDamage (percent value, 0.00 to 1.00)
=> Add chance property to secondary damage

About/About.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-HeavyWeapons.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Quickdraw.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier.xml
- Patches the weapons added by VWE - Frontier
- Patches the weapons added by VWE - Frontier + VWE - Quickdraw
- To do: VWE - Frontier + VWE - Heavy Weapons
=> Patch VWE - Frontier + Addons

Defs/ThingDefs_Misc/Weapons_Turrets.xml, Patches/Core/ThingDefs_Buildings/Buildings_Security.xml, Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml
- Patches the vanilla autocannon and slug turret.
- Changes the caliber of the VFE - Security double autocannon and adjusts some stats accordingly. (Plus a few small tweaks.)
=> Restore Vanilla Autocannon and Slug turrets.

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Resources_Leathers.xml, Patches/Alpha Animals/ThingDefs_Misc/Alpha_Hediffs.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_CrescendoAnole.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_CrystallineCaracal.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Erin.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_GreyCoatedMouflon.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Overgrown_Colossus.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Thunderbeast.xml
New creatures and one new projectile.
- Contributes towards #580
New animals needed to be balanced out for CE. That said I have no idea how to balance...So I decided to create the framework for whoever wants to balance them.
Modifying alpha damages or armor penetration where needed
=> Alpha Animals update

Source/CombatExtended/Compatibility/BlockerRegistry.cs, Source/CombatExtended/Compatibility/EDShields.cs, Source/CombatExtended/Compatibility/VanillaFurnitureExpandedShields.cs
the exact position for VFE Shields
CE Projectiles properly "hit" the right cell with VFE Shields now.
Fast moving CE projectiles could penetrate 1 tick into VFE shields, as the shield was correctly marking the projectile as landed, but not correctly setting the point of impact to the perimeter of the shield.
=> Move GetExactPosition to utility class, use GetExactPosition to set

Patches/Epona Race/Ammo/Ammo_Epona.xml, Patches/Epona Race/PawnKindDefs/Epona_PawnKind.xml, Patches/Epona Race/ThingDefs_Misc/Epona_Apparel.xml, Patches/Epona Race/ThingDefs_Misc/Weapons.xml, Patches/Epona Race/ThingDefs_Misc/Weapons_Spacer.xml
=> Epona Patchupdate

Patches/Moyo from the depth/Ammo/Ammo_Moyo.xml, Patches/Moyo from the depth/Scenario/Moyo_Scenario.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Dragonian_Apparel.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Royal_Apparel.xml, Patches/Moyo from the depth/ThingDefs_Misc/Weapons.xml
CE stats for new apparel
Adjusted and fixed the nail ammo further. Now a machineable ammo type and doesn't require abysteel. Lowered the damage and penetration, and added it to the scenario since you start with a nailgun. Lowered the amount of SMG ammo a little to compensate.
Commented out the stuff for the warped rifle, since it appears to have been removed.
=> Moyo Patches cont.

Patches/Anty the war Ant/Ammo/Ammo_Anty.xml, Patches/Anty the war Ant/ThingDefs_Misc/WeaponsP.xml, Patches/Anty the war Ant/ThingDefs_Races/AlienRace_Anty.xml, Patches/Anty the war Ant/ThingDefs_Races/Race_Proty.xml
Support for more of the new weapons. Change to proty tools so that they don't throw an error on startup.
Some of the diffs show removed inventory comp/tab stuff but it's still there.
=> More anty patchupdates

Patches/Vanilla Factions Expanded - Settlers/PawnKindDefs/PawnKinds_Bandits.xml, Patches/Vanilla Factions Expanded - Settlers/PawnKindDefs/PawnKinds_Settlers.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Coilguns.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Laser.xml
- Make weaponTag operation conditional, in case Frontier is running.
- Remove unpatched frontier coil and laser guns for the time being.
=> Adjust settlers, remove unpatched Coil&Laser guns

Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml
Who did this? Who made it? Why... Why... Who made this patch... I'm so upset. N7, please, check the whole patch for ballance issues. The carbine with sights 200% looks pretty sus too.
=> Why does AK-47 has 200% sights efficency?

Source/CombatExtended/CombatExtended/GenSightCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Fixes pawns mag-dumping into walls when leaning out of cover, like in the below example:
=> Update line of sight and collision detection

Patches/Warbanner Mod/ThingDefs_Banners.xml, SupportedThirdPartyMods.md
Patches warbanners, using the same stats as spears, with some minor debuffs due to the fact you've got a giant piece of fabric lashed to the thing. The buff given by the banner also reduces the effects of suppression.
=> Patch Warbanner mod

Patches/RadWorld/PawnKinds_RadWorld.xml, Patches/RadWorld/ThingDefs_Apparel.xml, Patches/RadWorld/ThingDefs_Misc.xml, Patches/RadWorld/ThingDefs_Races.xml
- Patches several irradiated creatures, all identical to their normal counterparts.
- Patches some new radiation gear.
- Patches CE gas masks to protect from radiation and to consume filters.
=> Patch RadWorld Mod

Patches/The GiantRace/ThingDefs_Misc/GiantApparel.xml, Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Melee.xml, Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Ranged.xml
Updates to the GiantRace patch, as well as removing fixed defense value patches from the chestplate since they were removed at some point and it was causing the patch to fail.
=> The GiantRace patch update.

Patches/Mincho, The Mint Choco Slime/Scenario/Mincho_Scenario.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Bodies/Mincho_Bodytype.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Misc/Mincho_Apparel.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Misc/Mincho_Weapon.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Races/Race_Mincho.xml, Patches/Mincho, The Mint Choco Slime/ThingDefs_Races/Race_Pets.xml
Added support for HAR version and new content.
=> Mincho patch update.

Patches/Nyaron/Ammo/Ammo_Nyaron.xml, Patches/Nyaron/Bodies/Nyaron_Bodytype.xml, Patches/Nyaron/PawnKindDefs/Nyaron_PawnKind.xml, Patches/Nyaron/Scenario/Nyaron_Scenario.xml, Patches/Nyaron/ThingDefs_Items/Items_Resources.xml, Patches/Nyaron/ThingDefs_Misc/Nyaron_Apparel.xml, Patches/Nyaron/ThingDefs_Misc/Weapons.xml, Patches/Nyaron/ThingDefs_Races/AlienRace_Nyaron.xml, SupportedThirdPartyMods.md
Add CE relevant stuff for Nyaron Race. Race specs themself are from the author's original patch.
=> Nyaron Race patch

Patches/Midworld Expanded Flak Armor/ThingDefs_Misc/ThingDef_Apparel.xml, SupportedThirdPartyMods.md
=> Midworld Expanded Flak Armor Patch

Patches/Morgante Mafia Weapons Pack/Weapons_Guns.xml, SupportedThirdPartyMods.md
Patches Mafia Weapons Pack. All of the weapons except the .38 revolvers are copy-paste from existing patches.
=> Patch Mafia Weapons Pack

Patches/Dragon's Descent/AbilityDefs/Dragon.xml, Patches/Dragon's Descent/DamageDefs/Damage_Dragons.xml, Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Common_Dragon.xml, Patches/Dragon's Descent/ThingDefs_Races/Races_Animal_Rare_Dragon.xml
Tweak for animal attacks to make it more sensible.
=> Dragon's descent tweaks

Patches/Core/ThingDefs_Races/Races_Animal_Bears.xml, Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml, Patches/Forsakens - Fauna/Forsaken_ResourcesCE.xml, Patches/Forsakens - Fauna/Patch_Projectile_ForsakenAnimal.xml, Patches/Forsakens - Fauna/Races_BehemothCE.xml, Patches/Forsakens - Fauna/Races_DarkVandalCE.xml, Patches/Forsakens - Fauna/Races_DuskProwlerCE.xml, Patches/Forsakens - Fauna/Races_MurklingCE.xml, Patches/Forsakens/Forsakens_CE_Patch_Ammo_ForsakensArrows.xml, Patches/Forsakens/Forsakens_CE_Patch_PawnKinds_Forsaken.xml
Fixes a few patches broken by recent updates.
- Forsakens Fauna: Behemoth Firebreath
- Forsakens: Forsaken Pawn inventory
-Very minor tweaks I want to make to vanilla animals
=> Forsakened Fixes

Patches/HLX ReGrowth - Extinct Animals Pack/Extinct_Birdlike.xml, Patches/HLX ReGrowth - Extinct Animals Pack/Extinct_Bodies.xml, Patches/HLX ReGrowth - Extinct Animals Pack/Extinct_Mammals.xml, Patches/HLX ReGrowth - Extinct Animals Pack/Extinct_Resources.xml, SupportedThirdPartyMods.md
Everything patched. Something simple this time.
=> Extinct Animals Pack by Helixen

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Gallatross.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MounriGallatross.xml
Missed out on the range attack of Erin.
=> Alpha animals lost patches

Patches/Poleepkwa Race/New_Prawns.xml, Patches/Poleepkwa Race/Patch_Bodies_Prawny.xml, Patches/Poleepkwa Race/Patch_PawnKinds_Prawn.xml, Patches/Poleepkwa Race/Patch_Race_Prawns.xml, Patches/Rim-Hivers!/New_Hivers.xml, Patches/Rim-Hivers!/Patch_Bodies_Hivers.xml, Patches/Rim-Hivers!/Patch_PawnKinds_Hivers.xml, Patches/Rim-Hivers!/Patch_Race_Hivers.xml, SupportedThirdPartyMods.md
Bugs, bugs and more bugs.
A few more things that I want to do:
=> Rim-Hivers!+Poleepkwa Race(updated)

Source/CombatExtended/CombatExtended/GenSightCE.cs
* Fixed pawns being able to fire through wall corners
* Improved the function that calculates which cells are present along a vector (previous implementation was lighter but missed some cells)
=> Fix pawns firing through wall corners, improve LOS detection

Patches/Hive Armory/HiveArmory_Armor.xml, Patches/Hive Armory/HiveArmory_Weapons.xml
=> Hive Armoury

Patches/Genetic Rim/GeneticRim_CE_Patch_Projectiles.xml, Patches/Genetic Rim/GeneticRim_Races_CE/Races_Animal_ArchoCent_CE.xml, Patches/RWY Dragon's Descent Void Dwellers/Bodies_SpaceDragons.xml, Patches/RWY Dragon's Descent Void Dwellers/Items_Resource_SpaceDragon.xml, Patches/RWY Dragon's Descent Void Dwellers/Projectile_SpaceDragon.xml, Patches/RWY Dragon's Descent Void Dwellers/Races_Animal_SpaceDragon_Base.xml, Patches/RWY Dragon's Descent Void Dwellers/Races_SpaceDragon_Attacks.xml, Patches/RWY Dragon's Descent Void Dwellers/Shoot_Breath_SpaceDragons.xml, SupportedThirdPartyMods.md
Patched all the stuff.
Dragon breathes are really iffy tho, sometimes they work sometimes they don't, it might be better if they simply used the vanilla shoot verb.
The armour penetration of their breath attack is another balance issue, I want them to be able to damage one another via breathe attack, but it seems uncertain at times.
Also, buffed archotech centipedes a bit to keep up with the power creep.
Also, please put a BIG note on the CE page indicating that just because the author says it is CE incompatible, doesn't mean it is actually CE incompatible, a lot of the mods are patched on our side and do check the compatibility list first!
=> Dragon's Descent : Void Dwellers

Patches/Core/FactionDefs/Factions_Misc.xml, Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Let's be honest here, mechanoids is balanced in an extremely lopsided manner, lancers, pike and scyther are exceedingly terrible while Centipedes are exceeding powerful. I'm not sure why it's balanced in such a matter in CE, other than to ass-blast new players.
I seek to address the utter lack of threat posed by scythers and lancers.
=> Vanilla Mech tweaks

Patches/Moyo from the depth/Ammo/Ammo_Moyo.xml, Patches/Moyo from the depth/ThingDefs_Misc/Weapons.xml, Patches/Polarisbloc Security Force/Ammo/Ammo_Polaris.xml, Patches/RimSec-Security/Ammo/SRS Ammo.xml
Changed modified charge ammo types to use new default stats.
Adjusted the stats of moyo weapons to match the new ammo specs. Changed the stats on the glaive/axes to reflect their new appearance.
=> Adjust Weapons

Defs/Ammo/Advanced/LaserChargePack.xml, Patches/Vanilla Weapons Expanded - Frontier/Patch_HighRoller_AddonAmmo.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Coilguns.xml, Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Laser.xml
Patches the addon frontier weapons added when Gauss and Lasers are active. The weapons are ultra tech level, so they just use the existing ammo items.
=> Patch VWE - Frontier Gauss and Laser addons.

Defs/Stats/Stats_Apparel.xml, Patches/Core/Stats/Stats.xml
1. Description of electric armor edited to be more clear and concise;
2. Description of heat armor edited to be more clear and concise;
1. and 2. Helps avoid unnecessary confusion for new players;
=> Changes to flame and electric armor descriptions

About/About.xml, Patches/Fuck it Unboomas your Lope/Noboom.xml, SupportedThirdPartyMods.md
=> Important Update

Patches/MiningCo. Spaceship/Airstrike_Damage.xml, Patches/MiningCo. Spaceship/Helmet.xml, Patches/MiningCo. Spaceship/Mining_Trader.xml, Patches/MiningCo. Spaceship/ShipTurrets.xml
Airstrikes with an AOE can penetrate armour but can't throw fragments, Gatling gun doesn't do anything(doesn't even work in vanilla either) but got it to stop throwing errors and freezing the spaceship. Would need to add heavy ammo to the trade ship inventory at a later date.
=> MiningCo Spaceship

Patches/Dinosauria/Dino_Bodies.xml, Patches/Megafauna/Mega_Bodies.xml
Added some natural armour Dinosaruia and Megafauna animals.
=> Bodies update

About/About.xml, Patches/Carbon/Items_Resource_Stuff.xml, Patches/Hive Armory/HiveArmory_Weapons.xml, Patches/Rim-Hivers!/New_Hivers.xml, SupportedThirdPartyMods.md
Final fixes and updates for 3.7
=> 3.7 final tweaks

Patches/LF Command And Conquer NOD Combat Armor/CE_Nod.xml, SupportedThirdPartyMods.md
=> [LF] Command And Conquer NOD Combat Armor

Patches/Genetic Rim/GeneticRim_CE_Patch_Projectiles.xml
Thrown explosive sac now properly patched and behaves like a grenade.
=> Fix Genetic rim thrown explosive Sac

Patches/Simple Ogre Race/CE_OgreSkin.xml, Patches/Simple Ogre Race/CE_Ogre_Race.xml, Patches/Simple Ogre Race/CE_Ogre_Race_Pawn.xml, Patches/Simple Ogre Race/CE_Ogre_Race_Wep.xml, Patches/Simple Ogre Race/Ogre_Resources.xml, SupportedThirdPartyMods.md
Simple Ogre Patch
Compiles fine, let me know if the thowing rock and the spiked club works well.
Closes #653
=> Simple Ogre Race

Patches/Hive Armory/HiveArmory_Weapons.xml, Patches/Rim-Hivers!/Patch_Bodies_Hivers.xml, Patches/Rim-Sheks!/Patch_Bodies_Sheks.xml, Patches/Rim-Sheks!/Patch_PawnKinds_Sheks.xml, Patches/Rim-Sheks!/Patch_Race_Shek.xml, Patches/Rim-Sheks!/Scenarios_Shek.xml, SupportedThirdPartyMods.md
Let me know if I;m missing anything.
Tweaked Rim-Hivers and Hiver armoury.
=> Rim-Sheks!

Patches/MorrowRim/Damage_Morrowind.xml, Patches/MorrowRim/MorrowRim_CorpusCE.xml
Corpus zombies should not knock you down with every hut.
=> Morrowrim fixes and tweaks

Patches/DMWands/Patch_Weapons.xml
Patch 1.0
- Compatibility patch 
Removes and adds the existing weapons and magic bolts (Bullets) with PatchOperation to achieve compatibility with CE
- Closes #[773]
CE is awesome? and I'd like my mod to be as usable as possible
Not relevant
=> Create DMWands/Patch_Weapons.xml @ Patches

About/About.xml, Patches/Exotic Arsenal/Exotic_Ammo_Energy.xml, Patches/Exotic Arsenal/Exotic_Ammo_Others.xml, Patches/Exotic Arsenal/Exotic_Damage_CE.xml, Patches/Exotic Arsenal/Exotic_Weapons_CE.xml, SupportedThirdPartyMods.md
Patch for Mod
TBF I'm worried that I'm patching for mods that'll never be updated for 1.3, so I'm hoping this gets merged into the final 1.2 or even merged into the 1.2 branch after 1.3 is live.
Another thing, CE needs to be loaded after any mods that uses "Halo Ammo" or error will appear.
=> Exotic Arsenal

About/About.xml, SupportedThirdPartyMods.md
=> Final stuff

Patches/Core/Bodies/Bodies_Humanlike/Human.xml, Patches/Mass Effect - Playable Geth/Geth_Bodies_CE.xml, Patches/Rim-Hivers!/Patch_Bodies_Hivers.xml, Patches/Rim-Sheks!/Patch_Bodies_Sheks.xml
Ears, unlike eyes, jaws or noses aren't located infront of your head but to the sides, since most shots would be coming from your front, it doesn't make sense for shots that hit the ear to also hit the head.
Current supported races.
-Humans(and all races that use the human body type)
-Hivers
-Sheks
-Geth
=> Ears aren't outside squishy!

Building.md, README.md
A markdown file explaining how to build the mod for those new to C# modding.
Requested in #823 
Closes #823
=> Add build instructions

.github/workflows/main.yml
Include the Ideology folder when building the zipfiles.
=> Include ideology files in build

.github/workflows/pullrequest.yml, .github/workflows/release.yml
=> Include ideology folder in zipfile

Defs/Tutor/Concepts_NotedOpportunistic.xml
=> Update Concepts_NotedOpportunistic.xml for Night Vision

Defs/CE_FlareTest.xml, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_ThingDefOf.cs, Source/CombatExtended/CombatExtended/MoteThrownCE.cs, Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Flare.cs, Source/CombatExtended/CombatExtended/Things/Flare.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootFlareCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootMortarCE.cs
- Added a flare projectile and flare thing (the glower).
- Added a verb for shooting flares. 
- Added basic Xml for the flare to work while testing.
=> Night Vision Flares

Patches/Alpha Animals/BodyDefs/AlphaAnimals_CE_Patch_Bodies.xml, Patches/Alpha Animals/DamageDef/AlphaAnimals_CE_Patch_DamageDef.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml, Patches/Alpha Animals/ThingDefs_Misc/Alpha_Hediffs.xml, Patches/Alpha Animals/ThingDefs_Misc/Ideological_stuff.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Arctic_Lion.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Atispec.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Black_Hive.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_CrepuscularBeetle.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_DarkBeast.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_EngorgedTentacularAberration.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Eyeling.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Frostling.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Gallatross.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Mammoth_Worm.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MounriGallatross.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Night_Aves.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_OcularNightling.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_SandLion.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Thermadon.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_UnblinkingEye.xml, Patches/Halo Ammo/9.5x40mm.xml
Tweaked balanced, added new creatures etc etc
=> Alpha Animal Update

Source/CombatExtended/CombatExtended/Comps/CompInventory.cs, Source/CombatExtended/CombatExtended/Defs/LoadoutGenericDef.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs, Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs, Source/CombatExtended/CombatExtended/Loadouts/PawnColumnWorker_Loadout.cs, Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs
- Now the equipe button in the assign tab force outfit update as well as loadout.
- Optimized forced loadout updates performance.
- Fixed the error when trying to drop a minified thing.
- Fixed an error related to loadouts and reloading.
=> Minified thing fix and Outfit equipping 

Defs/ResearchProjectDefs/ResearchProjects_Tier4_Misc.xml, Defs/ThingDefs_Misc/Apparel_Headgear.xml
Adds separate research for NVGs. The basic one is after machining, the advanced after microelectronics.
=> Make research for NVGs

Patches/More Vanilla Turrets/MVT_CE_Patch_Ammo_Shells.xml, Patches/More Vanilla Turrets/MVT_CE_Patch_Buildings_Security.xml
- Update patch to follow the new mod name
XML edit. Patch works on local edit.
=> Update More Vanilla Turrets patch

Defs/ThingDefs_Misc/Weapons_Ranged.xml
=> Flare gun tweaks

Patches/Xenohumans - Anthromorphs/Races_Avianmorph.xml, Patches/Xenohumans - Anthromorphs/Races_Bovinemorph.xml, Patches/Xenohumans - Anthromorphs/Races_Caninemorph.xml, Patches/Xenohumans - Anthromorphs/Races_Cervinemorph.xml, Patches/Xenohumans - Anthromorphs/Races_Dragomorph.xml, Patches/Xenohumans - Anthromorphs/Races_Felinemorph.xml, Patches/Xenohumans - Anthromorphs/Races_Gnollmorph.xml, Patches/Xenohumans - Anthromorphs/Races_Lagomorph.xml
Added compatibility patch for Xenohumans Anthromorphs
https://steamcommunity.com/sharedfiles/filedetails/?id=2349467636
Nothing modified, only added patch files
=> Added patch for Xenohumans Anthromorphs

About/About.xml, Patches/Project RimFactory - Materials/Ammo_PRFM.xml, Patches/Project RimFactory - Materials/Items_Fossil.xml, Patches/Project RimFactory - Materials/Items_Resource_Carbon.xml, Patches/Project RimFactory - Materials/Items_Resource_Coal.xml, Patches/Project RimFactory - Materials/Items_Resource_Coke.xml, Patches/Project RimFactory - Materials/Items_Resource_Glasswork.xml, Patches/Project RimFactory - Materials/Items_Resource_Masonry.xml, Patches/Project RimFactory - Materials/Items_Resource_Metal.xml, Patches/Project RimFactory - Materials/Items_Resource_Plastics.xml, Patches/Project RimFactory - Materials/Items_Resource_Quartz.xml, Patches/Project RimFactory - Materials/Items_Resource_Raw.xml
Added a potential compatability patch for CE and project RimFactory - Materials.
Adjusted the about.xml so PRF Materials loads before CE to avoid start errors
I choose to use PRF materials but some stuff didn't have the bulk and were not balanced
=> Project rim factory materials test

Patches/Arasaka Corporation [1.3]/7mmMiniRailgun.xml, Patches/Arasaka Corporation [1.3]/BigBrainGyrojet.xml, Patches/Arasaka Corporation [1.3]/Cyberweeb_Apperal.xml, Patches/Arasaka Corporation [1.3]/Cyberweeb_Guns.xml, Patches/Arasaka Corporation [1.3]/Cyberweeb_Hats.xml, Patches/Arasaka Corporation [1.3]/Cyberweeb_Melee.xml, Patches/Arasaka Corporation [1.3]/Cyberweeb_Turrets_Cyberware.xml, SupportedThirdPartyMods.md
=> Arasaka Corporation [1.3]

Defs/ThingDefs_Misc/Weapons_Grenades.xml, Defs/ThingDefs_Misc/Weapons_Ranged.xml, Defs/ThingDefs_Misc/Weapons_Turrets.xml, Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
- Added new weapon AI tags as described in #890
=> Weapon AI Tags

Patches/Halo Ammo/9.5x40mm.xml, Patches/Spartan Foundry/Apparel_Armors.xml, Patches/Spartan Foundry/Apparel_Headgear.xml, Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml, SupportedThirdPartyMods.md
- Added Spartan Foundry (Continued) to the find mod operation.
- Added night vision to VAE and Spartan Foundry headgear.
- Updated supported mods list.
=> Misc Updates

Patches/Android Tiers/Ammo/81mmMortar_Nanoshell.xml, Patches/Android Tiers/Ammo/MastiffShotgunShell.xml, Patches/Android Tiers/Andro_Trader.xml, Patches/Android Tiers/Bodies/Mod_Bodies_AT_M7Mech.xml, Patches/Android Tiers/Bodies/Mod_Bodies_AT_T4Android.xml, Patches/Android Tiers/CE_FractalSkin.xml, Patches/Android Tiers/Hediffs/Hediffs_Android.xml, Patches/Android Tiers/Hediffs/Hediffs_CustomImplants.xml, Patches/Android Tiers/PawnkindDefs/PawnKinds_Android.xml, Patches/Android Tiers/Scenarios_Andro.xml, Patches/Android Tiers/ThingDef_Misc/Weapons_Guns.xml, Patches/Android Tiers/ThingDef_Races/AlienRace_Androids.xml, Patches/Android Tiers/ThingDef_Races/Races.xml, SupportedThirdPartyMods.md
Comprehensive patch update.
Increased the coverage of android organs to stop them from being so tanky.
Only gave them a very small amount of night vision efficiency as I don't want to make it into a fight only at night situation. Plus, they can wear night vision like everyone else.
=> Android Tiers Update

Patches/Darkest Night SK Steam/Darkest_Void_CE.xml
=> Darkest Night SK Steam

Patches/O21 Forgotten Realms/ThingDefs_Races/Race_Firbolg.xml
Missing O21 race base CE support.
=> O21 Firbolg race update

Patches/Vanilla Ideology Expanded - Hats and Rags/Apparel_Headgear.xml, Patches/Vanilla Ideology Expanded - Hats and Rags/Apparel_Various.xml, SupportedThirdPartyMods.md
Vanilla Ideology Expanded - Hats and Rags https://steamcommunity.com/sharedfiles/filedetails/?id=2567387768
=> Basic VIE - Hats and Rags patch

Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_AuroraSylph.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_EmpressButterfly.xml
Tried patching newest creatures to CE (AA_AuroraSylph, AA_EmpressButterflyLarva, and AA_EmpressButterfly)
Their original power is one (all of them) so I tried balancing out the armor pens around that.
=> Aa updated

Patches/Core/ThingDefs_Items/Items_General.xml
- Fixes the missing parentName from latest update (Added minified trees)
=> Fix missing parentName

Source/CombatExtended/CombatExtended.csproj
- Updated to the latest RimWorld packages.
=> Updated to the latest RimWorld packages

Patches/Alpha Animals/ThingDefs_Misc/AA_Resource_CEStuff.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Gallatross.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MounriGallatross.xml, Patches/Ancient Blade Cyborg/CE_Cyborg_Race.xml, Patches/Android Tiers/ThingDef_Misc/Roboto_Eye.xml, Patches/Arasaka Corporation [1.3]/Cyberweeb_Turrets_Cyberware.xml
Arasaka Corp and Android tiers: Eye implant provide night vision.
Alpha animals: Patched Red wood.
Ancient Blade Cyborg fixes
=> Misc Fixes

Defs/Bodies/BodyShapes.xml, Defs/ThingDefs_Races/Races_Animal_Base.xml, Patches/Android Tiers/ThingDef_Races/AlienRace_Androids.xml, Patches/Core/ThingDefs_Races/Races_Animal_Base.xml
Things that would help in future patching, chunky humanoid bodyshape.
A Pawn base for simple races that do not use tactical behaviours.
=> Minor additions

Patches/Core/Misc/PawnTables/PawnTables.xml, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Comps/CompInventory.cs, Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs, Source/CombatExtended/CombatExtended/GUI/Fragments/Fragment_AttachmentEditor.cs, Source/CombatExtended/CombatExtended/GUI/Windows/Window_AttachmentsEditor.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_ModifyWeapon.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs, Source/CombatExtended/CombatExtended/Loadouts/PawnColumnWorker_Loadout.cs, Source/CombatExtended/CombatExtended/Things/WeaponPlatform.cs, Source/CombatExtended/Harmony/Harmony_PawnColumnWorkers.cs
- Removed the containers from `WeaponPlatform` this should simplify our workflow.
- Removed the carry column from the assign tab.
- Updated the rearm job. Now it shouldn't have any problems since i reduced the throttling to 1800 ticks which is 20 seconds as well as some minor structural changes.
=> Attachments Improvements

Languages/English/Keyed/Attachments.xml, Source/CombatExtended/CombatExtended/Gizmos/Command_Reload.cs, Source/CombatExtended/CombatExtended/Gizmos/Command_ReloadArmor.cs, Source/CombatExtended/CombatExtended/Gizmos/GizmoEditAttachments.cs, Source/CombatExtended/CombatExtended/Things/WeaponPlatform.cs
- Added gizmos for editing weapons off the ground.
=> Attachments Weapon Gizmos

Patches/Kit's Gunpowder Weapons/Ammo_KitsGunpowder.xml, Patches/Kit's Gunpowder Weapons/KitsGunpowder_Security.xml
Fixes some issues with patches.
=> Fix Kit's Gunpowder patches

Defs/ThingDefs_Misc/Weapons_Turrets.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
All turret guns and charge lance.
=> Disqualify certain weapons as relic

Defs/JobDefs/Jobs_CE.xml, Defs/ThingDefs_Misc/Weapons_Ranged.xml, Source/CombatExtended/CombatExtended/AI/Comps/CompReload.cs, Source/CombatExtended/CombatExtended/Attachment_AmmoUser.cs, Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_JobDefOf.cs, Source/CombatExtended/CombatExtended/DefUtility.cs, Source/CombatExtended/CombatExtended/Defs/AttachmentDef.cs, Source/CombatExtended/CombatExtended/Defs/AttachmentLink.cs, Source/CombatExtended/CombatExtended/Defs/AttachmentVerb.cs, Source/CombatExtended/CombatExtended/Defs/WeaponPlatformDef.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_ReloadAttachment.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_CheckReload.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_MuzzleFlash.cs, Source/CombatExtended/CombatExtended/Things/WeaponPlatform.cs, Source/CombatExtended/CombatExtended/Verbs/VerbPropertiesCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootUseAttachmentCE.cs, Source/CombatExtended/CombatExtended/WeaponPlatform_VerbManager.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_VanillaExpandedFramework.cs, Source/CombatExtended/Harmony/Harmony_Command_VerbTarget.cs, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs, Source/CombatExtended/Harmony/Harmony_Verb.cs, Source/CombatExtended/Harmony/Harmony_VerbTracker.cs, Source/CombatExtended/Harmony/Harmony_Verb_TryStartCastOn.cs, Source/CombatExtended/Utilities/Tracking/ThingsTracker.cs
- Added support for multiple verbs through attachments.
- Added independent ammo systems for attachments.
- Added reloading job for attachments.
- Added the attachment reload checks to the main ammo system so pawns should pickup ammo for attachments, reload on their own and other behaviors we similar with (from the main ammo system).
=> Attachments - Multi verb support

Patches/Rimsenal Collection/Core/Apparel_RS_CE.xml, Patches/Rimsenal Collection/Federation/ThingDefs_Misc/Ammo_Fed.xml
Reverts CombatExtended-Continued/CombatExtended#979
=> Revert "Update Apparel_RS_CE.xml"

Patches/Rim-Skeletons/Patch_Bodies_Skellingtons.xml, Patches/Rim-Skeletons/Patch_PawnKinds_Skellingtons.xml, Patches/Rim-Skeletons/Patch_Race_Skellingtons.xml, SupportedThirdPartyMods.md
Yes, I tested the patch for real.
=> Rim-Skeletons

Patches/Aspero Race/CE_Patch_Bodies.xml
Was recommended during my last merge request.  Spent some time playtesting before requesting another merge.
Added coverage values to match human coverage.
Changed bodypart coverage from vanilla to match CE humans.
Mod being patched: https://steamcommunity.com/sharedfiles/filedetails/?id=2565624012
=> Aspero Patch: Modified coverage values to match human

Patches/FalloutTraits/Traits_Patch_CE.xml
Commented out Fallout Traits
Fallout Traits now includes its own CE Patch
=> Fallout Traits Update

Patches/Vanilla Bionics Expansion/HediffDefs/FSFAdvancedBionics_AddedParts.xml
Update to Advanced bionics expansion. Nightvision support and tweaks to melee implants
Stats for new weapon bionics. Added nightvision stat to advanced bionic eyes
Buffed the advanced and archotech power claws
=> Update Advanced Bionics expansion

Ideology/Patches/ThingDefs_Misc/Apparel_IdeologyHeadgear.xml, Patches/Vanilla Ideology Expanded - Hats and Rags/Apparel_Headgear.xml, Royalty/Patches/ThingDefs_Misc/Apparel_RoyaltyHeadgear.xml
Based on #1030, with some various fixes to patch formatting.
=> Hat Fixes (Updated)

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/LTS Military/Weapons.xml
Make Sniper rifles less of a sad cringe, obviously this is far enough to make it useful but it's something, if this gets approved, I'll adjust all the other internally patched guns as well.
Also standardised MP5SD from LTS.
=> Buffs to Sniper Rifle

Source/CombatExtended/CombatExtended/AI/AI_Utility.cs, Source/CombatExtended/Harmony/Harmony_Verb_TryStartCastOn.cs
- Added null an extra check for custom pawns not using base pawn.
=> Tactical manger NPE fix

Patches/RH2 Rimmu-Nation² - Weapons/RM2_Axes_CE.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_BoltAction.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_BullpupAR.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_DMR.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_GrenadeDeletus.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_LMG.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Launchers.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Pistols.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Revolvers.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Rifle1_Style.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Rifle2_Style.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_SMG.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_CE_Shotguns.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_Industrial.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_Machete_CE.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_Research.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_SmolKnifes_CE.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_Swords_CE.xml, Patches/RH2 Rimmu-Nation² - Weapons/Rm2_CE_AirSupport.xml, SupportedThirdPartyMods.md
=> [RH2] Rimmu-Nation² - Weapons

Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
Added 1 mortar shell worth of fragments, not actually entirely sure if the fragment comp works for buildings.
=> Added fragments to explosive IED

Patches/Faction - Mafia/Apparel_Industrial.xml, Patches/Faction - Mafia/Industrial_Melee.xml, Patches/Faction - Mafia/PawnKinds_Mafia.xml, Patches/Faction - Mafia/Traders_Mafia.xml, SupportedThirdPartyMods.md
Patches the Faction : Mafia mod, which adds a few pawnkinds, a knife, two pieces of apparel, and a few traders.
=> Patch - Faction : Mafia

About/About.xml, About/Manifest.xml, Defs/Ammo/Shell/105x607mmR.xml, Defs/Ammo/Shell/15cmNebelwerfer.xml
Release stuff. Update About files, ammo housekeeping
=> housekeeping, about updates

Patches/Fallout Collaboration Project/FCP Makeshift Weapons Pack/Makeshift_Guns_CE.xml, Patches/Fallout Collaboration Project/FCP Minuteman Equipment Teaser/Minuteman_Weapons_CE.xml
- No new changes, just a bug fix
- Fixed an UI bug by fixing a typo (Woodlog -> WoodLog)
=> UI bug fix (NRE reference) due to a typo in FCP-Makeshift patch

Patches/Slime Rancher/Slime_Recipe.xml, Patches/Slime Rancher/SlimeyBois.xml, SupportedThirdPartyMods.md
=> Slime Rancher

Patches/MiningCo. Spaceship/Airstrike_Damage.xml, Patches/Rimeffect N7/ME_SpecialsExplosives.xml
=> Fix up explosion damage hediff

Patches/EvolvedOrgansRedux/Brain_Evo_CE.xml, Patches/EvolvedOrgansRedux/Ideological_organs.xml, Patches/EvolvedOrgansRedux/Limbs_Evo_CE.xml, Patches/EvolvedOrgansRedux/Organ_Evo_CE.xml, Patches/EvolvedOrgansRedux/Protec_Evo_CE.xml, Patches/EvolvedOrgansRedux/Royal_organs.xml, Patches/EvolvedOrgansRedux/Torso_Evo_CE.xml, SupportedThirdPartyMods.md
=> Evolved Organ Redux

Ideology/Patches/ThingDefs_Misc/Race_Animal_Dryads.xml
=> Buffed the Dryads abit

Patches/T's Samurai Faction/T_Samurai_Ammo.xml, Patches/T's Samurai Faction/T_Samurai_Apparel.xml, Patches/T's Samurai Faction/T_Samurai_Pawnkinds.xml, Patches/T's Samurai Faction/T_Samurai_Weapons_Melee.xml, Patches/T's Samurai Faction/T_Samurai_Weapons_Ranged.xml
Extensively playtested, everything should work
=> T's Samurai Faction

Patches/[O21] Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_PawnKinds.xml, Patches/[O21] Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_Races.xml, Patches/[O21] Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_Weapons.xml, Patches/[O21] Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Apparel.xml, Patches/[O21] Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Pawnkinds.xml, Patches/[O21] Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Races.xml, Patches/[O21] Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Weapons.xml, Patches/[O21] Outer Rim Galaxies/Mandalore/Patch_OuterRim_Mandalore_Apparel.xml, Patches/[O21] Outer Rim Galaxies/Mandalore/Patch_OuterRim_Mandalore_Pawnkinds.xml, Patches/[O21] Outer Rim Galaxies/Mandalore/Patch_OuterRim_Mandalore_Weapons.xml, Patches/[O21] Outer Rim Galaxies/Old Republic/Patch_OuterRim_OldRepublic_Races.xml, Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Ammo.xml, Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Apparel.xml, Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Races.xml, Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Turret.xml, Patches/[O21] Outer Rim Galaxies/Patch_OuterRim_Weapons.xml
Adds a compatibility patch for [O21] Outer Rim Galaxies [DevBuild].
=> Outer Rim Galaxies patch

Defs/ThingDefs_Items/Items_Turrets.xml, Defs/ThingDefs_Items/Items_Unfinished.xml, Patches/Core/ThingDefs_Items/Items_General.xml
Removed (pointless?) minified thing patch, Camping Stuff compatible now.
Loads without errors, everything looks working allright ingame.
=> Removed (pointless?) minified thing patch, Camping Stuff compatible now

Patches/RH2 Rimmu-Nation² - Clothing/Armors_CE.xml, Patches/RH2 Rimmu-Nation² - Clothing/Bandana_Balaclava_Scarf.xml
Fixed:
glasses double rendering
hats stacking
helmets material category
somewhat improved readability
=> RN Clothing - forgotten patchops

Source/CombatExtended/Compatibility/PawnKindAutoPatcher.cs
Added the suggested code cleanup, had to be a new PR because fork with code for previous one I deleted some time ago
=> Pawnkind autopatcher fix

Patches/LF Red Dawn/135mm9M113Konkur.xml, Patches/LF Red Dawn/82mmMortar.xml, Patches/LF Red Dawn/Armors_RD.xml, Patches/LF Red Dawn/Jacket_Pants_Boots.xml, Patches/LF Red Dawn/RD_CE_Fixed_Weapons.xml, Patches/LF Red Dawn/RD_CE_mortars.xml, Patches/LF Red Dawn/RD_Grenade.xml, Patches/LF Red Dawn/RD_LMG.xml, Patches/LF Red Dawn/RD_Launchers.xml, Patches/LF Red Dawn/RD_Pistols.xml, Patches/LF Red Dawn/RD_RifleS.xml, Patches/LF Red Dawn/RPG123456789_Projectiles.xml, Patches/LF Red Dawn/RPG16.xml, Patches/LF Red Dawn/RPG29.xml, Patches/LF Red Dawn/RespiratorsHelmets_RD.xml, Patches/LF Red Dawn/Shirt_RD.xml, Patches/LF Red Dawn/Softhead.xml
This is a WIP, but I welcome testing and fixing from anyone, I have being working on this for so long that I'm happy to accept any help.
=> LF Red Dawn

Patches/O21 Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_PawnKinds.xml, Patches/O21 Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_Races.xml, Patches/O21 Outer Rim Galaxies/Chiss/Patch_OuterRim_Chiss_Weapons.xml, Patches/O21 Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Apparel.xml, Patches/O21 Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Pawnkinds.xml, Patches/O21 Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Races.xml, Patches/O21 Outer Rim Galaxies/Clone Wars/Patch_OuterRim_CloneWars_Weapons.xml, Patches/O21 Outer Rim Galaxies/Mandalore/Patch_OuterRim_Mandalore_Apparel.xml, Patches/O21 Outer Rim Galaxies/Mandalore/Patch_OuterRim_Mandalore_Pawnkinds.xml, Patches/O21 Outer Rim Galaxies/Mandalore/Patch_OuterRim_Mandalore_Weapons.xml, Patches/O21 Outer Rim Galaxies/Old Republic/Patch_OuterRim_OldRepublic_Races.xml, Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Ammo.xml, Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Apparel.xml, Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Hediffs.xml, Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Races.xml, Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Turret.xml, Patches/O21 Outer Rim Galaxies/Patch_OuterRim_Weapons.xml, Patches/O21 Outer Rim Galaxies/Rakata/Patch_OuterRim_Rakata_Weapons.xml
Patched PTower Turret, Rakata armor and droid hediffs
Ammo bills produce 200 ammo instead of 500
=> Update Outer Rim Galaxies Patch

Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Ammo_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Apparel_Mechanite.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Items_Resource.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml
- Patches for new VFE: Mechanoids content.
Based on #1202 from contributor, with additional edits. 
=> Update VFE: Mechanoids Patch

Patches/Warhammer - Dryad/Apparel_Dryad.xml, Patches/Warhammer - Dryad/PawnKinds_Dryad.xml, Patches/Warhammer - Dryad/Race_Dryad.xml, Patches/Warhammer - Dryad/Race_Revenant.xml, Patches/Warhammer - Dryad/ThingDefs_Turrets.xml, Patches/Warhammer - Dryad/Weapons_Dryad.xml, SupportedThirdPartyMods.md
Patches the Warhammer Dryad mod.
- Several new human pawns.
- 2 new turrets.
- 2 new weapons.
=> Patch Warhammer Dyrad Mod

Patches/ODZ Suits/ThingDefs_Apparel.xml, SupportedThirdPartyMods.md
- Patches [ODZ Suits](https://steamcommunity.com/sharedfiles/filedetails/?id=2590632195)
Patch provided by Paket#4822
=> Patch ODZ Suits

Source/CombatExtended/CombatExtended/CollisionVertical.cs, Source/CombatExtended/Compatibility/Trenches.cs
- VFE Trenches adjust pawn heights
=> Add support for VFE Trenches

Patches/Warhammer - Dryad/Race_Dryad.xml
updated thingdef name
- Closes #1259
=> simple Warhammer Dryad patch fix

Patches/Anima Bionics/Hediffs_Anima_Bionics.xml, Patches/FSF More Psycasts Powers/AbilitiesPatch.xml, Patches/Infused 2 Expansion/Infused2_anyTier.xml, Patches/Infusion 2/Common_tier.xml, Patches/Infusion 2/Legendary_tier.xml, Patches/Infusion 2/Rare_tier.xml, Patches/Infusion 2/Uncommon_tier.xml, Patches/Mechanoid Bench 2 JGH/Apparel_MB2.xml, Patches/Mechanoid Bench 2 JGH/Hediff_MB2.xml, Patches/Mechanoid Bench 2 JGH/Weapons_MB2.xml
Patches the following mods:
- Mechanoid Bench 2 [JGH]
- [FSF] More Psycasts Powers
- Infusion 2
- Infused 2 Expansion
- Anima Bionics
=> added various patch for a lot of mods

Patches/ReGrowth - Extinct Animals Pack/Extinct_Birdlike.xml, Patches/ReGrowth - Extinct Animals Pack/Extinct_Bodies.xml, Patches/ReGrowth - Extinct Animals Pack/Extinct_Mammals.xml, Patches/ReGrowth - Extinct Animals Pack/Extinct_Resources.xml, Patches/ReGrowth - Mutated Animals Pack/Bodies.xml, Patches/ReGrowth - Mutated Animals Pack/Deffclaw.xml, Patches/ReGrowth - Mutated Animals Pack/Mutant_Beaver.xml, Patches/ReGrowth - Mutated Animals Pack/Mutant_Deer.xml, Patches/ReGrowth - Mutated Animals Pack/Mutant_Rat.xml
- Updating older ReGrowth - Extinct Animals and Mutated Animals Pack patches by creating separate folder patch
- Changed initial Woolly Rhinoceros defname from ReGrowth - Extinct Animals Pack
=> updated ReGrowth Animals Pack patch

Defs/Misc/TipSetDefs/Tips.xml
- Fixed some grammatical errors in the loading tips texts
- Added a bit of information to some tips to help unexperienced players and explain new systems
- Added some new tips to explain some of the newly implemented systems
=> Loading tips tweaks and grammatical fixes

Defs/Misc/TipSetDefs/Tips.xml, Defs/Tutor/Concepts_NotedOpportunistic.xml, Patches/Core/ThingDefs_Misc/Apparel_Various.xml
- Added a loading tip and a tutorial describing the bipods system
=> Update loading tips for bipods

Patches/RimTraits - Medieval Talents/RT_Traits.xml
- Rebalancing traits stat bonuses added by the mod
=> RimTraits - Medieval Talents Patch

Patches/Cossacks of the Rim/Cossack_Apparel.xml, Patches/Cossacks of the Rim/Cossack_MeleeMedieval.xml, Patches/Cossacks of the Rim/Cossack_Pawnkinds.xml, Patches/Crowns and Regalia/ThingDefs_Crowns.xml, Patches/Medieval Quest Rewards/MagicalWeave.xml, Patches/T's Samurai Faction/T_Samurai_Legendary_Melee.xml
- Cossacks of the Rim Patch
- Crowns and Regalia Patch
- Medieval Quest Rewards Patch
- Updated T's Samurai Patch
=> Sum medieval stuff patch

Patches/Birds Beyond - Temperate Forest/Races_Animal_Birds.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Projectiles.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Races.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Resources.xml, Patches/The Tuffalo/Animal_Tuffalo.xml
- Birds Beyond: Temperate Forest Patch
- The Tuffalo Patch
- Updated Magical Menagerie Patch
- Contributes towards #1257 
=> Fauna - Patches and Fixes

Patches/RH2 Rimmu-Nation² - Clothing/Bandana_Balaclava_Scarf.xml
=> Fixed typo in Bandana_Balaclava_Scarf.xml

Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Shields.xml
- Rebalancing VFE-Medieval Heater Shield Armor
- It is stated that Heater Shield offers a significant amount of protection than Kite Shield minus the more shield coverage provided by Kite Shield
=> VFE-Medieval Shields Rebalanced

Defs/Misc/TipSetDefs/Tips.xml
- Added a new loading tip explaining the melee targeting system
=> Update loading tips

Patches/Vanilla Factions Expanded - Ancients/Patch_Abilities.xml
- Changed the Weapon expert and Marksmanship superpowers to work properly and be useful
- The current way these superpowers are patched makes them either useless or broken, tweaked some values to remedy that
=> VFE - Ancients Superpowers tweaks and fixes

Patches/RH2 Rimmu-Nation² - Clothing/Armors_CE.xml
=> Added missing Armors from CE

Patches/Mechanoid Bench 2 JGH/Apparel_MB2.xml
- Removed MiddleHead layer from Mecha Helmet as it is removed from base CE
=> Mechanoid Bench 2 [JGH] - Fix

Patches/Nearmare Race/ThingDefs_Misc/Weapons.xml
Make the new weapons be compatible with CE
Add the new weapons.
Update the patch
None
The patch should be updated.
I will try to update other patches.
Not find any bugs.
=> Nearmare Weapons Update.xml

Patches/Kemomimihouse/ThingDefs_Races/Race_Animals.xml, Patches/Kemomimihouse/ThingDes_Items/Items_Resource_Stuff.xml
Update the patch of kemomimihouse
I have not found any bugs.
=> Update the patch of Kemomimihouse

Patches/Ratkin Apparel+/Apparel_Ratkin.xml, Patches/Rim-Sheks!/Patch_PawnKinds_Sheks.xml, Patches/Rim-Skeletons/Patch_Bodies_Skellingtons.xml
=> More Final Fixes

Defs/Ammo/HighCaliber/40x311mmR.xml, Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml
- Fix some values that were missed in the changes
=> Stupid Hotfixes

Source/CombatExtended/CombatExtended/CE_Utility.cs
- Add hitbox support for multi-cell buildings.
- Closes #1364.
=> Add hitbox support for multi-cell buildings

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Artillery.xml
- Increased to height of the cannons from VFE-Pirates to save ourselves the headache
=> Make the cannon tall again

About/Manifest.xml
- Fixed the versioning issue caused by the additional decimal added to the version of the mod in the Manifest file that caused Hugslib log upload to not work and other unforseen problems
=> Fix the versioning issue

About/About.xml, Defs/ThingDefs_Misc/Apparel_Carrying.xml
- Remove `CompQuality` from `ApparelCarryGearBase,` since it inherits it from the vanilla `ApparelBase`.
- Remove the hotfix version number from the About.xml.
Close #1387 
=> Fix Carry Apparel Quality Bug

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
small fix for ranged targetting against targets with no "human" torso
=> fix for pawns with no torsos

Defs/ThingDefs_Misc/Weapons_Turrets.xml
- Increased the magazine capacity of the M240B from 100 to 200 and the KPV from 40 to 50
=> M240B and KPV magazine capacity increase

Patches/kemomimihouse Kz/Misc/HediffGiverSets.xml, Patches/kemomimihouse Kz/Misc/Projectile.xml
Create a new patch of Kemomimihouse Kz
=> Create a new patch of Kemomimihouse Kz

Patches/ADE Advanced turrets PLUS/Buildings_Security.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
- VFE: Mechanoids - Fixed the defName causing the mech flame spewer description patch to fail.
- Tweaked some values in the ADE advanced turrets+ patch
=> Patch Fixes & Tweaks

Defs/Ammo/Medieval/CannonBall.xml, Patches/Animal Equipment/CE_patch_Apparel_Accessories.xml, Patches/Animal Equipment/CE_patch_Apparel_Clothing.xml, Patches/Animal Equipment/CE_patch_Apparel_Flak.xml, Patches/Animal Equipment/CE_patch_Apparel_Plate.xml, Patches/Animal Equipment/CE_patch_Apparel_Riding.xml, Patches/Animal Equipment/CE_patch_Apparel_Spacer.xml
- Rebalanced the apparel from the Animal Equipment mod
- Some housekeeping for the grape shot cannon shell
=> Animal Equipment patch tweaks and some housekeeping

Defs/Ammo/Advanced/8x35mmCharged.xml, Patches/Vanilla Weapons Expanded/Ammo/ChargeTriplet.xml, Patches/Vanilla Weapons Expanded/Spacer_Ranged.xml
- Changed the VWE sniper rifle to fire 3 projectiles per shot
- It is mentioned in the gun's description that it is a triple barreled sniper rifle like the "Triple Take" from Apex Legends so made the changes to make it so
- Leave the gun single-shot
=> VWE charge sniper tweaks

Patches/NewRatkinPlus/ThingDefs_Races/Race_Rakinlike.xml
Similar to Revia #1418 . I don't know what I did but it works now.
=> Fix Ratkin gizmo and gear tab

Defs/ThingDefs_Items/Items_Unfinished.xml, Defs/ThingDefs_Misc/Apparel_Shield.xml
Add unfinished item to shield crafting
Now pawns won't lose progress when they get interrupted mid-crafting
=> Shields unfinished item

Defs/Stats/Stats_Weapons_Ranged.xml, Languages/English/Keyed/Misc_Gameplay.xml, Source/CombatExtended/CombatExtended/DefOfs/CE_StatDefOf.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_OneHandedness.cs, Source/CombatExtended/Compatibility/Race AutoPatchers/RaceAutoPatcher.cs, Source/CombatExtended/Compatibility/Race AutoPatchers/RaceUtils.cs
Added display for one handedness. It doesn't matter gameplay wise really, but it's only for one handedness, no stat is shown on 2 handed guns
Adds a curve for armor ratings instead of set mults for race autopatcher
=> Caulaflower hands

.github/workflows/pullrequest.yml
Allows building split assemblies via GH actions.
=> Update workflow to build split assembly

Patches/Textiles+/Items_Resource_Stuff.xml, Patches/Vanilla Factions Expanded - Vikings/Races_Animal_Giant.xml, Patches/Vanilla Factions Expanded - Vikings/ThingDef_Items.xml
=> Redo of the PR #1496

.github/workflows/main.yml, .github/workflows/release.yml
- Build the split assemblies in the on-commit-to-dev and on-release workflows
=> Split assemblies build-branch and release workflows

Defs/Misc/TipSetDefs/Tips.xml
Not continued
- TKey's for translating
=> For allow translate tips

Patches/Combat Enthusiast's Collection/ThingDefs_Weapons.xml
=> Combat Enthusiasts Collection update from Augie

Patches/Arachne/AlienRace_Arachne.xml, Patches/Arachne/Apparel_Arachne.xml, Patches/Arachne/Leather_Arachne.xml, Patches/Arachne/MeleeWeapons_Arachne.xml, Patches/Arachne/PawnKind_Arachne.xml, Patches/Arachne/Weapons_Arachne.xml
=> Update Arachne Race Patch

Defs/ThingDefs_Items/Items_Unfinished.xml, Patches/Core/ThingDefs_Misc/Apparel_Various.xml
- Added a new and proper unfinished item for the vanilla armor (flak) vest
=> "Fix" armor vest's unfinished item

Patches/Arachne/ApparelNew_Arachne.xml, Patches/Arachne/Apparel_Arachne.xml
Describe new patches added by your code, e.g.
- Apparel
=> Arachne Update (Again)

Patches/Antinium/Bodies/Ant_Bodies.xml, Patches/Antinium/PawnKindDefs_Ants/Ant_PawnKindsRaider.xml, Patches/Antinium/Scenarios/Ant_Scenario.xml, Patches/Antinium/ThingDefs_Misc/Ant_DrugDefs.xml, Patches/Antinium/ThingDefs_Misc/Ant_ThingDefs.xml, Patches/Antinium/ThingDefs_Races/Ant_AntiniumRace.xml, Patches/Antinium/TraderKindDefs/Ant_TraderKinds.xml, Patches/Antinium/TraitDefs/Ant_Traits_Special.xml
- Added a patch for the antinium alien race.
- Link to the mod - https://github.com/emipa606/Antinium.
=> Patch for antinium alien race

About/About.xml, Patches/ADogSaid/Bionics.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Projectiles.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE.xml, Patches/Alpha Animals/ThingDefs_Misc/Alpha_Hediffs.xml, Patches/Alpha Animals/ThingDefs_Misc/Ideological_stuff.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Hediffs.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Projectiles.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Races.xml
- Added patches for A Dog Said implants in Magical Menagerie and Alpha Animals mods.
- Updated A Dog Said's patch
- Fixed some problematic projectiles in Magical Menagerie which led to wonky load order issues and adjusted MM's load order to be after CE.
- Tweaked certain Alpha Animal ranged attacks to make them work more reliably.
=> Implant and bionic patches updates and projectile fixes

Patches/WarCasket Gundam Addon/Apparel_Warcaskets.xml, Patches/WarCasket Gundam Addon/Melee_Warcaskets.xml, Patches/WarCasket Gundam Addon/Ranged_Warcaskets.xml
Patch is mostly there, just needs some small xml fixes.
=> Move Gundam patch to branch to work on.

Source/CombatExtended/CombatExtended/GunPatcherUtil.cs, Source/CombatExtended/Compatibility/GunPatcher.cs
=> Make autopatcher failures more robust and verbose.

Patches/Edge of Descension - Monoblades/EoD_BladelinksWeaponsDefs.xml, Patches/Edge of Descension - Monoblades/EoD_WeaponsDefs.xml
=> Edge of Descension - Monoblades Patch

Source/CombatExtended/CombatExtended/GunPatcherUtil.cs, Source/CombatExtended/Compatibility/GunPatcher.cs
limited autopatching to Things and ThingWithComps
=> Autopatcher fixes

Patches/Miho Race/ThingDefs_Items/Items_Resources.xml, Patches/Miho Race/ThingDefs_Misc/Weapons.xml
Fixed the costs/stats on one of the guns
Celestial scale is a very expensive material. It's makable but still quite difficult to get to tech wise, where you'd already be sitting at superior options in terms of pure armor anyway.
=> Miho fixes

Patches/Bori Race/PawnKindDefs/Bori_PawnKind.xml, Patches/Bori Race/Scenario/Bori_Scenario.xml, Patches/Bori Race/ThingDefs_Items/Items_Resources.xml, Patches/Bori Race/ThingDefs_Misc/Bori_Apparel.xml, Patches/Bori Race/ThingDefs_Misc/Bori_Explosives.xml, Patches/Bori Race/ThingDefs_Misc/Weapons.xml, Patches/Bori Race/ThingDefs_Races/AlienRace_Bori.xml, Patches/Bori Race/ThingDefs_Races/Race_Realyangdang.xml, SupportedThirdPartyMods.md
Adds patch stuff for the bori race mod.
Should cover everything currently.
=> Bori Patch

Defs/ApparelModBlacklist.xml, Source/CombatExtended/CombatExtended/Defs/ApparelModBlacklist.cs, Source/CombatExtended/Compatibility/ApparelAutoPatcher.cs, Source/CombatExtended/Compatibility/WeaponToughnessAutoPatcher.cs
Put weapon hardness calculation in try/catch
One weapon failing to get a hardness value shouldn't derail the mod loading.
=> Harden weapon autopatcher

Languages/English/Keyed/ModMenu.xml, Source/CombatExtended/CombatExtended/Defs/GunPatcherPreset/GunPatcherPresetDef.cs, Source/CombatExtended/CombatExtended/GunPatcherUtil.cs, Source/CombatExtended/CombatExtended/Settings.cs, Source/CombatExtended/Compatibility/ApparelAutoPatcher.cs, Source/CombatExtended/Compatibility/GunAutoPatcher.cs, Source/CombatExtended/Compatibility/PawnKindAutoPatcher.cs, Source/CombatExtended/Compatibility/RaceAutoPatchers/RaceAutoPatcher.cs, Source/CombatExtended/Compatibility/WeaponToughnessAutoPatcher.cs
* Rename GunPatcher to GunAutoPatcher
* Add options to enable/disable autopatchers
* Don't spam the log
* Add support for inserting extra weapon tags
=> More autopatcher tweaks

Defs/GunPatcherDefs/AssaultRifle.xml, Defs/GunPatcherDefs/MachineGun.xml, Defs/GunPatcherDefs/Pistol.xml, Defs/GunPatcherDefs/Revolver.xml, Defs/GunPatcherDefs/SMG.xml, Defs/GunPatcherDefs/SniperRifle.xml
- Add new weapon autopatcher presets for various modern conventional weapons.
- Slightly adjust stats of SMG.
- We need more weapon patcher presets.
=> Add Additional Gun Presets

Source/CombatExtended/CombatExtended/StatParts/StatPart_QualityConditional.cs
Fixed armor not scaling with quality
=> Armor scaling hotfix

About/About.xml
Just increments the version number in the About.xml to 1.3.4.7.1 for the hotfix.
=> Increment version number for hotfix

Patches/ODZ Stalingrad - Uniforms/ThingDefs_Apparel.xml
- Carry stats for webbings
- Aiming time offsets from webbings
- Stuff effect multiplier on both faction helmet
=> Patch for [1.3] Stalingrad - Uniforms

Patches/Individuality/Traits_Patch_CE.xml, Patches/RimTraits - General Traits/RT_General_Traits.xml
- Patch RimTraits - General Traits
- Updating [SYR] Individuality patch
=> Traits Boogaloo - Housekeeping

Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Bobeene.xml
- Patched the newly added animal to AA called Bobeene
- The new animal is a flying insect-bovine hybrid based on the Spined Gow stats-wise in vanilla, so the CE stats are based on the Gow as well.
=> Patch the new animal added to Alpha Animals

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE.xml
- Minor typo fix in the AA patch
=> Minor Alpha Animals typo fix

Patches/Ushankas Glitterworld Uprising/Hediff_Glitter.xml
- adjusted skin replacement stats to CE value
=> Patch for Ushankas Glitterworld Uprising

Patches/Archotech PowerArmor/Apparel_JDS.xml
- adjusted armor value
- Costlist and WorkToMake balance
- because archotech yes
=> Patch for Archotech PowerArmor

Patches/Seren from Stardust/Bodies_Seren.xml, Patches/Seren from Stardust/PawnKinds_Seren.xml, Patches/Seren from Stardust/Scenarios.xml, Patches/Seren from Stardust/Seren_Race.xml, SupportedThirdPartyMods.md
New patch for there Seren from Stardust race. Race is mostly identical to humans, but faster and slightly weaker--so, less fist blunt pen and a tradeoff of dodgechance for parrychance.
=> Patch Seren Race

About/About.xml, About/Manifest.xml
Exactly what is says in the title, and nothing more.
=> Increment Mod Version Number: 7.1 to 8.0

Defs/Misc/TipSetDefs/Tips.xml
=> Fix a typo in Tips

Source/CombatExtended/Harmony/Harmony_ShieldBelt.cs
Shield belts respect shield-break-chance and secondary ion damage.
=> handle secondary ion damage against shields

Source/CombatExtended/CombatExtended/ShiftVecReport.cs
=> don't lead stunned targets

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Explosive.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
=> Second attempt at rpg-targeting fix

Source/CombatExtended/CombatExtended/LightingTracker.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Explosive.cs, Source/CombatExtended/CombatExtended/ShiftVecReport.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
Allow blind pawns to fire at close targets and to return fire at distant ones.
- Closes #1695 
=> Blindfiring

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
=> Add extra bounds checking on raycasts.

Patches/Vanilla Psycasts Expanded/HediffDefs/Hediffs_Patch.xml
- Aiming accuracy stat add-on
- it was planned to be added on a previous pull request before it was merged.
=> Small add-on buff for Guided Shot on Vanilla Psycasts Expanded

Patches/Archotech PowerArmor/Apparel_JDS.xml, Patches/RH2 Rimmu-Nation² - Weapons/RM2_Swords_CE.xml
Two final xml fixes for the 4.8 release.
=> final tweaks

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_UBGLStats.cs
- Fix for floor issue caused by the UBGL code.
=> Nullcheck for floors' info screen

Patches/T's Samurai Faction/T_Samurai_Apparel.xml, Patches/T's Samurai Faction/T_Samurai_Legendary_Melee.xml, Patches/T's Samurai Faction/T_Samurai_Pawnkinds.xml, Patches/T's Samurai Faction/T_Samurai_Spacer_Weapons.xml, Patches/T's Samurai Faction/T_Samurai_Weapons_Melee.xml, Patches/T's Samurai Faction/T_Samurai_Weapons_Ranged.xml
- patches for Spacer Oni Gear from the mod
- reworked old patches method
- space oni marines iz cool
=> T's Samurai Faction Patch Update

About/About.xml
Increment version to 8.1 for the hotfix.
=> Increment version number for hotfix.

Rim-Robots!/Implants_Patch.xml, Rim-Robots!/Mechanent_Body.xml, Rim-Robots!/Pawnkind_Patch.xml, Rim-Robots!/Personae_Body.xml, Rim-Robots!/Race_Patch.xml, SupportedThirdPartyMods.md
Add patches for Pawnkind, Body and Implants from 'Rim-Robots!'
They have a patch on their end but it is incomplete, this one fills in the gaps.
=> 'Rim-Robots!' Patch

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs, Source/CombatExtended/Harmony/Harmony_AttackTargetFinder.cs
Currently, having many turrets on the map results in a noticeable
performance overhead because the vanilla logic for determining the best
target to shoot at ends up rerunning expensive validation logic
(line-of-sight, hostility etc.) checks. This can be optimized to
somewhat reduce the performance cost:
* Replace the section in BestAttackTarget() responsible for determining
the optimal target for a ranged attacker with an optimized equivalent
that runs expensive validation logic at most once per potential
target. Since the logic is shared between turrets as well as pawns,
add special casing for the case where the attacker is a turret or a
pawn manning a turret to avoid having to determine the closest target
in the case that there are no targets in range that can be shot at.
This logic is …
=> Reduce performance impact from turrets

Defs/Misc/TipSetDefs/Tips.xml, Source/CombatExtended/CombatExtended/Jobs/JobDriver_SetUpBipod.cs
Attempt at fixing issue where certain apparels modyfing weapon handling making bipods not set upable
=> fixed bipods not setting up

About/About.xml
- What it says on the tin, expand the list of incompatible and problematic mods with CE
- https://steamcommunity.com/sharedfiles/filedetails/?id=1134165362
- https://steamcommunity.com/sharedfiles/filedetails/?id=2799252286
- https://steamcommunity.com/sharedfiles/filedetails/?id=2597524334
- https://steamcommunity.com/workshop/filedetails/?id=2584374906
- https://steamcommunity.com/sharedfiles/filedetails/?id=2854006492
- https://steamcommunity.com/sharedfiles/filedetails/?id=2014429481
- https://steamcommunity.com/sharedfiles/filedetails/?id=1321600671
- https://steamcommunity.com/sharedfiles/filedetails/?id=2732147678
- https://steamcommunity.com/sharedfiles/filedetails/?id=2636621800
- https://steamcommunity.com/sharedfiles/filedetails/?id=2570381855
- …
=> Expand the list of incompatible mods

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
- Tweaked the charge rifle based on the gun spreadsheet, some values needed correcting.
=> Charge rifle tweaks

Patches/Rimsenal Collection/Federation/ThingDefs_Races/Race_Bion.xml
moves target of patch to the base so it should hopefully fire correctly now, preventing certain ones from getting error messages when hit.
=> Fix to bion bodyshape

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
Disable melee targeting for pawns that are in a social fight to avoid
unexpected lethal results. As part of this, rename gizmoComp to
CompMeleeTargettingGizmo to make it clear that this is a property and
not a field, and introduce a backing field for it that is reset on
warmup.
- Closes #1809
=> Disable melee targeting in social fights

Source/CombatExtended/CombatExtended/ShiftVecReport.cs
Attempt at fixing the issue with range error becoming huge with very low range
=> fix for low range target leading

Defs/Ammo/Pistols/44Magnum.xml
- Added the high velocity .44 Magnum ammo set which is used by lever-action guns.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1198674278
=> .44 Magnum high velocity ammo set

Patches/Core/ThingDefs_Misc/Apparel_Various.xml, Royalty/Patches/ThingDefs_Misc/Apparel_Armor.xml
- Patched vanilla + Royalty power armor descriptions to include the changes to loadbearing and handling. Otherwise the descriptions are unchanged from the vanilla versions
=> Patched power armor descrptions

Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_Ammo_Mech.xml, Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_SpacerWeapons_Mech.xml
- What it says on the tin, housekeeping for stuff that was missed in #1842 
=> Minor housekeeping after #1842

About/About.xml
- https://steamcommunity.com/sharedfiles/filedetails/?id=1975381493
- https://steamcommunity.com/sharedfiles/filedetails/?id=2860414285
- https://steamcommunity.com/sharedfiles/filedetails/?id=2596988484
- https://steamcommunity.com/sharedfiles/filedetails/?id=797360572
- https://steamcommunity.com/sharedfiles/filedetails/?id=2034896549
=> Expand the incompatible mods list

Defs/Ammo/Shell/105mmHowitzer.xml, Defs/Ammo/Shell/155mmHowitzer.xml
- Fixed the two aforementioned shells based on the correct values in the spreadsheet.
=> 105mm and 155mm shells fixed

Defs/Ammo/Rifle/277Fury.xml
- Tweaked the ammo's values based on the spreadsheet.
- The sheet that originated the cartridge was deleted by yours truly and redoing the ammo in the sheet again based on the available data resulted in slightly different values which are inserted into the xml file.
=> .277 Fury redone

Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Projectiles.xml, Patches/Magical Menagerie/MagicalMenagerie_CE_Patch_Races.xml
- Patched the new Stymphalian Bird animal and its ranged attack projectile.
=> Magical Menagerie patch update

Patches/Combat Enthusiast's Collection/ThingDefs_Weapons.xml
- Add "Combat Enthusiast's Collection (Continued)" to the patch FindMod so that it functions with the continued version.
Closes #1848
=> Update CEC FindMod Name

Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_Ammo_Mech.xml, Patches/Reinforced Mechanoids Tyrikan-Line/ThingDefs_Misc/RM_SpacerWeapons_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Ammo_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
=> Properly fixed the custom mechanoid ammo issues and rebalancing

Patches/Makeshift Melee Weapons/DetVisor_MakeshiftMelee.xml, SupportedThirdPartyMods.md
Github shenanigans somehow reverted the merge of the patch after merging #1886...
=> Redo of #1875

Defs/ThingDefs_Misc/Apparel_Headgear.xml, Patches/Medieval Overhaul/MO_Apparel_Helmets.xml, Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Apparel.xml
- Rebalanced some medieval gear based on the current implementation of main CE stuff
=> Rebalanced medieval armor pieces

Patches/Erin's Sephyr/Hediff_Racial_Sephyr.xml, Patches/Erin's Sephyr/PawnKinds_Sephyr.xml, Patches/Erin's Sephyr/Race_Sephyr.xml, Patches/Erin's Sephyr/Scenarios_Sephyr.xml, SupportedThirdPartyMods.md
- adjusted hediff stats value to be on par with CE's standard
nothing, just an ordinary fox girl
- because they are fluffy
=> Patches for Erin's Sephyr

Source/ArtilleryCompat/ArtilleryCompat.csproj, Source/BetterTurretsCompat/BetterTurretsCompat.csproj, Source/CombatExtended/CombatExtended.csproj, Source/Loader/Loader.csproj, Source/MiscTurretsCompat/MiscTurretsCompat.csproj, Source/MultiplayerCompat/MultiplayerCompat.csproj
- Update CE's dependency package versions to the latest 1.3 versions prior to 1.4 update.
=> Update CE's dependency package versions

Source/CombatExtended/CombatExtended/Settings.cs
- Put the debug settings after ammunition system settings in the options menu
=> Reorder some sections in the settings screen

Makefile, Source/CombatExtended/Harmony/Harmony_DamageWorker.cs
Breach axes (or anything with Demolish damage type) no longer generate fragments 
- closes #1810 
Breach axes do great damage to walls, enough to generate fragments, from close range, which leads to breach axes killing the wielder.
=> Fix breach axes

About/About.xml
- Increment the version number for the hotfix.
=> Increment version number for hf

LoadFolders.xml
- Added the Biotech folder to include the patches and defs in. The empty xml file can be deleted in a later PR.
- Adjusted the loadFolder rules to accommodate for Biotech.
=> Add the Biotech folder 

Defs/ResearchProjectDefs/ResearchProjects_Tier4_Misc.xml, Defs/ResearchProjectDefs/ResearchProjects_Turrets.xml, Defs/ThingDefs_Misc/Apparel_Carrying.xml, Patches/Core/ResearchProjectDefs/ResearchProjects.xml
- Shuffled some research projects around to fit the ones added by CE into the main research tab neatly.
- Added Complex clothing to tac vest and backpacks.
- Made the tac vest to be unlocked in Flak research.
- People tend to miss turret research projects that are hidden in other tabs and don't look at what is unlocked with which research prerequisites.
- Tac vest and backpacks were craftable without any prior research.
=> Research project tweaks

Patches/EPOE Forked Royalty DLC expansion/Bionics_Patch.xml, Royalty/Patches/HeDiffDefs/Hediffs_Implants.xml, SupportedThirdPartyMods.md
- Made some housekeeping changes to the Royalty implant patches
=> Patch EPOE-Forked: Royalty DLC expansion

Defs/SoundDefs/CasingSounds.xml
- https://discord.com/channels/278818534069501953/310869202892488705/1035301482007900271
=> Fix the casing impact sound

Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml
- Fixed a minor error in VFE-Mechanoid CombinationDefs.
=> Fix an error with CombinationDefs

Patches/Core/TraitDefs/Traits_Singular.xml
- Lowered the damage reduction percentage of the tough trait from 50% to 25%
- https://discord.com/channels/278818534069501953/322827713335394304/1035844562066882631
=> Tweak the Tough trait

Defs/Ammo/Rocket/90mmRecoilless.xml
- What it says on the tin, courtesy of Not a Bot #4184 on discord.
=> Add the 90mm recoilless rocket ammo

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml, Defs/Ammo/Advanced/164x284mmDemoShell.xml, Defs/Ammo/Advanced/66mmThermalBolt.xml, Defs/ThingDefs_Misc/Weapons_Ranged.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml, Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml
- Made sure the Legionary mech can spawn with ammo.
- Made robustness adjustments to mechanoid stats, weapons and loadouts.
- Adjusted mech weapons added and patched by CE to not have quality anymore, similar to their vanilla equivalents.
=> Mechanoid stuff adjustments

Patches/Core/ThingDefs_Races/Races_Animal_Arid.xml, Patches/Core/ThingDefs_Races/Races_Animal_Bears.xml, Patches/Core/ThingDefs_Races/Races_Animal_BigCat.xml, Patches/Core/ThingDefs_Races/Races_Animal_Birds.xml, Patches/Core/ThingDefs_Races/Races_Animal_Farm.xml, Patches/Core/ThingDefs_Races/Races_Animal_Giant.xml, Patches/Core/ThingDefs_Races/Races_Animal_Pet.xml, Patches/Core/ThingDefs_Races/Races_Animal_Rodentlike.xml, Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml, Patches/Core/ThingDefs_Races/Races_Animal_Tropical.xml, Patches/Core/ThingDefs_Races/Races_Animal_WildCanines.xml, Patches/Vanilla Animals Expanded - Royal Animals/ThingDefs_Races/Royal_Animals.xml, SupportedThirdPartyMods.md
- Patched the animals from VAE - Royal Animals based on the already patched animals in base game and mods.
- Consistency checks and housekeeping for vanilla animals.
=> Patch VAE-Royal Animals and vanilla animal housekeeping

Defs/Ammo/Rifle/556x45mmNATO.xml
Added 5.56 SBR ammoset, data in Sam's sheets
=> Added 5.56 SBR ammoset

Defs/Ammo/Pistols/454Casull.xml, Defs/Ammo/Pistols/460WMagnum.xml, Defs/Ammo/Pistols/500SWMagnum.xml, Defs/Ammo/Pistols/50AE.xml
- Added the new .460 S&W Magnum ammo.
- Made tweaks to some large caliber pistol cartridges' sharp AP values to bring them in more sane levels.
=> Add the new .460 S&W Magnum ammo and housekeeping

Patches/Core/ThingDefs_Misc/Weapons_Melee.xml, Patches/Rimsenal Collection/Core/Rimsenal_Melee.xml, Patches/Rimsenal Collection/Federation/ThingDefs_Misc/Fed_MeleeWeapons.xml, Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_MeleeWeapons.xml, Patches/Vanilla Factions Expanded - Classical/ThingDefs_WeaponsMelee.xml, Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Weapons.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Melee_Warcaskets.xml, Patches/Vanilla Factions Expanded - Vikings/Weapons_Crypto.xml, Patches/Vanilla Factions Expanded - Vikings/Weapons_Medieval.xml, Patches/Vanilla Weapons Expanded - Tribal/Melee_Neolithic.xml, Patches/Vanilla Weapons Expanded/Industrial_Melee.xml, Patches/Vanilla Weapons Expanded/Medieval_Melee.xml, Patches/Vanilla Weapons Expanded/Neolithic_Melee.xml, Royalty/Patches/ThingDefs_Misc/Weapons_BladelinkMelee.xml, Royalty/Patches/ThingDefs_Misc/Weapons_Melee.xml
- Some minor housekeeping regarding melee weapon tool chanceFactors, made the actual damaging tools have a better chance of being used. Some chanceFactor node were counterintuitive too which are addressed here.
=> Melee weapon chanceFactor tweaks

Source/CombatExtended/Harmony/Compatibility/Harmony_AlienRace.cs, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
Update for the method signature change introduced in https://github.com/erdelf/AlienRaces/commit/ac9d09187ec163613750fb79e3717520650108f2, and fix headgear sizing by using bodyWith rather than bodySizeFactor with the appropriate default value for humanlikes.
=> Fix Humanoid Alien Races compatibility patch

Patches/Biotech Prestige Mechlord Armor 1.4/Apparel_Mech.xml, SupportedThirdPartyMods.md
- Patch for Biotech Prestige Mechlord Armor. Duplicate of #2037 with some housekeeping.
=> Patch Biotech Prestige Mechlord Armor

Patches/Cybernetic Organism and Neural Network/Hediffs/CONN_CombatAdvancedBionics.xml, Patches/Cybernetic Organism and Neural Network/Hediffs/CONN_CombatBionics.xml, Patches/Cybernetic Organism and Neural Network/Hediffs/CONN_MindAlteringBionics.xml, Patches/Cybernetic Organism and Neural Network/Hediffs/CONN_ProductiveBionics.xml
New defNames for 1.4
Mod changed defNames for 1.4
Maybe I could add an or to each defName (defName="x" or defName="Y")
=> CONN defNames change

README.md
- Updated the steam workshop link for CE in the README file.
=> Update the steam workshop page link

Biotech/Patches/Bodies/Bodies_Mechanoid_Heavy.xml, Biotech/Patches/Bodies/Bodies_Mechanoid_Light.xml, Biotech/Patches/Bodies/Bodies_Mechanoid_Medium.xml, Biotech/Patches/Bodies/Mech_Centurion.xml, Biotech/Patches/Bodies/Mech_Diabolus.xml, Biotech/Patches/Bodies/Mech_Warqueen.xml, Patches/Core/Bodies/Bodies_Mechanoid/MechanicalCentipede.xml, Patches/Core/Bodies/Bodies_Mechanoid/MechanicalTermite.xml, Patches/Core/Bodies/Bodies_Mechanoid/Pikeman.xml, Patches/Core/Bodies/Bodies_Mechanoid/Scyther.xml
- Removed redundant patches for mechanoid bodies.
- Added missing patches for left-out body sections.
- Added missing bodyparts to certain mech bodies.
- Changed `/Defs` to `Defs` in the patches since the latter is faster.
=> Update mech bodies

Patches/Rimsenal Collection/Core/Apparel_RS_CE.xml, Patches/Rimsenal Collection/Enhanced Vanilla/Weapons_Ranged_CE.xml
Fixed compatibility issues by capitalizing thingDef properly in various patch operations.
=> Update Rimsenal Core and Augmented Vanilla Patch

Patches/Revia Race — biotech/PawnKindDefs/ReviaPawnKindDefs.xml, Patches/Revia Race — biotech/Scenario/Revia_Scenario.xml, Patches/Revia Race — biotech/ThingDefs_Misc/Weapons_Guns.xml, Patches/Revia Race — biotech/ThingDefs_Races/Race_Revia.xml, SupportedThirdPartyMods.md
Patch for biotech version of Revia race:
https://steamcommunity.com/sharedfiles/filedetails/?id=2893157989
Mostly the same as the original mod patch.
Just removed unused nodes and replaced useful
Need to patch biotech version for CE
=> Revia biotech patch.

Patches/Rimsenal Collection/Security/Ammo_Security.xml, Patches/Rimsenal Collection/Security/Patch_Security.xml
Mod name got updated, so fixed the findmod op.
=> Rimsenal Sec Fix

Patches/RH2 Faction - VOID/Monsters/Races.xml, Patches/RH2 Faction - VOID/Monsters/Races_Evolved.xml
- Patched the two newly added monsters.
- Updated the melee attack cooldown of all monsters as they were decreased by various amounts in the original mod.
- Updated the Reaper's melee tool AP.
=> Update RH2 VOID's patch

Patches/Erin's Final Fantasy Races/PatchBodies_AuRa.xml, Patches/Erin's Final Fantasy Races/PatchBodies_MQ.xml, Patches/Erin's Final Fantasy Races/PawnKinds_AuRa.xml, Patches/Erin's Final Fantasy Races/PawnKinds_MQ.xml, Patches/Erin's Final Fantasy Races/PawnKinds_Viera.xml, Patches/Erin's Final Fantasy Races/Race_AuRa.xml, Patches/Erin's Final Fantasy Races/Race_MQ.xml, Patches/Erin's Final Fantasy Races/Race_Viera.xml, SupportedThirdPartyMods.md
- All-in-One Erin's Races patches
- obviously, since the mod mentioned is a combination of Erin's Races like AuRa, Miqo'te, and Viera in one package
=> Patch - Erin's Final Fantasy Races

Patches/Erin's Auronya/PawnKinds_Auronya.xml, Patches/Erin's Auronya/Race_Auronya.xml, SupportedThirdPartyMods.md
- Koyan Race patch
- Koyan Pawnkind patch
- because nyaa cat race
=> Patch - Erin's Auronya - HAR Edition

Patches/Medieval Medicines 1.4 Medieval Overhaul Edition/Hediff_MM.xml, SupportedThirdPartyMods.md
- Mechanical Limbs patches
- Basic Prosthetic Limbs patches
- Artificial Limbs patches
- Ambroisen Limbs patches
- medieval transhumanism yes
=> Patch - Medieval Medicines 1.4 Medieval Overhaul Edition

Defs/Ammo/GENERIC/LauncherGrenade.xml, Defs/Ammo/GENERIC/ShotgunShell.xml, Defs/Ammo/Rocket/PG15V.xml, Defs/Ammo/Shell/105mmHowitzer.xml, Defs/Ammo/Shell/155mmHowitzer.xml, Defs/Ammo/Shell/60mmMortar.xml, Defs/Ammo/Shell/762x385mmRCannon.xml, Defs/Ammo/Shell/81mmMortar.xml, Defs/Ammo/Shell/90mmCannon.xml
- Added the research prerequisite to a couple ammo types that were missed in the previous PRs.
=> Microelectronics research for the missed EMP ammo

Patches/Medieval Overhaul/MO_Apparel_Armor.xml, Patches/Medieval Overhaul/MO_Apparel_Helmets.xml, Patches/Medieval Overhaul/MO_Apparel_Misc.xml, Patches/Medieval Overhaul/MO_Items.xml, Patches/Medieval Overhaul/MO_Materials.xml, Patches/Medieval Overhaul/MO_Races.xml, Patches/Medieval Overhaul/MO_Shields.xml, Patches/Medieval Overhaul/MO_Siege_Ballistas.xml, Patches/Medieval Overhaul/MO_Siege_Scorpio.xml, Patches/Medieval Overhaul/MO_Siege_Trebuchet.xml, Patches/Medieval Overhaul/MO_Weapons_Melee.xml
- Attachments Armor
- Ulric Armor (Adorned)
- Named Weapons
- Siege buildings (Scorpio, Repeater-Ballista)
- Farm animals (Hampshire, Gloucestershire, Northern Boar, Angus, Ravelder)
- Wild animals (Daer, Large Cobras, Giant Constrictors, Lindwurm, Dire Boar, Schrat)
- Indentation changes
- XPath changes (from /Defs to Defs)
- changing horn related from melee weapon to luxury item (enabling the commented-out patch)
- yes because medieval (and also fixing a lot of mess, literally)
=> Medieval Overhaul Update

Patches/Medieval Overhaul/MO_Materials.xml
- wood
- wood
- Contributes towards WOOD economy
- because the wood is RAW
- wood
=> Raw Wood Patch - Medieval Overhaul

Patches/Medieval Overhaul/MO_Ammo.xml, Patches/Medieval Overhaul/MO_Weapons_Ranged.xml
- Handgonne Shots projectile
- changed Handgonne to be One-Handed Blunderbuss, since it was like flintlock pistol last time so it's not as accurate like Handgonne from Battle Brothers (which Medieval Overhaul based of)
- Indentation changes
- https://battlebrothers.fandom.com/wiki/Handgonne
- because yes pew pew
=> Handgonne Tweaks - Medieval Overhaul

Patches/RimFantasy - Medieval Overhaul Edition/Patch_RF_Arcane_Melee.xml
- Arcane Halberds patch
- yes wizard halberdier
=> Update - RimFantasy: MO Edition

Patches/Medieval Overhaul/MO_Siege_Misc.xml
- fillPercent adjustment for Palisade Embrasures
- why yes wooden wall sticks
=> Housekeeping - Medieval Overhaul

Patches/ReGrowth - Extinct Animals/Extinct_Birdlike.xml, Patches/ReGrowth - Extinct Animals/Extinct_Bodies.xml, Patches/ReGrowth - Extinct Animals/Extinct_Mammals.xml, Patches/ReGrowth - Extinct Animals/Extinct_Resources.xml, Patches/ReGrowth - Extinct Animals/Extinct_Rodentlikes.xml, SupportedThirdPartyMods.md
- patches for Woolly Mammoth, Woolly Rhinoceros, Woolly Stegosaurus, Sabertooth Squirrel, Dodo, Synthetion, Arctic Drak, Velociraptor, Megalenhydris, Terror Bird, and Thrinaxodon.
- patches for Dinosaur Hides, Woolly Wools, and Mammoth Tusk
- patches for Bodyparts
- because yes ice age mammoth
=> Patches - ReGrowth: Extinct Animals

Patches/T's Samurai Faction/T_Samurai_Weapons_Ranged.xml
- changed non-existing XPath patches for Shuriken
- shuriken go shoo shoo
=> Housekeeping - T's Samurai Faction

Patches/RimFantasy - Medieval Overhaul Edition/Patch_RF_Arcane_Melee.xml
- melee tools for Arcane Spear and Halberd
- to make it synchronize with melee tools weapon counterpart from Medieval Overhaul
=> Adjustment - RimFantasy: Medieval Overhaul Edition

Patches/T's Conversion Staff/Patch_TCS_Staff.xml, SupportedThirdPartyMods.md
- patch for Conversion Staff
- because yes reeducation staff
=> Patch - T's Conversion Staff

Patches/RimFantasy - House Doyle/Patch_RFDoyle_Armor.xml, Patches/RimFantasy - House Doyle/Patch_RFDoyle_Jewelry.xml, Patches/RimFantasy - House Doyle/Patch_RFDoyle_Melee.xml, Patches/RimFantasy - House Doyle/Patch_RFDoyle_Ranged.xml, Patches/RimFantasy - House Doyle/Patch_RFDoyle_Shield.xml, SupportedThirdPartyMods.md
- House Doyle Melee Weapons
- House Doyle Bows
- House Doyle Armor
- House Doyle Shield
- yes arcane purple wizard stuff
=> Patch - RimFantasy: House Doyle

Patches/RimNauts 2/ThingDefs_Items/SpaceSuit_CEpatch.xml, SupportedThirdPartyMods.md
Added support to the space armor in rimnauts 2
Compared the armor values with SOS2 evo suit
- [] Playtested a colony (specify how long)
=> RimNauts 2 spacesuit patch

Ideology/Patches/ThingDefs_Misc/Race_Animal_Dryads.xml, Patches/Alpha Memes/HediffDefs/Hediffs_Global_Misc.xml, Patches/Alpha Memes/ThingDefs_Races/Races_UnshackledDryad.xml, SupportedThirdPartyMods.md
- Patched the dryad and a couple hediffs from Alpha Memes.
- A melee tool consistency check for Ideology dryads.
=> Patch Alpha Memes

Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs
Make it so that mech ammo beacons only drop ammo if the cluster still has active mechanoids, so that they can't be milked for infinite mech ammo. Do this by finding the Lord associated with the cluster and checking that it still has pawns attached.
We could try to attach the beacons themselves to the cluster's lord instead, but that doesn't seem doable without a transpiler, so the current post-spawn setup approach seems easier to maintain. It also wouldn't work for clusters that predate this patch.
=> Ensure mech ammo beacons don't provide infinite ammo

Defs/Ammo/Advanced/20x105mmCharged.xml
- Minor adjustment in the ammo description.
=> Update 20x105mm's description

Patches/Altered Carbon/ThingDefs_Apparel.xml, SupportedThirdPartyMods.md
- Updated the mod's name as it is called Altered Carbon now.
- DefNames were changed that also needed an update...
=> Altered Carbon patch update

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/Utilities/Tracking/ThingsTrackingModel.cs
Reverts CombatExtended-Continued/CombatExtended#2201
=> Revert "Fix ThingsNearSegment, make average projectiles apply suppression around travel path"

Defs/Drugs/Psychite_Psycho.xml
- Minor adjustments to the drug.
- Made it compatible with drug addiction genes.
=> Update Psycho for Biotech

Patches/Alpha Genes - Insectoid Mutations/HediffDefs/Hediffs_Mutations_CE.xml, SupportedThirdPartyMods.md
Added Alpha Genes insectoid mutations patch.
Current VFE-I patch for Hediffs
Just a copy paste from VFE-Insectoids with defName change
=> Alpha genes insectoid mutations

Patches/Core/ThingDefs_Misc/Weapons_Melee.xml, Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyBladelinkMelee.xml, Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyMelee.xml
- Made some adjustments to some melee weapons based on the updated melee weapon sheet, some of the used data was outdated.
- https://docs.google.com/spreadsheets/d/11e6FkTQvZiJpq7DpXUk9JSXBSq9enrx0DQhTTJ2xH7c/edit#gid=647442519
=> Minor melee weapon tweaks

Patches/Medieval Overhaul/MO_Weapons_Melee.xml, Patches/RimFantasy - Medieval Overhaul Edition/Patch_RF_Arcane_Melee.xml
- Medieval Overhaul's Longswords
- RimFantasy's Arcane Longswords
- adjustment is required following the latest updated weapon spreadsheet stats
=> Adjustment - Medieval Overhaul and RimFantasy: MO Edition

Patches/RimFantasy - House Doyle/Patch_RFDoyle_ArcaneWeapon.xml, Patches/RimFantasy - House Doyle/Patch_RFDoyle_Projectiles.xml
- Arcane weapons by the mod
- yes purple arcane wizardry good
=> Additional Patches - RimFantasy: House Doyle

Defs/Ammo/Rifle/4570Gov.xml
- What it says on the tin, it's the black powder version of the ammo.
=> Added the .45-70 Trapdoor Ammoset

Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_Ammo_Spacer.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_Buildings_Mech.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_Buildings_Security_Turrets.xml
- Patched the turrets in the mod which were unpatched.
- They are almost carbon-copies of the turrets in VFE-Mechs so the patches are similar.
=> Reinforced Mechanoid 2 turrets

About/About.xml, About/Manifest.xml, Patches/Vanilla Factions Expanded - Empire/Buildings_Security_Turrets.xml
Various last-minute things for the 5.1 release.
- Increment mod version number.
- Fix FindMod typo.
=> 5.1 Release Tweaks

Patches/ODZ Stalingrad - Uniforms/ThingDefs_Apparel.xml
- Update the FindMod from 1.3 to 1.4 so it works.
=> Update Stalingrad Uniforms Patch

Patches/Alpha Genes/HediffDefs/Hediffs_Attacks.xml
- Patched the newly added hediffs in AG.
- https://github.com/juanosarg/AlphaGenes/commit/ccb593e7c09726ad60a2df71bc543361604ee2a6#diff-677ec1f8a5ea5fc7ab21a35cd001ba5950fddc633d57073c26cc2c4b5303ec57
=> Patch Alpha Gene's new hediffs

Defs/Ammo/Medieval/BlunderbussShot.xml, Defs/Ammo/Medieval/CannonBall.xml, Defs/Ammo/Pistols/460WMagnum.xml, Defs/Ammo/Pistols/500SWMagnum.xml
=> Add the blunderbuss shot ammo

Patches/More Persona Traits/HeldWeaponTraits.xml, SupportedThirdPartyMods.md
just patch some armor values.
Patch More persona traits
https://en.wikipedia.org/wiki/Liquid_Armor
- Additional use for animals
- Anachronistic
- Breaks realism theme
=> Patch More persona traits

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Heavy.xml
- Changed the Tunneler's left claw to be a crusher claw.
- https://discord.com/channels/278818534069501953/322827713335394304/1063862034065805462
=> Tweak the Tunneler's melee tool

Defs/Tutor/Concepts_NotedSelfshow.xml
- Update the learning helper about loading benches being unlocked after Gunsmithing research.
=> Update ammo bench's learning helper tip

Patches/RH2 Faction - VOID/Monsters/Races.xml, Patches/RH2 Faction - VOID/Monsters/Races_Evolved.xml
- Made tweaks to the patches for the monsters to accommodate for the nerfs upstream.
=> Update VOID's patch

Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml
- What it says on the tin, it was using the one added by CE which is now in a man-made charge turret style.
=> Fix the mech mini-blaster turret's texture

Patches/ↁ Elves/AnimalDefs.xml, Patches/ↁ Elves/PawnKindDefs.xml, Patches/ↁ Elves/ThingDefs_Apparel.xml, Patches/ↁ Elves/ThingDefs_Headgear.xml, Patches/ↁ Elves/ThingDefs_MeleeWeapon.xml, Patches/ↁ Elves/ThingDefs_Misc.xml, Patches/ↁ Elves/ThingDefs_RangedWeapon.xml, Patches/ↁ Elves/ThingDefs_Shields.xml, SupportedThirdPartyMods.md
- 2 Animal
- 29 Apparel
- 20 Headgear
- 6 Pauldron
- 1 Utility Apparel
- 4 Shield
- 17 Melee Weapon
- 5 Ranged Weapon
- because yes elves good
- knife ears
=> Patch - ↁ Elves

Defs/Ammo/Advanced/12x72mmCharged.xml, Defs/Ammo/Advanced/20x105mmCharged.xml, Patches/Apex - Rimworld Legends/ApexRimworldLegends_AmmoPatch.xml
what it says on the tin
just fix a missed ammo texture path
=> fix apex ammo using old texture path

Patches/Kit's VFE Weapons/Ammo/Ammo_KitPlasma.xml, Patches/Kit's VFE Weapons/DamageDefs/DamageDefs_Vikings.xml, Patches/Kit's VFE Weapons/ThingDefs_Misc/Weapons.xml, SupportedThirdPartyMods.md
What it says on the tin,
NOTE: The whitespace in the end is NOT a typo.
add support for Kit's VFE weapons Continued,
the blackpowder weapons update uses the same name.
=> add kit's VFE weapons Continued

Patches/Alpha Animals/BodyDefs/AlphaAnimals_CE_Patch_Bodies.xml, Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_VerbShootCE.xml, Patches/Alpha Genes/ThingDefs_Races/Races_OcularSlinger.xml
- Patched the newly added Ocular Slinger, it's almost the same as the BarbSlinger from Alpha Animals.
- Updated Alpha Animal's BarbSlinger's ranged attack.
=> Update Alpha Gene's patch

Biotech/Patches/Bodies/Bodies_Mechanoid_Medium.xml, Patches/Core/Bodies/Bodies_Animal_Bird/Bird.xml, Patches/Core/Bodies/Bodies_Animal_Insect/Beetlelike.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/Monkey.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithClawsTailAndJowl.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithHooves.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithHoovesAndHorn.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithHoovesAndHump.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithHoovesAndTusks.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithHoovesTusksAndTrunk.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithPaws.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithPawsAndTail.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/TurtleLike.xml, Patches/Core/Bodies/Bodies_Animal_Snake/Snake.xml, Patches/Core/Bodies/Bodies_Mechanoid/Pikeman.xml
- Updated and completed the body patches of vanilla and DLC pawns.
=> Vanilla and DLC pawn body patch update

Defs/ThingDefs_Misc/Apparel_Shield.xml
- What it says on the tin, it's a medieval item unlocked at smithing research.
=> Change the melee shield's tech level to medieval

Patches/Core/Bodies/Bodies_Animal_Quadruped/TurtleLike.xml
- What it says on the tin, I had forgotten to include it in the patch.
=> Add natural armor coverage to turtle beaks

Patches/Android Tiers Reforged/ThingDef_Races/AlienRace_Androids.xml, Patches/Android Tiers Reforged/ThingDef_Races/Races_Animals.xml
- Adjusted some values, added some new patches for stuff that was forgotten and balance tweaks in general.
=> Update ATR's race patches

Defs/Ammo/HighCaliber/55Boys.xml, Defs/Ammo/HighCaliber/7.92x94mm Patronen.xml
- What it says on the tin for 7.92x94mm and .55 Boys. The values uses were not based on proper sources.
=> Fix a couple high caliber cartridges' sharp AP

Patches/Vanilla Factions Expanded - Pirates/AbilityDefs/Abilities.xml, Patches/Vanilla Factions Expanded - Pirates/Drugs/Drug_Bases.xml, Patches/Vanilla Factions Expanded - Pirates/Misc/Hediffs_Casts.xml, Patches/Vanilla Factions Expanded - Pirates/Misc/Precepts_Role.xml, Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Junkers.xml, Patches/Vanilla Factions Expanded - Pirates/PawnKindDefs/PawnKinds_Mercenaries.xml, Patches/Vanilla Factions Expanded - Pirates/Scenario/Scenario.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VFEIMeleeSpacer.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWECRangedWarcasket.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWELRangedWarcasket.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWENLRangedWarcasket.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VWEQRangedWarcasket.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Various.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets_Spacer.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Melee_Warcaskets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Artillery.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Turrets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Weapons_Mech.xml
- Tweaked and gave proper recoil values to the guns.
- Adjusted the weapons ranges and warmup times to be more in line with normal and already existing counterpart weapons.
- Rechambered the slug rifle into 20mm NATO and made it a DMR, it fires faster than a base game sniper rifle implying it's a DMR.
=> Update VFE-Pirates' patch

Defs/Ammo/Advanced/20x105mmCharged.xml, Defs/Ammo/HighCaliber/20x139mm.xml
- What it says on the tin, it's a bit heavier and faster version of 20x128mm Oerlikon cartridge.
- Tweaked 20x105mm's velocity from 1000m/s to 1100m/s as it was slow in comparison.
=> Add the 20x139mm cartridge

Patches/Grimworld Lasguns/lasgun ammo.xml, Patches/Grimworld Lasguns/lasguns.xml, SupportedThirdPartyMods.md
- What it says on the tin, the mod name was changed by the author or something...
=> Fix the mod name of Grimworld Lasguns

Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_ArmorBlunt.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_ArmorSharp.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_CombatMelee.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_CombatRanged.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_Default.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_Defense.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_HeavyUltraHeavy/HeavyUltraHeavy_EMPResistance.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_ArmorBlunt.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_ArmorSharp.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_CombatMelee.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_CombatRanged.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_Default.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_Defense.xml, Patches/Biotech Mech Stuff Elongated - Mechanoid Upgrades V2/Booster_LightMedium/LightMedium_EMPResistance.xml, SupportedThirdPartyMods.md
- Patch Biotech Mech Stuff Elongated - Mechanoid Upgrades V2
- Stat bonuses needed adjustment and nerfing in some cases.
=> Patch Biotech Mech Stuff Elongated V2

Defs/Ammo/Pistols/7.5FK.xml
=> Add the 7.5 FK ammo

Patches/Glitter Weaponry/Ammo.xml, Patches/Glitter Weaponry/RangedSpacer.xml, Patches/Glitter Weaponry/RangedSpacer_Heavy.xml, SupportedThirdPartyMods.md
=> Patch Glitter Weaponry

Source/CombatExtended/Contrib/MechTakeAmmoCE/Core/CompMechAmmo.cs
[StaticConstructorOnStartup]
One more yellow letter
=> added StaticConstructorOnStartup for mech take ammo

Patches/Android Tiers Reforged/Hediffs/Hediffs_Android.xml, Patches/Android Tiers Reforged/ThingDef_Misc/Apparel_Packs.xml, Patches/Android Tiers Reforged/ThingDef_Misc/Weapons_Mech.xml, Patches/Android Tiers Reforged/ThingDef_Races/Races_Animals.xml
- Three new bodyparts that needed patching.
- Updated some of the existing patches.
- https://github.com/RWDevathon/Android-Tiers-Reforged/commit/d407a08ea7974c216d77c8322a78dc5e5bf8210b#diff-a21ee0cf3aed21f9725aaeda8c83fde7d7ea75e603035e663b2b0bb1ae4d58e4
=> Patch ATR's new bodyparts

Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml, Patches/Android Tiers Reforged/ThingDef_Misc/Weapons_Mech.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_PlasmaWeaponry.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VFEIMeleeSpacer.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Melee_Warcaskets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
see title
- Contributes towards #2243 
- (the first line)
More headaches from patchers
=> Use weapon's drawsize if GunDrawExtension is not present

Defs/Ammo/AmmoBases.xml
Add a new BulletBaseCE
For third party mods to adapt before actual change takes place
Have players whine and cry about CE breaking their saves.
=> Add bulletBaseCE

Defs/Ammo/Pistols/25ACP.xml, Defs/Ammo/Pistols/32ACP.xml, Defs/Ammo/Pistols/762x25mmTokarev.xml
1. Reduced 7.62 Tokarev's sheet velocity (524 m/s to 497 m/s) and made corresponding adjustments to damage and AP.
2. Increased damage and blunt AP for the .32 ACP from sheet for an increased projectile mass (3.89 g to 4.5 g).
3. Increase .25 ACP base sharp AP from 2 to 2.5 mm.
1. While checking 7.63 Mauser's data, I realized the sheet used an especially hot (524 m/s) 85 gn FMJ loading for 7.62 Tokarev that I haven't actually been able to find any data on--where these initial values came from, I'm not sure. In any case, I've reduced it to tamer (497 m/s) loading of the same 85 gn FMJ that I can verify exists. This new value is more accurate to the round coming out of the longer barrel of an SMG than a pistol (which come in around 450 m/s), but I think this is acceptable. This ~5% …
=> Pistol Ammo Tweaks

Patches/Nukes/Ammo_Nuclear.xml, Patches/Nukes/IEDs_Nuclear.xml, Patches/Nukes/Projectiles_Nuclear.xml
Just changed patched mod name
https://steamcommunity.com/workshop/filedetails/?id=1777069843
=> [1.3] Nukes -> [1.4] Nukes.

Source/CombatExtended/Contrib/MechTakeAmmoCE/Core/CompMechAmmo.cs
remember to unload before reload
=> fix mech auto reload

Defs/Stats/Stats_Weapons_Ranged.xml, Languages/English/Keyed/Misc_Gameplay.xml, Source/CombatExtended/CombatExtended/DefOfs/CE_StatDefOf.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_OneHandedness.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_VanillaExpandedFramework.cs
-As mentioned in title
-Also, make our own one display "No" for not one handed weapons
=> Get rid of useless VE shield stat

Patches/Vanilla Factions Expanded - Empire/Apparel_Headgear.xml
- Update the Janissary helmet's patch, it's a perfect gas mask in the mod now.
=> Update VFE Empire's patch

Patches/RH2 Rimmu-Nation² - Clothing/Backpacks_CE.xml, Patches/RH2 Rimmu-Nation² - Clothing/Bandana_Balaclava_Scarf.xml, Patches/RH2 Rimmu-Nation² - Clothing/Jacket_Rimmu.xml, Patches/RH2 Rimmu-Nation² - Clothing/Shirt_Rimmu.xml
- Patched the newly added items to the mod.
=> Update RH2 Clothing's patch

Defs/Ammo/Rifle/280British.xml, Defs/Ammo/Rifle/485x49mm.xml
- .280 British rifle ammo
- 4.85x49mm rifle ammo
Cartridge data: 
=> Implement 4.85x49 and .280 British ammo

Patches/Vanilla Animals Expanded - Caves/ThingDefs_Races/Caves_Bodies.xml, Patches/Vanilla Animals Expanded - Waste Animals/Bodies/Patch_Bodies_Animals.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Items/WasteAnimals_Items.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Misc/WasteAnimals_Projectiles.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Hydra.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Megatardi.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Pestigator.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Toxafox.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Toxbear.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Toxiguana.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Toxlion.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Toxscorpion.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Wasteboar.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Wastedeer.xml, Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Wasteffalo.xml, Patches/Vanilla Factions Expanded - Insectoids/ThingDefs_Races_VatGrown/Races_Gigascorpion.xml, SupportedThirdPartyMods.md
=> Patch VAE - Waste Animals

Patches/Vanilla Races Expanded - Sanguophage/AbilityDefs/Abilities_SingleUse.xml, Patches/Vanilla Races Expanded - Sanguophage/HediffDefs/HediffDef_Deathrest.xml, Patches/Vanilla Races Expanded - Sanguophage/HediffDefs/HediffDef_SharpTalons.xml, Patches/Vanilla Races Expanded - Sanguophage/ThingDefs_Items/HemogenPacks.xml, Patches/Vanilla Races Expanded - Saurid/HediffDefs/HediffDef_SauridClaws.xml, SupportedThirdPartyMods.md
=> Patch VRE - Sanguophage

Patches/Cybernetic Organism and Neural Network/Hediffs/CONN_CombatAdvancedBionics.xml
- Since update stat for HP was moved off from mod to framework
=> Fixed errror for Cybernetic Organism and Neural Network

Defs/ThingDefs_Buildings/Buildings_Defenses.xml, Defs/ThingDefs_Buildings/Buildings_Production.xml
- Made the Embrasures, Barbed Wires and Ammo bench paintable.
=> Make CE's buildings paintable

Patches/More Medieval Helms and Armor/Apparel.xml, Patches/More Medieval Helms and Armor/Armor.xml, Patches/More Medieval Helms and Armor/Footwear.xml, Patches/More Medieval Helms and Armor/Handwear.xml, Patches/More Medieval Helms and Armor/Headgear.xml, Patches/More Medieval Helms and Armor/Leggings.xml, SupportedThirdPartyMods.md
- What it says on the tin, credit for the patch goes to Whimsical Porch Rock#0988 on discord.
_Lamellar Armor might need further rebalancing._
=> Patch More Medieval Helms and Armor

Patches/Core/ThingDefs_Misc/Apparel_Hats.xml, Patches/Core/ThingDefs_Misc/Apparel_Various.xml, Royalty/Patches/ThingDefs_Misc/Apparel_RoyaltyArmor.xml, Royalty/Patches/ThingDefs_Misc/Apparel_RoyaltyHeadgear.xml
- Patched the missing power armor items' description and fixed the description structure of the existing ones.
=> Item description patch housekeeping

Defs/Ammo/HighCaliber/20x110mmHispano.xml, Defs/Ammo/Pistols/38SW.xml, Defs/Ammo/Pistols/38Super.xml, Defs/Ammo/Pistols/44Magnum.xml, Defs/Ammo/Pistols/44SWSpecial.xml, Defs/Ammo/Pistols/454Casull.xml, Defs/Ammo/Pistols/45Colt.xml, Defs/Ammo/Pistols/45Schofield.xml, Defs/Ammo/Pistols/460SWMagnum.xml, Defs/Ammo/Rifle/17HMR.xml, Defs/Ammo/Rifle/22Hornet.xml, Defs/Ammo/Rifle/22WMR.xml, Defs/Ammo/Rifle/243Winchester.xml, Defs/Ammo/Rifle/30-30Winchester.xml, Defs/Ammo/Rifle/38-55Winchester.xml, Defs/Ammo/Rifle/458SOCOM.xml, Defs/Ammo/Rifle/50Beowulf.xml, Defs/Ammo/Rifle/8x50mmRMannlicher.xml, Defs/Ammo/Shotgun/410Bore.xml
Added the following cartridges (Cleaned up version of #2446):
- .38 S&W
- .38 Super
- .44 Special
- .45 Schofield
- .17 HMR
- .22 Hornet
- .22 Magnum
- .243 Winchester
- .30-30 Winchester
- .38-55 Winchester
- .458 SOCOM
- .50 Beowulf
- 8x50mmR Mannlicher
- Fixed two minor typos
- Ammo ~~bloat~~ variety for patching or whatever...
=> New cartridges and housekeeping

Reference.py
Added 2 lines after functions and classes to make the code more immediately readable
=> Format Reference.py

Make.py
N/A
I added 2 spaces between functions and data classes to promote readability. I also removed some double spaces and triple spaces within the functions themselves for readability as well.
N/A
- Formatting and readability at a quick glance
N/A
N/A
=> Updated make.py format

Patches/Fallout New Vegas - Elite Riot Gear/Apparel_RiotGear.xml
=> Add NV to FO New Vegas' Riot Helmet

Patches/High Tech Laboratory Facilities/ThingDef_Apparel.xml, SupportedThirdPartyMods.md
- What it says on the tin, it had some apparel needing a patch.
=> Patch High Tech Laboratory Facilities

Patches/Impact Weaponry/Addon Weapons/AthenaRanged.xml, Patches/Impact Weaponry/Addon Weapons/ImpactMelee.xml, Patches/Impact Weaponry/Addon Weapons/PiratesRanged.xml, Patches/Impact Weaponry/Flecks.xml, Patches/Impact Weaponry/ImpactAmmo.xml, Patches/Impact Weaponry/ImpactMelee.xml, Patches/Impact Weaponry/ImpactRanged.xml, SupportedThirdPartyMods.md
- What it says on the tin, patch provided by DeterminismCarl.
Closes #2465
=> Patch Impact Weaponry

Patches/The Corporation - Mort's Factions/Corporation_TraderKinds.xml, Patches/The Corporation - Mort's Factions/Pawnkinds_Corporation.xml, SupportedThirdPartyMods.md
- Patch new pawnkinds and traders added by the mod.
=> Patch Mort's Corporate Faction

Patches/Alpha Genes/HediffDefs/Hediffs_Mechanitor.xml
- A new Hediff needed patching.
=> Update Alpha Genes' patch

Patches/EPOE Forked/Bionics_Patch.xml
- Patched the tactical bionic eye.
=> Update to EPOE forked patch

Patches/Vanilla Races Expanded - Android/Scenario_Android.xml, SupportedThirdPartyMods.md
- The added scenario needed patching to include ammo, the rest of the mod does not need patching.
=> Patch VRE Android

Defs/Ammo/Neolithic/Javelins.xml, Defs/ThingDefs_Misc/Apparel_Carrying.xml, Defs/ThingDefs_Misc/Apparel_Headgear.xml, Defs/ThingDefs_Misc/Apparel_Shield.xml, Defs/ThingDefs_Misc/Weapons_Ranged.xml, Defs/ThingDefs_Misc/Weapons_RangedNeolithic.xml, Defs/ThingDefs_Misc/Weapons_Spotting.xml
- Added proper crafting skill checks to various added items in CE based on vanilla counterparts and similar things.
- Some housekeeping and input data checks and fixes for the Javelins.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit?usp=drive_web&ouid=116906287676220316241
=> Skill checks and housekeeping

Patches/Miho Race/Ammo/Ammo_Miho_Advanced.xml, Patches/Miho Race/Ammo/Ammo_Miho_Industrial.xml, Patches/Miho Race/ThingDefs_Misc/Miho_Apparel.xml, Patches/Miho Race/ThingDefs_Misc/Miho_Apparel_Special.xml, Patches/Miho Race/ThingDefs_Misc/Weapons_Mechanoid.xml, Patches/Miho Race/ThingDefs_Misc/Weapons_Melee.xml, Patches/Miho Race/ThingDefs_Misc/Weapons_Ranged.xml, Patches/Miho Race/ThingDefs_Races/Race_MihoMech.xml
- Patched new Miho Mechanoid (Bulgasal Grenade)
- Patched new weapon for Miho Mechanoid (57mm Grenade Launcher)
- Add new 57mm ammo set
- Patched new Miho gas mask (apparel)
- Patched Miho pistol
- Fixing some apparel patch which cause red line errors
-  Close #2509 
- I am playing Miho colony right now. Wanna play with new features.
=> Miho patch update

Patches/Industrial Melee Weaponry/Weapons_Melee.xml
- Patch for Industrial Melee Weapons.
=> Industrial Melee Patch

Source/CombatExtended/Compatibility/VanillaExpandedFramework.cs
Field activity check
Missed field activity check
Reduced lag pikes
- Closes #2519
=> VFE LagFix + field activity check

Patches/Core/Misc/ApparelLayerDefs/ApparelLayerDefs.xml
- Added ModExtension patch operation to eye cover layer.
- Closes #1158
- Closes #2490
- Thanks to aedbia from #2490 for https://steamcommunity.com/sharedfiles/filedetails/?id=2985256508
=> Eye cover apparel layer patch

Source/ArtilleryCompat/ArtilleryCompat.csproj, Source/BetterTurretsCompat/BetterTurretsCompat.csproj, Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/GUI/Windows/Window_AttachmentsDebugger.cs, Source/CombatExtended/CombatExtended/GUI/Windows/Window_GiveAmmoAmountSlider.cs, Source/MiscTurretsCompat/MiscTurretsCompat.csproj, Source/MultiplayerCompat/MultiplayerCompat.csproj, Source/VehiclesCompat/VehiclesCompat.csproj
- A method had become obsolete which is fixed.
=> Update reference package versions

Defs/Ammo/AmmoBases.xml
- Removed the duplicate BaseBullet node as a follow-up to #2389.
=> Remove the BaseBullet duplicate

Patches/Vanilla Psycasts Expanded - Hemosage/AbilityDefs/AbilityDefs_Patch.xml, Patches/Vanilla Psycasts Expanded - Hemosage/ThingDefs/Projectile_Tweaks.xml, SupportedThirdPartyMods.md
- What it says one the tin, a couple abilities and their tied projectiles needed tweaking.
(Even after giving the base armor penetration node to the projectiles, both behave very oddly and seem to ignore any armor on the target.)
=> Patch VPE Hemosage

Patches/Matter Manipulator/MatterManipulator.xml
Added patch for mod5s.mattermanipulator (matter manipulator) mod, so that it stops meleeing out of melee position ;)
=> Patch for  mod5s.mattermanipulator

About/About.xml, About/Manifest.xml
- Increment mod version number for 5.3, since I forgot to last time.
=> Increment Mod Version

Defs/Ammo/Advanced/10x18mmCharged.xml, Defs/Ammo/Pistols/50AE.xml, Defs/Ammo/Pistols/9x18mmMakarov.xml, Defs/Ammo/Rifle/303British.xml, Defs/Ammo/Rifle/7.92x57mmMauser.xml, Defs/Ammo/Rifle/75x54mmFrench.xml, Defs/Ammo/Rifle/77x58mmArisaka.xml
- Minor consistency checks and tweaks for certain cartridge AP values based on muzzle energy and velocity comparisons.
=> Minor armor penetration tweaks

Defs/Ammo/Pistols/500SWMagnum.xml
- Fixed .500 S&W Magnum's speed value.
=> Minor typo fix

Patches/Core/ThingDefs_Buildings/Buildings_Security.xml
- What it says on the tin, similar to #2373.
=> Add base damage to incendiary traps

Patches/K4G Rimworld War 2/ThingDefs_Misc/BritishWeapons_Ranged.xml, Patches/K4G Rimworld War 2/ThingDefs_Misc/WW2_Grenades.xml
updated file path to textures in the (not yet refactored) replacement defs for UK weapons
=> K4G RWW2 UK weapons filepath quickfix

Patches/Vanilla Races Expanded - Highmate/HighmateBondEffectHediffs/HighmateBondEffectHediffs.xml, SupportedThirdPartyMods.md
- What it says on the tin, just a couple minor value changes.
=> Patch VRE Highmate

Patches/Impact Weaponry/ImpactAmmo.xml
- What it says on the tin, just a quick fix for recipe products.
=> Impact Weaponry quickfix

Patches/Erin's Auronya Biotech/Auronya_Hediffs_BodyParts.xml, Patches/Erin's Shisune/Shisune_Hediffs_BodyParts.xml, SupportedThirdPartyMods.md
- What it says on the tin, patch two gene that give melee tools.
=> Patch for Erin's Shisune and Erin's Auronya

Patches/DD House Sanguin/Mods/Medieval Overhaul/Bloodwine_MO.xml, Patches/DD House Sanguin/Mods/RimFantasy - Medeival Overhaul/Blood Weapons.xml, Patches/DD House Sanguin/Mods/Vanilla Faction Expanded Medieval/BloodWine_VFEM.xml, Patches/DD House Sanguin/ThingDefs_MeleeWeapons.xml, Patches/DD House Sanguin/ThingDefs_Misc.xml
- Updated House Sanuin compatibility patch. Original mod moved stuff that broke the patch
- Patched new items that mod had added since last patch
- Moved patches for the mods additional content to separate folders for easier patching in future
- RW was throwing errors when attempting to load with CE and House Sanguin
=> House Sanguin Patch Fix

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/Harmony/Harmony_CompProjectileInterceptor_PostPreApplyDamage.cs
- Royalty skipbarrier break fix
- Fixed dealing multiple instances of damage
- Fixed centurion shield recharge
- Barrier unbreakable in vanilla RW
=> Shield fix

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
- Code handling ingesting from inventory was updated.
- Teetotaler pawns will be allowed to take drugs if they have dependency genes.
- Royal pawns will refuse to eat food that doesn't match their royal title, unless they're starving, ascetic, or it provides joy when consumed.
- Pawn will refuse to ingest drugs if their ideology forbids it (and they aren't addicted).
- A warning will be included for disliked foods (foods that lower pawn's mood).
- The changes apply to both the button, as well as the right-click float menu options.
- The button may be a bit more restrictive than the float menu in cases where pawns wouldn't like ingesting something, but are allowed to. In those situations, the float menu option will show extra info (like disliked food).
- Matching ingesting functionality …
=> Updated code to ingest from inventory

Patches/Medieval Tailor/MO_Tailor_Armor.xml, Patches/Medieval Tailor/MO_Tailor_Clothes.xml, Patches/Medieval Tailor/MO_Tailor_Outwear.xml
Compatibility Patch for Medieval Tailor
- Patches for all of Medieval Tailors clothes
- Needed patched and in line with MO patch
=> Medieval Tailor Patch

Source/ArtilleryCompat/ArtilleryCompat/Subclasses/CompLongRangeArtilleryCE.cs
- In `CompLongRangeArtilleryCE`, 2 new static methods were added - `SyncedSetTargetedTile` and `SyncedResetForcedTarget`
- The methods `SetTargetedTile` and `ResetForcedTarget` call the new static methods
- `SyncedSetTargetedTile` now has most of the functionality of `SetTargetedTile`, however the old method keeps the call to `CameraJumper.TryHideWorld`
- `SyncedResetForcedTarget` required a slight workaround, so `ResetForcedTarget` only calls it in Multiplayer while letting the original code run outside of it (to skip the call to `GetComp`)
- The SyncMethods needed to be static, as `CompLongRangeArtilleryCE` comp is not recognized by MP - it was much easier to use static methods instead of trying to find the root of the problem (possibly due to the .dll files of the compats being loaded …
=> Sync CompLongRangeArtilleryCE in Multiplayer (VFE - Security compat)

Patches/Alpha Animals/BodyDefs/Bodies_CE_Patch_Squid.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Fansquid.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Ravager.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Rayhound.xml, Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_RipperHound.xml
- Updated the patch according to the changes made in the 4.2 update of AA.
=> Alpha Animals patch update

Patches/Possesed Weapons/PossessedWeapons_RangedPatch.xml
=> Possessed bugfix

Patches/Possesed Weapons/PossessedWeapons_RangedPatch.xml
Fix patch error with statBases
- PatchOperationAdd needed instead of Replace
=> Syntax Error

Patches/Sanguinary Animals/SanguineAnimal_Bodies.xml, Patches/Sanguinary Animals/SanguineAnimals_Animals.xml, Patches/Sanguinary Animals/SanguineAnimals_Insects.xml, Patches/Sanguinary Animals/SanguineAnimals_Materials.xml, SupportedThirdPartyMods.md
- Compatibility for 3 new animals that this mod adds
- Compatibility for new body type for Varghulf
=> Sanguinary Animals Compatibility Patch

Patches/More Archotech Garbage Continued/MAGC_Hediff.xml, Patches/More Archotech Garbage Continued/MAGC_Resource_Stuff.xml, SupportedThirdPartyMods.md
=> Patch More Archotech Garbage Continued

Patches/Dragonian Race/ThingDefs_Bodies/Dragonian_Bodytype.xml, Patches/Dragonian Race/ThingDefs_Items/Items_Resource_Stuff.xml, Patches/Dragonian Race/ThingDefs_Misc/DR_Apparel.xml, Patches/Dragonian Race/ThingDefs_Misc/DR_Weapon.xml, Patches/Dragonian Race/ThingDefs_Races/Race_Dragonian.xml, Patches/Dragonian Race/ThingDefs_Races/Race_Dragonian_Garam.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Dragonian_Apparel.xml
- Update the FindMod to include the unofficial 1.4 continuation.
- Was requested on the discord, so why not.
=> Update Dragonian Race FindMod Reference

Patches/Miho Race/ThingDefs_Misc/Weapons_Mechanoid.xml, Patches/Miho Race/ThingDefs_Races/Race_MihoMech.xml
Added miho cluster rocket mech patch
=> Miho cluster rocket mech patch

Source/CombatExtended/CombatExtended/Defs/LoadoutGenericDef.cs
- `LoadoutGenericDef` will now have a `shortHash` generated
- `DefDatabase<LoadoutGenericDef>.defsByShortHash` will be initialized, allowing the calls to `DefDatabase<LoadoutGenericDef>.GetByShortHash()`
- Multiplayer uses `shortHash` for defs when synchronizing them across players
- Multiplayer uses`DefDatabase<T>.GetByShortHash()` to quickly lookup the defs when synchronizing them
- If short hashes and defs by short hash dictionary aren't initialized, multiplayer will fail to synchronize them
- By initializing those, it's now possible to use "any ammo" options for loadouts in Multiplayer
- Making harmony patches to Multiplayer to change how those specific defs are handled
- Modify methods taking `LoadoutGenericDef` as parameter by passing something else, like a `defName` and then …
=> Fix picking any ammo for loadouts in Multiplayer

Patches/Core/Stats/Stats.xml
- Updated the heat armor category's description to mention is protecting against direct cold/frostbite attacks.
=> Heat armor description update

Patches/Zombieland/Zombieland_Patches.xml
- Updated the patch for the newly added Zombie Spitter and Chainsaw.
=> Zombieland patch update

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechVarious.xml
- Adjusted the recipe and HP of the bandolier to reflect its mass difference in comparison to CE's tac vest better, it costs 45 materials instead of the absurd 75. I weighs x0.75 of our tac vest.
- Shuffled its thingCategory to be in the same category as other loadbearing gear.
=> Bandolier tweaks

Patches/Zombieland/Zombieland_Patches.xml
=> ZL patch syntax fix

Source/CombatExtended/Harmony/Harmony_CompAbilityEffect_LaunchProjectile.cs
=> Fix lauchProjectile ability targeting for cells.

Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Base.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Bellicor.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Bellicor_Mortar.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_PristineStrider.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Siegemelter.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Starfire.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Advanced/AdvFireworm.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Advanced/AdvGoliath.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Advanced/AdvPhalanx.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Advanced/AdvSiegebreaker.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Clean/VFEFireworm.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Clean/VFEGoliath.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Clean/VFEPhalanx.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Clean/VFESiegebreaker.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/PlayerControlled/PC_Fireworm.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/PlayerControlled/PC_Goliath.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/PlayerControlled/PC_Phalanx.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/PlayerControlled/PC_Siegebreaker.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Demolisher.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Fireworm.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Goliath.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Phalanx.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Siegebreaker.xml
- Updated some values and added some missing ones.
=> Alpha Mechs patch housekeeping

Patches/Vanilla Plants Expanded - Mushrooms/ThingDefs_Items/Items_Resource_Stuff.xml, SupportedThirdPartyMods.md
- What it says on the tin, the Mycothread required patching, it's similar to cloth but very slightly weaker in stats.
=> VPE - Mushrooms patch

Defs/BipodCategoryDefs/BipodCategories.xml
- Reduced the range bonus from DMR bipods from 15 down to 10.
- Reduced the LMG bipod setup time from 300 down to 240 ticks.
=> Bipod def tweaks

Patches/Urbworld Weaponry SDS/18mmSSR.xml, Patches/Urbworld Weaponry SDS/50ISM.xml, Patches/Urbworld Weaponry SDS/556mmISM.xml, Patches/Urbworld Weaponry SDS/9x35mmSSR.xml, Patches/Urbworld Weaponry SDS/CE-UWSDS.xml, SupportedThirdPartyMods.md
- Patches UWSDS for CE
-4 calibers and 8 weapons
=> UWSDS Patch

Patches/Big and Small/Big and Small - MO/BS_MO_Pawnkind.xml, Patches/Big and Small/Big and Small - Medieval Factions/BS_Medieval_Pawnkind.xml, Patches/Big and Small/Big and Small Genes/HediffDefs/Hediffs_Armor.xml, Patches/Big and Small/Big and Small Genes/Pawnkind/BS_Genes_Pawnkind.xml, Patches/Big and Small/Big and Small Genes/Weapons/ThingDef_Ammo.xml, Patches/Big and Small/Big and Small Genes/Weapons/ThingDef_Building_Security.xml, Patches/Big and Small/Big and Small Genes/Weapons/ThingDef_MeleeWeapons.xml, Patches/Big and Small/Big and Small Genes/Weapons/ThingDef_Ranged.xml, Patches/Big and Small/Big and Small Genes/Weapons/ThingDef_RangedNeolithic.xml, Patches/Big and Small/Big and Small Genes/Weapons/ThingDef_Shrink.xml, Patches/Big and Small/Big and Small Races/ThingDef_Armor.xml, Patches/Medieval Overhaul/MO_Materials.xml, Patches/Vampire, Demons, and the Undead/HediffDefs/VU_Hediff_Patch.xml, SupportedThirdPartyMods.md
- Compatibility Patches for Big and Small Genes 
- Compatibility Patches for Big and Small Races
- Compatibility Patches for Big and Small Medieval Factions
- Compatibility Patches for Big and Small Medieval Overhaul Factions
- Compatibility Patches for Vampires, Demons, and the Undead
- Noticed Medieval Overhaul Rawhide was never patched
- Several of the mods only have 1-2 items to patch
=> Big and small patches

Patches/Not Only Just A Cannon/Patch_Cannon_Ammo.xml
- Adds ammo class so it doesn't show up as a "sling bullet" in game
- Annoying typo
=> Not Just Cannon Typo Fix

Source/CombatExtended/CombatExtended/StatParts/StatPart_LoadedAmmo.cs
Fixed under barrel weapons not adding mass to weapon
=> UBGL Mass fix

Patches/UEM More Mechanitor Mechs/Defs/ThingDefs_Races/Races_Mechanoid_Light.xml, SupportedThirdPartyMods.md
- Patched the mechs weapons to work with CE
- Patched https://steamcommunity.com/sharedfiles/filedetails/?id=2880075558 mod for CE
- Based the values on biotech mechs, mostly Agrihand mech
- Unsure if the `bodyshape` for those mechs should be Vehicle or Humanoid
- First patch and I am not sure how to do the balance part, if at all possible would appreciate someone taking a look at the stats
=> UEM More Mechanitor Mechs Patch

Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
Several changes and improvements have been applied to CompArmorDurability:
- When finishing the repair, an additional check if ingredients are in pawn's inventory was added to prevent issues if they were dropped before finishing.
- When finishing the repair, only the required amount of the ingredients will be removed instead of an entire stack.
- The pawn will reserve the actually needed amount of the ingredients, instead of always reserving only 1.
- Simplified code related to picking up the ingredients from the ground.
- The code will no longer error out when no ingredients are specified in the XML, instead assuming that the repair is free.
- Some extra safety to prevent potential issues in a couple of places.
- Built-in Multiplayer support.
- It was possible to drop ingredients from …
=> Several improvements to CompArmorDurability

Patches/Alpha Mechs/Mods/Biotech/ThingDef_Misc/Apparel.xml
=> Minor syntax error fix in the Alpha Mechs patch

About/About.xml, Patches/Divine Order/PawnKindDefs/Divine_Order_CE_Pawnkinds.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Apparel.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Armor.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Headgear.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Shield.xml, Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Grenades.xml, Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Melee.xml, Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Ranged.xml, Patches/Divine Order/ThingDef_Races/Divine_Order_CE_Horse.xml, SupportedThirdPartyMods.md
- Patch weapons and apparel
- Patched pawns to properly spawn with ammo and shield
- Patched horse to match vanilla horse
=> Divine order Compatibility Patch

Patches/Possesed Weapons/PossessedWeapons_Ammo.xml, Patches/Possesed Weapons/PossessedWeapons_MeleePatch.xml, Patches/Possesed Weapons/PossessedWeapons_RangedPatch.xml
- Added patches for 3 new weapons
- Moved ammo to seperate file for easier future patching
=> Updated Possessed Weapons

Patches/Gloomy Dragonian Race/ThingDefs_Misc/DR_Apparel.xml, Patches/Gloomy Dragonian Race/ThingDefs_Misc/DR_Weapon.xml, Patches/Gloomy Dragonian Race/ThingDefs_Races/Race_Dragonian.xml
New apparel/weapon stats.
Added natural armor comp
Mace doesn't have EMP in this version so removed.
=> Gloomy drag update

Patches/Dubs Rimatomics/Turrets_Rimatomics.xml
- Minor typo that needed fixing.
=> Rimatomics' patch typo fix

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Requested by Aelanna in https://discord.com/channels/278818534069501953/286486075466317826/1149074601003995156
=> Set projectile height virtual

Defs/Ammo/Shell/762x539mmR.xml
=> Add 76.2x539mmR shells

Patches/ESCP - Spriggans/ESCP_BodyDefs_Spriggan.xml, Patches/ESCP - Spriggans/ESCP_Projectiles_Spriggan.xml, Patches/ESCP - Spriggans/ESCP_Spriggan_Scenario.xml, Patches/ESCP - Spriggans/ESCP_ThingDef_Spriggan.xml, SupportedThirdPartyMods.md
- Compatibility patch for creatures in mod
- Patch creature body
=> Escp-Spriggan Compatibility Patch

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
- Melee hit on a slave will now increase slave suppression like it does in vanilla.
- Closes #2778 
Fixes a bug
=> Fixing slave suppression increment on melee hit

Patches/Gestalt Engine/ThingDefs_Races/Matriach.xml, SupportedThirdPartyMods.md
Patches the new mech added by the Gestalt Engine standalone mod
=> Patch for Gestalt Engine Mech

Patches/Imperial Arsenal Royal Warcasket/Ammo/AmmoCategories_Bolts.xml, Patches/Imperial Arsenal Royal Warcasket/Ammo/Xonus.xml, Patches/Imperial Arsenal Royal Warcasket/Apparel_Royal_Warcaskets.xml, Patches/Imperial Arsenal Royal Warcasket/RangedWeapons.xml, SupportedThirdPartyMods.md
patch for Imperial Arsenal: Royal Warcasket   author: Joaquin
same story as ancient arsenal one works but needs my submitted VFE pirates drawsize change to not look terrible
=> patch for imperial arsenal warcasket

Patches/Zombieland/Zombieland_Patches.xml
Changes spitter regen to False by Request of Brrainz
=> Change Zombieland spitter regen to false

Languages/English/Keyed/ArmorDurability.xml, Languages/English/Keyed/BipodStatWorker.xml, Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_BipodDisplay.cs
- Translation keys for armor durability and bipod statworker
=> tr key for armor durability and bipod stat

Patches/Alpha Mechs/Mods/Biotech/ThingDef_Misc/Weapons.xml
- Small balance changes to the aforementioned gun. It's mag stats were being inherited from the rotary needle gun.
=> Alpha Mechs mini needle gun tweaks

Patches/Alpha Biomes/RangedIndustrialGrenades.xml
- Add correct ThingClass to the AB dart projectile to make them work.
- It needs it to work.
- Leave it broken or assign the projectile a different parent, I guess.
=> Fix Alpha Biomes Dart Proj.

Source/CombatExtended/CombatExtended/FleckMakerCE.cs, Source/CombatExtended/Compatibility/VanillaPsycastExpanded.cs
- Changed effecter to fleck
- Fixed impact position
- For recent BlockerRegisry changes I decided to improve how VPE works with CE
Depends on #2796 
=> VPE improvments

Patches/RH2 Rimmu-Nation² - Clothing/Backpacks_CE.xml, Patches/RH2 Rimmu-Nation² - Clothing/Vests_CE.xml
Bailout bag fix for CE(fixed defname mistake)
Maxpedition Belt Fixed for CE(item not being patched before)
=> Fix for RH2 Clothing

Source/VehiclesCompat/VehiclesCompat.csproj
- Added Publicizer to the .csproj file of VehiclesCompat assembly
=> Include publicizer in VehcilesCompat

Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Marshal.xml
- Remove duplicate xml field in VFE - T3 Marshall.
=> Misc. XML Fixes

About/About.xml, About/Manifest.xml
- Increment mod version number for release.
=> Increment Version Number

Defs/Ammo/Advanced/LaserChargePack.xml, Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Advanced.xml, Patches/Det's Energy Weapons/EnergyBoltAmmoSet.XML, Patches/Det's Energy Weapons/Guns_Defs.XML, SupportedThirdPartyMods.md
4 new weapons and a Ammoset to those
Still needed to be polished (I.E animations) and balanced (damage and bulk/weight)
=> Det's Energy Weapons patch

Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/CollisionVertical.cs, Source/CombatExtended/CombatExtended/Comps/CompTacticalManager.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Reverts CombatExtended-Continued/CombatExtended#2905
We've encountered various issues with the changes not caught during the initial testing.
=> Revert "Cache pawn heights"

Patches/Ancient Eastern Armory/AsianArmory_Apparel.xml, Patches/Ancient Eastern Armory/AsianArmory_Armour.xml, Patches/Ancient Eastern Armory/AsianArmory_Weapons.xml
added the (Continued) version to findmod of OG's patch, modpage didn't say anything got changed about it that would break things
=> Ancient Eastern Armory (Continued) Findmod

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Changed a shitton of private to protected virtual
I'm trying to make a guided projectile, turned out projectile movement in CE is locked behind a private getter.
Suffer.
=> virtualized something for fiddling with projectile movement

Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Ammo_12Gauge_Dual.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Ammo_BfgCell.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Ammo_EmgPistol.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Ammo_GaussCannonFlechette.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Ammo_PlasmaCell.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Ammo_Rocket.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Apparel_Armor.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_Apparel_Armor_Headgear.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_LauncherDOOM_Weapons.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_MeleeDOOM_Weapons.xml, Patches/RH2 DOOM/RH2_DOOM_CE_Patch_RangedDOOM_Weapons.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_Ammo_NonLethal.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_Apparel_Armor.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_Apparel_Armor_Headgear.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_Apparel_Headgear.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_Apparel_OnSkin.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_MeleeWeapon.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_PawnKindDefs.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_RangedIndustrial_Pistols.xml, Patches/RH2 Metal Gear Solid/RH2_MGS_CE_Patch_Scenario.xml, SupportedThirdPartyMods.md
Patches for "RH2 DOOM" and "RH2 Metal Gear Solid" updated from the patches for the old 1.2 mods of same name
=> updated the old patches from the 1.2 mods

Patches/Miho Race/Ammo/Ammo_Miho_Industrial.xml, Patches/Miho Race/ThingDefs_Misc/Miho_Apparel.xml, Patches/Miho Race/ThingDefs_Misc/Weapons_Melee.xml, Patches/Miho Race/ThingDefs_Races/Race_MihoHediff.xml
Proper patch for tinkerer mech stat buffs
Added mechanator exosuit stat patch
Fixed ammo recipe descriptions
=> Miho updates/fixes

Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Buildings/TurretGatlingGun.xml, Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs, Source/CombatExtended/Compatibility/BlockerRegistry.cs
Reverts #2949 for now.
Fixes typo (cherry pick from #2970 )
- Contributes towards #2968 
Steam is currently mostly borked, this lets us get that working again without disrupting the dev branch progress.
Figure out the remaining issues with #2969 so it can be merged tonight.  Will likely take too long.
=> Hotfix for current stable

Patches/Better Wool Production/Blended_Wool_Patch.xml, SupportedThirdPartyMods.md
- Patch for Blended Wool
- Patched to be equal to baseline wool
=> Better Wool Production Patch

Patches/Big and Small/Big and Small Weapons/BS_Medieval_Weapons.xml, Patches/Big and Small/Big and Small Weapons/BS_Modern.xml, Patches/Big and Small/Big and Small Weapons/BS_Neolithic.xml, Patches/Big and Small/Big and Small Weapons/BS_Ultratech.xml
- Patch for weapons
- Mini-Cannonball for Musket to prevent more ammo bloat
- Create new ammo for musket
=> Big and Small Weapons Patch

Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Ranged.xml
- Add compatibility patch for new weapon.
- Still using vanilla VerbClass Verb_Shoot instead of the CE Verb_Shoot due to acting similar to Orbital Laser beam
=> Update Divine Order Patch

Patches/Alpha Genes/HediffDefs/Hediffs_Attacks.xml
- Patched the newly added scyther blade hands gene.
=> Alpha Genes patch update

Patches/Vanilla Persona Weapons Expanded/MeleeBladelink.xml, SupportedThirdPartyMods.md
- What it says on the tin, it's a newly added weapon to the mod
- It's identical to the non-persona eltex staff from Royalty.
=> VPWE Persona Eltex Staff patch

Patches/Vanilla Factions Expanded - Deserters/RangedSpacer.xml
- Fix red errors when loading a save with the Charge Cycler equipped.
##References
Closes https://discord.com/channels/278818534069501953/324222101550661663/1208928098486194258
=> Fix VFED Charge Cycler

Defs/Ammo/Grenade/25x59mmGrenade.xml, Defs/Ammo/Grenade/30x29mmGrenade.xml, Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/Grenade/40x53mmGrenade.xml, Defs/Ammo/Grenade/40x53mmVOG25Grenade.xml, Defs/Ammo/Shell/40x365mmBofors.xml
- Fixed the ammoClass and the label of the Time-Fuzed ammo type.
=> 40mm L/70 bofors ammoClass and label fix

Patches/The Vanity Project - Shiba Inu/Vanity_Project_Shiba_Inu_Patch.xml, SupportedThirdPartyMods.md
- Patch animal from mod
- Stats from existing Japanese Dog patch
- Durability from Core patch Labrador Retriever. Body Scales are the same
=> Vanity Project Shiba Inu Patch

Defs/Ammo/Advanced/5x35mmCharged.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml, Patches/Forsakens/Forsakens_CE_Patch_Ammo_ProjReskin.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_Ammo_Spacer.xml, Patches/Royal Arsenal/Ammo/Ammo_5x35RoyalCharged.xml, Patches/SYR Naga/Patch_Ammo_Naga.xml, Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml, Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Ammo_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
- Increased the bullet mass of 5x35mm charged from 4 to 6 grams and made the relevant adjustments to affected items.
- Changed the ammo's ammoClass to `ChargedAP` as it's a Conc. ammo type.
- Fixed some stat mistakes for the charge lance.
- Increased the mag size of the charge lance from 5 to 10 rounds and readjusted the loadouts of lancers and pikemen accordingly.
- Following the discussion made here (https://discord.com/channels/278818534069501953/303988654492090370/1209266329731989544) and the ensuing calculations, it became apparent that lancers deserve a buff of some kind and …
=> 5x35mm charged adjustments

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_AmmoConsumedPerShotCount.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
-Fix stat panel and shooting for a weapon with no ammoSet.
- Closes #2989
=> add missing null checks

Patches/DD House Sanguin/ThingDefs_Shields.xml
- Fix layer issues with shields
- Closes #[[Discord](https://discord.com/channels/278818534069501953/630624305947869184/1207723753400832001)]
- Easier to replace full def due to number of changes needed to make and the multiple abstracts used in the original mod
- Patch each abstract separately
- Harder to read and troubleshoot
- Doesn't replace entire thingDef
=> Fix House Sanguin Shields

Defs/Ammo/Shell/57x307mmR.xml, Defs/Ammo/Shell/75x350mmR.xml, Defs/Ammo/Shell/762x539mmR.xml
- Switch over to using the associated shell projectile, instead of the generic big bullet.
Have the art, should use it.
Leave as-is.
=> Implement shell projectiles

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Source/CombatExtended/CombatExtended/Comps/CompFragments.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Bursting.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Flare.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs, Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs, Source/CombatExtended/CombatExtended/Verbs/VerbPropertiesCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
- Closes #2906 
Same as the above, but the max reduction limit applies correctly, and is rebased against the other projectile fixes.
Also does not change bounds checking, that will come in 1.5
Keep the current system until 1.5
=> Fix repeat shots 2

.github/workflows/backports.yml, .github/workflows/code-style.yml
Code style and PR-verification apply to the backports-1.4 branch
=> Enable workflows on backports

Defs/DamageDefs/Damages_LocalInjury.xml
Duplicate of #3068, just aimed at 1.4 instead.
=> Fix 'CE_Laser' Name typo

Source/BetterTurretsCompat/BetterTurretsCompat.csproj, Source/CombatExtended/CombatExtended.csproj, Source/Loader/Loader.csproj, Source/MiscTurretsCompat/MiscTurretsCompat.csproj, Source/MultiplayerCompat/MultiplayerCompat.csproj, Source/SRTSCompat/SRTSCompat.csproj, Source/VehiclesCompat/VehiclesCompat.csproj
Use latest harmony and krafs reference versions for building
=> Update reference assembly versions

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- landedEffecter support... Is it used anywhere?
- Support of new field
- No support of new field
=> landedEffecter support

Defs/ResearchProjectDefs/ResearchProjects.xml, Defs/ResearchProjectDefs/ResearchProjects_Turrets.xml
- Added rule strings to existing researches, enabling them to appear in schematic books.
- Mentioned in #3024
- Attempted to keep the overall writing style close to vanilla, with some extra technical details.
=> Add rule strings to researches

ModPatches/Paniel the Automata/Defs/Paniel the Automata/Ammo_Paniel.xml, ModPatches/Pratt WWII Weapons Pack/Defs/Pratt WWII Weapons Pack/Recipes_Grenades.xml, ModPatches/Revia Race/Defs/Revia Race/Recipes_Revia.xml, ModPatches/Vanilla Genetics Expanded/Defs/Vanilla Genetics Expanded/Projectiles.xml, ModPatches/Vanilla Weapons Expanded - Tribal/Defs/Vanilla Weapons Expanded - Tribal/Recipes_Ranged.xml
XML fixes for a number of post patch to loadfolder def issues.
Changed xml/patches to try and reduce number of remaining misformatted xml.
=> Loadfolder Defs XML fixes

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Fixed NRE
- Turrets not working
- Ignore turrets.
=> NRE fix for turrets

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- New field support
- Flare flip... I dunno
=> spinRate support

Source/CombatExtended/CombatExtended/Building_AmmoContainerCE/Building_AutoloaderCE.cs
missed a .GraphicColoredFor(this)
-suffer.
=> autoloader material color fix

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs
Add back the missing + in the code.
Fix the offset of projectiles have hight fuse.
- Closes #3126 
Bug fix
=> Fix the Height Fuse shell offset problem

LoadFolders.xml, ModPatches/Edge of Descension - Vanguard/Patches/Edge of Descension - Vanguard/EoD_ApparelDefs.xml, ModPatches/Edge of Descension - Vanguard/Patches/Edge of Descension - Vanguard/EoD_WeaponsDefs.xml, SupportedThirdPartyMods.md
- added patches for Vanguard Armor set and Charge Magnum.
- because the mod has sick video animation and GIF.
=> Patches for Edge of Descension - Vanguard

LoadFolders.xml, ModPatches/Vanilla Races Expanded - Insector/Patches/Vanilla Races Expanded - Insector/AbilityDefs/AbilityDefs.xml, ModPatches/Vanilla Races Expanded - Insector/Patches/Vanilla Races Expanded - Insector/GeneDefs/GeneDefs.xml, ModPatches/Vanilla Races Expanded - Insector/Patches/Vanilla Races Expanded - Insector/HediffDefs/Hediffs.xml, SupportedThirdPartyMods.md
- Values are based on existing patches.
=> VRE Insector patch

ModPatches/ODZ Stalingrad - Uniforms/Patches/ODZ Stalingrad - Uniforms/ThingDefs_Apparel.xml
- patches for Soviet Steel Cuirass
- changed Soviet Steel Cuirass flat armor value to stuffed scaling
- removed Soviet Steel Cuirass MoveSpeed debuff
- The soviet sent combat medic
- move factory to the ural
=> Update ODZ Stalingrad - Uniforms

ModPatches/Edge of Descension - Monoblades/Patches/Edge of Descension - Monoblades/EoD_WeaponsDefs.xml
- Luciblade `PatchOperation` from Replace on `<MeleeDodgeChance>` to Add.
- the devil's contract has changed and replaced XML node has vanished.
=> Update Edge of Descension - Monoblades

ModPatches/ReGrowth - Extinct Animals/Patches/ReGrowth - Extinct Animals/Extinct_Mammals.xml
- Patches for Sabertooth Tiger "Smilodon"
- Ice Age series
- Floof big cat
- don't let sabertooth squirrel pull the acorn
=> Update ReGrowth - Extinct Animals

LoadFolders.xml, ModPatches/ReBuild - Doors and Corners/Patches/ReBuild - Doors and Corners/Buildings_Structure.xml, SupportedThirdPartyMods.md
- added patch for Wall Armor
- added more damage def to the damageMultipliers property
- adjusted damage multiplier for Bomb and Thump damage def
- bob
- the
- builder
=> Patches for ReBuild - Doors and Corners

ModPatches/Save Our Ship 2/Patches/Save Our Ship 2/Hediffs_SOS2.xml, ModPatches/Save Our Ship 2/Patches/Save Our Ship 2/UpgradeTree.xml
missing SOS2 hediff and description update,
archo lung tox and smoke resistance archo jaw CE tools
also made archo skin to offer more armor
=> SOS2 missing hediff and description update

LoadFolders.xml, ModPatches/ADogSaid2/Patches/ADogSaid2/Bionics.xml, SupportedThirdPartyMods.md
- Patches for Simple Prosthetics (Legs, Arms)
- Patches for Bionic Prosthetics (Legs, Arms, Jaws)
- removal of simple prosthetic jaws patch from original mod
- A Dog Said... yes
- Increase the survival rate of animals in RimWorld, those cuties deserve more.
- A Dog Said... no more animals :(
=> Patches - A Dog Said... Animal Prosthetics 2

LoadFolders.xml, ModPatches/Melee Animation/Patches/Melee Animation/AM_Weebstick.xml, SupportedThirdPartyMods.md
- patches for Scarlet Edge
- nothing changes with weebs
- metal gear revengeance reference
- because weeb stick is edgy
- your hand is a sword
=> Patches - Melee Animation

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
Changed some privates to protected virtual for extendability
-I'm bothered enough by custom melee verbs that I have to do this to make CE versions of them.
-Reflect everything.
=> Un-privatize some melee verb stuff

LoadFolders.xml, ModPatches/Matter Manipulator/Patches/Matter Manipulator/MatterManipulator.xml, ModPatches/More Utility Packs/Patches/More Utility Packs/Apparel_Mechanoids.xml, ModPatches/More Utility Packs/Patches/More Utility Packs/Apparel_Packs.xml
what it says on the tin, and patch for Matter manipulator range attack
=> update patch for More Utility Packs (Continued) + Matter Manipulator Patch

ModPatches/Moyo 2/Patches/Moyo 2/Race/AlienRace_Moyo.xml, ModPatches/Moyo 2/Patches/Moyo 2/Race/Moyo_Bodytype.xml
Actual race patch stuff. Bodydef and alien race def. The latter isnt' really important because it should inherit but bodydef groups are important for natural armor stuff
=> Moyo 2 race missed stuff.

ModPatches/ReBuild - Doors and Corners/Patches/ReBuild - Doors and Corners/Buildings_Structure.xml
- patches for Reinforced Glass and Clerestory Wall.
- removed damage multiplier patch for Wall Armor
- Contributes towards #3231
- silly cat did some balancing
- update this patch again once they added missing node on reinforced glass door
=> Update - Rebuild: Doors and Corners

Defs/Ammo/Other/Flamethrower.xml
=> Fix missing "chemfuel" in recipe

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
title.
bumped into this when updating plasma weapon
Reflect here it goes
=> make GetHeightAtTicks protected

Defs/BipodCategoryDefs/BipodCategories.xml
- Tweaked the comment placements for better readability.
- Small adjustments to AMR and ATR bipods.
- There are a couple complaints about the readability of the comments.
- ATRs are already extremely niche, the bipods did not help with that as much as possible.
=> Bipods tweaks and housekeeping

LoadFolders.xml, ModPatches/Enchanted Sword/Patches/Enchanted Sword/ES_AbilityDefs_Patch.xml, ModPatches/Enchanted Sword/Patches/Enchanted Sword/ES_DamageDefs_Patch.xml, ModPatches/Enchanted Sword/Patches/Enchanted Sword/ES_WeaponDefs_Patch.xml, SupportedThirdPartyMods.md
what it says on the tin, the bow is patched via projectile cause it has custom verb with tracking.
=> Enchanted Sword patch

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_AmmoConsumedPerShotCount.cs
- "Not patched" message in description 
- Fixed cast exception
=> Info Panel cast exception fix

ModPatches/Vanilla Factions Expanded - Deserters/Patches/Vanilla Factions Expanded - Deserters/Buildings_Special.xml
- Updated reference
- CompExplosive_Shells was moved to VFECore
=> Fixed patch for VFE - Deserters

ModPatches/Vanilla Animals Expanded/Patches/Vanilla Animals Expanded/Desert_Animals.xml, Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml
- Added degradable natural armor to vanilla and VE tortoises.
- Somehow or for some reason I forgot to add the comp to them, it's there now.
=> Tortoise degradable armor

ModPatches/BiologicalWarfare/Defs/Ammo.xml, ModPatches/BiologicalWarfare/Patches/Patches.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/DamageDefs/DamageDef_DragonMelee.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/Projectiles/Projectile_Dragon.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/ThingDefs_Misc/Apparel_Headgear.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/ThingDefs_Misc/Weapons/MeleeDD.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/ThingDefs_Races/Races_Animal_Common_Dragon.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/ThingDefs_Races/Races_Animal_Rare_Dragon.xml
What it says on the tin
remove old DD Projectile patch
=> Dragons descent patch update tag Royalty content, and tag Biological warfare Anomaly content

ModPatches/Alpha Genes/Patches/Alpha Genes/AG_Anomaly/HediffDefs/HediffDefs_Patch.xml
- Patched the newly added hediffs which are melee attacks and a temporary buff to armor and other stats.
- The Cube demands so.
- Cube.
=> Alpha Genes Anomaly update patch

LoadFolders.xml, ModPatches/Jin-Roh Kerberos Panzer Cop Armor/Patches/JinRohKerberosPanzerCopArmor/JinRohKerberosPanzerCopArmor_Patches.xml, SupportedThirdPartyMods.md
Armor-patches
- CE-values for the armor and helmet
- Better to have the patch included in CE than in the mod
=> Jin-Roh Kerberos Panzer Cop Armor

Source/CombatExtended/CombatExtended/GUI/Windows/Window_GiveAmmoAmountSlider.cs
- Fixed missing slider
- An old working "give ammo" dialog
- Give one at a time
- Suffer
=> GiveAmmo window fix

ModPatches/Altered Carbon Ultratech Unleashed/Patches/Altered Carbon Ultratech Unleashed/AC_Apparel.xml, ModPatches/Altered Carbon Ultratech Unleashed/Patches/Altered Carbon Ultratech Unleashed/AC_Patches.xml, ModPatches/Altered Carbon Ultratech Unleashed/Patches/Altered Carbon Ultratech Unleashed/AC_Weapons.xml
=> Patch Overseer helmet

LoadFolders.xml, ModPatches/Titan Vehicles/Patches/Titan Vehicles/Avenger.xml, ModPatches/Titan Vehicles/Patches/Titan Vehicles/Conquistador.xml, ModPatches/Titan Vehicles/Patches/Titan Vehicles/Warchief.xml, SupportedThirdPartyMods.md
Added Patches To The Three Vehicles In Titan Vehicles.
The Only Thing I Couldn't Patch Was The Tanks Low Shield Ability Due To No Experience With C#, 
Everything Else Works Fine.
=> Titan vehicles CE Patch

ModPatches/Pulse Weaponry/Defs/Pulse Weaponry/Damage.xml, ModPatches/Pulse Weaponry/Patches/Pulse Weaponry/RangedSpacer.xml
new spacer Taser damage 
buff stun chance added new damage, make the stun stick one handed
=> make Pulse Weaponry Stunstick one handed

LoadFolders.xml, ModPatches/Medieval Overhaul House Roxmont/Patches/CE_Apparel.xml, ModPatches/Medieval Overhaul House Roxmont/Patches/CE_Patches.xml, ModPatches/Medieval Overhaul House Roxmont/Patches/CE_PawnKindDefs.xml, ModPatches/Medieval Overhaul House Roxmont/Patches/CE_Weapons.xml, ModPatches/Medieval Overhaul/Patches/Medieval Overhaul/ThingDefs_Misc/MO_Apparel_Armor.xml, SupportedThirdPartyMods.md
- Patches the aforementioned mod, there were some items and pawnKinds that needed patching.
- Stats are chosen similar to existing patches.
=> MO House Roxmont patch

ModPatches/Grimworld Core Imperialis/Patches/CE_Patch_RangedWeapons.xml
- Changes Volkite Weapon patch for comps due to base mod adding comp to the weapons. Fixes duplicate node error.
=> Update Volkite Weapons

Source/CombatExtended/CombatExtended/Comps/CompAmmosetSwitcher.cs
MustTranslate in UBGL compprops
=> Add translate annotations

Defs/Ammo/Generic/LauncherGrenade.xml
- Remove generic recipe. I managed to "fix" the missing recipe twice across different branches.
- I plead 'whoopsie daisy'.
- Suffer.
=> Remove duplicate generic recipe

Source/CombatExtended/CombatExtended/PatchOperationMakeGunCECompatible.cs
Add WeaponClass in PatchOpsMakeGunCompat
=> Add WeaponClass in PatchOpsMakeGunCompat

Defs/Misc/DesignatorDropdownGroupDef/DesignatorDropdownGroupDef.xml, Defs/ThingDefs_Buildings/Buildings_Turrets.xml, Defs/ThingDefs_Misc/Apparel_Headgear.xml
- Added dropdown categories for CE's various turret types and assigned the turrets inside their corresponding dropdown menu.
- Keeping things clean, it's a nice dropdown menu with the turret listed with their name and uiIcon.
- Keep the clutter.
=> Turret dropdowns

ModPatches/Divine Order/Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Melee.xml
- Patches Warhammer
- Mod has added weapon after last time Divine Order was patched
=> Patch Divine Order Warhammer

ModPatches/Medieval Overhaul/Patches/Medieval Overhaul/ThingDefs_Misc/MO_Apparel_Helmets.xml
- Patches partially patched helmet
- Leave it partially patched
=> Update Medieval Overhaul Patch

About/About.xml, SupportedThirdPartyMods.md
- ModList updates.
- Increment mod version.
- N/A
- N/A
- N/A
=> Misc. 6.1 Tweaks & Fixes

LoadFolders.xml, ModPatches/Spacer Pack/Patches/Spacer Pack/Backpacks.xml, SupportedThirdPartyMods.md
- Changed Mod Backpacks To Use Correct Bodypart Groups, Layers, and Thing Categories
- All Backpacks now give Bulks Amounts 
- Spacer Backpacks Bulk amount was set with CE Armors Large Backpack in mind
- Tweaking Bulk values if it's too much
=> Spacer Pack Patch

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
- ITab NRE fix
- NRE blocks display of inventory panel with some modded animals.
- Not being able to view inventory is bad, makes unloading caravans a pain.
- Suffer
=> Fix ITab NRE when trying to display armor values for pawns with no apparel

ModPatches/EPOE Forked/Patches/EPOE Forked/Bionics_Patch.xml, ModPatches/EPOE/Patches/EPOE/Bionics.xml
add NV stats to both EPOE and forked patch
=> Epoe and forked patch NV update

LoadFolders.xml, ModPatches/Dragons Descent/Patches/Dragons Descent/ThingDefs_Misc/Weapons/MeleeDD.xml
look for 1.5 version of archotech weaponry
update Dragons Descent melee weapon stats
=> update Archotech weaponry patch, and DD stats patch

ModPatches/Spacer Pack/Defs/Spacer Pack/Defs_Projectiles.xml, ModPatches/Spacer Pack/Patches/Spacer Pack/Backpacks.xml
just added patch for the two new packs
=> Spacer pack patch update

ModPatches/Spacer Pack/Defs/Spacer Pack/Defs_Projectiles.xml, ModPatches/Spacer Pack/Patches/Spacer Pack/Backpacks.xml, ModPatches/Spacer Pack/Patches/Spacer Pack/Damage.xml, ModPatches/Spacer Pack/Patches/Spacer Pack/Hediff.xml
update patch for the new pack, that has a grenade that eats armor.
=> Spacer pack again

LoadFolders.xml, ModPatches/Rimrats/Patches/Rimrats/ThingDefs_Races.xml, SupportedThirdPartyMods.md
Added support for Rimrats (Continued) by Mlie.
=> Rimrats support

LoadFolders.xml, ModPatches/GREG/Patches/GREG/ThingDefs_Races.xml, SupportedThirdPartyMods.md
Added support for GREG (great egret) mod, by Tyrannidae: https://steamcommunity.com/sharedfiles/filedetails/?id=3228302152
=> Add GREG support

Languages/Russian/DefInjected/ThingDef/Apparel_Carrying.xml, Languages/Russian/DefInjected/ThingDef/Apparel_Shield.xml, Languages/Russian/DefInjected/ThingDef/Apparel_Various.xml
- Fixed errors on startup
- I don't like errors on startup
- Ignore these errors
=> Russian translation fix

LoadFolders.xml, ModPatches/Hyena (Continued)/Patches/Hyena (Continued)/ThingDefs_Races.xml, SupportedThirdPartyMods.md
Added support for Hyena (Continued), by Zaljerem: https://steamcommunity.com/sharedfiles/filedetails/?id=2778544400
Defined CE-only parameters, changed tools.
All added hyena properties are identical to the VAE hyena, so this is also a streamlining mod.
Check tests performed:
=> Add Hyena (Continued) support

Defs/ResearchProjectDefs/ResearchProjects.xml
- Fix a typo.
- Follow up from #3576 
- I plead whoopsie daisy.
- Suffer.
=> Fix Research typo

ModPatches/Altered Carbon Ultratech Unleashed/Patches/Altered Carbon Ultratech Unleashed/AC_Apparel.xml, ModPatches/Altered Carbon Ultratech Unleashed/Patches/Altered Carbon Ultratech Unleashed/AC_Hediff.xml
patch "new" helmet
fix toxblade not using correct capacity in one tool.
=> AC patch update 

About/About.xml, ModPatches/Rimrats/Patches/Rimrats/ThingDefs_Races.xml, ModPatches/Spacer Arsenal/Patches/Spacer Arsenal/Apparel_Various.xml, ModPatches/Vanilla Arsenal/Patches/RangedIndustrial.xml, SupportedThirdPartyMods.md
- Add Spacer Arsenal to the mod list, since it got overlooked.
- Increment the version number.
- Fix some duplicate nodes in patches.
- Needed.
- No.
=> Finalize the v6.2 release

ModPatches/T's Samurai Faction/Patches/T's Samurai Faction/T_Samurai_Apparel.xml, ModPatches/T's Samurai Faction/Patches/T's Samurai Faction/T_Samurai_Weapons_Ranged.xml
- patch for Daimyo Armor
- remove Components requirement for Gunpowder Weaponry
- Medieval Component-less
- suffer with component search in medieval when it's removed
=> Update - T's Samurai Faction

ModPatches/The GiantRace/Patches/The GiantRace/Scenario/Giant_Scenario.xml, ModPatches/The GiantRace/Patches/The GiantRace/ThingDefs_Misc/GiantWeapons_Ranged.xml, ModPatches/The GiantRace/Patches/The GiantRace/ThingDefs_Races/AlienRace_Giantlike.xml
=> fixes for errors on start up for the giantrace 1.5

ModPatches/Rimsenal - Spacer Faction Pack/Patches/Rimsenal - Spacer Faction Pack/PawnKinds_CE.xml
=> Pawnkind patch for Rimsenal Spacer Faction

LoadFolders.xml
- Adds back Reinforced Mechanoids 2 <li> line to LoadFolders.xml that was accidentally removed in the #3632 pull.
=> Reinforced Mechanoids LoadFolder Readdition

ModPatches/Reinforced Mechanoid 2/Patches/Reinforced Mechanoid 2/ThingDefs_Races/RM_Races_Machines.xml, ModPatches/Reinforced Mechanoid 2/Patches/Reinforced Mechanoid 2/ThingDefs_Races/RM_Races_Mechanoids.xml
- Adds Natural Armor To Reinforced Mechanoid 2 Mechanoids and Droids (Didn't notice they had no natural armor when patching)
- Most likely tweak the values if they're too high/low
=> Reinforced Mechanoid 2 Natural Armor Addition

LoadFolders.xml, ModPatches/Rimsenal Xenotype Pack - Harana/Patches/Rimsenal Xenotype Pack - Harana/Apparel_Harana_CE.xml, ModPatches/Rimsenal Xenotype Pack - Harana/Patches/Rimsenal Xenotype Pack - Harana/Genes_Harana_CE.xml, ModPatches/Rimsenal Xenotype Pack - Harana/Patches/Rimsenal Xenotype Pack - Harana/Weapons_Harana_CE.xml, SupportedThirdPartyMods.md
Patches for Xenotype ability, armor and weapon
=> Harana patch

LoadFolders.xml, ModPatches/RPG Adventure Flavour Pack/Patches/RPG Adventure Flavour Pack/RPGAFP_Apparel_Carry.xml, ModPatches/RPG Adventure Flavour Pack/Patches/RPG Adventure Flavour Pack/RPGAFP_ThingDefs_Races.xml, SupportedThirdPartyMods.md
- patches for Broombug
- patches for Bag of Holding
- Fantasy into reality
- Your average isekai stuff
- because Truck-kun says time's up
- Stay as salaryman and enjoy the life instead of going isekai
=> Patches - RPG Adventure Flavour Pack

ModPatches/RimFantasy - House Doyle/Patches/RimFantasy - House Doyle/Patch_RFDoyle_ArcaneWeapon.xml, ModPatches/RimFantasy - Medieval Overhaul Edition/Patches/RimFantasy - Medieval Overhaul Edition/Patch_RF_Arcane_Ring.xml, ModPatches/RimFantasy - Medieval Overhaul Edition/Patches/RimFantasy - Medieval Overhaul Edition/Patch_RF_Arcane_Staff.xml, ModPatches/RimFantasy - Medieval Overhaul Edition/Patches/RimFantasy - Medieval Overhaul Edition/Patch_RF_Arcane_Wand.xml
- Rebalance for Arcane weapons from RimFantasy - House of Doyle and RimFantasy - Medieval Overhaul Edition
- Harry Potter
- The previous value looks quite overturned which makes them perform too well even outside medieval settings.
- Muggles weapons stays underpowered against magic weapons
=> Update - RimFantasy Series

ModPatches/AV Mechtech/Patches/AV Mechtech/CompanionSphere.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/Fluoid.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/RoyalLancer.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/RoyalLancerWeapons.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/Scrapper.xml
- All mechs added now have armor and proper comps, the royal lancer's weapon in both ranged mode and melee mode is patched and balanced to the best of my ability. 
- No existing patch
- [yes ] Compiles without warnings
- [yes ] Game runs without errors
- [yes] (For compatibility patches) ...with and without patched mod loaded
- [yes ] Playtested a colony (specify how long) - 200 day colony
=> AV Mechtech patch

About/About.xml, ModPatches/T's Samurai Faction/Patches/T's Samurai Faction/Biotech/T_Samurai_Biotech_Apparel.xml
- patches for Kid Kamon and Gi (requires Biotech)
- population growth
- Meiji restoration
- because the default value doesn't match or close to their adult clothing counterpart
- back to the Sakoku era
=> Updates - T's Samurai Faction

LoadFolders.xml, ModPatches/Ratkin Xenotype/Patches/Ratkin Xenotype/GeneDefs_Ratkin.xml, SupportedThirdPartyMods.md
- patches for Carry Weight Reduce Gene
- stats reduce from statOffsets to statFactors
- rats
- because that's rats
- just have a mouse
=> Patches - Ratkin Xenotype

Defs/Ammo/Modded/Warhammer 40k/Bolter_Small.xml
- Reduces FSX cost to match other ammo
- Closes #[[3630](https://github.com/CombatExtended-Continued/CombatExtended/issues/3630)]
- Xenos win
=> Fix Bolter Ammo Recipe Cost

Source/CombatExtended/CombatExtended/WorldStrengthTracker.cs
- No more Rebuild for single every tick;
- Removing expired records
=> Faction tracker fix

Languages/English/Keyed/ModMenu.xml, Languages/Russian/Keyed/ModMenu.xml, Source/CombatExtended/CombatExtended/Comps/CompVerbDisabler.cs, Source/CombatExtended/CombatExtended/Settings.cs, Source/CombatExtended/CombatExtended/Things/Building_CIWS_CE.cs, Source/CombatExtended/CombatExtended/Things/Building_Turret_MultiVerbs.cs, Source/CombatExtended/CombatExtended/Verbs/VerbCIWS.cs, Source/CombatExtended/CombatExtended/WorldStrengthTracker.cs
- Player able to disable CIWS completly 
=> CIWS disable option

LoadFolders.xml, ModPatches/Tools O'Plenty/Patches/Tools O'Plenty/ToolsOPLentyElectricCE.xml, ModPatches/Tools O'Plenty/Patches/Tools O'Plenty/ToolsOPLentyPrimitveCE.xml, ModPatches/Tools O'Plenty/Patches/Tools O'Plenty/ToolsOPLentySimpleCE.xml, ModPatches/Tools O'Plenty/Patches/Tools O'Plenty/ToolsOPLentySpacerCE.xml, SupportedThirdPartyMods.md
- Patches for damge and armor penetration for all tools
None
- Need balance for this tools
- Different balance additions
=> Feat(ModPatches) Patch for mod Tools O'Plenty

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- lastShootLine is nullable. Requires a check or NRE
- Suffer
=> Fix Null Object Verb_LaunchProjectileCE

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Possible fix for NRE
- Closes #3717 
=> NRE fix for TrajectoryWorker property (not patched projectiles)

Source/CombatExtended/Harmony/Harmony_ExpandableWorldObjectsUtility.cs
- Removes log message from transpiler that was used for testing
- Vibe coding
=> Remove Log Message

LoadFolders.xml, ModPatches/Vanilla Quests Expanded - Cryptoforge/Defs/Vanilla Quests Expanded - Cryptoforge/VQEC_Ammo_Cryptoforge.xml, ModPatches/Vanilla Quests Expanded - Cryptoforge/Patches/Vanilla Quests Expanded - Cryptoforge/VQEC_Apparel_Various.xml, ModPatches/Vanilla Quests Expanded - Cryptoforge/Patches/Vanilla Quests Expanded - Cryptoforge/VQEC_Hediffs_Global_Misc.xml, ModPatches/Vanilla Quests Expanded - Cryptoforge/Patches/Vanilla Quests Expanded - Cryptoforge/VQEC_Races_Animal_Insect.xml, ModPatches/Vanilla Quests Expanded - Cryptoforge/Patches/Vanilla Quests Expanded - Cryptoforge/VQEC_Things_Weapons.xml, SupportedThirdPartyMods.md
- Ammo for Crypto Bolter.
- Weapon Patches for Crypto Axe, Crypto Bolter.
- Armor Patches for Crypto Helmet, Crypto Heavy Helmet, Crypto Armor, Crypto Heavy Armor.
- Hediff Patches for Megamidge's Hediff Melee Tools.
- Race Patches for Ice Crawler, Megamidge.
- uhhh hypothermia++
- God of War: Valhalla
- because yes icy weapon go brrrrr
- no crypto stuff : (
=> Patch - Vanilla Quests Expanded Cryptoforge

LoadFolders.xml
- Changed to continued version of Cybernetic Organism and Neural Network
- Closes #3797 
- Broken patches
=> Update CONN modId

LoadFolders.xml, ModPatches/Medieval Bowyer/Defs/Medieval Bowyer/Ammo.xml, ModPatches/Medieval Bowyer/Patches/Medieval Bowyer/Weapons_Ranged.xml, SupportedThirdPartyMods.md
Makes Medieval Bowyer CE compatible
More weapons good
=> Medieval Bowyer CE patch

ModPatches/Royal Arsenal/Patches/Royal Arsenal/Things/RoyalArsenal_Armors.xml, ModPatches/Royal Arsenal/Patches/Royal Arsenal/Things/RoyalArsenal_PrestigeArmors.xml
- Mod moved to ApparelReloadable and this fixes that issue
- https://discord.com/channels/278818534069501953/630624305947869184/1367576657946214591
- Fixes issue
- Another broken patch
=> Update Royal Arsenal

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Moves check and returns false
- Fixes bug from PR #3766
- Suffer
=> Fix intercept

.github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml
The new `VersionInfo.COMMIT` field gets populated with information from the build system
=> Embed additional version info during build

LoadFolders.xml, ModPatches/Det's Xenotypes - Venators/Patches/Det's Xenotypes - Venators/Apparel_Venators.xml, ModPatches/Det's Xenotypes - Venators/Patches/Det's Xenotypes - Venators/GeneDef_Venators.xml, ModPatches/Det's Xenotypes - Venators/Patches/Det's Xenotypes - Venators/Pawnkind_Venators.xml, ModPatches/Det's Xenotypes - Venators/Patches/Det's Xenotypes - Venators/Weapon_Ranged_Venators.xml, SupportedThirdPartyMods.md
- Patches AMR (Requires Athena)
- Patches Mask
- Patches Genes
- Closes #3597 
- Weaker gas mask
- Rifle is meant only for the gene
- PawnKind in mod inherits from already patched base
- Less races
=> Patch Det's Venator

ModPatches/Save Our Ship 2/Patches/Save Our Ship 2/Patch_DamageDefs_SOS2.xml
Patch unpatched damage defs
Add cannon turret and ship debri damage defs to the patch
=> Update SOS2 patch

LoadFolders.xml, ModPatches/More Armory! Midworld Arms Pack/Patches/More Armory! Midworld Arms Pack/ThingDefs_Apparel.xml, ModPatches/More Armory! Midworld Arms Pack/Patches/More Armory! Midworld Arms Pack/Weapons_Melee.xml, ModPatches/More Armory! Midworld Arms Pack/Patches/More Armory! Midworld Arms Pack/Weapons_Ranged.xml, SupportedThirdPartyMods.md
Makes More Armory! Midworld Arms Pack compatible with CE
More guns good
=> More Armory! Midworld Arms Pack CE Patch

ModPatches/Big and Small Genes/Defs/Big and Small Genes/Weapons/ThingDef_Ammo_Arrows.xml, ModPatches/Big and Small Genes/Patches/Big and Small Genes/Pawnkind/BS_Genes_Pawnkind.xml, ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_RangedNeolithic.xml
- Patches new bow
- Patches new archer pawnKindDef
- Adds Giant's arrows
- Closes #3739 
- Suffer
=> Update Big and Small Genes

ModPatches/Dark Ages - Beasts and Monsters/Patches/Dark Ages - Beasts and Monsters/Projectiles/DABeasts_CE_Patch_Projectiles.xml, ModPatches/Dark Ages - Beasts and Monsters/Patches/Dark Ages - Beasts and Monsters/ThingDef_Races/DABeasts_CE_Patch_Race_Barog.xml, ModPatches/Dark Ages - Beasts and Monsters/Patches/Dark Ages - Beasts and Monsters/ThingDef_Races/DABeasts_CE_Patch_Race_Phrak.xml
- Patches two new creatures
- Sneaking in before release cut
- Incomplete patching prior to release
=> Update Dark Age Beasts and Monsters

ModPatches/Japanese Dogs/Patches/Japanese Dogs/Dogs.xml
-fix japanese dogs patch error
-fixed typos in dogs.xml
-
-
-
=> Fix japanese dogs patch error

LoadFolders.xml, ModPatches/Dust Bunnies/Patches/Dust Bunnies/Races_DustBunny.xml, SupportedThirdPartyMods.md
- Add patch for the Dust Bunnies mod.
- The dust bunnies have the combat capability slightly less than a squirrel.
- Different more nuanced balance scheme, I suppose?
=> Patch Dust Bunnies

Source/CombatExtended/CombatExtended/StatParts/StatPart_NonHumanParry.cs
- Adds null check
- Closes #3896
- Meleeing vehicles causing an NRE due to not actually having tools
- Probably best to have this check regardless for other pawns that may not have tools
- Errors
=> Fix Vehicle Melee Interaction

ModPatches/Profaned/Patches/Profaned/ThingDefs_Misc/Profaned_CE_Patch_Projectiles.xml, ModPatches/Profaned/Patches/Profaned/ThingDefs_Misc/Weapons/Profaned_Weapons_Melee.xml
-Fixes Profaned Shooty Scythe
- Somehow was set to vanilla shooting verb
- Not a mortar so don't need overhead
- Errors
=> Fix Profaned Scythe

Languages/English/Keyed/ModMenu.xml
- Changes label to be more succinct
- Leave it
=> Change Reset Button Translation

About/About.xml, LoadFolders.xml
- Increment mod version number.
- Clean up some whitespace in the LoadFolders.xml.
- Housekeeping.
- Use a different versioning scheme, for some reason?
=> Increment mod version num, whitespace cleanup in loadfolders

Source/CombatExtended/CombatExtended/PatchOperationMakeGunCECompatible.cs
- Adds comment filtering on PatchOperationMakeGunCECompatible.Populate method
- 1.6
- XML commenting not being filtered from the look like
- Suffer
=> Fix CE Gun Patcher

ModPatches/Big and Small Genes/Patches/Big and Small Genes/Genes/GeneDefs_Armor.xml, ModPatches/Big and Small Genes/Patches/Big and Small Genes/HediffDefs/Hediffs_Armor.xml, ModPatches/Big and Small Genes/Patches/Big and Small Genes/HediffDefs/Hediffs_Transformations.xml, ModPatches/Big and Small Genes/Patches/Big and Small Genes/HediffDefs/Hediffs_Weapons.xml
- Re-adds back old patches for armor as they are no longer commented in the mod
- Slightly buffs from old patches
- Metabolic costs of genes
- Natural pawn armor genes have gotten a buff since was last patched
- Reinstate non-buffed genes
=> Update Big and Small

ModPatches/Integrated Implants/Defs/Integrated Implants/ThingDefs_ImplantedShells.xml, ModPatches/Integrated Implants/Patches/Integrated Implants/Hediffs_Anomaly.xml, ModPatches/Integrated Implants/Patches/Integrated Implants/Hediffs_Biotech.xml
- Moves DLC implants under a PatchOperationFindMod
- Add MayRequire for DLC shells
- Closes #3968
- Suffer
=> Update Integrated Implants

Source/CombatExtended/CombatExtended/Comps/BipodComp.cs, Source/CombatExtended/CombatExtended/ModSettings/Settings.cs
=> Fix bipod nre backport

Source/CombatExtended/CombatExtended/ModSettings/Settings.cs
=> Backport of Fix Fire Arc Reset

Source/CombatExtended/CombatExtended/ModSettings/Settings.cs
- Adds fix fire arc menu reset to default
- Was not added to menu
- Suffer
=> Fix Fire Arc Menu Reset

Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_BunkerBuster.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Flare.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_SpawnsThing.cs, Source/CombatExtended/Harmony/Harmony_NotifyClamorImpact.cs
- Added impact clamors to projectiles, making nearby animals flee. This largely just copies vanilla behavior, except with the chance raised to 60% because of CE's increased accuracy.
- Animals standing around when shot at is kinda silly.
=> Add impact clamors

Source/CombatExtended/Harmony/Harmony_Fire.cs, Source/CombatExtended/Harmony/Harmony_Hediff_Injury.cs
- Moves Fire.Tick transpiler to to Fire.TickInterval
- Updates Hediff_Injury.PostAdd Transpiler
- IL showing Bgt_un_s for Hediff_Injury
- TickInterval has supplanted Tick()
- Broken patches
=> Update More Failing Transpiler Patches

Source/CombatExtended/CombatExtended/Comps/BipodComp.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_BipodDisplay.cs
Git manual rebase and squash of #4038 
- Closes #4038
=> Squash Viral's Bipod fixes

Source/CombatExtended/CombatExtended/Verbs/Verb_ThrowGrenade.cs
Base assumption is now line-drive, then adjusted for cover.
- After #4032 
Low cover wasn't correctly triggering the cover-avoiding code, leading to line-drives into cover.
Targeting empty cells targeted the top left corner of the cell instead of the center
=> Throw grenade tweaks

Source/BetterTurretsCompat/BetterTurretsCompat.csproj, Source/CombatExtended/CombatExtended.csproj, Source/MiscTurretsCompat/MiscTurretsCompat.csproj, Source/MultiplayerCompat/MultiplayerCompat.csproj, Source/PsyblastersCompat/PsyblastersCompat.csproj, Source/SOS2Compat/SOS2Compat.csproj, Source/SRTSCompat/SRTSCompat.csproj, Source/VehiclesCompat/VehiclesCompat.csproj
- Updates Nuget package so can be compiled against most recent version of RW with new DLC code included
- New DLC
- Suffer
=> Update Nuget Packages

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml, Defs/ThingDefs_Misc/Apparel_Headgear.xml, Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs, Source/CombatExtended/CombatExtended/Defs/ApparelDefExtension.cs
- Closes #4017 
- Massive rebase hate life full indention change make go crazy
- Suffering
=> Soft Armor Check

LoadFolders.xml, Odyssey/Patches/Abilities/Abilities_Odyssey.xml, Odyssey/Patches/Bodies/Crab.xml, Odyssey/Patches/Bodies/Cyclops.xml, Odyssey/Patches/Bodies/Drones/BodyParts_Drone.xml, Odyssey/Patches/Bodies/Drones/Drone.xml, Odyssey/Patches/Bodies/Drones/DroneWithThreads.xml, Odyssey/Patches/Bodies/Drones/DroneWithThreeLegs.xml, Odyssey/Patches/Bodies/Larva.xml, Odyssey/Patches/Bodies/Pinniped/Pinniped.xml, Odyssey/Patches/Bodies/Pinniped/PinnipedWithTusks.xml, Odyssey/Patches/Bodies/Snail.xml, Odyssey/Patches/DamageDefs.xml, Odyssey/Patches/GeneDefs/GeneDefs_Odyssey.xml, Odyssey/Patches/PawnkindDefs/PawnKinds_Odyssey.xml, Odyssey/Patches/ThingDefs_Buildings/Buildings_Security.xml, Odyssey/Patches/ThingDefs_Items/Items_Resource_Stuff_Leather.xml, Odyssey/Patches/ThingDefs_Items/Items_Resources_Exotic.xml, Odyssey/Patches/ThingDefs_Items/Items_Resources_Fish.xml, Odyssey/Patches/ThingDefs_Items/Items_Resources_Misc.xml, Odyssey/Patches/ThingDefs_Items/Items_Resources_Stuff.xml, Odyssey/Patches/ThingDefs_Misc/Apparel_Odyssey.xml, Odyssey/Patches/ThingDefs_Misc/Weapons_UniqueGuns.xml, Odyssey/Patches/ThingDefs_Races/Races_Animals.xml, Odyssey/Patches/ThingDefs_Races/Races_Animals_Bird.xml, Odyssey/Patches/ThingDefs_Races/Races_Animals_Coastal.xml, Odyssey/Patches/ThingDefs_Races/Races_Animals_Insects.xml, Patches/Core/Bodies/BodyParts_Animal.xml
- Initial, partial pass at Odyssey XML patching.
- New animals, body types, weapons, materials, apparel, etc.
- More animal to patch.
- Boghound
- Prairie Dog
- Scimitar Cat
- Wolverine
- Greatwolf
- Alphathrumbo
- Megavole
- Bullfrog
- Colossus Toad
- Lava Snail
- Handle unique weapons.
- Many other things.
- Most current animal stats taken from existing patches.
- We do it because it must be done.
- Cannot into space.
=> Initial Odyssey XML Patching Pass

LoadFolders.xml, ModPatches/Weapon Proficiency/Patches/Weapon Proficiency/WP_stats.xml, SupportedThirdPartyMods.md
patch Weapon proficiency
added all the CE stats and removed range cooldown
none
none
I like the mod
not patch it
=> Weapon proficiency patch

ModPatches/Medieval Overhaul/Patches/Medieval Overhaul/ThingDefs_Misc/Shields/MO_Shields.xml
- Updates shield texture file path
- Mod changed file structure
- Suffer
=> Fix MO Shield Texture

Odyssey/Patches/Drugs/Drugs.xml, Odyssey/Patches/Scenarios/Scenarios.xml
Patch a couple of things I overlooked my first pass:
- Patch new drug bulk.
- Patch Odyssey scenario ammo.
- Keep it in line with other patched drugs.
- Need ammo in space.
Suffer.
=> Patch more DLC stuff

Odyssey/Defs/Ammo.xml, Odyssey/Patches/ThingDefs_Misc/Ranged_Spacer.xml, Odyssey/Patches/ThingDefs_Races/Races_Mechanoid.xml, Source/CombatExtended/Harmony/Harmony_CompDHunterDrone.cs
- Patches new drones from Odyssey
- Harmony patch on CompHunterDrone to utilize CE explosion
- Fragments due to being sizeable bomb inside a metal body
- Stabs based on agrihand stab
- More fragments/ Bigger Fragments
- Venom on Wasp stab
=> Patch odyssey drones

ModPatches/Vanilla Weapons Expanded - Frontier/Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier-Laser.xml, ModPatches/Vanilla Weapons Expanded - Laser/Patches/Vanilla Weapons Expanded - Laser/RangedSpacer.xml
- Updates more namespace issues
- Mod's parent framework changed namespaces
- Suffer
=> Fix VWE patches

LoadFolders.xml, ModPatches/Medieval Coastal Outfits/Patches/Medieval Coastal Outfits/CE_MedievalCoastalOutfits.xml, SupportedThirdPartyMods.md
All apparels are patched and balanced.
=> Medieval Coastal Outfits patch

ModPatches/Rimsenal Core/Defs/Rimsenal Core/Ammo_GDGrenades.xml, ModPatches/Rimsenal Core/Patches/Rimsenal Core/Ammo_GDGrenades.xml, ModPatches/Rimsenal Core/Patches/Rimsenal Core/Weapons_GD_CE.xml
Added micromissile ammo for GD launcher caliber
Replaced GD rifle Micromissile ability for underbarrel, as per normal with ability to underbarrel conversions.
=> 1.6 Rimsenal - GD underbarrel

Source/BetterTurretsCompat/BetterTurretsCompat.csproj, Source/CombatExtended/CombatExtended.csproj, Source/CombatExtended/CombatExtended/Render/PawnRenderNode_Apparel.cs, Source/MiscTurretsCompat/MiscTurretsCompat.csproj, Source/MultiplayerCompat/MultiplayerCompat.csproj, Source/PsyblastersCompat/PsyblastersCompat.csproj, Source/SOS2Compat/SOS2Compat.csproj, Source/SRTSCompat/SRTSCompat.csproj, Source/VehiclesCompat/VehiclesCompat.csproj
none
bump ``Krafs.Rimworld.Ref`` to 1.6.4535, and added the new constructor from rw ``PawnRenderNode_Apparel``
- Closes #[#4117]
update to newest rw render
n/a
=> Render error fix and rw nuget bump 

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Fixes edge case of both ground and air intercept allowing all projecitles
- Odyssey shield generator for gravship intercepts both
- Needed in case other mods block both.
- Suffer
=> Fix projecitle interceptors

LoadFolders.xml, ModPatches/Gravship Captain Set/Patches/Gravship Captain Set/Patches_Apparel.xml, ModPatches/Life Support Pack/Patches/Life Support Pack/Patches_Apparel.xml, ModPatches/Odysseus Vacsuit Set/Patches/Odysseus Vacsuit Set/Patches_Apparel.xml, ModPatches/Prestige Vacsuit Set/Patches/Prestige Vacsuit Set/Patches_Apparel.xml, ModPatches/VacSlipsuit/Patches/VacSlipsuit/Patches_Apparel.xml, ModPatches/W1NG VacSuit Set/Patches/W1NG VacSuit Set/Patches_Apparel.xml, SupportedThirdPartyMods.md
6 patches for Kilo Vacsuit mods
no real change to CE
I like more suit variants
not patch them
As of making this pr the kidsilpsuit have wrong name in texture, and it persists after removing CE
=> Patch Vacsuit mods

ModPatches/GREG/Patches/GREG/ThingDefs_Races.xml
Creature names were changed in the original mod.
Patch prepared by the original mod's author.
=> Updated creature IDs for GREG

LoadFolders.xml, ModPatches/Chougou Mechs/Defs/Chougou Mechs/5x35mmCharged_CGM.xml, ModPatches/Chougou Mechs/Patches/Chougou Mechs/PawnKinds/PawnKinds.xml, ModPatches/Chougou Mechs/Patches/Chougou Mechs/Scenarios/Scenarios.xml, ModPatches/Chougou Mechs/Patches/Chougou Mechs/ThingDefs_Misc/Weapons_Mechanoid.xml, ModPatches/Chougou Mechs/Patches/Chougou Mechs/ThingDefs_Races/Races_Mechanoid.xml, SupportedThirdPartyMods.md
Patches for the mechs/weapons/scenario
=> Chougou mechs
