Patches/Rockmen Race/PawnKinds_Rockmen.xml, Patches/Rockmen Race/Rockmen_Race.xml, Patches/Rockmen Race/Rockmen_Scenario.xml, SupportedThirdPartyMods.md
- Patch Rockmen Race.
- Rockmen have higher carryweight/carry bulk.
- In line with the base mod, rockmen have the same melee damage as humans, but have a surprise attack `stun` extra damage.
=> Patch Rockmen Race.

Patches/Thog's Armor/Armor_Thogs.xml, Patches/Thog's Armor/Armor_ThogsChild.xml, SupportedThirdPartyMods.md
Patch Thog's Armor.
- Armor patched in line with existing flak and plate armor.
- Child armor generally has around 50 - 75% bulk/wornbulk and roughly 60% protection of the adult version.
=> Patch Thog's Armor

Defs/Ammo/Flamethrower.xml, Defs/Ammo/Grenade/20x42mmGrenade.xml, Defs/ThingDefs_Buildings/Buildings_Turrets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/VFEIMeleeSpacer.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Melee_Warcaskets.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
- Fixed warcasket weaponry's draw size being borked in CE and requiring a mod extension being patched in.
- Added a screen shake node set to 0 for flamethrower projectiles.
- Updated the 20x42mm ammoset based on a new reference mentioning that the SAPHEI cartridge can go through 6mm of steel, also tweaked some incorrect values.
- Fixed the flak cannon's classic mortar set up, it was missing a single necessary node.
=> Assorted fixes

Patches/Paniel the Automata/HediffDef/Hediff.xml, Patches/Paniel the Automata/PawnKindsDef_Paniel/PawnKinds_Misc.xml, Patches/Paniel the Automata/ThingDefs_Misc/Paniel_Apparel.xml, Patches/Paniel the Automata/ThingDefs_Races/AlienRace_Paniel.xml, Patches/Rimsenal Collection/Federation/ThingDefs_Misc/Fed_Apparel.xml, Patches/Rimsenal Collection/Feral/ThingDefs_Misc/Feral_Apparel.xml, Patches/WarCasket Expanded/Apparel_Warcaskets.xml
**Paniel Race:**
- Patch the pawnkinds to give them ammo.
- Fix the Hediff patch, restructure to work better.
- Add some bulk/wornbulk as needed to avoid the autopatcher firing.
**Rimsenal:**
- Tweak some Federation and Feral apparel to avoid the apparel autopatcher.
**Warcaskets Expanded:**
- Patch the Centurion warcasket.
- Fix patches with the corrected defNames.
=> Misc. Compatibility Patch Fixes

Patches/Animal Armor - Vanilla/ThingDefs_Apparel.xml, Patches/Animal Equipment/CE_patch_Apparel_Plate.xml, Patches/Core/ThingDefs_Misc/Apparel_Various.xml, Patches/Darkest Rim Core/Apparel_DarkestCE.xml, Patches/Epona Race/ThingDefs_Misc/Epona_Apparel.xml, Patches/Kenshi Armory/KenshiArmory_Armour.xml, Patches/Medieval Overhaul/MO_Apparel_Armor.xml, Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_Apparel.xml, Patches/O21 Dragons Not Included/Apparel_Dragon.xml, Patches/RimFantasy - House Doyle/Patch_RFDoyle_Armor.xml, Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Medieval.xml, Patches/Vanilla Factions Expanded - Medieval/ThingDef_Misc/VanillaMedieval_Apparel.xml, Patches/Vanilla Psycasts Expanded/ThingDefs_Misc/Apparel_Patch.xml
- What it says on the tin, reduce the base game's plate armor and modded plate armors' worn bulk values by 2/3, resulting in the base game plate armor having 10 worn bulk instead of 15.
- After the discussion among the team, the decision was to reduce it from 15 to 10 as it was too high and a arbitrary value.
=> Reduce plate armor's worn bulk value

Patches/Vanilla Genetics Expanded/ThingDefs_Races/Races_Animal_Failures.xml
- What it says on the tin, the error caused by the transparent texture is fixed by changing the texture directory of the pawn to the actual one that has stuff in it in the mod itself. Also made the drawSize smaller as it was too big in-game at x3.
=> Fix the Flesh Fly's texture/hitbox issue

Defs/Ammo/Shotgun/23x75mmR.xml, Patches/Android Tiers Reforged/Ammo/RotaryShrapnelcannonShell.xml, Patches/Vanilla Factions Expanded - Pirates/Ammo/SlughthrowerShell.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
- Tweaked the 23x75mm shotgun shells based on an actual real world replica of the shell. The slug shell is faster than what's stated in the video because the shell used there is underloaded. The previous existing slug, beanbag and EMP shells were very absurd to begin with, absurd as in firing something 3 times the mass of a .50 BMG bullet at half the speed from a shotgun resulting in almost double the blunt AP...
- Tweaked and fixed some stuff for the ATR's shrapnel cannon shotgun shells.
- Added special shotgun shells for the warcasket slugthrower based on the item description stating the shotgun firing x4 12ga slugs.
- https://www.youtube.com/watch?v=en_55fzWeVo …
=> Shotgun shell fixes and tweaks

Patches/Fallout New Vegas - Elite Riot Gear/Apparel_RiotGear.xml, Patches/Heavy Melee Weapons/ThingDefs_Misc/Weapons.xml
**Fallout New Vegas - Elite Riot Gear**
- Update the FindMod with the 'Continued' version and remove the old version.
- Update the defName prefixes, which the new author changed for some reason.
**Heavy Melee Weapons**
- Update the FindMod with the 'Continued' version.
=> Update Fallout New Vegas - Elite Riot Gear + Heavy Melee Weapons Patches

SupportedThirdPartyMods.md
Simple compatibility patch for Royal Warcaskets mod
- Armor values are identical to patched values for corresponding non-prestige warcaskets
- Steel, component, and gold costs were doubled to fit better with corresponding patched VFEP warcasket costs. Plasteel costs were not touched
=> Royal Warcaskets patch

Defs/Drugs/Psychite_Psycho.xml
- Fixed a typo in the item description.
=> Psycho's description typo fix

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
- Both weapons dealt slightly less damage than their turret version in vanilla, it was not fair to chamber them in such smaller cartridges. Rechambered the autorifle in 20mm mauser (a proper autocannon cartridge) and the slug rifle back in 25mm nato.
=> Tweak Warcasket autorifle and slug rifle

Biotech/Patches/ThingDefs_Items/Items_BiotechGeneral.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/ThingDefs_Turrets.xml
- Made the mech boss loot items resistant to explosion damage sources so that they don't get deleted right after being dropped.
- Made the crashed gauntlet ships from VFE-Pirates resistant to their own explosions upon landing so that they don't destroy each other.
=> Explosion damage resistance tweaks

Patches/Giddy-Up 2/Job_Patch.xml, SupportedThirdPartyMods.md
- Made pawns be able to reload weapons while mounted, without the patch pawns have to dismount and reload. Also pawns are forced to dismount when the reload job is started.
=> Giddy-Up 2 compatibility patch

Patches/Vanilla Factions Expanded - Empire/Ammo/ChargeThumperRound.xml, Patches/Vanilla Factions Expanded - Empire/Ammo/FletcherRifleRound.xml
- What it says on the tin, the two newly added ammo were missing a speed node in their projectile defs.
=> Fix VFE-Empire's ammo speeds

Patches/Vanilla Factions Expanded - Empire/PawnKinds.xml
- Patched the parent def as it has many child defs derived from it that have the same weapon set up.
=> Patch VFE-Empire's deserter pawnkind

Patches/Android Tiers Reforged/ThingDef_Races/AlienRace_Androids.xml
- As of ATR ver. 1.2.11, mechs do Demolish damage instead of Blunt. Adjusted the patch to account for that.
- https://github.com/RWDevathon/Android-Tiers-Reforged/commit/6ba88ebb5131aef0bc4e299b6b5f8f9fc9d10f23#diff-a366102bfac3f60313f36e006c8bdeb73faf8c11f68ebe8c7209773275b5d70f
=> Tweak ATR mech's melee tool

Biotech/Patches/GeneDefs/GeneDefs_Misc.xml
- Tweaked the Nearsighted gene to retain its weapon handling penalty as aiming accuracy does not do much on its own.
- Tweaked the patch for the Unstoppable gene to retain the removed stagger effect upon the pawn being hit as the stagger effect still works in melee.
=> Tweak the Nearsighted and Unstoppable genes

About/About.xml
- What it says on the tin. It has to be loaded after CE otherwise it breaks the Give Ammo system.
- https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182
=> add What's That Mod load order rule

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
- Adds a `minAmmoCount` tag that defines how much ammo should the pawn at least spawn with. Can be set per pawnkinddef in loadout generation xml. Gives 10 bullets by default, unless it's a single-use weapon.
- Pawnkinds like `Pirate Gunner` often might spawn with a musket or double-barrel shotgun, while having only 3-4 mags of ammo set. This makes them spawn with very few bullets. Pirate gunner xml commit is an example of a use case.
- Grenades, disposable launchers, etc should not be affected by this, so minAmmoCount is 1 for them, unless pawnkind's minAmmoCount is set otherwise. 
- If minAmmoCount is higher than pawn's bulk limit, it gets reduced to fit inventory like before.
- …
=> Add minimum ammo count spawn tag

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
makes knock-downs (when an animal's melee attack crits) only occur when:
-the attacker is at least 1/5 mass of the equivalent mass of the pawn being attacked. 
-the equivalent mass is caculated by actual mass * (width/height).
-attacks on heads halve the equivalent target mass.
-When a crit occurs, animals have a chance to knock target down based on their relative size.
-knock down chance increases as attacker mass increases. reaches 100% when the attacker is heavier that equivalent target mass.
-moved the "knock down!" mote generation to damage application, so that only upon a successful knockdown will the mote appear.
(actual values can be disgussed, 1/5 is only a placeholder stat I pulled from my rear)
Let's imagine the following scenario:
Now you just built your shiny new …
=> Knock down mass limit

Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs, Source/CombatExtended/Harmony/Harmony_PawnInventoryGenerator.cs
- Sidearms will now follow base game rules for biocoding.  Note: knives do not appear to be biocodable.
- Closes #2269
=> biocode sidearms.

Source/CombatExtended/CombatExtended/Comps/HediffComp_Stabilize.cs, Source/CombatExtended/Harmony/Harmony_HediffTendPriority.cs
- Stabilized wounds are now tended before bruises/cracks/burns.
- Patched Hediff.TendPriority to return a value of a fraction of the normal bleed rate for stabilized bleeding
- Stabilized wounds that will start bleeding should be treated before bruises
- Patch to tendPriority was easy to implement
- Patch the tend job to not use a simple list sorted by a single number.
=> Tend priority accounts for stabilized wounds.

Defs/Ammo/Advanced/30x64mmFuelCell.xml, Defs/Ammo/Advanced/66mmThermalBolt.xml, Defs/Ammo/Advanced/80x256mmFuelCell.xml, Defs/Ammo/Medieval/CannonBall.xml, Defs/Ammo/Rocket/M6A3.xml, Defs/Ammo/Rocket/RPO.xml, Defs/Ammo/Shell/105mmHowitzer.xml, Defs/Ammo/Shell/120mmCannon.xml, Defs/Ammo/Shell/155mmHowitzer.xml, Defs/Ammo/Shell/50mmType89Mortar.xml, Defs/Ammo/Shell/60mmMortar.xml, Defs/Ammo/Shell/762x385mmRCannon.xml, Defs/Ammo/Shell/81mmMortar.xml, Patches/Call of Duty - Zombies Pack/Ammo/Recipe/30x64mmFuelCell-Punched.xml, Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml, Patches/LF Red Dawn/82mmMortar.xml, Patches/Not Only Just A Cannon/Patch_Cannon_Ammo.xml, Patches/Orassans/Ammo/ChemicalCompoundOE.xml, Patches/Paniel the Automata/Ammo/Ammo_Paniel.xml, Patches/Rimsenal Collection/Security/Ammo_Security.xml, Patches/Rimworld-Style Pilas And Bows Strapped With Grenades and Shells Extended/Javelin.xml, Patches/Turret Collection/TurretCollection_CE_Patch_Turrets.xml, Patches/Warcaskets - Adeptus Astartes/Ammo/Bolter.xml, Patches/Warcaskets - Adeptus Astartes/Ammo/HeavyBolter.xml
- Added the missing ammo types to the 50mm type 89 mortar shells.
- Updated some outdated values in the shell ammo type defs.
- Added a flat prometheum flame damage to incendiary (explosive) ammo types.
- As it is currently, the prometheum soak hediff is not stacking (with the altered ammo types in this PR) at all and the severity does not go up no matter how many times the hediff-causer projectile hits a target, which makes these ammo types very lackluster on that front. The RM2 flamethrower and molotovs are good because they deal raw prometheum flame damage. This change was made by giving a 10% damage multiplier and 15% to Incendiary and Fire bomb damage types respectively instead …
=> Update the incendiary ammo and housekeeping

Defs/SoundDefs/World_Sustainers_RPG.xml
-Rocket sustainers now pause when game paused
-The rocket motor sustainer is driving me mad when I pause the game with a rocket mid-flight
-Suffer.
=> Make rocket sustainer less an ear rape

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Gizmos/Command_Reload.cs
-Make "DEV: Set ammo to max" change currently using ammo to the selected ammo in reload gizmo
-Make reload gizmo show all ammo types when in god mode
-Do not stow weapon for player pawn when out of ammo and in god mode
so that we don't have to spawn the ammo when testing non default ammo.
Find and spawn corresponding ammo every time when testing something not FMJ, as convenient as pre-dev buttons.
=> Better ammouser dev button

Source/CombatExtended/CombatExtended/Comps/CompAmmosetSwitcher.cs
-Make UBGL gizmo only appear on player pawns (or in god mode)
=> Fix ubgl faction check

Source/MultiplayerCompat/MultiplayerCompat/MultiplayerCompat.cs
- Fix ITab_Inventory syncing, recovered SyncWorker for ITab_Inventory.
- Fire a gun caused Desync in Multiplayer
- Try any command in pawn's equipment(drop, drop and haul, consume thing) produce Exception cuz no SyncWorker for ITab_Inventory.
N/A
=> [MultiplayerCompat] Fix ITab_Inventory syncing

Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
- Change the default `minAmmoCount` from 10 to 1.
- Remove a check that applied if the minAmmoCount prescribed was using the default of 10.
The `minAmmoCount` determines the absolute minimum amount of ammo a pawnkind will spawn with, overriding the amount spawned by the pawn's loadout if it is smaller. With 10 as the default value, it will apply to any and all pawnkinds that don't have a `minAmmoCount` otherwise prescribed to them.
Given the wide range of different weapons these pawns may be armed with, it's not desirable to force them to spawn with this much ammo across the board. While 10 is perfectly reasonable for a pawn spawning with a bow or a musket, it's potentially too much for a pawn spawning with a rocket launcher or similarly heavy weapon--they might be assigned something like …
=> Change the minammocount from 10 to 1.

Defs/Ammo/GENERIC/Generics_Misc.xml, Defs/Ammo/Pistols/454Casull.xml, Defs/Ammo/Shotgun/410Bore.xml
- What it says on the tin, it lacked the newly added .410 ammo types.
- Changed the normal .410 shotgun ammoset to be similar to Shotgun generic ammoset.
=> Fix the RevolverShotgun generic ammoset

Patches/Rim-Effect Core/Apparel_ME.xml, Patches/Rim-Effect Core/Armor_ME.xml, Patches/Rim-Effect Core/ME_Machine.xml, Patches/Rim-Effect Core/Mech_Weapons.xml, Patches/Rim-Effect N7/Armor_N7.xml
Did some work on the Rim-Effect patches.
- Fixed some failing patch operations.
- Added some missing Bulk values for apparel, so that the autopatcher no longer messes with them.
- Simplified a couple of operations.
- Whitespace clean-up and other housekeeping.
The Rim-Effect Core and N7 mods updated recently, so the patches needed some adjustment.
=> Rim-Effect Patches: Updates, Fixes, Housekeeping

Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs
- All suppression received by pawns is multiplied by a constant (currently 2).
- After the changes in #2201, projectiles that are slower than 360 speed have suffered from decreased suppression overall. This change should make suppression amounts similar to before #2201 for weapons that have around 180 speed.
=> Add hidden additional suppression factor.

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Put the firingWithoutTarget code in front of projectile makeThing.
Before this change, the trycastshot code aborts shooting when the target is gone and not in suppress mode *after* the projectile thing was made. Which is normally harmless as the projectile dissolves itself when out of bound. However, under the circumstanse of there're any obstacle between the last target location and (-inf,-inf), a red letter appears as the newly-made-still-in-chamber bullet tries to collide before it dies.
By moving the abortion code in front of projectile make thing, the launch process is aborted before projectile is given birth, fixing this red letter.
Suffer.
=> Fix mid burst bug

Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs
Fix berserk pawns endless reloading bug
=> Fix for berserk pawn endless reload (issue 2411)

Source/CombatExtended/CombatExtended/AI/Comps/CompReload.cs
- If the ammo system is disabled, and a pawn tries to fire a weapon that is out of ammo, they will stow their weapon instead of reloading. This patch fixes this behavior.
- Closes #1461
* Disable the ammo system
* Draft a pawn
* Equip them with a gun (like an assault rifle)
* Give them an attack order so they drain their ammo
* When they run out of ammo, they will automatically attempt to reload
* Interrupt them by issuing a move order
* Give them another attack command, while they have no ammo
* They will automatically stow their weapon instead of reloading
=> Fix a bug when swapping weapons

Defs/Ammo/Pistols/22Short.xml, Defs/Ammo/Rifle/280British.xml, Defs/Ammo/Rifle/485x49mm.xml
Fixed .22 Short's mass and bulk values being backwards. Also corrected some small grammar issues.
Projectile sheet: https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit#gid=1393347070
It's a fix, .22 Short was too heavy and not bulky enough (as if it matters, but still)
=> Fixed .22 Short's mass and bulk values + some spelling corrections

Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Turret.xml
- Increased the spread of the mounted charge blaster turret from biotech to 0.2.
- It's not affected by the accuracy stats of the mech it's mounted on and it's pretty accurate with 0.08 spread, 0.2 degrees of spread should make it less accurate as it seems like it has aimbot or something...
- Let players mald about the accuracy.
=> Biotech charge blaster turret accuracy tweak

Source/CombatExtended/CombatExtended/DangerTracker.cs, Source/CombatExtended/CombatExtended/SuppressionUtility.cs, Source/CombatExtended/CombatExtended/Things/Smoke.cs
1. Danger becomes less important with better initial cell cover rating;
2. Pawns will no longer even consider pathing to other sides of impassable terrain when running for cover, though will still consider mantling over cover (and, additionally, moving trough doors) as a worse path;
3. Pawns will prefer to move away from their suppressor's location, however this preference is smaller than the distance cost.
4. Danger generated by explosives by default falls over distance, being around x0.5 at the edges;
5. Smoke now sets danger at a cell depending on the concentration instead of increasing it by a flat value.
1., 2., 3. and 4. Reported cases of "pawns doing stupid things when running for cover";
5. #2414.
1., 2., 3., 4., 5. Can't be bothered, really, just reread the References.
- …
=> Danger behavior adjustments

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Explosive.cs
the removed code in projectileCE's exposeData is causing redletters when a projectile aimed at ground is saved and loaded.
Added scribe for impactPosition because the lack of it caused grenades fail to detonate if they're saved and loaded when landed.
Suffer.
=> fix some save-load bugs

Patches/Core/Stats/Stats.xml, Patches/Core/ThingDefs_Races/Races_Humanlike.xml, Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_StatDefOf.cs, Source/CombatExtended/CombatExtended/StatParts/StatPart_MechDurability.cs, Source/CombatExtended/CombatExtended/StatParts/StatPart_NaturalArmorDurability.cs
Natural armor degration now has a minimal value.
Several new fields in MechArmorDurabilityExt:
MinArmorPct as the general min armor percentage for all armor categories, if no explicit values are given. Default at 0.25
MinArmorValueSharp/Blunt/Heat/Electric as the explicit min value for each armor category. These overrides MinArmorPct in their respective category. Value below 0 deactivates it. Default at -1 (deactivated)
Removed the hardcoded statpart add which seems to break statdefof.
Used traditional xml patching instead
=> Armor degrade min amount

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_BodyPartGroupDefOf.cs
- Shield now behaves similar to apparel, will double-check for its blunt armor when deflecting sharp attack
- Contributes towards #2412
- Currently shield totally ignores its blunt armor when blocking sharp attack, rendering this stat somewhat useless (I really doubt any blunt weapon other than zeus hammer could overwhelm its blunt armor)
- It's reasonable that deflecting a bullet won't cause any damage, but this applies to melee too
- Can add additional checks for different behavior towards ranged sharp and melee sharp attack
- Or could add a new stat for "perfect deflection" which relates to the pawn's …
=> Checks shield's blunt armor after sharp damage deflection

Defs/Ammo/Grenade/20x42mmGrenade.xml
- What it says on the tin, the normal cartridges were grouped together with the grenades and were made at the machining table, this PR puts them in the loading bench similar to other normal ammo separate from the grenade ammo types.
=> Separate the normal from explosive ammo of 20x42mm

Patches/Android Tiers Reforged/Ammo/81mmMortar_SwarmShell.xml, Patches/Android Tiers Reforged/ThingDef_Misc/Apparel_Packs.xml, Patches/Android Tiers Reforged/ThingDef_Races/AlienRace_Androids.xml, Patches/Android Tiers Reforged/TraderKindDefs/Android_TraderKinds.xml
- What it says on the tin, the orbital trader needed patching and fixing and there were remaining stuff from the migrated races.
=> Update and fix ATR's patch

Patches/Morgante Mafia Weapons Pack/Weapons_Guns.xml, Patches/Thog's Guns - More Brukka Pack/Ranged_Industrial.xml
- Fix a couple of revolvers that were using .38 ACP (a semi-rimless automatic pistol cartridge) instead of .38 Special (a rimmed revolver cartridge.)
The .38 ACP ammo would not actually work in the revolvers due to a lack of a rim. Them being given the .38 ACP ammoset was likely a mistake. 
=> Fix Some Revolver Ammosets

Defs/ThingDefs_Misc/Weapons_Ranged.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Currently the gunner centipede uses the normal handheld minigun that because of it being set up to be hip-fired, it has a high sway value which makes the gun very inaccurate and veers of its aim mid-shooting. This makes it very undesirable as a weapon in the hands of a centipede. This PR adds a fixed version of the minigun with appropriate mass and longer barrel length to make the weapon a potent tool in the hands of the centipede gunner.
- The current mechanoid minigun is still chambered in 7.62x51mm, one could chamber it in .338 Norma to make it compete a bit better with the Heavy Charge Blaster chambered in the almighty 12x64mm. This'd bridge the vast …
=> Add the mechanoid version of the minigun

Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Fixed the incorrect syntax for the weapon tag's patch.
=> Fix the MechanoidMinigun weapon tag patch

Defs/Ammo/Rifle/4570Gov.xml
- Removed the .45-70 ammoset as it serves virtually no purpose. The Gatling gun from Armory will use the normal ammoset.
=> .45-70 Trapdoor removed

Defs/DamageDefs/Damages_LocalInjury.xml
- What it says on the tin, applied a x0.25 building and plant damage multiplier to the Beanbag damage type so that it does not deal more damage to walls and such than bullets like a shotgun slug.
=> Reduce Beanbags' damage to buildings

Defs/Ammo/HighCaliber/23x152mmB.xml
Sources:
https://en.wikipedia.org/wiki/ZU-23-2
https://en.wikipedia.org/wiki/23%C3%97152mmB
http://www.steelbeasts.com/sbwiki/index.php/Ammunition_Data#Autocannon https://arconpartners.net/products/ammunition/medium-caliber/23-x-152-mm-round-with-armour-piercing-incendiary-tracer-projectile-api-t-for-23-mm-anti-aircraft-guns-zu-23-2-2a13-and-zsu-23-4/ https://arconpartners.net/products/ammunition/medium-caliber/23-x-152-mm-round-with-high-explosive-incendiary-projectile-hei-for-23-mm-anti-aircraft-guns-zu-23-2-2a13-and-zsu-23-4/
Adds a new autocannon AmmoSet, 23x152mmB
- The usual AP, AP-I, AP-HE and Sabot ammo types
- In case someone decides to add a ZU-23 autocannon. Though the 23mm …
=> New autocannon cartridge

About/About.xml, Patches/New Mech - Mini-Miner/Race_MiniMiner.xml, SupportedThirdPartyMods.md
- A very small patch for the new Mini-Miner mech. It inherits most of its stats from LightMechanoid, its parent.
- Added it as a 'Load Before' mod because the author has, for some ungodly reason, patched all the new stuff in rather than just making them Defs. This will hopefully go away at some point in the future.
Close #2469 
Also, I removed a bit of trailing whitespace in the ThirdPartyMod file that was there for some reason.
=> Patch New Mech: Mini-Miner

Defs/Ammo/Rocket/90mmRecoilless.xml
Makes guns able to use 90mm RCR canister and also display caliber information
Changed the base bullet from explosive to Base12GaugeBullet
Was quick, easy, works, and I wanted to fix something.
Removing 90mm RCR, or harassing the person who first implemented it for not play testing anything.
- [] (For compatibility patches) ...with and without patched mod loaded
=> Fix 90mm recoilless' canister projectile issue

Patches/Rimsenal Collection/Core/Apparel_RS_CE.xml
Modified the movespeed penalty on the helmet slightly. Increased the provided carry weight for the body armor itself. This should result in an overall simmilar movespeed penalty from the armor from the current configuration, without making the armor exceptionally good when moving capacity is scaled up. Additionally leaves the armor as heavily armored but still somewhat less optimal that cataphract given the price difference in the two.
Assault Armor is aquired before cataphract, but is supposed to be the heavily armored, slow version of power armor compared to conventional power armor. This leaves the defensive parameters as is as well as movespeed retaining around the same value as previous speed penalty on the armor. Increased mass of the helmet compared to cataphract combined with the …
=> Rimsenal Assault Armor changes

Patches/Vanilla Weapons Expanded/Ammo/AntiGrainRocket.xml
- Minor housekeeping after tweaking the SPG9 ammo, the old parent def was being used in VWE that needed fixing.
=> Minor housekeeping

Defs/Ammo/Shotgun/10Gauge.xml
- Fixed the spread multiplier on the 10ga buckshot mamo from 17.8 to 8.9.
=> Fix 10gauge buck's spread multiplier

Patches/Rimsenal Collection/Security/Ammo_Security.xml
- What it says on the tin, the HEAT rocket incorrectly had the `CombatExtended.ProjectileCE_Explosive` thingClass which needed removing.
=> Fix Rimsenal Security's rocket launcher ammo

Patches/Dusk Armory/Apparel_Dusk_Armor.xml, Patches/Dusk Armory/Apparel_Dusk_Cloak.xml, Patches/Dusk Armory/Apparel_Dusk_Helmet.xml, Patches/Dusk Armory/Apparel_Dusk_Hood.xml, Patches/Dusk Armory/Apparel_Dusk_Hooded_Helmet.xml, Patches/Dusk Armory/Weapons_Dusk_Melee.xml, Patches/Dusk Armory/Weapons_Dusk_Ranged.xml, SupportedThirdPartyMods.md
- What it says on the tin, some apparel and weapons that needed patching.
- The weapons are based on the Dusk gear unlike the VOID stuff that are loosely based on the X-Dusk set.
=> Patch Dusk Armory

Patches/Vanilla Races Expanded - Waster/HediffDefs/Hediffs.xml
- The Pollution Accuracy gene needed patching which is patched similarly to the Nearsighted gene from Biotech.
=> Patch VRE Waster

Patches/Core/ThingDefs_Races/Races_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid_PlayerControlled.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml
- Gave the pikeman mechs their leg melee attack tool back, the poor guys need it.
- https://docs.google.com/spreadsheets/d/11e6FkTQvZiJpq7DpXUk9JSXBSq9enrx0DQhTTJ2xH7c/edit#gid=647442519
=> Pikeman mech leg attack tool

Defs/Ammo/Medieval/CrossbowBolts.xml, Defs/Ammo/Neolithic/Arrows.xml, Defs/Ammo/Neolithic/GreatArrows.xml
- Fixed and tweaked some values for the Arrows and Bolts in the spreadsheet. Some of the mass, velocity and casing mass values needed consistency checks and fixes. The arbitrary Area Factor value for the Stone arrows was changed from 2.0 to 1.5 which allowed for more freedom in accurately changing and fixing the data.
=> Arrows and Bolts tweaks and fixes

Defs/Ammo/Medieval/CannonBall.xml
- The final spread of the grapeshot ammo was too tight making it a superior single-shot ammo to the round shot instead of it being more of a crown control ammo.
=> Increase Grapeshot's spread factor

Defs/Ammo/Rocket/RPG7.xml
- Changed the dimensions of RPG-7 grenades based on a new calculation in the projectile spreadsheet resulting in smaller bulk values.
- Fixed some inconsistencies.
- The majority of the bulk taken up by RPG-7 grenades are the rocket motor and the booster that sit in the carrier's backpack and the warhead usually sticks out of the backpack's top. The spreadsheet counted the warhead diameter and length for bulk calculations which is not representative of how much space the grenades take. As a result, to take the motor and booster length into account and reduce the unrealistic bulk value of the ammo, the spreadsheet data is changed in a way that the overall length of the ammo is actually …
=> RPG-7 ammo bulk tweaks and housekeeping

Patches/Core/DamageDefs/Damages_LocalInjury.xml
- Patched the default damage and armor penetration of BombSuper damageDef.
- The damage type is used in various places without a damageAmount node which means it deals the default 550 damage contrary to the 81mm anti-grain shells dealing 800 damage. Patching the default damage and AP to 800 and 264 repectively makes its performance consistent with said shells everywhere it's used.
=> BombSuper damageDef consistency check

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
1. Hard armor takes half as much damage than before by using a constant factor.
1. After https://github.com/CombatExtended-Continued/CombatExtended/commit/89577b52c3ba46cacccd8002365e414c99ec6f4a and other armor damage changes, the damage taken by armor changed to blocked damage and how close the penetration value is to the armor value. This caused damage to grow, for example, in the case of a normal steel armor vest against 7.62mm NATO FMJ, from about 8 to about 28, while armor health remained the same.
1. Update armor health directly:
1. A lot of busy work required to do that.
- This mean that a normal steel armor vest will now be penetrated by 7.62mm NATO FMJ on the 6th bullet instead of the 3rd.
- Testing with the changes:
- Normal steel armor vest health against 7.62mm NATO FMJ: …
=> Hard armor health damage reduction

Source/CombatExtended/CombatExtended/DefUtility.cs
Now checks any verb that's assignable from Verb_LaunchProjectileCE
See issue #2450 
- Closes #2450 
Usually when running out of ammo enemies are close enough, and in that case using a grenade as melee weapon should only happens when in desperate situation (e.g. having no melee weapon), and when having a better alternative (melee weapon in this case), it's reasonable that pawn switch to melee weapon rather than grenade.
=> Check verbs rather than CompAmmoUser when initializing ranged weapons

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechChild.xml, Patches/AOC The Cleanup Devil/Apparel/Apparel - Flex.xml, Patches/Apparello/ThingDefs/StuffPowers.xml, Patches/CP British Military Kit/CP_BMK_CE_Patch_Apparel_Shell.xml, Patches/Core/ThingDefs_Misc/Apparel_Various.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml, Patches/Nearmare Race/ThingDefs_Misc/Nearmare_Apparel.xml, Patches/Neclose Race/ThingDefs_Misc/Neclose_Apparel.xml, Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_Apparel.xml, Patches/O21 Outer Rim/Patch_OuterRim_Apparel.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Shell.xml, Patches/SCP/Apparel_SCP.xml, Patches/Saclean Race/ThingDefs_Misc/Saclean_Apparel.xml, Patches/Silkiera Race/ThingDefs_Misc/Silkiera_Apparel.xml, Patches/Solark Race/ThingDefs_Misc/Solark_Apparel.xml, Patches/Xenoorca Race/ThingDefs_Misc/Xenoorca_Apparel.xml
- Made parkas 4mm thick (<StuffEffectMultiplierArmor>4</StuffEffectMultiplierArmor>).
- Parkas are fluffy and when compressed, they are actually less than 5mm thick so it makes sense for them to reflect that thickness when it comes to armor multipliers.
- The vanilla parka has a x0.2 armor factor vs duster's x0.3 and CE dusters are 5mm thick, the change would help with the huge gap
- Parkas are useless outside of cold insulation in vanilla, it requires no tech to be made and with that high of a thickness. Flak jackets should and do outperform parkas in regards to raw armor value in vanilla but that's the opposite in CE by a large margin, the competition in vanilla is flak jacket vs duster and parkas are nowhere near them in terms of armor.
=> Parka thickness adjusted

Defs/Ammo/Advanced/30x64mmFuelCell.xml
- Made 30mm fuel cells craftable in the machining bench similar to other launcher ammo and fixed its research prerequisites.
=> 30mm Fuel Cell housekeeping

Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Melee_Warcaskets.xml
- Increased the armor penetration of the warcasket knife and broadsword, both were severely lacking in the AP department for weighing 10 and 35kgs each.
- Made the warcasket knife attack faster in return for a bit less damage.
=> Tweak warcasket melee weapons

Defs/Ammo/Grenade/20x42mmGrenade.xml, Defs/Ammo/Grenade/25x59mmGrenade.xml, Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/Grenade/40x53mmGrenade.xml, Defs/Ammo/Grenade/40x53mmVOG25Grenade.xml
- Updated and fixed some values according to the spreadsheet and new sources.
- Introduced a 50% bullet damage multiplier for HEDP nades as not all of the projectile's mass does the damage transfer. It also alleviates the need for arbitrary bullet damage values that are currently used.
=> Launcher grenade consistency checks

.gitignore, Patches/Warhammer 40k - Genes and Psycasts/GeneDefs.xml
https://steamcommunity.com/sharedfiles/filedetails/?id=2880152795
- Patched all genes, hopefully, that have to deal with sharp, blunt and carry capacity. Left bulk alone as I have no clue on balancing, OP as it is anyway. 
- I reduced some carry weights as 1200 weight seems excessive on Primarch and Custodes. 
- I calculated the sharp and blunt values using (sharp of vanilla flak pants/sharp from gene)*sharp of flak pants in CE respectively.
- Left maxhitpoints alone, don't know how to …
=> Warhammer 40k - Genes and Psycasts

Patches/Warhammer 40k - Genes and Psycasts/Abilities_SpaceMarine.xml, Patches/Warhammer 40k - Genes and Psycasts/GeneDefs.xml, Patches/Warhammer 40k - Genes and Psycasts/Hediffs_Attacks.xml, Patches/Warhammer 40k - Genes and Psycasts/PawnKinds.xml, Patches/Warhammer 40k - Genes and Psycasts/TraderKinds.xml
Finish up the patch originally added as a draft PR. #2185 
- Patch pawnkinds and traders.
- Add ancillary stats to the various genes (smoke sensitivity, night vision, etc.)
- Balance pass for a few of the gene stats.
- Patch the acid spitting attack.
Armor levels and carrying capacity are fairly strong. In vanilla, this should make the xenotypes quite strong in combat--though, this will be lessened by power creep from other mods.
Could reduce carry weight and natural armor to lower levels, which might make them mesh somewhat more with vanilla. However, this would probably undermine the status of the space marine xenotypes as super-human killing machines.
=> Finish Warhammer 40k - Genes and Psycasts

Source/CombatExtended/Compatibility/WeaponToughnessAutoPatcher.cs
- Attempted to improve the weapon toughness autopatcher's resilience to breaking.
- Toughness autopatcher was mentioned in https://gist.github.com/HugsLibRecordKeeper/fc0a532e4a6ddf4548ee55acbf50b795
- Other mentions of the autopatcher breaking.
- Less red errors. One of the main reasons for the autopatcher breaking was a recipe definition with unexpected properties.
=> Updated weapon toughness autopatcher

About/About.xml, Source/CombatExtended/Harmony/Compatibility/Harmony_AlphaGenes.cs, Source/CombatExtended/Harmony/Harmony_MechanitorTracker_CanCommandTo.cs, Source/CombatExtended/Harmony/Harmony_MechanitorTracker_DrawCommandRadius.cs
Increased the Mechanitor control range to 43.9 cells.
The draw radius patch destructively prefixes the original to stop it from drawing, but should still play nice with other postfixes on it.
**This will likely conflict with other mods that modify the range and will have to be resolved manually.**
=> Mechanitor command range increase

Defs/Ammo/Shell/81mmMortar.xml
- What it says on the tin, 81 mortar shells don't have casings like howitzer shells.
=> No shell casings for 81mm shells

Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_Ammo_Spacer.xml
- What it says on the tin, should have changed from 150 to 144.
=> RM2 projectile velocity typo fix

Patches/Core/ResearchProjectDefs/ResearchProjects.xml
- Changed the Greatbow's research project techLevel to Neolithic.
- Reduced the Greatbow research project cost from 600 down to 400.
- Greatbows/Longbows date back to thousands or years ago and the weapon itself is considered a neolithic thing in xml.
- The research project already requires 400 points of prior research in non-tribal starts and 600 is too much for something that does not provide that much of an improvement over a recurve bow.
=> Greatbow research redemption

Patches/Star Crafter's Armory/CMC300.xml, Patches/Star Crafter's Armory/CMC405.xml, Patches/Star Crafter's Armory/PPS.xml
Restored the patch that removes ToxicSensitivity, since the original mod uses the wrong node name.
Restored the patch that was wrongly changed to "ToxicResistance" - in this case, it's correct, since we are _removing_ the bad node from target items.
Patch is fully correct otherwise, but this change caused the item to have unviewable description.
Change the node to correct one in the target mod: author is unresponsive.
=> Restored the patch that removes ToxicSensitivity for Starcrafter's Armoury

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml, Biotech/Patches/ThingDefs_Misc/Apparel_BiotechVarious.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Misc/Apparel.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_PristineStrider.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml
- Added some missing nodes to the mechanitor power armors.
- Removed the direct combat penalties from the mechanitor armors.
- Minor tweaks to the strider mech inventory capacities.
- The mechanitor armors already take a lot of setup to get and are simply modified normal power armor. Leaving them with no accuracy bonuses (neutral status) is a better approach than a flat nerf since the helmets already do not provide any night vision which is penalizing enough. The neutral accuracy is also comparable to how normal power armors don't give an accuracy bonus in vanilla but do in CE.
=> Mechanitor power armor adjustments and housekeeping

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Light.xml
- Adjusted the melee attack of the constructoid mech as it's supposed to be slightly weaker and slower than a pikeman headbutt.
=> Constructoid melee tool tweak

Patches/Vanilla Apparel Expanded - Accessories/Apparel_Utility.xml
- Adjusted the cost of the belt to reflect an explosive belt.
- Adjusted the bomb damage dealt by the belt exploding to 200 as it was using the default Bomb damageDef's damage value of 634.
=> Tweak and fix the explosive belt from VAE Accessories

Patches/Alpha Mechs/ThingDefs_Misc/AlphaMechs_RangedMechanoid.xml, Patches/Core/DamageDefs/Damages_LocalInjury.xml
- What it says on the tin, just to make direct frostbite attacks be counter-able with CE's percentage damage reduction code.
- A small tweak the the Alpha Mech's cryo weapon to adjust for the new change.
=> Add Heat armorCategory to Frostbite damageDef

Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCount.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCountBatched.cs
- Modifying mech loadout now uses `GenUI.CurrentAdjustmentMultiplier()` for modifying the current amount
- This will make it so holding ctrl and/or shift will modify the amount for 10/100/1000 instead of only 1
- This is a quality-of-life feature
- Modifying by 1000 may be a niche feature, but 10 and 100 are quite likely to be usable in more situations
=> Mech loadout - holding shift/ctrl affects the amount of change

Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCount.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCountBatched.cs
- `Dialog_SetMagCount` will automatically close if the mechanoid is dead or despawned.
- `Dialog_SetMagCountBatched` will remove dead or despawned mechs from its list of mechs, and if there's none left it will close.
- Both dialogs will now handle more gracefully (no errors) situations of being opened with null data.
- `Dialog_SetMagCountBatched` no longer keeps a cached reference to a primary mech, as it would cause issues. Instead, ammo types and magazine size are cached (as it was the main reason the mech was cached in the first place).
- Mechs despawning or dying could cause issues.
- Those dialogs don't force pause the game, allowing for those situations to happen.
- Even if the dialogs were set to force pause, it wouldn't be force paused with Multiplayer mod (without additional code …
=> Mech loadouts - handle issues caused by despawned and dead mechs

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
- Changed condition for `Verb_MeleeAttackCE` so the final condition is no longer ignored (`CompMeleeTargettingGizmo.targetBodyPart != null`).
- This is the same type of issue as in #2557
- The current implementation was basically `potentiallyNullValue ?? (false && condition)`, the changed version is `(potentiallyNullValue ?? false) && condition`.
- Without this fix there was nothing wrong when the code was called, as `CompMeleeTargettingGizmo.SkillBodyPartAttackChance` handled the null value by returning 0. The proper handling of this check means that the whole condition will now be skipped if the body part was not specified, as opposed to running code that would do nothing.
=> Fixed unreachable condition in Verb_MeleeAttackCE

Source/CombatExtended/CombatExtended/Comps/CompAmmoGiver.cs
- Changed condition for `CompAmmoGiver` so the final condition is no longer ignored (`outAmmoCount >= ammo.stackCount`).
- The current implementation was basically `potentiallyNullValue ?? (false && condition)`, the changed version is `(potentiallyNullValue ?? false) && condition`.
- Without this fix, a pawn could give another pawn as much ammunition as they themselves could carry, as long as the other pawn had space for at least 1 more.
=> Fixed CompAmmoGiver allowing pawns to carry over maximum amount

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs, Source/CombatExtended/CombatExtended/Loadouts/Utility_Loadouts.cs
- Mechanoids can no longer drop their weapons from inventory
- Since mechanoids are generally not supposed to be able to drop weapons, I haven't included the option (even as a disabled/greyed out one)
- Adding a disabled option would most likely require adding new text, as the vanilla generic text doesn't match too well ("This person refuses to drop this" doesn't really work well with mechanoids).
- `IsItemMechanoidWeapon` could be expanded to checking if the weapon's `weaponTags` in any way with mech's tags. I thought this shouldn't be needed and current code would be enough, but let me know if it it's needed for any reason
- This code could potentially be expanded to all inventory, possibly excluding ammo. I've decided against it, but it shouldn't be hard to change. …
=> Prevent mechanoids from dropping their weapons

Patches/Core/DamageDefs/Damages_LocalInjury.xml, Patches/Vanilla Apparel Expanded - Accessories/Apparel_Utility.xml
- Removed the problematic patch added in #2550.
- Adjusted the Bomb damage patch introduced in #252 that changed its default damage and AP as it was causing problems in cases like the explosive belt from VAE Accessories. There are cases that are not solvable in XML with how the default bomb damage is absurdly high. The new values are replicated 81mm HE shells.
=> #252 and #2550 revised

Defs/HediffDefs/Hediffs_CE.xml
- Changed the label of the hediff so that there are no double mentions of "wearing" in the label when the mask is worn.
=> Gas mask hediff label housekeeping

Defs/ThingDefs_Buildings/Buildings_Turrets.xml, Defs/ThingDefs_Misc/Weapons_Turrets.xml, Patches/Core/ThingDefs_Buildings/Buildings_Security.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_Buildings_Security_Turrets.xml, Patches/Rimsenal Collection/Security/Patch_Security.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Furniture Expanded - Security/ThingDefs_Sentry.xml, Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml, Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml
- Gave the proper night vision node to turrets that already had them.
- `NightVisionEfficiency_Weapon` actually does not give night vision to turrets if it's used on the turret gun itself. The turret building needs the `NightVisionEfficiency` node that pawns get to actually have night vision.
=> Fix turret night vision

Source/CombatExtended/Harmony/Harmony_Bombardment.cs
- Transpiled the bombardment class to use its own damage and pen values, allowing it to be adjusted separately.
- Required for #2590 
- High default damage for Bomb damage can lead to unintended behavior, bombardment is the largest outlier contributing to the increased default damage.
=> Bombardment damage/pen adjustment

Source/ArtilleryCompat/ArtilleryCompat/Utility.cs
- Changed `CombatExtended.Compatibility.Artillery:HarmfulStrikes` to call `GetProjectileProperties` instead of doing a big condition
- The current condition was a bit messy, the new implementation should be much more readable
- The current implementation did not properly handle all projectiles - it assumed the projectile will be either `ThingDef.projectile` or `AmmoDef.detonateProjectile`. The correct projectile for the mortar are obtained through `AmmoDef.Users`.
- Every other place that I can see is using `GetProjectileProperties` instead of trying to access the projectile from the shell def.
=> Fix CompLongRangeArtilleryCE for mortars (VFE - Security compat)

Source/CombatExtended/CombatExtended/Projectiles/Projectile_FireTrail.cs
- Code creating the motes for `Projectile_FireTrail` is now surrounded with `Rand.PushState()` and `Rand.PopState()`
- Calls to `Verse.Rand` (specifically `Rand.Range`) happen after `GenView.ShouldSpawnMotesAt`, which would mean that those calls may trigger based on the current map.
- Unseeded calls to `Verse.Rand` cause desync if they happen at a different time or only for some players, as the state of the RNG seed would progress for only some of the players.
- General state of RNG must remain the same for all players, as Multiplayer uses deterministic lockstep to keep everyone synchronized - so calls to RNG would have different result where they were expected to be the same.
=> Fix Multiplayer desyncs caused by Projectile_FireTrail

Patches/Medieval Overhaul/MO_Apparel_Armor.xml, Patches/Medieval Overhaul/MO_Apparel_Helmets.xml, Patches/Medieval Overhaul/MO_Apparel_Misc.xml, Patches/Medieval Overhaul/MO_Materials.xml, Patches/Medieval Overhaul/MO_Pawns_Medieval.xml, Patches/Medieval Overhaul/MO_Weapons_Ranged.xml
Multiple items have been added since last patched.
- Added new armor to existing patches
- Patched various new leg armors
- Patched hyena and wolf pelt cloaks
- Patched Silk and Linen. Were never patched from original mod. Heat armor was way off on these two
- Removed leg slot from Gambeson and Surcoat. These were previously added due to MO not having leg armors at that time.
- Reduced Daer and Lindwurm sharp and blunt. Previously at steel level of armor
- Reduced Named Plate Mail armor levels of heat.
- Added quiver and bow to pawnkinds that were to spawn with Bow/Crossbows. Should always spawn with ammo and simple melee weapon
- Changed weapon tags on MO ranged weapons to keep original mods weapon selection for ranged combatants. 
- Fixed Brigand Marksman from spawning periodically …
=> Medieval Overhaul Patch Update

Source/CombatExtended/CombatExtended/Comps/CompAmmoGiver.cs, Source/CombatExtended/CombatExtended/GUI/Windows/Window_GiveAmmoAmountSlider.cs
- Added `GiveAmmo` method inside of `CompAmmoGiver`
- The method is marked with `SyncMethodAttribute` to be synchronized with Multiplayer present
- The method is called from the `FloatMenuOption` initialized in `CompAmmoGiver:CompFloatMenuOptions`, as well as `Window_GiveAmmoAmountSlider:Close`
- Both places previously had very similar code to start the job for a pawn to give ammo to another one, so this will remove a bit of code repetition and allow it to be called from other places more easily
=> Sync CompAmmoGiver in Multiplayer

Source/CombatExtended/CombatExtended/Comps/CompAmmosetSwitcher.cs
- In `CompUnderBarrel`, the methods `SwitchToUB` and `SwithToB` received `SyncMethodAttribute`
=> Sync CompUnderBarrel in Multiplayer

Source/CombatExtended/Contrib/MechTakeAmmoCE/Core/CompMechAmmo.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCount.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCountBatched.cs
- `CompMechAmmo:TakeAmmoNow` now has `SyncMethodAttribute`
- `Dialog_SetMagCountBatched` had the code for setting the loadout extracted into a separate method, which is now synced
- `Dialog_SetMagCount` now works more like the batched version for simplicity of syncing, so the changes are only applied when accepted in the dialog (instead of being instantly accepted). Since it was unused, I've tested it by opening this dialog instead of the batched one.
=> Sync mech loadouts in Multiplayer

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml
- Adjusted the crafting cost of the MAC-10 according to the gun spreadsheet, simple blowback guns require 2 less components to craft now.
=> MAC-10 cost adjustment

Defs/Ammo/Medieval/CannonBall.xml
- Lowered the spread to 26.7 (base 17.8*1.5) from 35.6 as it was unrealistically high.
=> Readjust cannon grapeshot spread

Source/CombatExtended/Harmony/Compatibility/Harmony_AlphaMechs.cs
Pawn unloads ammo before gun swap.
Tried to order (by code) pawn reload after gun swap, but failed.
- Guns getting destroyed on swap weapons.
- Override swap gun code.
=> (Alpha Mechs) Ammo destroy on gun swap fix 

Patches/Biomes Caverns/Weapons/CE_Thrumbungushroom.xml
Add Melee Tools to ThrumbungusShroom
Fix an oversight.
=> Biomes Cavern Thrumbungus Shroom Melee Tool Fix

Defs/ThingDefs_Misc/Apparel_Headgear.xml
- What it says on the tin, the Medieval tech level node was missing.
=> Add missing tech level node for the plate helmet

Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs
- Limits the amount of ammo that pawns without loadouts pick up to 4 magazines of their held weapon, respecting the mag override
- Requirements to initiate the pickup are unchanged (less than 2 mags held and no enemies nearby)
- Enemy ammo pickup amount is unchanged
- Pawns pick up in 4 magazine size batches, but don't try to drop excess from that amount (still allowing to manually pick up more ammo)
- **Loadout behavior remains unchanged**
- Previously pawns without loadouts tried to pick up as much ammo as their inventory allowed, which resulted in the pawns hoarding ammo from other colonists or carrying unreasanable amounts of ammo themselves.
- Limiting the pickup to 4 magazines lets them carry a reasonable amount without any setup.
- Leave the behavior unchanged - previous reasonings …
=> Limit the automatic ammo pickup to 4 magazines

Patches/Medieval Overhaul/MO_Siege_Trebuchet.xml
Some mod features were never patched and just removed previously.
- Flaming boulders were never patched and only removed when compat patch was first made. This adds that functionality back to the game.
=> MO Feature Fix

Patches/Gloomy Dragonian Race/ThingDefs_Bodies/Dragonian_Bodytype.xml, Patches/Gloomy Dragonian Race/ThingDefs_Items/Items_Resource_Stuff.xml, Patches/Gloomy Dragonian Race/ThingDefs_Misc/DR_Apparel.xml, Patches/Gloomy Dragonian Race/ThingDefs_Misc/DR_Weapon.xml, Patches/Gloomy Dragonian Race/ThingDefs_Races/Race_Dragonian.xml
Patch for gloomy dragopnian race, which is a distinct mod from dragonian. Seperated folder as there are a lot of different defs, enough that it isn't really worth sharing the patches with the old version.
Hammer no longer has augmented EMP in vanilla, so removed from the mace here.
We could try and merge the patch with the alternatiave version of the mod, but there's a lot of differnt defnames and the bodydef is different.
Check tests you …
=> Gloomy Dragonian Race Patch

Patches/Recon Mechanoid/Mech_PawnKinds.xml, Patches/Recon Mechanoid/Races_Mechanoid.xml, Patches/Recon Mechanoid/RangedRecon.xml, SupportedThirdPartyMods.md
- Patch Recon Mechanoid.
- Mechs have light armor and limited bulk capacity.
- Weapons a inferior variants (more sway, lower rate of fire, more recoil) of industrial and spacer rifles and SMGs. SMGs use pistol caliber (.45 ACP and 6x18mm Charged) while rifles are semi-auto in 5.56 NATO and 6x24mm Charged.
- Fix a listed mod on the SupportedModList that wasn't in alphabetical order.
Close #2511 
The mod notes these mechs as light, frontline models, only a small step up from militors. As such, their weapon options are more effective than the militor's shotgun--with the option of automatic SMGs or decent-ranged semi-auto rifles--but are still nothing special.
Could stat the weapons differently.
=> Patch Recon Mechs Mod

SupportedThirdPartyMods.md
None
Small PR to add Alpha Mythology to the list of supported mods
It seems to have an up to date patch [here](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/Patches/Alpha%20Mythology/AM_CE_Patch_Races.xml) so it must have been an oversight not to include it
Haven't tested it since this is just a markdown change
=> Add Alpha Mythology to the list of supported mods

Defs/ThingDefs_Items/Items_Resource_Ammo.xml
- Actually changed FSX's market value to 7.5$, it was left out in #2604.
=> FSX market value updated

Patches/Core/HediffDefs/BloodLoss.xml
- Relabeled the "hidden" stage back to the vanilla "minor" as it's not actually hidden and seeing it labeled as hidden in-game is really odd.
=> Bloodloss hediff hidden label renamed

Biotech/Patches/PawnKindDefs_Humanlike/PawnKinds_Special.xml
- Patched the Mechanitor and Sanguophage pawnkinds that were unpatched so far. The Mechanitor only needed a simple loadout and the Sanguophage pawnkinds received a loadout similar the base game mercenary pawnkinds.
=> Patch the special Biotech PawnKinds

Patches/Biotech Expansion - Mythic/BEM_AbilityDefs_Patch.xml
migrate BiotechExpansion's CE patch to CE side.
add patch for BiotechExpansion's abilities, blast range patch may need balancing, considering beside the mana costs it has a 2 hours cooldown.
needs[PR#2657](https://github.com/CombatExtended-Continued/CombatExtended/pull/2657) to work.
- Tribals need ways to close distance …
=> update BiotechExpansion's patch

Source/CombatExtended/Compatibility/VanillaPsycastExpanded.cs
Fixed shots interception (pawn with overshield was not able to shoot using some guns, e.g. chain shotgun)
=> VE Psycast Overshield: Projectile wont be intercepted if interceptor = launcher

Defs/ThingDefs_Items/Items_Unfinished.xml
- Added the unfinished armored apparel item for things like fragsuits which solves the issues of the material for the item and its unfinished thing being chosen incorrectly, Same thing that used to happen with ballistic goggles.
- Changed the texture for the unfinished texture to the unfinished armor texture, the apparel texture did not fit the bill.
=> Unfinished armored apparel

Patches/Spartan Foundry/Apparel_Headgear.xml
- Fix the helmet night vision. NightVision stats were incorrectly being patched into the worn offsets, instead of the statbases. As was, these stats were appearing on the helmet but not actually applying.
=> Fix Spartan Foundry Patch NV

Defs/Ammo/Shell/105x617mmR.xml, Defs/Ammo/Shell/57x307mmR.xml, Defs/Ammo/Shell/75x350mmR.xml, Defs/Ammo/Shell/77x350mmR.xml
Some new shells for the upcoming vehicles. All have been added to the main sheet.
- 105x607mmR (105mm gun on the Abrams)
- 57x307mmR (British Naval 6 Pounder, used on the Mark IV male)
- 75x350mmR (M4 Sherman's 75mm gun.)
- Fixed an incorrect recipe label amount and revised some labels.
=> Add New Shells

Patches/Warcaskets - Adeptus Astartes/Ammo/Bolter.xml, Patches/Warcaskets - Adeptus Astartes/Ammo/HeavyBolter.xml
- What it says on the tin, the ammo is custom and not conventional like normal firearm ammo so it does not make sense for it to have generic ammo which causes issues without the Bolter ammo having its own custom tailored generic ammo (the generic ammo system does not recognize the ammo types cuz they have custom ammo classes) which in the end would be exactly the same as the existing ammo.
=> Adeptus Astartes Bolter ammo fix

Source/CombatExtended/CombatExtended/Comps/CompFragments.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs
- Allowed to set a `castShadow` node to CE projectiles in XML, defaults to `true`
- Moved the shadow assignment for fragments to keep the original behavior (only 20% chance for frags to have a shadow)
- The value is only assigned at projectile launch, allowing it to be modified later
- Added on request from GarbageDay, for easier custom projectiles
=> Expose projectile shadow to XML

Patches/Core/ThingDefs_Misc/Apparel_Hats.xml, Patches/Moyo from the depth/ThingDefs_Misc/Moyo_Apparel.xml, Patches/Rimmu-Nation - Clothing/RNC_CE_Patch_Apparel_Headgear.xml, Patches/Vanilla Apparel Expanded/ThingDefs_Misc/Headgear_Industrial.xml, Patches/Vanilla Ideology Expanded - Hats and Rags/Apparel_Headgear.xml
Tuque texture(s) clip with a whole bunch of helmet textures, many people were comlaining about this before, and now that we actually have balaclavas there's no point keeping them thisway.
=> Move tuque back to overhead

About/About.xml, Patches/Vanilla Weapons Expanded - Makeshift/RangedIndustrial.xml
- What it says on the tin, no more special gimmicks, no more extra gizmos, no more headaches... (Makeshift ammo does not exist, scavenge or trade for it.)
- The alternatives are dead.
=> VWE Makeshift patch fix

Patches/Alpha Genes/ThingDefs_Races/Races_OcularSlinger.xml
- What it says on the tin, AA_ was changed to AG_.
=> Alpha Genes patch typo fix

Source/CombatExtended/Harmony/Harmony_Pawn_HealthTracker.cs
- Transpiler changes to kill mechs when downed.
- Recreate the vanilla behavior of mechanoids automatically dying when downed, removing the need to manually finish them off.
- Manually kill every downed mechanoid
=> Fix mech death on down

Patches/Appliances Expanded/CA_ChemfuelSmithy.xml, SupportedThirdPartyMods.md
Fixes ammo inheritance on Appliances Expanded for the Chemfuel Smithy.
Used 'generic' patch by targeting the ElectricSmithy tradeTags on ammunition defs and adding the required AutoEnableCrafting tag to them for the CA_ChemfuelSmithy
Simple and ensures all ammos, including any added by ANYTHING and other mods, is patched appropriately to the matching workbench type.
N/A
Patch works in local copy.
=> Patch for Appliances Expanded - Chemfuel smithy

Defs/Stats/Stats_Basics_Inventory.xml, Languages/English/Keyed/Descriptions.xml, Languages/English/Keyed/Stats.xml, Languages/Russian/DefInjected/StatDef/Stats_Basics_Inventory.xml, Languages/Russian/Keyed/Descriptions.xml, Languages/Russian/Keyed/Stats.xml, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_LongRange.cs, Source/CombatExtended/Harmony/Harmony_ThingDef.cs
- Distance stat for shells/rockets
- Long range radio stat (Appears only with ApparelDefExtension.isRadioPack == true)
- Description of stat
- Stat naming (Might be "LongRange" is a bit incorrect)
=> Shelling distance and long range radio stats

Patches/Core/HediffDefs/Hediffs_Local_Injuries.xml, Patches/Core/HediffDefs/Hediffs_Local_Misc.xml
- Made Scaria-ridden animals feel 50% less pain.
- Made bruises inflict more pain per severity, from 0.0125 to 0.0175 similar to other patched values in CE.
- Updated the pain patch for the Crush damages as it was simply replacing the vanilla value with the same one, it's 0.0175 similar to other damage types.
- Rabid animals don't care as much about pain.
- Bruises are trivial in CE and can lead to a body part, mainly the torso, getting destroyed due to chip damage before the pawn goes into pain shock, this will help mitigate that problem to some extent and would be consistent with the changes CE makes to other damage types.
- Increase pain threshold on rabid animals instead of the pain factor, or increase the pain factor if x0.5 is too low.
=> Hediff pain tweaks

Defs/ThingDefs_Buildings/Buildings_Turrets.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Vanilla Weapons Expanded/Spacer_Ranged.xml
- Replaced x6 industrial components in the charge guns' crafting recipe with x1 advanced component and adjusted the workToMake accordingly.
=> Charge weapon crafting recipe tweaks

Patches/Miho Race/Ammo/Ammo_Miho_Advanced.xml, Patches/Miho Race/ThingDefs_Misc/Weapons_Ranged.xml, Patches/Miho Race/ThingDefs_Races/AlienRace_Miho.xml, Patches/Miho Race/ThingDefs_Races/Race_MihoMech.xml
Added armor comps
Reduced mech shooting accuracy.
Increased carry weight on the heavy gun mechs to allow for better ammo load.
10mm gun was changed in properties, so updated that to match.
Matching grenade launcher performance to the vanilla equivalent means that there isn't a need to add 3 additional ammodefs for the weapon itself. Increased carry weight for heavy gun mech allows for 1 + 3 reloads of grenades with a bit spare.
=> Miho patches

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
- Fix null map warning that somehow cleared queued attack orders 
=> Fix warnings thrown on structure destruction in melee

Defs/Ammo/Grenade/25x40mmGrenade.xml, Defs/Ammo/Grenade/25x59mmGrenade.xml, Defs/Ammo/Grenade/30x29mmGrenade.xml, Defs/Ammo/Grenade/35x32mmSRGrenade.xml, Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/Grenade/40x53mmGrenade.xml
- Updated the stats of launcher grenades, especially the filling amount.
- Introduced a new formula for HEDP damage calculations based on explosive filling and reduced its filling amount by 25% since not all of it is used for the external explosion, some of it is used to deal the bullet damage.
=> Launcher grenade updates and tweaks

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Defs/AmmoDef.cs
easier than I thought, which scares me. I probably missed something but idk.
I'll see if I can do something with comprefuelable/reloadable
ammoCount field in ammodef. when this ammo is used, the ammoCount amount of shots will be added into the gun magazine per ammo item.
partialUnloadAmmoDef is used to handle, well, partial unloads, when there're remainders after dividing.
if CompReloadable is found on ammo def, another ammo item with a charge amount of the remainder will be given. Otherwise if partialUnloadAmmoDef is not empty, remainder amounts of it will be given. if both are not present, remainder will be wasted.
Say, a gun with 30 round capacity and each ammo item has an ammoCount of 15. it'll take 2 ammo to reload it. and when you unload the gun at 26 round remaining, you only get …
=> Integrated multi-round ammo

Patches/Dubs Rimatomics/Turrets_Rimatomics.xml, Source/CombatExtended/CombatExtended/WorldObjects/HostilitySheller.cs, Source/CombatExtended/CombatExtended/WorldObjects/TravelingShell.cs
- Fix Rimatomics HEL not targeting incoming world shells.
- Shells launched by a HostilitySheller have a null launcher pawn, when they should not
=> Shelling Fixes

Source/CombatExtended/Compatibility/BlockerRegistry.cs
CombatExtended.Compatibility.BlockerRegistry is now `public static` instead of just `static`
It's an API we want downstream mods to use, so it needs to be public.
Create a separate public API (would end up just proxying calls to this one).
Make them use a publicized CE (defeats the purpose of marking anything not public)
Make them use reflection (ick)
=> Make BlockerRegistry public

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
- Closes #2718
If the turret only has one type of ammo included, the secondary ammo stack is `null`.  This causes an NPE when trying to spawn that ammo stack, which prevents the turret from setting its ammo count to 0.
=> add null check for secondary ammo type

Patches/Rim-Effect Asari and Reapers/Races_Reapers.xml
Rim-effect asari and reapers brute has 2 left claws. changed one to right claw.
it has 2 sides, one claw on each.
=> fixed duplicated left claw on reapers' brute

Defs/Ammo/Projectiles_Fragments.xml
- Changed fragments from being a FMJ round to a HP round in the spreadsheet resulting in more raw damage.
- Frags are anemic damage-wise which is doubled by the fact that the minDamageToFragment node makes the damage value be fragmented into smaller numbers resulting is less than ideal results. Frags are also jagged resulting in nasty wounds like a HP bullet.
=> Fragments' damage adjusted

Patches/Core/ThingDefs_Items/Items_Resource_Stuff.xml
- Readjusted Hyperweave to be more in line with other armor fabrics like Devilstrand which as a result makes it more viable for use as an endgame fabric.
The heat armor is reduced to 0.2 which used to be absurdly high, the flat mass offset is removed and the mass factor value is reduced as them coupled with the high base mass value of Hyperweave resulted in the material being very unviable for use compared to something like Thrumbofur which does not have these penalties. The new numbers make it more reasonable and accurate to its item description and design compared to something like again Devilstrand.
=> Hyperweave rebalanced

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_MechWeaponry.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml
- Decreased the mass value of the inferno cannon down to 50kg and adjusted similar weapons accordingly.
- The high mass is serving no purpose for a mounted weapon and it's only takin inventory space which said inventory space will be adjusted in a later PR.
=> Inferno cannon tweaks

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml, Biotech/Patches/ThingDefs_Races/Races_Mechanoids_SuperHeavy.xml, Patches/Advanced Mechanoid Warfare/Patches/Patch_Races.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Apoptosis.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Infernus.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Legate.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Siegemelter.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_Starfire.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_WarEmpress.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Advanced/AdvGoliath.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Advanced/AdvSiegebreaker.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Clean/VFEGoliath.xml, Patches/Alpha Mechs/Mods/VFE_Mechs/Clean/VFESiegebreaker.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Goliath.xml, Patches/Alpha Mechs/ThingDefs_Races/AlphaMechs_Race_Siegebreaker.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml, Patches/MechanoidsExtraordinaire/ThingDefs_Races/Races_Mechanoid_MechanoidsExtraordinaire.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Races/RM_Races_Mechanoids.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid_PlayerControlled.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid_PlayerControlled.xml
- Reduced the mass carry capacity of large mechs. Centipedes got reduced from 250kg base down to 150 kg (750kg to 450kg). 
- Increased the shield capacity of centurion mechs.
- With the introduction of Biotech and buildable mechs, the inventory size of large mechs in the hands of the player neared unreasonably high amounts which made certain pawns/entities that handled the duty of carrying things in caravans pretty much obsolete. This coupled with the fact that mech loadouts received a reduction in size, results in a need for reducing the mass capacity of large mechs which used to be just free inventory space ripe for filling up.
- Centurions have very little going for them aside from the shield and the turret on their back, increased their shield capacity to make them more viable and …
=> Mechanoid tweaks

Defs/Ammo/Shell/762x385mmRCannon.xml, Defs/Ammo/Shell/762x539mmR.xml
- 762x539mmR texPath updated. Was referencing deleted textures
- 762x385mmRCannon GraphicClass updated to Graphic_StackCount as was giving errors when GraphicClass set to Graphic_Single. 
Red errors on launch from missing textures and incorrect GraphicClass
=> Fix for 762x385mmRCannon and 762x539mmR

Defs/Ammo/Flamethrower.xml, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Bursting.cs
- Adds the check introduced in #2640 to Bursting projectile class, which got left out because it overrides the `Launch` method.
- Removes shadows from flame stream of flamethrowers, which uses that Bursting class. Doesn't make sense for a ball of flame to cast a shadow.
=> Bursting projectiles shadow

Patches/ESCP - Spriggans/ESCP_Spriggan_Scenario.xml
- Fix a copy-paste error that pointed the FindMod at CE instead of the actual mod.
=> Fix Typo in ESCP - Spriggans Patch

Patches/Alpha Vehicle/Alpha_Vehicle.xml, Patches/Alpha Vehicle/Alpha_Vehicle_Hwacha.xml, Patches/Alpha Vehicle/Alpha_Vehicle_WarChariot.xml, SupportedThirdPartyMods.md
- Compatibility patch for Alpha Vehicle Neolithic
- Armor of vehicles based on research of thickness of wood used and the CE stats for wood.
- Hwacha ammo capacity based on amount of total arrows the Vanilla can shoot per reload.
- Rocket arrows based on a 50g blackpowder charge for the explosive. Which should be equal to 21.5g of TNT
- Hwacha spread/sway/recoil to give it the area suppression that was used for historically.
=> Alpha Vehicle Neolithic patch

Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
- When repairing armor from `CompArmorDurability`, the target will wait along with the pawn repairing the armor
- `WithProgressBarToilDelay` was removed as `WaitWith` has an argument `useProgressBar`, which does exactly the same thing
- Pawns walking away while having their armor repaired and then still getting the effect of repairing from a distance is rather unrealistic
=> Repairing armor from CompArmorDurability forces the target to wait in place

Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs
- Rocketswarms now able to shell world targets... Again.
- Can't remeber if there was if-statement that I changed.
=> Global targeting for rocketswarm-like systems fix

Patches/pphhyy Expanded Scythers/MechBodies_CE.xml, Patches/pphhyy Expanded Scythers/MechKind_CE.xml, SupportedThirdPartyMods.md
- Patch for [phynilla Expanded Mech Scythers]
Patch 5 new kinds of scythers, each with their own charateristics and roles
Mainly for player side use (might be a bit too powerful), also possible to spawn on enemy side. I've tried to balance it while 
keeping their intended roles.
**the mechs use exact same Bodies def as vanilla mechanoid walkers, but the author still make a new one for some reason
=> phynilla Expanded Mech Scyther patch

Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Bunsen.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Highwayman.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Roadkill.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Bulldog.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Tango.xml, Source/CombatExtended/CombatExtended/Defs/AmmoSetDef.cs
added the infomation of ammo and projectile into the ammoset's info tab.
I figured I could display the calibres used by a vehicle via vanilla hyperlinks, it turned out fine but the ammoset info tab doesn't provide anything meaningful other than a name. So I made it happen.
- a handful of people every day coming and asking about "what ammo that vehicle uses"
=> Add calibre info to ammosetdef

Defs/Effects/Flecks.xml, Defs/ThingDefs_Misc/Weapons_Turrets.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Defs/GunDrawExtension.cs, Source/CombatExtended/CombatExtended/Things/Fleck_Casing.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
Make casing mote originate from where gun draw center is. Works perfect for AR, LMG, pistol and shotguns, sub-optimal but acceptable on SMG, rifle and sniper rifle, a bit hilarous on minigun
Also fixed casing velocity on handheld weapons when firing towards right side
Added casing offset to gundrawextension
Made casing mote life span randomize from 0.5 to 1.5, because the original looked awful when not firing east/west.
before:
after:
We CE people don't pull ammo out of our butts like vanilla does, so casings shouldn't either.
Shit hot brass.
-I actually hated the implementation but I couldn't come up with a better one, unless I copy a good chunk of code from pawnrenderer. Probably need a look from a coder better than me.
-Another modextension for angle offset? …
=> Casing mote center to gun draw center

Source/CombatExtended/CombatExtended/BoundsInjector.cs
- Graphics_Random may return different textures, so the boundaries may change from time to time (as result desync in MP possible)
- Just calculate average of all sub-textures.
=> Average of Graphics_Collection

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- `ProjectileCE:StartingTicksToImpact` won't call `ImpactSomething` when MP is active.
- `StartingTicksToImpact` getter can get called outside of ticking (during drawing), causing the `ImpactSomething` method to get called. In MP, `ImpactSomething` will cause issues when called during drawing as the call won't be called at the same time across all players, causing issues.
=> Fixed desync with multiplayer 0-tick impact projectiles

Source/CombatExtended/Compatibility/Multiplayer.cs, Source/CombatExtended/Harmony/Harmony_Pawn_DraftController.cs, Source/MultiplayerCompat/MultiplayerCompat/MultiplayerCompat.cs
- Added callback for `MP.IsExecutingSyncCommand`
- Cancel execution of postfix to `Pawn_DraftController.FireAtWill` in Multiplayer outside of synced commands (delay the call)
- The callback is required for the second part of the PR
- `FireAtWill` is a synced method in Multiplayer, which causes the execution to be delayed until synchronized. However, this does not affect prefixes, postfixes, and finalizer thus the postfix would run and cause a desync in Multiplayer. The postfix will still run after the method is synchronized, just won't run when the original method was cancelled by Multiplayer.
- Instead of …
=> Fix Multiplayer issue with Fire at Will gizmo

Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
Respects generic ammo, and no ammo modes.
Vehicle patches should no longer manually assign ammos, they are auto assigned from the ammoset if one is specified and ammo is enabled.
The previous approach duplicated information, allowing data to be out of sync.  It also made generic ammo support difficult.
Manually specify both
=> Dynamically add ammo items to vehicle ammo ThingFilter

Source/CombatExtended/CombatExtended/CE_DebugTooltipHelper.cs
CE_DebugTooltipHelper iterates all methods in all classes during its initialization.  The causes type not found errors with mods that expect to lazy-load their methods when optional mods are missing.  This should suppress those errors.  
Explicitly register the methods which have CE_DebugTooltip somewhere.  This is more robust, as forcing methods to load that were lazy loaded might cause side effects.  But it would require a significant redesign of the debug tooltip subsystem.
=> Add try/catch around iterating all methods

Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
If a vehicle doesn't have a CE Def Mod Extension, but properly defines its ammo and default projectile, it shouldn't break the ammo injector.
=> Null check def mod extension in ammo injector

Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
Human pawns with only minimal natural armor have 500 pts of natural armor durability.  So if the natural armor max is 500 pts, don't show it.
Players get confused that basic humanoid pawns, and small animals, have "natural armor".  This is a trivial amount that doesn't actually matter, so displaying it just confuses players.  
Never show it
Always show it.
Show only a percentage.
Show it only in dev mode.
=> Hide armor durability from pawns with default armor amount

Source/CombatExtended/CombatExtended/AmmoUtility.cs
- Adds a line that shows how much damage each fragment does to ammo inspection menu.
Example:
=> Add damage of fragments to ammo description

Source/CombatExtended/CombatExtended/Comps/CompAmmoGiver.cs, Source/CombatExtended/CombatExtended/Comps/CompAmmosetSwitcher.cs, Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/Core/CompMechAmmo.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCount.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/UI/Dialog_SetMagCountBatched.cs, Source/CombatExtended/Harmony/Harmony_Pawn_DraftController.cs
When using the makefile to rebuild the project, it references 0Multiplayer.dll left over from the previous build.
This creates an ambiguous match between `Multiplayer`, the class inside `CombatExtended.Compatibility` and `Multiplayer` the namespace from the dll.
Rename the class.
=> Explicitly reference Compatibility.Multiplayer instead of just Multiplayer

Patches/Kit's VFE Weapons/Ammo/Ammo_KitPlasma.xml, Patches/Kit's VFE Weapons/DamageDefs/DamageDefs_Vikings.xml, Patches/Kit's VFE Weapons/ThingDefs_Misc/Weapons.xml
- added space to VFE mod listing
Added Space to kit's VFE weapon's continued since original mod about.xml contained a space, removing it disabled the patch
Kit's modmetadeta contains a space
the patch doesnt
no alternatives unless you ask the mod author to change the name
DO NOT REMOVE THE SPACE IN THE MOD NAME, IT IS INTENDED
=> Fixed Kit's VFE Weapons CE Patch Typo

Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Badger.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Marshal.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Paladin.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Udar.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Vehicles_Unarmed.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Bulldog.xml, SupportedThirdPartyMods.md
- Adds a patch for VVE - T3.
- The Udar works in direct-fire, but currently can't target LOS. Will probably need re-visited when VF eventually supports that.
- Adjusts some armor values for VVE.
=> Patch Vanilla Vehicles Expanded - Tier 3

Patches/Vulpine Pack/Race_Frij.xml
add missing pawncomp and Suppressable comp to a race patch
- Buffed regular smoke grenades as they are rarely utilized …
=> Update Vulpine pack patch

Defs/Ammo/GENERIC/Shell_Cannon.xml, Defs/Ammo/Shell/100x695mmR.xml, Defs/Ammo/Shell/105x607mmR.xml, Defs/Ammo/Shell/105x617mmR.xml, Defs/Ammo/Shell/120mmCannon.xml, Defs/Ammo/Shell/28cmSpgr.xml, Defs/Ammo/Shell/37x223mmR.xml, Defs/Ammo/Shell/40x365mmBofors.xml, Defs/Ammo/Shell/50mmType89Mortar.xml, Defs/Ammo/Shell/57x307mmR.xml, Defs/Ammo/Shell/57x483mmBofors.xml, Defs/Ammo/Shell/60mmMortar.xml, Defs/Ammo/Shell/75x350mmR.xml, Defs/Ammo/Shell/762x385mmRCannon.xml, Defs/Ammo/Shell/762x539mmR.xml, Defs/Ammo/Shell/90mmCannon.xml
- Added generic shell ammo types (light and heavy) based on 40mm Bofors and 90mm shells, the more commonly used and complete in terms of ammo types among different shells.
- With the emergence of vehicles and high caliber shells finally getting used more commonly, and with the apparent implementation of generic ammo compatibility for vehicles, it's was time generic shells were added to the mod.
- The ammo was added in two (Light and Heavy) variants due to ammo type differences, caliber differences/gaps and also crafting costs. Shells were grouped into each category based on their ammo types and size.
- Leave shells without a generic ammo type.
- Indirect-fire ammo types being mortar and howitzer shells (direct-fire howitzer shells too, generic shells don't have incendiary and smoke shell …
=> Generic cannon shell ammo

Languages/English/Keyed/ModMenu.xml
- Add keys for recoil options in the mod menu.
- Fix a typo.
- Already set up in the code for the translations, just need them added.
- Leave the setting untranslated, for some reason.
=> Mod Menu Keys

Patches/Pulsefire Turret/PulsefireTurret_CombatExtendedPatch.xml
Fixed Erroneous aiming, changing from suppression to aimed turret shots would disable the turrets entirely. Set default to aimed shot and added fill percent
- [Y] Compiles without warnings
- [Y] Game runs without errors
- [Y] (For compatibility patches) ...with and without patched mod loaded
- [Y] Playtested a colony (specify how long)
=> Pulsefire patch cleanup

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Inverted intersection check
- Fixed hit position
- Shield's doesn't work compeletly 
- Hit position can be incorrect
=> Interceptor comp fix

Source/CombatExtended/Compatibility/VanillaPsycastExpanded.cs
- Fixed outgoing projectiles being intercepted
- Removed Y from calculation to avoid incorrect projectile bypass
- Removed useless variable
- One check was missing since blocker registry changes.
- parameter "from" can be used instead of "origin" of projectile, but for some reason it wont work
=> Vpe shield outgoing interception

Defs/Ammo/Advanced/164x284mmDemoShell.xml, Defs/Ammo/Generic/Mech.xml, Defs/Ammo/Lasers/BaseLaserProjectiles.xml, Defs/HediffDefs/Hediffs_CE.xml, Patches/Halo - UNSC Armoury/Weapons_Laser.xml, Patches/Vanilla Factions Expanded - Deserters/RangedSpacer.xml, Patches/Vanilla Factions Expanded - Empire/Ammo/FletcherRifleRound.xml, Patches/Warcaskets - Adeptus Astartes/Ammo/MeltaGun.xml
- Remove ModExtension for ProjectileFX from a few beam projectiles, as they currently cause errors.
- Fix issue with the 164x284mm Demo shell in Generic Ammo mode caused by the generic ammoset lacking the correct ammo type. Added an appropriate new ammo item for that purpose.
- Fix Gas Mask hediff being "curable" by mech healer serum. Closes #2865.
- The ProjectileFX errors can probably eventually be fixed, but the offending XML should be removed for the time being, as it'll likely need reformatted anyway, given the new ProjectileFX system.
=> Various XML Fixes

Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
When changing the ammunition allowed in VF vehicles, just replace the ammunition thing filter, and have it resolve its references.  
Without this, vehicles not supplying an empty `<ammunition/>` node in their turret def would break.  Also, vehicles with only 1 type of ammo would behave oddly when scheduling reload jobs.
Only add a new node, and try to re-run resolve references.
=> always replace vehicle ammunition ThingFilter

Patches/Dark Ages - Medieval Tools/MeleeMedieval.xml, SupportedThirdPartyMods.md
- Patch Dark Ages: Medieval Tools
- Where possible, copy-paste patches/stats from existing tools.
- Broom is a slightly weaker quarterstaff (owing to the inconvenience of having a broom on one end.)
- Could use different stats.
=> Patch Dark Ages: Medieval Tools

Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Paladin.xml
- Fixed Paladin's `chargePerAmmoCount` to consume one ammo per shot.
=> Fix paladin reloading

Patches/Vanilla Factions Expanded - Tribals/Apparel_Tribals.xml, Patches/Vanilla Factions Expanded - Tribals/ThingDefs_WeaponsMelee.xml, Patches/Vanilla Factions Expanded - Tribals/ThingDefs_WeaponsRanged.xml, Patches/Vanilla Weapons Expanded - Tribal/Melee_Neolithic.xml, SupportedThirdPartyMods.md
- Patch for Vanilla Factions Expanded - Tribals
- Update armor penetration values in Vanilla Weapons Expanded - Tribal that were using the old armor penetration node.
- New tribal gear is balanced on par with existing tribalwear and simple weapons.
=> Patch Vanilla Factions Expanded - Tribals

Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/Compatibility/VanillaPsycastExpanded.cs
- Inverted crossing check
- Moved additional collision check after CanCollideWith check (can help to avoid incorrect early interception)
- Projectiles intercepted instantly:
If p1 and p2 outside of shield but line between them intersect shield, then method returns false.
=> Intersection improvment

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
- Updated loadouts to respect the pawn's current food restrictions
- Should prevent pawns from picking up food that they cannot eat
- Use `pawn.WillEat` instead, this also checks for venerated animal meat or royal restrictions
- Not check for restrictions at all
=> Loadouts meal fix

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Adds a radius highlight when aiming area of effect weapons. I didn't write this code, it was all in vanilla's `Verb_LaunchProjectile`
- Easier to see how big the explosion will be
=> Add explosion radius highlight

Patches/Vanilla Races Expanded - Archon/Apparel_Various.xml, Patches/Vanilla Races Expanded - Archon/Archon_Misc.xml, Patches/Vanilla Races Expanded - Archon/Melee_Archon.xml, SupportedThirdPartyMods.md
- Add patch for VRE - Archon
**Note:** The Archon shields require #2869 to intercept projectiles properly. 
- Archon armor has slightly less protection than cataphract armor, but no leg or foot protection. It is lighter and less bulky (owing to superior archotech), making it better suited for melee fighting.
- Archoblade is plasma sword without stabbing attack and very high Sharp AP, as the weapon is described as "phasing through" armor.
- Could change some armor values.
=> Patch Vanilla Races Expanded - Archon

Defs/ThingDefs_Items/Items_Unfinished.xml
Remove stuff in unfinished arrow
So I was told that while making poison arrow (or whatever neolithic ammo with a non-stuff in its ingredients) sometimes an error pops out when that non-stuff was used for the stuff of unfinished ammo. So I got rid of it
Suffer.
=> No stuff4 unfinished arrow

Patches/Warhammer 40.000 - Imperium Materials/GrimForge_CE_Resources.xml, SupportedThirdPartyMods.md
- Migrate patch from Warhammer 40.000 - Imperium Materials into CE's side.
- Rebalanced some materials from their version of the patch.
- Add some Warhammer mods to the Supported Mod List that were somehow missed, despite their patches being present.
- The materials have been balanced to be fairly in-line with their scaling relative to vanilla materials (chiefly plasteel, in this case) while preserving their stated role as an extremely high-tier material as an answer to threats from intentionally OP mods like VOID.
=> Patch Warhammer 40.000 - Imperium Materials

Patches/Orassans/Ammo/MissileAmmo.xml, Patches/Orassans/ThingDefs_Misc/Apparel_Various.xml
it had ammo texture pointing to the old path,
- Buffed regular smoke grenades as they are rarely utilized and to …
=> Orassans ammo fix

Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/CollisionVertical.cs, Source/CombatExtended/CombatExtended/Comps/CompTacticalManager.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Pawns cache their collision heights rather than calculating multiple times per tick
Required for smarter height management.
Improves performance
=> Cache pawn heights

Building.md
- Windows batchfile builder provided by @Draconomial is linked from Building.md
- Closes #2902 
The batch file runs with full user permissions, so needs to be under at least as strict branch protection rules as any of our other code.  
It is in its own repo so further changes from Draconomial can easily be pulled, and because it is GPL3, so can't sit in this repo.  Since it is supposed to help automate checking this repo out and building it, from the top level `Mods` directory, it makes more sense to have it in its own repo anyway.
Have people manually call `dotnet build` on the solution file.   …
=> Add link and description for windows batch builder

Patches/Medicine Supplements (Continued)/Items_Bandages.xml, SupportedThirdPartyMods.md
Patch Medical Supplement's bandages bulk from 1.0 to 0.1 per piece
Bandages are supposed to be a weaker, lighter alternative to a full medicine kit. The bulk stat didn't reflect this at all without the patch.
=> Patch Medical Supplement's bandage bulk stat

Source/CombatExtended/Harmony/Harmony_StunHandler.cs
- EMP damages nolonger stun turrets that doesn't require electricity and need to be manned.
unmanned and unpowered turrets are considered self-powered and will still be stunned.
-  Why on earth should emp stun a machinegun on a tripod?
- Suffer.
=> EMP don't stun non-powered and manned turrets

Patches/Thrumbo Plushie/ThrumboPlushie.xml, SupportedThirdPartyMods.md
Create ThrumboPlushie item patch.
- Buffed regular smoke grenades as they are rarely utilized and to justify …
=> Patch for Thrumbo Plushie

Defs/Stats/Stats_NightVision.xml, Patches/Vanilla Races Expanded - Fungoid/Apparel_Various.xml, Patches/Vanilla Races Expanded - Fungoid/Fungoid_Hediffs_BodyParts.xml, SupportedThirdPartyMods.md
patch fungoid melee tools in xml.
- Buffed regular smoke grenades as they are rarely utilized and to justify …
=> VRE Fungoid patch

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Incorrect adjacent cells when shoting some directions (south and west).
Adjacent cells when shoting/throwing from south to north (red = projectile pos, blue checked cell):
Adjacent cells when shoting/throwing from north to south:
For some reason GenAdj.CellsAdjacentCardinal() works incorrect for rot4.South and rot4.West
Grenades now hit high pawns (centipede and other) correctly from each direction
=> Incorrect adjacent cells collect

Defs/Ammo/Rifle/5x100mmCaseless.xml, Patches/Rimsenal - Spacer Faction Pack/Apparel_Spacer_CE.xml, Patches/Rimsenal - Spacer Faction Pack/Explosives_Smart_CE.xml, Patches/Rimsenal - Spacer Faction Pack/Mechs_Body_CE.xml, Patches/Rimsenal - Spacer Faction Pack/Mechs_Smart_CE.xml, Patches/Rimsenal - Spacer Faction Pack/Weapons_Smart_CE.xml, SupportedThirdPartyMods.md
Patches for new smartguns, mechs and the two apparels.
Saw a while ago that some people wanted the super-industrial ammo as the primary ammo type for the smart guns, so given these are all techncially new guns, they now mostly all just use either 277 or 5.7 as their ammo. Lance uses sniper like stats and thankfully isn't craftable.
Smart weapons are set up with general -25% sway and spread, and half recoil.
Could change for more varied ammo strength/caliber
=> Rimsenal Spacer Patch

Biotech/Patches/GeneDefs/GeneDefs_Misc.xml, Patches/Alpha Genes/GeneDefs/GeneDefs_Archite.xml, Patches/Big and Small/Big and Small Genes/Genes/GeneDefs_Temperature.xml
Adds patch to include PrometheumFlame and Flame_Secondary to the effects of fire related genes (Biotech, Big and Small Genes and Alpha Genes)
=> Patch fire related genes

Defs/Misc/TipSetDefs/Tips.xml, Defs/Stats/Stats_NightVision.xml, Patches/Apex - Rimworld Legends/ApexRimworldLegends_Weapons_AssaultRifles.xml, Patches/Biomes Caverns/ThingDefs_Races/CE_WoollySpider.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Patches/Vanilla Races Expanded - Archon/Apparel_Various.xml
Another grab-bag PR of tweaks and changes.
1. Fix typo in Biomes! Caverns patch.
2. Adjust Night Vision quality factors.
3. Change HCB aim mode from Snapshot to SupressFire.
4. Change Apex Legends mech rifle caliber from 5x35 to 8x40. (#2888)
Closes #2914
Closes #2924
1. Typo in the patch makes it fail. Possibly caused by a minor mod update.
2. Existing scaling for NV quality factors in unusual compared to other RW quality stats, as 1x is not the "normal". This makes it somewhat counter-intuitive, and makes NV perhaps weaker than it really needs to be. With the new scaling, NV is somewhat stronger, but still very rarely hits the 100% reduction even with advanced NV systems of masterwork quality.
3. In SuppressFire, losing LoS will prevent will not interrupt the warm-up. So, rather than …
=> Misc. Tweaks & Fixes

Patches/Alpha Vehicle/Alpha_Vehicle_Hwacha.xml, Patches/Alpha Vehicle/Alpha_Vehicle_WarChariot.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Badger.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Marshal.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Paladin.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Bunsen.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Highwayman.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Roadkill.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Bulldog.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Tango.xml, Patches/Vehicle Framework Expanded - Classic Mechs/Mech_BattleCannon.xml, Patches/Vehicle Framework Expanded - Classic Mechs/Mech_GatlingCannon.xml, Patches/Vehicle Framework Expanded - Classic Mechs/Mech_MachineGun.xml, Patches/Vehicle Framework Expanded - Classic Mechs/Mech_MissileLauncher.xml
- Remove operations changing the state of `genericAmmo` from vehicle patches.
- The swapping of generic/non-generic ammo is already appropriately handled in the assembly. The only thing including the operation does it prevent the vehicle from being able to load its generic ammo type when using No Ammo Mode, which is not desirable.
=> Fix VF Vehicles in No Ammo Mode

Patches/Alpha Vehicle/Alpha_Vehicle_Hwacha.xml, Patches/Alpha Vehicle/Alpha_Vehicle_WarChariot.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Marshal.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Paladin.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Bunsen.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Roadkill.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Bulldog.xml, Patches/Vehicle Framework Expanded - Classic Mechs/Mech_BattleCannon.xml, Patches/Vehicle Framework Expanded - Classic Mechs/Mech_MissileLauncher.xml, Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
Charge per ammo is set to 1 automatically for all VF turrets if ammo is enabled.
This was done in XML for some vehicles, but doing it in XML opens the possibility of missing some, and interferes with no-ammo mode.
=> Set chargePerAmmoCount to 1 if ammo enabled

Source/CombatExtended/CombatExtended/Comps/BipodComp.cs
- Automatic bipod setup will no longer trigger if the pawn is carrying another pawn, preventing them from dropping them every time they stop moving.
- Manually put away weapons whenever you need a pawn to carry someone.
=> Fix bipodded weapons causing pawns to drop carried pawns

Source/CombatExtended/CombatExtended/Defs/AmmoSetDef.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_AmmoConsumedPerShotCount.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootMortarCE.cs, Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
- A new field is added to ammoSetDefs to support modifying ammo used per shot across entire ammosets.  Mostly matters for vehicles.
- The existing per-verb property is left unmodified, but the effects multiply
- Vehicles do not have ammosets, so moving the value to the ammoset is  the simplest way to expose the data for VF use.  
- Multi-verb frameworks might want to set different values for different verbs, so removing the value from the verbs is probably a poor choice.
- Explicitly add a separate mult value for vehicles to use
- Disable the per-verb value
=> Add ammoConsumedPerShot to ammosetdefs

Defs/Ammo/Shell/81mmMortar.xml, Defs/Effects/Motes.xml, Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_ThingDefOf.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_BunkerBuster.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs
Height-fused projectile that uses aimHeightOffset as which height it should detonate. Intended for fly overhead projectiles. Flying above aimHeightOffset will arm the shell, after which flying below aimHeightOffset will detonate the shell.
Includes two air burst mortar shells for demonstration and testing purposes, may be removed later.
HF shell detonate at 0.6 height (somewhere near human body I think?) and spread frags horizontally.
HiF shell detonate at 6 height and spread frags in a downward facing cone.
Added detonateMoteDef detonateFleckDef detonateEffectsScaleOverride in ProjectilePropertiesCE, which will be played at projectile's drawpos when hit. Scale will be projectile's explosion diameter, with optional override.
Changed some occurances of compfragments to accept multiple of …
=> height fuse

Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
A null or empty check in VF compat, and an error message if null check occured
So that a mistake in vehicle ammoset patch doesn't break the entire ammo injector, and patcher can know what is going wrong
Suffer.
=> List Null check in VF compat ammo injector

Patches/Divine Order/PawnKindDefs/Divine_Order_CE_Pawnkinds.xml, Patches/Divine Order/Scenario/DivineOrder_CE_Scenario_Patch.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Apparel.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Armor.xml, Patches/Divine Order/ThingDef_Misc/Divine_Order_CE_Shield.xml, Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Melee.xml, Patches/Divine Order/ThingDef_Misc/Weapons/Divine_Order_CE_Ranged.xml, Patches/Divine Order/TraderDefs/Divine_Order_CE_Traders.xml
- Patch traders to stock CE cannonballs, miniballs, and pre-industrial tagged ammo
- Added crossbow bolts to Scenario
- Patched new weapon
- Patched new apparels
- Fixed duplicate xml errors due to updates in Divine Order
- Replaced shield def since CE replaces the VE shield comps.
- Patched PawnkindDef to utilize shield without VE
- Hand crossbow given crossbow ammo set, but at vastly reduced ranged. 
- Patching hand crossbow to realistic values
- Would make weapon functionally useless
- Have to add new ammo set and projectiles
- Breaks mods intent
=> Update Divine Order Patch

Source/CombatExtended/CombatExtended/CE_Utility.cs
Map null check for MakeIconOverlay
Occassional red letter from trying to spawn suppression mote on not spawned pawn
Suffer.
=> Null check MakeIconOverlay

Defs/ThingDefs_Misc/Filth_Casings.xml
- No functional changes. Simply consolidates the filth defs a bit, creating a unified parent (`BaseFilth_CE`) to reduce some redundancy since, aside from label and sprites, the filth defs have the same stats.
- Housekeeping and general good practice.
- Could leave it as-is.
=> Casing Filth Housekeeping

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
Damage to armor when armor amount and pen amount are both 0 no longer instagibbs hard armor.  
- Always ignore armor damage for fire
- Pick an arbitrary amount of damage to do to armor
- Let armor get erased
=> Specially handle fire damage based on apparel flammability

Defs/Ammo/Flamethrower.xml, Defs/Effects/Flecks.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Bunsen.xml
Redone flamethrower projectile graphic using rocket trail function
So that flamethrowers don't comically throw literal balls of fire, instead fires a trail of burning liquid
"firethrower"
=> better flamethrower graphics

Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs
- Simplified the pickup behavior for mag-less weapons to pick up the entire available stack. Pickups for weapons with magazines remain unchanged.
- Previous behavior led to potential pickup loops when pawns' available bulk was still in range of the pickup check as bows don't check for having <2 mags already picked up.
- The resulting small stacks of ammo sometimes also ended up below the minimun bulk check for the pickup job, leading to more undesireable behavior.
- Ideally bows and other mag-less weapons should get a mag size override added to them and this should be kept as the last fallback.
- Add a more robust check for ammo already picked up for mag-less weapons.
- Rely exclusively on mag size override for mag-less weapons.
=> Simplify magless ammo pickup fallback

Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/Harmony/Harmony_ThingDef.cs
Added a def.GetLastModExtension<T> function for returning last modextension for future use
A patch in def postload will remove every occurance of partialarmorext except the last. so that partialarmorext in parent defs won't intefere
so that the partialarmorext in base mechanoid won't prevent editing partial armor.
Suffer.
=> make last partialarmorext apply instead of first

About/About.xml, Patches/Alpha Memes/StyleCategoryDefs/StyleCategoryDefs.xml, Patches/Rimsenal - Spacer Faction Pack/Explosives_Smart_CE.xml, Patches/Rimsenal Collection/Core/Weapons_Explosives.xml, Patches/Rimsenal Collection/Core/Weapons_ExplosivesRecipeBase.xml, Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Buildings/TurretGatlingGun.xml
A handful of small fixes for the 5.6 release.
- Load VFE - Tribals before CE. It modifies some of the VWE - Tribal weapons we also modify, causing the patch to fail.
- Resolve duplicate explosive recipe base for the Rimsenal series--easiest to just load it in a separate file.
- Fix a duplicate `costList` for the VWE - Settlers Gatling gun.
- Alpha Memes: Patch out styles for weapons CE removes and make AM load before CE to prevent errors.
=> 5.6 final fixes

Languages/English/Keyed/LongEventHandler.xml, Languages/Russian/Keyed/LongEventHandler.xml
- Added a missing loc string to the `CE_LongEvent_CompatibilityPatches` event during startup, along with a russian version.
- The russian string may not be using the correct technical terms, so could be replaced.
=> Add missing startup loc string

Patches/All-Tech Melee/Weapons_ATM_Industrial.xml, Patches/All-Tech Melee/Weapons_ATM_Spacer.xml, Patches/All-Tech Melee/Weapons_ATM_Tribal.xml, Patches/All-Tech Melee/Weapons_ATM_Ultratech.xml, SupportedThirdPartyMods.md
Describe new functionality added by your code, e.g..
- Compatibility for All-Tech Melee
Added compatibility for All-Tech Melee
Mod: [https://steamcommunity.com/sharedfiles/filedetails/?id=2789794530](All-Tech Melee)
It was not compatible and we lack good simple melee weapon mods.
no alternatives considered
=> Added support for All-Tech melee

Patches/Rambo Weapons Pack/RamboWeaponsPack_amrifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_assaultrifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_battlerifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_heavy.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_machineguns.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_pistols.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_rifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_shotguns.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_sniperrifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_submachineguns.xml
None
- Added weapontags for bipods to Rambo Weapons Pack 
- Added weapontags for one handed weapons to Rambo Weapons Pack
- Added weapontags for Sidearm and machinegunner flags to Rambo Weapons Pack
- Added weapontags for AI flags to Rambo Weapons Pack
N/A
Bring Rambo Weapons Pack up to date with more modern iterations of CE, taking advantage of new mechanics like bipods as well as flagging one handed weapons, pistols and machineguns correctly for CE to take advantage of. 
non others considered
- Tested with faction raids during in dev quick start instance (both with and without Rambo Weapons Pack enabled) as well as ensuring weapon functionality works as intended with a sample selection of weapons added by RWP.
=> Rambo weapons pack - weapontag modernisation pass

Source/CombatExtended/CombatExtended/ArmorUtilityCE.cs
If apparel offers 0 protection against sharp, blunt, or fire, don't warn when the pen system can't handle it gracefully.
Avoids log spam for nv goggles and the like.
implement our own warnOnce like function to not drop red errors in the log
=> Handle apparel that isn't armor more gracefully

About/About.xml, Patches/K4G Empires of Old - Core/Apparel.xml, Patches/K4G Empires of Old - Core/Apparel_Royalty.xml, Patches/K4G Empires of Old - Core/WeaponsMelee.xml, Patches/K4G Empires of Old - Core/WeaponsRanged.xml, Patches/K4G Empires of Old - Factions/PawnKinds_Dynasty.xml, Patches/K4G Empires of Old - Factions/PawnKinds_Guild.xml, Patches/K4G Empires of Old - Factions/PawnKinds_Legion.xml, Patches/K4G Empires of Old - Factions/PawnKinds_Sultanate.xml, Patches/K4G Empires of Old - Factions/TraderKinds_Sultanate.xml, SupportedThirdPartyMods.md
- Patch new apparel, weapons, and factions from the [K4G] Kingdoms of Old mod series.
- Wherever possible, used patches from existing equipment as templates. Should be reasonably balanced. 
- Patch factions added by the various K4G submods, adding ammo to pawnkinds and adjusting the Sultanate traders. 
Many of the items were already patched in other places, or were comparable enough to patch with a few stat tweaks. Tried to stick reasonably close to vanilla balance.
Switched the 'bolter' from basically a very crude dart gun into a crude 9mm pistol, since the single, crappy weapon wasn't really worth making a whole new ammoset for.
Have to load the Sultanate faction before CE, because it otherwise adds a duplicate `weaponTag` field to the vanilla Bolt Action Rifle.
- Could take a different …
=> Patch [K4G] Empires of Old - Core & Factions

Patches/VRE Android Factions/Factions_Misc.xml, SupportedThirdPartyMods.md
- Patched the trader from the aforementioned mod.
- The trader is loosely based on the outlander exotics trader, with slightly different stock.
- The faction itself is completely based on normal outlander and pirate factions with no new pawnKinds.
=> VRE Android Factions patch

Source/CombatExtended/CombatExtended/Comps/CompFragments.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Flare.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs
- Projectile Height returned a cached value.  Projectile next position relied on projectile height.  This lead to projectile height being frozen.  
- Deprecating ProjectileCE.Height makes it clear that ProjectileCE.ExactPosition is the sole authority on CE-related projectile positioning.  Also it removes a virtual lookup so will have marginally better performance.
- By storing the next "frame" directly into ExactPosition and then pulling a local copy inside Tick, subclasses of ProjectileCE can override how ExactPosition gets updated entirely, without forcing updating ExactPosition into a virtual call in the trivial case.
- Explicitly initializing ExactPosition and LastExactPosition during launch removes a messy and moderately expensive calculation and removes the need for a nullable, …
=> 5.6 hotfix for broken projectiles

Patches/Vanilla Factions Expanded - Pirates Unofficial Addon Warcasket Melee Armory/VFE_P_UA_WMA_Weapons.xml, SupportedThirdPartyMods.md
Using the knowledge I gained from patching the Outer Rim mods, I've added CE support for the Continued/1.4 version of the VFE Pirates Unofficial Addon Melee Armory, which adds 9 new warcasket melee weapons, +1 with VFE:Insectoids, +1 with VFE:Vikings, and +3 with VFE:Mechanoids, for a total of 14 new warcasket melees with all mods.
Mostly to close my own patch request I made a year and a half ago.
- Closes #2002 
The new warcasket weapons were roughly statted by comparing existing warcasket melees to normal-quality steel basic weapons (knife / warcasket combat knife, longsword / warcasket broadsword) and going from there, and/or basing them off other added warcasket weapons like the gravity hammer.
The baton and mecha baton have a small amount of added EMP/ion damage for flavour, though …
=> VFE Pirates Unofficial Addon Melee Armory

Patches/NewRatkinPlus/Bodies/Bodies_Ratkin.xml, Patches/NewRatkinPlus/ThingDef_Misc/Ratkin_Apparel.xml
I try to add defense value on RK_HeavyShield_big (Ratkin Bigshields) which based on normal RK_HeavyShield and CE default Shield modifiers 
If the better value exist Please comment 
I'm noob to GitHub project pull requests. So if this is not good work Please announce it. 
* simple XML changes 
* continued with existing changes 
* I'm can't understand of this. Is this has issue? 
* works with equip and RHA defense modifer works
=> ADD RK_HeavyShield_Big modifiers

Defs/Ammo/Lasers/BaseLaserProjectiles.xml, Defs/Ammo/Modded/Warhammer 40k/LasGun.xml, Defs/Ammo/Modded/Warhammer 40k/MeltaGun.xml, Defs/DamageDefs/Damages_LocalInjury.xml, Patches/Alpha Mechs/Mods/Biotech/ThingDef_Misc/Weapons.xml, Patches/Det's Energy Weapons/EnergyBoltAmmoSet.XML, Patches/Halo - UNSC Armoury/Weapons_Laser.xml, Patches/Halo UNSC Weapon Pack/UNSC_CE.xml, Patches/Rim Flood/Sentinal_Laser_CE.xml, Patches/Save Our Ship 2/Holograms_Projectiles.xml, Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Addon Weapons/Ammo_Laser.xml, Patches/Vanilla Genetics Expanded/Patch_Projectiles.xml, Patches/Vanilla Weapons Expanded - Frontier/Patch_HighRoller_AddonAmmo.xml, Patches/Vanilla Weapons Expanded - Laser/Ammo.xml, Patches/Vanilla XCOM weapons/Laser Weapons/Ammo.xml
Added new laser damageDef, applies burn damage while properly checking against sharp armor, applied to relevant projectiles in patches.
Reasoning:
it was stupid. most of the laser projectiles had assinged sharp penetration values which wouldn't have been put there if patcher didn't want them to get used.
Current setup with burn damagedef on most is literally broken OP.
Testing:
tested new damage def ingame, was working as it should
=> Laser damage type

Defs/ThingDefs_Misc/Weapons_Ranged.xml, Patches/Android Tiers Reforged/PawnkindDefs/PawnKinds_Android.xml, Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Patches/K4G Rimworld War 2/PawnKinds_Defs/PawnKinds_Japan.xml, Patches/MH Android Tiers/PawnkindDefs/PawnKinds_Android.xml, Patches/MH Military Tiers/PawnkindDefs/PawnKinds_Android.xml, Patches/Rim-Effect Asari and Reapers/PawnKindDefs/Asari_Pawns.xml, Patches/Rim-Effect Core/Alliance_Pawns.xml, Patches/The Corporation - Mort's Factions/Pawnkinds_Corporation.xml, Patches/Vanilla Factions Expanded - Empire/PawnKinds.xml, Patches/Xenohumans Expanded/Xenos_Pawns.xml, Royalty/Patches/PawnKindDefs_Royalty/PawnKinds_Royalty.xml
- Increased the budget for flare guns in pawn loadouts.
- https://discord.com/channels/278818534069501953/303988654492090370/1216773608479916052
tl;dr NPC pawns don't have enough budget to have flare guns when spawned.
- No flare guns on NPCs?
=> Flare gun loadout budget fixed

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml, Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Spacer.xml
- Added hand coverage to the trooper armor from "Vanilla Armour Expanded"
- All power armors cover the hands, so it was weird that this armor covered the whole body except the hands
- None
=> Adds hand coverage to trooper armor from "Vanilla Armour Expanded"

Patches/Rambo Weapons Pack/RamboWeaponsPack_amrifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_assaultrifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_battlerifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_heavy.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_machineguns.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_pistols.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_rifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_shotguns.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_sniperrifles.xml, Patches/Rambo Weapons Pack/RamboWeaponsPack_submachineguns.xml
N/A
Changed weapon recipies in RWP to include furniture of weapons created. (i.e chemfuel for polymer, wood for wood furniture) 
N/A
Changed recipes to include materials required for furniture and amounts of furniture (i.e, just handguard/stock, handguard and stock, action inserted into furniture body). 
- Aims to further differentiate between separate instances of weapons within this weapon pack. 
-  Providing slight incentivisation for using trying different weapons over a playthrough due to associated costs and material stocks.   
None 
=> Rambo Weapons Pack - Recipe change

Defs/Ammo/AmmoCategoryDefs/AmmoCategories_Advanced.xml, Defs/DamageDefs/Damages_LocalInjury.xml, Defs/HediffDefs/Hediffs_CE.xml, Patches/Outer Rim - Chiss Ascendancy/Outer_Rim_Chiss_Ascendancy_Ranged_Weapons.xml, Patches/Outer Rim - Core/Outer_Rim_Core_Ammo.xml, Patches/Outer Rim - Core/Outer_Rim_Core_Apparel.xml, Patches/Outer Rim - Core/Outer_Rim_Core_Armour.xml, Patches/Outer Rim - Core/Outer_Rim_Core_Grenades.xml, Patches/Outer Rim - Core/Outer_Rim_Core_Ranged_Weapons.xml, Patches/Outer Rim - Galactic Empire/Outer_Rim_Galactic_Empire_Apparel.xml, Patches/Outer Rim - Galactic Empire/Outer_Rim_Galactic_Empire_Ranged_Weapons.xml, Patches/Outer Rim - Galactic Republic/Outer_Rim_Galactic_Republic_Ranged_Weapons.xml, Patches/Outer Rim - Mandalore/Outer_Rim_Mandalorian_Apparel.xml, Patches/Outer Rim - Mandalore/Outer_Rim_Mandalorian_Ranged_Weapons.xml, Patches/Outer Rim - Old Republic/Outer_Rim_Old_Republic_Apparel.xml, Patches/Outer Rim - Old Republic/Outer_Rim_Old_Republic_Ranged_Weapons.xml, Patches/Outer Rim - Rebel Alliance/Outer_Rim_Rebel_Apparel.xml, Patches/Outer Rim - Rebel Alliance/Outer_Rim_Rebel_Ranged_Weapons.xml, Patches/Outer Rim - Seperatists/Outer_Rim_Seperatist_Ranged_Weapons.xml
Builds on the patches in #2997 to improve balance and clarify a few things;
- Improves sharp armour (slightly) and blunt armour (noticeably) for all armours.
- Adjusts armour coverage %s for various bodyparts to match spacer armours. Feet no longer have reduced armour (but necks do).
- Improves penetration of blaster rifle shots, and lethality of blaster sniper shots. Standard blaster sniper shots got a slight sharp pen reduction.
- Makes blaster rifles consume 2 ammo per shot and sniper rifles 3 ammo per shot. Ammo capacities have been buffed up. I've noticed this may be incorrectly displayed in weapon infocards but I suspect that's a CE code issue that's out of scope for the patches.
- Adds custom AmmoCategoryDefs for blaster bolts and the RPS-6 rockets, to note differences from Charge …
=> Outer Rim Patches Update/Balancing

Patches/Charge-Loading Lee-Enfield/ThingDefs_Weapons.xml, SupportedThirdPartyMods.md
- Patch for the Charge Enfield Mod
- Charge Enfield uses same base stats as the vanilla bolt action.
- Charge Lewis Gun uses the same base stats as the vanilla LMG. (We patch this as a Bren instead of a Lewis, but it's close enough for our purposes.)
Close #2882 
Weapons are essentially spacer versions of the regular guns, firing 8x35mm Charged instead of .303 British. The recoil has been adjusted accordingly.
Could use a different charge caliber or make a new one, I suppose.
=> Patch Charge Enfield Mod

Patches/Alpha Animals/ThingDefs_Misc/AlphaAnimals_CE_Patch_Resources_Leathers.xml, Patches/Core/ThingDefs_Items/Items_Resource_Stuff_Leather.xml, Patches/Vanilla Animals Expanded/AridShrubland_Resources.xml, Patches/Vanilla Animals Expanded/Desert_Resources.xml, Patches/Vanilla Animals Expanded/IceSheet_Resources.xml, Patches/Vanilla Animals Expanded/TropicalRainforest_Resources.xml, Patches/Vanilla Animals Expanded/Tundra_Resources.xml
- What it says on the tin, various animals leathers now provide armor consistent with their vanilla counterparts.
- The stats were all over the place and seemingly arbitrary with no cohesion between their vanilla counterpart. Top end of the leather types being heavy and rhino leather provide the most armor among the vanilla leathers now as intended by the game and the rest are scaled accordingly based on them.
- Leave Lizardskin the best leather in terms of armor and suffer.
=> Leather armor multiplier consistency check

Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Burya.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Goliath.xml, Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Vehicles_ExplosionsHotfixTier3.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Scytheman.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier1/Toad.xml, Patches/Vanilla Vehicles Expanded/VehicleDefs/Tier2/Vehicles_T2_Unarmed.xml, Patches/Vanilla Vehicles Expanded/Vehicles_Explosions_Fix.xml
- Patches for new Toad, Burya, Goliath, and Scytheman vehicles.
**- All have a turret that should fire indirectly, but vehicle turrets currently don't support our mortar system and can't fire without LOS.**
- Patch new Wisent truck. Unarmed military cargo truck, with armor just about sufficient to resist light small-arms fire.
Close #2930 
=> Update VVE Patch

Patches/Core/ThingDefs_Items/Items_Resource_Stuff_Leather.xml
- Swap a 'Replace' operation with an 'Add' instead.
- Patch operation failing.
Suffer.
=> Fix Vanilla Leather Patch

Source/CombatExtended/CombatExtended/Comps/CompFragments.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Bursting.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Flare.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs
Projectiles cache most values instead of recalculating on the fly.
Recalculating values on the fly is incredibly expensive, doing it multiple times per projectile per tick is incredibly expensive.
Tracking position and other properties lets other mods modify projectile trajectory on the fly.
Roll back position changes
=> Projectile position fix

Defs/Ammo/Projectiles_Fragments.xml, Defs/Ammo/Rifle/277Fury.xml
- Increased the spreadsheet velocities of frags from 400, 450 and 500 to a more realistic 600, 650 and 700m/s.
- Accuracy check on .277 Fury's muzzle velocity.
- The usual argument around frags being underperforming. According to here (https://en.wikipedia.org/wiki/F-1_grenade_(Russia)) grenade fragments fly at 700m/s away from the explosion which is pretty accurate to the velocity numbers shown in videos by Ballistic High Speed youtube channel. This increase helps both damage and the blunt AP of fragments considering fragment damage type already make the initial projectile to fragment and deal multiple smaller instances of damage.
=> Frags adjusted and minor housekeeping

Patches/Vanilla Factions Expanded - Settlers/ThingDefs_Buildings/TurretGatlingGun.xml, Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs, Source/CombatExtended/Compatibility/BlockerRegistry.cs
- Correct spelling error `PawnUnsuppresableFromCallback` to `PawnUnsuppressableFromCallback`.
- Fix an error in the VFE - Settlers patch.
- Spelling error could create confusion and inconsistency, and so should be fixed.
- Patch operation was broken.
Suffer.
=> Additional Fixes for 5.6 Hotfix

Defs/Ammo/Advanced/5x35mmCharged.xml, Defs/Ammo/Generic/Mech.xml
- Reverted the 5x35mm charged ammoClass back to Charged.
- Minor housekeeping for the mech generic ammo.
- The generic ammo lacked AP and Ion ammo types leading to anything that uses the ammo to break in Generic Ammo mode.
- Add AP and Ion ammo types to the generic mech ammo set.
=> Mech generic ammo hotfix

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml, Defs/ThingDefs_Misc/Apparel_Headgear.xml, SupportedThirdPartyMods.md
- Add a small amount of armor to a few pieces of apparel that don't otherwise have it.
- Update SupportedModList with one that was forgotten.
CE currently reports an error the first time apparel without any armor value is struck by a projectile (ErrorOnce). This error is harmless, but can be annoying/alarming for players seeing it. The easiest way to remedy it is simply to give the affects pieces of apparel a tiny amount of armor.
- Could rework the error/warning message.
- Could ignore.
=> Resolve armor value error for some clothing.

Source/CombatExtended/CombatExtended/Comps/CompFragments.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_BillDoors.cs
Provides explicit getters and caches for mods compiled against the old CE version which cannot easily recompile.
With 1.5 coming out soon, some mod authors have moved on from 1.4, making recompiling against CE 1.4.5.7 difficult.  So the most common getters and fields that are no longer needed by CE itself should still be provided for these legacy mods.
Only support mods that can be recompiled against current CE.
Roll back significant performance boosts to our projectiles
Use harmony to monkey patch affected legacy mods
=> Hotfix to restore ABI compatibility with CE < 1.4.5.7

Defs/Ammo/Advanced/80x256mmFuelCell.xml, Defs/Ammo/Generic/Mech.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Guns_MechanoidsExtraordinaire.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_MechWeaponry.xml, Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml, Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml
Same as #3029, my fork got borked and had to delete it.
- Increased the projectile and casing mass of the 80x256mm fuel cell ammo and also increased the filling amount from 0.5 to 1kg of incendiary agents.
- Make the appropriate changes to the inferno cannons to accommodate for the changes to the ammo.
- Decreased the reload time of the inferno cannon to a single shot weapon's 1.6s and reverted the warmup time to the accurate 4.3s.
- The cells were extremely light to the point that the projectile was 5/6th made up of filling contrary to conventional incendiary shells being a lot …
=> 80mm fuel cells and inferno cannons readjusted and fixed (#3029 reopened)

Defs/Ammo/Advanced/30x64mmFuelCell.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
Same as #3030, my fork got borked and had to delete it.
- Similar to the changes in #3057, adjusted the stats on the 30mm fuel cells.
- Fixed the stats on the T-9 incendiary launcher and added the proper Spacer TechLevel to it.
- The aforementioned cells were extremely light for something with 270 grams of filler.
- The T-9 lacked the reflex sights and the advanced component in its recipe.
=> 30mm fuel cells and T-9 launcher fixed and tweaks (#3030 reopened)

Defs/Ammo/Advanced/80x256mmFuelCell.xml, Defs/Ammo/Generic/Mech.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Patches/MechanoidsExtraordinaire/ThingDefs_Misc/Weapons_Guns_MechanoidsExtraordinaire.xml, Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_MechWeaponry.xml, Patches/Vanilla Factions Expanded - Mechanoids/CombinationDefs/CombinationDefs.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Mech.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Buildings_Security_Turrets.xml, Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Misc/Weapons_Mech.xml, Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml, Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml
Reverts CombatExtended-Continued/CombatExtended#3057
Having this PR in `development` would create serious and difficult to resolve conflicts with `loadfolder-migration.`
=> Revert "80mm fuel cells and inferno cannons readjusted and fixed (#3029 reopened)"

Defs/DamageDefs/Damages_LocalInjury.xml
- Fix an error with `CE_Laser` having a `Name` instead of a `ParentName`. 
- Trim out some excess lines that are already present in `Bullet` an so aren't needed.
- It's a typo.
Suffer.
=> Fix 'CE_Laser' ParentName Typo

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs
The ExactPosition line should be relative.  In trying to fix it the first go around, I added the new line withotu committing the removal of the old line.
=> Fix airburst positioning

.github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml, Source/BetterTurretsCompat/BetterTurretsCompat.csproj, Source/CombatExtended/CombatExtended.csproj, Source/Loader/Loader.csproj, Source/MiscTurretsCompat/MiscTurretsCompat.csproj, Source/MultiplayerCompat/MultiplayerCompat.csproj, Source/SRTSCompat/SRTSCompat.csproj, Source/VehiclesCompat/VehiclesCompat.csproj
- Compatibility patches can't currently build against 1.5, so are disabled
- Mod compatibility uses LoadFolders.xml + ModPatches/ so include them in the zip file
=> Disable building compat libraries add ModPatches/

LoadFolders.xml, ModPatches/Revia Race — biotech/Defs/Revia Race — biotech/Recipes_Revia.xml
- Delete leading whitespace in Revia patch that's causing a parse error.
- Change Ancient Armory - Fallout packageID from 1.3 to updated version.
- It just works.
- It just doesn't work.
=> Minor Patch Fixes

Anomaly/Patches/Misc/Mutants.xml
- Patch the melee weapon attacks for Anomaly's Ghouls and Shamblers
While playtesting Anomaly, having my starting ghoul melee and land an attack would give this error:
```
Exception in JobDriver tick for pawn Speedy driver=JobDriver_AttackMelee (toilIndex=2) driver.job=(AttackMelee (Job_3735) A = Thing_Hare49152 Giver = ThinkNode_QueuedJob [workGiverDef: null])
System.NullReferenceException: Object reference not set to an instance of an object
[Ref 23AC53EF]
at CombatExtended.Verb_MeleeAttackCE+<DamageInfosToApply>d__33.MoveNext () [0x00627] in <114f8ba2cb5445278852f48ffa8a3138>:0 
at CombatExtended.Verb_MeleeAttackCE.ApplyMeleeDamageToTarget (Verse.LocalTargetInfo target) [0x0007d] in <114f8ba2cb5445278852f48ffa8a3138>:0 
at …
```
=> Add CE patches for ghoul and shambler weapon

ModPatches/Vanilla Factions Expanded - Pirates/Defs/Vanilla Factions Expanded - Pirates/Ammo/DamageDefs.xml
Fix crypto cannon's damage not applying hypothermia and changed parent def to Frostbite.
- Tribal catapult that launches melee …
=> VFE- Pirate crypto cannon damage fix.

Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs
Fix NRE when selecting Corpse
```
System.InvalidCastException: Specified cast is not valid.
[Ref B0D7E200]
at CombatExtended.CompMeleeTargettingGizmo+<CompGetGizmosExtra>d__14.MoveNext () [0x00029] in <132a6d48a02a4daca8de5c85a98fad9a>:0 
at Verse.ThingWithComps+<GetGizmos>d__35.MoveNext () [0x000f3] in <957a20e0be784a65bc32cf449445b937>:0 
at Verse.Corpse+<GetGizmos>d__55.MoveNext () [0x0007a] in <957a20e0be784a65bc32cf449445b937>:0 
at System.Collections.Generic.List`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection) [0x00077] in <eae584ce26bc40229c1b1aa476bfa589>:0 
at System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00018] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
at …
```
=> Fix NRE when selecting Corpse

Anomaly/Patches/ThingDefs_Buildings/Buildings_Misc.xml, Anomaly/Patches/ThingDefs_Misc/Apparel_Packs.xml, Anomaly/Patches/ThingDefs_Misc/Weapons_Guns.xml, LoadFolders.xml, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCEOneUseStatic.cs
- Verb_ShootCEOneUseStatic for tactilal turret pack
- Patch for tactical turret (mostly copied from default turret, except range and mag size)
- Disabled explosion code if there's no damage def
- Disabled explosions without damageDef cuz Tynan use explosionRadius to show turret range
Add Anomaly folder to LoadFolder.xml before test
Also it's better test with #3097 
=> Verb_LaunchProjectileStaticOneUse and tactical turret patch

ModPatches/Rimsenal - Spacer Faction Pack/Patches/Rimsenal - Spacer Faction Pack/Mechs_Smart_CE.xml, ModPatches/Rimsenal - Spacer Faction Pack/Patches/Rimsenal - Spacer Faction Pack/Weapons_Smart_CE.xml
Buffed tagmaton gun
Added patch for new skulaton
partial armor patch for rimsenal mechs
suicide drone works fine
Added patch for new skulaton
Degrading armor added for rimsenal mechs
The bomb mech doesn't need a patch since its inheritance is all good, though depending on balance may need to nerf the bomb damage perhaps.
Increased Tagmaton needler melee damage. Increased clip size as Vanilla version is actually 4 shot assault rifle which indicates its probably high capacity, so that is now reflected. 
Increased armor on tagmaton .
3 bandwidth cost, and large size means they're (tag and skul) bulletcatchers. Both have close to pede armor in vanilla and tech wise you get them at the same time as gunnerpedes, so buffed accordingly to hopefully make them a bit meatier in combat. Armor …
=> Rimsenal Spacer 1.5 Mech update.

ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_RSGuns_CE.xml
Add the underbarrel weapons.
Added patches for the three cat-weapons added by the new 1.5 update
Tweaks to carbine and BR stats
Changed the carbine to SB 5.56 as it is a short barrel variant
Implemented the underbarrels with CE's underbarrel comp as it is not clear how we will be updating comp ability weapons going forward.
If an alternative comes up regarding the comp ability, we could use that implementation instead.
=> Rimsenal vanilla 1.5 underbarrels

ModPatches/Metal Gear Rimworld-Gekko/Patches/Metal Gear Rimworld-Gekko/ThingDefs_Races/Races_Mechanoid.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml, ModPatches/pphhyy Expanded Scythers/Patches/pphhyy Expanded Scythers/MechKind_CE.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Increased the partial armor on mech eyes from x0.1 to x0.25
- Mechs are getting brained through their eyes. With the outside squishy bodyparts working for mechs and degradable armor we can afford to have higher armor values on their eyes to lower the instant kill chances by destroying their brains.
- Even more armor on their eyes?
=> Mech sight sensor partial armor tweaked

ModPatches/Vanilla Factions Expanded - Pirates/Defs/Vanilla Factions Expanded - Pirates/Ammo/Ammo_Mods.xml, ModPatches/Vanilla Factions Expanded - Pirates/Defs/Vanilla Factions Expanded - Pirates/Ammo/Ammo_Vikings.xml, ModPatches/Vanilla Factions Expanded - Pirates/Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Apparel_Warcaskets.xml, ModPatches/Vanilla Factions Expanded - Pirates/Patches/Vanilla Factions Expanded - Pirates/ThingDefs_Misc/Ranged_Warcaskets.xml
- Changed the Warcasket Autorifle into a hip-fire weapon.
- It lacks a proper stock and overshadows every other warcasket weapon in terms of lethality in quick bursts due to how quick its aim time was.
- Leave it be?
=> Hip-fire Warcasket Autorifle

ModPatches/Vanilla Vehicles Expanded - Tier 3/Patches/Vanilla Vehicles Expanded - Tier 3/VehicleDefs/Burya.xml
- Added recoil of 0 to the "Vehicles.CETurretDataDefModExtension" for the Burya
- Requires #3122 or similar fix for testing
- The recoil for the Burya was broken and incrementing by -1 after each shot causing it to shoot randomly all around the place and even at itself
- Recoil of 0 replicates behaviour of other vehicles when using CE (all other vehicles seem to have 0 recoil by default)
https://gyazo.com/88a60be30e81e9099ae881fcb45316cb
=> VVE Tier 3 - Fix broken recoil on Burya

Source/CombatExtended/Harmony/Compatibility/Harmony_AlienRace.cs
- Removed the transpiler GetHumanlikeHeadSetForPawnHelper patch for HAR
- Closes #3111 
- With 1.5, HAR no longer has a transpiler patch for GetHumanlikeHeadSetForPawnHelper which meant the CE side patch was obsolete and breaking and causing CE to not load properly.
- Could maybe just delete the whole Harmony_AlienRace.cs file as it seems theres no patching needed but I left it since it has the giant example comment
- Might need to add back some kind of alternate patch if CE further changes the pawn rendering for 1.5
=> Fix HAR Compat by removing obsolete/broken patch

Languages/ChineseSimplified/Keyed/Misc_Gameplay.xml, Languages/English/Keyed/Misc_Gameplay.xml, Languages/PortugueseBrazilian/Keyed/Misc_Gameplay.xml, Source/CombatExtended/CombatExtended/Comps/CompAmmoGiver.cs
- Changes code to allow translations to use {0} in place of subject
- Update existing English, Chinese Simplified, and Portuguese translations to utilize correctly
- Allows translations that do not follow same sentence structure as English to have proper translation
- Add a space directly in the C# code
- Not as flexible as using {0} for the subject
- Leave typo of "Give Ammo to{SUBJECT]" on float menu
=> Give Ammo Float Menu Typo Fix

About/About.xml, LoadFolders.xml
- Updated and fixed the package ID of the Vanilla Base Generation Expanded mod.
- Updated the RW version in the LoadFolders file from v1.4 to v1.5.
- Suffer.
=> VBGE packageId fix and RW version update

ModPatches/Alpha Biomes/Patches/Alpha Biomes/Items_Resource_Stuff.xml
- Fixed a couple patches regarding the woody materials added by Alpha Biomes, the Alpha Animals check and equippedStatOffsets patch were unnecessary and broken.
=> Alpha Biomes material patch fix

ModPatches/Vanilla Armour Expanded/Patches/Vanilla Armour Expanded/ThingDefs_Misc/Armor_Riot.xml
- What it says on the tin, the riot gear were moved from VFE-Insectoids to VE Armour.
=> Patch the riot gear in VE Armor

Defs/Ammo/Rifle/762x39mmSoviet.xml
- Added the Short Barrel ammoset for the 7.62x39mm ammo.
- AKMS-U in Guns requires it.
=> Short Barrel 7.62 Soviet ammoset

Source/CombatExtended/Compatibility/WeaponToughnessAutoPatcher.cs
- Fixes the autopatcher when encountering weapons with a defined, but empty ingredients list;
- Rewrote and reformatted the autopatcher.
- Fixes an error encountered by #3139 which was caused by the autopatcher;
- Should look slightly cleaner.
- Ran #3139 with the changed assembly and did not encounter the error.
=> Fix and rewrite weapon toughness autopatcher

LoadFolders.xml, ModPatches/Edge of Descension - Hovercraft/Patches/Edge of Descension - Hovercraft/VehicleDefs/ArmoredHovertruck.xml, ModPatches/Edge of Descension - Hovercraft/Patches/Edge of Descension - Hovercraft/VehicleDefs/Hovercar.xml, ModPatches/Edge of Descension - Hovercraft/Patches/Edge of Descension - Hovercraft/VehicleDefs/Hovertank.xml, ModPatches/Edge of Descension - Hovercraft/Patches/Edge of Descension - Hovercraft/VehicleDefs/Hovertruck.xml, ModPatches/Edge of Descension - Hovercraft/Patches/Edge of Descension - Hovercraft/VehicleDefs/Vehicles_Explosions_Fix.xml, SupportedThirdPartyMods.md
- added patches for Armored Hovertruck and Hovertank.
- adjusted armor value for Armored Hovertruck, Hovercar, Hovertruck, and Hovertank.
- adjusted cargo value for Hovertank.
- adjusted internal components explosion range for Armored Hovertruck, Hovercar, Hovertruck, and Hovertank.
- because Sci-fi vehicles go woosh and Hovertank go boom boom.
- electric Tesla vehicles.
=> Patches for Edge of Descension - Hovercraft

Source/CombatExtended/Harmony/Harmony_StunHandler.cs
StunHandler patch for 1.5.
Besides all changes that makes it works in 1.5:
- Add reduction from `DamageDef.stunResistStat` if it exists;
- Make the prefix only returns true when the calculation is not redirected
- Fix a bug where the chance of resist another stun is always 100% (`Rand.Value` returns 0~1, but `stunResistChance` is not a percentage)
=> StunHandler 1.5 patch

Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/Gizmos/Command_ArtilleryTarget.cs
Remote bombardment can target ambush map now
- Player can no longer target the world object itself when there's player pawn on the map.
- Cross-map bombardment can only be performed on artillery markers.
https://discord.com/channels/278818534069501953/324222101550661663/1241442741221720317
- Or make it possible as long as there's any player faction pawn on target map (or have equipped radio pack, or more...)
=> Fix Remote Bombardment Cannot Target Ambush Map

Royalty/Patches/PawnKindDefs_Royalty/PawnKinds_Royalty.xml
- Made sure imperial Cataphract+ pawnKinds spawn older than 18 years old.
- Imperial Cataphracts spawn with ages lower than 18 and tend to have inventory cap issues, cataphract armor is heavy by itself and requires full inventory capacity values instead of the 80% that 13-18 y/o pawns get.
=> Imperial Cataphract minGenerationAge

Defs/Ammo/Grenade/30x29mmGrenade.xml, Defs/Ammo/Grenade/35x32mmSRGrenade.xml, Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/Grenade/40x53mmGrenade.xml
- Added 30x29mm HEDP grenades.
- Minor blunt AP housekeeping on a couple other HEDP nades.
=> 30x29mm HEDP grenades and housekeeping

Defs/ThingDefs_Buildings/Buildings_Defenses.xml
- Added the Smithing research as barbed wire's research prerequisite.
- Making the wires being metalworking and all that.
- Could set the prerequisite to machining but that'd be too ~~evil~~ late.
=> Barbed Wire research prerequisite

Defs/ResearchProjectDefs/ResearchProjects_Turrets.xml, Patches/Core/ResearchProjectDefs/ResearchProjects.xml
- Moved CE's heavy auto turret research project slightly up to be on the same Y level as the vanilla autocannon turret.
- Removed the Y axis patch of the vanilla autocannon turret.
- Alignment issues. CE's heavy auto turret tech now sits besides vanilla's AC turret tech and does not stick to the precision rifling project. AC turret tech now has the 3.1 Y coordinate by default making the patch redundant.
=> Minor turret research project location tweaks

Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs
- Improved the time it takes to open the loadout editor window on a 400x400 map from 5 seconds to pretty much instant
- Similarly improved the performance of the generic tab
- Re-added the visibility check for greying out items
- Other logic _should_ be unchanged
The previous implementation searches through every selectable thing on the map for every item in the list. That's a lot, especially for big and mountanous maps. Now it's only done once each time you open the window or the generic tab. The rest of the lookups go through a distinct list of defs found, which is much, much smaller. 
That frees up a lot of performance to reimplement the visibility check that was deemed "CPU expensive!" before.
=> Loadout manager window performance fixes

.github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml
- Turn compat assembly building back on by uncommenting it in the workflows
- Makes testing fixes to the compat patches way easier and allows people to test the patches for bugs on 1.5 as you don't have to build locally
- None of the compat patches give errors on startup when building locally unless they are outdated and their specific mod is enabled, so theres no real reason to keep them disabled
=> Turn compat assembly building back on

Defs/Ammo/Advanced/12GaugeCharged.xml
- Changed the spread multiplier of the 12 gauge charged ammo to be in line with other shotgun ammo types, 17.8 to 8.9.
- Forgor? There was a reason it was not touched but can't remember...
=> 12 Gauge Charged spread tweak

Royalty/Patches/PawnKindDefs_Royalty/PawnKinds_Royalty.xml
- Made sure imperial fighters retain their proper headgear regardless of the seasonal weather.
- Empire fighter pawnkinds can spawn with seasonal apparel and lack the `<apparelIgnoreSeasons>true</apparelIgnoreSeasons>` node leading them to forego armor in favor of tuques and other junk, helmets are irrelevant in vanilla but not CE.
- Cataphracts that wear tuques.
- Can target specific heavy units nut I prefer all the fighters keeping their helmets.
=> No hats for imperial fighters

Defs/ThingDefs_Misc/Weapons_Turrets.xml, Patches/Core/ThingDefs_Buildings/Buildings_Security.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
- Slight adjustments to the vanilla mini-turret and CE's medium turret. Changed the components in the mini-turret building recipe from 3 to 6 and power consumption from 80 to 100. Minor mass adjustments to increase the recoil on the both turret guns. Made the mini-turret slightly shorter and less bulkier.
- The mini-turret in vanilla is truly garbage and its recipe and power requirements fit it perfectly, but it's a decently potent turret and slightly overtuned in CE as it fires a not-so-weak cartridge pretty accurately at close range, it also has access to advanced ammo and is very cheap to build and power. The slight increase in power consumption and the components in its recipe …
=> Mini and Medium turret adjustments

Royalty/Patches/IncidentDefs/Incidents_Map_Misc.xml
- Placed the mech cluster trigger delay patch in the correct directory.
- Suffer the red error when Royalty is not loaded.
=> Mech Cluster delay patch fix

LoadFolders.xml, ModPatches/Det's Xenotypes - Boglegs/Patches/Det's Xenotypes - Boglegs/Abilities_Boglegs.xml, ModPatches/Det's Xenotypes - Boglegs/Patches/Det's Xenotypes - Boglegs/Hediff_Boglegs.xml, SupportedThirdPartyMods.md
- Patch boglegs xenotype.
- Rebalance blunt armor values added by stored blubber hediff.
- Patch knuckleduster melee attack along the lines of the brass knuckles from my CE Weapons mod (which I made stats for a long while ago).
- Slightly increase the range of the muck spit ability.
Close #3043 
- Set appropriate values for CE balance.
- Didn't see a point in patching the muck spit verb or projectile, since all it does is create a patch of filth.
- Different stat values, I suppose.
=> Patch Dev's Xenotypes - Boglegs

Defs/JobDefs/Jobs_CE.xml, Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
- Removed right click menu option to repair hostile pawns
- Player does not need an option to repair hostile mechs.
- Allow player to send pawns to commit suicide attempting to repair an angry hostile centipede.
=> Only allow repair armor repair of non-hostile pawns.

Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs
- Fixed incorrect calculations due to syntax sugar
- Closes #3190 
- No damage
Original code was compiled to this:
- Destroy centipede with molotov
=> Fixed incorrect penetration value

.github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml
- Include the Anomaly patch folder in the files built by the github actions.
- Because I forgot to add it to the original Anomaly PR.
- Suffer.
=> Add Anomaly to built files

Source/CombatExtended/CombatExtended/AmmoGeneralizer.cs
The ammo generalizer was disabled to ease porting to 1.5, this re-enables the code.
The required migrating the comp reloadable stuff, same as several other subsystems.
It also required replacing a def-equals check with an instanceof check, as 1.5 no longer provides handy handles to the scene part defs.
=> Re-enable and update AmmoGeneralizer

Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs, Source/CombatExtended/CombatExtended/DefOfs/CE_BodyPartDefOf.cs, Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs
1.5 removed the Neck def from the BodyPartDefOf provided by core RW.  This adds it to our own CE_BodyPartDefOf and uses it for the targeting pieces that used to target neck (and currently target eyes).
=> Use Neck BodyPart for melee targeting

ModPatches/Rimsenal - Spacer Faction Pack/Defs/Rimsenal - Spacer Faction Pack/Recipes_Grenades.xml
Change recipedef name for smart grenadex10 production to prevent red error on startup when loaded without Rimsenal Core
Changes Parentname: RSExplosive_RecipeBase, which only exist in Rimsenal Core to GrenadeRecipeBase. That's it. 
Rimsenal faction is meant to be able to be used standalone. 
None.
=> Minor bug fix for Rimsenal Spacer Faction

LoadFolders.xml, ModPatches/Moyo 2/Defs/Moyo 2/Ammo/Ammo_Moyo_Industrial.xml, ModPatches/Moyo 2/Defs/Moyo 2/Ammo/Ammo_Moyo_Laminar.xml, ModPatches/Moyo 2/Defs/Moyo 2/Ammo/Ammo_Moyo_Laminar_Charged.xml, ModPatches/Moyo 2/Patches/Moyo 2/PawnKindDefs/Moyo_PawnKind.xml, ModPatches/Moyo 2/Patches/Moyo 2/ThingDefs/Patch_Items_Resources.xml, ModPatches/Moyo 2/Patches/Moyo 2/ThingDefs/Patch_Moyo_Apparel.xml, ModPatches/Moyo 2/Patches/Moyo 2/ThingDefs/Patch_Moyo_Guns.xml, ModPatches/Moyo 2/Patches/Moyo 2/ThingDefs/Patch_Moyo_Melee.xml, SupportedThirdPartyMods.md
Patches for the new version of moyo content. Old stuff remains since they're a different mod technically and there's a cont'd version on the workshop that if it has the same package ID as the original, should load our patches anyway
Minor changes to the abyssteel. A number of weapons are outright different or don't have old equivalents.
Currently, we use the now shared ammo underbarrel comp to do the overclocked firing modes. In vanilla this actually outright changes what the weapon is, but that functionality breaks the ammo comp that we have, not transfering said data across.
We could make the guns fire from inventory, which sidesteps the ammo deleting/unloading problem when switching the item from one to the other. Alternatavely, a compatability module could be set up for the specifc …
=> Moyo 2 patch

Defs/Ammo/Advanced/12GaugeCharged.xml, Defs/Ammo/Advanced/12x64mmCharged.xml, Defs/Ammo/Advanced/12x72mmCharged.xml, Defs/Ammo/Advanced/15x65mmDiffusingCharged.xml, Defs/Ammo/Advanced/20x105mmCharged.xml, Defs/Ammo/Advanced/8x35mmCharged.xml, Defs/Ammo/Advanced/8x40mmCharged.xml, Defs/Ammo/Advanced/8x50mmCharged.xml
- Fixed the diameter of charged ammo types.
- Fixed and incorrect ammo recipe output.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit?gid=1393347070#gid=1393347070
- Charged ammo is telescoping caseless but the case diameter is the same exact as the projectile diameter, Added 2mm to the total diameter of the ammo.
=> Charged ammo diameter fix

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Parameter instead of property. Doesn't affect default render of Projectile in fact
- https://discord.com/channels/278818534069501953/322827713335394304/1256120395640209469
=> DrawAt: use parameter instead of property

Anomaly/Patches/PawnKinds/PawnKinds_Horaxian.xml, Defs/Ammo/Medieval/CannonBall.xml, Defs/Ammo/Medieval/MiniCannonBall.xml, Defs/ThingDefs_Misc/Apparel_Shield.xml, Defs/ThingDefs_Misc/Weapons_Ranged.xml, LoadFolders.xml, ModPatches/JDS Castle Walls/Patches/JDS Castle Walls/ThingDefs_Tower.xml, ModPatches/Vanilla Furniture Expanded - Security/Defs/Vanilla Furniture Expanded - Security/Ammo_Security.xml
- Add some rotation to ballistic shield when pawn is facing east or west.
- Add ammo to the Anomaly highthrall pawnkind.
- Allow VFE: Security raider heavy artillery to fire tox shells.
- LoadFolder.xml housekeeping.
- Add 'Castle Walls Reborn' to LoadFolder, slightly increase range of greatbow tower.
- Set shields to render on layer 80, preventing them from rendering in front of weapons.
- Increase the mag count override of the M72 and M79, so pawnkinds spawning with them get a bit more ammo.
- Makes the carrying position of the shield look a bit more natural and less rigid as the pawn is moving.
- Highthrall needs ammo, too.
- Sieges will be supplied with tox shells, so it makes sense to let the raider arty fire them. We don't have a dedicated 155mm tox shell, but the 81mm is sufficient …
=> 1.5 Release Fixes & Tweaks

Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_AmmoConsumedPerShotCount.cs
- Stop showing AmmoConsumedPerShot for Melee Weapons
It doesn't make sense
Leave it be
=> Don't show ammoPerShot for Melee Weapons

Source/CombatExtended/CombatExtended/Comps/CompTacticalManager.cs
- Tactial comps not used for shamblers (and crawling pawns) anymore
- Shamblers with guns and melee weapons
- Lose against shamblers (maybe even gorehulks and other) with rifles?
=> Tactital Comp deactivation for turned mutants and crawling mutants

LoadFolders.xml, ModPatches/pphhyy's Lightless Empyrean/Patches/pphhyy's Lightless Empyrean/Bodies_Jellyfish.xml, ModPatches/pphhyy's Lightless Empyrean/Patches/pphhyy's Lightless Empyrean/Race_Animals.xml, ModPatches/pphhyy's Lightless Empyrean/Patches/pphhyy's Lightless Empyrean/ThingDefs_Resources.xml, SupportedThirdPartyMods.md
- Patch new animals and material from pphhyy's Lightless Empyrean.
- New fabric is in line with basic wools.
- Gaster is essentially a stronger megascarab.
- Jellys are unarmored and fairly weak, but have a toxic attack.
- The shades are basically buffed humans.
- See above.
- Could do a different balancing scheme.
=> Patch pphhyy's Lightless Empyrean

LoadFolders.xml, ModPatches/Deployable Turret/Patches/Deployable Turret/Patch_MicroTurret.xml, SupportedThirdPartyMods.md
- Patch for Deployable Turret mod.
- Gunslinger arm is patched as a slightly weaker archotech arm, as in base mod.
- Because it is so cheap and spammable (though temporary), the micro turret is a crappier version of the Anomaly tactical turret, stats-wise. It has less range, RoF, and mag capacity, and higher recoil and sway. It also uses the low velocity variant of 5.56.
See above.
- Difference balance choices.
=> Patch Deployable Turrets

About/About.xml
N/A
Add Ludeon.RimWorld.Anomaly to loadAfter node of About.xml
- Closes #3243
Error if loaded before Anomaly. Adding to loadAfter will prevent this from happening unless user intentionally ignores defined load order.
N/A
=> Add Anomaly to loadafter

Defs/Ammo/Rocket/84x246mmR.xml
- What it says on the tin, it had the incorrect output of HEAT ammo.
- Suffer...
=> Thermobaric CG ammo recipe output fix

LoadFolders.xml, ModPatches/Vanilla Arsenal/Patches/RangedIndustrial.xml, SupportedThirdPartyMods.md
- chaingun patched for aprox. +25% bullet volume per burst and +25% ammo capacity relative to CE minigun, but retains speed penalty and minor accuracy penalty, and gains increased weight and bulk for mechanism
- pistol, rifle and dmr patched with respective common calibers, stats, and mod specific firing modes
- shotguns patched as common single fire weapons
n/a
n/a
- chaingun features an increase in firepower in vanilla with speed downside. implementation features that also, with the added bonus of mag capacity, but with an increase in weight and bulk, meaning reduced ammo cap for pawn. necessitates either local stationary ammo storage, bionics, exosuit, or full PA to carry more mags effectively due to total weight
- pistol, rifle and dmr feature credible (possibly unusual) burst fire …
=> vanilla arsenal patch

ModPatches/Kurin/Patches/Kurin/Scenario/DRNTF_Scenario.xml, ModPatches/Kurin/Patches/Kurin/ThingDef_Misc/DRNTF_Apparel.xml, ModPatches/Kurin/Patches/Kurin/ThingDef_Misc/DRNTF_Weapon.xml
- Added patches for new Kurin HAR Edition weapons; Kurin Carbin, Kurin Shotgun, Kurin Charge Rifle and Kurin Charge Shotgun. They're made slightly stronger than CE variants to reflect their higher costs.
- Added patches for Kurin Redfox Armor and Kurin Redfox Helmet. They're made similar to Power Armor.
- Removed melee dodge chance patch for Kurin Armored Gothic Dress as that stat is also removed in Kurin HAR Edition; that armor is now a psycaster armor in Kurin HAR Edition.
- Nerfed Kurin Military Helmet and Kurin Bikini Armor. Both of these had way too high of a material multiplier. Now they are more in line with the stats of the original mod.
=> Updated Kurin HAR Edition patch

Source/CombatExtended/Compatibility/Bipod_Injector.cs
Make bipod injector check for subclass of ShootCE instead of only ShootCE, so that weapons with custom verb can benefit from bipod
-Suffer from the insane recoil of railgun
=> enable custom verb on bipod injector

Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
-Make weapons with CE_AmmoGen_Disposable weapontag to be treated as single use during NPC loadout generation
It's bill doors with his custom verb problems again. My indirect weapons' verb was coded not to fire under roof, which make them not recognized as single use weapon.
Every raider show up with only one disposable LGIS launch tube (sounds like a benefit)
=> Correct ammo gen for single use weapon with custom verb 

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Things/Building_TurretGunCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootMortarCE.cs
**Verb_LaunchProjectileCE**
- `numShotsFired` | private int > protected int
- `lastTargetPos` | private IntVec3 > protected IntVec3
- `doRetarget` | private bool > protected bool
- `ShotHeight` | public float > public virtual float
- `GetMinCollisionDistance` | private float > protected float
- `CanHitCellFromCellIgnoringRange` | private bool > protected virtual bool
**Verb_ShootMortarCE**
- `numShotsFired` | private int > private new int 
**ProjectileCE**
- `TryCollideWithRoof` | protected bool > protected virtual bool
**Building_TurretGunCE**
- `Active` | public bool > public virtual bool
- `CanSetForcedTarget` | private bool > protected virtual bool
- `Projectile` | public ThingDef > public virtual ThingDef
- `TryStartShootSomething` | public void > public virtual void
- …
=> Change access level of various fields and methods for extensibility

Patches/Core/Stats/Stats.xml
- Made ranged weapon cooldown be affected by quality.
- Ranged weapon cooldown is considered the time it takes for a gun's action to cycle so the change is made to simulate the action being of a better or worse quality resulting in quicker and slows cycles.
- Numbers are not final, made sense to be this much considering the common values for cooldown.
- Leave as is.
=> Ranged weapon cooldown quality factor

ModPatches/WarCasket Expanded/Patches/WarCasket Expanded/Apparel_Warcaskets.xml
- Updated the Warcasket Expanded patch as it was causing errors on load for 1.5
- Fix patch errors
- None
=> Update warcasket expanded patch

Languages/English/Keyed/ModMenu.xml, Source/CombatExtended/CombatExtended/Settings.cs
- Add translation keys for autopatcher mod menu settings.
- Expand some autopatcher descriptions to actually provide some details about their functionality.
- Requested, and it's the proper way to do it.
- Continue to espouse the primacy of the anglosphere.
=> Key autopatcher mod menu entries

Source/CombatExtended/CombatExtended/CE_Utility.cs
- Toned down the recoil animations, especially for the higher end. Turrets travel less in the Y axis and there's slightly less muzzle rise for high recoil guns.
- Current curve leads to absurd muzzle rises and turret top movements.
- Suffer and tear the proverbial eyes out.
=> Recoil animation tweaks

Patches/Core/ThingDefs_Misc/Weapons_Guns.xml, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Defs/GunDrawExtension.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
Added a celling for casing lifetime, so that slow casings don't keep falling for too long.
A metric load of variables that will be enabled if AdvancedCasingVariables is true in gundrawext, including random ranges for casing eject angle, casing rotation, random spawn offset range. And multipliers and overrides for casing lifetime and speed.
-Deal with very-very edge case
-Prevent guns with too low recoil from behaving weird.
-Extra fine tuning freedom
-Most logic locked behind AdvancedCasingVariables so they don't burden most weapons too much.
-Suffer
=> More casing variables

Patches/Core/ThingDefs_Buildings/Buildings_Structure.xml
- Add a patch for the fence gate fill percent, reducing its height from 3.5m to 0.88m.
- Closes #3297 
-  The gate inherits `<fillPercent>1</fillPercent>` from vanilla `DoorBase`, making it 3.5m tall. This is the same height as a regular door and is, obviously, a little silly. Setting the value to 0.5 gives it an appropriate amount of cover--a bit taller than a fence, but shorter than a sandbag.
- Could leave as-is, or use a different value.
=> Patch fence gate height

ModPatches/Kurin/Patches/Kurin/ThingDefs_Races/Race_DRNTF.xml
Fixes an issue with patch causing no races other than Kurin to be able to wear backpacks if the Kurin HAR edition mod is loaded
It's a old patch maybe? It's not clear why it was done like this in the first place and was probably something from back when HAR alien race defs were different.
Actually check this patch is working as a whole since it throws a ton of errors on start-up.
=> Fix Kurin HAR patch from breaking CE apparel wearability.

Source/VehiclesCompat/VehiclesCompat/VehicleArmorPatch.cs
- Component depth is now effected by upgrades
- Should mean that everything from VF new upgrade system is working properly now. (Other values already correctly upgrade)
- N/A
=> Vehicle Framework - Component depth effected by upgrades

Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
- Added ability for vehicle turrets to shoot laser ammo types
- It would be cool if vehicles could use lasers
- N/A
https://github.com/user-attachments/assets/f73efb66-1aa4-4478-ac33-923045c38e27
=> Vehicle Framework - Add support for laser turrets on vehicles

Defs/Ammo/Advanced/164x284mmDemoShell.xml, Defs/Ammo/Generic/Mech.xml, Defs/Ammo/Medieval/CannonBall.xml, Defs/Ammo/Modded/Warhammer 40k/PlasmaCannon.xml, Defs/Ammo/Rocket/84x246mmR.xml, Defs/Ammo/Rocket/90mmRecoilless.xml, Defs/ThingDefs_Items/Items_Resource_Ammo.xml
- Fixed the cook-off explosion size scaling for certain items.
- Somewhere along the line between #1522 and now, there was a behind the scenes change to the cook-off explosion size scaling, most likely the `explosiveExpandPerStackcount` node, that changed how certain items behaved when cooked off. Most importantly Prometheum, FSX and Chemfuel itself which went from a huge 12 tile explosion to a mere 4 tiles. The new values mean that FSX and other bomb-like items explode in the same radius as before, being 5 tiles. Same thing but slightly smaller for Prometheum.
- Cringe at the puny explosions?
=> Cook-off explosion radius fix

ModPatches/Altered Carbon Ultratech Unleashed/Patches/Altered Carbon Ultratech Unleashed/AC_Patches.xml
patch Charge Incursionar from Altered Carbon
=> patch Charge Incursionar from Altered Carbon

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_AdvancedMechanoid_PlayerControlled.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid_PlayerControlled.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Updated the natural armor HP of the mechs that received 1.0 HP scaling in #3137.
- Forgor.
=> walker mech natural armor HP update

ModPatches/Ancient Blade Cyborg/Patches/Ancient Blade Cyborg/Cyborg_CoveredByNaturalArmor.xml, ModPatches/Antinium/Patches/Antinium/Bodies/Ant_Bodies.xml, ModPatches/Aspero Race/Patches/Aspero Race/CE_Patch_Bodies.xml, ModPatches/Astoriel Legacy/Patches/Astoriel Legacy/Astoriel_Bodytype.xml, ModPatches/Biomes Caverns/Patches/Biomes Caverns/BodyDefs/Bodies_CE.xml, ModPatches/Rim Flood/Patches/Rim Flood/CE_Flood_Bodies.xml, ModPatches/Rim Flood/Patches/Rim Flood/CE_Flood_Bodyparts.xml, ModPatches/pphhyy's Lightless Empyrean/Patches/pphhyy's Lightless Empyrean/Bodies_Jellyfish.xml
- Removed OutsideSquishy group patches for 'Ancient Blade Cyborg', 'Antinium', 'Aspero Race', 'Astoriel Legacy', 'Biomes! Caverns', 'pphhyy's Lightless Empyrean' mods, changed OutsideSquishy from group to tag patch for 'Rim Flood'.
- Closes #3260;
=> Update OutsideSquishy for missed mod patches

LoadFolders.xml
- Add continued version of both DD Elves & DD House Sanguin in LoadFolders to apply correct patches
Nothing.
- Adding instead of replacing to keep v1.4 running nad be able to remove it easily when/if both mod are updated by the original mod author
Could have copy/paste complete DD patch folders but that would have been combersome
=> chore(load-folder): Add continued version of DD House Sanguin & Elves

ModPatches/EPOE Forked Royalty DLC expansion/Patches/EPOE Forked Royalty DLC expansion/Bionics_Patch.xml, ModPatches/EPOE Forked/Patches/EPOE Forked/Bionics_Patch.xml, Patches/Core/HediffDefs/Hediffs_Local_AddedParts.xml, Royalty/Patches/HeDiffDefs/Hediffs_Implants.xml
- Tweaked the vanilla, Royalty DLC and EPOE-Forked's combat bionics and implants.
- https://docs.google.com/spreadsheets/d/11e6FkTQvZiJpq7DpXUk9JSXBSq9enrx0DQhTTJ2xH7c/edit?gid=647442519#gid=647442519
- They are all anemic when it comes to armor penetration, this helps a decent amount without making them imbalanced. The advanced parts in EPOE swing faster than the normal versions and the scyther versions are faster and heavier tools, the player is spending scyther blades to make them but they lack the bonuses that come with advanced parts so it balances out.
- Suffer the waste of resources and time.
- MOAR?!
=> Combat bionics and implants rebalanced

Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyMelee.xml
- What it says on the tin, it had inaccurate stats according to the spreadsheet data.
- https://docs.google.com/spreadsheets/d/11e6FkTQvZiJpq7DpXUk9JSXBSq9enrx0DQhTTJ2xH7c/edit?gid=647442519#gid=647442519
=> Fix Royalty's warhammer stats

Source/CombatExtended/CombatExtended/CE_Utility.cs
-Fix Rimworld of Magic wand rendering error.
-Bugfix
- Suffer
=> Add null check for weapon tags in recoil function.

ModPatches/A Rimworld of Magic/Defs/A Rimworld of Magic/Defs_Projectiles.xml, ModPatches/A Rimworld of Magic/Patches/A Rimworld of Magic/Patch_Ranged.xml
- Changed defNames for the CE projectiles, so they are not removed by the PatchOperationRemove targeting the defName of the original projectiles
- Closes #3301
- [ X ] Playtested a colony (specify how long) - large raid
=> Update Patch for A RimWorld of Magic

ModPatches/RH2 Faction - VOID/Patches/RH2 Faction - VOID/Items_Drugs/Alcohol_RedWine.xml
- Combine two PatchOperationAdd operations targeting the same def's (RH_RedWine) statBases into one operation
- cleaner this way
- might save a millisecond per startup
- leave as-is
- [ X ] Playtested a colony (specify how long) - spawned the Wine, checked Info Card shows Bulk and MeleeCounterParryBonus values are as expected, and bonked a raider with it
=> RH2 Faction - VOID small patch cleanup

LoadFolders.xml, ModPatches/Biotech Expansion - Insectoid/Patches/Biotech Expansion - Insectoid/BEI_AbilityDefs_Patch.xml, ModPatches/Biotech Expansion - Insectoid/Patches/Biotech Expansion - Insectoid/BEI_Hediffs_BodyParts.xml, SupportedThirdPartyMods.md
What it says on the tin.
Abilities has two versions one when pawn ingested jelly one didn't, the jelly one has slightly better pen and x2 damage. the 1 and 2 damage one is a debuff that when affected pawn dies they explode.
=> Patch Biotech Expansion - Insectoid

ModPatches/Rah's Vanilla Turrets Expansion/Patches/Rah's Vanilla Turrets Expansion/Patch_Buildings_Security.xml
- Removed patches for VulcanCannon, VulcanCannonManned, ChargeCannon that change their passability and pathCost
- These turrets are no longer impassable in the base mod, making the patches unnecessary, and also causing errors due to targeting nonexistant <passability> node on those defs.
- [ X ] Playtested a colony (specify how long) - spawned the turrets in question, forced a pawn to walk through them, forced pawns to reload them, forced them to fire on a target
=> Rah's Vanilla Turrets Expanded Patch Update

Defs/Ammo/Shell/105mmHowitzer.xml, Defs/Ammo/Shell/81mmMortar.xml
- Changed the Airburst shells to throw 1.5 times the amount of frags of normal HE shells.
- Fixed the indentation style of the files in the meantime.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit?gid=1393347070#gid=1393347070
- Shells that lack an explosive component and are meant to kill with frags should not have the same, or even less in the case of 81mm shells, the frag numbers than HE shells, it's counterintuitive and makes them useless. 
- Keep things as is and have yet another useless ammo type, suffer as a result.
=> Aitburst shell frag amount fix

Languages/English/Keyed/AmmoContainerKeyed.xml, Source/CombatExtended/CombatExtended/Building_AmmoContainerCE/Building_AutoloaderCE.cs
Additional notification when a powered autoloader is unpowered, or a manned is unmanned.
-Turned out it's not obvious a manned autoloader need to be manned. fooled me once.
-AUTOLOADER ARE BROKEN!!! (not really you need to man them)
=> additional autoloader failure notification

Anomaly/Patches/CreepjoinderDefs/Forms.xml
- Made sure certain creepjoiners from anomaly have backpacks to carry their weapon and its ammo.
- Made sure said creepjoiners spawn with enough ammo for their gun.
- The lone genius joiner spawns with the charge lance which was replaced with the charge rifle.
- Closes #3329
- Bulk cap issues.
- Creepjoiners are not like normal pawnkinds and spawn with their gun in not a traditional way (the weapons are forced items in their inventory) for CE's loadout code to assign ammo for them so patching the pawnkind itself or its parent does nothing hence the forced ammo in their inventory.
- Lances are not for the meatbags, the rifle is the closest option.
- Suffer.
=> Creepjoiner fixes

ModPatches/pphhyy Demigryph/Patches/pphhyy Demigryph/Demigryph_Banners.xml, ModPatches/pphhyy Demigryph/Patches/pphhyy Demigryph/Demigryph_Shields.xml
- Patched the banners and shields added by the mod.
- Both the banners and shields are converted to CE's shields, the banners have a melee attack that knocks back the target which is not compatible with CE and was left out.
- There a slight issue with the textures, the mod's textures are set up in a way that CE somehow does not recognize their masking style as they have all the directions/faces and as a result the textures don't take the color of the material they are made out of, maybe the code needs more work to recognize them?
=> pphhyy Demipryphs patch update

Defs/Ammo/Rocket/84x246mmR.xml
- What it says on the tin, the HEDP ammo types didn't have the correct ammoClass of GrenadeHEDP.
- Made the Canister ammo type's spread tighter, the base spread of the weapon is rather high resulting it a final spread being too much. The ammo type is less likely to spawn on NPCs too.
=> CG HEDP ammo ammoClass fix and misc housekeeping

Biotech/Patches/AbilityDefs/Abilities_Biotech.xml
- Adjusted the Sanguophage piercing spine projectile to be more potent in terms of AP, 14mm and 21MPa to be exact.
- It's extremely anemic for something that is supposed to be a charge lance shot in extremely close range that only fires 5 projectiles before needing to be "reloaded" under perfect conditions and if no other ability is even used. The current values are based one a plasteel bolt weighing 250 grams. It can do something to a normal composite vest after a couple shots now.
- Same thing that is happening to the Anomaly patch rebalancing, have to make things work as they are intended to be for space magic creatures, not what realistically might make sense.
- Suffer.
- Can go even higher, it lowers the chances of the change getting approved even more. …
=> Sanguophage spine stats tweak

ModPatches/Vanilla Furniture Expanded - Security/Defs/Vanilla Furniture Expanded - Security/NewRaiderArtillery.xml
- Set the raider artillery to have no designation category, so that it doesn't appear as buildable to the player.
- This was previously accomplished via CE's `MenuHidden`, but that currently appears to be broken. As a result, players can see the raider arty after researching mortars (for reasons that are unclear to me--removing the research pre-req doesn't make it stop).
- Fix `MenuHidden` (we need to do this anyway).
=> VFE - Security: Hide Raider Arty Again

Patches/Core/ThingDefs_Misc/Weapons_Grenades.xml
- Make frag grenades non-smeltable.
Due to the crafting cost for frags and their ability to be smelted, it was possible to "profit" on steel by crafting 10 grenades for 8 steel, and then smelting them for 5 steel each. Since RW can't do fractional amounts, it's easiest to just make frags non-smeltable, like other grenades.
- Could ignore the issue and leave as-is.
=> Make frag grenades non-smeltable

Biotech/Patches/ThingDefs_Misc/Weapons/RangedMechanoid_Light.xml, Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Light.xml
**Militor Mech**
- Reduce the militor's Aiming Accuracy from 1 to 0.6. This is better than the mini-turret (0.25) but worse than the lancer (1.7).
- Reduce the militor's Shooting Accuracy from 1 to 0.769. This gives the militor weapon handling comparable to a (healthy) Level 5 shooter. Previously, it was equivalent to a Level 8 shooter.
- Reduce night vision from 80% (inherited) to 40%.
**Mini-Shotgun**
- Reduced the mini-shotgun's ammo capacity from 8 to 6.
- Increase the mini-shotgun's cooldown from 0.4 to 0.6.
**Militor Mech**
The militor is a low-tier, swarm-style combat mech. It's patched combat power (60) is equal to a tribal berserker or 1.5 manhunting tortoises. While carrying a shotgun is always going to be an advantage in the early game before armor becomes more of a factor, the …
=> Militors Balance Adjustments

Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Keys for a few messages that can appear in the targeting/aiming info box.
- Swap a few strings in English out for translation keys.
- Closes #3305 
- This text can appear to the player, so there's no reason not to key it.
- Suffer (in languages other than English).
=> Add verb translation keys

About/About.xml
- Changed SOS2 from needing CE to load before to needing CE to load after
- Fixes [this](https://discord.com/channels/278818534069501953/994681225262415902/1275838774332493824) issue caused by the SOS2 assembly not being loaded by the time CE tries loading the SOS2Compat assembly
- To fix the above issue
- N/A
=> Fix SOS2 Load order

Defs/Ammo/Medieval/CannonBall.xml
- Tweaked the bursting and incendiary ammo recipe descriptions for the 12-pounder cannon shells.
- Odd descriptions.
- Better wording?
=> 12-Pounder recipe label tweaks

Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
Natural armor durability will not be reduced from damage that def harmshealth = false (firefoams) or is external violence (frostbite and SOS2 vacuum damage something)
-As we all know, firefoam shell is the best AT weapon in the universe, we should equip our armies with fire engines.
-Suffer.
=> Armor durability apply damage fix for non-health damaging or non external violence damage

ModPatches/Rimsenal Federation/Defs/Rimsenal Federation/FederationShellingResponse.xml, ModPatches/Rimsenal Federation/Defs/Rimsenal Federation/ThingDefs_Misc/Ammo_Fed.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/Factions_Federation.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_Apparel.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_DamageDefs.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_Explosives.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_MechWeapons.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_MeleeWeapons.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_RangedWeapons.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_Security.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Races/Race_Bion.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Races/Race_FederatorMech.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Races/Race_Hulk.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Races/Race_SeekerMech.xml, ModPatches/Rimsenal Feral/Defs/Rimsenal Feral/ThingDefs_Misc/Ammo_Feral.xml, ModPatches/Rimsenal Feral/Patches/Rimsenal Feral/ThingDefs_Misc/Feral_MutantWeapons.xml, ModPatches/Rimsenal Feral/Patches/Rimsenal Feral/ThingDefs_Races/Race_Ogrons.xml, ModPatches/Rimsenal Feral/Patches/Rimsenal Feral/ThingDefs_Races/Race_Razortooth.xml, ModPatches/Rimsenal Feral/Patches/Rimsenal Feral/ThingDefs_Races/Race_Shadark.xml, ModPatches/Rimsenal Feral/Patches/Rimsenal Feral/ThingDefs_Races/Race_Twisted.xml
Partial armor where suggested.
Natural Armor degradation.
Federation weapons now have a non-ammo consuming reload system.
Buffed armor that degrades for bions
Bions are now pain shock immune.
Federation custom bombardment response and shelling type. (Cluster and Heavy plasma bombs, prefer bombing to raiding and have slow world projectiles)
Bions now have much higher base armor, but it now degrades to less, more signficantly for blunt armor which will reduce down to 20%, while the sharp will reduce down to around 50% of the new value (slightly lower than what they were prior to this change)
Mutants also have degrading armor. The hulk mutant now  has partial on the arms/legs roughly equivalent to flak, and steel helmet/vest equivalent on their head/torso.
Federation ammo has been tweaeked …
=> Feral / Federation Partial Armor + Tweaks

Biotech/Patches/ThingDefs_Misc/Weapons/RangedIndustrial_Biotech.xml, Defs/Ammo/Generic/LauncherGrenade.xml, Patches/Core/Bodies/Bodies_Animal_Quadruped/QuadrupedAnimalWithPawsAndTail.xml
- Add recipes for Tox and Airburst to the generic grenade launcher ammo. Uses 40x46mm crafting stats.
- Add Tox grenade to the generic launcher ammo set.
- Add armor coverage to the tail of `QuadrupedAnimalsWithPawsAndTail`.
- These grenades need to be craftable in generic ammo mode, too.
- Entries within `ammoTypes` in an AmmoSetDef don't currently work with `MayRequire`, so we have to patch it. 
- Don't see a reason why the tail shouldn't be armored--probably just an oversight when the patch was made.
- Suffer.
- Fido keeps losing his tail.
=> Generic Grenade Recipes & Quadruped Tail Fixes

Biotech/Patches/ThingDefs_Misc/Weapons/RangedIndustrial_Biotech.xml
Removed the minimum range for tox grenades.
They're the same as flashbangs/smoke grenades where technically the explosion is unpleasant, but in most use cases you're wanting to actually throw these pretty close or cover yourself to slow down a non-tox immune target.
Complicated, but overall mechanism for changing minimum range based on threat to user. Not something I'd be able to implement though
=> Remove Tox Grenade Min range

About/About.xml
- Adds loadAfter for VFE - Mechanoid
- Fixes error of when VFE - Mechanoid and Alpha Biomes are both loaded. Auto-sorting may put VFE - Mechanoid before Combat Extended. https://discord.com/channels/278818534069501953/324222101550661663/1279139876423602349
- Fixes issue with CE patch of when VFE - Mechanoid and Alpha Biomes are both loaded, depending on load order of mod list. VFE - Mechanoid uses PatchOperationAdd to add a Def instead of LoadFolders.
- Ignore
- Less potential for cyclical load orders
=> VFE Mechanoid Load After

LoadFolders.xml, ModPatches/Remove Industrial Stuff/Patches/RemoveIndustrial_AmmoInjector.xml, SupportedThirdPartyMods.md
- Removes tradeTags to prevent Ammo Injector errors with Remove Industrial Stuff
- Mod leaves Cannonballs and Arrows that Ammo Injector attempts to add to respective Industrial workbenches that have since been removed.
- Rewrite the Ammo Injector
=> Remove Industrial Stuff Patch

Defs/Ammo/Advanced/164x284mmDemoShell.xml, Defs/Ammo/Advanced/66mmThermalBolt.xml, Defs/Ammo/Advanced/80x256mmFuelCell.xml, Defs/Ammo/Rocket/84x246mmR.xml, Defs/Ammo/Shell/105mmHowitzer.xml, Defs/Ammo/Shell/155mmHowitzer.xml
- Made large incendiary ammo deal less thermobaric damage, by 33% to be exact.
- Increased the raw damage dealt by the thump cannon ammo.
- Initial values were arbitrary according to Serina and kinda overtuned.
- The shells underperform in general, more raw damage is better than a lot of frags as it's easier to keep track of.
=> Incendiary and Thump ammo minor tweaks

Defs/Ammo/Advanced/12GaugeCharged.xml
- Increased the sharp AP of the 12ga charged ammo types to 10, 15and 12.5
- The slug ammo type had the incorrect amount of bomb damage (should have been 14), fixed that and increases the slug diameter by 1mm as there was just enough room for it.
- Reduced the total length of the cartridge as it was the same as a normal 12ga disregarding the fact that charged ammo is caseless and so on.
- Going with the normal charged ammo standard of the AP ratios and also the fact that 12ga charged buckshot pellets have the same exact velocity and mass, only 1 mm thinner in diameter which should even make them better at penetrating armor. So it makes 12mm for the base projectile, 18mm for the slugs same as how conc. is relative to normal charged and 15 for Ion same as normal Ion ammo but reduced the base …
=> 12 gauge charged adjustments

Defs/Ammo/AmmoBases.xml
- Reduced ammo crafting skill gain by half.
- Ammo crafting giving the same amount of exp as individual items makes it a bit too easy to level/maintain crafting.
=> Reduce ammo crafting skill gain

Defs/Ammo/Generic/Generics_Misc.xml, Defs/Ammo/Generic/ShotgunShell.xml
Adds <generateAllowChance>0.5</generateAllowChance> to generic shotgun ammo (emp) just like the non-generic versions
Renamed the label of revolver shotgun ammoset to "pistol". This fixes an issue where all pistol caliber bullets are called "revolver shotgun bullet"
=> Generic ammo fixes

ModPatches/Rimsenal Core/Patches/Rimsenal Core/Apparel_RS_CE.xml, ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Charge_CE.xml, ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Dumbfire_CE.xml, ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_RSGuns_CE.xml
Added size to match Vanilla changes more closely
Reduced EMP gun cooldown (no longer operates from infinite ammo pool and deals lower per hit damage) Reduced innate spread on Dumbfire weapons by 25%
Recoil added for single shot weapons, stats updated on a number of the regular guns as well as cost update for thumpercat/thundercat rifle
=> Rimsenal Vanilla Gun tweaks

Anomaly/Defs/Ammo/Flamethrower_Burst.xml, Anomaly/Defs/Ammo/NerveSpikerBolt.xml, Anomaly/Defs/DamageDefs/DamageDefs_Anomaly.xml, Anomaly/Defs/HediffDefs/Hediffs_Anomaly.xml, Anomaly/Defs/ToolCapacityDefs/ToolCapacity.xml, Anomaly/Patches/AbilityDefs/Abilities_Anomaly.xml, Anomaly/Patches/Bodies/Devourer.xml, Anomaly/Patches/Bodies/Dreadmeld.xml, Anomaly/Patches/Bodies/Fingerspike.xml, Anomaly/Patches/Bodies/Fleshbulb.xml, Anomaly/Patches/Bodies/FleshmassNucleus.xml, Anomaly/Patches/Bodies/Gorehulk.xml, Anomaly/Patches/Bodies/Metalhorror.xml, Anomaly/Patches/Bodies/Nociosphere.xml, Anomaly/Patches/Bodies/Noctol.xml, Anomaly/Patches/Bodies/Toughspike.xml, Anomaly/Patches/Bodies/Trispike.xml, Anomaly/Patches/Hediffs/Hediffs_BodyParts_Prosthetic.xml, Anomaly/Patches/Hediffs/Hediffs_Mutants.xml, Anomaly/Patches/Misc/Mutants.xml, Anomaly/Patches/ThingDefs_Buildings/Buildings_Obelisks.xml, Anomaly/Patches/ThingDefs_Misc/Apparel_Anomaly.xml, Anomaly/Patches/ThingDefs_Misc/Apparel_Packs.xml, Anomaly/Patches/ThingDefs_Misc/Weapons_Ranged.xml, Anomaly/Patches/ThingDefs_Races/Races_Entities_Misc.xml, Anomaly/Patches/ThingDefs_Races/Races_Fleshbeasts.xml, Anomaly/Patches/ThingTreeDefs/ThinkTreeDefs_Anomaly.xml, Biotech/Patches/DamageDefs/Damages_Misc.xml, Patches/Core/DamageDefs/Damages_LocalInjury.xml
- Added and patched missing things, tweaked stats that needed adjusting and ran a consistency check on everything related to combat.
- Anomalies are very anemic in the current set up, they were in a dire need of a buff. Their melee dodge, crit and parry chances were broken too which was fixed. Sightstealers needed some sustaining way of dealing with armor so gave them a stab attack similar to noctols but it's a propertionally weaker attack.
- Anomaly ranged attacks did not make sense compared to vanilla, made the ones that needed to threatening stronger and made the gorehulks shoot high damage but low AP projectiles as intended.
- Shamblers are sappers, made them better at their job.
- Made ghouls get some armor from the *armor* plating instead of just damage reduction, barbs also give a …
=> Anomaly balance pass

Anomaly/Patches/Hediffs/Hediffs_BodyParts_Prosthetic.xml
- Fixed the incoming damage multiplier stat on the ghoul plating.
- The patch was meant to reduce the damage resistance by 25%, not the other way around.
=> Ghoul plating stat typo fix

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Bursting.cs, Source/CombatExtended/CombatExtended/Verbs/VerbPropertiesCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
- Weapons can have their vertical draw position tweaked while pawns are warming up or recoiling.
- Projectiles fudge their draw position for the first few ticks (default 5) to hide the latent camera perspective issues
- Fully lie about projectile positions
- Draw projectile positions accurately, ignoring visual issues
- Change virtual camera perspective
=> Cheat on Projectile and Weapon drawing positions to mask camera problems

Defs/Ammo/Pistols/45ACP.xml, Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/AmmoGeneralizer.cs, Source/CombatExtended/CombatExtended/Defs/AmmoDef.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs
GenericLabelOverride field in CombatExtended.AmmoDef. Ammo generalizer will use it for projectile name if present.
Translation key for " bullet " in Ammo generalizer, since I stumbled across it.
NoTranslate annotation in AmmoDef's oldDescription, it has been annoying me forever and I happened to come across it.
Intended for edge cases.
Revolver shotgun SMG.
=> generic projectile label override

ModPatches/Miho Race/Patches/Miho Race/ThingDefs_Races/AlienRace_Miho.xml, Source/CombatExtended/CombatExtended/Comps_CCL/CompPawnGizmo.cs
CompPawnGizmo will now check if duplicate exists. If there does, an error message will be shown and extra compPawnGizmos will be deactivated.
Dupe CPG has been haunting HAR races for ages, as HAR patchers may not realize there's one in baseHuman. And duplicated CPGs causing gizmo to trigger twice upon click, breaking functions like aim height selection and UBGL. AFAIK it happened on miho and revia, and there're probably something else that does but not as popular.
An error message is with defname and mod name is provided so that patchers can locate the problem and players can report the issue to patch provider.
Duplicated CPG will skip their getgizmo so that functions still operate normally.
Strongly-worded letter to HAR patchers, check the god damned parent def! …
=> CompPawnGizmo Duplicate Proof

ModPatches/Vanilla Races Expanded - Insector/Patches/Vanilla Races Expanded - Insector/VFE-I2/AbilityDefs/AbilityDefs.xml, ModPatches/Vanilla Races Expanded - Insector/Patches/Vanilla Races Expanded - Insector/VFE-I2/GeneDefs/GeneDefs.xml, ModPatches/Vanilla Races Expanded - Insector/Patches/Vanilla Races Expanded - Insector/VFE-I2/HediffDefs/Hediffs.xml
- Patched the newly added cross-content with VFE-I2.
- Stats are chosen according to the existing stuff, the armor gene is stronger than stoneskin gland and comes from the Xanides geneline for example.
=> VFE Insector patch update

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Check if lightingtracker.map!=caster.map for recache
I received bug report about pawns moving from one map to another can't fire their weapon. this is the fix
=> Fix verb lighting tracker cache

Defs/Ammo/Medieval/BlunderbussShot.xml, Defs/Ammo/Medieval/MiniCannonBall.xml, Royalty/Patches/ThingDefs_Misc/Weapons_RoyaltyMelee.xml
- Swapped the sharp AP of blunderbuss and mini cannon ball grape ammo.
- Decreased the material requirement in the Royalty warhammer's recipe.
- Blunderbuss shot should have had 3mm and the other 3.5mm, not the other way around.
- The CE Melee maul is heavier and requires 120 materials which is the baseline, the warhammer being lighter and costing 150 doesn't make sense.
- Make the CE Melee maul require more work and materials? It requires 4000 less work in comparison too.
=> Minor assorted housekeeping

LoadFolders.xml, ModPatches/Star Crafter's Armory/Patches/Star Crafter's Armory/Apparel.xml, ModPatches/Star Crafter's Armory/Patches/Star Crafter's Armory/PPS.xml
- Changes Star Crafters Armory packageID to correct one making the patches load with the mod again
- Removed one Patch Operation line for PPSH since it fails on load and is Unnecessary (The one below it does what it's supposed to do)
- https://discord.com/channels/278818534069501953/668604879526428713/1285281816281878540
=> Star Crafters Armory fix

Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Non lerp projectile's armor pen now scales with velocity.
Made non lerp projectile's acceleration function virtual.
Fixed various problems including non lerp projectile hitting nothing because of ticktoimpact
Moved acceleration function in front of actual move code.
Having acceleration behind exactpos+=velocity means that I need to caculate the velocity needed next tick instead of current tick, which fucks with guided missile.
=> Non lerp projectile fixes

Defs/Ammo/Advanced/30x64mmFuelCell.xml, ModPatches/Rimsenal Enhanced Vanilla/Defs/Rimsenal Enhanced Vanilla/Ammo_EnhancedVanilla.xml
Improved capacity of fuel cells from 0.27 to 0.6.
Changed the rimsenal mini-thumper force from 1/2 power reduction to 1/3 reduction.
Makes fuel cells better because who the heck actually uses thermobaric fuel cells. Prior to weight nerf at least they had the niche of being efficent for wallbusting, but now they're practically useless. You gain access to their production 
This change makes them slightly more weight to damage efficent as stick bombs.
Thumper force increased to make it more proficent in its role as a wall breacher given that regular thermal cells have a bit of actual anti-personel lethality now probably.
Give fuel cells better ammo gated behind charge ammo.
Convince me how this is a bad thing that will utterly break game balance or something and that we should leave it as …
=> 30x64 fuel cells buff

Defs/Ammo/Shotgun/12Gauge.xml, Defs/Ammo/Shotgun/410Bore.xml, ModPatches/Morgante Mafia Weapons Pack/Patches/Morgante Mafia Weapons Pack/Weapons_Guns.xml, ModPatches/Pratt WWII Weapons Pack/Patches/Pratt WWII Weapons Pack/PWW2_CE_Patch_Weapons_Ranged_FR.xml, ModPatches/Rambo Weapons Pack/Patches/Rambo Weapons Pack/RamboWeaponsPack_shotguns.xml, ModPatches/Rimmu-Nation - Weapons/Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_RangedIndustrial_Shotguns.xml, ModPatches/Vanilla Weapons Expanded/Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml, Patches/Core/ThingDefs_Misc/Weapons_Guns.xml
- Adjusted the weapon's stats based on https://www.mossberg.com/500-retrograde-50429.html.
- Added a short barrel 12 gauge ammoset for use in sawed-off shotguns.
- https://docs.google.com/spreadsheets/d/1lbT0zzagCRPDJG4GctkeeoTsFCt3lYfM4SRnWt8ql-k/edit?gid=1573763037#gid=1573763037
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit?gid=1393347070#gid=1393347070
- Stat inconsistencies.
- Tests (https://www.kommandoblog.com/2017/05/16/shotgun-barrel-length-velocity/) show that an 11 inch barrel vs a 18~19 inch shotgun barrel have around 150 fps / 45 m/s difference in velocity.
=> Mossberg 500 parity checks and 12ga SB ammoset

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml
The Biotech patch now copies over the tags of the Combat Extended gas mask apparel to the Biotech gas mask apparel.
- People asked me to:
- Combat Extended has its own specific GasMask tag and the Biotech gas mask using the IndustrialBasic causes issues, like random pawns spawning with gas masks, that are not present in Combat Extended
- Completely removing the item overlap:
- Would be prefered, arguably leaving two different but identical items is a bit sloppy, but removals of those items were rejected in the past.
=> Biotech gas mask tags fix

.github/workflows/pullrequest.yml
The defensive programming added by #3431 fails if no target files are found.  Make `rm` ignore missing files.
=> Ignore nonexistant bad files

.github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml, BuildCompat.py
The workflows now tell BuildCompat.py where to find csc, it passes that information on to Make.py
- Needed to build #3428
We should use the same compiler for all assemblies.
The new PsyBlaster compat assembly uses C#10 syntax.
=> Make BuildCompat.py aware of new roslyn csc

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
If a projectile was launched above roof height and under roof, this projectile will ignore roof.
Fly overhead projectiles that meets above criteria will ignore roof when ascending, and re-enable roof colision when descending.
So that tall shooter under roof won't end up hitting roof.
-Disallow tall shooters from going under roof
--Good luck with AI pathing.
=> Proj from tall shooter under roof ignore roof

Defs/ThingDefs_Misc/Apparel_Shield.xml, ModPatches/Vanilla Factions Expanded - Classical/Defs/Vanilla Factions Expanded - Classical/ThingDefs_Shields.xml
- The base CE melee shield and the VFE one were too much to the left and low in the south perspective, similar to the ones in Armory fixed in: https://github.com/CombatExtended-Continued/CombatExtendedArmory/pull/94
- Suffer from the jank offsets.
=> Shield offset tweaks

About/About.xml
- Removes Profaned mod from having a loadAfter in About.xml
- No longer required and could cause unneeded cyclical load orders
=> Remove profaned loadAfter

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Instead of trying to duplicate the functionality in CE_Utility inline in the gear tab, we just use the same function to calculate location specific armor values.
Changes to location based armor calculations (like the natural armor, and later location-specific partial armor) lead to the two versions of the code getting out of sync.  Always using the same calculation means the reported value should match the value the damage system actually uses.
Fix the de-sync one issue at a time, forever.
=> Defer gear-tab armor calcs to CE_Utility

Defs/Ammo/Generic/Mech.xml
Changed the name of the generic `mechanoid shell (Incendiary)` item to `mech shell (Incendiary)`
Yes, I know this is a very minor nitpick.
The ammo sets and the recipes of incendiary mech shells refer to the item as mech shells. The item for the other mech shell type - demolition - is also called a mech shell. This seems to be an oversight.
Rename all mech shells to mechanoid shells.
=> Fixed a name inconsistency in generic mech shells

Defs/ThingDefs_Misc/Weapons_Ranged.xml
- What it says on the tin, makes the M79 use the new casing ejection features, as it's a break-action weapon.
=> Add casing ejection on reloading to M79 grenade launcher

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Bursting.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
Moving the logic of ticktotruepos from setted via launch to via projectileprop. A new field tickToTruePos is added for it, and if not present, the tick it takes to travel 10 tiles or 3 ticks will be used, whichever is larger.
-To restore backward-compat of custom projectiles and save our already ill-reputated compatibility.
-Breaking mods with their own custom CE projectile and not actively maintained.
=> Moving ticktotruepos from launch to projectileProps

Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
Reverts changing the weapon draw position to avoid jittering with automatic weapons.
People don't like how it looks.  Fixing it right would require interpolation and be fiddly.  It probably isn't needed with the cheating on projectile positions.
=> Revert pawn renderer cheating

ModPatches/Vanilla Animals Expanded/Patches/Vanilla Animals Expanded/ExtremeDesert_Animals.xml
- Fixed the armor patches for the megascorpion.
- Closes #3445
- The animal has the same amount of armor as a megascarab.
- Somehow this patch had not failed for me until the steam release even though I've been playing with the mod and #3349 at the same time so far...
=> VAE patch fix

ModPatches/Alpha Animals/Defs/Alpha Animals/Defs_DamageDef.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/AA_VFEI2/ThingDefs_Buildings/Buildings_Insectoid_AlphaAnimals.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_BlackQueen.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/AbilityDefs/Abilities.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Buildings/Buildings_Insectoid.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Patriarch.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_RoyalMegascarab.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_RoyalMegaspider.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_RoyalSpelopede.xml
- Patched and tweaked the turrets and pawn abilities.
- Fixed the temporary (psycast) Black Queen's patch.
- Increased the insect ability ranges as done with abilities in CE.
- The Vilelobber is tweaked slightly to match CE's standards better and the Thronworm is given a proper CE projectile along with the necessary changes for it to work as a CE turret. The Thronworm projectile is intended to have this much AP, it has more than double the AP of the vanilla AR in vanilla and requires a core to be built so it has to perform (Could probably give it even more AP, up to 9mm). Same deal with the Black Defiler, it's intended to fire a sharp damage type in explosion form which doesn't vibe with CE so it's converted into a main sharp projectile that has an appropriate spit explosion attached to …
=> VFE Insectoids 2 and Alpha Animals patch update

ModPatches/Vanilla Weapons Expanded - Frontier/Defs/Vanilla Weapons Expanded - Frontier/HighRoller_AddonAmmo.xml
VWE - Gauss uses LaserBulletYellow as a parent for their gauss projectiles while the addon guns, present when both VWE - Gauss and VWE - Frontier are loaded, use BaseLaserBullet which causes errors when fired. The base gauss weapons do not have this issue.
Changed the projectiles to use a parentname of LaserBulletYellow instead of BaseLaserBullet. Doing so fixes the errors that appear when the guns are fired.
- I do not like errors.
errors
=> Update VWE - Frontier Patch

About/About.xml
- Added the new packageId of the Better Loading mod to the incompatibility list.
- The author has changed the mod's ID which leads to the mod not being listed as incompatible, kept the old ID in place for future-proofing.
=> Better Loading incompatibility update

ModPatches/Rimsenal Core/Defs/Rimsenal Core/Ammo_TE.xml, ModPatches/Rimsenal Core/Patches/Rimsenal Core/Apparel_RS_CE.xml
Hazard armor heat and electric resistance changed for torso/head respectively. Kinetic lance ammo type now has higher secondary damage to assist with armor stripping of natural armor targets (like federators). Canister shots now have larger radius to account for damage falloff in CE.
Buffed the federator a bit which is pretty much the specific prey of the kinetic lance. Buffs to the penetration/damage should assist with making them a bit better of an option against them without realistically making much difference against most ohter targets due to the weapon already mulching most targets anyway.
Hazard helmet is  supposed to share protection levels with the armor, boosted the heat armor a bit to help combat the federation pentration changes.
=> Minor TE Adjustments

Source/CombatExtended/CombatExtended/Things/IncendiaryFuel.cs
- Prometheum how self-destroys when placed on water.
- Unreachable prometheum burning infinitely on deep water is janky.
- Patch a new tag onto deep water and check for that. This would still let prometheum burn on passable water.
=> Fix prometheum burning on water

Defs/ThingDefs_Misc/Apparel_Carrying.xml, LoadFolders.xml, ModPatches/Archotech PowerArmor/Patches/Archotech PowerArmor/Apparel_JDS.xml, ModPatches/K4G Empires of Old - The Alekeepers/Patches/K4G Empires of Old - The Alekeepers/Pawnkinds_Alekeepers.xml, ModPatches/K4G Empires of Old - The Faceless Sultainate/Patches/K4G Empires of Old - The Faceless Sultainate/PawnKinds_Sultanate.xml, ModPatches/K4G Empires of Old - The Faceless Sultainate/Patches/K4G Empires of Old - The Faceless Sultainate/TraderKinds_Sultanate.xml, ModPatches/K4G Empires of Old - The Polluted Legion/Patches/K4G Empires of Old - The Polluted Legion/PawnKinds_Legion.xml, ModPatches/K4G Empires of Old - The Rising Sun/Patches/K4G Empires of Old - The Rising Sun/PawnKinds_Dynasty.xml
- Patch for [K4G] Empires of Old - The Alekeepers
- Adds a single pawnkind with a ranged weapon that needs ammo.
- Note: Empires of Old - Core has a patch failing. It's since added some new content, and needs some attention. That'll be its own PR when I get around to it.
- Give the radio pack some WornBulk.
- Update [JDS] Archotech Armor to the 1.5 version that's floating around the workshop.
- Patch the new helmet and armor added.
- Remove some of our patches that made the armor cost less work and reduced the HP.
- Consolidate some patches.
- Misc. whitespace housekeeping inside Empires of Old (before I realized the patches were going to need more attention and would be better in their own PR).
Closes #3430
- Might as well patch the Alekeepers with some ammo. No reason not to.
- Usually …
=> Misc. Patch Tweaks/Updates

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
- Adds apparel check back to Gear Tab
- Adds check that prevents adding armor value under shieldCoverage part if the bodyPart shows up in in the bodyPartGroups for the apparel section of the shield. Prevents doubling up of the armor value, but not normally shown anyways.
- Suffer
=> Add Apparel Armor to Gear Tab

Anomaly/Patches/Hediffs/Hediffs_Misc.xml
- Inhumanized hediff now also gives a 50% multiplier to suppressability.
- People not caring about pain or other human concerns should probably care less about incoming fire
=> Suppress multi for inhumanization

Defs/Ammo/Generic/AntiMateriel.xml, Defs/Ammo/Generic/Autocannon.xml, Defs/Ammo/Generic/LauncherGrenade.xml, Defs/Ammo/Generic/Pistol.xml, Defs/Ammo/Generic/PistolMagnum.xml, Defs/Ammo/Generic/Rifle.xml, Defs/Ammo/Generic/RifleIntermediate.xml, Defs/Ammo/Generic/RifleMagnum.xml, Defs/Ammo/Generic/ShotgunShell.xml
- Full power rifle and pistol magnum now use the texture variants from their 'parent' calibers.
- Swapped generic stack classes to the vanilla `Graphic_StackCount`
- No point in having two different stack types across two different modes. If the explicit range stack is preferred then the classic ammo stacks should be converted as well.
- Read above.
=> Generic texture variants + filepath cleanup.

Defs/Ammo/Advanced/164x284mmDemoShell.xml
- Added the missing tradeTag that makes the ammo craftable in the fabrication bench, the ammo had the required recipe but not the tradeTag to be injected properly.
=> Made 164mm demo shells actually craftable

ModPatches/Vanilla Races Expanded - Lycanthrope/Patches/Vanilla Races Expanded - Lycanthrope/Pawnkinds_Special.xml
- The pawnKind wasn't patched, the loadout is similar to sanguophage thralls.
=> VRE Lycan wolfman pawnKind patch

Biotech/Patches/ThingDefs_Races/Races_Mechanoids_Medium.xml
- Removed the natural armor durability patch from the Tesseron and Legionary mechs.
- Both have the Lancer mech as their parent def which has the armor durability already patched in, causing a duplicate natural armor comp.
=> Duplicate natural armor durability fix

ModPatches/Vanilla Factions Expanded - Tribals/Defs/Vanilla Factions Expanded - Tribals/Recipes_Tribals.xml
Throwspikes from VFE - Tribals regularly requires the hunting research to be crafted and the research even mentions this.
The combat extended patch removes the multi-use throwable and adds a new recipe to make single-use throwspikes as usual, however this recipe does not have the appropriate research requirements.
- Consistency with the original intent of the mod.
Remove the mention of throwspikes from the research project.
=> Add a hunting research dependency to throwspikes from VFE - Tribals

LoadFolders.xml, ModPatches/Persona Warcasket Weapons/Patches/Persona Warcasket Weapons/Weapons_Warcaskets.xml, SupportedThirdPartyMods.md
update Persona warcasket weapons patch to look for the 1.5 version of the mod, removed no longer used capacity patches, changed prefix.
it got a new version, and the old one is no longer supported.
=> Persona warcasket weapons update

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
- Changed tribal pentinent's weaponMoney value from 50\~150 to 52\~150,
- An unidentified weapon has a mininum cost of 51.024, which might cause tribal pentinent to be weaponless.
=> Prevent tribal penitent from being weaponless

ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/PawnKindDefs/Pawnkinds_Mech.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Removed the combatPower patches from pikeman mech variants.
- The patch was there to balance out the mortar pikemen, it's not necessary anymore.
- I've been planning on adding a hostile-only mortar pikeman variant, it will have the same combatPower level.
=> Default pikeman combatPower reversion

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
Fixed projectile true position lerp broken by a int/int mistake
=> Fix true pos lerp

Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs
65ff9683efa00fa36d68ec6e11e523c44ff3d998 mistakenly turned off mech ammo beacons for clusters that start off dormant. Fix the logic so that beacons in such clusters correctly drop ammo once the cluster is awake and other conditions are met.
=> Fix initially dormant mech ammo beacons

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
- Added a null check to food policy in loadout updates, with true as a fallback
- Related bug report: https://discordapp.com/channels/278818534069501953/324222101550661663/1296770969045700669
- Conflict with Pawn Rules
- If a pawn ends up with no food policy it's better to accept any meal than not pick up any
- Set it to false
- Do a more extensive compat with Pawn Rules
=> Add null-check to loadout updates

Source/CombatExtended/Harmony/Designator_Dropdown_Patch.cs, Source/CombatExtended/Harmony/Harmony_Designator_Dropdown.cs
1. Research "Gas operation" or "Gun turret";
2. Check Security tab for KPV or Charge blaster turret.
- Player won't be able to build KPV (and few other turrets) w/o research
- Player able to build KPV w/o research
- Tynan\Ludeon, fix it, please;
- Validate active designator when game loaded/project researched instead of validation while accessing Visibility (not sure how it affects performance now);
- Let players build Mid-late game turrets w/o researches;
- Suffer.
=> Fixed the appearance of unresearched buildings 

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
I made a small change in projectile collision calculation to use seeded randomness in order to avoid desyncing when shooting through plants/trees.
Currently ChanceSeeded is using the thing.HashOffsetTicks() as seed, not sure if ideal but seems to work with no obvious issues
- Changed Rand.Chance() to use Rand.ChanceSeeded() within TryCollideWith() while calculating collisions for plants/trees.
I did some searching within the Multiplayer RW discord server about similar randomness issues, to which I found advice from a development team member of the Multiplayer mod that recommended using ChanceSeeded over Chance, with the seed being thing.HashOffsetTicks.
=> change Rand.Chance to Rand.ChanceSeeded for Multiplayer

Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs
- Fixed the long-standing bug of underbarrel weapons removing the aimed shot mode from weapons permanently until reloading the save. All I did was move the line that added the aimed shot mode into the init function. It's really simple, but it works without issues in my testing so far.
- Closes #3324
- Underbarrels call the InitAvailableFireModes() function, which skipped adding the AimedShot mode as that gets added outside of the function.
=> Fix underbarrel aim mode bug

ModPatches/Rimsenal Federation/Defs/Rimsenal Federation/ThingDefs_Misc/Ammo_Fed.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_DamageDefs.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Misc/Fed_RangedWeapons.xml
Thermal penetration on the three Fed damage types
Manufacturable crucible weapons (Which are specifically the modifed versions, not any original federation ones) have the ability to switch between their default crucible type damage and optical damage via underbarrel comp.
Player made plasma cavilier now can switch to the bion variant fire mode via underbarrel comp.
Optical type weapons outside of the heavy weapons have had their damage output reduced by ~1/3 to compensate for their ability to ignore a very significant amount of thermal armor (80%).
Crucible damage remains the same but now has 40% penetration.
Plasma has also received a moderate amount of penetration (30%).
Optical weapons have received a significant penetration buff to help them retain efficency against the player where …
=> Rimsenal Federation - Thermal Pen

Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs
Ignore burning ammo in JobGiverUtils_Reload, to match the corresponding jobdriver.
The reload jobgiver ignores ammo that is burning, but the jobgiver does not. Because of this, if the best available ammo for a turret is on fire, it'll cause pawns to spam jobs ("X started 10 jobs in one tick"). 
=> Disregard burning ammunition when reloading turrets

Patches/Core/HediffDefs/Hediffs_Local_AddedParts.xml, Royalty/Patches/HeDiffDefs/Hediffs_Implants.xml
- Same exact treatment that armor glands received, the Moving stat is responsible in inventory capacities in CE which a hand/arm prosthetic impacting it doesn't make sense, a movement speed coupled with dodge chance penalty instead makes the most sense.
=> Prosthetic Moving stat penalty replaced with movement speed and dodge chance

ModPatches/Robotic Servitude/Patches/ThingDefs_Races/Races_Mechanoid.xml
- The armor values were given based on a simple comparison with vanilla walker mechs that have 40% S and 20% B armor, the combat laborer has 55% and 35% and the assassin has 45% and 55% sharp and blunt armor respectively. Their armor values are reversed and broken right now.
=> Robotic Servitude armor patch fixes

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Reverted the projectile shadows to showing their exact position.
- The current 'realistic' shadows for projectiles make it significantly harder to see the trajectory and current position of indirect fire shells that often go off-screen due to their altitude and doesn't add anything significant to direct-fire projectiles.
- Use exact position only for indirect projectiles
=> Revert projectile shadows

Languages/English/Keyed/Messages.xml, Source/CombatExtended/CombatExtended/WorldObjects/HostilityComp.cs
Currently, the message that pops up when a retaliation raid is impending does not indicate which world object the raid is targeting, which can be confusing if the player has multiple colonies or launched a bombardment from a temporary map. So, make the target explicit in the notification.
=> Indicate target site for retaliation raids

Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs
Matrix4x4.rotation and Quaternion.eulerAngles are, somewhat confusingly, not fields but relatively costly property accessors. When rendering many pawns, repeated calls to them can have a measurable impact, so store the result in a local variable and reuse it.
This cuts the overhead of our pawn rendering patch by half. Impact on the overall game performance would depend on how many pawns are being rendered in the viewport, but when profiling a 10k point tribal raid, it went from ~2.22% to ~1.23%.
=> Memoize Y-offset for pawn rendering

ModPatches/Vanilla Factions Expanded - Deserters/Patches/Vanilla Factions Expanded - Deserters/Contraband.xml
Removed a stray > symbol in the Deserters patch file.
...don't ask me why it didn't error out in testing.
=> Fix stray closing tag in Deserters patch

Source/CombatExtended/CombatExtended/Settings.cs
- Subsequent shots are now enabled by default for new configs.
- Feels stable enough in testing.
- Larger number of people using it would help iron out the edge cases faster.
=> Enable faster subsequent shots by default

Defs/ThingDefs_Buildings/Buildings_Turrets.xml
- Increased turret HP to 1000
- Increased cover height to 3.5m
- 90mm flak is a really weak turret for the resource investment. The only advantage over handheld launchers it has is double the range, while having twice as long aiming time and twice as long reloading time. And you can't move it, so it gets shot up by a centipede pretty quick. And it has 5x the steel cost, compared to a Carl Gustav, while having only 500 HP (like a granite wall), so 30 rounds of 7.62 APHE is enough to completely destroy it. 
- These changes would give it an advantage over handheld AT launchers in form of being much less risky to use.
- [Discord discussion …
=> Buff Flak cannon protection

Defs/Ammo/Shell/105mmHowitzer.xml, Defs/Ammo/Shell/155mmHowitzer.xml
A very minor one. Makes the 155mm and 105mm howitzer shells no longer drop casings.
Realism. 105mm and 155mm shells being fired from artillery guns don't use fixed-cased projectiles, instead using bag charges. There are fixed-case 105mm shells that I've found, but we currently don't have anything that would use those.
- Leave it as-is.
- Create separate variants of the 105 and 155 projectiles that do spit out casings when fired, in case we end up needing them.
=> Artillery shells don't use casings

ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Barb_Slinger.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Base.xml, ModPatches/Alpha Genes/Patches/Alpha Genes/ThingDefs_Races/Races_OcularSlinger.xml, ModPatches/Metal Gear Rimworld-Gekko/Patches/Metal Gear Rimworld-Gekko/ThingDefs_Races/Races_Mechanoid.xml, ModPatches/RimWorld - Witcher Monster Hunt/Patches/RimWorld - Witcher Monster Hunt/Races_KikimoreCE.xml, ModPatches/Rimsenal Federation/Patches/Rimsenal Federation/ThingDefs_Races/Race_Bion.xml, ModPatches/Rimsenal Feral/Patches/Rimsenal Feral/ThingDefs_Races/Race_Razortooth.xml, ModPatches/Vanilla Animals Expanded - Waste Animals/Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Base.xml, ModPatches/Vanilla Animals Expanded - Waste Animals/Patches/Vanilla Animals Expanded - Waste Animals/ThingDefs_Races/WasteAnimals_Toxscorpion.xml, ModPatches/Vanilla Animals Expanded/Patches/Vanilla Animals Expanded/Desert_Animals.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Bases.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Machines.xml, ModPatches/Vanilla Factions Expanded - Mechanoids/Patches/Vanilla Factions Expanded - Mechanoids/ThingDefs_Races/Races_Mechanoid.xml, ModPatches/pphhyy Expanded Scythers/Patches/pphhyy Expanded Scythers/MechKind_CE.xml, Patches/Core/ThingDefs_Races/Races_Animal_Farm.xml, Patches/Core/ThingDefs_Races/Races_Animal_Insect.xml, Patches/Core/ThingDefs_Races/Races_Animal_Temperate.xml, Patches/Core/ThingDefs_Races/Races_Mechanoid.xml
- Remove all instances of `<useStatic>false</useStatic>` and add a bit of additional info to the in-line notes.
`useStatic` is false by default, and so this doesn't need to be specified in the mod extension except in cases where the pawn might be inheriting it from somewhere (there are no such cases in our integrated patches).
I suspect this is simply a case of a value being copy-pasted while patches were being made without people really knowing why. It's functionally harmless, but removing it slightly shortens some file lengths and may reduce confusion as to the field's actual functionality.
- Leave it as-is.
=> Clean up useStatic tags on Partial Armor

ModPatches/Big and Small Genes/Defs/Big and Small Genes/Weapons/ThingDef_Ammo.xml, ModPatches/Big and Small Genes/Patches/Big and Small Genes/Weapons/ThingDef_RangedNeolithic.xml, ModPatches/Vanilla Factions Expanded - Classical/Patches/Vanilla Factions Expanded - Classical/ThingDefs_WeaponsRanged.xml, ModPatches/Vanilla Factions Expanded - Tribals/Patches/Vanilla Factions Expanded - Tribals/ThingDefs_WeaponsRanged.xml, ModPatches/Vanilla Weapons Expanded - Frontier/Patches/Vanilla Weapons Expanded - Frontier/Weapons_Frontier.xml
- Tweak the stats of the VWE: Frontier Rolling Block Rifle
- Weight was too high, not sure where the old values came from.
- https://docs.google.com/spreadsheets/d/1R0to_-kn7-7Xut9P9BAenOdSII4hOVKQpZH2Ce8cRgQ/edit?usp=sharing
- Big & Small Genes javelin.
- Changed the recipe labels a bit to improve clarity.
- Fix thing category for some thrown weapons.
- Big & Small Genes
- VWE - Tribal & Classical
- Closes #3533
- Some rolling block's other stats were slightly off compared to what the sheet comes up with.
- Some thrown weapons don't have an assigned thing category for stockpiles because we changed the parent, but forgot to give them a thing category.
- Suffer.
=> Some patch fixes/tweaks

Anomaly/Patches/ThingDefs_Races/Races_Entities_Misc.xml, Anomaly/Patches/ThingDefs_Races/Races_Fleshbeasts.xml, ModPatches/Starship Troopers Arachnids/Patches/Starship Troopers Arachnids/Races.xml
- Change pain shock threshold of various pawns.
- Change values of 99 to 0.99, to be more clear.
- Change values of 90 to 0.90 so that they're actually less than the max threshold. 
While `PainShockThreshold` will accept any numerical value, it is clamped between 0.01 and 0.99 by the StatDef, so only values in that range have any discrete function. All values < 0.01 are functionally the same as 0.01, and all values > 0.99 are functionally the same as 0.99--see the min and max values below.
```
<StatDef>
<defName>PainShockThreshold</defName>
<label>pain shock threshold</label>
<description>The pain level at which this creature is downed from pain.</description>
<category>BasicsPawn</category>
<minValue>0.01</minValue>
<maxValue>0.99</maxValue>
<defaultBaseValue>0.8</defaultBaseValue> …
```
=> Correct Pawn Painshock Threshold Values

Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/VehiclesCompat/VehiclesCompat/VehiclesCompat.cs
The static method for launching CE-compatible projectiles is now included in the core assembly, instead of the vehicle assembly.  
This allows mods and addons other that VF to use it.
Duplicate the functionality in each other instance where it's needed.
=> Move static LaunchProjectileCE to CE_Utility

Source/CombatExtended/CombatExtended/Verbs/VerbPropertiesCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
Verb classes contain a good deal of unused code, let's remove it.
Reduces confusion and also lessens the potential maintenance burden going forward.
=> Remove unused verb-related code

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
https://github.com/CombatExtended-Continued/CombatExtended/pull/2869 adjusted the collision check used by shields to normalize away the 3D component of positions by default, which in turn caused high-shields to no longer intercept indirect fire shells. Switch these to use spherical collision checking to bring back the old behavior.
- Closes #3010
=> Fix high-shields not intercepting indirect fire shells

LoadFolders.xml, ModPatches/Xen's Spirit Wolf/Patches/Xen's Spirit Wolf/ThingDefs_Races.xml, Patches/Core/ThingDefs_Races/Races_Humanlike.xml, SupportedThirdPartyMods.md
Added support for Xen's Spirit Wolf mod.
- Similar to the warg, but a bit faster.
=> Add Xen's Spirit Wolf support

ModPatches/Anima Animals - Community Temp/Patches/Anima Animals - Community Temp/ThingDefs_AnimaCreatures.xml, ModPatches/Profaned/Patches/Profaned/ThingDefs_Races/Profaned_Race_UndeadWarg.xml, Patches/Core/ThingDefs_Races/Races_Animal_Bears.xml, Patches/Core/ThingDefs_Races/Races_Animal_WildCanines.xml
- Remove patches reducing the wildness values of the warg, wolves, and bears.
Noticed these patches while looking over the warg's combat stats, and found that they were done by NIA about 5 years ago (on the old CE) and haven't been changed since. I couldn't find any specific reasoning, but I'd suspect it was intended to make them more effective as combat animals by allowing the player to keep more of them.
Removed them because, broadly speaking, I'm of a mind that CE shouldn't change basic stats in vanilla or shift balance more than is really necessary. In this case, we create the strange situation where a warg is more tame than a horse. One could argue, "genetic tailoring to be easier to train, blah blah," but it strikes me as a violation of common sense than the roided out space velvet …
=> Remove Wildness Changes

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/SuppressionUtility.cs, Source/CombatExtended/Compatibility/BlockerRegistry.cs
Suppression code can be fairly hot, e.g. when an explosion occurs within a large group of pawns that sends them looking for cover. Some of the relevant logic in SuppressionUtility is using LINQ heavily, which causes significant memory pressure in such scenarios. When profiling a save with a doomsday hitting a 10k point tribal raid, InterceptorZonesFor() was responsible for ~3.7% of total time despite there being no shields on the map at all.
So, replace LINQ in relevant methods with iterator functions, which are less memory intensive, eliminating about ~3.5% of the total time.
=> Remove LINQ from suppression code

Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs
The current implementation of the "repair armor" menu option eagerly scans every item on the map when the menu is displayed, which can cause lag. As a fix, use GenClosest for each ingredient def with a custom validator to ensure only the relevant items are scanned, and reorder the checks to avoid doing this at all if the armor of the pawn being inspected cannot be repaired any further.
- Closes #3339
=> Fix potential lag from natural armor repair menu

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootMortarCE.cs
* Centralize ammo management for verbs within `Verb_ShootCE`
* Split ammo count check / selection and ammo consumption into separate methods
* Consume ammo in `OnCastSuccessful` rather than before attempting the shot
- Closes #3500
* `Verb_LaunchProjectileCE` doesn't need to know about `CompAmmo`, only `Verb_ShootCE` and derivatives do. The current system leads to reload / ammo management logic being copypasted across verb classes, which is error-prone.
* We currently check for and reduce ammo count before checking if a shot can actually be fired. For burst weapons with interruptibleBurst = true, this can cause extra ammo to be consumed without a corresponding shot being made.
=> Only consume ammo for shots that were actually fired

ModPatches/Alpha Animals/Patches/Alpha Animals/AA_VFEI2/ThingDefs_Races/Races_BlackEmpress.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/AA_VFEI2/ThingDefs_Races/Races_BlackQueen.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/AA_VPE/ThingDefs_Races/Races_BlackQueen.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Ravager.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Empress.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Gigalocust.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Gigamite.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Ironclad.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Megapede.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Patriarch.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Queen.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_RoyalMegaspider.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Silverfish.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Teramantis.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Titantick.xml
- Added high pain shock threshold, damage reduction and in some cases both to VFE Insectoid 2 and Alpha Animals boss insects and very large bugs.
- Large bugs are falling way too quickly due to pain, damage reduction and higher pain shock threshold is going to help with that since armor can only be so high.
- Even higher DR% for the boss insects?
=> Modded large insectoid durability buffs

Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs, Source/CombatExtended/Harmony/Harmony_DamageWorker.cs
- Melee attacks now no longer create fragments when the fragments from walls are enabled
- Using melee to break buildings/debris carries disproportionate risk with the setting enabled.
- Melee attacks *should* be the only instances of damage where the tool isn't null, so shouldn't affect anything else.
=> Exclude melee from wall frags

Defs/ResearchProjectDefs/ResearchProjects.xml
- As stated in the title, adds mention of reflex sights and advanced optics to the optoelectronics research description.
- Certain weapons in CE Armory require optoelectronics research to craft, this simply gives an explanation why. Most notably, basic opto is used for the M7, M250, and MG338 because of their reflex sights, and advanced opto is used for the Carl Gustaf's laser rangefinder scope.
- May encourage modders and patchers to use these research projects more.
=> Broaden Optoelectronics Research Descriptions to Include Electronic Weapon Sights

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
Add `CompAmmo` back to `Verb_LaunchProjectileCE` after it was moved to `ShootCE` in https://github.com/CombatExtended-Continued/CombatExtended/pull/3569.
* Some mods such as Bill Doors' Plasma Weapons will need a recompile before being able to use the new property.
Arrange for dependent mods to recompile against new CE - but there's no guarantee that'll happen in time for the release.
=> Add CompAmmo back to Verb_LaunchProjectileCE

Defs/ResearchProjectDefs/ResearchProjects_Turrets.xml
- Removed the multi-analyzer building requirement from researching heavy auto-turrets research project.
- As seen in the screenshot below, the tech is placed and supposed to be unlocked before multi-analyzer tech and is also blocking access to autocannon turrets which are originally meant to be a microelectronics research. Apart from that the tech itself already has three prerequisites with the main one being precision rifling so another gate in front of it is unnecessary in my opinion. Auto KPV turrets are also not advanced enough to warrant a multi-analyzer to research.
- Leave things be or shuffle things around? It seems not needed in my opinion.
=> Heavy auto turrets tech prerequisite tweak

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
Don't try to decrement ammo count in the magazine for weapons that don't have a magazine.
=> Fix ammo handling for magless weapons

LoadFolders.xml, ModPatches/Mantis Race/Patches/Mantis Race/Bodies_Mantis.xml, ModPatches/Mantis Race/Patches/Mantis Race/Hediff_Mantis.xml, ModPatches/Mantis Race/Patches/Mantis Race/PawnKind_Mantis.xml, ModPatches/Mantis Race/Patches/Mantis Race/Race_Mantis.xml, ModPatches/Mantis Race/Patches/Mantis Race/Scenarios.xml, ModPatches/Mantis Race/Patches/Mantis Race/ThingDefs_Items_Claws.xml, SupportedThirdPartyMods.md
- Patch for the Mantis Race mod.
- Adds a new, melee-focused race and their body as well as a scenario, pawnkinds, and prosthetics.
- **Known issue:** The mantis claws, antenna, and other parts rendered specially by HAR appear over top of the ballistic shield. Unfortunately, I couldn't find an easy way to change this, so I made the mantis unable to use those shields.
Closes #636 (at long last)
- The Mantises excel in melee, and so their base melee attacks are borrowed from the various insectoids (with the AP toned down). The prosthetics follow similar lines, upgrading this as appropriate.
- Could leave it unpatched for another few years.
=> Patch Mantis Race

Patches/Core/PawnKindDefs_Humanlike/PawnKinds.xml
- Remove sidearms from pirate drifters.
- Drifters are melee pawns, they have no use for another knife.
- Double knife madness.
=> Remove Sidearms from Pirate Drifters

ModPatches/Grimworld Core Imperialis/Defs/Grimworld Core Imperialis/CE_Patch_Ammo_Production.xml
- Point the Imperium loading bench texture at our copy of the textures, instead of Grimworld's (which was removed in the last update).
- Grimworld updated and removed the Imperium ammo bench texture that were accidentally relying on.
- Suffer.
=> Update loading bench texture path

Defs/Ammo/Shotgun/10Gauge.xml, Defs/Ammo/Shotgun/12Gauge.xml, Defs/Ammo/Shotgun/16Gauge.xml, Defs/Ammo/Shotgun/20Gauge.xml, Defs/Ammo/Shotgun/23x75mmR.xml, Defs/Ammo/Shotgun/410Bore.xml
- Added slug specific AmmoSetDefs for all shotgun calibers, intended for use in slug guns.
- Certain shotguns (slug guns) are rifled* and intended to only be loaded with slugs. While they _can_ fire buckshot, they would suffer from wildly inaccurate spread patterns from the rifling, and are basically unusable with the unintended ammunition.
- Slug guns are commonly scoped, and are quite accurate at longer ranges. Currently however, modders adding scoped slug guns have to also deal with "sniper buckshot" as a result of the increased range and lowered spread, which as explained would not be realistic.
*Note: Yes the KS-23 has a rifled barrel. It also sucks IRL. The CE Armory KS-23 is statted no differently from an ordinary shotgun and therefore doesn't need to use the new AmmoSet.
- Suffer …
=> Add slug AmmoSetDefs to shotgun calibers

Defs/Ammo/Pistols/38SW.xml, Defs/Ammo/Pistols/762x38mmR.xml, Defs/Ammo/Pistols/8x22mmNambu.xml
- Fixed 8x22mm Nambu using a rifle texture for FMJ
- Swapped .38S&W and 7.62x38mmR to revolver textures
- Those are (at least mostly) revolver cartridges
=> Minor pistol texture fixes

Languages/ChineseSimplified/Keyed/ModMenu.xml, Languages/English/Keyed/ModMenu.xml, Languages/PortugueseBrazilian/Keyed/ModMenu.xml, Languages/Russian/Keyed/ModMenu.xml, Source/CombatExtended/CombatExtended/Settings.cs
- Replace cyrillic chars in translation keys to ascii version
- Translation keys should have ascii-chars only;
- Non-ascii translation keys are not searchable;
- It may not display correctly in text editors if user don't have a font with cyrillic charset;
- Might be copy-paste error that no one noticed.
=> Replace non-ascii chars in CE_Settings_CreateCasingsFilth keys.

Anomaly/Patches/CreepjoinderDefs/Forms.xml
- Creep joiner patches now use conditional generic patch ops.
=> Add generics for creep joiners

ModPatches/Save Our Ship 2/Patches/Save Our Ship 2/Scenarios_SOS2.xml
Similar to default crashlanded scenario, SOS2 starting scenarios need vanilla armor removal, as it causes ignore-able stuffing red errors if starting unedited scenario. Or worse, scenario editor broken badly if scenario is edited before start, which is a frequent case for those scenarios.
Fix to Save Our Ship 2 compatibility patch, specifically for scenarios.
=> SOS 2 starting scenarios patch fix

Languages/English/Keyed/ModMenu.xml, Source/CombatExtended/CombatExtended/Controller.cs
- The game now prompts for a restart when closing the settings window after toggling the generic ammo setting.
- The change requires a full restart to apply properly, unlike disabling ammo, which silently re-runs the injection again.
=> Promt for restart on changing generic mode

ModPatches/RH2 Faction - Gruppa Krovi/Patches/Apparel_Gruppa_Krovi.xml, ModPatches/RH2 Rimmu-Nation² - Clothing/Patches/RH2 Rimmu-Nation² - Clothing/Backpacks_CE.xml, ModPatches/Spartan Foundry/Patches/Spartan Foundry/Apparel_Armors.xml
=> Removal of CarryingCapacity notes from RH2 patches

Source/CombatExtended/Harmony/Harmony_ResearchPrerequisitesUtility.cs
- Disabled ammo now no longer shows up in research
- Cleans up the research screen
- Answer more questions about the Tomahawk Missile
=> Hide disabled ammo from research

Make.py
Github's runners no longer provide a systemwide install of csc, so we need to always use the snapshotted version
needed by new PRs, including #3602 #3635 and so on
=> Always use snapshotted csc

.github/workflows/code-style.yml, .github/workflows/main.yml, .github/workflows/pullrequest.yml, .github/workflows/release.yml
ubuntu-latest now points at 24.04, which does not include mono/csc/C# out of the box. For now, we just specify the previous version to run on.
Figure out the ubuntu/debian package name for mono and have it install in the setup phase
=> Specify ubuntu-22.04

ModPatches/Vanilla Weapons Expanded/Defs/Vanilla Weapons Expanded/Ammo/Recipes.xml
The 10x recipe for throwing knives from Vanilla Weapons Expanded uses 14 steel and produces 14 throwing knives. Fixed the recipe to output 10 knives and consume 10 steel.
https://github.com/user-attachments/assets/06c9c290-7f58-4ed8-af7d-01b2e3cc0340
- Make the recipe x14:
- Really awkward number
=> Fixed throwing knives recipe having wrong amounts

Anomaly/Patches/ThingDefs_Misc/Weapons_Ranged.xml
- Change the Incinerator's warmup time to that of SMG/shotgun type weapons, fix the absurdly high cooldown time.
- Flamethrowers in CE are close-ranged spray and pray weapons, similar to a shotgun or SMG, yet they use the warm up times of full-sized rifles. This caused many situations where pawns won't fire until the target is basically inside the minimum firing range circle and getting dangerously close to the shooter.
- The incinerator for some reason had a whopping 1.1 extra seconds of cooldown time compared to the RM2. Simply set the cooldown to that of the RM2's.
- "Hold still while I aim this flamethrower"
=> Tweak Incinerator Warmup and Cooldown

LoadFolders.xml, ModPatches/Victorian Era Apparels/Patches/Victorian Era Apparels/GnmVictorianEra_Apparel.xml, SupportedThirdPartyMods.md
- patches for Adventure Dress, Elegant Dress, Maid Dress (A-B), Walking Dress, Riding Habit Dress, Simple Dress
- patches for Dress Coat, Frock Coat, Smoking Jacket, Waistcoat, Bulletproof Waistcoat, Soldier Coat, Hussar Jacket
- patches for Feathered Hat, Maid Headdress (A-B), Boater Hat, Top Hat, Soldier Helmet, Slouch Hat, Shako Hat, Metal Soldier Helmet
- patches for Glasses, Monocle
- Fashion culture leap in British isle history
- Industrial revolution
- Because of industrial revolution and its consequences
Describe alternative implementations you …
=> Patch - Victorian Era Apparels!

Defs/Ammo/Shell/57x438mmBofors.xml
- A simple fix to recipe labels and descriptions, should be x10 instead of 25.
=> 57mm Bofors recipe typo fix

Defs/StuffCategoryDefs/StuffCategories.xml
Added missing nouns for stuff category defs.
Fixes this:
Noun is used to represent stuffable categories in most contexts, not the label.
=> Add missing nouns to stuff category defs

Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs
- Will use the item's unreserved stack count instead of the current stack count in the UpdateLoadout JobGiver when giving jobs to pickup or equip items. 
- https://discord.com/channels/278818534069501953/324222101550661663/1323104384539693087
- The pickup job throws exceptions when it fails to reserve an item right after starting.
- The issue can be replicated with, for example, assigning two pawns a loadout that requires more ammo for both than is currently available and ordering both to rearm. With this change, the first pawn to get the rearm job should pick up the most ammo, and no exception should be thrown.
=> Check for unreserved item stack count before giving loadout update jobs

Defs/Ammo/Other/Flamethrower.xml, Languages/ChineseSimplified/DefInjected/ThingDef/Flamethrower.xml
- Fix a typo in the flamethrower description that causes a malformed linebreak.
- Noticed it in MysteriousFawx's video, and will not be able to sleep if I don't fix it.
- Seriously, it's been like that for months! How has nobody pointed it out?
- Shame and insanity.
=> Fix linebreak typo

Defs/Stats/Stats_NightVision.xml, Defs/Stats/Stats_Weapons_Ranged.xml, Languages/English/Keyed/Stats.xml, Source/CombatExtended/CombatExtended/StatParts/Base/StatPart_StatSelect.cs, Source/CombatExtended/CombatExtended/StatParts/StatPart_Bipod.cs, Source/CombatExtended/CombatExtended/StatParts/StatPart_StatMaxima.cs, Source/CombatExtended/CombatExtended/StatParts/StatPart_StatMinima.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_BipodDisplay.cs
- Duplicate fire rate and burst shot count stats are hidden on weapons, they were already displayed from verb props.
- Info tabs of weapons with items without a Thing reference (i.e. from research or crafting screens) now displays bipod stats correctly.
- Sway and Recoil values on those weapons now also default to 'set up' values, if bipods are enabled.
- Tweaked the colors of bipod stat explanations to use more muted colors.
- Added explanation for Night Vision stat calculations.
- Changed apparel and weapon night vision labels to make the explanation clearer.
- No point in showing the same data twice.
- Better to show the stats of the weapon set up, since that's how it's meant to be used.
- Previous bipod stat colors were too bright.
- Apparel and weapon night vision stats were …
=> Clean up various stats

ModPatches/EvolvedOrgansRedux/Patches/EvolvedOrgansRedux/Brain_Evo_CE.xml
EVOR_Hediff_Brain_ReptilianFrontalCortex patches removed, as def is commented out in Steam release
https://discord.com/channels/278818534069501953/324222101550661663/1334461968303652924
Prevents Patch errors
Could comment it out instead, in case mod author re-implements the hediff
=> Patch Update for Evolved Organs Redux - author removed def

LoadFolders.xml
Polarisbloc CoreLab and SecurityForce mods does not have official 1.5 version, and there're fan made ports for 1.5. But the mod ids have changed in order to keep both mods alive on disk.
- Make CE work with Polarisbloc CoreLab tmp port https://steamcommunity.com/workshop/filedetails/?id=3225348593
- Make CE work with Polarisbloc Security Force tmp port https://steamcommunity.com/sharedfiles/filedetails/?id=3225387996
- Add a line for Vanya.Polarisbloc.CoreLab.tmp in LoadFolders.xml
- Add a line for Vanya.Polarisbloc.SecurityForce.tmp in LoadFolders.xml
- Issues not created yet
Why did you choose to …
=> Add supports for Polarisbloc fan made port Mods for 1.5 

LoadFolders.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/CompanionSphere.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/Fluoid.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/RoyalLancer.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/RoyalLancerWeapons.xml, ModPatches/AV Mechtech/Patches/AV Mechtech/Scrapper.xml, SupportedThirdPartyMods.md
- Patch for [AV] Mechtech.
Same as #3672 + necessary fixes, but Visual Studio pushed it to a separate branch instead, for some reason. Could be the original PR author denied editing permissions? Not sure.
- Mechs patched along similar line to existing light and medium mechs.
- Different balancing scheme.
=> Patch [AV] Mechtech

ModPatches/Vanilla Factions Expanded - Deserters/Patches/Vanilla Factions Expanded - Deserters/Buildings_Special.xml, ModPatches/Vanilla Factions Expanded - Deserters/Patches/Vanilla Factions Expanded - Deserters/Things_Security.xml
- Patched the autocannon loader to also reload the double autocannon turret from VFE Security.
- Double autocannon now also accepts a loader when Deserters is active, causing an error when spawned unpatched.
=> Minor VFE Deserters patch update

LoadFolders.xml, ModPatches/GrimWorld Scattered Sons/Patches/GrimWorld Scattered Sons/CE_Patch_Armors.xml, ModPatches/GrimWorld Scattered Sons/Patches/GrimWorld Scattered Sons/CE_Patch_Armors_Helmets.xml, ModPatches/GrimWorld Scattered Sons/Patches/GrimWorld Scattered Sons/CE_Patch_Hediffs.xml, ModPatches/GrimWorld Scattered Sons/Patches/GrimWorld Scattered Sons/CE_Patch_Melee_Weapons.xml, ModPatches/GrimWorld Scattered Sons/Patches/GrimWorld Scattered Sons/CE_Patch_Shield.xml, SupportedThirdPartyMods.md
- New patch for armor, melee weapons, abilities, and pawnkinds added by Grimworld Scattered Sons.
- Close #3613 
- Patched along the same lines as various other Grimworld mods. Equipment is generally superior, since Primarchs presumably have the absolute best of the best.
- Different balancing scheme, I suppose.
=> Patch Grimworld - Scattered Sons

Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs
Changed the biocoded check in ITab_Inventory to use EquipmentUtility.CanEquip instead.
I expect most mods that fiddle with equipment restrictions do their job by patching CanEquip. Ours don't use it, which means ours can bypass it.
Bruh
=> Equip from inventory uses CanEquip

ModPatches/DD House Sanguin/Patches/DD House Sanguin/Mods/RimFantasy - Medeival Overhaul/Blood Weapons.xml
- Fixes the find mod as Rimfantasy name changed
- Closes #[[3591](https://github.com/CombatExtended-Continued/CombatExtended/issues/3591)]
- Suffer
=> Update House Sanguine Patch

Source/CombatExtended/CombatExtended/Building_AmmoContainerCE/Building_AutoloaderCE.cs, Source/CombatExtended/CombatExtended/Comps_CCL/CompPawnGizmo.cs, Source/CombatExtended/CombatExtended/StatParts/Base/StatPart_StatSelect.cs
- Added null checks for apparel and equipment in night vision stat explanations, because animals don't have these trackers.
- Also removed a couple of stray semicolons that somehow haven't tripped the style checker in months. (?????)
=> Add null checks for animal night vision

ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/HighCaliber/20x102mmNATO.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/HighCaliber/338Lapua.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/HighCaliber/50BMG.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/Pistol/Patch_44Magnum.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/Pistol/Patch_45ACP.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/Rifle/Patch_556x45mmNATO.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/Rifle/Patch_762x51mmNATO.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/Sabot.xml, ModPatches/Expanded Materials - Metals/Patches/Expanded Materials - Metals/Ammo/Shotgun/12Gauge.xml
Added generic ammo to the corresponding non-generic ammo's patch for EM Metals
Could give some or all generic ammo their own patch rather than using the same values as the non-generic ammo
=> EM Metals Patch for Generic Ammo

Source/CombatExtended/CombatExtended/AmmoGeneralizer.cs, Source/CombatExtended/CombatExtended/AmmoInjector.cs
- Changed ammoInjector to no longer use a SCOS and only inject ammo with a LongEvent.
- Added a log to generalizer to more easily check execution order.
- SCOS was initializing the class earlier than the LongEvent, which led to injection running twice, once in the constructor, and once in said LongEvent.
- Builds made with the github actions were causing that SCOS to run before the generalizer, causing non-generic hyperlinks to appear in descriptions.
=> Fix race condition in AmmoInjector

ModPatches/Vanilla Factions Expanded - Classical/Defs/Vanilla Factions Expanded - Classical/ThingDefs_Shields.xml
Changed the Vanilla Factions Expanded - Classical shield label from kite shield to tower shield
The Roman Scutum is a type of tower shield for infantry, kite shields taper towards the bottom and can be more easily used mounted.
=> Update VFEC shield label for historical and graphical accuracy

Source/SOS2Compat/SOS2Compat/Building_ShipTurretCE.cs, Source/SOS2Compat/SOS2Compat/Verb_ShootShipCE.cs
Changed implicit cast operator to explicit type conversion function. That function is now used on SOS 2 side to make selecting ship turrets from tactical console (via gizmos) feature work properly
SOS2 side changes, split into 2 PRs:
https://github.com/Bqr1s/SaveOurShip2/commit/135e1d9a7da9298af97e1fd98fbbe360880b62a2
https://github.com/Bqr1s/SaveOurShip2/commit/473c6da79e36c9ec65558da759eed58f5bbd3293
Implicit type cast operator won't work on SOS2 side, so it was replaced with named function, to make calls via reflection more readable
When only CE is updated, feature is not expected to work, because main fix body is on SOS2 side, not tested.
feature = when tactical console is selected, all connected turrets have separate gizmos to select turrets of the …
=> Added explicit type conversion method to be used on SOS2 side

Defs/Ammo/Advanced/164x284mmDemoShell.xml, Defs/Ammo/Projectiles_Fragments.xml, ModPatches/Anty the war Ant/Defs/Anty the war Ant/Ammo_Anty.xml, ModPatches/Grimworld Core Imperialis/Defs/Grimworld Core Imperialis/Ammo/CE_Patch_GravGunAmmo.xml, ModPatches/Maru Race/Defs/Maru Race/Ammo_Arrow_AT.xml, ModPatches/Miho Race/Defs/Miho Race/Ammo/Ammo_Miho_Industrial.xml, ModPatches/Paniel the Automata/Defs/Paniel the Automata/Ammo_Paniel.xml, ModPatches/Rim-Effect Core/Defs/Rim-Effect Core/ME_Projectile_Damage_Ammoclass.xml, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Will carry the projectile ticks until true draw position through save and loads;
- Will add tickToTruePos as zero to projectiles that are used only as fragments in order to allow them to spawn at the position of the projectile which spawned them.
- #3638
=> Save projectile's ticks to true position, make fragment projectiles have zero ticks to true position

About/About.xml
There's a patch in Vanilla Factions Expanded - Medieval 2 targeting Vanilla Weapons Expanded that can potentially fail if Combat Extended is loaded after Vanilla Weapons Expanded but before Vanilla Factions Expanded - Medieval 2, which is entirely possible as Combat Extended does not complain about being loaded before that mod.
These patches in Vanilla Factions Expanded - Medieval 2 fail because in this scenario, the mod tries to patch verbs that Combat Extended has replaced.
This error does not happen when Combat Extended is loaded after both mods.
- errors sob sob
=> Add VFE - Medieval 2 to loadAfter

Source/CombatExtended/Harmony/Harmony_PawnGenerator_GenerateGearFor.cs
- PawnGenerator.GenerateGearFor Postfix that checks if a pawn has generated with both a shield and a two-handed weapon. If so, it destroys the shield.
- Pawns that spawn with both a two-handed weapon and a shield just stand around not doing anything productive during raids
- CE Shields are apparel and can be potentially spawned during apparel generation before two handed weapons are spawned.
- Weapons are generally more important than armor
- Patch on PawnWeaponGenerator.TryGenerateWeaponFor
- Leave potentially useless pawns
=> Fix Pawn Generation 2HWeapon+Shield

Defs/Ammo/Advanced/12mmRailgun.xml, Defs/Ammo/Grenade/40x46mmGrenade.xml, Defs/Ammo/HighCaliber/20x102mmNATO.xml, Defs/Ammo/Modded/Warhammer 40k/Autoguns.xml, Defs/Ammo/Modded/Warhammer 40k/Bolter.xml, Defs/Ammo/Modded/Warhammer 40k/Bolter_Small.xml, Defs/Ammo/Modded/Warhammer 40k/HeavyBolter.xml, Defs/Ammo/Modded/Warhammer 40k/LasGun.xml, Defs/Ammo/Modded/Warhammer 40k/MeltaGun.xml, Defs/Ammo/Modded/Warhammer 40k/PlasmaCannon.xml, Defs/Ammo/Other/Flamethrower.xml, Defs/Ammo/Pistols/454Casull.xml, Defs/Ammo/Pistols/45ACP.xml, Defs/Ammo/Rifle/3006Springfield.xml, Defs/Ammo/Rocket/84x246mmR.xml, Defs/Ammo/Shotgun/10Gauge.xml, Defs/Ammo/Shotgun/23x75mmR.xml, ModPatches/GrimWorld Talons of the Emperor/Patches/GrimWorld Talons of the Emperor/CE_Patch_Traders.xml, ModPatches/Grimworld Angels of Death/Patches/Grimworld Angels of Death/CE_Patch_Traders.xml, ModPatches/Grimworld Core Imperialis/Defs/Grimworld Core Imperialis/Ammo/CE_Patch_GravGunAmmo.xml, ModPatches/Grimworld Core Imperialis/Patches/CE_Patch_Traders.xml, ModPatches/Grimworld Hammer of the Imperium/Patches/Grimworld Hammer of the Imperium/CE_Patch_Traders.xml
PR Content TBC - Currently in draft for building and testing
- Added 40K ammo trade tags to all ammo used by Grimworld mod weapons
- Added TraderKindDef patches for all the traders in the various Grimworld mods
- None of the traders in the Grimworld mods would stock ammo, despite CE_AutoEnableTrade being on pretty much all the ammo tags
- Trade volumes copied over from Royalty base and caravan traders as I decided it would be the closest match to the Grimworld traders
- Trade volume for ammo for the orbital Rogue Trader copied from the orbital combat supplier
=> Grimworld Multi-patch - Traders

LoadFolders.xml, ModPatches/Huscarl - Power Armor/Patches/Huscarl - Power Armor/Huscarl_Armor.xml, SupportedThirdPartyMods.md
- Patch for [Huscarl Armor mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3427511463&searchtext=huscarl).
- Spacer power armor + helm
- Gambeson
Closes #3712 
- Power armor patched as slightly cruder than vanilla power armor, per mod description.
- Stuffable, though most armor from a base stat value to avoid too much disparity in armor values due to material.
- Slightly inferior bonuses and protection in exchange for being slightly cheaper and higher HP.
- Gambeson the same as CE Armor stats, but only covering torso.
- Different balancing scheme.
=> Patch Huscarl Armor

ModPatches/Dark Ages - Medieval Tools/Patches/Dark Ages - Medieval Tools/MeleeMedieval.xml
CE patch Guard Baton, a Medieval stun baton
CE patch Dark Ages: Medieval Tools  weapon "Guard Baton"
Kept stun ability
Added normal CE defs based on other tools already patched and other "stun" weapons CEed
No Changes sides CE additions to existing patchs/items
No Mod Request at the time of patch
Noticed it wasnt patch after it got added, been trying to clean up and figured id give this a update
N/A
=> Update MeleeMedieval.xml to include new Guard Baton

Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs, Source/CombatExtended/CombatExtended/Loadouts/GameComp_LoadoutManager.cs, Source/CombatExtended/CombatExtended/Loadouts/Loadout.cs, Source/MultiplayerCompat/MultiplayerCompat/MultiplayerCompat.cs
- sync Loadout using its uniqueID instead of its index in the Loadout list
- had to make public reading the uniqueID and getting a loadout by id, as the multiplayer sync workers live in another dll
- sync loadout label on every label change instead of on current loadout change or window close
Tested it a bit, and it seemed the desyncs were related to a combination of:
- label sync is infrequent
- the loadouts are synced by index
- the loadouts are sorted by label
=> Fix multiplayer desyncs related to the Loadout manager

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileStaticCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCEOneUseStatic.cs
- Added MPSyncMethodAttribute to Verbs that override `OrderForceTarget`
- For MP normally we sync every `OrderForceTarget` of ITargetingSource classes.  Seems Sokyran forget to sync this.
- If these are not patch, you are not able to use things that related. e.g. You'll get nullpointer error when trying to use Disruptorflarepack with CE.
=> Fix Mp compat about StaticVerbs

Source/CombatExtended/CombatExtended/AI/Toils/Toils_CombatCE.cs, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_BipodDisplay.cs, Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_Magazine.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs, Source/CombatExtended/Harmony/Harmony_Verb.cs
- more compatiblity with [RW-Modularization Weapon](https://github.com/RW-NodeTree/RW_ModularizationWeapon)
- Add checker befor get stat, reduce systemic differences betwen vanilla.
- If there has not only one props in `ThingDef.verbs`, it will let weapon use error parm. because stat value can only has one value in def.
=> Check WeaponPlatform before get stat

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Ambient sustainer no longer spawns if the map is null
- CIWS dummy projectile spawns sustainer for each iteration (causing lag spike)
- Mark projectile as dummy instead of checking map (in case we need to spawn sustainer without map)
=> Do not spawn sustainer for projectiles that do not belong to any map

Source/CombatExtended/CombatExtended/Building_AmmoContainerCE/Building_AutoloaderCE.cs
Made the find-turret code in autoloaders separate and virtual
Just in case I or someone else decided to make an autoloader that doesn't always load every adjacent turret, instead with different logic.
=> Virtualize autoloader target acquision

LoadFolders.xml, ModPatches/Vanilla Prestige Specialist Armours Reworked/Patches/Vanilla Prestige Specialist Armours Reworked/Apparel_Armor.xml, SupportedThirdPartyMods.md
[Vanilla Prestige Specialist Armours Reworked](https://steamcommunity.com/sharedfiles/filedetails/?id=3246196440)
Recycled the patch for [Prestige Specialist Armor](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/ModPatches/Prestige%20Specialist%20Armor/Patches/Prestige%20Specialist%20Armor/Apparel_Armor.xml) because they're both forks of the same mod and share the same defNames. This patch is nearly identical to the original, with only a few updated xpath arguments to get it working.
- Add mod to LoadFolders.xml
- Add patch to ModPatches/ModName/Patches/ModName as outlined in wiki
- Change to recycled patch: replaced xpath `@Class="CompProperties_Reloadable"` with `@Class="CompProperties_ApparelReloadable"`.
=> Patch - Vanilla Prestige Specialist Armours Reworked

ModPatches/Vanilla Weapons Expanded - Non-Lethal/Defs/Vanilla Weapons Expanded - Non-Lethal/40mmLessLethal.xml, ModPatches/Vanilla Weapons Expanded - Non-Lethal/Patches/Vanilla Weapons Expanded - Non-Lethal/NonLethal_Grenades.xml
change the damage from VWENL_TearGas to Smoke
https://discord.com/channels/278818534069501953/630624305947869184/1356656090745671860
the VWENL_TearGas damage one shot pawns and cause error
make a CE damage and armor type of gas.
=> VWENL gas damage fix

LoadFolders.xml, ModPatches/Grimworld Heresy Addon/Patches/Grimworld Heresy Addon/CE_Patch_Armors.xml, ModPatches/Grimworld Heresy Addon/Patches/Grimworld Heresy Addon/CE_Patch_Armors_Backpacks.xml, ModPatches/Grimworld Heresy Addon/Patches/Grimworld Heresy Addon/CE_Patch_Armors_Helmets.xml, SupportedThirdPartyMods.md
- Patch for the Grimworld 40k Heresy Armor Addon
- Patches for three sets of armors and helmets + two backpacks.
- Close #3652 
- Patched along similar lines to Angels of Death armor that have similar vanilla values, with slight changes to exact armor value and night vision capability. Otherwise, functionally the same.
- Different balancing scheme.
=> Patch Grimworld Heresy Addon

ModPatches/Nukes/Patches/Nukes/IEDs_Nuclear.xml, ModPatches/Nukes/Patches/Nukes/Projectiles_Nuclear.xml
- Add shelling props to Nuke mortar shells. Gave them damage in line with the anti-grain shell.
- White space housekeeping.
- Closes #3747 
- The most straightforward approach.
- Could split up the operations a bit more to individualize shelling damage.
=> Nukes Patch Update

LoadFolders.xml, ModPatches/Cursed Guns/Patches/Cursed Guns/CursedGuns.xml
- Fixed the Cursed Guns CE loadfolders patch only activating on the outdated version from 1.3 and not the unofficial 1.5 version
- Cursed guns go brrr
- I want cursed guns in CE
=> Cursed Guns Loadfolder fix

ModPatches/YetAnotherProsthetics - Core/Patches/YetAnotherProsthetics - Core/Patches/Bionics_Patch.xml
The bionic jaw was removed from the mod as Tynan added a bionic jaw to the base game in 1.5.
=> Update 'Yet another prosthetic expansion mod - Core' patch

Patches/Core/Stats/Stats.xml
- Turns patch conditional to prevent patch errors
- Some mods such as Pandora's Framework are also removing this node. Leading to patching errors in log.
- Harmless, but annoying error
=> Conditional PatchRemove ArmorRatingBase MaxValue

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Severely reduces item clutter from tribal raids by checking the Region where reusable projectile impacted for existing stacks of that ammo
Demo:
https://discord.com/channels/278818534069501953/356498503847116801/1363145502723407902
- Cluttered fields with items look ugly and obsturct vision. If cinematic effect is needed, I'd much rather redo it via flecks.
- Check nearby cells manually instead of using regions
- perhaps, if an existing stack is found, could increment its stackcount without spawning a Thing?
=> Use regions to spawn reusable ammo on existing stacks

Defs/ThingDefs_Items/Items_Turrets.xml, Defs/ThingDefs_Items/Items_Unfinished.xml
none
added industrial tech level to minified turrets.
discord bug channel
Medieval 2 loot table look in trader inventory to spawn loot when it's a thing that can't be spawned on shelves map gen fails, add tech level is fastest to fix this issue on CE side.
idk
=> Medieval 2 map gen fix

ModPatches/Vanilla Genetics Expanded/Patches/Vanilla Genetics Expanded/CE_Patch_DamageDef.xml
a patch for two damages that ignore armor, gave them blunt armor category
Edit: that didn't work... switch to set their parent node to bomb
discord Troubleshooting channel
toxic explosion is still explosion 
=> Vanilla Genetics Expanded fix for damages ignore armor 

Source/CombatExtended/CombatExtended/Lasers/LaserBeamCE.cs
- Beams with off-screen origin now use their destination cell as their in-map position
- Would be good to have with https://github.com/CombatExtended-Continued/CombatExtendedArmory/pull/111
- The game culls rendering for objects that aren't in view of the camera, and since the position of the beam was set to the origin it made lasers invisible when shot off-screen
- Dynamically calculate the visible cell of the beam to account for situations where both the origin and the destination are off-screen
=> Fix off-screen laser rendering

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Fixes an edge case where arrows impact method breaks because they flew inside between 2 walls and there is no region there.
- Contributes towards #3789 
=> Check for null region for reusable projectiles

ModPatches/FSF Advanced Bionics Expansion/Patches/FSF Advanced Bionics Expansion/HediffDefs/FSFAdvancedBionics_AddedParts.xml
Copies the Advanced Power Arm's melee attack definitions and assigns them to the Advanced Power Leg, so that it doesn't produce a Null Reference Exception and dissapear during regular play.
Since in the mod, the Advanced Power Arm and Advanced Power Leg have the exact same stats, I just copied over the existing patched melee attacks to the leg bionic.
- [] Compiles without warnings
Tested by modifying the XML locally and seeing the leg attack properly and not dissapear.
This is my first time attempting a CE patch so I am not sure if a pure XML change like this needs another kind of test? Do I need to compile it somehow? Please let me know if anything is lacking or wrong, thank you.
=> Bugfix - Advanced Bionics Expansion -  Advanced Power leg

Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- The barrel ext getter in LaunchProjectileCE now null-checks the equipment source, for attacks made without a weapon.
- Closes #3814 
=> Add null-check to barrel offset extension

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_CIWS.cs, Source/CombatExtended/CombatExtended/Verbs/VerbCIWS.cs
- Removed isCIWS field
- Moved CIWS projectile destroying to ProjectileCE_CIWS
- CIWS projectile must use ProjectileCE_CIWS (or subclass)
- Less checks for regular projectiles
=> CIWS projectile destroying changes

ModPatches/Rimsenal - Spacer Faction Pack/Patches/Rimsenal - Spacer Faction Pack/Explosives_Smart_CE.xml
- Added tools to smart grenades from Rimsenal spacer
- Fixes #3559 
- We patch vanilla nades to have tools
=> Add tools to Rimsenal smart grenades

About/About.xml, Source/CombatExtended/CombatExtended/Controller.cs, Source/CombatExtended/Version.cs
Logs version information, including partial commit hash, on startup.
Mod versions aren't otherwise logged. Sometimes someone comes by with a local compiled version, or an *ancient* copy of CE, requesting help.  Logging the version info, including the ability to identify PR snapshot versions, will reduce the friction identifying old or broken installs.
=> Log version info on startup

Defs/ThingDefs_Misc/Apparel_Carrying.xml
- Gives the Powered Exoframe a +0.15 weapon handling increase to represent assistance in recoil and sway management thanks to the electronic servos and motors, similar to what we already do with power armor.
- Description tweaked to reflect this change.
https://discord.com/channels/278818534069501953/700236703180259358/1346990607939407934
Basically, the exoframe sits in a weird niche place where its only real purpose is to aid in carrying heavy weapons from other mods before power armor or bionics are unlocked. This change gives it a more universal reason to be used, sacrificing potential outer layer protection for an increase in handling (along with the previous benefits to carry weight).
Power armor is still better in every way, providing the same carry weight and handling bonuses …
=> Add Weapon Handling Stat Buff to Powered Exoframe

Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs
- Fixes duplicate float menu while on ambush map
- Forcing true bypasses vanilla float menu without removing it's code
- Closes #938 
- Closes #1277
- Duplicate float menu
=> Fix Duplicate Float Menu

ModPatches/Outer Rim - Galactic Empire/Patches/Outer Rim - Galactic Empire/Outer_Rim_Galactic_Empire_Apparel.xml, ModPatches/Outer Rim - Galactic Empire/Patches/Outer Rim - Galactic Empire/Outer_Rim_Galactic_Empire_Ranged_Weapons.xml
Patches the new E11D rifle and Stormtrooper Kama in the `Outer Rim: Galactic Empire` module. No other added content required patching thanks to the use of abstracts. Need to doublecheck the new pawnkinds but this is otherwise good to go.
The E11D is basically the E11 but slightly better, at the cost of increased weight and bulk; longer barrel and extended stock makes it more accurate, more stable, and very slightly longer ranged, whilst its CQB focus means longer bursts and slightly better warmup/cooldown times.
https://starwars.fandom.com/wiki/E-11D_blaster_carbine
=> Outer Rim Patch update

ModPatches/A Rimworld of Magic/Patches/A Rimworld of Magic/Patch_Ranged.xml, ModPatches/Alpha Genes/Patches/Alpha Genes/ThingDefs_Misc/WeaponsRanged_Forsaken.xml, ModPatches/Black Widows/Patches/Black Widows/ThingDefs_Weapons/Patch_Weapons.xml, ModPatches/DD Elves/Patches/DD Elves/ThingDefs_RangedWeapon.xml, ModPatches/EdoThemedExpansion/Patches/EdoThemedExpansion/EdoTheme_Weapons_Ranged.xml, ModPatches/Infinity Rim Ariadna/Patches/Infinity Rim Ariadna/Weapons/AntipodeWeapon.xml, ModPatches/JDS Castle Walls/Patches/JDS Castle Walls/ThingDefs_Tower.xml, ModPatches/Kijin 3.0/Patches/Kijin 3.0/ThingDef_Misc/Kijin_Weapons_Ranged.xml, ModPatches/Medieval Overhaul/Patches/Medieval Overhaul/ThingDefs_Misc/Weapons/MO_Weapons_Ranged.xml, ModPatches/MorrowRim - Bloodmoon/Patches/MorrowRim - Bloodmoon/Hunter_Weapons.xml, ModPatches/Nyaron/Patches/Nyaron/ThingDefs_Misc/Weapons.xml, ModPatches/Outland - Eastborn/Patches/Outland - Eastborn/Eastborn_WeaponsRanged.xml, ModPatches/Possessed Weapons/Patches/PossessedWeapons_RangedPatch.xml, ModPatches/Profaned/Patches/Profaned/ThingDefs_Misc/Weapons/Profaned_Weapons_Ranged.xml, ModPatches/Rim-Elves/Patches/Rim-Elves/Weapons_Elves.xml, ModPatches/RimFantasy - House Doyle/Patches/RimFantasy - House Doyle/Patch_RFDoyle_Ranged.xml, ModPatches/Rimcraft Weaponry/Patches/Rimcraft Weaponry/Patch_WOW_Ranged.xml, ModPatches/Rimmu-Nation - Weapons/Patches/Rimmu-Nation - Weapons/RNW_CE_Patch_Ranged_Misc.xml, ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Ranged_CE.xml, ModPatches/Royal Arsenal/Patches/Royal Arsenal/Things/RoyalArsenal_Ranged.xml, ModPatches/T's Samurai Faction/Patches/T's Samurai Faction/T_Samurai_Weapons_Ranged.xml, ModPatches/Tribal Warrior Set/Patches/Tribal Warrior Set/TribalWarrior_Apparel.xml, ModPatches/Vanilla Factions Expanded - Medieval 2/Patches/Vanilla Factions Expanded - Medieval 2/ThingDefs_Misc/Weapons/VFEM2_Weapons_Ranged.xml, ModPatches/Vanilla Weapons Expanded/Patches/Vanilla Weapons Expanded/Industrial_Ranged.xml, ModPatches/Vanilla Weapons Expanded/Patches/Vanilla Weapons Expanded/Neolithic_Ranged.xml, Patches/Core/ThingDefs_Misc/Weapons_RangedNeolithic.xml, Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs
- Adds magazine size override to all bows of 5. Pawns will pickup to max of 20 arrows (override size * 4)
- Adds magazine size override check to checking for low ammo when magazine size = 0. This allows pawns with bow to automatically find and pickup arrows similar to other ranged weapons. Also, stops constant searching for ammo that was happening under the hood.
- Closes #2789 
- Other ranged weapons pick up ammo automatically
- Sad archers
=> Fix arrow pickup

Defs/RecipeDefs/Recipes_Production.xml
- What it says on the tin, added 5x16mm and 8x40mm mech ammo types to reclaim and recycle recipes.
- None shall go to waste, those ammo types can potentially drop from modded mechs.
- 5x50mm caseless too, but that doesn't have plasteel in it and would be a bit exploity?
=> Update mech ammo reclaim recipes

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs
- Removes white space at end of CompAmmoUser.TransformLabel
- Closes #2726
- Fixes issue of picking up warcasket guns. Extra white space was preventing a Contains check that VE team was doing on the float option menu from properly matching.
- Transpile VE HeavyWEapon harmony patch to Trim the label
- Open PR on VE team to see if they will fix it on their end
=> CompAmmoUser Remove Whitespace

Source/CombatExtended/CombatExtended/Comps/CompAmmosetSwitcher.cs
- Switching to UBGL for the first time initializes the selected ammo type to the first option, imitating CompAmmoUser's initialization
- Technically closes #3459 
- The bug only happens if using the devmode option to fill the magazine. Loading it using ammo items doesn't cause it and using the devmode option after that also works as intended.
=> Init a default UBGL ammo def

Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs
- Move item.Label.short into the translation string for when there is no path to an item
- Closes #3384
- Failing translation
- Move away from vanilla translation key
=> Fix CannotPickUp translation

ModPatches/Gas Traps and Shells/Patches/Gas Traps and Shells/Patch_Buildings_GasTrap.xml, ModPatches/Nukes/Patches/Nukes/IEDs_Nuclear.xml, ModPatches/Outer Rim - Core/Patches/Outer Rim - Core/Outer_Rim_Core_Mines.xml, ModPatches/Remote Detonator/Patches/Remote Detonator/Remote_Detonator_CEpatch.xml, ModPatches/Vanilla Factions Expanded - Deserters/Patches/Vanilla Factions Expanded - Deserters/Things_Security.xml, Patches/Core/ThingDefs_Buildings/Buildings_Security.xml, Source/CombatExtended/CombatExtended/SuppressionUtility.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Allows them to be shot and remotely triggered by giving them a fillPercent to interact with CE bullet system
- Add fillPercent of 0.01 to vanilla mine abstract. 
- Adds fillPercent to patched modded mines that do not use vanilla base class as parent.
- Changes cover code to prevent Building_TrapExplosive from being appropriate cover
- Changes shooting to prevent Building_TrapExplosive being calculated as cover
- Closes #2887 
- Building is meant to be able to be triggered via bullets.
- Only added fillPercent to patched mines that had triggers tied …
=> Fix IED shootability

Source/CombatExtended/CombatExtended/Comps/HediffComp_Venom.cs
- Scars no longer build up venom, as it was unable to be tended.
- Additionally changed the lifetime and venomPerTick values to be saved.
- Permanent comp lookup is cached by Viral's suggestion
- Related report: https://discord.com/channels/278818534069501953/303988654492090370/1366153391893385388
=> Stop scars from applying venom buildup

README.md
- Fixed stray underlined spaces from the image links in readme file.
- These things between buttons:
- Whitespace collapsing turns any newlines between tags into single spaces, avoided by putting the closing tags inline.
=> Fix stray whitespace in readme image links

Defs/Ammo/Advanced/8x35mmCharged.xml, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_CIWS.cs, Source/CombatExtended/CombatExtended/Verbs/VerbCIWS.cs
CIWS projectiles are drawn with the same 57 degree camera projection.
Draw all projectiles' rotation based on its actual movement, once we have it. Falling back to a reasonable estimate before the projectile first moves.
Currently, CIWS projectiles are drawn using a top-down perspective, without distance scaling.  This makes it impossible to judge their height visually, hides their shadows, and makes them *look* like they are skimming across the ground.  Since we want them to visually intercept projectiles at the same time as they mechanically intercept them, they need to be drawn with the same camera properties as their target.
Change the camera perspective for all projectiles.
Let them look odd.
Once we are satisfied with how skyfallers are drawn, CIWS projectiles targeting skyfallers …
=> Draw CIWS Projectiles using standard camera perspective. 

Defs/Ammo/Other/Flare.xml, ModPatches/Vanilla Weapons Expanded - Bioferrite/Defs/BioferriteFlare.xml
- Fixes texture path errors that were happening when VWEB is loaded
- Removes patches' ammo item and uses the one from base ce instead.
- Uses projectile like our flaregun uses instead of the hand thrown one. Had to make a duplicate projectile def, because the existing one relies on mortar charges system
- Fixes this [issue ](https://discord.com/channels/278818534069501953/994681225262415902/1368998431351115879)
- Handthrown projectile looks goofy
=> Fix VWE-Bioferrite flare rifle ammo

LoadFolders.xml, ModPatches/Fantasy Metals Reforged Forked/Patches/Fantasy Metals Reforged Forked/CE_Patch_FantayMetalsReforged.xml, SupportedThirdPartyMods.md
- Patches metals partially based on the original mod
- Mithril changed to match Plasteel as the modder specifically calls it out to being equal
- Heat Armor to 0 like other metals
- Add melee armor penetration like plasteel/uranium
- Defnames changed in the forked version
-  Original mod will still technically work being a purely XML and relatively simple
- Completely overwrite the original
=> Patch Fantasy Metals Reforged Fork

Defs/Ammo/HighCaliber/23x115mm.xml, Defs/Ammo/HighCaliber/27x145mmMauser.xml, Defs/Ammo/HighCaliber/30x170mm.xml, Defs/Ammo/HighCaliber/35x228mmNATO.xml
- New ammo types added in the now closed #3792.
- Stat fixes and correction for the 27mm Mauser ammo.
- https://docs.google.com/spreadsheets/d/1P9U8EtYoRBh-jPMPmXcqam1O3qvKZPMml2ktAMPssOk/edit?gid=1393347070#gid=1393347070
- Even though I dislike the main mod getting cluttered with new ammo types that are not going to get widely used, 27mm Mauser was added without resistance so ¯\_(ツ)_/¯. If it's getting done, then it has to be done properly.
- Both 27mm Mauser and the newly added ammo in the aforementioned PR needed adjustments and corrections based on proper citations.
- Remove/revert 27mm Mauser.
=> Ammo housekeeping and additions

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectilePropertiesCE.cs
The legacy `lerpPosition` flag is re-added to ProjectileCE for downstream mods referencing it. It will be expunged when 1.6 drops.
- Closes #3862 
Some mods, at least Bill's, reference the lerpPosition field to determine how some of their projectiles behave. So we need to make it a field they can reference until the last mod depending on it is updated.
Break other mods.
=> re-add lerpPosition to ProjectileCE for legacy compatibility

Source/CombatExtended/CombatExtended/PatchOperationMakeGunCECompatible.cs
Log which defName is missing when a `PatchOperationMakeGunCECompatible` fails
The native logging only reports the file. In large patch files, it can take a bit to find the offending defName.
=> Log the missing defName when our patch operation fails

ModPatches/FSF Vanilla Bionics Expansion/Patches/FSF Vanilla Bionics Expansion/HediffDefs/FSFBionics_AddedParts.xml
The FSFBionicJaw hediff was removed from [FSF] Vanilla Bionics Expansion in 1.5. All I've done is remove the patch that creates a harmless red error at startup.
=> Remove deprecated FSFBionicJaw patch from [FSF] Vanilla Bionics Expansion

ModPatches/DD House Sanguin/Patches/DD House Sanguin/Mods/Medieval Overhaul/PawnKinds_MO.xml
Apologies for the duplicate PR, I unintentionally closed the previous one while doing some housekeeping on my end.
Adds a FindMod check to the Medieval Overhaul-specific patches in House Sanguin. The check is present in the [bloodwine patch](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/ModPatches/DD%20House%20Sanguin/Patches/DD%20House%20Sanguin/Mods/Medieval%20Overhaul/Bloodwine_MO.xml), but not this one. Without this check, users with House Sanguin but not Medieval Overhaul will get harmless red errors about a patch failure.
=> Add Medieval Overhaul check to House Sanguin/MO patch

Defs/Ammo/Other/Flare.xml
- What it says on the tin, the recipe output was incorrectly set to normal flares and not caught.
- Suffer the goof.
=> Bioferrite flare recipe output fix

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/TrajectoryWorkers/LegacyTrajectoryWorker.cs
Added LegacyTrajectoryWorker that moves by querying projectile positions.
Projectiles that override Vec2Position now use the LegacyTrajectoryWorker
Special-casing the default trajectory worker makes for messier code with worse performance.
This keeps the cost relatively low, as the result is cached and early-outs for modern projectiles.
Require explicitly opting into the legacy worker.
Require mods to move away from legacy code paths.
=> Add LegacyTrajectoryWorker for projectiles that override Vec2Position

Defs/Ammo/Other/Flamethrower.xml, Defs/Ammo/Rocket/RPG7.xml, Source/CombatExtended/CombatExtended/Comps/CompThrownFleckEmitterSmooth.cs
- Adds a `<startDelayTick>1</startDelayTick>` field to skip creating certain flecks before a certain tick
- Sets this field to skip the first tick by default
- Projectiles like flamethrower fuel and RPG-7 rockets use this and look weird, because projectiles are launched from the center of the pawn, and firey flecks are left on the pawn itself. Since making projectiles spawn at gun's end is problematic, this is a quick fix that will be also useful for doing different visual effects. 
- Serina wanted to use this to make blackpowder guns emit smoke flecks
- Before and after:
- Make projectiles appear at gun barrel position …
=> Add starting delay to projectile fleck emitter

ModPatches/Anty the war Ant/Defs/Anty the war Ant/Ammo_Anty.xml, ModPatches/Anty the war Ant/Patches/Anty the war Ant/Ammo/Ammo_Anty.xml, ModPatches/Anty the war Ant/Patches/Anty the war Ant/ThingDefs_Misc/Anty_Apparel.xml, ModPatches/Anty the war Ant/Patches/Anty the war Ant/ThingDefs_Misc/WeaponsP.xml, ModPatches/Anty the war Ant/Patches/Anty the war Ant/ThingDefs_Races/AlienRace_Anty.xml, ModPatches/Anty the war Ant/Patches/Anty the war Ant/ThingDefs_Races/Race_Proty.xml
=> Anty patch fixes and update

ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MatureFleshbeast.xml
- Adds back swallow ability to Fleshbeast
- Closes #1206 
- Testing shows at least for the flesh beast the swallow is working and is not insta killing pawns
- Leave it be
=> Add Flesh Beast Swallow

Source/CombatExtended/CombatExtended/MoteMakerCE.cs
- Adds null check for map on MoteMaker
- Closes #3868 
- May Close #3750
- Motemaker was throwing constant errors when killing TriSpike in numerous ways as the corpse gets fully destroyed.
- Easily replicated with using VPE KillSkip on a tripspike
- Prevents constant error spam
=> Fix NRE MoteMaker

ModPatches/Vanilla Weapons Expanded - Bioferrite/Patches/VWE_BioferriteRanged.xml, Source/CombatExtended/CombatExtended/Comps/CompAmmosetSwitcher.cs
- Fixes burst fire option availability due to burstShotCount equaling aimedBurstShotCount during CompFireModes.InitAvailableFireModes
- Closes #3341 
- Annoying warning
- Missing gizmo option is bad player experience
- Completely change shooting when underbarrel is active
=> Fix Full Auto Underbarrel Burst Fire Gizmo

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Check if projectile already inside target bounds
- Slow projectiles may miss the target even if projectile is already inside the target - `dist * dist > (ExactPosition - LastPos).sqrMagnitude` fails there due to low speed of bullet 
=> Check if projectile already inside target bounds

ModPatches/RH2 Faction - VOID/Defs/RH2 Faction - VOID/ShellingResponse_VOID.xml, ModPatches/RH2 Faction - VOID/Patches/RH2 Faction - VOID/FactionDefs/Factions_VOID.xml, ModPatches/RH2 Faction - VOID/Patches/RH2 Faction - VOID/ThingDefs_Buildings/CE_VOID_PowerCell.xml, Source/CombatExtended/CombatExtended/DefOfs/CE_AmmoCategoryDefOf.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_VOID.cs
- Adds code to check and respawn turrets as proper class
- Maxes ammo for turrets
- Makes ammo as AP-HE as VOID is supposed to be top tier
- Changes Void power cell to 2000kw due to power changes in CE turret's. This maintains the integrity of the power network and all the turrets to be powered.
- VOID base turrets will not shoot lacking ammo and improper thing class
- Due to unique spawning code of VOID code requiring destroying turrets as they will spawn with wrong ThingClass and respawning them
- Void Power Cell is worth 100k silver normally for 1kw power cell, while vanilla Vanometric power cell is 1200 silver for 1kw. Adding extra 1000 watts of power to maintain turrets, won't …
=> Fix VOID base turrets ammo

Royalty/Patches/PawnKindDefs_Royalty/PawnKinds_Royalty.xml, Source/CombatExtended/CombatExtended/DefUtility.cs, Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs
- Adds ability to force pawnKindDef shields to generate with select material
- Shield setColor according to their pawnKindDef apparelColor
- Filter resolved during startup so not to have any impact during play
Example:
```
<li Class="CombatExtended.LoadoutPropertiesExtension">
<shieldMoney>100~350</shieldMoney>
<shieldTags>
<li>Shield</li>
<li>BiggerShield</li>
<li>BiggestShield</li>
</shieldTags>
<forceShieldMaterial>true</forceShieldMaterial> 
<shieldMaterialFilter>
<thingDefs>
<li>WoodLog</li>
</thingDefs>
<categories>
<li>Steeled</li>
</categories>
</shieldMaterialFilter>
<shieldChance>0.35</shieldChance>
</li>
```
- Ability to force material requirements bring shield generation …
=> Forced Shield Material/Color

Defs/ThingDefs_Misc/Things_Special.xml, Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/Projectiles/ArtilleryMarker.cs
- Adds a tooltip when hovering above an artillery marker that shows stats of the marker.
- Adds expiration time to marker's label in bottom left; and to pawn's bottom left menu when marker is attached to pawn.
- It was difficult to understand how much of a bonus a particular arty marker gives.
- Shows aiming accuracy, because it comes from pawn skill, and sight efficiency, because it comes from binocular quality.
- Marker also affects weather and light shifts, but I didn't include those into the tooltip, because during inter-tile bombardments, those stats are disregarded and replaced with a fixed value.
- Include weather …
=> Add tooltip to artillery marker

Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs, Source/CombatExtended/CombatExtended/Jobs/JobDriver_Reload.cs
Reloading held weapon will try to use multiple stacks of ammo if needed.
-some weapons have more magazine capacity than ammo item stack count.
Tune every ammo's stack count higher, only to run across weapon with even higher stack count.
=> Multi stack held weapon reloading

ModPatches/Vanilla Quests Expanded - Cryptoforge/Patches/Vanilla Quests Expanded - Cryptoforge/VQEC_Things_Sentry.xml
Patch the turrets and landmine for VQE Cryptoforge
the turret shield mechanic is done via thingclass which is patched so turret HP got timed 1.35
the shield have 35% chance of mitigate common ranged damages, so timed HP by 1.35
add a damage reduction for common ranged damages by the same amount
C# patch a thingclass that's used by total of two buildings
=> Patch security buildings for VQE Cryptoforge

Defs/Ammo/Pistols/357Magnum.xml, Defs/Ammo/Pistols/38Special.xml, Defs/Ammo/Pistols/44Magnum.xml, Defs/Ammo/Pistols/44SWSpecial.xml, Defs/Ammo/Pistols/454Casull.xml
- Added high velocity projectiles for rifles chambered in the above calibers.
- Renamed .44 S&W Special to simply .44 Special for consistency and length (We don't call .38 Special .38 S&W Special).
- Certain multicaliber AmmoSets renamed to include their other calibers.
https://docs.google.com/spreadsheets/d/1zlzjPXKY7beHLDCz6aLD-oU9xroHybU1WpcJnrpV9qc/edit?gid=1393347070#gid=1393347070
- We have high-velocity AmmoSets for .44 Magnum but none for the others.
- 357_HV is used by bolt-action rifles such as the Ruger 77, 357_Lever is obviously used by lever actions, which explains the need to distinguish them.
- I'm not aware of any .38 Special or .44 Special rifles that aren't also able to chamber their magnum counterparts, so their HV projectiles are only included by the bigger …
=> High Velocity AmmoSets for .357 Magnum, .38 Special, and .44 Special

ModPatches/RH2 Helldivers Super Firearms/Defs/RH2 Helldivers Super Firearms/20mmPhoenix.xml, ModPatches/RH2 Helldivers Super Firearms/Defs/RH2 Helldivers Super Firearms/80mm_Ultimatum.xml
- Added particle trails and SFX to 20mm Phoenix rounds, and changed sprite to one found in the Super Firearms mod
- Added prometheum splatter to 20mm Phoenix APHEI and changed its explosion sound
- Added increased suppression and danger factors to 80mm Ultimatum rounds
- Makes 20mm Phoenix rounds more distinctive when in flight
- Improves utility of 20mm APHEI rounds
- Makes it so pawns are "smarter" and more likely to run away from incoming Ultimatum shells that will otherwise probably obliterate them
=> HD2 Firearms Tweaks

ModPatches/Vanilla Factions Expanded - Ancients/Patches/Vanilla Factions Expanded - Ancients/ThingDefs_Sentry.xml, Royalty/Defs/ThingDefs_Buildings/Weapons_Turrets.xml, Royalty/Patches/ThingDefs_Buildings/Buildings_Mechanoid.xml, Source/CombatExtended/CombatExtended/Things/Building_CIWS_CE.cs
- Allows the following turrets to function as CIWS turrets:
- VFE: Ancients Point Defense
- Royalty Mech Charge Blaster turrets to function as CIWS.
- Some whitespace changes.
- It only makes sense that the VFE turret be able to function as a CIWS turret, give that the base mod allows it to engage shells and drop pods. Is effective against shells, but 5.56mm isn't as good at destroying pods in-flight.
- Allowing the mech blasters to engage incoming drop pods and shells increases the threat they present, making it more difficult to simply shell them from afar.
- Don't, I guess?
=> CIWS Turret Implementation

About/About.xml
Avoid Friendly Fire's mod Id is removed from the incompatiblity list.
Avoid Friendly Fire is TPS heavy, but works without errors with CE. It's TPS heavy without CE too. It's friendly-fire avoidance code is more robust than ours, which can be important for some players.
Encourage people to ignore red errors in their mod list, because compatible mods are marked incompatible.
It may be worth adding an entry to the learning helper, suggesting disabling it for drafted colonists in the late game. It has a mod option to do exactly that.
=> Remove Avoid Friendly Fire from incompatibility list

Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs, Source/CombatExtended/CombatExtended/Comps/CompProperties_ExplosiveCE.cs
Adds prop for screenShakeFactor in CompProperties_ExplosiveCE and uses it when it generates an explosion, allowing for comp explosions to alter the level of screenshake like regular projecitle explosiosn do
Assists with feature parity for CompProperties_ExplosiveCE.
=> Add screenshake field in CompProperties_ExplosiveCE

Source/CombatExtended/CombatExtended/Jobs/JobDriver_Stabilize.cs, Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs
- Pawn faces patient if north spot is blocked
- Checks if pawn is carrying medicine when called to stabilize and will use that if no better medicine in inventory. Can be checked by creating a storage zone and tell pawn to haul medicine. While carrying the medicine in arms to storage you can tell it to stabilize and it will drop the stack and take one medicine to the pawn in need.
- Pawn carries medicine instead of dropping.
- Carried medicine is destroyed if patient dies between hediff stabilization or job interrupted after stabilizing first hediff on patient
- Pawn checks if carrying medicine (This is in addition to the inventory)
Links to the associated issues or other …
=> Fix Stabilization Issues

ModPatches/Vanilla Furniture Expanded - Security/Defs/Vanilla Furniture Expanded - Security/Ammo_Security.xml
Changes the EMP Cannon from VFE: Security to use the EMP Explosion SFX, rather than the generic HE/Mortar Explosion.
It's an EMP AOE weapon, it should sound like other EMP AOE weapons.
EMP cannon sounds like a regular HE cannon/mortar, which could cause confusion.
=> VFE Security EMP Cannon SFX

Source/CombatExtended/CombatExtended/ExplosionCE.cs
- Changes explosions to notify all things, not only pawns. Code copied from decompiled vanilla.
- [Discord discussion](https://discord.com/channels/278818534069501953/286486075466317826/1382054540164993096)
- Some things might've wanted to get notified about explosions but got excluded because they were not Pawns, even though base `Thing` does have a `Notify_Explosion()` method
- Vanilla does it this way. Seems like our code got outdated
- Keep things as is.
tested FSX stack explosions, grenades in dev colony.
=> Notify all things about explosions

Languages/English/Keyed/Keys.xml, Source/CombatExtended/CombatExtended/Jobs/JobGiver_TakeAndEquip.cs, Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs
- Changes float menu to check if ammo is cooking off. Prevents picking up if so
- JobDriver_EquipAndReload to check if ammo is cooking off
- Related #687 
- Ammo will now cease cooking off when picked up, but will continue cooking off when set back down. Be it immediately or a year later
- Simplifies the issue, by preventing picking up cooking off ammo
- Make them cook off while in inventory
=> Fix Pickup Cooking Off Ammo

Defs/Ammo/Medieval/BlunderbussShot.xml, Defs/Ammo/Medieval/CannonBall.xml, Defs/Ammo/Medieval/MiniCannonBall.xml, Source/CombatExtended/CombatExtended/Comps/CompThrownFleckEmitterSmooth.cs
- Adds smoke vfx for BP multi pellet projectiles
- Changed `offsetOrigin` field to be a FloatRange instead of Float
- Continuation of #3946, requires that PR
- Fixes [the issues described here](https://discord.com/channels/278818534069501953/310869202892488705/1380932035379462144)
- Quick fix to multipellet projectiles creating too much projectile vfx 
- Will be useful for creating other effects down the line.
- Doesn't break existing xml as FloatRange accepts not only "5~5" input, but input in form of "5" too
Describe alternative implementations you …
=> Randomised origin offset for proj vfx

Defs/Tutor/Concepts_NotedSelfshow.xml, Languages/English/Keyed/BulkAndWeight.xml, Source/CombatExtended/CombatExtended/CE_Utility.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_CheckReload.cs, Source/CombatExtended/CombatExtended/Jobs/JobGiver_UpdateLoadout.cs, Source/CombatExtended/CombatExtended/Loadouts/Dialog_ManageLoadouts.cs, Source/CombatExtended/CombatExtended/Loadouts/FileListDialog.cs, Source/CombatExtended/CombatExtended/Loadouts/GameComp_LoadoutManager.cs, Source/CombatExtended/CombatExtended/Loadouts/ITab_Inventory.cs, Source/CombatExtended/CombatExtended/Loadouts/Loadout.cs, Source/CombatExtended/CombatExtended/Loadouts/LoadoutConfig.cs, Source/CombatExtended/CombatExtended/Loadouts/Utility_HoldTracker.cs, Source/CombatExtended/CombatExtended/ThinkNodes/ThinkNode_ConditionalHasLoadout.cs, Source/CombatExtended/Utilities/CustomWidgets.cs
- Loadouts can inherit slots from a parent loadout
- Loadouts can be marked ad-hoc to auto-manage ammunition
- Loadouts can have auto-removal of undefined items disabled
- Closes #3900 
Allows partial use of loadout system, without breaking taming jobs or simple sidearms or similar mods
Keep doing it via harmony patching in its own sub-mod.
=> Composable and Ad-Hoc Loadouts

ModPatches/Grimworld Angels of Death/Patches/Grimworld Angels of Death/CE_Patch_Shields.xml, ModPatches/Grimworld Hammer of the Imperium/Patches/Grimworld Hammer of the Imperium/CE_Patch_Shields.xml
Patches the Ogryn, Assault, Storm, Primaris, and Salamander Shields in Hammer of the Imperium and Angels of Death.
Listed seperately from the #3836 patch as that one's getting a bit unwieldy and this is more important than balance changes since it patches something that is currently entirely unsupported.
A lot of values such as Bulk are already handled on GW's side via MayRequire, so this really only needs to bring the material strength multipliers up to scratch.
So the shields are usable and not effectively tissuepaper under CE armour strength rules.
Ogryn shield is made equivalent to CE's stock ballistic shield, whilst the Astartes shields are increasingly durable; the unpowered Assault Shield is a little tougher, the powered Storm and Salamander Shields are tougher than that, and the …
=> Grimworld Shields

Languages/English/Keyed/ModMenu.xml, Source/CombatExtended/CombatExtended/ModSettings/Settings.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Mid burst retargeting can be disabled via mod-option menu.
There are several subsystems that interlock in a poor way, but it's too late in 1.5's release cycle to fix them.
This makes working on any of them prone to breaking the others. So while the retargeting is fixed, this adds
a reasonable failsafe in the event it breaks in an akward way after we move to working on 1.6.
Leave it always on and be willing to backport fixes for it for a couple months.
disable it for 1.5
default it to disabled but with a mod option to enable it - it *was* on all the time previously though.
=> Gate retargeting behind mod option in case something breaks

Source/CombatExtended/CombatExtended/Comps/BipodComp.cs, Source/CombatExtended/CombatExtended/ModSettings/Settings.cs
- Fixes NRE in bipod setup when loading from save
- Changes bool check to just straight comp null check
- Fixes menu size for mechanics, as settings were getting cut off
- NRE needs fixing
- Menu needs to be manually adjusted
- Suffer
- Most likely also needs pushed to Master and hotfix released for workshop so 1.5's last vestiges aren't left broken
=> Fix Bipod NRE On Load

Source/CombatExtended/Harmony/Compatibility/Harmony_AlphaGenes.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_BBBodySupport.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_RunAndGun.cs, Source/CombatExtended/Harmony/Compatibility/Harmony_VanillaEventExpanded.cs, Source/CombatExtended/Harmony/HarmonyBase.cs, Source/CombatExtended/Harmony/Harmony_ApparelGraphicRecordGetter.cs, Source/CombatExtended/Harmony/Harmony_AttackTargetFinder.cs, Source/CombatExtended/Harmony/Harmony_AvoidGrid.cs, Source/CombatExtended/Harmony/Harmony_Bombardment.cs, Source/CombatExtended/Harmony/Harmony_CompressibilityDecider.cs, Source/CombatExtended/Harmony/Harmony_DamageWorker_AddInjury.cs, Source/CombatExtended/Harmony/Harmony_ExpandableWorldObjectsUtility.cs, Source/CombatExtended/Harmony/Harmony_Fire.cs, Source/CombatExtended/Harmony/Harmony_FireUtility.cs, Source/CombatExtended/Harmony/Harmony_HediffComp_TendDuration.cs, Source/CombatExtended/Harmony/Harmony_Hediff_Injury.cs, Source/CombatExtended/Harmony/Harmony_JobGiver_AIBreaching.cs, Source/CombatExtended/Harmony/Harmony_PawnColumnWorkers.cs, Source/CombatExtended/Harmony/Harmony_PawnGraphicSet.cs, Source/CombatExtended/Harmony/Harmony_PawnRenderer.cs, Source/CombatExtended/Harmony/Harmony_Pawn_HealthTracker.cs, Source/CombatExtended/Harmony/Harmony_Thing.cs, Source/CombatExtended/Harmony/Harmony_ThingDef.cs, Source/CombatExtended/Harmony/Harmony_TradeUtility.cs, Source/CombatExtended/Harmony/Harmony_Verb.cs, Source/CombatExtended/Harmony/Harmony_VerbTracker.cs, Source/CombatExtended/Harmony/Harmony_Verb_BeatFire.cs, Source/CombatExtended/Harmony/Harmony_Verb_TryStartCastOn.cs, Source/CombatExtended/Utilities/TranspilerCE.cs
- Adds fail error message for transpiler patches
- Allows us to know when a transpiler is failing.
- Silent fail had a patch broken for entire time of 1.5 #4014
- Silent failures
=> Add Fail Message For Transpilers

Source/CombatExtended/CombatExtended/AI/Comps/CompGasMask.cs, Source/CombatExtended/CombatExtended/Things/Smoke.cs, Source/CombatExtended/Harmony/Harmony_GameCondition_ToxicFallout.cs, Source/CombatExtended/Harmony/Harmony_GasUtility_PawnGasEffectsTickInterval.cs
- Tweaks AI of non-colonists to don gas masks when exposed to Toxic Gas
- Tweaks AI of non-colonists to don gas masks when exposed to Toxic Fallout
- Tweaks AI of non-colonists to don gas masks when exposed to Polluted Terrain
- Refactor CompGasMask for minor performance improvements and readability
- Smoke checks for if pawn is Humanlike and not Subhuman. Prevents TryGetComp unnecessarily
- Closes #3982 
- Harmony patches before their target method to mimic Smoke and prevent ill effects
- Removing LINQ prevents unnecessary allocations
- Removes …
=> Fix AI GasMask Wearing

Source/CombatExtended/CombatExtended/Verbs/Verb_MarkForArtilleryCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
- Added checks for downed and colony mech pawns to closer match vanilla skill gain conditions.
- Removed skill gain from binoculars to prevent free skill farming.
- Matches vanilla behavior and prevents farming skill levels by attacking colony mechs using low-pen attacks.
=> Tweak skill xp gain

Source/CombatExtended/CombatExtended/Comps/CompAmmoResupplyOnWakeup.cs, Source/CombatExtended/CombatExtended/Comps/CompArmorDurability.cs, Source/CombatExtended/CombatExtended/Comps/CompInventory.cs, Source/CombatExtended/CombatExtended/Comps/CompSuppressable.cs, Source/CombatExtended/CombatExtended/Comps/CompTacticalManager.cs, Source/CombatExtended/CombatExtended/Comps/CompThrownFleckEmitterSmooth.cs, Source/CombatExtended/CombatExtended/Comps/HediffComp_InfecterCE.cs, Source/CombatExtended/CombatExtended/Comps/HediffComp_Prometheum.cs, Source/CombatExtended/CombatExtended/Comps/HediffComp_Stabilize.cs, Source/CombatExtended/CombatExtended/Comps/HediffComp_Venom.cs, Source/CombatExtended/CombatExtended/Projectiles/ArtilleryMarker.cs, Source/CombatExtended/CombatExtended/Things/AmmoThing.cs, Source/CombatExtended/CombatExtended/Things/Flare.cs, Source/CombatExtended/CombatExtended/Things/IncendiaryFuel.cs, Source/CombatExtended/CombatExtended/Things/Smoke.cs, Source/CombatExtended/CombatExtended/WorldObjects/TravelingThing.cs, Source/CombatExtended/Contrib/MechTakeAmmoCE/Core/CompMechAmmo.cs
- Converted existing ThingComp and HediffComp and some regular ticks to use the new interval ticks system.
- Passed `delta` argument is the number of ticks since last call, so it was used to scale the effects the ticks had.
- This is still largely a blind conversion, so might be missing certain details.
=> Convert comps to interval ticks

Defs/GameSetupSteps/ExplosiveCurveSetup.xml, Source/CombatExtended/CombatExtended/ExplosionCE.cs, Source/CombatExtended/CombatExtended/GameSetupSteps/GameSetupStep_ExplosionCurve.cs, Source/CombatExtended/CombatExtended/GenExplosionCE.cs, Source/CombatExtended/Harmony/Harmony_CompExplosive.cs
- Added a GameSetupStepDef that initializes the default explosion curve.
- Added an argument to GenExplosionCE.DoExplosion to override the falloff curve used.
- Allows the default falloff curve to be patched using xpath.
=> Store default explosion falloff curve in a GameSetupStepDef

ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Atispec.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_EngorgedTentacularAberration.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_Gallatross.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_MoribundGallatross.xml, ModPatches/Alpha Animals/Patches/Alpha Animals/ThingDefs_Races/AlphaAnimals_CE_Patch_Race_UnblinkingEye.xml, ModPatches/Alpha Mechs/Patches/Alpha Mechs/Mods/Biotech/ThingDef_Races/Races_PristineAssembler.xml, ModPatches/The Joris Experience/Patches/The Joris Experience/Unique_Joris_Extended.xml, ModPatches/The Joris Experience/Patches/The Joris Experience/Unique_Joris_Extended2.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Durapod.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Ironclad.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Silverfish.xml, ModPatches/Vanilla Factions Expanded - Insectoids 2/Patches/ThingDefs_Races/Races_Tankroach.xml
This is not a full patch update of any of the involved mods, it is targeting one specific update across multiple mods' patches.
N/A
- Fix references to AnimalBehaviours to now reference VEF.AnimalBehaviours after VFECore restructured to VEF
- Based on Discord bug report https://discord.com/channels/278818534069501953/324222101550661663/1390911920240066642
- namespace has changed
- wait for full 1.6 release of the mods involved before updating patches
=> Update references to AnimalBehaviours to target VEF.AnimalBehaviours

ModPatches/Vanilla Races Expanded - Archon/Patches/Vanilla Races Expanded - Archon/Abilities_Transcendent.xml
Patched VPE for VRE Archon 
increased range and armor pen of the combat Abilities and 
Edit projectiles seems to have full armor pen removing armor pen patch
tests are done on 1.5, when VRE Archon is updated for 1.6 "VFECore.Abilities.AbilityDef" need to be replaced with "VEF.Abilities.AbilityDef"
=> Archon VPE patch

Defs/Ammo/Shell/120mmMortar.xml
Add 120mm Mortar Shell.
If we are to simplify the ammunition for both 120mm smoothbore mortars and rifled mortars into a single type, I personally recommend using the ammunition stats of the 120mm rifled mortar.
Here is ammo sheet:
https://docs.google.com/spreadsheets/d/1jq0Cm8K6Q42wz_0rYNmztumzibAbv0UKjZnpg7fkb3M/edit?gid=1978847997#gid=1978847997
Providing uniformly defined (defname) ammunition for potential mods in the Workshop that may include 120mm mortars, ensuring easy compatibility.
The 120mm mortar ammunition is a highly significant caliber, widely used in various weapons across many nations. This caliber will inevitably be added to CE's Base eventually.
=> Add 120mm Mortar Shell

Biotech/Patches/FactionDefs/Factions_Misc.xml
Added grenadiers and gunners to Savage Impish tribes and Fierce Neanderthal tribes to bring them inline with the human tribal factions they replaced. 
I will follow this up with a similar PR rebalancing Industrial factions raid composition if this gets a thumbs up. I'll also add some actual combat troops to worksites quests so it isn't just entirely people with pocket knifes.
Biotech tribal factions have mostly replaced human tribal factions, but they lack even basic guns or stick bombs, which makes fighting them a generic shooting gallery. Adding them would bring them inline with human tribal factions.
=> Patched Biotech tribal factions to have grenadiers and gunners

Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs
- Pawn's tools get checked for max armor pen incase pawn's tools are bigger pen than their equipment. (E.g. Pawn equippped with Knfie, but has mega pen bionic)
- Fixes NRE if a primary equipment doesn't have tool
- LINQ changed to foreach loops. Reduce overhead and improve readability
- Improve readability with explicit types
- Store skill level in local variable instead repeatedly calculate it
- NRE on CompMeleeTargettingGizmo.finalHeight when primary equipment does not have tools
- Example Weapon is Poison Darts from Alpha Biome
- Calculate all verbs …
=> Fix Melee Target Gizmo

About/About.xml, ModPatches/Alpha Biomes/Defs/Alpha Biomes/Defs_Ammo.xml, ModPatches/Alpha Biomes/Patches/Alpha Biomes/RangedIndustrialGrenades.xml, ModPatches/Alpha Biomes/Patches/Alpha Biomes/Tar_IED.xml
none
change the alpha biome darts to ammo
fix the darts don't stack
and removed AB_ProcessedResin from a recipe
none
it didn't stack before
not fixing it?
=> Alpha biomes darts fix

ModPatches/Rimsenal Core/Patches/Rimsenal Core/Apparel_RS_CE.xml
Problem: Rimsenal Core updated its modular helmet system to require security helmet precursor armor to craft, rather than plasteel directly. Since CE patched the costlist of these helmets, red errors appeared on startup. 
Since the precursor helmets appear to have already been patched by CE, including costs, I just deleted  the part of the CE patch that messed with rimsenal's costs. 
Precursor armors already patched by CE. Deleting the costlist patch seemed just reasonable. 
Suffer, probably
=> Update Rimsenal Core Modular Helmets costlists

Source/CombatExtended/CombatExtended/Projectiles/BulletCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs
- Support for ExtraDamages, DamageDefOverride and IgnoreAccuracyMaluses fields added in the unstable branch.
- Even if we decide to not use the fields as part of Odyssey patching, those are still very likely to be used by other modders and this will let us make future patches easier.
- Unify SecondaryDamage and ExtraDamage into a single system.
=> Preliminary Odyssey support

LoadFolders.xml, ModPatches/Det's Xenotypes - Half-foot/Patches/Det's Xenotypes - Half-foot/Apparel_Headgear.xml, ModPatches/Det's Xenotypes - Half-foot/Patches/Det's Xenotypes - Half-foot/Weapon_Melee_Spacer.xml, SupportedThirdPartyMods.md
Added compatibility patch for the headset and wrench introduced in the new xenotype mod. 
Xenotype itself largely did not appear to need patching. Strangely, I see no way for this xenotype to spawn naturally in the game at least from the xml files itself. (no pawnkinds)
Wrench is comparable to an entrenching shovel, but since it is electrified, I gave it a small stun capability. 
The new headset appears to be comparable to an integrator headset except instead of giving mech bandwidth, it speeds up repair process. I largely copied over the stats given to integrator headsets.
Could've given increased suppression vulnerability to a gene. Could've given bulk penalty to the gene.
However, as the mod itself does not appear to actually change the pawn's bodysize nor mess with carry weight in any …
=> Det's Half-Foot Initial Compatibility Patch

Source/CombatExtended/CombatExtended/Defs/LoadoutPropertiesExtension.cs, Source/CombatExtended/CombatExtended/Defs/WeightedAmmoCategory.cs
New field public List<WeightedAmmoCategory> weightedAmmoCategories
New class WeightedAmmoCategory
Changed ammo selection logic in LoadWeaponWithRandAmmo(ThingWithComps gun)
Longstanding modder request
- Added as new field so that existing defs do not need to be rewritten, function the same as before
Old system was limited in the following ways:
- Can only define one forcedAmmoCategory
- unable to force ammo category for different weapon types, e.g. if a PawnKind can use a shotgun or a rifle, can only force ammo category on one or the other
- unable to force a subset of ammo categories, e.g. a PawnKind that can use any of the three advanced rifle ammos, but not the basic ones
- if not using forcedAmmoCategory, have to rely on the global generateAllowChance of the ammos
New system enables …
=> Implemented new weightedAmmoCategories field for LoadoutPropertiesExtension

ModPatches/Alpha Mechs/Patches/Alpha Mechs/Mods/Biotech/ThingDef_Misc/Weapons.xml
none
enabled the chaining effect on tesla gun, changed the chain projectile damage to smoke, nerfed all the chain stats and damage, to not one shot mechs( still does a lot of damages to mechs that doesn't have high health pool)
discord patch channel
Would be nice if the chain worked, and not one shot every mech
not have chaining effect
=> alpha mech enable the chaining effect

ModPatches/Rimsenal Enhanced Vanilla/Defs/Rimsenal Enhanced Vanilla/Ammo_EnhancedVanilla.xml, ModPatches/Rimsenal Enhanced Vanilla/Defs/Rimsenal Enhanced Vanilla/Ammo_EnhancedVanilla_Lasers.xml, ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Beam_CE.xml, ModPatches/Rimsenal Enhanced Vanilla/Patches/Rimsenal Enhanced Vanilla/Weapons_Dumbfire_CE.xml
Added laser and laserpack ammo set defs.
Barrage gun has been changed to minigun-ish stat profile as per vanilla changes to the gun.
Note that scatter grazer has damage falloff turned off so it can actually fire a beam spread. Effectively shouldn't make much of a difference but looks nicer.
=> Rimsenal Vanilla 1.6

Defs/Ammo/Shell/57x348mmSR.xml
Added 57x348mmSR shell.
AmmoStat Sheet:  
https://docs.google.com/spreadsheets/d/1Y0tK7uN85p9nzm0X3rce8MsiN2-wSWrYBEmmP3GOaCk/edit?gid=746529518#gid=746529518
Adding this real-world ammunition caliber will allow everyone to use items with a unified defName for ammunition, reducing management complexity.
In reality, this round is used by:
57mm guns:   S60, S68, 2A90
Related weapon platforms: 
2S38 (and other vehicles equipped with the AU-220M turret)
ZSU-57-2
Various vehicles armed with the S60 anti-aircraft gun
These are all highly renowned systems.
=> Add 57x348mmSR Shell

LoadFolders.xml, ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Apparel.xml, ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Armor.xml, ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Head.xml, ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_HeavyTurretpack.xml, ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Loadbearing.xml, ModPatches/Misstall's Armor and Uniforms/Patches/Misstall's Armor and Uniforms/Misstall_Turretpack.xml, SupportedThirdPartyMods.md
Patches apparel.
Charge backpack turrets patched with 6x24 and 8x35.
Some apparel has been adjusted to use CE layers since tacvests kind of suck as middle layer option, and to prevent doubling up on gas masks. Industrial armor sets have been patched to work like vanilla vest with stuffability instead of just flat stat.
Leave tacvest type things on middle where they're functionally useless really.
=> Misstall apparel

Biotech/Patches/ThingDefs_Misc/Apparel_BiotechHeadgear.xml, Biotech/Patches/ThingDefs_Misc/Apparel_BiotechVarious.xml
Re-added penalties to Mechlord armor.
Change intergrator headset to work like other headsets layering wise.
Mechlord armor in vanilla does the equivalent of smashing 10 levels of melee and shooting off of the user to compensate for the fact that it provides such a significant number of additional mech control slots + acceptable armor at the time.
There's not really any apparent reason why it shouldn't do the same in CE.
Specific scaling is so that the full set causes the combatant to lose roughly 10 levels worth of shooting and melee hit capacity.
Change specifics of the offsets or leave as is.
=> Re-add Nerfs and change inheritance/layers

Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs
- Disallows weapons that don't have a magazine from benefiting from Subsequent Shot system.
- As per Serina's request
https://discord.com/channels/278818534069501953/303988654492090370/1397901456513695795
- Weapons that require you to fiddle with something after each shot should not reacquire targets fast.
- Not do it, i don't particularly care, responding to serina's complaint
=> No subsequent shots bonus for weapons without magazines

Source/CombatExtended/Harmony/Compatibility/Harmony_WeaponProficiency.cs
Weapon proficiency C# patch to patch in CE verbs on their end
move the old C# patch to /Harmony
no more compat project
- Closes #[#4109]
Learnt that I didn't need to make a compat project to patch it
not fix it?
=> Weapon proficiency C# patch w/o new project

Source/CombatExtended/CombatExtended/Loadouts/Loadout.cs
- Adds null check for loadout slots
- If a thingDef is removed between save and the next load of the save, it will generate a null def. Mainly due to users changing/removing mods between saves
- Null def in the save will cause the loadout dialog to self destruct
- Removes the slot if both thingDef and genericDef are null on a slot during loading process
- Adding null checks in the dialog box would not prevent the the continue saving of the slots with null things
- Send users who modify lists during play to the phantom zone
=> Loadout PostExpose Null Check

Source/CombatExtended/CombatExtended/SuppressionUtility.cs
- Re-introduces the behaviour of throwing smokes at allies.
- In 1.4, CE had code that made npcs throw smoke at their suppressed allies. In 1.5 migration period, it started throwing NREs and got temporarily disabled. I fixed it up, turns out NREs were caused by allied pawns being null - from becoming dead or other reasons. Most noticeably, they happened when a rocket exploded in a middle of a swarm - someone is guaranteed to be dead and others heavily suppressed.
- To test this, go into `Royalty\Patches\PawnKindDefs_Royalty\PawnKinds_Royalty.xml`, set Cataphract's chance to carry smokes to 1.0, spawn an empire raid and shoot 7.62x54 AP - enough to suppress everyone …
=> Fix and restore ally smoke throwing

Source/CombatExtended/CombatExtended/Comps/CompTacticalManager.cs
- adds a null check in tactical manager
- Closes #4076
- [Discussion](https://discord.com/channels/278818534069501953/324222101550661663/1402633872742809621)
- Caused a game breaking bug, making pawns stand still in combat unresponsively
- Difficult to reproduce, basically you have to spawn a 10k vs 10k raid with humans and just wait for it to happen. I managed to reproduce it with only CE and dlcs, have a save where it often happens that i can share if needed. While i'm not 100% sure why and when it happens, this fix seems to stop errors from occurring in the test case i have.
Describe alternative implementations you …
=> fix pawns jobdriver freezing due to jobs being null

Building.md
- add markdown explanation for Visual Studio 
- check the following markdown
- <https://github.com/choi4624/CombatExtended/blob/250805-Building-instruction-for-VS/Building.md> 
- Myself
- I'm able to find why my project is not build. And check package manager setting is something wrong in my VS.
- Actually, I'm not using C# with package manager So I'm not configured like that. 
- Is it not default setting in VS installed? Project doesn't configure link nuget package (unlike spring)
- May be Skilled C# programmer or Rimworld modder don't require that 
- My Native language is not English so Something wired explanation is exist. 
=> Building Instruction for VS 2022. Related Nuget package. 

Source/CombatExtended.sln
- required after #4149 
SOS2 is not updated for 1.6, and just broke when VF updated. Turn it off for now.
=> disable sos2

Source/CombatExtended/CombatExtended/CollisionVertical.cs
- A naive implementation of height offsets for pawns flying in-map (birds flying away from the map appear to no longer be spawned)
- Currently just adds 0.5 to the height, with light easing using the numbers from the flight tracker.
- Probably best to not give it too large of a bonus, since it might make projectile visuals look wrong.
- Use a separate value from the trench height offset.
=> Flying pawn height offsets, again

Source/CombatExtended/CombatExtended/Comps/CompAmmoExploder.cs, Source/CombatExtended/CombatExtended/Comps/CompExplosiveCE.cs, Source/CombatExtended/CombatExtended/Comps/CompProperties_ExplosiveCE.cs, Source/CombatExtended/CombatExtended/ExplosionCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs, Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_BunkerBuster.cs
- Added 1.6 code to handle new postExplosionSpawnSingleThingDef and preExplosionSpawnThingDef fields in explosions
- 1.6 added it
- Use antimatter IED trap for testing - it will start spawning a crater from its XML with this pr
- Reject technology
=> Fix post and pre single thing spawning

Source/CombatExtended/CombatExtended/Comps/CompFragments.cs
- Explosions with default vertical angles will now get the min angle shifted downwards, if the explosion occured at height bigger than 0.1 cell. At height of 1 cell (wall's max height), frag angles will become from -30 to 5 degrees, instead of from 0.5 to 5 degrees. Calculated via formula `height * -30`.
- Contributes towards #4180
- RPG-7 frags fly over pawns if the rocket hits a wall.
- Increase frag count to accomodate for increased dispersion?
- Different max value?
=> Shift frags downwards for explosions at big heights

Defs/Ammo/Rocket/50mmRocket.xml, Defs/Ammo/Rocket/57mmS5Rocket.xml, Defs/Ammo/Shell/152mmHowitzer.xml
- Fix the 152mm incendiary detonate projectile. Leaving it as the 155mm was almost certainly just a typo.
- Adjust bombardment damage value of the 57mm S-6 rockets.
- Prior values were too high, giving the rocket (~1.2 kg warhead) more bombardment damage than the 155mm HE (~10 kg filler).
- Adjusted the 50mm rocket along similar lines.
- Typo.
- Less boom should mean less boom.
- Suffer.
=> Misc. Shelling Tweaks

LoadFolders.xml, ModPatches/The REAL flamberg/Patches/The REAL flamberg/MeleeUltratechFlamberge.xml, ModPatches/The REAL flamberg/Patches/The REAL flamberg/MeleeUltratechFlambergeBladelink.xml, SupportedThirdPartyMods.md
support for https://steamcommunity.com/sharedfiles/filedetails/?id=2343072589
Patched 1 melee weapon and its bladelink version.
As per the original mod's description, this is supposed to be a larger version of the vanilla plasmasword.
I could not find the weapon in the dev spawn tool and I have no idea why. So... not really that well tested.
Since I have the same problem without CE, I reported to the main mod.
=> support for The REAL flamberg

LoadFolders.xml, ModPatches/Rimsenal Core/Defs/Rimsenal Core/Ammo_GD.xml, ModPatches/Rimsenal Core/Defs/Rimsenal Core/Ammo_GD_Mauler.xml, ModPatches/Rimsenal Core/Patches/Rimsenal Core/Apparel_RS_CE.xml, ModPatches/Rimsenal Core/Patches/Rimsenal Core/Weapons_GD_CE.xml, ModPatches/Rimsenal Xenotype Pack - Zohar/Patches/Rimsenal Xenotype Pack - Zohar/Weapons_Zohar_CE.xml, SupportedThirdPartyMods.md
Patch for Rimsenal Xenotype Pack - Zohar
New ammo types and set defs for rimsenal core, as the zohar mod gun requires rimsenal core to load in the first place, and all assets bar the gun itself are included in core pack too.
GD Modular weapons have been standardized to a new GD 6.6mm caseless ammo type. Ammo count generally reduced across the board and the significant difference in properties means the recoil's shot way up but that's what happens when you have a featherweight carbine.
Also buffed the nomad helmet since it has +2 aiming accuracy in vanilla, so brought it up a bit closer to gunlink performace including handling offset.
Mauler is a high damage suppressed gun. It's 17 damage in vanilla which is quite a lot, so it's been given effectively a round simmilar to 12.7x55. …
=> Rimsenal GD stuff

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_Bursting.cs
- Sometimes bursting projectiles get destroyed at the same tick as their timer runs out. This makes destroyed projectile try to impact and throw a harmless red error.
- Easy to replicate by using flamethrower with this mod, as it makes flame projectiles airburst and they sometimes hit ground:
https://steamcommunity.com/sharedfiles/filedetails/?id=2929493288&tscn=1747113855
- Clean up red errors
- Check for null `Map` instead of `Destroyed`
only dev mode testing
=> Fix bursting projectiles trying to impact after being destroyed

Source/CombatExtended/CombatExtended/Comps/HediffComp_InfecterCE.cs
- Ce's applies different infection chances for wounds tended outside. When tending outside, room used to be `null`. Now they're not null, as it returns an outside region instead. So, we use an `isOutsideForWork` property instead of only checking for null
- reported by Glub on discord 
https://discord.com/channels/278818534069501953/278818534069501953/1411673056644169768
- Tending in this situation counts as being in a room when debugging:
room == null returns false
- Betray NIA's vision
Tested the following …
=> Fix outside tending being counted as inside for infections

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
- Undoes caching added in #3820 specifically for overhead projectiles, since their texture gets terribly squished because of it. I am not fully familiar with the reasons of why global projectile drawing got changed for CIWS, so input from Perkins or Shashlichnik would be appreciated.
- Closes #4173 
- Partially undoes #3820 
- Mortar shells are difficult to see like this.
- Adding a check for flyOverhead allows CIWS bullets to keep their squishing, but leaves mortar shells using the old behaviour
- Move the caching behaviour to …
=> Dont cache rotation for overhead projectiles

ModPatches/Communitable Diseases/Patches/Communitable Diseases/Communitable_Disease_Apparel.xml
- Removed patch for `Dust Mask` for Communicable Diseases mod, as it removed the item in its 1.6 update.
- Mod link: https://steamcommunity.com/sharedfiles/filedetails/?id=3263015203
- Removes red errors on startup
=> Communicable diseases 1.6 patch fix

ModPatches/Rimefeller/Patches/Rimefeller/Napalm_Tweaks.xml
No longer needed, was removed from main mod.
Removed outdated patch operation
Fixes a red error on Startup. Vanilla Fishing Expanded - Fishing Treasure Addon no longer has the Rimefeller patch on their end for 1.6.
=> Vanilla Fishing Removed Patch fix

ModPatches/Reinforced Mechanoid 2/Patches/Reinforced Mechanoid 2/ThingDefs_Misc/RM_PlasmaWeaponry.xml
Updated the path for one of the grenades
Modified the xpath for VWE_Apparel_GrenadePlasmaImmolator
Fixes a red error on game startup.
- Additional use for animals
- Anachronistic
- Breaks realism theme
=> Fix for RM2-VWE Subpatch

Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE.cs
DamageInfo now registers its inteded target
- Closes #4247 
Of course, considering how easy one can exploit this feature with ce, we can implement a much more complex system, but...
=> Fix DamageInfo Missing Intended Target
